### ISSUE TITLE
[RFE] Series metadata

### ISSUE THREAD

**Issue by M4rtinK** [dteviot/WebToEpub#1]
I think it would be nice if the extension could include Series metadata in the generated epub file. It should be quite easy to parse series name from the URL (at least on Baka Tsuki) and the series metadata is pretty useful for ebook library management in Calibre and other such tools. Some e-book reading devices can even make use of the series metadata to automatically assign books into collections (at least the Kobo Auro H2O when managed with Calibre).

Surprisingly I have not been able to find information about how the series metadata should look like in the epub spec (well, I haven't really looked very deeply), but this is how the `ebook-meta` tool provided by Calibre does it:

`ebook-meta foo.epub --series bar_series`

It can also be used by just passing the name of an epub file to inspect epub metadata, including series information. In any case checking how the epub file looks like after being modified by the `ebook-meta` tool might provide insight how series metadata works.

While I can't really help with extension development, I can certainly help with testing of this if needed. :)

**Comment by dteviot** [comment]
http://www.mobileread.com/forums/showthread.php?t=69988
suggests the values are:
<meta name="calibre:series" content="CAC"/>
<meta name="calibre:series_index" content="29"/>

https://github.com/idpf/epub-revision/issues/326
says to use refines.
```xml
<dc:title id="collection">Scott Pilgrim</dc:title>
    <meta refines="#collection" property="title-type">collection</meta>
    <meta refines="#collection" property="group-position">1</meta>
```
But that may be an EPUB 3 feature

**Comment by dteviot** [comment]
@M4rtinK Trunk version now adds the calibre series metadata, if you'd like to give it a try and see how it goes.

**Comment by M4rtinK** [comment]
>@M4rtinK Trunk version now adds the calibre series metadata, if you'd like to give it a try and see how it goes.

Thanks! Seems to be working fine - I've created a few epubs using the trunk version of the extension and the series information & book number are displayed correctly in Calibre. The series -> collection feature on my Calibre-managed Kobo also works correctly with the files. :)

**Comment by dteviot** [comment]
Closing as reported as working and merged to trunk.
