### ISSUE TITLE
Baka-Tsuki parser not grabbing correctly

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#100]
Baka-Tsuki parser has an issue with ["Blood Sign Volume 5"](https://www.baka-tsuki.org/project/index.php?title=The_Unexplored_Summon_Blood_Sign:Volume5).

Basically the last ExperimentalTabMode branch (0.0.0.25) doesn't grab the **"Epilogue"** while on Chromium, but the regular Firefox release (0.0.0.24) does grab it correctly.

Basically it's kept just after the **"Afterwords"**, but it doesn't get its entry in the TOC grabbing it from Chromium but it's perfect on Firefox (has its TOC entry, its separate xhmtl and "Epilogue" title.

**Comment by toshiya44** [comment]
Not a bug. It's a cache issue on Baka-Tsuki's side. 

Some changes were made to the BloodSign pages recently (adding titles and such). Clear your browser's cache force refresh the page.

**Comment by typhoon71** [comment]
mmm

I did notice Baka-Tsuki splitted the "Epilogue" from the "Afterwords", so when I got the issue I did I clear Chromium cache... that's why I posted this.

If it's not a webtoepub issue it's good, but I'd like to understand why it happened.

**Comment by dteviot** [comment]
@typhoon71 
I am unable to reproduce the problem you describe with Chrome 55.0.2883.87

**Comment by typhoon71** [comment]
Then I guess it was a cache issue like toshiya44 said.
Probably more on the website side cache than on the browser side.

I couldn't test myself on more than a PC so I couldn't verify this one well.
I'm closing this, put an "invalid" tag or something since "we" determined that it's not a bug.
