### ISSUE TITLE
Please update the parser for [https://knoxt.space/] so that the footnotes aren't written in the chapter text as well :)

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1002]
Hello! 

My request is a little similar to #934. The footnotes for the site [https://knoxt.space/] are already generated by WebToEpub at the **bottom of the chapters**. But for some reason, those said footnotes are also generated **WITHIN the chapter text itself** as well. They **appear right next to the number which is linked to the end footnote** (but the number is perfectly fine as is). Since the footnote is already generated at the bottom of chapter, is there some way to make it so that the footnotes are **NOT generated within the paragraphs** as well lest it be confused with the actual chapter text itself?

Please refer to the below image for reference:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/223b2594-382f-4522-b2a4-e3ec37669772)

- The text underlined in **red** is the footnote that already appears at the bottom of the chapter and **shouldn't be there**.
- The text underlined in **purple** is the ACTUAL chapter text of this novel that comes before the footnote number.
- The number underlined in **pink** is the number which shows which footnote it's referring to.

Example TOC:
https://knoxt.space/can-you-take-me-away/

Example Chapter with Footnotes:
https://knoxt.space/can-you-take-me-away-chapter-2/

Thank you very much for your time, consideration and much appreciated efforts! :D And as always, apologies for any inconvenience or hassles my many requests may have caused.

**Comment by dteviot** [comment]
@vanessabluellie 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://knoxt.space/can-you-take-me-away-chapter-2/

For my notes: 30 minutes work

**Comment by vanessabluellie** [comment]
Thank you!!! It works perfectly :D!!

**Comment by dteviot** [comment]
Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
