### ISSUE TITLE
The site [https://tamagotl.com/] also has the exact same problem with placing footnotes in the chapter text as well...

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1003]
Hello!

Really sorry for a consecutive request, but the site [https://tamagotl.com/] also has the exact same footnote problem as #1002. Meaning that the footnotes are already generated at the bottom of the chapter, but are also generated **WITHIN the chapter text itself** as well. They **appear right next to the number which is linked to the end footnote** (but the number is perfectly fine as is). Since the footnote is already generated at the bottom of chapter, is there some way to make it so that the footnotes are **NOT generated within the paragraphs** as well lest it be confused with the actual chapter text itself?

Please refer to the below image for reference:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/7d31520d-0772-4a86-8a00-0cf9a50dff75)

- The text underlined in **red** is the footnote that already appears at the bottom of the chapter and **shouldn't be there**.
- The text underlined in **purple** is the ACTUAL chapter text of this novel that comes before the footnote number.
- The number underlined in **pink** is the number which shows which footnote it's referring to.

Example TOC:
https://tamagotl.com/series/tvvsh/

Example Chapter with Footnotes:
https://tamagotl.com/tvvsh-chapter-65/

Apologies for the copy and paste with most of this issue... And thank you for your help!! :D

**Comment by dteviot** [comment]
@vanessabluellie 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://tamagotl.com/tvvsh-chapter-65/

For my notes: 15 minutes work

**Comment by vanessabluellie** [comment]
Thank kyuuu!!! It works perfectly :)!!!!

**Comment by dteviot** [comment]
Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
