### ISSUE TITLE
Please add site https://www.wuxiap.com/

### ISSUE THREAD

**Issue by joecheung1** [dteviot/WebToEpub#1004]
What used to be https://www.readwn.com/ now redirects to https://www.wuxiap.com/, so the existing parser no longer works. The site layout is otherwise completely the same, so hopefully it should be an easy fix?

**Comment by dteviot** [comment]
@joecheung1 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiap.com/novel/im-really-a-villain.html

For my notes: 12 minutes work

**Comment by joecheung1** [comment]
Thanks for the quick response and it's working perfectly.

**Comment by dteviot** [comment]
@joecheung1 
Reopen, so I know to notify you when version in Chrome and Mozilla stores is updated.

**Comment by dteviot** [comment]
@joecheung1 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
