### ISSUE TITLE
Please add site https://kaystls.site/

### ISSUE THREAD

**Issue by namecantbebl0nk** [dteviot/WebToEpub#1006]
TOC: https://kaystls.site/reincarnated-in-the-mastermind-of-the-story-evolving-magic-swords-and-game-knowledge-to-defeat-everything/

I don't know about coding. I tried using the default parser, but the elements on the site are so confusing, unlike the example shown in the default parser tutorial.

Update: After trying to figure out how elements work—which I still really don't—these are the settings that work best. There are some elements that I can't get rid of or that removing them will affect other elements that I don't really want to remove.

CSS selector for element holding content to put into EPUB:	 div.primary
CSS selector for element(s) to remove: div.wp-block-cover, div.comments-area

**Comment by dteviot** [comment]
@namecantbebl0nk 

Yup, it's a soup.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kaystls.site/reincarnated-in-the-mastermind-of-the-story-evolving-magic-swords-and-game-knowledge-to-defeat-everything/, prolog and V4 C31
* https://kaystls.site/the-reincarnation-of-the-strongest-exorcist-in-another-world-these-monsters-are-too-weak-compared-to-my-monsters/, chapter 10

For my notes: 45 minutes work

**Comment by dteviot** [comment]
@namecantbebl0nk 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
