### ISSUE TITLE
Please add site https://hp.adult-fanfiction.org/

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#1008]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://hp.adult-fanfiction.org/story.php?no=600095379&chapter=1

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
I am not sure how to do it for that site.

**Comment by dteviot** [comment]
@kolbdog3333 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://hp.adult-fanfiction.org/story.php?no=600100015, chapter 1
* https://hp.adult-fanfiction.org/story.php?no=600095379&chapter=1

For my notes: 36 minutes work

**Comment by dteviot** [comment]
@kolbdog3333 
Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
