### ISSUE TITLE
Please add site https://www.taadd.com/

### ISSUE THREAD

**Issue by JoshOm21** [dteviot/WebToEpub#1009]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
- https://www.taadd.com/book/I%27ll+Take+the+Dukedom+From+Today.html

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
- No. I'm using mobile.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove
- N/A

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
- No I didn't. I don't have that skill.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
- Sadly, I don't know anyone.

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
- N/A

**Comment by dteviot** [comment]
@JoshOm21 

Going to say no to this one.  Too much effort.

The table of contents entries go to different sites, with different layouts.
e.g. https://www.taadd.com/book/I%27ll+Take+the+Dukedom+From+Today.html goes to www.taadd.com, where the chapters have multiple pages, one image per page.
https://www.taadd.com/book/Renai+Daikou.html goes to  https://www.glanceoflife.com/, which has up to 10 images per page.

For my notes: 13 minutes
