### ISSUE TITLE
Please add site https://octopii.co

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#1011]
Hello

is it possible to add this website : octopii.co

Here is an example : https://octopii.co/novel/27-the-ultimate-evolutio

Thanks a lot for your works :)

**Comment by dteviot** [comment]
@Flwk 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://octopii.co/novel/27-the-ultimate-evolutio chapters 1 &amp; 1460
* https://octopii.co/novel/5-the-king-of-hells-genius-pampered-wife chapters 1 &amp; 8

For my notes: 37 minutes work
