### ISSUE TITLE
Epubeditor extention kiwibroser

### ISSUE THREAD

**Issue by Veaxale** [dteviot/WebToEpub#1013]
Can u make epubeditor extension more compatible with kiwibrowser for mobile user.
Because the browser cant unpack the zip file.
And the extention not loaded at all

**Comment by gamebeaker** [comment]
@Veaxale please provide an example what your problem is. I can't understand your problem. 
What zip file should be unpacked? 
Where is that a function from WebToEpub?

**Comment by Veaxale** [comment]
No its a function from epubeditor.zip wich i downloaded in the gdrive.

**Comment by gamebeaker** [comment]
@Veaxale Than create a issue there [https://github.com/dteviot/EpubEditor/issues](https://github.com/dteviot/EpubEditor/issues) not here. Here is WebToEpub plugin you mean the EpubEditor these are different programs.

**Comment by Veaxale** [comment]
Ohh okay
