### ISSUE TITLE
Default option body not shown anything

### ISSUE THREAD

**Issue by Veaxale** [dteviot/WebToEpub#1014]
In one of the site i want to fetch with default option.
With  Body or div. Etc. its not show anything or its just something like this.

(function(){var js = "window['__CF$cv$params']={r:'7e7db5e4ea38c336',m:'_YxrvpUewsERnlyBgHU8_zTPbZSFsTY86CaYkMmjDxA-1689546845-0-AUP2kaVq9anjRrXj9gnOP8+oy13hFNpZ++IL4kPThe0y'};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/invisible.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();

Is it because the css display:block in that site?
Well the developer view with kiwibrowser work tho.

**Comment by Veaxale** [comment]
Mm i think i forgot to change the issue from the suggestion feature to a different one

**Comment by gamebeaker** [comment]
@Veaxale Hi i need more information to reproduce the error.
What is the Website? (link to story)
What is your device?
What is your Browser?

**Comment by Veaxale** [comment]
I cant give u the link as its seems one of the blocked one from ......parser.js
Thats why i deleted the file and choose a deault option instead.
I can give u the link through email if u want tho.

**Comment by dteviot** [comment]
@Veaxale 
Closing.  Without URL to story, there is nothing we can do to help.
