### ISSUE TITLE
Please add site https://goodnovela.com/book_info/married-at-first-sight-by-gu-lingfei-online-free/

### ISSUE THREAD

**Issue by Blakemontefalco** [dteviot/WebToEpub#1018]
https://goodnovela.com/book_info/married-at-first-sight-by-gu-lingfei-online-free/

**Comment by dteviot** [comment]
@Blakemontefalco 
Please put site name in title of issue when you create it.

**Comment by dteviot** [comment]
@Blakemontefalco 

Site is working for me.  (It's a Madara formatted site.)
Tested with: https://goodnovela.com/book_info/married-at-first-sight-by-gu-lingfei-online-free/, chapters 1 &amp; 6

For my notes: 5 minutes work.

**Comment by dteviot** [comment]
@Blakemontefalco 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
