### ISSUE TITLE
Please add site https://novelebook.net

### ISSUE THREAD

**Issue by Blakemontefalco** [dteviot/WebToEpub#1019]
https://novelebook.net/novelebook/married-at-first-sight

**Comment by dteviot** [comment]
@Blakemontefalco 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelebook.net/novelebook/married-at-first-sight, chapters 1 &amp; 2124

For my notes: 7 minutes work  (Easy one, same format as Novelfull.)
