### ISSUE TITLE
[Improvement] remove epub .extension from filename tab

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#102]
Since the ebook is an epub the .epub extension is redundant in the filename, one could just put the name and the addon should add the .epub itself.

I propose this because I noticed that if you -remove- the extension, i.e. you write only the filename without .epub at the end, you'll get a .zip file; this makes some sense but I think it should not happen.

After all usually one doesn't have to add the file extension, expecially if the filetype is only one.

**Comment by dteviot** [comment]
@typhoon71
Checked into Experimental Tab Mode branch.

**Comment by typhoon71** [comment]
Thanks, works perfectly.
