### ISSUE TITLE
Please add site https://www.wuxiar.com/

### ISSUE THREAD

**Issue by gille90** [dteviot/WebToEpub#1022]
yeah, knows the bare basics of coding but just added just add `parserFactory.register("wuxiar.com", () => new ReadwnParser());` in the ReadwnParser.js file of your downloaded 0.0.0.155 beta version and loaded it back in and it worked. 👍  Just wanted to tell you it so you can test it / add it.

**Comment by dteviot** [comment]
@gille90 

Thanks. Done.
For my notes:  5 minutes work

**Comment by dteviot** [comment]
@gille90 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
