### ISSUE TITLE
Please add site https://m.xklxsw.com/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#1023]
pls add https://m.xklxsw.com/ thank you

**Comment by dteviot** [comment]
@Finks82 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://m.xklxsw.net/book/119080/ chapter 1 &amp; 2  (Note, table of contents on this page seems to be messed up)
* https://m.xklxsw.net/book/312525/ 

For my notes: 35 minutes work
