### ISSUE TITLE
Please add site https://www.pandasnovel.com/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#1024]
panda-novel.com has started transitioning to a new name.
Please add it to the parser. But please keep the old parser, since it still works fine.

Novel url: 
https://www.pandasnovel.com/details/goddess-helps-me-simulate-cultivation(EN)-1746

**Comment by dteviot** [comment]
@budikesuma 
Unfortunately, doesn't work.  They've changed API to get chapters, adding a query parameter, e.g.
> https://www.pandasnovel.com/api/book/chapters/2056/1?_=1690582379463

which is not obvious how to obtain.

**Comment by SirRomey** [comment]
Oh, I did not see this issue before I made a PR. It seems to be working fine for me on my local build. Just added the url like you'd normally do. #1034 

It gives you 403 once or twice before it takes you to the WebToEpub error which has the captcha link. Once you get the captcha done and click on "Retry", it loads all the chapters fine.

At least that was my observation. There could be stuff not working in the back that I'm not aware of.

**Comment by dteviot** [comment]
@SirRomey 

My bad.  I wasn't able to get the captcha to turn up, so assumed the call had changed.
If it's working for you, I'll just add the URL.

No new test build, the existing ones already have the URL from when I was trying to make it work.

For my notes, 5 minutes work.

**Comment by SirRomey** [comment]
Do I leave my PR open or shall I close it? The url doesn't seem to be on any of the branches on GitHub.

**Comment by SirRomey** [comment]
Didn't see the mentioned commit, my bad. Will close my PR.

**Comment by dteviot** [comment]
@SirRomey 

Thanks.  Sorry for late reply.  Just aquired "No Man's Sky", and it's sucking up all my time.

**Comment by dteviot** [comment]
@budikesuma @SirRomey 
Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
