### ISSUE TITLE
Is it possible to generate the Table of Contents into the epub for site layouts like [https://knoxt.space/]?

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#1025]
Hello!

Apologies for another request, but I was wondering if it is possible to **generate the Table of Contents into the EPUB** for sites that have a **more blocky TOC layout** like "https://knoxt.space/" or maybe "https://travistranslations.com/". Regarding the KNOXT site, is it somehow doable to maybe also generate just the **first two columns of the TOC** into the epub as well, so just the headings for "**Vol/Ch**" + "**Chapter Title**", but **NOT** the third column which is the "Release Date". If these two columns are able to be generated into the EPUB, is it possible to perhaps have each respective row written accordingly with each link? Here's a very poor example of how it can be encoded in the epub just for general purpose:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/bc713f47-b16c-4a6f-a8a4-7f7be2425d83)

Please also refer to the below image that has been marked for reference about the Table of Contents on the KNOXT site itself! :)

![image](https://github.com/dteviot/WebToEpub/assets/55352222/dcc07adf-d48b-499b-a3bd-fb3d77114206)

I apologise for any inconveniences my request has caused and hope all has been going well with you! :D Thank you very much for all your help and effort as always! It's always been much appreciated!

**Comment by dteviot** [comment]
@vanessabluellie 
Seems to work for https://travistranslations.com/novel/91120/those-years-when-i-was-a-dalao/.   What exactly is the problem?

Re:
>Regarding the KNOXT site, is it somehow doable to maybe also generate just the first two columns of the TOC into the epub as well

I think what you're asking is "Can each chapter's use the value from the Table of Contents as the page's Title."
The answer is: not without more effort than I'm willing to put in.  
WebToEpub is open source, so you're welcome to do it yourself.  
Although given my lack of success at tying to teach you how to use the EpubEditor, I suspect you're not a developer.

**Comment by vanessabluellie** [comment]
Regarding TravisTranslations, I've tried and the Table of Contents doesn't generate into the epub file for any novel.

But about KnoxT, that's fine then ahah. No, I'm not a developer, so I wouldn't be able to wrap my head around it. But thank you for your fast reply.

**Comment by dteviot** [comment]
@vanessabluellie 
Please clarify what you mean by "generate the Table of Contents into the EPUB"

**Comment by vanessabluellie** [comment]
I mean to generate the list of chapters into the first xhtml file of the EPUB, provided that the Advanced Option "**Add Page with Chapters to Chapters List**" in the WebToEpub extension is selected.

![image](https://github.com/dteviot/WebToEpub/assets/55352222/465d4c7c-1c7b-4030-b6d3-b2550ea44b44)

Given the layout of sites like KnoxT and Travis Translations, the Table of Contents wasn't able to be generated into the EPUB, despite this option being checked. So I was wondering if there was a workaround that could be applied to generate the TOC chapters list from sites like these. If this is not doable or too much effort on your part, I'd be much obliged to re-close my request ahah. Thank you for your time.

**Comment by dteviot** [comment]
@vanessabluellie 

Apologies for late response.  As I've said previously.  Serious gaming addiction.
Anyway, I'm sorry, but the news isn't good.

The Javascript/Tabbed nature of the TravisTranslations means it really doesn't work well in an epub. So, no for that.
Knoxt, doesn't work well either, you only get the Synopsis.  Which WebToEpub puts on the information page anyway.

For my notes: 28 minutes work

**Comment by vanessabluellie** [comment]
@dteviot

No problem about the delay, real life commitments matter first :)

And no need to apologise, it didn't really seem that doable, just thought I'd ask~ But thank you regardless.
