### ISSUE TITLE
https://ranobes.top/ has broken index

### ISSUE THREAD

**Issue by ad4d** [dteviot/WebToEpub#1026]
When compiling a book from https://ranobes.top You can only add last 25 chapters.

**Comment by dteviot** [comment]
@ad4d 
I think I've seen similar issues in the past.  IIRC, problem was, WebToEpub was opened on the wrong sort of web page.  e.g. Table of  Chapters, instead of the Title page.

I just tried https://ranobes.top/novels/396653-the-devils-sleeping-beauty-v71134.html, and it seems to work fine.
If this isn't your problem, please provide URL that isn't working.

For my notes: 5 minutes.

**Comment by upsych** [comment]
Packing from url that brings me only 25 chapters. But it has over 200+ chapters. I tried multiple options, nothing seems to work. I am using firefox if it helps.

**Comment by ad4d** [comment]
Packing from url that brings me only 25 chapters. But it has over 200+ chapters. I tried multiple options, nothing seems to work. I am using firefox if it helps.

**Comment by dteviot** [comment]
@ad4d 
When you open WebToEpub, how many chapters does it show?
Is the problem that while all chapters are shown, only the first 25 can be fetched?

**Comment by dteviot** [comment]
@ad4d 

Apologies.  WebToEpub was getting the wrong URLs for every chapter after the first 25.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* anobes.top/novels/396653-the-devils-sleeping-beauty-v71134.html,  Chapters 1, 207

For my notes: 18 minutes work

**Comment by ad4d** [comment]
@dteviot 

Thank you for your kindness. I am deeply honored that you took time from your life to solve my issue. The issue is still persisting on firefox. But I tried the new package on chromium and worked perfectly. I am happy, for that I am grateful.

**Comment by srockw** [comment]
Currently the issue remains on Firefox, and it only works in Google Chrome (not Chromium as @ad4d mentioned) from my experience.

**Comment by dteviot** [comment]
@ad4d @srockw 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.

I just tried the Firefox (desktop) version against https://ranobes.top/novels/396653-the-devils-sleeping-beauty-v71134.html and it seems to be working.
