### ISSUE TITLE
Please add site https://www.foxteller.com/

### ISSUE THREAD

**Issue by upsych** [dteviot/WebToEpub#1027]
https://www.foxteller.com/ is a niche translation site. I would be grateful if you could add it.

**Comment by dteviot** [comment]
@upsych 

My records say support for this site was added in 2020-09-20.
I just tried https://www.foxteller.com/novel/58/to-deprive-a-deprived-person, chapters 1 &amp; 327 on desktop Chrome.
Appears to work fine.
What's the problem?

**Comment by dteviot** [comment]
Closing due to lack of response
