### ISSUE TITLE
Please add site en.novelxo.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#1028]

**Comment by dteviot** [comment]
Duplicate of https://github.com/dteviot/WebToEpub/issues/1021

**Comment by dteviot** [comment]
@AngelBurn 
Duplicate of https://github.com/dteviot/WebToEpub/issues/1001. 
Unfortunately, site is scrambling and encoding the text to prevent things like WebToEpub working.
I can't help you.
