### ISSUE TITLE
Option to show advanced options by default

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#103]
I'd like to ask for the possibility to show the advanced options by default.

I suppose them being hidden by default is good, but someone wanting to fiddle around with those often, expecially with the parser selector, may want to click less. ;)

Would this be possible?

**Comment by dteviot** [comment]
Added checkbox "Advanced Options Open by Default" to "Advanced Options".
Checked into Experimental Tab Mode branch.
Warning: I completely rewrote the code for loading/saving/applying Advanced Options. 
As far as I can tell, that area is all working. But, you may want to check it for yourself.

**Comment by typhoon71** [comment]
Thanks. 
I tested it and the new code works fine: new options are remembered and applyed correctly.
