### ISSUE TITLE
Please add site https://bookalb.com/series/darkness-mate-cheated-versus-fated-by-victory-done/

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#1031]
If you are free only, i know that i requested it in the past but it seems i cant download because of updated site.

thank you so much!

**Comment by dteviot** [comment]
@AngelBurn 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://bookalb.com/series/darkness-mate-cheated-versus-fated-by-victory-done/, chapters 1 &amp; 264

Note, I am unable (without significant effort) to do anything about this crap that's in the chapters.  (It's there if you view the page normally in a browser, so... WTF???)
> 0.00% 
16:49 
288 Vouchers 

For my notes: 
* 37 minutes work
* Interesting, seems to have same underlying structure as noblemtl.com but looks different.

**Comment by dteviot** [comment]
@AngelBurn 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
