### ISSUE TITLE
Please add site https://m.metanovel.org/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#1036]
pls add https://m.metanovel.org/ 

Q: any fix for this kind of site [1 chapter cut into 3 page]  without parser ??

**Comment by dteviot** [comment]
@Finks82 

> Q: any fix for this kind of site [1 chapter cut into 3 page] without parser ??

No.   I don't know how to automatically detect multiple pages, as every site does something a bit different.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://m.metanovel.org/book/360290, chapters 1 &amp; 2

Note, as I can't read Chinese, I'm not 100% sure how well it works.

For my notes: 65 minutes work
