### ISSUE TITLE
Please add site https://shubaowb.com/

### ISSUE THREAD

**Issue by bonnetchuu** [dteviot/WebToEpub#1038]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://shubaowb.com/novel/290463.html**

On this site, Webtoepub only grabs the links on the current page. The Table of Contents is split into a drop-down list and divided into groups of fifty chapters. Webtoepub only grabbed the chapter links on the current page which was the first (or latter) 50 chapters. If possible, please make it so that, regardless of which page of the TOC a user is on, Webtoepub will automatically be able to generate all chapter links from a novel page. Thanks.

This is what the drop-down TOC looks like:

![image](https://github.com/dteviot/WebToEpub/assets/141732398/2d94a46c-9b49-41fa-9ba1-e254ec70ac2e)

If possible, can you also make it so that the parser for this site doesn't grab anything AFTER the "chapter content" tags, like up to the "back" & "next chapter" buttons? So like the below image examples:

![image](https://github.com/dteviot/WebToEpub/assets/141732398/502d48f0-1db1-4e0c-8ee9-cdc44b394488)

![image](https://github.com/dteviot/WebToEpub/assets/141732398/05ad9a8e-639f-4f6c-959a-7e8466adc27f)

So nothing past the two red lines (only capturing the chapter content itself into the epub from the "div chapter content" tags). Thank you.

**Comment by bonnetchuu** [comment]
Hello! I'm not too sure if it's okay to bring up an old request? I didn't want to open a duplicate with the same details haha. If it's not too much trouble, I'd really appreciate this source being supported by Webtoepub! :) Thank you for all your time and effort <3

P.S. And I only just saw that you had already fixed a different request of mine about updating a parser, apologies for the late response about that, I'm quite clueless with how to navigate github :'). Nevertheless, thank you very much, it worked splendidly!

**Comment by dteviot** [comment]
@bonnetchuu 
> Hello! I'm not too sure if it's okay to bring up an old request? I didn't want to open a duplicate with the same details haha. If it's not too much trouble, I'd really appreciate this source being supported by Webtoepub!

Are you asking again for https://shubaowb.com?  In which case, you're welcome to ask again, but it won't change the priority.
Basically, my priority is:
1. Broken parsers.
2. New sites, with oldest requests being served first (in general), unless site has something on it I want.

Note, old stuff isn't forgotten, it's just taking me a while to work though it.

**Comment by bonnetchuu** [comment]
@dteviot

> Are you asking again for https://shubaowb.com?

Yes haha, thank you for taking the time to reply. Your efforts are really appreciated, I shall wait for this site support keke :D But thank you for informing me that old requests are not forgotten~

**Comment by dteviot** [comment]
@bonnetchuu 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://shubaowb.com/novel/290463.html, chapters 1 &amp; 2
* https://shubaowb.com/novel/298224.html chapters 1 &amp; 299

Note, I can't read Chinese, so please check carefully.

For my notes: 57 minutes work

**Comment by bonnetchuu** [comment]
Thank you so much!!!!! It works perfectly!!! <3

**Comment by dteviot** [comment]
@bonnetchuu 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
