### ISSUE TITLE
Add Log-in feature

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#104]
@Quaturn
Requested by "A Google User"
> I hope you add log-in feature for http://www.lnmtl.com/ because some novel are restricted to users.

I got the following request.

If I'm very lucky, this can be fixed by setting the credentials property of fetch() to "include".
e.g. this.
```javascript
fetch(url, {  
  credentials: 'include'  
})
```
Any chance you can help?
At minimum, can you give me one of the URLs that requires a logon?
Ideally, if I change the code, can you test, as I don't have an account with lnmtl, and I'd prefer not creating one if I don't have to?
Thanks.

**Comment by dteviot** [comment]
Closing, due to no response from person who originally raised issue.

**Comment by belldandu** [comment]
@dteviot on a side note after checking https://lnmtl.com/chapter/battle-through-the-heavens-chapter-401 it doesnt appear you need to login at all. so yeah leaving closed.
