### ISSUE TITLE
Update Parser For Site https://exiledrebelsscanlations.com/

### ISSUE THREAD

**Issue by bonnetchuu** [dteviot/WebToEpub#1040]
Hello, I would like to request for a specific update regarding the parser for the site "https://exiledrebelsscanlations.com/".

Despite one of the Advanced Options in the Webtoepub extension being selected "**Add Page with Chapters to Chapters List**", Webtoepub can no longer **grab the Table of Contents page** of any novel on this site into the epub. I recall that Webtoepub used to be able to do this, but one of the recent updates to the extension removed this capability from this specific parser.

![image](https://github.com/dteviot/WebToEpub/assets/141732398/8b36d6f4-e1a4-4143-b2ea-0bb91ab1c0b9)

Also, regarding one more thing about this site, when generating the epub, is it possible to not grab the **"dir" attribute of all paragraph + heading tags** and to _also_ **not grab the embedded font attributes in the span tags**. So to basically omit the dir and embed font attributes in the p and span tags, and just grab the text ensconced within the paragraph tags itself (+ the < p > tags). These are written extremely lengthy and make the epub look very cluttered, especially since they're written for literally almost every sentence.

![image](https://github.com/dteviot/WebToEpub/assets/141732398/f2417980-6e62-4307-9d83-0dfe041e9b8a)

Thanks for your time.

**Comment by yuzucitrusx** [comment]
@dteviot 

hi hiiii, i was looking through the open issues before opening a new request and saw that someone else had already requested this fix about the source i was looking to ask about! i didn't wanna open a duplicate request, so is it okay to also make this request via a comment?

**Comment by dteviot** [comment]
@yuzucitrusx 
> so is it okay to also make this request via a comment?

Yes.  Although I'd point out bonnetchuu has made at least 3 requests above, so you might like to be specific about exactly what it is you want.  Although I assume you're asking to have "Add Page with Chapters to Chapters List" fixed.

**Comment by dteviot** [comment]
@bonnetchuu @yuzucitrusx 

Re:  **Add Page with Chapters to Chapters List** not working.  
The situation is, the layout of the Table of Contents page is different to the layout of a typical chapter.  
In particular, the HTML node that holds the wanted content on a chapter isn't there. 
So, I need to add code to find the content node for a ToC page, and have the logic to do this not mess up when page isn't a ToC page.  Then, if there's additional processing needed for chapters, I need to make sure that doesn't mess up either.
So, to support getting a ToC page when it's a different layout to a chapter means (worst case) I have to write two parsers for the site, plus enough logic to distinguish between the two cases.
In general, I'd rather spend my time writing a parser for a completely new site.

That said, it looks like this one's an easy fix.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://exiledrebelsscanlations.com/novels/grandmaster-of-demonic-cultivation/

For my notes: 10 minutes work  (Or 40 if I include writing this rant.)

@bonnetchuu, as regards scrubbing the HTML, that looks like a job for my epub editor tool.  Please go to https://github.com/dteviot/EpubEditor and raise the issue there.  And I'll see about giving you a script to do the cleanup.

FYI. In general, to make it easier to me to track what I've done, and what still needs doing, please create an issue for each separate thing you ask for.  Putting multiple requests in a single issue does NOT make my life easier.

**Comment by dteviot** [comment]
@bonnetchuu 
Actually, looks like I've already done something close to what you want.  Have a look at: https://github.com/dteviot/WebToEpub/issues/964

**Comment by yuzucitrusx** [comment]
@dteviot 

hi hii, thank you, it fixed the toc issue! i also looked at that other issue you referenced for the span tags, but um i got kind of confused when i tried it out with the script in epubeditor... should i open the issue for epubeditor there and maybe ask for a script specifically for these "span style" tags instead?

**Comment by dteviot** [comment]
@yuzucitrusx 
> should i open the issue for epubeditor there and maybe ask for a script specifically for these "span style" tags instead?

Yes, please do so.
