### ISSUE TITLE
Please add site: https://www.wuxiap.com

### ISSUE THREAD

**Issue by MapleTreeForest** [dteviot/WebToEpub#1042]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.wuxiap.com/novel/sailing-exposure-of-nika-luffy-shocked-the-world.html

### Did you try using the Default Parser for the site?  If not, why not?
Yes.
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
Used. Seemingly no problem.
* CSS selector for element holding content to put into EPUB
Used several different ones, .chapter-content looks to be the correct one.
* CSS selector for element holding Title of Chapter
Used.
* CSS selector for element(s) to remove
Fiddled around with settings for quite some time and discovered I know nothing about this.

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
No developer skills.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I can try.

**Comment by dteviot** [comment]
@MapleTreeForest 

This has already been done on the "in development" version of the extension.  It hasn't been published to Firefox or Chrome web stores yet, as there is still work for other sites to be done.  If you'd like to use that version before then:

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
This request duplicates https://github.com/dteviot/WebToEpub/issues/1004
