### ISSUE TITLE
https://secondlifetranslations.com gibberish

### ISSUE THREAD

**Issue by bookimp** [dteviot/WebToEpub#1043]
**Describe the bug**

**To Reproduce**
1. Go to 'https://secondlifetranslations.com/novel/watf/'
2. Download epub
3. Scroll down to 'First chapter'
4. See error/gibberish

**Expected behavior**
No gibberish

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/20101896/01ec3a37-425f-4485-b6a5-f1e22c41d47e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Windows 10 Pro 22H2
 - Browser: Opera GX
 - Version LVL 5 (core: 100.0.4815.82)

**Comment by dteviot** [comment]
@bookimp 

Please see https://github.com/dteviot/WebToEpub/issues/683 for solution

**Comment by dteviot** [comment]
@bookimp 
And to anticipate your next question, here's how to get EpubEditor and start it.

Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8 and download EpubEditor.
Unzip the file and open main.html in Chrome or Firefox.

**Comment by dteviot** [comment]
@bookimp 

Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.
