### ISSUE TITLE
Please add site https://www.69shuba.com

### ISSUE THREAD

**Issue by Alastorwill** [dteviot/WebToEpub#1045]
the source no longer works when you have time I would appreciate if you could fix it

**Comment by dteviot** [comment]
@Alastorwill 

Looks like site was renamed to https://www.69shuba.com

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.69shuba.com/book/40363.htm

For my notes: 8 minutes work

**Comment by dteviot** [comment]
@Alastorwill 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
