### ISSUE TITLE
Please add site https://moonlightnovel.com/

### ISSUE THREAD

**Issue by Kiriri01** [dteviot/WebToEpub#1050]
Moonlightnovel had another website, https://moonlightnovel.com/
Please added this website in your free time. Thank you in advance ^^

**Comment by dteviot** [comment]
@Kiriri01 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@Kiriri01 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
