### ISSUE TITLE
Option to export only the chapter files as .xhtml files with naming as on web fetch

### ISSUE THREAD

**Issue by zeoint** [dteviot/WebToEpub#1057]
**Is your feature request related to a problem? Please describe.**
- No.

**Describe the solution you'd like**
- None.

**Describe alternatives you've considered**
- None.

**Additional context**
- None.

**Comment by dteviot** [comment]
@zeoint 
1. Are you aware that epubs are also zip files?  (Just change the extension from .epub to .zip.)
2. This change is not going to happen for WebToEpub.  That would complicate WebToEpub, for something that probably only benefits you.
3. I'd suggest a better solution is a tool that unpacks an epub, renaming the XHTML files based on the chapter names.  That would be (I think) reasonably simple to do.   The file toc.ncx gives the file name of each chapter file in the epub, along with the chapter's title.  
4. I could add the ability to do what you request to the MergeWebToEpub tool.  It would probably take less than 2 hours to do so.  Now persuade me why I should do this.  Basically, why would doing this be useful?  Note, if it's useful to you, it might be useful to others.  So a better solution would be a Calibre plug-in.  Which is a bit outside my area of expertise.
