### ISSUE TITLE
What IDE should I be using to code a project like this?

### ISSUE THREAD

**Issue by LudovicLachance** [dteviot/WebToEpub#106]
I want to try coding a plugins, but I don't know what IDE to use.

**Comment by ddraws** [comment]
Eclipse or Atom should be good enough.

**Comment by LudovicLachance** [comment]
I personnaly use https://www.visualstudio.com/vs/ is it comparable?

**Comment by dteviot** [comment]
@LudovicLachance 
Assuming you're using VS 2017, then it should work.  Although I haven't tried it.
I personally use https://code.visualstudio.com/ as the editor.  
Although I've also used Notepad++

Best of luck.  Please let me know how it goes.

**Comment by ddraws** [comment]
Which one is lighter?

**Comment by dteviot** [comment]
@ddraws
Visual Studio 2015 https://www.visualstudio.com/vs/  is 15 to 40 Gigs, depending on the components you install.  I assume 2017 is even bigger.
Visual Studio Code is about 30 Megs.
My install of Notepad++ is 25 Megs (but 8 Megs of that is plug-ins.)
