### ISSUE TITLE
Ranobes.top 

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#1062]
Extension is not working for novels with the MTL option

Examples:

https://ranobes.top/novels/1206153-since-the-red-moon-appeared.html

https://ranobes.top/novels/1206186-the-immortal-in-marvel.html

https://ranobes.top/novels/1206154-the-bragging-system.html

**Comment by Iadders** [comment]
nvm, it seems to be a mobile issue, Switching to desktop mode fixed it.

Here's the error btw: 
![Screenshot_20230901_133011_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/84446964/b2f07a89-30be-4417-a4bb-ad8b487e8c60)

**Comment by dteviot** [comment]
@Iadders 
Could it be related to https://github.com/dteviot/WebToEpub/issues/1068?

**Comment by Iadders** [comment]
You can download the MTL directly from the site, so this isn't an issue anymore. 

![Screenshot_20230916_205346_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/84446964/2e6a22bd-babc-4cdf-bae4-5b0482fbf2bf)
