### ISSUE TITLE
"Edit Chapter URLs" ignoring URL Fragments during Deduplication

### ISSUE THREAD

**Issue by Anthop-2** [dteviot/WebToEpub#1063]
**Describe the bug**
When editing and saving a chapter list, WebToEpub applies a duplicate detection and removal step that improperly ignores URL fragments (the portion after the # hash symbol) resulting in unique URLs being removed.

**To Reproduce**
1. On any page or go to https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881.
2. Open the WebToEpub extension.
3. Click `Edit Chapter URLs`.
4. Replace the contents of the text box with the following

> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/#post-50751769">Prologue</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/#post-50751811">Step 1.1</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/#post-50802154">Step 1.2</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/#post-50802253">Step 1.3</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/page-2#post-50916898">Step 1.4</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/page-175#post-58969372">Side-Step SR</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/page-175#post-58969396">Side-Step L</a>`
> `<a href="https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/page-183#post-59114851">Step 5.1</a>`

5. Click `Apply Changes`.
6. Note that the chapter list and Chapter Count is only 4 elements, with `Step 1.1`, `Step 1.2`, `Step 1.3`, and `Side-Step L` missing.

**Expected behavior**
In the reproduction steps, there should be 8 chapters.  Chapter deduplication, at least for SpaceBattles and other forum-based parsers, should consider the URL fragment during deduplication.

**Desktop (please complete the following information):**
 - Firefox 116.0.3
 - WebToEpub 0.0.0.154

**Additional context**
On forums such as SpaceBattles/SufficentVelocity, novels are stored as posts in a thread.  However, the underlying CMS, XenForo, no longer produces enables direct URLs to posts with the post details in the URL path (e.g.: `https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/post-58969372`).  Instead, XenForo now prefers to produces post links as fragments in a thread (e.g.: `https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/page-175#post-58969372`).

While the post-details-in-path link still works in XenForo, the SpaceBattles WebToEpub parser no longer supports the former type of link.  Parsing `https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/post-58969372` gives the following NPE:
`fetchedDom.getElementById(...) is null fetchChapter@moz-extension://e5ea1dd0-3544-4a9c-bcbb-648b78a8fa52/js/parsers/SpacebattlesParser.js:40:33`

A workaround is to simply add a unique query element to the URL.  This can be ignored by XenForo but allows the URL to pass deduplication check while still being supported by the SpaceBattles WebToEpub parser.  For example, the URL `https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881/page-175?post=58969372#post-58969372` works fine.

**Comment by dteviot** [comment]
@Anthop-2 

Actually, the parser logic for Spacebattles is aware of the fact that a page may have multiple chapters.  And the logic will just fetch the page from the website once and use the fragment in the URL to obtain the relevant text for chapters.

You can verify this for yourself, by doing the same thing you did before except DON'T click `Edit Chapter URLs`.
E.g. 
1. Go to https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881.
2. Expand page, to show all chapters.  
3. Open the WebToEpub extension.
4. You will see all chapters listed.  You can even click on `Show URLs of Chapters` and see that some chapters just differ by the fragment.
5. Click "Pack" and the resulting epub has the chapters.

Problem seems be with `Edit Chapter URLs`.  That's stripping the duplicates when reading back into list of chapters to fetch.

I'll look into that.

For my notes: time so far: 33 minutes.

**Comment by dteviot** [comment]
@Anthop-2 

That proved much easier to fix than I expected.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au-complete.680881.

For my notes: 57 minutes work, total

**Comment by Anthop-2** [comment]
Tested and verified it works correctly on Firefox 116.0.3.

Thank you!

**Comment by dteviot** [comment]
@Anthop-2 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
