### ISSUE TITLE
Epub of a Tumblr post only downloads the first picture and reuses them for the other pictures

### ISSUE THREAD

**Issue by minekasetsu** [dteviot/WebToEpub#1067]
Hello, sorry to bother you again.

**Describe the bug**
When trying to make epub of a tumblr post that has multiple pictures, it only saves the first picture of the post and reuses it for the other pictures.

**To Reproduce**
1. Open WebToEpub on a blank page.
2. Manually select the parser to "Default", put a `https://yamayuandadu.tumblr.com/post/726747256898895872/horned-hermits-and-immoral-immortals-an-inquiry` as a Starting URL, then click "Load and Analyse".
3. When no parser is found and asked to specify, put `.textpostbody` for element holding the content, and `h2 a` for element holding title of chapter.
4. Put `https://yamayuandadu.tumblr.com/post/726747256898895872/horned-hermits-and-immoral-immortals-an-inquiry` as URL of starting chapter, test and sees that it works, then apply.
5. Click "Clear URL" on Cover Image URL, unselect all chapter, then edit chapter url and paste `<a href="https://yamayuandadu.tumblr.com/post/726747256898895872/horned-hermits-and-immoral-immortals-an-inquiry">Horned hermits and immoral immortals: an inquiry into Zanmu’s background</a>`.
6. Pack epub.
7. Open the epub and sees that it downloads only the first picture of the page and reuses it for other pictures.

**Expected behavior**
It should download all the pictures in a post instead of downloading only the first and reusing that one for the rest.

**Screenshots**
![Untitled254](https://github.com/dteviot/WebToEpub/assets/25549192/5ec97037-9201-440a-a77e-01c8b8c5c2b7)
Left: Tumblr post opened on a browser.
Right: The resulting epub opened on a reader app. Note how it reuses the first picture for the second.

**Smartphone (please complete the following information):**
 - OS: Android 10
 - Browser: Kiwi Browser
 - Version: 0.0.0.154

**Comment by dteviot** [comment]
@minekasetsu 
I see the problem.  Each image is enclosed in a &lt;a&gt; element.  When this happens, WebToEpub thinks the &lt;a&gt; points to the high res version of the image, and tries to fetch that.  unfortunately, these &lt;a&gt; don't have a href, so WebToEpub thinks they're all the same.  So, it doen't try to get all of them, just the first, and then uses that for the other images.

I'm reluctant to spend the time to try and fix it for for this one odd-ball page, and risking breaking others.

**Comment by gamebeaker** [comment]
@minekasetsu 
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-installation and let me know how it goes.
