### ISSUE TITLE
Ranobes.Top MTL

### ISSUE THREAD

**Issue by Arsur3215Loki** [dteviot/WebToEpub#1068]
![image_2023-09-06_012008974](https://github.com/dteviot/WebToEpub/assets/74763442/9941d7f8-0445-47c9-a272-30aa322f31a0)
I had this issue where the MTL download had a different story than the one I wanted, when I tried to use the app on the MTL and manually edit the Chapter URL since it couldn't find the chapters, I get this message and the file had only 2 pages, the Title picture and the URL.

**Comment by dteviot** [comment]
@Arsur3215Loki 
Please provide URL of Table of Contents that isn't working.
Also, are you running the latest test version of WebToEpub?  The version in the stores has not been updated for latest changes to that site.

**Comment by Arsur3215Loki** [comment]
@dteviot 
https://ranobes.top/mtl-reader/1206178/index/
I tried the test version and it came nothing, I don't think there is a template for this yet since it's a machine translated and there's a download button next to read online. but in this situation, the story is different from the one downloaded and what's available to read. One is My German Empire while the one downloadable is My Third Empire.

**Comment by dteviot** [comment]
@Arsur3215Loki 
That page has completely different format than what WebToEpub is expecting.
WebToEpub is designed to work with pages like https://ranobes.top/novels/1206178-my-third-empire.html
Trying to make it work with the MTL pages is breaking the normal parser.
So, sorry,  not happening.

For my notes: 29 minutes work.

**Comment by Iadders** [comment]
You can download the MTL epub directly from the site. 

https://ranobes.top/novels/1206224-my-longevity-simulation.html

![Screenshot_20230916_205346_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/84446964/8bb3ed23-e6ba-49a4-9452-51f492cd6b69)
