### ISSUE TITLE
Please add support for https://bookswithqianya.com along with these footnote specifications :D

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1069]
The TOC of a novel on this site is: **https://bookswithqianya.com/bat/**

Although Webtoepub is able to generate novels from this site, because there's no specific parser, a lot of extraneous html elements are also grabbed into the epub.

And the novels on this site has an extreme amount of footnotes. These footnotes are also the "**hover over the word to appear**" type. Would it be possible to **generate these footnotes at the bottom of each respective xhtml file** like it's done in ChrysanthemumGarden please?

Because there are also countless footnotes in the synopsis on the Table of Contents page too (and within almost **all chapters**). They look like this:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/4bcba60b-fcfc-4baf-97c9-193ad369e013)

Ah and almost all chapters on this site are actually password-locked, but if a password is inputted, I think it won't immediately lock when WebToEpub crawls the site? Since this worked for some other sources :)

**Comment by dteviot** [comment]
@vanessabluellie 

> Would it be possible to generate these footnotes at the bottom of each respective xhtml file like it's done in ChrysanthemumGarden please?


Unfortunately, the footnotes are HTML embedded in JavaScript in multiple script elements.
I'd need to go through each script element, parse the JavaScript to see if it holds a footnote, then extract and sanitize the HTML, before inserting as a footnote.
So yes, it's technically possible, but far more work than I'm willing to do.

> Ah and almost all chapters on this site are actually password-locked, but if a password is inputted, I think it won't immediately lock when WebToEpub crawls the site?

It depends on how the locking works.  Most sites add a cookie that says 'unlocked' (or has that effect.)
And WebToEpub will supply the cookies the browser knows about for the site.


Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://bookswithqianya.com/bat/, chapters 1 and 3.1

Note, the HTML is soup, so work isn't very good.
You'll need to manually fix the list of chapters WebToEpub finds, and there is crap in the chapters I can't automatically identify to remove.

For my notes: 74 minutes work

**Comment by vanessabluellie** [comment]
Ohhh okay, that's fine! Thank you very much though~ the epub format is actually pretty similar with or without the parser, but thank you for your time and effort! It still grabs the chapters fine!

Ah and there's no need to notify me about the chrome webstore for this particular issue, so I hope it's okay with you that I close this issue.

**Comment by dteviot** [comment]
>Ah and there's no need to notify me about the chrome webstore for this particular issue, so I hope it's okay with you that I close this issue.

LOL.  I was just waiting for your confirmation before pushing a new version to the stores.

**Comment by loriette-01** [comment]
> LOL. I was just waiting for your confirmation before pushing a new version to the stores.

HAHAH, perfect timing :D thank you!!

**Comment by dteviot** [comment]
Well, this is embarrassing.
Got similar request https://github.com/dteviot/WebToEpub/issues/1071, and realized this might be easier than I thought.
And... now the site is down and I can't test.  Curses. 

For my notes, time spent so far: 83 minutes

**Comment by loriette-01** [comment]
> Well, this is embarrassing. Got similar request #1071, and realized this might be easier than I thought. And... now the site is down and I can't test. Curses.

That's okay! Thank you for putting so much time into my request. But ughhh, actually I found out why the translator closed the site (because I literally just went on it when it was still up but then freaked when I saw you said the site is down). Knowing this translator, they're probably going to keep the site shut for like quite some time so ughhh, it's completely okay to put this off for some time (if they ever do re-open because judging by how they do and act, it seems likely that it'll stay offline for I dunno, like months?). I'm so sorry that this caused a disruption for you ahah, but do take some leisure time for yourself to game lots more keke :3

**Comment by loriette-01** [comment]
@dteviot 

Hello! Just wanted to notify you that they suddenly reopened the site, which was much quicker than I had initially thought. But everything should be fine now, I think?  :)

**Comment by dteviot** [comment]
@loriette-01 

That... was not fun.
1. The footnotes are in script elements, with far more elements than there are footnotes on a page. I suspect ALL the footnote scripts are on every page.
2. A footnote can appear multiple times on a page.
3. Footnotes in the scripts are not ordered.  (Not surprising given 1 and 2)
4. Footnotes are in HTML.  (So, HTML formatting is shown in the epub.)

(Insert rant about what mind altering drugs was the author of this code on when they wrote this? And how can I get my hands on same?)

So, here's my best attempt.
Note, it's generating a footnote for each item seen in the text, so some footnote entries are repeated.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://bookswithqianya.com/bat/, chapter 1

For my notes: 168 minutes work (total)

**Comment by loriette-01** [comment]
@dteviot 

AHHH you did really well with this one though!!! It worked perfectly! <3 but i'm really sorry for taking such a huge chunk of your time and gosh I'm really sorry that this request was not great at all for you ahah, but it really does make me wonder how they came up with this type of way for doing footnotes lol, me want sum drugs too

**Comment by dteviot** [comment]
@loriette-01 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
