### ISSUE TITLE
[BUG] addon stopped working?

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#107]
Uhm, I can't seem to grab anything today? Example:

https://translationchicken.com, http://unlimitednovelfailures.mangamatters.com/teaser/shinanai-otoko-ni-koi-shita-shoujo/, https://www.lightnovelbastion.com/project.php?p=98, ...

I get this error (on LNB):
`
Cannot read property 'getElementsByTagName' of undefined TypeError: Cannot read property 'getElementsByTagName' of undefined
at getElements (chrome-extension://pdjgnlommckobgkiialndbmakmkebdjp/js/Util.js:577:52)
at Object.getElement (chrome-extension://pdjgnlommckobgkiialndbmakmkebdjp/js/Util.js:582:24)
at LightNovelBastionParser.findContent (chrome-extension://pdjgnlommckobgkiialndbmakmkebdjp/js/parsers/LightNovelBastionParser.js:23:21)
at chrome-extension://pdjgnlommckobgkiialndbmakmkebdjp/js/Parser.js:261:36
at <anonymous>`

I fear the last ExperimentalTab branch may have some issues, because I updated it yesterday and started have issues today.

From the Network tab in the inspector I see "HttpClient.js:23" (initiator) as the first line, then nothing.

The strange thing is that I was able to get a couple of things from http://skythewoodtl.com/fanfic-gifting/ before it stopped working, namely volume 1 and 2, but volume 2 was "damaged" basically the epilogue contained a full duplicate of the gallery).

Disabling AV and FW doesn't seem to help. I'm on chrome btw.

**Comment by dteviot** [comment]
@typhoon71
> Cannot read property 'getElementsByTagName' of undefined TypeError

D'oh!
Error in file Parser.js, function fetchChatper(url).  Change it to this.
```javascript
    fetchChapter(url) {
        return HttpClient.wrapFetch(url).then(function (xhr) {
            return Promise.resolve(xhr.responseXML);
        });
    }
```

**Comment by dteviot** [comment]
@typhoon71 
> volume 2 was "damaged" basically the epilogue contained a full duplicate of the gallery).

Not actually a bug.  the epilogue has a link to the gallery it appears just this line at the bottom of the story text.
> End of Volume 2: Even with Chunnibyou, I Want to Be a Witch!

However , there are a couple of other issues with the CrimsonMagicParser.  I'll fix tonight.

**Comment by typhoon71** [comment]
Parser.js: I appreciate the fast fix, thanks a lot. 
CrimsonMagicParser: thanks in advance, but take your time (read: during nights sleep too! XD)

**Comment by dteviot** [comment]
Fixed:
1. Cannot read property 'getElementsByTagName' of undefined 
2. Not reading "chapters" that are imgur galleries.
