### ISSUE TITLE
Site Layout has changed for this source, so Webtoepub doesn't work anymore :(

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1070]
Hello! The site [**https://cangji.net/**] has just changed their layout and now Webtoepub isn’t able to grab the chapter links from any category TOC on this source. Would it be possible to please update the parser for this site?

Example Table of Contents page: **https://cangji.net/category/xianshishoulie/**

The TOC for novels on this site are divided in pages. Webtoepub was previously able to scan through all pages by running on the first TOC page and retrieve all chapter links. Hopefully this is still possible! Thank you!!!

Also, almost all chapters on this site are actually password-locked, but if a password is inputted, I think it won't immediately lock when WebToEpub crawls the site? Since this worked for some other sources :)

**Comment by dteviot** [comment]
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://cangji.net/category/xianshishoulie/, chapter 1 and 98
Note, does not work for password protected chapters.

For my notes: 17 minutes work

**Comment by vanessabluellie** [comment]
Thank you! It worked perfectly, though I'm unsure what you mean that it doesn't work with password-locked chapters because it was still able to grab all locked chapters normally and process them into the epub with all text as it should ahah, which is perfect so thank you. :D

**Comment by dteviot** [comment]
@loriette-01 
>  I'm unsure what you mean that it doesn't work with password-locked chapters

Should have been, I was unable to test it worked with password locked chapters, because I did not have a password.

**Comment by dteviot** [comment]
@loriette-01 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
