### ISSUE TITLE
Grab footnotes from this source?

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1071]
hi hiii! I was wondering if it was possible to update the parser for the source **www.chickengege.org** so that Webtoepub can also grab the footnotes to the bottom of the chapter please? 

all chapters are password-locked so I can try to show what the page source looks like, and here's an example chapter with footnotes: https://www.chickengege.org/translations/dinghai/dinghai-2/

the footnotes hover above the text in a grey box, like this:

![image](https://github.com/dteviot/WebToEpub/assets/144674653/85d4838d-0a3e-4169-a0a0-19a6a5945d27)

the text is put in these tags:

![image](https://github.com/dteviot/WebToEpub/assets/144674653/38ab30b8-73b4-4313-a49e-20bc7f6fbf22)

then the footnote information is written in these tags:

part 1 - 
![image](https://github.com/dteviot/WebToEpub/assets/144674653/667059bc-4fc8-43fd-b43f-0f7afa8d46e1)

part 2 (some text was cut off so i put the second part here!) - 
![image](https://github.com/dteviot/WebToEpub/assets/144674653/35b44f79-e9b5-4e65-85b1-8cdcdf8b65b5)

it seems different than other sites i've seen so i'm unsure if this is possible? but if it's not then that's okay! i'll close this issue! thank you!

**Comment by dteviot** [comment]
@yuzucitrusx 

I had similar request yesterday, although the JavaScript was a bit different.
One thing I noticed in that JavaScript was there was text for footnotes that were not on the page.
A copy of all the HTML for the page would be helpful.

**Comment by dteviot** [comment]
@yuzucitrusx 

Based on what you sent me, I'd try something like below.  But I'd really need to test and debug
```javascript
    preprocessRawDom(webPageDom) {
        let content = this.findContent(webPageDom);
        let footnotes = this.scriptElementsToTextNodes(webPageDom);
        this.moveFootnotes(webPageDom, content, footnotes);
    }

    scriptElementsToTextNodes(dom) {
        return [...dom.querySelectorAll("script")]
            .map(s => this.extractFootnoteText(s.textContent))
            .filter(t => t !== null)
            .map(t => dom.createTextNode(t));
    }

    extractFootnoteText(script) {
        if (!script.includes("{ toolTips(")) {
            return null;
        }
        let start = script.indexOf("\"") + 1;
        let end = script.lastIndexOf("\",'");
        let text = script.substring(start, end);
        return text;
    }
```

**Comment by yuzucitrusx** [comment]
@dteviot

hi hii!! thank you for your reply!! apologies for the late response, i hope sending you the entire page source will help with the testing! but do let me know if it's too strenuous on you and i'm still happy to skip over this request of mine.

i tried to copy the page source in three different files. the txt file contains all text with no cut-offs, but the pdf has it in colour although a lot of text is missing... and the html file has what the chapter looks like (not the page source). just thought i'd send all 3!

[Full HTML Page Source.zip](https://github.com/dteviot/WebToEpub/files/12584190/Full.HTML.Page.Source.zip)

**Comment by dteviot** [comment]
@yuzucitrusx 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* Not fully tested. 

For my notes: 30 minutes work

**Comment by yuzucitrusx** [comment]
hi hii! thank you for your hard work! i tried it just now and still...um...no footnotes were grabbed :'(

i only generated a few chapters, but will attach the epub here for you, if you'd like~

[EPUB.zip](https://github.com/dteviot/WebToEpub/files/12597518/EPUB.zip)

but the span tooltip tags i can see in the epub around the affected text that supposedly has footnotes, it's just that the footnotes themselves aren't generated at the bottom of the chapter.

would having access to the novel help maybe?

**Comment by dteviot** [comment]
> would having access to the novel help maybe?

Yes.  Obviously I've missed something.
Note, please email me dteviot@gmail.com the necessary details for access. 
Do NOT post them here, which is public.

**Comment by dteviot** [comment]
@yuzucitrusx 

My apologies, I think I know what happened.
Yesterday I did a fix for freewebnovel.com, and as part of that I accidentally reverted the footnote work for chickengege.
So, if you downloaded the test version yesterday, it lacked that code.

I've restored the footnote code for the test versions for Firefox and Chrome and uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.

**Comment by yuzucitrusx** [comment]
> Yes. Obviously I've missed something. Note, please email me [dteviot@gmail.com](mailto:dteviot@gmail.com) the necessary details for access. Do NOT post them here, which is public.

ahhh yes, that's why i asked instead of just sending the password here :) i apologise for the delayed response, but i'll send an email just in case~

> My apologies, I think I know what happened. Yesterday I did a fix for freewebnovel.com, and as part of that I accidentally reverted the footnote work for chickengege. So, if you downloaded the test version yesterday, it lacked that code.

thank you! i just tried the new version :D but uhhh i'm not sure whether it's me or i'm just clueless, but now webtoepub won't grab any chapters at all. the save file pop-up dialogue will like appear after every single chapter it tries to grab and the epub will be blank? uhhh i'm not sure why... :'(

**Comment by dteviot** [comment]
@yuzucitrusx 

> but uhhh i'm not sure whether it's me or I'm just clueless, but now webtoepub won't grab any chapters at all. 

You're not stupid.  WebToEpub was broken.  It was in the path I could not easily test without working access to the web site.
Anyway, footnotes are now being added.  Note, in many cases the footnote text is HTML.  Which is being inserted into the footnote as text, so you see the HTML.  Fixing that is problematic, as it's not always HTML.   Well, I could just jam the text into the list item, but then WebToEpub fails security validation by Google and Mozilla.  (don't ask.)
Also, there's no mark in the main text to indicate a footnote.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.chickengege.org/novels/dinghai/, chapters 1, 2, & 3

Chapter 2 is good example of what footnotes with HTML look like.

For my notes: Total time 101 minutes

**Comment by yuzucitrusx** [comment]
> You're not stupid. WebToEpub was broken.

@dteviot

OHHHH i really thought i broke it HAHAH, but thank youuuuuuu, it works perfectly!! i'm sorry for taking up so much of your time, 101 minutes of it too, but many super thanks for your big efforts!! <3

**Comment by dteviot** [comment]
@yuzucitrusx 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
