### ISSUE TITLE
i got an error trying to grab novel from freewebnovel.com

### ISSUE THREAD

**Issue by rizukitomi** [dteviot/WebToEpub#1073]
I got error when i try grabbing Emperor's Domination novel from freewebnovel.com, this is the error i got:

TypeError: Cannot read properties of undefined (reading 'href')
    at getUrlsOfTocPages (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/parsers/FreeWebNovelParser.js:21:77)
    at FreeWebNovelParser.getChapterUrlsFromMultipleTocPages (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/Parser.js:661:30)
    at FreeWebNovelParser.getChapterUrls (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/parsers/FreeWebNovelParser.js:12:21)
    at FreeWebNovelParser.onLoadFirstPage (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/Parser.js:378:14)
    at processInitialHtml (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/main.js:47:24)
    at populateControlsWithDom (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/main.js:252:9)
    at onMessageListener (chrome-extension://cbakjfolkciekclcpnahgokglifminmf/js/main.js:16:13)

I just open this link https://freewebnovel.com/emperors-domination.html in my chrome browser and click WebToEpub extension icon and i got that error.

And when i try to click "OK" button there, WebToEpub go back to main popup page, and no matter how long i wait, it doesn't load any chapters.

This is the version of the WebToEpub that i used:
WebToEpub0.0.0.155.Chrome

Browser: Google Chrome 116.0.5845.180 (Official Build) (64-bit) (cohort: Stable)
Revision: 17ff023f3eb4f6883321db9399bfc65560ef84a9-refs/branch-heads/5845@{#1745}
OS: Windows 10 Version 22H2 (Build 19045.3208)

![screenshot-nimbusweb me-2023 09 13-10_02_35](https://github.com/dteviot/WebToEpub/assets/29246496/6de14973-4a49-40e5-9bed-4643a1628904)
![screenshot-nimbusweb me-2023 09 13-10_14_27](https://github.com/dteviot/WebToEpub/assets/29246496/96dd6e3d-2869-4115-b225-181b9e28e281)
![screenshot-nimbusweb me-2023 09 13-10_17_52](https://github.com/dteviot/WebToEpub/assets/29246496/9e0684dc-d552-4bf0-8064-db3e6bbd1307)

**Comment by dteviot** [comment]
@rizukitomi 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://freewebnovel.com/emperors-domination.html, chapters 1 and 5321

For my notes: 32 minutes work

**Comment by rizukitomi** [comment]
Thanks for the update... for the tryout... i used this one WebToEpub0.0.0.156.Chrome.zip

Initial loading went okay... no error...

Try grabbing three epub from https://freewebnovel.com/emperors-domination.html...

1. chapter 1-5
2. chapter 2720-2724
3. chapter 5344-5348

All three attempts went alright... no error...

Thank you for the fixed... i'll close this issue with this reply...

![screenshot-nimbusweb me-2023 09 13-16_43_03](https://github.com/dteviot/WebToEpub/assets/29246496/e96e63e4-56a4-4ae6-8f2f-b2ef7426f35d)
![screenshot-nimbusweb me-2023 09 13-16_43_34](https://github.com/dteviot/WebToEpub/assets/29246496/bda53007-4b39-40e8-89d6-ed3b85046b50)
![screenshot-nimbusweb me-2023 09 13-16_45_01](https://github.com/dteviot/WebToEpub/assets/29246496/e64f11c6-64bf-402c-99d1-b5d22cc28d11)
![screenshot-nimbusweb me-2023 09 13-16_45_32](https://github.com/dteviot/WebToEpub/assets/29246496/aa023e4f-be1f-4637-bbf5-e67fabc0f441)

**Comment by dteviot** [comment]
@rizukitomi 
You should try **other** novels on the site.

Reopen, so I know to tell you when I post new version to Chrome and Firefox stores.

**Comment by swanknight** [comment]
> @rizukitomi You should try **other** novels on the site.
> 
> Reopen, so I know to tell you when I post new version to Chrome and Firefox stores.

I was just about to report this issue, but I found that you fixed it already, Thanks!  
I just tested the updated extension from GDrive, and so far it's working fine (different novel that OP).

**Comment by rizukitomi** [comment]
@swanknight thanks for the report... i've been kinda busy this past week... and i just found out that if you open any chapters from any novels in freewebnovel.com and innread.com (same content as freewenovel.com, just different link), you get redirected to bednovel.com (same content as both links i mentioned above)...

and i try it using the extension provided by @dteviot on GDrive, edit the link inside FreeWebNovelParser.js from freewebnovel.com to bednovel.com, and it works... so it's basically a mirror...

@dteviot i think the parser for freewebnovel.com (or innread.com if there is a request open for it) is no longer needed since you basically just get redirected to bednovel.com... or you can just keep that and create a new parser for bednovel...

and thank you for for the fixed above and sorry... i've been kinda busy this past week... can't do any test...

**Comment by dteviot** [comment]
@rizukitomi 

Thanks for that.  Added bednovel.com and innnovel.com as aliases for freewebnovel.com.

**Comment by dteviot** [comment]
@swanknight @rizukitomi 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
