### ISSUE TITLE
Please add site https://whitemoonlightnovels.com/

### ISSUE THREAD

**Issue by elpsycongruent** [dteviot/WebToEpub#1075]
If and when you could add this one, I'd really appreciate it!

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://whitemoonlightnovels.com/series/gold-medal-coach/

### Did you try using the Default Parser for the site?  If not, why not?
I tried, but it didn't pick up any of the chapters

**Comment by elpsycongruent** [comment]
It works perfectly, thanks!

**Comment by dteviot** [comment]
@elpsycongruent 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
