### ISSUE TITLE
Grabbing full image when there's a "?resize=" link type

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#108]
I noticed that sometimes there are links like this one: 

'https://i2.wp.com/shintranslations.com/wp-content/uploads/2015/07/blushing-tiera.png?resize=615%2C907&amp;ssl=1'

The addon will use this link and grab a resized image even if the fullsize image does exist; you can see it here:

'https://i2.wp.com/shintranslations.com/wp-content/uploads/2015/07/blushing-tiera.png'

Basically the issue is the '?resize=615%2C907' which resises the image on the fly.

I noticed this on THE NEW GATE on 'shintranslations.com', but the same happens when the "detected" cover link contains '?resize=....'

The site is wordpress based, but I think something like that can happen anywhere?

Can webtoepub be made to grab the "original" (ie non resized) image instead?

**Comment by dteviot** [comment]
Seems easy enough.
There's already processing to remove the "h" and "w' resize parameters.
Just need to add "resize" as well to list .
ImageCollector.js, line 324.
Also need to add ".wp.com" to hostnames to check for.  Line 313

**Comment by dteviot** [comment]
@typhoon71 
Change has been committed to the usual experimental branch.
Please try it out.
Caution, it's possible this will result in failures from other sites if they require a resize parameter in the URL.  I have not tested to see if any have an issue.

**Comment by typhoon71** [comment]
Seems to work OK here, the images are grabbed full size. Thanks.
I didn't find sites requiring the "resize" parameter, but if I do I'll let you know.

A little detail: the cover image link (the editable one that gets autofilled) still contains a link with resize info: actually it's not a big issue since it's in the front and easy to fix manually.

**Comment by dteviot** [comment]
@typhoon71 
> The issue the is that webtoepub seems to tries to "reconstruct" the page layout (the "grid" of images), scaling the images to a really smal size at view time (calibre).
It happens with all of the links for the illustrations galleries from "https://shintranslations.com/the-new-gate-toc/", for example "https://shintranslations.com/vol-3-illustrations/".

No. That's not it.  Full size images are obtained for the illustrations pages of volume 1 and 2.
The Volume 3 images page fails to get full size images.
The reason for this is the v3, &lt;img&gt; tags are wrapped with a &lt;img&gt; tag.  e.g. Like this
```html
<a href="https://shintranslations.com/vol-3-illustrations/mapvol3/#main" border="0" itemprop="url">
   <meta itemprop="width" content="178"/> 
   <meta itemprop="height" content="261" /> 
   <img data-attachment-id="1372" 
             data-orig-file="https://shintranslations.com/wp-content/uploads/2015/11/MapVol3.png" 
             data-orig-size="1009,1481" 
             data-comments-opened="1" 
             data-image-meta="{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" 
             data-image-title="Map Vol 3" 
             data-image-description="" 
             data-medium-file="https://i2.wp.com/shintranslations.com/wp-content/uploads/2015/11/MapVol3.png?fit=204%2C300&amp;ssl=1" 
             data-large-file="https://i2.wp.com/shintranslations.com/wp-content/uploads/2015/11/MapVol3.png?fit=698%2C1024&amp;ssl=1"
             src="https://i2.wp.com/shintranslations.com/wp-content/uploads/2015/11/MapVol3.png?resize=178%2C261&amp;ssl=1" 
             width="178" 
             height="261" 
             data-original-width="178" 
             data-original-height="261" 
             itemprop="http://schema.org/image" 
             title="Map Vol 3" 
             alt="Map Vol 3" 
             style="width: 178px; height: 261px;"> 
</a>
```

When an &lt;img&gt; tag is wrapped, the parser assumes the &lt;img&gt; tag points to the full size image and follows the link.  However, in this case the link is to an HTML page.  So the parser falls back to the lower res image in the &lt;img&gt;.

I'll see what I can do to fix.  
Note, the full size image seems to be given by the "data-orig-file" attribute of the &lt;img&gt; tag.

**Comment by dteviot** [comment]
@typhoon71
On further investigation, problem is limited to 4 images on the v3 illustrations page.
(Volume 4 and 5 have no issues.)
As such, it's easier to manually replace the images with Calibre than to fix WebToEpub code.

**Comment by typhoon71** [comment]
Ehm, it seems I was checking the files in the wrong directory... 
I was opening the ones I got before you updated webtoepub with non resized images... I'm sorry. 

Indeed only a some images in the illustration gallery of volume 3 are affected, no point fixing them in the code, I will edit manually the epub, as you said.

Btw, I see webtoepub grabs the fullsize the Cover Image, despite the "Cover Image URL" still showing all the resize parameters: nice, one thing less to "worry".

**Comment by typhoon71** [comment]
Again on resized images / html / galleries.

I noticed the image grabbed from "https://isekaicyborg.wordpress.com/isekai-maou-to-shoukan-shoujo-dorei-majutsu/" are resized. It's the same thing that happened with shintranslations.com galleries.

I checked all of them this time: volume 1 is perfect (gallery and in-page pics are OK), but volume 2/3/4 gallery illustrations are resized (while in-page pics are OK). 

I will fix them manually (3 or 4 pics each gallery), but if this becomes widespread maybe it would be nice to find some kind of automated solution, if possible.

**Comment by dteviot** [comment]
@typhoon71
> I will fix them manually (3 or 4 pics each gallery), but if this becomes widespread maybe it would be nice to find some kind of automated solution, if possible.

Don't bother, I'll have a fix for this in a few days (I hope.)

**Comment by dteviot** [comment]
@typhoon71
In file ImageCollector.js, replace this
```javascript
    initialUrlToTry(imageInfo) {
        return ImageCollector.removeSizeParamsFromWordPressQuery(imageInfo.wrappingUrl);
    }
```
with this.
```javascript
    initialUrlToTry(imageInfo) {
        let isImageUrl = !ImageCollector.urlHasFragment(imageInfo.wrappingUrl);
        let urlToTry = isImageUrl ? imageInfo.wrappingUrl : imageInfo.sourceUrl;
        return ImageCollector.removeSizeParamsFromWordPressQuery(urlToTry);
    }

    static urlHasFragment(url) {
        let parser = document.createElement("a");
        parser.href = url;
        return !util.isNullOrEmpty(parser.hash);
    }
```

I've tested against isekaicyborg volmes 2 and 3, and The new gate volume 3.  Seems to collect the large images.  You should also try on other sites, there's a small chance it will now fail to get images where it did before.

**Comment by typhoon71** [comment]
Thanks, it seems to work fine with that code replaced.
If I see any failure in getting images that waas fine before I will report back.

**Comment by dteviot** [comment]
@typhoon71
I'm going to call this fixed.  Please re-open if you find any more issues.

**Comment by typhoon71** [comment]
OK.
