### ISSUE TITLE
Patreon ( I can't download the content/post of the authors) 

### ISSUE THREAD

**Issue by JoyceEstrada13** [dteviot/WebToEpub#1084]
I just want to confirm something. In patreon site (https://www.patreon.com) , Before I can see/download all the post of the authors even though I didn't subscribe to authors (but of course it is lock). But now I can't see the authors post when i am using Webtoepub to convert. Is it a bug or this is permanent? Thank you!

Before i can see all the post, now it is just this one 👇👇
![Screenshot_20231004_195437_com kiwibrowser browser](https://github.com/dteviot/WebToEpub/assets/82950997/e3ac1942-7980-440f-ac9c-ee9af8ea4a01)

**Comment by dteviot** [comment]
@JoyceEstrada13
Site has probably changed format, so WebToEpub doesn't work with it.
I'll need to update.

**Comment by JoyceEstrada13** [comment]
THANK YOU SO MUCH.

**Comment by dteviot** [comment]
@Reopen so I know to notify you when version in Chrome and Firefox stores updated.

**Comment by dteviot** [comment]
@JoyceEstrada13 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
