### ISSUE TITLE
Please add site https://www.wuxiau.com/

### ISSUE THREAD

**Issue by FrostDuchess** [dteviot/WebToEpub#1085]
Hi if it's not too much a bother can you add a parser for **https://www.wuxiau.com/**
It was formerly **https://www.wuxiax.com/** and WebToEpub worked just fine before, but they changed something and the domain so the parser broke

Please fix that, thanks

**Comment by dteviot** [comment]
@FrostDuchess 

That's an easy fix.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiau.com/novel/top-tier-providence-secretly-cultivate-for-a-thousand-years.html, chapters 1 &amp; 2

For my notes: 8 minutes work

**Comment by FrostDuchess** [comment]
Thank you so much!

**Comment by dteviot** [comment]
@FrostDuchess 
Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
