### ISSUE TITLE
HostedNovel with half of the chapter only

### ISSUE THREAD

**Issue by marcussacana** [dteviot/WebToEpub#1086]
**Describe the bug**
The HostedNovel has some verification shit to display the entire chapter content, it must be bypassed.

**To Reproduce**
1. Trying download: https://hostednovel.com/novel/theres-absolutely-no-problem-with-the-magic-cards-i-made

**Expected behavior**
The WebToEpub should be able to run the site in some type of iframe to let the site verify the browser and load the entire chapter

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/10576957/5028fcd0-88a1-4ca8-82f5-5d7b1989ec30)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Edge
 - Version 117.0.2045.47

**Comment by dteviot** [comment]
@marcussacana 
Have you tried to login and then run WebToEpub?

**Comment by marcussacana** [comment]
> @marcussacana Have you tried to login and then run WebToEpub?

You are right, I just forgot that today my browser has been reseted all cookies for some random reason, false alert then, thx for the help.
