### ISSUE TITLE
file name incorrect and seems to reassemble memory location

### ISSUE THREAD

**Issue by dfhasdh** [dteviot/WebToEpub#1088]
**Describe the bug**
when attempting to download an already downloaded file the file is incorrect. it seems to instead reassemble memory location.

**To Reproduce**
1. Go to 'royalroad' note I tried it on other website including fannovel and readwn and it still happened
2. use webtoepub
3. file you receive will be a mumbled pile of memory location

**Expected behavior**
file should be the title
**Screenshots**
![Screenshot 2023-10-08 000614](https://github.com/dteviot/WebToEpub/assets/117046944/7203644e-1f59-4976-9f73-8e55aae98a76)
**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 0.0.0.155(I think it is this, it's the version in chrome webstore)

**Additional context**
titles are not what the titles should be and look like memory location.
Note no setting are changed from the default.

**Comment by dteviot** [comment]
@dfhasdh 

Most common causes of this are:
1. Youve got another extension loaded that's (unintentionally) interacting with WebToEpub.  Try disabling your other extensions.
2. You're running in incognito mode.  (Was supposed to be fixed, but does get broken.)
3. You've got other chrome settings that are conflicting.  (I think there's a couple of download settings that can cause issues.)

Worst case, to fix, use the Firefox version of the plug-in with a Firefox browser.

For my notes: 6 minutes.

**Comment by dfhasdh** [comment]
My solution--
I am still unsure which of the what caused it not to work ,however you mentioned that other extensions may conflict with WebToEpub, so I tried it on incognito mode in order to only allow 1 extension to be loaded into chrome and tried it. it worked I was able to download my epub thank you for your help.

**Comment by dteviot** [comment]
@dfhasdh 
Additional, I think the oddly named file is still a valid epub file.  You should be able to rename it and view with an epub viewer.
