### ISSUE TITLE
Tumblr - Could not find content element for web page

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#1091]
Windows 10, Firefox 119.0b7 (64-bit)

Version
0.0.0.155
Last Updated
September 2, 2023

Error:
Could not find content element for web page 'https://thefinalcinderella.tumblr.com/post/189968250310/kaze-ga-tsuyoku-fuiteiru-chapter-1-the-residents'. fetchWebPageContent/<@moz-extension://c994fc2a-ab27-4154-aeb1-08022f16ea49/js/Parser.js:501:23

I'm trying to generate an epub for this page, but it's giving me the above error (it's also not parsing the chapter URLs correctly - I had to get them myself).

https://thefinalcinderella.tumblr.com/kazetsuyo

**Comment by dteviot** [comment]
@Tenome 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://thefinalcinderella.tumblr.com/post/616419996520808448/tsurune-novel-index

For my notes: 24 minutes work

**Comment by dteviot** [comment]
@Tenome 
Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
