### ISSUE TITLE
How to use default parser for a site that already has an existing built parser to custom remove elements with css selector?

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1092]
hi hiiii!

i had recently learnt to use the default parser for sites where there was no existing parser and found the "css selector" removal option really useful to custom select all extraneous html elements for removal before generating the epub itself.

there are some sites that webtoepub does already support, but a lot of html elements still get grabbed and so i was wanting to make use of the default parser for these specific sites as well to customise the format, but when i click on the webtoepub icon, since the site is already supported with a built parser, it'll automatically lead to the page of chapters and not the default parser page.

is there perhaps some way i can use the default parser for sites that already an existing parser in webtoepub so i can custom select elements to remove? like maybe a link? or do i need to just go to any site that webtoepub does not yet support to find the default parser page?

thank you for all your help!!

**Comment by Alastorwill** [comment]
You just have to go to advanced options and the menu will appear and you will go
Select analyzer manually
and you hit default

**Comment by dteviot** [comment]
@yuzucitrusx 
If you want to clean extraneous html elements from an epub, I suggest using https://github.com/dteviot/EpubEditor.
That said, you might try using "Manually Select Parser" on the Advanced Options.
Or, get the test build, unpack, and add a removeUnwantedElementsFromContentElement function.
Or, raise an issue and I can fix it for everyone.

**Comment by yuzucitrusx** [comment]
@Alastorwill 

ohhhh, that worked!! thank you!!!

@dteviot 

i actually use epubeditor together with the default parser! so i do a joint process basically. by configuring the epub beforehand, i remove the majority of extraneous html elements and then i touch it off by cleaning the remaining elements that were still pulled into the epub which i could not delete via css selector by using the epubeditor. i found using both together to be more accurate haha :D

but i'm quite curious what you meant when you said "test build", can you maybe elaborate a bit more on where and how to go about that please?

thank you again for all your help! the option for "manually select parser" did what i wanted so i can now configure sources that already have an existing parser :)

**Comment by dteviot** [comment]
Test versions for Firefox and Chrome are uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

These are just zip files with the extension, so you can unzip the file and then modify the code.

**Comment by yuzucitrusx** [comment]
@dteviot

ohhhh, that's much too advanced for my noggin haha, i will continue with the simplicity keke, but thank you so much for your continued responses, they've been helpful :)
