### ISSUE TITLE
https://moonlightnovels.com/ becomes https://moonlightnovel.com/

### ISSUE THREAD

**Issue by courli79** [dteviot/WebToEpub#1095]
novel : https://moonlightnovel.com/novels/i-thought-i-didnt-have-long-to-live/

**Comment by dteviot** [comment]
@courli79 

You neglected to say site has also completely changed its format.  Are you sure it's the same site?

Anyway test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://moonlightnovel.com/novels/i-thought-i-didnt-have-long-to-live/, chapters 1 &amp; 2

Note, I can't easily do anything about the empty blocks that are injected every few paragraphs.  But I don't think any text is being lost.

For my notes: 29 minutes work

**Comment by dteviot** [comment]
@courli79 

And I'm an idiot.  As soon as I realized the empty blocks are &lt;span&gt; elements with no content, it's trivial to remove them.
Test version updated.

For my notes: 20 minutes work

**Comment by courli79** [comment]
> You forgot to say that the site has also completely changed its format. 
Hello, sorry I forgot to specify that. I posted it quickly to put the problem online while I tried to put in place the code due to the modification of the site on which I was blocked.

> Are you sure it's the same site?
yes, it's the same site.

In any case, always and again thank you for your work!

**Comment by dteviot** [comment]
@courli79 
Reopen, so I know to notify you when version in Chrome and Firefox stores is updated.

**Comment by dteviot** [comment]
@courli79 
Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
