### ISSUE TITLE
Please add site https://translatinotaku.net/

### ISSUE THREAD

**Issue by Wonkie-wow** [dteviot/WebToEpub#1097]
https://translatinotaku.net/novel/pick-me-up-infinite-gacha/
Used the default parser, and it didn't load any of the chapters.

**Comment by dteviot** [comment]
@Wonkie-wow 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://translatinotaku.net/novel/pick-me-up-infinite-gacha/, chapter 1

Note, site is now using a fairly standard Madara style, so just falling back to the standard Madara parser.  The created "info" page has some cruft, but I can't be bothered creating a tweaked parser.

For my notes: 13 minutes work

**Comment by dteviot** [comment]
@Wonkie-wow 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
