### ISSUE TITLE
Here is an update for CreativeNovels.com, please add/edit the .js file with code from this request

### ISSUE THREAD

**Issue by MeliMeliDH** [dteviot/WebToEpub#1098]
I've updated the code for the js/parsers/creativenovelsparser.js to make it actually function, but I have never used github before so I don't know how to comitt the code change. The following code has been tested and I am currently using it on https://creativenovels.com/novel/the-villains-need-to-save-the-world/ and it works downloading all chapters. (Do note that you still need premium/to buy chapters that are behind pay-wall)

The update is to the chapter retrieving command and content retrieving command, edited so it matches the correct id's and classes. Only tested on Chrome/OperaGX, not Firefox.

-----

"use strict";
parserFactory.register("creativenovels.com", function() { return new CreativeNovelsParser() });
class CreativeNovelsParser extends Parser{
    constructor() {
        super();
    }

    getChapterUrls(dom) {
        let chapters = [...dom.querySelectorAll("div#chapter_list_novel_page, div.post_box a")]
            .map(a => util.hyperLinkToChapter(a));
        return Promise.resolve(chapters);
    }

    findContent(dom) {
        return dom.querySelector("div.entry-content.content");
    };

    removeUnwantedElementsFromContentElement(element) {
        util.removeElements(element.querySelectorAll("div.team, div.x-donate-1,"+
            " div.navigation, div.navi, header.entry-header"));
        super.removeUnwantedElementsFromContentElement(element);
    }

    findChapterTitle(dom) {
        return dom.querySelector("header.entry-header h1");
    }

    findCoverImageUrl(dom) {
        let img = dom.querySelector("img.book_cover");
        return (img === null) ? util.getFirstImgSrc(dom, "header") : img.src;
    }

    makeHiddenNodesVisible(node) {
        node.removeAttribute("style");
    }
}

**Comment by dteviot** [comment]
@MeliMeliDH 

Thank you.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://creativenovels.com/novel/the-villains-need-to-save-the-world/

For my notes: 10 minutes work

**Comment by dteviot** [comment]
@MeliMeliDH 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
