### ISSUE TITLE
https://www.shw5.cc/

### ISSUE THREAD

**Issue by levinuiiy** [dteviot/WebToEpub#1099]
https://www.shw5.cc/

i don't have a computer at moment at hand, & prob dont know how it works, but just requesting a site. 
So when i have one later, i can crawl this site.

**Comment by dteviot** [comment]
@levinuiiy 

I should just close this and tell you to reopen when you get a PC, but it's almost Christmas, and I'm feeling generous.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.shw5.cc/book/1688/, chapters 1 to 3

For my notes: 18 minutes work

**Comment by dteviot** [comment]
@levinuiiy 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
