### ISSUE TITLE
[Enhancement] Preserve original image filename

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#11]
This was requested by a guest

This is a self marker for me and is exactly what the title says.

**Comment by dteviot** [comment]
This is similar to request to use Chapter Title as part of filename.
Using chapter titles for filename has a number of problematic edge cases.
- The chapter title may contain characters resulting in an invalid URL.
- The chapter title may contain path characters, resulting in file going to unexpected place.
- The chapter title may contain characters that are invalid on a Windows/Mac/Linux filesystem, resulting in undefined behaviour when try to unzip the ePUB.
- Older zip libraries have undefined handling of filenames that are not ASCII.  (This could be a problem as we want to support foreign languages.)

While none of these are insoluble, they provide plenty of scope for bugs.

Suggested alternate solutions:

1. In the content.opf file which lists every file, add a XML comment giving the original URL.  Advantage: easy to implement.  Disadvantage: Not easily discoverable by user.
2. Add a File List table to end of epub which gives the filename (in the ePUB) of each file and the URL it came from. Not quite as easy to implement, but should be easy for users to discover.  Disadvantage.  Some users may regard this as "polluting" the ePUB.  Fix by providing an option to turn it off.

**Comment by belldandu** [comment]
All of the original image Filenames on Baka-Tsuki Do not have Invalid characters or path characters. They follow a very strict format when it comes to images mostly because these images are uploaded via the wiki and the wiki almost always strips characters that interfere with the url.

As for the chapter names i see your point on the edge case scenarios. Especially in the case of ASCII.

Either way i did provide the original image url as a data-origin value within the image. see https://github.com/belldandu/WebToEpub/blob/e2dbb556446cfcce06b9b65c854b9822e37b6212/plugin/js/Util.js#L53

This has disadvantages of its own.

Back to the chapter title for a moment. The function that truncates the chapter title will most likely be changed to getChapterTitle and then i would just do checks and if the major checks fail then we do "" otherwise we strip out any invalid characters,

**Comment by dteviot** [comment]
> Either way i did provide the original image url as a data-origin value within the image

Yes I saw that.  What are the disadvantages, other than it's not obvious to user.

> For the chapter title i will most likely do this to get rid of ALL special characters excep...

I did something sort of similar for the save filename (generated from the Title).  Should probably replace my code with your one.

**Comment by belldandu** [comment]
That's pretty much the only disadvantage. I see atm. Could probably put a note somewhere in the readme or something about the origin file name being in the image tag when they inspect the source.

**Comment by belldandu** [comment]
```
    var getChapterTitle = function (title) {
        if(title) {
            title = title.replace(/([^a-z0-9_\- ]+)/gi, '');
            return (title.length > 20 ? title.substr(0, 20) + "..." : title);
        }
        return "";
    }

    var getImageName = function (page) {
        if(page){
            let name = page.split(/file:/gi)[1];
            if(name){
                let image = name.split(/\./gi)[0].replace(/([^a-z0-9_\- ]+)/gi, '');
                return (image.length > 20 ? image.substr(0, 20) + "..." : image);
            }
        }
        return "";
    }
```

**Comment by belldandu** [comment]
Closing now as added in #10
