### ISSUE TITLE
Can you add www.timotxt.com. Thanks

### ISSUE THREAD

**Issue by Draoko** [dteviot/WebToEpub#1100]

**Comment by dteviot** [comment]
@Draoko 

Caution: you may need to pass Captcha before running WebToEpub

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.timotxt.com/0712433418/, chapter 1

For my notes: 30 minutes work

**Comment by dteviot** [comment]
@Draoko 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
