### ISSUE TITLE
Error https://fluffytranslations.home.blog/

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#1101]
It detects the chapters well but when the download starts it gives that error

https://fluffytranslations.home.blog/

![screenshoteasy](https://github.com/dteviot/WebToEpub/assets/29169926/1eb32790-12a4-4b73-89bf-4da2a13374c5)

![screenshoteasy (1)](https://github.com/dteviot/WebToEpub/assets/29169926/954d1f48-ca65-4453-be5e-69d278a05774)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dteviot** [comment]
@bichitoxxx 

Nothing wrong with WebToEpub.  Several of the chapters have the wrong URL.  e.g. See chapter 40 in screenshot below
![image](https://github.com/dteviot/WebToEpub/assets/5157081/e4d3c12e-4453-41fe-b823-97b9c8b1c97e)


You can see this for yourself if you click onthe "Show URLs of Chapters" button.

For my notes: 12 minutes work

**Comment by bichitoxxx** [comment]
Thank you
