### ISSUE TITLE
Please Remove the Repeated Word "Advertisement" From Within the Chapter Text

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1102]
Hello!

I was wondering if it was possible to maybe remove the repeated word "Advertisement" that gets generated along with the chapter text and into the epub from two different sources. But, to make it easier, I'll put them in two different issues :) This issue is for the first source [https://knoxt.space/].

Please refer to the following image references. This is how it appears on the source itself, where it appears every few paragraphs:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/5283d5cd-2b50-4d75-b086-9423e24703f0)

This is from the page source of the chapter itself:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/f51d0b9a-d4d6-4111-9b03-a6a602395983)

And lastly, this is an example of the text generated into the epub that I was hoping for **all such code blocks to be removed**:

```
<div class="code-block code-block-2" style="margin: 8px 0; clear: both;">
<p style="text-align: center;">
  <div style="padding: 20px;">Advertisement</div>
</p>

</div>
```

The only changing variable in the above example is the "code-block-#". Hoping this is possible, thank you very much for your time and effort!

**Comment by dteviot** [comment]
@loriette-01 

Updated WebToEpub anyway.  
Note, while removed from chapters, they remain on the information page.
Reopen, so know to notify you when version in Chrome and Firefox stores updated.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://knoxt.space/the-master-of-metaphysics-just-wants-to-quit-the-circle/, chapter 1

For my notes: 7 minutes work

**Comment by dteviot** [comment]
@loriette-01 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
