### ISSUE TITLE
This Site Also Has the Same Issue, Please Remove the Word "Advertisements" From Within the Chapter Text

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1103]
Hello!

This second site also has a similar problem as the other one [**https://secondlifetranslations.com/**]. But, unlike the first site, the excessive repetition of the word "Advertisements" does not actually appear within the chapter text on the website itself and only appears within the Page Source and the epub file itself.

Please refer to the following image references. This is how it appears in the page source, but this is not the full text because the line is rather long so part of the code is cut off in this image, please look to the below code block for the complete segment:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/c1e8779d-b6e0-41be-adde-68cd77bd32c2)

And, this is an example of the text generated into the epub that I was hoping for all such code blocks to be removed:

```
<div class="code-block code-block-14" style="margin: 8px auto; text-align: center; display: block; clear: both;">
<div class="code-block-label">Advertisements</div>

</div>
```

Similar to the other source, the only changing variable in the above example is the "code-block-#". Again, thank you very much for your time and effort! :D

**Comment by dteviot** [comment]
@loriette-01 
> This second site also has a similar problem

You didn't tell me what this second site is.
That said, this looks like a job for EpubEditor.  See https://github.com/dteviot/EpubEditor/issues/4
The CSS selector to put in the script should be:
```css
.code-block, .code-block-label
```

**Comment by dteviot** [comment]
@loriette-01 

Updated WebToEpub anyway.
Reopen, so know to notify you when version in Chrome and Firefox stores updated.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://secondlifetranslations.com/novel/cnch/ chapter 2

For my notes: 14 minutes work

**Comment by dteviot** [comment]
@loriette-01 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
