### ISSUE TITLE
Please add site https://novel-next.com

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#1107]
Hello,

Is it possible to add this website. Here is an example : 

https://novel-next.com/novelnext/martial-world-novel

Thank you very much for all your works :)

**Comment by dteviot** [comment]
@Flwk 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novel-next.com/novelnext/martial-world-novel, chapters 1 &amp; 2

Note, to get full list of chapters, select the "Chapter List" tab and wait for list to load before opening WebToEpub

For my notes: 14 minutes work  (Site was another copy of Novelfull)

**Comment by Flwk** [comment]
@dteviot Thank you very much !

**Comment by dteviot** [comment]
@Flwk 
Reopen so I know to notify you when version in Chrome and Firefox stores is updated.

**Comment by dteviot** [comment]
@Flwk 

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
