### ISSUE TITLE
https://kemono.su

### ISSUE THREAD

**Issue by Hiragi3k** [dteviot/WebToEpub#1109]
Webtoepub was working before to crawl epubs from various webnovels that were added to the site from different patreons. A few days ago it stopped working. Would appreciate if it was possible to have it work on the site once more.

**Comment by dteviot** [comment]
@Hiragi3k 
Please provide URL to at least one of the webnovels

**Comment by Hiragi3k** [comment]
https://kemono.su/patreon/user/22614979
https://kemono.su/patreon/user/38971397
https://kemono.su/patreon/user/21149764

Much thanks.

**Comment by Hiragi3k** [comment]
@dteviot 

https://kemono.su/patreon/user/22614979
https://kemono.su/patreon/user/38971397
https://kemono.su/patreon/user/21149764

Much thanks.

**Comment by dteviot** [comment]
I tried
* https://kemono.su/patreon/user/22614979, chapter 848
* https://kemono.su/patreon/user/38971397, chapter 27

Both seem to work fine with the latest test build.  Note, I you might have run into the site changing it's name from kemono.party.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 10 minutes work

**Comment by Hiragi3k** [comment]
Works perfectly now. Much thanks.

**Comment by dteviot** [comment]
@Hiragi3k
Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
