### ISSUE TITLE
Fetch of url error on gravitytales

### ISSUE THREAD

**Issue by AndreaHasani** [dteviot/WebToEpub#111]
I'm getting this error when trying to make epubs from gravity site.

Fetch of URL 'https://gravitytales.com/Novels/GetChapterGroups/5' failed with network error 404. Error: Fetch of URL 'https://gravitytales.com/Novels/GetChapterGroups/5' failed with network error 404.
at Function.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:31:35)
at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31

I'm sure this error started happening on this month since I was to make epubs fine from gravity.

Thanks

**Comment by dteviot** [comment]
@AndreaHasani
Thank you for bringing this to my attention.
GravityTales site had changed it's REST API.
I've updated the extension and checked new version (0.0.0.32) into Chrome store.  Your copy should update automatically within 24 hours.
