### ISSUE TITLE
Remove thank you headers from Chapters.

### ISSUE THREAD

**Issue by LinkofHyrule89** [dteviot/WebToEpub#1110]
I'm not sure if this is really possible or not but it would be nice if it was. On https://nyx-translation.com/ they have Thank you headers on each chapter. They do have somewhat of a format but not exactly the same so not sure if it's automatable or not. There are double lines before the actual chapter starts though so maybe detect the chapter title ignore the text after that and start chapter text after the double lines?

<img width="564" alt="image" src="https://github.com/dteviot/WebToEpub/assets/3983279/0cd7d532-85aa-4066-894b-2c0b5c0ab4fc">

Here's the Chapter Page https://nyx-translation.com/striving-for-the-luxury-liner-get-that-rich-isekai-life-with-a-ship-summoning-skill-wn/

Thanks for your hard work!

**Comment by dteviot** [comment]
@LinkofHyrule89 
I'm not prepared to do this.  I'm not confident that the site will format every page the same way, so doing this might delete something important.  For that matter, some people might consider the thank you important.

That said, if you want to clean up the epubs after you download them, you could look at calibre or https://github.com/dteviot/EpubEditor https://github.com/dteviot/EpubEditor/issues/4

**Comment by LinkofHyrule89** [comment]
I understand! Thanks for your reply!
