### ISSUE TITLE
Please add site https://raeitranslations.com/

### ISSUE THREAD

**Issue by Wonkie-wow** [dteviot/WebToEpub#1111]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://raeitranslations.com/the-academys-time-stop-player

### Did you try using the Default Parser for the site?  If not, why not?
Used default parser and worked

### What settings did you use?  What didn't work?
As stated above, used the default parser and settings and was able to get the ToC, however when attempting to convert pages to epub, I get hit with a warning that the content element for web page has no visible content and leaves the downloaded epubs blank.

**Comment by dteviot** [comment]
@Wonkie-wow 

Notes, 
1. You'll need to manually expand the chapters before opening WebToEpub
2. You may want to adjust the stylesheet, to show status pannels in a different color.  e.g. for https://raeitranslations.com/i-became-a-third-rate-villain-in-the-hero-academy, to show status in green add following to stylesheet.
```ccs
div.status {
    color: #00FF00
}
```

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://raeitranslations.com/i-became-a-third-rate-villain-in-the-hero-academy, chapter 1 and 2

For my notes: 90 minutes work

**Comment by dteviot** [comment]
@Wonkie-wow 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
