### ISSUE TITLE
Please add site https://faloomtl.com/

### ISSUE THREAD

**Issue by lomborton** [dteviot/WebToEpub#1115]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by lomborton** [comment]
Укажите URL-адрес веб-страницы, содержащей оглавление (список глав) типичной истории на сайте.

https://faloomtl.com/series/my-longevity-simulation/

**Comment by dteviot** [comment]
@lomborton 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://faloomtl.com/series/my-incompetent-reign-gifting-the-kingdom-at-the-beginning-becoming-an-eternal-emperor/, chatper 1 &amp; 2

For my notes: 15 minutes work

**Comment by masteoo** [comment]
@dteviot hello, sorry to disturb, could you please download this novel? There are 1686 chapters and I don't know how to use the extension. Thanks
https://en.readerexp.com/virginity-in-second-marriages-bd269.html

**Comment by dteviot** [comment]
@masteoo 

That site isn't currently supported.  
Create a new issue requesting that site.  
To make tracking my to do items easier, one site per issue, please.

**Comment by dteviot** [comment]
@masteoo 
Looks like default parser might work for that site.
Here's the instructions.
https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

**Comment by masteoo** [comment]
> @masteoo Looks like default parser might work for that site. Here's the instructions. https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Thanks, I tried but failed 😔 . I cannot see all the 1686 chapters

**Comment by dteviot** [comment]
@masteoo 
D'oh!  Right,  Problem is ToC is chunked into sets of 36 chapters.
Please create new issue and I'll add to the queue.  (Actually, as this looks like it might be an easy one to do, I **might** do it tonight.)

**Comment by masteoo** [comment]
> @masteoo D'oh! Right, Problem is ToC is chunked into sets of 36 chapters. Please create new issue and I'll add to the queue. (Actually, as this looks like it might be an easy one to do, I **might** do it tonight.)

@dteviot wow thanks a lot! I just need epub and than I will find a way to translate all the text in Italian language:)

**Comment by dteviot** [comment]
@lomborton

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
