### ISSUE TITLE
Slow pull from royalroad

### ISSUE THREAD

**Issue by blacksan** [dteviot/WebToEpub#1116]
**Describe the bug**

Pulls from royalroad are extremely slow

**To Reproduce**
Download anything from epub

**Expected behavior**

Slow slow pulls

**Comment by dteviot** [comment]
@blacksan 
Site is doing rate limiting.  Go to Advanced options and make sure rate is set to 5 seconds/page and only 1 page at a time.
Otherwise you'll trigger it.
