### ISSUE TITLE
Please fix site https://shanghaifantasy.com/ (ver2. site has been reprogrammed it seems)

### ISSUE THREAD

**Issue by Naanaa28** [dteviot/WebToEpub#1117]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site:  https://shanghaifantasy.com/novel/farm-girls-space-picking-up-a-major-villain-during-the-runaway-journey/

This is just a shot in the dark but they kind of reworked the website. WebtoPub worked on it before but now they made it so that the site itself cannot be read at all (it's very protected. Cant even right click on anything to inspect.) I understand they probably did that /so/ webtopub and etc. doesn't work buuuut... I am making a request here anyway. Just in case. Please excuse me. (for more info I have discovered that a different page/tab to epub converter extension still works so it shouldn't be completely unreadable)

### Did you try using the Default Parser for the site?  If not, why not? ---- The site is view only and cannot be read.
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work? --- Everything as far as I know
* URL of first chapter - https://shanghaifantasy.com/farm-girls-space-picking-up-a-major-villain-during-the-runaway-journey-chapter-1/
* CSS selector for element holding content to put into EPUB - body or div, but both turn up with just the site logo, and anything else pulls up as an error
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@Naanaa28 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://shanghaifantasy.com/novel/farm-girls-space-picking-up-a-major-villain-during-the-runaway-journey/, chapters 1 &amp; 120

For my notes: 98 minutes work

**Comment by Naanaa28** [comment]
Hello! The Chrome test version works like a charm!! But somehow it doesn't read punctuations on the chapter titles well on the somehow, i.e. The Villain&amp;#8217;s Father&amp;#8217;s But that's the only thing. Thank you!

**Comment by dteviot** [comment]
@Naanaa28 
It's issue with encoding going from JSON to HTML.
While the titles shown in WebToEpub look funny, they seem to be OK in the generated EPUB.  So, I'm not going to worry about it.  If I'm wrong, please provide URL that shows issue.

**Comment by dteviot** [comment]
@Naanaa28 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
