### ISSUE TITLE
Please add site wuxiabee.com

### ISSUE THREAD

**Issue by Mielanjelo** [dteviot/WebToEpub#1121]
Hi if it's not too much a bother can you add a parser for https://www.wuxiabee.com/
It was formerly https://wuxiap.com/or https://readwn.com and WebToEpub worked just fine before, but they changed something and the domain so the parser broke
Please fix that, thanks

**Comment by dteviot** [comment]
@Mielanjelo 

@Kiradien provided a fix (thank you)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiabee.com/novel/when-did-i-become-invincible.html, chapters 1, 500

For my notes: 10 minutes work

**Comment by dteviot** [comment]
@Mielanjelo 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
