### ISSUE TITLE
https://secondlifetranslations.com epubs become gibberish

### ISSUE THREAD

**Issue by Naanaa28** [dteviot/WebToEpub#1124]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site:   https://secondlifetranslations.com/novel/after-being-turned-into-a-dog-i-conned-my-way-into-freeloading-at-my-rivals-place/
 
Issue: The epubs created from the site now contains becomes scrambled paragraphs/gibberish text as well as a notice in big bold letters like with the old Chrysanthemum Garden issue. However sadly the Clean Chrysanthemumgarden option from EpubEditor doesn't work on them like it does with CG epubs so I suppose the codes are different.

Please excuse me.

**Comment by dteviot** [comment]
@Naanaa28 

Duplicate.  See: https://github.com/dteviot/WebToEpub/issues/1043 **for fix.**

**Comment by Naanaa28** [comment]
Hello. I did as instructed but it looks like the watermark wasn't removed and there is also an &nsbp at the end of each of the unscrambled paragraphs. 
![Screenshot (1)](https://github.com/dteviot/WebToEpub/assets/151754223/7d272305-604c-4aa7-bf87-8fe31e70e538)
