### ISSUE TITLE
Update existing file with new chapters. Feature Request

### ISSUE THREAD

**Issue by d5364t54ytfr4** [dteviot/WebToEpub#1129]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to download the whole novel from the beginning if there are new chapters. Also, downloading too much triggers the wordpress bot detection algorithms.

**Describe the solution you'd like**
Give an option to update an existing book by downloading only new chapters and creating a new .epub based on that.
You could have an option to upload an existing book  into the browser and then update the chapters and then give the download with updated chapters since browsers probably don't allow editing files on disk.
The addon should even be able to parse the novel link and automatically scrape the links.

For example FanFicHub, the calibre addon supports downloading new chapters without downloading all the chapters from the beginning.

**Comment by gamebeaker** [comment]
@d5364t54ytfr4 the Add to Library function solves your problem [https://github.com/dteviot/WebToEpub/wiki/Library](https://github.com/dteviot/WebToEpub/wiki/Library)
