### ISSUE TITLE
Please add site https://www.wuxiago.com

### ISSUE THREAD

**Issue by TrailNumber** [dteviot/WebToEpub#1130]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.wuxiago.com/novel/global-killing-awakening-sss-level-talent-at-the-beginning.html

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
I have no idea what I am doing.

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
I know nothing about coding.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I don't need friends; they disappoint me.

Also, thank you for the hard work.

**Comment by dteviot** [comment]
@TrailNumber 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiago.com/novel/global-killing-awakening-sss-level-talent-at-the-beginning.html, chapter 1

For my notes: 19 minutes work  (Mostly finding the existing parser for this site format.)

**Comment by TrailNumber** [comment]
@dteviot
Thank You Kind Sir.
