### ISSUE TITLE
Kakuyomu Site Changes Broke Parser

### ISSUE THREAD

**Issue by MPTSakurada** [dteviot/WebToEpub#1131]
**Describe the bug**
The Kakuyomu site parser no longer fully works as the main work page has been changed. The selectors have changed, but it also seems that chapter links are not all loaded into the html by default.

**To Reproduce**
1. Go to a works page (eg https://kakuyomu.jp/works/1177354054894027232)
2. Click on the WebToEpub button
3. WebToEpub fails to properly scrape any details beyond the language
4. Clicking Pack Epub gives `Error: No chapters found.`

**Expected behavior**
Metadata should be extracted from page along with links to individual chapters. Packing epub should begin downloading pages.

**Desktop (please complete the following information):**
 - OS: macOS 14.1.2
 - Browser Chrome
 - Version 118.0.5993.96 (Official Build) (arm64)

**Additional context**
- Going to an individual chapter page (eg https://kakuyomu.jp/works/1177354054894027232/episodes/1177354054894027298) results in the chapters being discovered, though metadata still isn't correctly detected. Attempting to Pack Epub from that page works, though the TOC generated doesn't match the hierarchy of the site's
- The main page no longer has all of the links loaded into the html, but does have a JSON in a `<script id="__NEXT_DATA__" type="application/json">` that contains all of the IDs of the TOC, but also contains data for reviews etc.

**Comment by dteviot** [comment]
@MPTSakurada 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kakuyomu.jp/works/1177354054894027232, chapters 1 to 10

Notes.
* Thanks for the tip about script tag
* Was not able to extract author.
* For my notes: 99 minutes work

**Comment by MPTSakurada** [comment]
Thanks for the quick fix, @dteviot!

It seems to work great for the initial one I linked, and a few others I tested
Those being:
- https://kakuyomu.jp/works/1177354054886530454
- https://kakuyomu.jp/works/16816700426916845204
- https://kakuyomu.jp/works/16817330659832998605

However, others don't work and give
`tocc.chapter is null buildSubToc@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/parsers/KakuyomuParser.js:32:23
buildToc@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/parsers/KakuyomuParser.js:20:18
getChapterUrls@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/parsers/KakuyomuParser.js:11:21
onLoadFirstPage@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/Parser.js:378:14
processInitialHtml@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/main.js:47:24
populateControlsWithDom@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/main.js:252:27
onMessageListener@moz-extension://27eb8edd-70fe-4ee5-b888-5546a3d63e98/js/main.js:16:36`

I _think_ it might have something to do with how many sections the chapters are split into, total number of chapters, or a combination of the two. All the ones I tested which didn't work were relatively short.
- https://kakuyomu.jp/works/16817330667740926717
- https://kakuyomu.jp/works/4852201425155006107
- https://kakuyomu.jp/works/16816927861548337782
- https://kakuyomu.jp/works/16817330661875063991

As for the author, I don't know how feasible it is with the parser structure, but there are a couple of places you might be able to extract it from:
- It's the last thing enclosed in full width brackets `（）` before ` - カクヨム` in the title tag.
- It's the first instance of `activityName` in the json (as a sanity check, since there seem to be a lot of activityName elements in the json, it seems to be the only one who has >5 sibling nodes)
- It's the text content of the first `.partialGiftWidgetActivityName` (`document.querySelector(".partialGiftWidgetActivityName").textContent` seems to return the right name on the ones I checked)

**Comment by dteviot** [comment]
@MPTSakurada 

OK, I think I've fixed the issue with the four failing stories above.  (At least one "story arc" was missing a title.)
Also fixed fetching the Author, using your suggestion.  

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* See above

For my notes: 152 minutes work (total)

**Comment by MPTSakurada** [comment]
Thanks, that seems to work perfectly now.

**Comment by dteviot** [comment]
Reopen, so I know to notify you when version in Chrome and Firefox stores is updated.

**Comment by MPTSakurada** [comment]
I'm not sure what's changed now, but using the first test link (https://kakuyomu.jp/works/1177354054894027232) but when using the beta version on firefox (120.0.1) I now get 
```tocc.episodes is undefined buildSubToc@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/parsers/KakuyomuParser.js:33:31
buildToc@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/parsers/KakuyomuParser.js:20:18
getChapterUrls@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/parsers/KakuyomuParser.js:11:21
onLoadFirstPage@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/Parser.js:378:14
processInitialHtml@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/main.js:47:24
populateControlsWithDom@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/main.js:252:27
onMessageListener@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/main.js:16:36```

And on a chapter page (like https://kakuyomu.jp/works/1177354054894027232/episodes/1177354054894027298) I get 
```dom.querySelector(...) is null buildToc@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/parsers/KakuyomuParser.js:15:26
getChapterUrls@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/parsers/KakuyomuParser.js:11:21
onLoadFirstPage@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/Parser.js:378:14
processInitialHtml@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/main.js:47:24
populateControlsWithDom@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/main.js:252:27
onMessageListener@moz-extension://6ba59952-0da8-41c4-91ac-bc806803195f/js/main.js:16:36```
I'm assuming the second is because of the lack of JSON on that page.

You probably don't want to be troubleshooting this kind of thing around Christmas/New Year, so whenever you can get around to it, I'll appreciate it.

**Comment by dteviot** [comment]
@MPTSakurada 

Fixed for https://kakuyomu.jp/works/1177354054894027232

Not going to fix for "list of chapter" pages like https://kakuyomu.jp/works/1177354054894027232/episodes/1177354054894027298, as that's a different layout and would double my work.  And if works for the other layout

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kakuyomu.jp/works/1177354054894027232

For my notes: 26 minutes work

**Comment by MPTSakurada** [comment]
Tested it and it seems to work fine. Thanks again!

**Comment by dteviot** [comment]
@MPTSakurada 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
