### ISSUE TITLE
https://www.pandasnovel.com/details/apocalypse-cheater-2135/chapters

### ISSUE THREAD

**Issue by goalhunter960** [dteviot/WebToEpub#1134]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
it works but it says that the site has captcha so it can't continue.

**Comment by goalhunter960** [comment]
this is the error it shows:  WARNING: Site 'www.pandasnovel.com' has sent an Access Denied (403) error.  You may need to logon or satisy a CAPTCHA before WebToEpub can continue.

**Comment by Kiradien** [comment]
Does it fail on the first chapter or after a few?

Do you have the Advanced Option "Manual Throttle" set? If so, how many seconds?

**Comment by dteviot** [comment]
@goalhunter960 

This is a known issue.

For this site, you need to solve a CAPTCHA before it will let WebToEpub see chapters.
See: https://github.com/dteviot/WebToEpub/issues/784#issuecomment-1242952433 onwards

I just tested, and it's working for me after the "I am not a robot" window appears and is ticked.
Also, make sure you don't try to download more than 1 page at a time, at a rate of 3 seconds or more per page.
