### ISSUE TITLE
Fanfiction.net acess denied

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#1135]
**Describe the bug**
This is the error I am getting whenever trying to download a sotry
WARNING: Site 'www.fanfiction.net' has sent an Access Denied (403) error.  You may need to logon or satisy a CAPTCHA before WebToEpub can continue.

**To Reproduce**

**Expected behavior**
pack the epub with all the chapters
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kiradien** [comment]
Sounds like typical Cloudflare - it happens a lot if you're using a vpn but can happen without it. You need to open up a new chapter (one that hasn't already successfully loaded for generation) and complete the captcha.

I personally recommend manually using the advanced setting "Manual Throttle" set at 5+ seconds to minimize encounters with this issue.

**Comment by jklly12** [comment]
I've Tried this solution and it doesn't work

**Comment by dteviot** [comment]
@kolbdog3333 @jklly12 

I just tried.  After filling in the Cloudflare "are you a human" CAPTCHA, it worked for https://www.fanfiction.net/s/14100933/1/Warrior-plus-Vampire.

I can't help you further.
