### ISSUE TITLE
Please add site [https://ninetysevenkoi.wordpress.com/]

### ISSUE THREAD

**Issue by loriette-01** [dteviot/WebToEpub#1137]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://ninetysevenkoi.wordpress.com/wildfire/**

### Did you try using the Default Parser for the site?  If not, why not?
Yes, I did, but this site proved a little more difficult to remove all the extraneous elements, specifically in the footer.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

Regarding the second input, I tried to just select the "novel content" but couldn't find the right selector for the "body" because other unwanted elements still remained within the main selector for the chapter text.

**Comment by dteviot** [comment]
@loriette-01 
You can use the default parser for this site.
You just need to set "(required) CSS selector for element holding content to put into EPUB" to ".entry-content"  (Ignore the quotes, and don't miss the full stop at the start.)  e.g.
![image](https://github.com/dteviot/WebToEpub/assets/5157081/dbbbf6bf-5cba-4916-aa0b-d87c5d1c9512)


And then press "Apply"

**Comment by loriette-01** [comment]
Thank you so much!! And I'm sorry to bother again, but can I perhaps ask for how to find the CSS Selector for the "Chapter Number" heading, i.e. the [CSS selector for element holding Title of Chapter].

Only the novel content itself was grabbed, so I was wondering how to also select the title? I located where the heading is using the Inspect tool, but despite inputting the CSS selector, the chapter heading still didn't appear... If it's okay to input here, the selectors I tried are the ones below:

> #wp--skip-link--target > div:nth-child(1)
> 
> #wp--skip-link--target > div:nth-child(1) > div.wp-block-group.is-nowrap.is-layout-flex.wp-container-core-group-layout-2.wp-block-group-is-layout-flex
> 
> #wp--skip-link--target > div:nth-child(1) > div.wp-block-group.is-nowrap.is-layout-flex.wp-container-core-group-layout-2.wp-block-group-is-layout-flex > h1

Thank you again for all your help!! :D

**Comment by loriette-01** [comment]
> Did you try "h1"?

Yes, but that's just the site name haha, not the chapter title. But it's okay, I figured it out!

It was: "**.wp-block-post-title**"

Thank you for your help! :)
