### ISSUE TITLE
https://novelsemperor.com/ - the extension will not work if a novels has less than 100 chapters.

### ISSUE THREAD

**Issue by abetestnow** [dteviot/WebToEpub#1138]
The extension will not work if a novels has less than 100 chapters.  

For example:

https://novelsemperor.com/series/people-are-eating-halberds-exiting-totsuki-academy-at-the-beginning

pagination is null nextTocPageUrl@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/parsers/NovelsemperorParser.js:32:17
walkTocPages@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/Parser.js:687:33
getChapterUrls@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/parsers/NovelsemperorParser.js:11:28
onLoadFirstPage@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/Parser.js:378:14
processInitialHtml@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/main.js:47:24
populateControlsWithDom@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/main.js:252:27
onMessageListener@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/main.js:16:36

https://novelsemperor.com/series/great-voyage-many-children-many-blessings-reviving-the-d-family

pagination is null nextTocPageUrl@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/parsers/NovelsemperorParser.js:32:17
walkTocPages@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/Parser.js:687:33
getChapterUrls@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/parsers/NovelsemperorParser.js:11:28
onLoadFirstPage@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/Parser.js:378:14
processInitialHtml@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/main.js:47:24
populateControlsWithDom@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/main.js:252:27
onMessageListener@moz-extension://749b5540-54c7-4b72-8c57-31762c723020/js/main.js:16:36

**Comment by dteviot** [comment]
@abetestnow 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelsemperor.com/series/people-are-eating-halberds-exiting-totsuki-academy-at-the-beginning

For my notes: 12 minutes work

**Comment by abetestnow** [comment]
I have just tried it out and it worked perfectly.
Thanks for the quick response and for maintaining this extension!

**Comment by dteviot** [comment]
@abetestnow 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
