### ISSUE TITLE
Failed to get images in forum.questionablequesting.com

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#1141]
I checked in three fictions, and they all failed to get any images.
so I checked the error log and find that the link to the images in the epub is different from the site

from epub:
https://forum.questionablequesting.com/threads/ever-play-competitive.23597/proxy.php?image=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F896775938669436929%2F1144301644322983976%2FCloudPicture1.png&hash=fced95e869ec4a3cea42b9e063b9c735

from site:
https://forum.questionablequesting.com/proxy.php?image=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F896775938669436929%2F1144301644322983976%2FCloudPicture1.png&hash=fced95e869ec4a3cea42b9e063b9c735

the one from the epub, if put in web browser returns error 404, but the one in the site works just fine. please fix this.
the image is from chapter 1 of this fic:
https://forum.questionablequesting.com/threads/ever-play-competitive.23597/

**Comment by dteviot** [comment]
@SpiralBaka 
Looks like a fix was posted for this https://github.com/dteviot/WebToEpub/issues/1112.
Version in stores has not been updated with this fix yet.  Only the Test versions have it.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, I have not verified it works for the supplied URL, as I can't access it.  I think I need an account on the site.

**Comment by SpiralBaka** [comment]
it still doesn't work.
but I got a new info, this one also applies to previous version:
it works for images that isn't in spoiler tag, but doesn't work for one inside a spoiler tag. 

example of one that works:
https://forum.questionablequesting.com/threads/an-arc-for-every-season-team-rwby-maiden-fic.24830/
https://forum.questionablequesting.com/threads/another-way-pok%C3%A9mon-mystery-dungeon-oc-isekai.23106/
the images in those two worked.

example of one that doesn't work:
https://forum.questionablequesting.com/threads/ice-pie-spyxfamily-si.10724/
'chapter seven and eight' has one image in spoiler tag. it doesn't work.

https://forum.questionablequesting.com/threads/shiro-tokita-has-a-weird-visitor-evangelion-fanfic-canon-character-protagonist-og-eva-rebuilds.21905/
the prologue, chapter 3, 4, and many other, has many images in spoiler tag, none worked.

you should be able to test those, since they're not in nsfw section. in fact, I tested them in private browsing.

**Comment by dteviot** [comment]
@SpiralBaka 

OK, I think (hope?) I've got it fixed.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://forum.questionablequesting.com/threads/ice-pie-spyxfamily-si.10724/, chapter "seven and eight"
* https://forum.questionablequesting.com/threads/an-arc-for-every-season-team-rwby-maiden-fic.24830/ chapter 1
* https://forum.questionablequesting.com/threads/shiro-tokita-has-a-weird-visitor-evangelion-fanfic-canon-character-protagonist-og-eva-rebuilds.21905/ chapter 3 and 4

For my notes: 99 minutes work
That really wasn't fun.  There were 3 separate bugs.
1. host can be "questionablequesting.com" and "forum.questionablequesting.com"
2. did not correctly handle case of no "data-url" property
3. common code in ImageCollector was overriding fixed value

**Comment by dteviot** [comment]
@SpiralBaka 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
