### ISSUE TITLE
Cannot find all the chapters on noveldrama.com 

### ISSUE THREAD

**Issue by masteoo** [dteviot/WebToEpub#1142]
Please help to download all the chapters of a book. The book has a thousand chapters. Thanks (please note that I have only Tab S8 and kiwi browser)

https://en.readerexp.com/virginity-in-second-marriages-bd269.html

**Comment by dteviot** [comment]
@masteoo 
Do you want noveldrama or en.readerexp.com?  They seem to be different.

**Comment by masteoo** [comment]
@dteviot the book is the same, you can choose the easiest website for you:)
I prefer noveldrama

**Comment by dteviot** [comment]
@masteoo 
Unfortunately, both sites are encrypting the content of each chapter.
And it's against Google's terms of service for an extension to decrypt this sort of thing.  Doing so would have WebToEpub removed from the Chrome store.
So, sorry, I can't help you here.

For my notes: 52 minutes work.

**Comment by masteoo** [comment]
> @masteoo Unfortunately, both sites are encrypting the content of each chapter. And it's against Google's terms of service for an extension to decrypt this sort of thing. Doing so would have WebToEpub removed from the Chrome store. So, sorry, I can't help you here.
> 
> For my notes: 52 minutes work.

@dteviot ok:( understood. Thanks for your time

**Comment by masteoo** [comment]
@dteviot just thinking..maybe u can just pass me .zip mod extension without load it on chrome store if you want:)

**Comment by dteviot** [comment]
@masteoo 
I'd have to decrypt the content, that's going to take a while.  But I'll see what I can do.  I'm a little occupied at moment.

**Comment by masteoo** [comment]
@dteviot ok, thanks a lot for your effort, I appreciate.

**Comment by dteviot** [comment]
@masteoo 

Merry Christmas

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://en.readerexp.com/virginity-in-second-marriages-bd269.html, chapter 1 and 1686

Notes:
1. You might want to start with an epub with just one chapter (e.g. chapter 1) and see if it works.
2. As well as AES encryption, it's also using CSS to scramble the content.  Depending on your reader this may or may not be handled.  Please let me know if it's a problem
3. I've assume the encryption codes are fixed (I sampled a couple of chapters, and all the codes were the same)  So, to make my life easy, I've hardcoded them.  I don't know how long they will be good for.

For my notes: 185 minutes work  (total)

**Comment by masteoo** [comment]
@dteviot thanks a lot and Merry Christmas! 🤗 I will test it on my Tab S8!
Do u know if it works also for noveldrama.com? Thanks again

**Comment by dteviot** [comment]
@masteoo 
> Maybe u can give me a hint how to translate the epub in italian.

I don't understand the question.  Are you asking me how to machine translate any epub into Italian?
If so, I suggest you try searching on Google.  It's not something I've tried.

> Do u know if it works also for noveldrama.com?

It does not.  It works for https://en.readerexp.com  That site was easier to decrypt.

**Comment by masteoo** [comment]
@dteviot thanks for your feedback, it's difficult to find epub translator. I thought that using G traslate link [https://en-readerexp-com.translate.goog/virginity-in-second-marriages-bd269.html?_x_tr_sl=auto&_x_tr_tl=it&_x_tr_hl=it&_x_tr_pto=wapp] I could pack epub in Italian 😔

**Comment by masteoo** [comment]
@dteviot sorry, just read on issues that not possible to integrate G translate on this app, sorry again. I tried also this https://github.com/quantrancse/epub-translator but not working :(

**Comment by masteoo** [comment]
@dteviot
[Virginity marriages.txt](https://github.com/dteviot/WebToEpub/files/13854357/Virginity.marriages.txt)
Hello and Happy new Year, sorry again, maybe you have a hint to suggest me to download ita version of this eng txt. Thanks again

**Comment by masteoo** [comment]
> It does not. It works for https://en.readerexp.com That site was easier to decrypt.

@dteviot hello, sorry to disturb but extension is no more working with this url:(
https://en.readerexp.com/wolf-president-hooks-up/chapter-1-r1.html
Could you fix it please? Thanks a lot

**Comment by dteviot** [comment]
@masteoo 

> @dteviot @ImLJS hello, sorry to disturb but extension is no more working with this url:(
https://en.readerexp.com/wolf-president-hooks-up/chapter-1-r1.html
Could you fix it please?

This issue is titled noveldrama.com and closed.  To help me keep track of things, please raise a new issue.
