### ISSUE TITLE
not able to download from panda.

### ISSUE THREAD

**Issue by ghost** [dteviot/WebToEpub#1143]
**Describe the bug**

**To Reproduce**
1. Go to '[Panda](https://www.panda-novel.com/top)'
2. Click on 'any novel'
3. Scroll down to 'chapter list and open it'
4. Click on 'webtoepub'
5. Click on 'Pack epub'
6. See 'error'

**Expected behavior**
For the downloads to work.
I can view the page in the browser and there is no captcha or login required to view the chatper, but the pop-up still does not close.

**Screenshots**

https://github.com/dteviot/WebToEpub/assets/154743608/683ac4ec-a95f-4af0-b580-ff164ab104f2

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [firefox]
 - Version [121]

**Comment by dteviot** [comment]
@ghost @zeoint 

This is a known issue.  

For this site, you need to solve a CAPTCHA before it will let WebToEpub see chapters.
See: https://github.com/dteviot/WebToEpub/issues/784#issuecomment-1242952433 onwards

I just tested, and it's working for me after the "I am not a robot" window appears and is ticked.
