### ISSUE TITLE
Please add site https://www.lightsnovel.com

### ISSUE THREAD

**Issue by zeoint** [dteviot/WebToEpub#1144]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

- https://www.lightsnovel.com/details/surviving-the-zombie-apocalypse-with-my-military-system(1)-2155/chapters

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

- Yes.

### What settings did you use?  What didn't work?
* URL of first chapter - [Link](https://www.lightsnovel.com/content/surviving-the-zombie-apocalypse-with-my-military-system(1)-2155-1730446/chapter-1)
* CSS selector for element holding content to put into EPUB **- #novelArticle2**
* CSS selector for element holding Title of Chapter **- .novel-content > h2:nth-child(1)**
* CSS selector for element(s) to remove **- #scriptList0, #scriptList4, #scriptList1, #novelArticle2 > p:nth-child(40)**

**1.** Out of 218 chapters only the first 30 chapters showed up when I clicked apply.
**2.** Also the chapters have dates beside them, I don't know how to remove them.

---

https://github.com/dteviot/WebToEpub/assets/127277950/ef1a47a6-0a4e-453f-9d36-7c631ec57f07

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

- None.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

- None.

### If you tried writing a parser, and it doesn't work.  Attach the parser here.

- None.

**Comment by dteviot** [comment]
@zeoint 

Thank you for telling me that it's like an existing, supported site.  That saves me a lot of time.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.lightsnovel.com/details/surviving-the-zombie-apocalypse-with-my-military-system(1)-2155, chapters 1 &amp; 68

For my notes: 20 minutes work

**Comment by dteviot** [comment]
@zeoint 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
