### ISSUE TITLE
AO3 doesnt work

### ISSUE THREAD

**Issue by Kuratius** [dteviot/WebToEpub#1145]
**Describe the bug**
Trying to get a story from AO3 results in an error.

**To Reproduce**
1. Go to site.
2. Click the WebToEpub extension button.
3. 

**Expected behavior**
Downloading should be allowed.

**Screenshots**
![grafik](https://github.com/dteviot/WebToEpub/assets/47481645/d259fc03-b60b-47c8-93aa-3d5ed6bc8337)

![grafik](https://github.com/dteviot/WebToEpub/assets/47481645/dc8299e0-c3d7-4f2e-84c9-42d32763276e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 
 - Version 121.0

**Comment by arisboch** [comment]
I tried to reproduce (Kubuntu 23.10):
MS Edge 120.0.2210.91 & WebToEpub *.156 (from Google Chrome store): It worked
Firefox 121 & WebToEpub *.156: It worked
You're using an obsolete version of the extension, try to download the newest version.

**Comment by Kuratius** [comment]
You're wrong 
![grafik](https://github.com/dteviot/WebToEpub/assets/47481645/92def3bb-08f5-49d6-8209-fc7b5455239a)

**Comment by dteviot** [comment]
@Kuratius 

I just tried https://archiveofourown.org/works/50455516/chapters/127482139, and it seems to work as designed.

From your error message, I think you launched WebToEpub from a page with a format that WebToEpub does not know how to handle.  
Please 
1. Try the above URL and let me know if it works or fails.
2. If 1 works, provide the URL you were using that fails.

**Comment by dteviot** [comment]
@Kuratius 
I'll also add you don't need WebToEpub for Archive of our own.  The site provides the ability to download content in epub form directly, Just click on the "Download" button on the top right of the page and select "Epub"

**Comment by Kuratius** [comment]
> @Kuratius
> 
> I just tried https://archiveofourown.org/works/50455516/chapters/127482139, and it seems to work as designed.
> 
> From your error message, I think you launched WebToEpub from a page with a format that WebToEpub does not know how to handle. Please
> 
>     1. Try the above URL and let me know if it works or fails.
> 
>     2. If 1 works, provide the URL you were using that fails.

Your url works.
As for 2) you can see the url in the second screenshot I provided in case you didn't see it.

https://archiveofourown.org/works/46292428?view_full_work=true

**Comment by dteviot** [comment]
@Kuratius 

You're viewing in "full work" mode.
Change to chapter mode (click the "Chapter by Chapter" button near top right of page) and WebToEpub will work.

**Comment by Kuratius** [comment]
I don't  think it should be an issue. 
1. Using the full work URL would be better for downloading as it minimises requests
2. Even then the format of the url is essentially the same, just with an extra postfix. Better behaviour would be to ignore unknown postfixes.
