### ISSUE TITLE
Firefox Mobile - Mark as Android Compatible

### ISSUE THREAD

**Issue by duplaja** [dteviot/WebToEpub#1146]
**Is your feature request related to a problem? Please describe.**
Firefox just opened up browser extensions on mobile to any that are on addons.mozilla.org (which WebToEpub is) that are marked as Android compatible (which it is not). I'd love to be able to download epubs on the go.

**Describe the solution you'd like**
Unless it is non-functional, I'd like this plugin marked on addons.mozilla.org as Android compatible

**Describe alternatives you've considered**
I've been using the tool on my desktop, and then having to transfer it over.

**Additional context**
https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/

**Comment by dteviot** [comment]
@duplaja 

> Unless it is non-functional, I'd like this plugin marked on addons.mozilla.org as Android compatible

The last time I checked, it was not Android compatible.

**Comment by duplaja** [comment]
Thank you. I've had luck using it with other mobile browsers (Kiwi Browser, chromium based) with minor issues.

**Comment by duplaja** [comment]
I've successfully installed it in FireFox beta, using the workaround here: https://www.androidpolice.com/install-add-on-extension-mozilla-firefox-android/

I'll do that for now, but it does seem to be compatible, as far as my limited testing at least.

**Comment by dteviot** [comment]
@duplaja 
I'll take your word for it and mark the next update as working with Android.

**Comment by dteviot** [comment]
@duplaja 

Mozilla requires me to confirm that I've tested extension on Android before it will allow me to mark it as working on Android.
And I haven't personally tested it.

However, at it's an open source project, you could submit latest build to them, under your name

**Comment by duplaja** [comment]
Ahh, fair enough. I'm able to use it in Firefox beta via the list workaround, so I'll just keep doing that that.

**Comment by dteviot** [comment]
Want to think about this some more.  If you can verify the latest build in Mozilla store works on Android, I can bump the number and re-submit.

**Comment by grenskul** [comment]
I have also been using this with android ever since the extensions became available in Firefox nightly and it always worked fine.

**Comment by dteviot** [comment]
@kevin01523 @grenskul 
Which build were you using?  

- The "in development" build from Google Drive (if so, when did you download it) 
- Or a released version from the Firefox store (If so, which version?)

Thanks

**Comment by dteviot** [comment]
@kevin01523 
Thanks.  I'll probably be updating version in the stores in a few days.  I'll set the Firefox mobile flag when I do.

**Comment by dteviot** [comment]
@kevin01523 @duplaja @grenskul 

Updated version (0.0.0.159) is now available from Firefox stores, has been marked as compatible with Firefox for Android.
Sorry for delay in update, needed to get Patreon working.
