### ISSUE TITLE
Is it possible to create a Universal Default Parser to automatically work for all similarly configured free Wordpress sites?

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1149]
hi hiiiii!

i was wondering if it's probable to create a universal default parser that will automatically parse any Wordpress blog but also maintain the same clean output in the epub (i.e. only grab the heading and body content without any unnecessary elements)?

these sites are similarly structured and coded, so is it possible to maybe create a universal parser that will automatically parse these Wordpress blogs (it's the free site, not the specially designed ones).

below are a couple example Table of Contents that have this issue, where the Default Parser didn't exactly work for me because it took long for me to locate all the elements to remove via CSS Selectors and even then, there were still remaining extraneous elements that could not be removed.

https://noveltrans0.wordpress.com/swallowing-the-seas-%e5%90%9e%e6%b5%b7by%e6%b7%ae%e4%b8%8a/

https://mothmantl.wordpress.com/im-the-white-moonlight-of-the-paranoid-immortal-rebirth/

**Comment by dteviot** [comment]
@yuzucitrusx 

> i was wondering if it's probable to create a universal default parser that will automatically parse any Wordpress blog

Short answer: No.  

Longer answer:  WebToEpub already has code that tries to recognize wordpress sites.  Unfortunately, there are so many different layouts that it doesn't work very well.
