### ISSUE TITLE
Added more sane labels. Feedback appreciated.

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#115]
https://github.com/dteviot/WebToEpub/labels

Feedback is appreciated. The current labels fit most scenarios.

**Comment by dteviot** [comment]
I don't understand what the Status:Completed is for.  If Completed, then close.

**Comment by belldandu** [comment]
Some issue can be closed with `Status: Abandoned` or `Status: *fliptable*` and sometimes we may have an issue that may be currently completed but needs to be left open for some reason. The main reason though is so that we can distinguish issues at a glance whether they be open or closed. I plan to go through the closed issues soon an place the appropriate tags there as well.

**Comment by dteviot** [comment]
Closing.  Has been no more feedback in months.
