### ISSUE TITLE
Please add site https://novelmax.net

### ISSUE THREAD

**Issue by swanknight** [dteviot/WebToEpub#1151]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelmax.net/n/super-gene-optimization-fluid#tab-chapters-title

### Did you try using the Default Parser for the site?  If not, why not?
Yes. Not perfect, but it worked.

### What settings did you use?  What didn't work?
* URL of first chapter: **https://novelmax.net/n/super-gene-optimization-fluid/chapter-1**
* CSS selector for element holding content to put into EPUB: **div.chr-c**
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove: **script**

**Comment by dteviot** [comment]
@swanknight 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelmax.net/n/super-gene-optimization-fluid, chapter 1
 
For my notes: 10 minutes work

**Comment by swanknight** [comment]
@dteviot 

I just tested it on Edge, and it worked with a very minor issue.
If I visit the main novel page, and click the extension, it only detects 30 chapters.
But, if I go to the chapters list, and click the extension, it detects all chapters.
As I said, it's a very minor issue, but I thought you should know nonetheless.
Thanks a lot 😄

**Comment by dteviot** [comment]
@swanknight 
That's because the page doesn't load all the chapters until you click on the chapters list.
I'm not going to try fixing it.

**Comment by dteviot** [comment]
@swanknight 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
