### ISSUE TITLE
Wrong Language in EPUB causes ‘Send To Kindle’ to fail

### ISSUE THREAD

**Issue by arcaniia** [dteviot/WebToEpub#1154]
I recently discovered your plug-in and used it to download a few translated Chinese books from novelbin.net. The result is good except that when I use Amazon’s Send To Kindle service the upload fails. 

I then discovered [this site](https://kindle-epub-fix.netlify.app/) that fixes EPUB errors so that Send to Kindle will work. 

In all cases I tried, the error in question is
“Language ‘us’ is not supported by Kindle. Documents may fail to convert. Continue or specify new language in RFC 5646 format, e.g. en, fr, ja.”
When I enter ‘en’ and then use the fixed file, then Send To Kindle works fine. 

So I would like to request for the option to set the document language when using WebToEpub so that fixing the EPUB file is no longer required. I know it’s just a minor annoyance, so I just thought I’d ask in case other’s have had this problem and would benefit from a fix.

**Comment by dteviot** [comment]
@arcaniia 
Can I assume you found WebToEpub has the ability to set the language?  (It's the 4th item on the window.)
