### ISSUE TITLE
Plz add this one. https://novelsparadise.net/

### ISSUE THREAD

**Issue by Alzamly0** [dteviot/WebToEpub#1155]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site.

https://novelsparadise.net/series/%d8%a7%d9%84%d8%b9%d8%b5%d8%b1-%d8%a7%d9%84%d8%ac%d9%8a%d9%86%d9%8a-%d8%a7%d9%84%d8%b9%d8%b8%d9%8a%d9%85/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

The CSS things. I have no skills at developing.
If you plz can make a short video using this website as an example so I can try applying it on other websites. Much appreciated 

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

I'm not and I do not have developers friends. Sorry.

**Comment by dteviot** [comment]
@Alzamly0 

Note, I don't know Arabic, so I'm not 100% I've got it right.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelsparadise.net/series/%d8%a7%d9%84%d8%b9%d8%b5%d8%b1-%d8%a7%d9%84%d8%ac%d9%8a%d9%86%d9%8a-%d8%a7%d9%84%d8%b9%d8%b8%d9%8a%d9%85/ chapter 1

For my notes: 10 minutes work

**Comment by dteviot** [comment]
@Alzamly0 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
