### ISSUE TITLE
fails to get epub from volarenovels.com

### ISSUE THREAD

**Issue by Samppady** [dteviot/WebToEpub#1156]
Describe the bug

I was trying to get novel out of volarenovels.com, but got an error instead.

To Reproduce
    1. Go to https://www.volarenovels.com/novel/red-packet-server
    2. Click on the extension button
    3. Click on "Pack epub"

Could not find content element for web page 'https://www.volarenovels.com/novel/red-packet-server'. fetchWebPageContent/<@moz-extension://8ec44176-83bd-4753-a7ef-683a2a1ac395/js/Parser.js:501:23

Desktop (please complete the following information):
    OS: Windows 10
    Browser Firefox 121.0
    Version extension 0.0.0.156

Thank you for your nice project! :)

**Comment by dteviot** [comment]
@Samppady 
It works fine for me.  Note that the URL in the error (https://www.volarenovels.com/novel/red-packet-server) is NOT the URL for a chapter, instead, it's the URL of the Table of Contents (ToC) page.
Chapter URLs look like https://www.volarenovels.com/novel/red-packet-server/rps-chapter-1

So, WebToEpub is probably trying to add the ToC page as a chapter to the Epub.  (I suspect you've got "Add Page with Chapters to Chapters List" checked on the Advanced Options.)
Unfortunately, the layout of the ToC page is different to a chapter, and so WebToEpub is unable to handle it.  Hence, the failure.

Fix: Remove the ToC page from the chapters to fetch.

For my notes: 16 minutes work.
