### ISSUE TITLE
Creating a discord group for support related things and such.

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#116]
Who all would be for this idea?

**Comment by dteviot** [comment]
I think it would not get much use.
There's only a couple of us, and the only real benefit over GitHub issues is we can communicate in real time, when our schedules make that possible.  Based on fact I'm we're literally all over the world, that doesn't happen much.  Plus we haven't had much need for real time communication.

**Comment by dteviot** [comment]
Closing.  Has been open for months with no more feedback.
