### ISSUE TITLE
Please add site https://libread.com/

### ISSUE THREAD

**Issue by Moridin101** [dteviot/WebToEpub#1161]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://libread.com/libread/global-lord-100-drop-rate-186468

(This site is where https://freewebnovel.com is in the process of moving to, so it should require all the same settings as that. Hope that info helps)

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by ImLJS** [comment]
Checked just now! WebToEpub is working on libread

**Comment by dteviot** [comment]
@Moridin101 
As @ImLJS says, you'll need to use the experimental version for this site.
According to my records, version in Chrome and Firefox stores was updated 2023-11-10.  Support for libread.com was added in 2023-11-27. So, version in store does not have this yet.

For my notes: 9 minutes work.

**Comment by dteviot** [comment]
@Moridin101 @ImLJS 
Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
