### ISSUE TITLE
Need support: Retrieving entire chapter content from a website requires login and there is a delay when loading content

### ISSUE THREAD

**Issue by laofun** [dteviot/WebToEpub#1162]
**Describe**:
1. **Problem description**:
    - I developed a Parser for `metruyencv.com` and integrated it into the `WebToEpub` project.
    - Parser works well with unencrypted chapters.
    - With encrypted chapters: the chapter content after the first page load is only a part, and the rest is loaded via the API, then decoded and displayed via canvas (obfuscated) after a period of time .
  

2. **Technical issues**:
    - I wrote code to decrypting content from canvas to text (tested successfully on chrome console).
    - Need a method to wait and get the chapter content completely, including handling the login state and waiting until the content is converted to canvas and then decoded to text.
    
    URL of chapter: [URL of chapter](https://metruyencv.com/truyen/truong-sinh-theo-chieu-co-su-nuong-bat-dau/chuong-99)

**Comment by dteviot** [comment]
@laofun 
It's a violation of the Chrome stores policy for an extension to bypass anti-copy measures.  Doing so will get it banned.
If you want to do this for yourself, I'd suggest you try opening a tab, and then inject a content script into the tab.
https://developer.chrome.com/docs/extensions/develop/concepts/content-scripts

**Comment by gamebeaker** [comment]
closed as not planed.
