### ISSUE TITLE
Please move the footnotes to the bottom of the chapter instead of generating inside the paragraphs text.

### ISSUE THREAD

**Issue by dmbada** [dteviot/WebToEpub#1166]
Hello,

There's an issue with the site "https://wanderertl130.id", where the footnotes are generated within the paragraphs. Is it possible to move those footnotes to the bottom of the chapter instead? They're the clickable footnotes where the reference notes appear under the respective paragraph when the number is clicked on.

Chapter example: https://wanderertl130.id/the-protagonist-pursues-me-relentlessly-chapter-16/

This issue is similar to #1002

**Comment by dteviot** [comment]
@dmbada

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://wanderertl130.id/bl-projects/the-protagonist-pursues-me-relentlessly-bl/, chapter 16

Note, clicking on hyperlink will NOT take you to the footnote text.

For my notes: 15 minutes work

**Comment by dmbada** [comment]
It's working. Thanks

**Comment by dteviot** [comment]
@dmbada 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
