### ISSUE TITLE
Please add site https://novelbuddy.com/

### ISSUE THREAD

**Issue by beanstalkgleams** [dteviot/WebToEpub#1169]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://novelbuddy.com/fey-evolution-merchant

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Yes. I couldn't get it to load all the chapters, however.

### What settings did you use?  What didn't work?
* URL of first chapter - https://novelbuddy.com/novel/fey-evolution-merchant/chapter-1-hundred-questions-beast-and-sound-bird
* CSS selector for element holding content to put into EPUB - #chapter__content > div.content-inner
* CSS selector for element holding Title of Chapter - #chapter__content > h1
* CSS selector for element(s) to remove - #pf-3053-1 > script

I tried all of these. The test worked fine, but when it came to packing the epub, not all the chapters appeared.

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
No.

### If you tried writing a parser, and it doesn't work.  Attach the parser here.

Thank you so much for your hard work!

**Comment by beanstalkgleams** [comment]
Yup, it works! Thanks so much!

**Comment by beanstalkgleams** [comment]
Yup, it works! Thanks so much!

**Comment by dteviot** [comment]
@beanstalkgleams 
Reopen, so I know to notify you when Chrome and Firefox store updated.

**Comment by Flwk** [comment]
Thank you very much dteviot for your works !

**Comment by dteviot** [comment]
@beanstalkgleams @Flwk 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
