### ISSUE TITLE
https://www.38xs.com/ the last 12 chapter, not on DL list

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#1170]
https://www.38xs.com/269412/?btwaf=90080010

dl missing the last 12 chapter

**Comment by dteviot** [comment]
@Finks82 
I'm getting at HTTP 403 error when I try to access the site.  Please let me know when site is working again.

**Comment by dteviot** [comment]
@Finks82 
Sorry, still not working for me

**Comment by dteviot** [comment]
@Finks82 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.38xs.com/269412/?btwaf=90080010

Note that table of contents at above URL has (at least) the following errors
  * does not have a chapter 117
  * has 2 chapters labeled 132 (with different titles)
  * has 3 chapters with label 152 (but different title)

For my notes: 46 minutes work

**Comment by dteviot** [comment]
@Finks82 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
