### ISSUE TITLE
Please add site -- https://titannovel.net/

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1174]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://titannovel.net/category/all-novels/gain-a-cute-wife-by-kidnap/

### Did you try using the Default Parser for the site?  If not, why not? 

yes, I did, but the chapters in the table of contents did not load...

thank you again for all your help thus far! :D

**Comment by dteviot** [comment]
@yuzucitrusx 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://titannovel.net/category/all-novels/gain-a-cute-wife-by-kidnap/ chapters 1 &amp; 2

For my notes: 28 minutes work

**Comment by yuzucitrusx** [comment]
thank youuuuu, it worked perfectly! :)

**Comment by dteviot** [comment]
Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
