### ISSUE TITLE
Please add site -- https://midnightrambles.in/

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1175]
hi hiiii, i apologise for another consecutive request, but would it also be possible to add support for this site please?

here's a link to a novel's table of contents on the site:

https://midnightrambles.in/2023/09/28/part-time-taoist-priest-pttp-bl/?amp=1

thank you again!! :)

**Comment by dteviot** [comment]
@yuzucitrusx 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://midnightrambles.in/2023/09/28/part-time-taoist-priest-pttp-bl/?amp=1 chapter 1.2

Notes.
1. Link to chapter 1.1 seems to be broken.
2. HTML layout is messy, making it difficult to just extract the wanted content.  So, epub is picking up cruft.

For my notes: 35 minutes work

**Comment by yuzucitrusx** [comment]
thank you again for this one too!!! it also worked very well!!! <3

**Comment by dteviot** [comment]
Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
