### ISSUE TITLE
RoyalRoad inserts text about story theft in the epub

### ISSUE THREAD

**Issue by AnotherUser321** [dteviot/WebToEpub#1177]
When converting a story on RR you will end up with random warnings in the epub in each chapter like "If you come across this story on Amazon, be aware that it has been stolen from Royal Road. Please report it."

It has dozens of permutations that I've seen, so you can't edit it out afterwards.

When looking at the source code you can see how RR adds the text so it would be good if the RR parser was updated to look for it and not add it to the epub.

Thank you for your time and effort on this.

**Comment by dteviot** [comment]
@AnotherUser321 

There's a pull request with a fix.  https://github.com/dteviot/WebToEpub/pull/1172

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by AnotherUser321** [comment]
I have tested "WebToEpub0.0.0.157.Firefox" on Firefox 121.0.1 (64-bit) and it seems to work as intended. Thanks for the quick fix.

**Comment by TRUELIKEtheRIVER** [comment]
`webPageDom.querySelector(...) is null removeWatermarks@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/parsers/RoyalRoadParser.js:55:36
preprocessRawDom@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/parsers/RoyalRoadParser.js:41:14
fetchWebPageContent/<@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/Parser.js:496:24
promise callback*fetchWebPageContent@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/Parser.js:493:59
async*fetchWebPages/<@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/Parser.js:470:69
fetchWebPages@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/Parser.js:470:41
async*fetchContent@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/Parser.js:442:21
fetchContentAndPackEpub@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/main.js:153:16
EventHandlerNonNull*addEventHandlers@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/main.js:463:9
window.onload@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/main.js:644:13
EventHandlerNonNull*main<@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/main.js:639:5
@moz-extension://313af1b8-0dba-4bcc-9f30-8a2ae254abc1/js/main.js:658:3`


looking at the 'removeWatermarks thing in the error log, looks like RR may have done some fuckery that breaks it.

**Comment by dteviot** [comment]
@TRUELIKEtheRIVER @AnotherUser321 

Well, this is embarrassing.  Turns out the logging code (used to test it worked) had a bug.  As logging code no longer needed, I've removed it.  Should not have committed it in the first place.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.royalroad.com/fiction/65801/slumrat-rising, chapter 1

For my notes: 10 minutes work

**Comment by dteviot** [comment]
@AnotherUser321 @TRUELIKEtheRIVER 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.

**Comment by Nitrousoxide** [comment]
I know this is a completed issue. But would about adding a general "remove hidden elements" option to the settings that a user can turn on too?  If you have a few overrides for the techniques that site owners use for invisible watermarks it would make for a useful toggle for users generally.

**Comment by dteviot** [comment]
@Nitrousoxide 

This issue is closed.  Please open a new one.
