### ISSUE TITLE
Add option to download multiple chapter in separate files

### ISSUE THREAD

**Issue by nolepguy** [dteviot/WebToEpub#1178]
I always want a series of a novel consisting of separate ebook file per chapter, especially if that's a series from KR or JP web. For those who want to translate, is better for them to have every chapter in the separate file I guess...

The plugin will download each chapter and make it into separate files, and we can download it in zip format.
.

**Comment by nolepguy** [comment]
Sorry,

**Comment by nolepguy** [comment]
epub is also epub file, i already read at prev feature req

**Comment by dteviot** [comment]
@nolepguy 

Have you looked into Calibre's "EpubSplit" Plugin?
See second item on https://www.epubor.com/how-to-split-an-epub-file.html
