### ISSUE TITLE
Chapter heading doesn't appear in the xhtml file for any novels from this source, but the novel's title appears for every chapter instead...

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1180]
hi hiiii! i'm really sorry for the bother again (thrice in a row ahah), but there's also a tidbit problem with this source -- https://moonlightnovel.com/

> Random TOC Link: https://moonlightnovel.com/novels/after-marrying-the-lord-of-the-underworld/

when generating an epub from this site, the chapter heading for all xhtml files is not the actual chapter title but is the novel name instead. it's like a previous problem that happened with wattpad which is now fixed.

is it possible to configure the parser to generate the chapter title within the heading tags instead of the novel name please?

the chapter title for _each_ respective chapter is positioned directly under the novel title (the sub-heading text that's not bolded):

![image](https://github.com/dteviot/WebToEpub/assets/144674653/c4fd158b-0c95-4c17-9770-585909f0ecf2)

how the heading currently outputs in the epub:

![image](https://github.com/dteviot/WebToEpub/assets/144674653/cecadef1-7aab-439b-8cb0-75a31d80a944)

how the chapter title should be in the heading tags:

![image](https://github.com/dteviot/WebToEpub/assets/144674653/eb60f0b5-a169-4b16-ba5f-eb97329eedff)

from the site layout, it doesn't seem like it'd possible to add the chapter numbers too, but if the chapter titles could be generated, that'd be really helpful! though actually, there are some novels where the chapters don't have a sub-heading (like the actual chapter title under the novel name as well), so i'm not sure how else to circumvent these issues in order for all chapters to have a proper heading haha.

i tried using the default parser and it did work with the selector "**.cat-series**", but when i used the default parser, large blocks kept appearing between the text instead and i'm not sure how to remove them (since they didn't appear in the outputted epub that's generated using the in-built parser for this source). so it'd be super great if this could be edited in the parser! :D apologies in advance for the inconvenience again. thank youuuuuu!!

**Comment by dteviot** [comment]
@yuzucitrusx

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://moonlightnovel.com/novels/after-marrying-the-lord-of-the-underworld/ chapters 1 &amp; 2

Note, would have been helpful for testing if you had provided chapter with no "sub title", so I could check output is kind of sane.

For my notes: 12 minutes work

**Comment by yuzucitrusx** [comment]
> Note, would have been helpful for testing if you had provided chapter with no "sub title", so I could check output is kind of sane.

hi hiiii, thank you so much for your fast response and effort! and i'm really sorry for not providing adequate details regarding this point, but i tried the new update on one of the novels which had no "sub title" and it did appear as the chapter heading! 

though, if i may ask, if the chapter heading was perhaps generated directly from the TOC (the second column) into the xhtml file, is it perhaps also possible to pull in the chapter number from the first column into the **same** heading tags as well, as in to be written directly before the title?

![image](https://github.com/dteviot/WebToEpub/assets/144674653/a91c2b29-f02a-43b1-9eb0-f89c141e17a8)

for reference, the used TOC in the above image is the novel which has no "sub title": **https://moonlightnovel.com/novels/the-leaders-warpet-hamster/**

ah but if this requires too much effort, then that's okay! <3 thank you so much for all the continued help! :D

**Comment by dteviot** [comment]
@yuzucitrusx 
Chapter heading isn't generated from the Table of Contents.  It's generated from the text on the page.
And while it COULD use the ToC, it gets complicated, because there's not always a one to one relationship between web page and chapters.  More specifically, the original site this was created for, each web page became multiple chapters.
So, sorry, no plans to do that at this time.

**Comment by yuzucitrusx** [comment]
ohhhh okay! thank you for the fast response~ :)

**Comment by yuzucitrusx** [comment]
ahhh actually, i'm sorry for the bother again, but regarding the outputted novel that had no "sub titles", i had assumed that the chapter headings were generated from the second column of the TOC because the Novel Title started appearing as the Chapter Heading when the proper titles in the second column stopped and became an acronym of the novel's title + the chapter number (and were moved over to occupy the first column) instead.

in the below image, the chapters highlighted in blue means that the chapter heading does appear as proper titles in the xhtml file, whereas the chapters rounded in red have the Novel Title written in their chapters.

![image](https://github.com/dteviot/WebToEpub/assets/144674653/cf896724-1fcc-48e0-bbb1-c744a2762667)

really sorry for the inconvenience, only hoping to offer clarity on what i meant haha, i apologise again for not clearly explaining...

**Comment by dteviot** [comment]
No problem.
The change I made was: if a ".cat-series" element was present on the web page, use that as the title.
If there is no ".cat-series", use the "h1.entry-title" (which it was using previously) as the title.

**Comment by yuzucitrusx** [comment]
ohhhhh i see!! thank you very much for explaining and clearing that up! :D

**Comment by dteviot** [comment]
@yuzucitrusx 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
