### ISSUE TITLE
Please add wuxiabee.com

### ISSUE THREAD

**Issue by 18jaymes** [dteviot/WebToEpub#1181]
Please add wuxiabee.com
It's not work on my android Kiwi browser

**Comment by dteviot** [comment]
@18jaymes 

It's in the development branch, https://github.com/dteviot/WebToEpub/commit/bf164e0f3bdbba415fffc831bd4e3fcd08886a05 version in Chrome and Firefox stores hasn't been updated yet.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@18jaymes 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
