### ISSUE TITLE
Novel order reversed on Genesistls.com

### ISSUE THREAD

**Issue by Saladitas** [dteviot/WebToEpub#1188]
**Describe the bug**
The novel is downloaded in the wrong order.

**To Reproduce**
1. Go to [Genesis Translations- Kidnapped Dragons](https://genesistls.com/series/kidnapped-dragons/)
2. Click on your extension 
3. Scroll down to where the first and last chapter are shown.
4. First chapter is 434; Last chapter is 1

**Produced behavior**
I download the Epub and opened it Sigle to clean up the code a bit and realized that the whole novel was backwards.

**Workaround** 
Tried to fix it Sigle and it was more work than it was worth, so I went to the page again and redownload the novel but this time I selected 'Edit chapters URLs'. I selected it all and copied it to notepad++, from there I just used the Edit > Line Operations > Reverse Line Order to fix the order. Through it into WebToEpub and this time It worked fine. 

 
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Vivaldi]
 - Version [6.5.3206.57 (Stable channel) (64-bit)]

**Comment by dteviot** [comment]
@Saladitas 
Just click the Reverse Chapter URLs Order button.
![image](https://github.com/dteviot/WebToEpub/assets/5157081/8bf6654f-6f43-49a9-be09-a2763a82201c)

Not going to change this.  Same parser is used for a multiple other sites and they have it in the other order.

**Comment by Saladitas** [comment]
ahh I see... ~~or actually I don't see...~~
