### ISSUE TITLE
Large blocks keep appearing between the text for this source (after using the latest version)

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1189]
hi hiiiii, i'm really sorry for another request, i apologise in advance for the inconvenience. but i have an issue with a different source. after using the latest version of webtoepub, large blocks now appear between the paragraphs for this other source -- **https://lazygirltranslations.com/the-obsessive-shou-moves-on-rebirth/**

`<span id="ezoic-pub-ad-placeholder-613" data-inserter-version="2"></span><p><span data-ez-ph-id="186" style="margin-right:auto!important;margin-left:auto!important;text-align:center!important;max-width:728px;background:rgba(128,128,128,5%)!important;margin-top:15px!important;margin-bottom:15px!important;line-height:0;border:0 solid #ddd!important;float:none!important;min-width:300px;min-height:400px;width:728px;display:block!important;padding:0;background-color:rgba(128,128,128,5%)!important"></span>`

in the above example, the previous version of webtoepub usually only grabbed the first <span> tag, but for some reason, the second element is now also generated into the epub, thereby forming large extraneous blocks to appear within the chapter text. certain attributes in these two span tags are variable and changing. it'd be amazing if both these span elements could be removed (except that the first span element is nested in a paragraph tag).

![image](https://github.com/dteviot/WebToEpub/assets/144674653/5aa21a42-1599-4f50-a65e-d70ec7b5482b)

is it possible to revert this somehow to remove the blocks? thank you very much and again, really sorry for the bother! <3

**Comment by dteviot** [comment]
@yuzucitrusx 

I don't see any changes that were made to WebToEpub that could be causing the new behavior.  
So, I think it's a site change.
As regards changing WebToEpub for this site, I'm not willing as the site is using the WordpressBaseParser, which is used by WebToEpub for many Wordpress based sites.  So, changing it runs risk of breaking other sites.

However, it is possible to use EpubEditor to remove the blocks with the following scirpt.

```javascript
let toChange = [...dom.querySelectorAll("span[data-ez-ph-id], span[id^='ezoic-pub-ad-placeholder']")];
for(let s of toChange) {
    s.removeAttribute("style");
}
return 0 < toChange.length;
``` 

Tested with:
* https://lazygirltranslations.com/the-obsessive-shou-moves-on-rebirth/, chapter 1

For my notes: 31 minutes work

**Comment by yuzucitrusx** [comment]
ohhhhh i see! that's much easier, apologies again for the inconvenience! and thank you very much for the quick fix!!! :D
