### ISSUE TITLE
Direct image link images are not downloaded

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#119]
I found that if the page contains a link to an image it's not processed.
This is what I mean:

https://crimsonmagic.me/2016/08/31/continued-explosions-p/ [Any link in the page]

As you can see, they have hi-res images, but to speed up the loading they make it a link, so ppl wil lclick on it only to load it (I suppose).

Now, while I think I can contact them to ask if they can do it better, can this issue be taken care on the webtoepub side? Maybe an option of some kind? 

Thanks anyway.

**Comment by dteviot** [comment]
@typhoon71
I am aware of this.  I've seen at least 3 sites that do this.  

> can this issue be taken care on the webtoepub side?

It can, for the simple cases.
I hope to have time to get it done this weekend.
(Note to self, one problematic edge case is when the link is to an Imgur gallery.)

**Comment by typhoon71** [comment]
Thanks, I'll wait patiently, after all I'm rather busy too as of late.
I didn't expect this kind of thing be common, but I guess it is.

**Comment by dteviot** [comment]
@typhoon71 
I have added code to Experimental Tab branch that will convert &lt;a&gt; elements that are obviously images (e.g. The URL ends with .png) to &lt;img&gt; elements. Note, the new code doesn't handle links to imgur galleries.  However, the CrimsonMagic parser already has code for that, so that works for the above link.
Please give it a try and let me know how it works.

**Comment by typhoon71** [comment]
Everything seems to work here, at least on CrimsonMagic which is where I noticed the issue.

**Comment by dteviot** [comment]
@typhoon71
New commit to Experimental Tab branch.
* Image Collector now fetches content for links to Imgur gallery.
* Also, fix for Imgur changing format of their galleries

I did a quick test with Gifting chpt 9 from here. http://skythewoodtl.com/fanfic-gifting/
I'm going to call this done and close.  If you have any issues, please reopen.
