### ISSUE TITLE
Readlightnovel not working/changed address

### ISSUE THREAD

**Issue by wilkher** [dteviot/WebToEpub#1190]
**Describe the bug**
Readlightnovel.com is has changed their domain to readlightnovel.today and the parser has stopped working

**To Reproduce**
1. Go to 'www.readlightnovel.com'
2. Click on 'any novel'
3. Click on the extension

**Expected behavior**
That the parser will load the chapters and create an epub. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome and firefox 
 - Version 120.0 and 122.0

**Additional context**

**Comment by dteviot** [comment]
@wilkher 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 10 minutes work

**Comment by dteviot** [comment]
@wilkher 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
