### ISSUE TITLE
The chapter sub-heading also doesn't appear in the xhtml files for this source...

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1194]
hi hiiiii, sorry again for another bothering request. but this other source [**https://knoxt.space/in-love-quick-transmigrate/**] also has a similar issue to #1180.

the structural layout of this source is extremely similar as the one in the referenced issue, where the main difference is that the grabbed heading in the `<h1>` tags isn't exactly the Novel Name (as designed on this site), but more so a placeholder title that's an acronym of the Novel Name.  would it be possible to generate both this heading (acronym) since it has the chapter number, but also grab the "sub title" that's below the acronym into the same heading tags as well, like directly after it.

`<h1>ILQT20 The General Take The Initiative To Be Rob 1</h1>`

![image](https://github.com/dteviot/WebToEpub/assets/144674653/8ec349b4-8ee9-4c6f-80c6-93ca1a57a66b)

i remember seeing a past issue with travistranslations where you were able to grab and generate the "sub title" into the `<h1>` heading tags along with the chapter number (main heading) before, so was wanting to ask if it was possible for this source as well :D

thank you again for all the help!!! super appreciative!! <3

**Comment by dteviot** [comment]
@yuzucitrusx 
Are most of the stories on the site like this, or only a few?

**Comment by yuzucitrusx** [comment]
> @yuzucitrusx Are most of the stories on the site like this, or only a few?

all the novels on this site are like this haha, but there are some novels that don't have proper titles, thereby entirely omitting the "sub title" (like this novel --> **https://knoxt.space/the-way-of-the-empress-interstellar/**)

so for those type of novels without any "sub title", WebToEpub poses no issue in generating only the main heading thus far, considering the lack of the "sub title" in question. but for all novels which do include a "sub title", the corresponding html element for the "sub title" isn't able to be grabbed and generated into the epub.

ah and just for reiteration, this is another novel which has chapters that include a "sub title" --> **https://knoxt.space/hes-super-sticky/**

**Comment by dteviot** [comment]
@yuzucitrusx 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://knoxt.space/in-love-quick-transmigrate/, chapter 1
* https://knoxt.space/the-way-of-the-empress-interstellar/, chapter 1
* https://knoxt.space/hes-super-sticky/, chapter 1

For my notes: 35 minutes work

**Comment by dteviot** [comment]
@yuzucitrusx 

> hi hiiiii, sorry

You need to get the 'i' key on your keyboard fixed.

**Comment by yuzucitrusx** [comment]
hello~ it worked perfectly, thank you again. and the 'i' key isn't jammed or anything haha, sorry if that was a bother for you, i'm just used to greeting like that, but i'll tone it down next time ahah :)

**Comment by dteviot** [comment]
@yuzucitrusx 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
