### ISSUE TITLE
Multiple chapters from the TOC on this source can't be grabbed anymore if TOC has sub-headings

### ISSUE THREAD

**Issue by bonnetchuu** [dteviot/WebToEpub#1195]
Hello! Hoping this is not a bother to you, but I recently started using WebToEpub again and found that there's an error with an old source that has a pre-existing parser which wasn't present previously in an older version of the extension --> **https://exiledrebelsscanlations.com/**

There are _some_ novels on this source, wherein the Table of Contents page includes textual sub-headings that are not hyperlinks coming between a portion of the chapters. So, when WebToEpub tries to generate the TOC of chapter links, when it reaches a sub-heading, the extension seems to hit a bump and does not generate any chapter links further than the occurrence of the **first** sub-heading, thereby only grabbing a portion of the chapters out of the majority of links.

A couple novels which has this error (due to the emplacement of sub-headings) are:

https://exiledrebelsscanlations.com/novels/mecha-slave-contract/

https://exiledrebelsscanlations.com/novels/the-governors-illness/

Please refer to the below image for reference, wherein the **double underline in red** (+ the cross) indicates when WebToEpub stops and fails to proceed in grabbing the remainder of chapters due to the impediment of the **first occurring sub-heading** [that's encircled in blue].

![image](https://github.com/dteviot/WebToEpub/assets/141732398/220013df-d87a-4ac3-b7e9-4e3d1445eccc)

Just for a note, all other novels which do not include sub-headings as part of the TOC do not pertain to this issue. But, for the novels which do have sub-headings, it would be greatly appreciated if this error could somehow be rectified. Thank you!!! :)

**Comment by dteviot** [comment]
@bonnetchuu 

Fix supplied by ImLJS

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://exiledrebelsscanlations.com/novels/mecha-slave-contract/

For my notes: 15 minutes work

**Comment by bonnetchuu** [comment]
Thank you, it fixed the issue!

**Comment by dteviot** [comment]
@bonnetchuu 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
