### ISSUE TITLE
Please add site https://faqwiki.us/

### ISSUE THREAD

**Issue by hesoyamma785** [dteviot/WebToEpub#1197]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://faqwiki.us/the-demon-prince-goes-to-the-academy/
### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by ImLJS** [comment]
![image](https://github.com/dteviot/WebToEpub/assets/109210868/8b1077be-94bf-48ff-b5ca-93d55d07fb17)

Parser is Working!! 

If there are still issues try the experimental version of webtoepub or if you are using the extension on mobile, turn on desktop mode and try again.

**Comment by dteviot** [comment]
@hesoyamma785 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.

**Comment by hesoyamma785** [comment]
Thanks♥
