### ISSUE TITLE
[Wuxiaworld Pareser] Little bug, missing chapters

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#120]
There's a little problem when making the epub frome here: http://www.wuxiaworld.com/wmw-index/.

This is the ToC of Warlock of Magus World, and at the time of writing this post the ToC is up to date with the trasnslated chapters, last one being ch708 (there's a some placeholders too).

If you try to grab it, webtoepub will create the chapter list, but it will be incomplete, having ch649 as the last one; chapters from 650 to 708, and the placeholders, just aren't there.

Can you please fix this? Thanks.

**Comment by dteviot** [comment]
I just tried opening it with Firefox and Chrome, the list of chapters went up to 721 for both
There were 718 chapters in the list
URLs for 422, 438 & 439 do not appear.

**Comment by typhoon71** [comment]
Yes, I confirm now I see till chapter 748 (721 with placeholders), while chapters 439 and 440 do not appear. S o you have issue with chapter 438 instead of 440?

It's strange because all of the chapters link are available in the ToC page...

**Comment by dteviot** [comment]
If you look at the HTML, the URL does not match the chapter title.
I'm not sure what's going on, but there's not much I can do about it.

**Comment by typhoon71** [comment]
mmm, indeed is seems an error in the html: I will let the webmaster(s) know.
I'm closing this, not a bug actually.
