### ISSUE TITLE
Please generate the sub title into the same heading tags for this source as well -- https://whitemoonlightnovels.com/

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/WebToEpub#1200]
hello! sorry for being back again so soon, but i noticed this other site (with the same layout) has the same problem with not generating the "sub title". could it be possible to resolve this issue with the same outcome as issue #1194 please?

here's an example TOC of a novel which does include the "sub title": **https://whitemoonlightnovels.com/series/gold-medal-coach/**

thank you very much! :)

**Comment by dteviot** [comment]
@yuzucitrusx 

To avoid doing these one by one, please check the following list:

``javascript
parserFactory.register("bookalb.com", () => new NoblemtlParser());
parserFactory.register("ckandawrites.online", () => new NoblemtlParser());
parserFactory.register("daotranslate.com", () => new NoblemtlParser());
parserFactory.register("faloomtl.com", () => new NoblemtlParser());
parserFactory.register("genesistls.com", () => new NoblemtlParser());
parserFactory.register("jobnib.com", () => new PandamtlParser());
parserFactory.register("moonlightnovel.com", () => new MoonlightNovelParser());
parserFactory.register("noblemtl.com", () => new NoblemtlParser());
parserFactory.register("novelsparadise.net", () => new PandamtlParser());
parserFactory.register("tamagotl.com", () => new NoblemtlParser());
parserFactory.register("knoxt.space", () => new KnoxtspaceParser());
parserFactory.register("novelsknight.com", () => new NoblemtlParser());

parserFactory.register("pandamtl.com", () => new PandamtlParser());
parserFactory.register("universalnovel.com", () => new NoblemtlParser());
parserFactory.register("whitemoonlightnovels.com", () => new WhitemoonlightnovelsParser());
```

**Comment by yuzucitrusx** [comment]
hello! thank you for the quick reply, but i'm not quite clear on what you mean ahah, could i perhaps bother you to please clarify?

ah, also the source this issue is addressing is the last one in the above list, um is that right...? although i'm aware webtoepub is open source, i'm really clueless on how to open a js file, let alone edit it haha. though, I'm unsure if that's what you're asking? i also did look through the parsers, but couldn't find the one matching with this source...

i really apologise for causing much inconvenience...

**Comment by dteviot** [comment]
@yuzucitrusx 
Apologies.  I meant, please try these sites and let me know if they also have the same problem with titles.

e.g. 
```javascript
parserFactory.register("bookalb.com", () => new NoblemtlParser());
``` 

Refers to site https://bookalb.com

So, please go to that site, try a couple of chapters from a couple of stores and see if there's a problem with the titles.  Then repeat for the other sites.

**Comment by yuzucitrusx** [comment]
ohhhhh, thank you so much for taking the time to explain! i get it now! :D

from the list above, although it seems like this issue pertains to all of those sites (due to bearing the same structural layout), the sites that i actually use would only be the ones below:

`parserFactory.register("ckandawrites.online", () => new NoblemtlParser());`

**Example TOC:** https://ckandawrites.online/male-consort-upgrade-system/

`parserFactory.register("whitemoonlightnovels.com", () => new WhitemoonlightnovelsParser());`

**Example TOC:** https://whitemoonlightnovels.com/series/gold-medal-coach/

---

**These sources below have already been addressed in previous issues and are therefore fixed, but are simply indicated for reference.**

`parserFactory.register("moonlightnovel.com", () => new MoonlightNovelParser());`

**Example TOC:** https://moonlightnovel.com/novels/after-marrying-the-lord-of-the-underworld/

Note, this source was previously fixed (in issue #1180) by generating the "sub title" as the main heading, but if this same fix (addressed in this issue) could be made to also grab the chapter number as well into the same heading tags, that would be really amazing! but it's also perfectly fine to leave this as is since the "sub title" is already grabbed! :)

`parserFactory.register("knoxt.space", () => new KnoxtspaceParser());`

**Example TOC:** https://knoxt.space/alpha-predator/

**Comment by dteviot** [comment]
@yuzucitrusx 

I had hoped you would check the other titles and let me know if they also needed fixing.
To save me the time needed to do that myself.
But fine, be that way.

Fortunately, it turns out that using the value from the Table of Contents as the chapter title is actually trivial.  So I've just done that for all the sites in the list.  (Sticks head in sand and refuses to consider potential maintenance headaches in the future.) So congratulations, I think that also results in doing what you've been nagging about for moonlightnovel.com. 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://ckandawrites.online/male-consort-upgrade-system/, chapter 1
* https://whitemoonlightnovels.com/series/gold-medal-coach/, chapter 1
* https://moonlightnovel.com/novels/after-marrying-the-lord-of-the-underworld/, chapter

For my notes: 36 minutes work.  Would have been much shorter, but I wasted too much time typing up a rant that was best deleted.

**Comment by yuzucitrusx** [comment]
> I had hoped you would check the other titles and let me know if they also needed fixing.

um i did check the other sites, as indicated in my opening statement:

> from the list above, although it seems like this issue pertains to all of those sites (due to bearing the same structural layout)

the issue did occur with all those sites as well but since the list of sites was long, i didn't want to trouble you so only picked out the sites that i actually used. i didn't think this would actually irritate you instead so i apologise if this wasted your time instead. thank you anyway.

**Comment by dteviot** [comment]
@yuzucitrusx 

I apologize as well, I mis-read your response as "I'm only interested in these sites, so I only checked these sites".  And ignoring the fact that someone is using them, so they all need to be checked and fixed.

Anyway, are your sites working satisfactorily now?

**Comment by yuzucitrusx** [comment]
thank you for understanding haha, i thought to try to lessen your workload by only mentioning the sites i used, despite ascertaining that this issue did indeed align with all of the listed sources, but didn't think it'd have the opposite effect. so, for lacking clarity in my response, i do apologise. though i do get that my multiple requests must be annoying seeing how i'm a bit too particular about minor details that for most would be considered inconsequential to the overall use. so thank you for fixing these issues regardless :)

but, if i may, regarding the current outputted main headings, this is the **perfect result** for the "moonlightnovel.com" source because the internal heading completely omitted the chapter number and this fix resolved that issue. but, now this specific amendment changed the result for these sources (knoxt, ckandrawrites, whitemoonlightnovel) as well, thereby removing the retention of the original chapter headings that were derivative of the actual main heading and "sub title" on the source itself.

so, is it perhaps possible to only retain this new fix of using the labels in the webtoepub TOC for the source "moonlightnovel" **alone**, and then backtrack to retain the fix of simply inserting the "sub title" into the heading <h1> tags along with the main heading (completed in issue #), thereby retaining the original labels grabbed from the source itself for **knoxt, ckandawrites and whitemoonlightnovel**?

i understand this may be an inconvenience since this issue is essentially resolved, but unless a site is specifically finicky in somehow excluding a required element, I prefer to keep the majority of the file as close to the original as possible haha. hoping this is not too much trouble again, and thank you very much for all your time and effort :D

**Comment by dteviot** [comment]
@yuzucitrusx 

Just so there's no confusion, please grab at least one chapter from each of the sites knoxt, ckandawrites and whitemoonlightnovel.
For each chapter, provide:
* URL of chapter
* Title that  WebToEpub puts on the chapter
* Title that you would like to see.

Note, if any of the sites has stories with different title layouts, please include one example of each layout.
Because I need to make things work with all layouts.  It's not good if WebToEpub only works with some of the stories on a site (that you care about) and fails for others.

**Comment by yuzucitrusx** [comment]
okay! please allow me to apologise in advance should i have omitted any particular details you had wanted mentioned, so please do tell if there's something else i should've included.

<h2>KnoxT:</h2>

- URL of Chapter: https://knoxt.space/hes-super-sticky-chapter-1/
- Title that WebToEpub puts on the chapter: Directly takes and generates edited label from TOC into xhtml file --> 

![image](https://github.com/dteviot/WebToEpub/assets/144674653/1a427401-a5d7-4876-8a4f-709e01f4cdec)

![image](https://github.com/dteviot/WebToEpub/assets/144674653/50bed7ab-e4df-4e95-a477-cd54cfe4815a)

- Title that you would like to see: As seen in a previous version of WebToEpub, insert the "sub title" into the **same** `<h1>` heading tags containing the main heading -->

![image](https://github.com/dteviot/WebToEpub/assets/144674653/84b6c8ad-af7a-4f87-a763-fcd6e5a62b17)

[KnoxT Chapter Example.zip](https://github.com/dteviot/WebToEpub/files/14274537/KnoxT.Chapter.Example.zip)

note, the novels on this site are rather consistent so the layouts are pretty similar. the only variance is that **some** novels do not include a "sub title", but this issue should be inconsequential to the overall output.

---

<h2>Ckandawrites:</h2>

- URL of Chapter: https://ckandawrites.online/mcus-chapter-1/
- Title that WebToEpub puts on the chapter: Same as the above --> Directly takes and generates edited label from TOC into xhtml file (please refer to the two images above for this point).
- Title that you would like to see: As seen in a previous version of WebToEpub, insert the "sub title" into the **same** `<h1>` heading tags containing the main heading --> 

![image](https://github.com/dteviot/WebToEpub/assets/144674653/acbf200f-c4f5-4bb7-ac04-d74751a83f3f)

[Ckandawrites Chapter Example.zip](https://github.com/dteviot/WebToEpub/files/14274594/Ckandawrites.Chapter.Example.zip)

note, this site is also organised similar to the first one above, so there are essentially no different layouts to account for, other than some novels omitting the inclusion of a "sub title".

---

<h2>Whitemoonlightnovel:</h2>

- URL of Chapter: https://whitemoonlightnovels.com/gold-medal-coach-chapter-1/
- Title that WebToEpub puts on the chapter: Same as the above two sources --> Directly takes and generates edited label from TOC into xhtml file (please refer to the two images from knoxt for this point).
- Title that you would like to see: This is the primary commit i had initially asked for through this open issue for this specific source, that is to also insert the "sub title" into the **same** `<h1>` heading tags containing the main heading --> 

![image](https://github.com/dteviot/WebToEpub/assets/144674653/0b11854d-8826-46c1-bf39-9cd141e17ed7)

[Whitemoonlightnovel Chapter Example.zip](https://github.com/dteviot/WebToEpub/files/14274642/Whitemoonlightnovel.Chapter.Example.zip)

note, this site is also organised similar to the two sources above, so there are essentially no different layouts to account for, other than some novels omitting the inclusion of a "sub title".

**Comment by dteviot** [comment]
@yuzucitrusx 

KnoxT, Why are you changing the text for the Table of Contents?  If you leave it alone, the generated ToC entries are like "Ch.1 Real and Fake Young Master 1" And same text is used for the Title on the Chapter.  Surely this is exactly what you would want.

Ckandawrites:.  As with KnoxT, what's wrong with the Chapter titles now being generated?  Title is "Vol.1 Ch1. Prelude"   (But only the first chapter has the "Vol. 1"  the rest just start with the Chapter number.

And same again for Whitemoonlightnovel.

The only real difference I can see between what WebToEpub is now doing, and what you're asking for is to put the Name (or abbreviation) of the Novel itself in the title.  And I don't see that adding any value.

**Comment by yuzucitrusx** [comment]
ah no, actually, that isn't quite what i meant. the way these sources structured the TOC is rather unorganised, but prior to this latest update that ultimately fixed the issue with "moonlightnovel.com", it also altered the behaviour of how the titles were generated for all sites bearing this same layout (knoxt, ckandawrites and whitemoonlightnovel).

but the way that these latter three sources generated the chapter titles before were simply inserting the "sub title" into the heading tags along with the chapter number, which i had asked for in a previous open issue (#1194). i preferred the outcome in issue #1194 for those three specific sources and the result in **this issue** #1200 for only *one* source, which is "moonlightnovel.com".

hence, why i had intially asked to revert some effects in the parser to enable this (like it was done previously) haha. though i'm not sure if it's probable to commit a singular specification regarding the "title" for one source without affecting the rest in inadvertently bearing the same outcome, due to being written within the same parser. but, thank you for answering my request.

**Comment by dteviot** [comment]
@yuzucitrusx 
I don't think you'll want to use the default parser.  It's going to be a bit flaky extracting the URLs of chapters and building the Table of Contents.

You also can't just join the two title elements together.  As they're not always both there,  WebToEpub will break unless you handle those cases.

Anyway, try this.  I think I've got those 3 sites set the way you're asking.  Personally, I think it's NOT an improvement.  But that's a subjective judgement.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://whitemoonlightnovels.com/gold-medal-coach-chapter-1/
* https://ckandawrites.online/mcus-chapter-1/
* https://knoxt.space/hes-super-sticky-chapter-1/

For my notes: 28 minutes work (additional)

**Comment by yuzucitrusx** [comment]
thank you for your time and efforts, but all sites now (except knoxt) now exclude the "sub title" haha. i'm not sure if this was intended? it seems like the commits resulted in further backtracking that even "moonlightnovel.com" no longer shows the chapter number in the heading tags.

the most ideal result was in i think two previous versions ago and then um doing the same of generating the ".cat-series" element inside the same heading tags as well to the "whitemoonlight.com" site just like knoxt. and then to also take the new commit made specifically for "moonlightnovel.com" that's in the second to latest parser where it takes directly from the TOC. i um attached the two parsers, and labelled them according to which sites the result is perfect for as reference.

[Perfect Result For -- KnoxT & Ckandawrites.zip](https://github.com/dteviot/WebToEpub/files/14318561/Perfect.Result.For.--.KnoxT.Ckandawrites.zip)

[Perfect Result For -- Moonlightnovel.zip](https://github.com/dteviot/WebToEpub/files/14318564/Perfect.Result.For.--.Moonlightnovel.zip)

the ideal was to merge the two results for the four sources into the same parser (including a **new specification committed solely for "whitemoonlightnovel.com"**)

since only "whitemoonlightnovel.com" couldn't receive the same output as the zip file knoxt is mentioned in, which was the main reason i opened this issue, hoping to just generate the ".cat-series" element for this site too, like the others had previously before the current update ahah.

but overall, i do really appreciate your efforts for my continuous requests. so again, thank you very much :) i won't press any further for this to be done the way i liked, so deepest apologies for the bother xx

p.s. thank you for informing me about not being able to join two elements in the default parser as well^^, i will try to look for other alternatives haha.

**Comment by yuzucitrusx** [comment]
ahhhh i'm not sure why, but with the version i used yesterday, everything went back to the unedited outputs. though, with the current version i just downloaded, all four sites work now seamlessly! i really really really do apologise for taking up so much of your time, but thank you kindly for doing this the way i liked xx :D
