### ISSUE TITLE
Please add site https://novelingua.com/

### ISSUE THREAD

**Issue by AzaleaBehati** [dteviot/WebToEpub#1202]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

Sorry, I don't have any friends that have a develope skills huhu

I've tried Default Parser but it says it doesn't have content element. I don't know how to do. Help me, pleaseeee!

Error: Could not find content element for web page 'https://novelingua.com/turning-chapter-001/'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:501:23
    at async Promise.all (index 0)
    at async DefaultParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:470:17)

**Comment by dteviot** [comment]
@AzaleaBehati 
Use "div.entry-content" as value for "(required) CSS selector for element holding content to put into EPUB:".  
Note, 
1. Ignore the quotes.

For my notes: 14 minutes work

**Comment by AzaleaBehati** [comment]
Thank you so much! It works!
