### ISSUE TITLE
This source also turns text to gibberish when generating an epub...

### ISSUE THREAD

**Issue by bonnetchuu** [dteviot/WebToEpub#1204]
Hello! So I've noticed with a specific site that the copy protections on this source are very stringent (it's essentially impossible to view the page source even with the use of external applications) --> https://bittercoffeetranslations.com/translations/laws-of-the-other-world/?lcp_page0=7#lcp_instance_0

Specifically for this novel [**Laws of the Other World**], from **Chapter 60 onwards to 96**, literally all the text turns entirely to gibberish. Similarly to Chrysanthemum Garden, it seems like the site uses a specific font to render the text to be readable as the novel content, albeit only on the source itself. Extracting the text will instead result in turning the entire chapter into gibberish content. Even using chrome extensions like "Reading Mode" will result in viewing the same garbled text.

```
<h1>Laws of the Other World Chapter 61</h1><p><span style="font-family: OpenSans-1;">Bifrgvc 61: Xipw Sw &amp; Dp Sv JQ giv mvfgi mfikhf</span></p>
<p><span style="font-family: OpenSans-1;">Aivn givs avcv kvqq gifn yhjv dvgvcq fafs ycpd giv khxfcm dpnqgvc, hg qwmmvnks cfhqvm hgq ivfm fnm kvfrvm, fbbwcfgvks rpwnbhno pn giv qdfkk bcvfgwcv ahgi f qrvvm gifg qwcrchqvm Xipw Sw.</span></p>
```

I'm sorry for troubling you again, but would a solution to unscramble all gibberish text be possible? Like editing the epub through a script via epubeditor? Thank you again! xx

**Comment by dteviot** [comment]
@bonnetchuu 

Irritating.  They're using at least 3 different fonts.

Give this script a try with EpubEditor.

```javascript
function decrypt(clear, selector) {
    let crypt = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    let decryptTable = new Map();
    for(let i = 0; i < crypt.length; ++i) {
        decryptTable.set(crypt[i], clear[i]);
    }
    let decryptChar = c => decryptTable.get(c) ?? c;
    let decryptString = (cypherText) => cypherText.split("").map(c => decryptChar(c)).join("");
    for(let e of dom.querySelectorAll(selector)) {
        e.textContent = decryptString(e.textContent);
    }
}

decrypt("wcrmbatihvlxdngospykqeuzfjWCRMBATIHVLXDNGOSPYKQEUZFJ", "span[style*='OpenSans-1']");
decrypt("dznqohwfytcmpaerubklgvsxjiDZNQOHWFYTCMPAERUBKLGVSXJI", "span[style*='OpenSans-2']");
decrypt("iqydbeanljopmukrhztxsvfcwgIQYDBEANLJOPMUKRHZTXSVFCWG", "span[style*='OpenSans-3']");

return true;
```

Tested with
* https://bittercoffeetranslations.com/translations/laws-of-the-other-world/?lcp_page0=7#lcp_instance_0, chapters 61 to 70

For my notes: 78 minutes work

**Comment by bonnetchuu** [comment]
Thank you!!!!!! Apologies for taking up a huge chunk of your time! But it fixed this gibberish issue amazingly!!!
