### ISSUE TITLE
Please add site https://wetriedtls.site/

### ISSUE THREAD

**Issue by MohamadTaher** [dteviot/WebToEpub#1206]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://wetriedtls.site/series/a-regressors-tale-of-cultivation

### Did you try using the Default Parser for the site?  If not, why not?
yes.

### What settings did you use?  What didn't work?
* URL of first chapter: https://wetriedtls.site/series/a-regressors-tale-of-cultivation/chapter-0
* CSS selector for element holding content to put into EPUB: div.bg-black
* CSS selector for element holding Title of Chapter: h1.font-semibold
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by ImmortalDreamer** [comment]
@MohamadTaher 
Try `div#reader-container` as the selector for content. Leave chapter title selector blank since `div#reader-container` has that info already.

**Comment by aaasssdd2** [comment]
Yesterday they've redesigned website and broke the parser, any chance for an update?

**Comment by dteviot** [comment]
@aaasssdd2 @MohamadTaher 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://wetriedtls.site/series/a-regressors-tale-of-cultivation, chapters 1 &amp; 2
* https://wetriedtls.site/series/sss-class-hunter-who-dies-to-live, chapter 1

For my notes: 92 minutes work

**Comment by dteviot** [comment]
**Additional notes, for when I need to revisit**.
Getting full list of chapters is a pain
To get each block of 25 chapters, need to call REST endpoint https://api.wetriedtls.site/chapter/query
with JSON
```json
{"series_id":15, "page ":2, "perPage":25}
```
I'm abusing this to fetch all chapters in one hit.  Might be a problem if chapter count gets too big..
Total chapters is included in the "meta" parameter of the return.

**Comment by dteviot** [comment]
@ImmortalDreamer @MohamadTaher 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
