### ISSUE TITLE
Way to purge or edit failed attempts at trying to setup an unsupported site

### ISSUE THREAD

**Issue by IonDrako** [dteviot/WebToEpub#1207]
Issue that lead to this request:
Basically I was trying to setup this site to download into an epub {https://yonglibrary.com/__trashed-4/the-extras-academy-survival-guide/2/} and completely didn't understand what I was looking for when putting in the main css pointer so I put in the wrong thing and hit apply instead of test, it seemed like it was working as all the chapter links showed up for selecting but when I tried to pack it it gave an error and lead back to the base file select page but now stuck on searching for urls. I can't find a way to go back and edit the failed attempt at setting up the site, clicking the webtoepub button just shows an error then goes to the searching for url blank page and I can't find anything on that page that'd let me edit the css pointer stuff to try and fix it.

The feature request is to have something that lets a user purge or edit the css stuff for a site in cases where something went wrong (or if that does exist a better way to find it)

**Comment by dteviot** [comment]
@IonDrako 
Good point.

I can think of two possible workarounds.
1. Uninstall WebToEpub and re-install.  That should reset the settings to defaults.  Hopefully it won't be too big a problem to re-create any other settings you will lose.

2. Go to "Advanced Options" and click on the "Write Options to file" button.  Then edit the file to remove the unwanted setting, and then load the edited file back in with the "Choose File" button that's below the "Write Options to file" button.
Note, file is JSON, so this should only be attempted if you've got the skills to handle it.

**Comment by IonDrako** [comment]
The uninstall/reinstall option seems the best for me, thanks for the workaround info. Cheers!

(as this is a feature post idk if you want to close it with the workarounds you posted there or leave it open, I'll leave that up to you)

**Comment by dteviot** [comment]
@IonDrako 
I'm going to leave this open.  Adding ability to clear settings for the default parser is probably something that should be done.  (Eventually.)

**Comment by SpiralBaka** [comment]
are you talking about going back to the page that says "No parser found for this URL. Default Parser will be used. Please specify how to obtain content from each web page."?
if you are, you can just go to 'advanced option' -> 'Manually Select Parser' -> 'Default'
also, I'm pretty sure quitting webtoepub page and going back again (pressing the webtoepub icon again I mean) will make you go back to that page.

sorry if you're talking about something else. it works like that in my computer/browser.
