### ISSUE TITLE
Please update wuxiabee.com

### ISSUE THREAD

**Issue by Mielanjelo** [dteviot/WebToEpub#1208]
Please add or update https://www.wuxiabee.net/ , its not working anymore, thanks

**Comment by sml1961** [comment]
also   https://www.wuxiahub.com/
Thanks

**Comment by dteviot** [comment]
@Mielanjelo @sml1961 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiahub.com/novel/she-becomes-glamorous-after-the-engagement-annulment.html
* https://www.wuxiabee.net/novel/zongwu-sign-in-an-army-of-100000-at-the-beginning.html

For my notes: 13 minutes work

**Comment by sml1961** [comment]
Works fine.  Thank you

**Comment by dteviot** [comment]
Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
