### ISSUE TITLE
Please add site https://readwn.org

### ISSUE THREAD

**Issue by sml1961** [dteviot/WebToEpub#1209]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://readwn.org/book/ms-tan-is-the-real-boss/

### What settings did you use?  What didn't work?
* URL of first chapter              
               https://readwn.org/book/ms-tan-is-the-real-boss/chapter-1
* CSS selector for element holding content to put into EPUB
                 div.txt
* CSS selector for element holding Title of Chapter
                h4
* CSS selector for element(s) to remove
                script

The test seems work fine with the first chapter, but can't retrieve the  list of chapters.

**Comment by sml1961** [comment]
this site seems similar to the sites that are using NovelfullParser
But NovelfullParser seems not working, p.ej.
https://allnovelnext.com/allnovelnext/the-famous-detective-of-the-red-mansion
https://novelfull.net/poison-gods-heritage.html

**Comment by dteviot** [comment]
@sml1961 

Fix was provided by ImLJS 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@sml1961 

And might I add, thank you very much for telling us what site it resembles.  That saves us significant time and effort.

**Comment by sml1961** [comment]
Thank you.  It is working fine.

**Comment by dteviot** [comment]
Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
