### ISSUE TITLE
Please update support for ncode.syosetu.com

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#1210]
they started splitting table of contents into several page with 100 link per page

for example, this novel:
https://ncode.syosetu.com/n8740ce/

this is its 'pager box'

```
<div` class="novelview_pager-box">
<div class="novelview_pager">
<span class="novelview_pager-first">最初へ</span>
<span class="novelview_pager-before">前へ</span>
<a href="/n8740ce/?p=2" class="novelview_pager-next">次へ</a>
<a href="/n8740ce/?p=4" class="novelview_pager-last">最後へ</a>
</div><!--novelview_pager-->
<div class="novelview_result-stats">1&nbsp;～&nbsp;100&nbsp;部分を表示中</div>
</div><!-- /.novelview_pager-box `-->
```

as you can see, it's split into 4 pages, I'd like to get all pages at once.

also, I'd like to get novel info like with many sites. this is its info page (作品情報):
https://ncode.syosetu.com/novelview/infotop/ncode/n8740ce/

in that page, I'd like everything in this tag:
`<div class="clearfix">`

**Comment by dteviot** [comment]
@SpiralBaka 

I received this patch https://github.com/dteviot/WebToEpub/pull/1201 from @ImmortalDreamer a few days ago for Syosetu.
Has been merged into the experimental branch, but versions in stores have not been updated yet.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me and ImmortalDreamer know how it goes.

**Comment by ImmortalDreamer** [comment]
#1201 fixes the issue with pagination, yeah.
I won't be able to work on the information page until this weekend, tho.
Will send a pull request then if it hasn't already been dealt with. @SpiralBaka @dteviot

**Comment by ImmortalDreamer** [comment]
@dteviot @SpiralBaka So, I had a look at this last weekend and it was way more work than I thought, simply because the info is present on a different page. I'm going to try a different approach soon and see if that works.

**Comment by dteviot** [comment]
@ImmortalDreamer 

Thanks for letting us know.

**Comment by ImmortalDreamer** [comment]
@dteviot Took a while but #1247 solves the information page issue. Tested it on both ncode.syosetu.com and novel18.syosetu.com novels, works fine.
@SpiralBaka Please wait for dteviot to merge and provide the test version.

**Comment by dteviot** [comment]
@SpiralBaka @ImmortalDreamer 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@SpiralBaka @ImmortalDreamer

If you confirm this is good, I'll update the Google and Firefox stores.

**Comment by ImmortalDreamer** [comment]
@dteviot Looks good to me.

**Comment by dteviot** [comment]
@ImmortalDreamer 
Thank you for your hard work

@SpiralBaka 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
