### ISSUE TITLE
Please add site https://daodivinetl.com/

### ISSUE THREAD

**Issue by WRed7785** [dteviot/WebToEpub#1217]
Thanks for doing the lords work

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://daodivinetl.com/book/fantasy-investment-return-taking-demon-empress

### Did you try using the Default Parser for the site?  If not, why not?
Yes

### What settings did you use?  What didn't work?
* URL of first chapter: https://daodivinetl.com/book/fantasy-investment-return-taking-demon-empress/1
* CSS selector for element holding content to put into EPUB: div.break-words/#contentNode > div
* CSS selector for element holding Title of Chapter: h1

The error I get every time: "Could not find content element for web page"
Using just body also shows a broken webpage on preview

**Comment by dteviot** [comment]
@WRed7785 
This site already supports a "Download" ability
![image](https://github.com/dteviot/WebToEpub/assets/5157081/53d94adf-c95c-4ff1-9c46-97d813b36d66)
Why is this not adequate?

Notes.
This is one of the difficult sites, the text isn't HTML, instead.  Is assembled via JSON.

Start with table of contents URL: 
https://daodivinetl.com/book/fantasy-investment-return-taking-demon-empress

Call to get a partial list of chapters (50) is:
https://divineserverone.vercel.app/api/book/getChapterMetadata?b_name=3b1d23dd-2432-4410-8c91-9f8c36facc39&page=3&key=U2FsdGVkX19nsg94iWlttTNqcTuHiVzfY98yKNpbFC3vP%2BC8BX%2BeF2p%2BSI2Qu01y

the **b_name** (along with title, author, description and number of chapters) can be obtained by calling
https://daodivinetl.com/api/chBookdata?b_name=fantasy-investment-return-taking-demon-empress
However, this doesn't provide the **key** and call won't work without it.

Obtaining text for a chapter needs a URL like
https://divineserverone.vercel.app/api/book/getChapter?b_name=fantasy-investment-return-taking-demon-empress&chapter=51&key=U2FsdGVkX1%2FPImbcRpZDSBUAhXksErhyIAnvECJmyTm1qxz07j9Saia%2Ft1VjXNBs
And then process the JSON.

For my notes: 24 minutes work

**Comment by WRed7785** [comment]
Downloading requires the premium currency per chapter of download. But if it isn't worth your time, can just close this.
