### ISSUE TITLE
Dynamic Script Updates

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#1219]
Hi,

### **Description**

I've been using your extension for some time now and have found it incredibly useful for saving novel from various websites. However, I've noticed that updating the content retrieval scripts to accommodate changes in website structures can sometimes be cumbersome, especially when waiting for updates to be pushed to the Chrome Web Store, or having to do it manually.

### **Proposal**

I'd like to propose a feature that could streamline this process by allowing the extension to dynamically fetch content retrieval scripts from an external source, such as a GitHub repository. This would enable more immediate updates without relying on Chrome Web Store updates.

### **Implementation Overview:**

- [x] Store the content retrieval scripts in a GitHub repository.
- [ ] Implement functionality in the extension to fetch and use these scripts dynamically.
- [ ] Periodically check for updates to the scripts and download them if changes are detected.

### **Benefits**

- More timely updates to the content retrieval functionality.
- Enhanced user experience through improved usability and maintainability.

I understand that implementing this feature may require some development effort, but I believe it could significantly improve the extension's usability and maintainability in the long run.

Thank you for considering this feature request, and I look forward to hearing your thoughts on the matter.

**Comment by dteviot** [comment]
@Flwk 
I've looked into this in the past.
Unfortunately, it isn't permitted under the Terms of Use for the Chrome and Firefox stores.
Google and Mozilla need to be able to inspect all code that will run in an extension at the time it's uploaded to the store.

They have good reason for this, if they allowed it, bad actors could use this to sneak malicious code into extensions.

**Comment by Flwk** [comment]
@dteviot 
Okay i understand, but isn't possible to do it only for the developer version, not the chrome webstore version ? 

Even if it's not possible, thank you very much for all your work :)

**Comment by Flwk** [comment]
@dteviot 
I wrote a batch script that allows you to automatically download and extract the extension from the Google Drive link. Here it is for those who are interested :)

```
@echo off
setlocal

cd /d "C:\Users\xXxX\Documents\temp\zip"

rem Download the file from GDrive
wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1OFMASy0mx1e8I9FBAKzs_pR5jMMgB2P4" -O "web.zip"

rem Check if the download was successful
if %errorlevel% equ 0 (
    echo The file has been successfully downloaded.
) else (
    echo An error occurred while downloading the file.
)


set "zip_file=C:\Users\xXxX\Documents\temp\zip\web.zip"

set "destination_folder=C:\Users\xXxXxX\Documents\WebToEpub"

rem Make sure that the ZIP file and the destination folder exist.
if not exist "%zip_file%" (
    echo The specified ZIP file does not exist.
    exit /b
)

if not exist "%destination_folder%" (
    echo The specified destination folder does not exist.
    exit /b
)

rem Extracting the ZIP file to the destination folder
echo Extraction in progress....
powershell -Command "Add-Type -A 'System.IO.Compression.FileSystem'; Remove-Item -Path '%destination_folder%\*' -Recurse -Force; [System.IO.Compression.ZipFile]::ExtractToDirectory('%zip_file%', '%destination_folder%');"


echo Extraction completed.

rem The extension https://t.ly/jPPDr will reload all installed extensions on Chrome
start chrome http://reload.extensions

```

You need to install the "Extension Reloader" extension, which you can get [here](https://t.ly/jPPDr), to reload the installed extensions on Chrome.
Then, I have created a task that executes the script every day at a specified time.

It took me a bit of time because I had no idea how to approach it, I hope it will be useful for those who need it.

Thanks again for all the work you do
