### ISSUE TITLE
Add information about WebToEpub in the ebook

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#122]
Currently there's nothing in the epubs explicitly stating that WebToEpub was used, let alone which version.
It would be helpful to have it in there to spread the word and also for submitting bug reports. 
It will also help to sort ebooks, at least for me, if I know which versions of WebToEpub was used to make a certain ebook, it will help me to easily determine whether I should keep/discard it. I can't do that when I encounter epubs made by other people.

This is probably the standard way of including information about the ebook making software, according to [this idpf page](http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.2.6).
```
<dc:contributor opf:role="bkp">WebToEpub (ver. #) [https://github.com/dteviot/WebToEpub]</dc:contributor>
```

Edit: You can also add meta information directly on the header of html files. such as
```
    <meta name="generator" content="WebToEpub ver."/>
```
Both would be nice :D

**Comment by dteviot** [comment]
@toshiya44 
WebToEpub version info now added to epub's contents.opf file.
Change committed to Experimental Tab branch.
Note, given how big a pain it was to get this to work  (Code needs to be different for Firefox and Chrome, and different again between running in Unit Test framework vs running as actual extension), I'm not going to add it to the header for each file, unless you can give me a really good reason for doing so.

Closing.  Please re-open if you have issues.
