### ISSUE TITLE
Please add site https:///www.fansmtl.com/

### ISSUE THREAD

**Issue by sml1961** [dteviot/WebToEpub#1220]
Please add site https://www.fansmtl.com/   seems similar to the sites using  ReadwnParser
Thank you

**Comment by dteviot** [comment]
@sml1961 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.fansmtl.com/novel/dragon-son-in-law-god-of-war.html, chapter 1

For my notes: 16 minutes work

**Comment by sml1961** [comment]
Works fine.  Thank you.

**Comment by dteviot** [comment]
Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
