### ISSUE TITLE
Need Discordapp dot com captcha to download

### ISSUE THREAD

**Issue by SetaMushiroom** [dteviot/WebToEpub#1221]
Solved, please erase this

**Comment by dteviot** [comment]
@SetaMushiroom 
Please put this back. Ideally, along with how you solved it.  It may be useful for others.  It might also tip me off for improvements needed.

**Comment by dteviot** [comment]
Note, I suspect the problem is someone put a link to discord on one of the chapters (or in the author's comments) and WebToEpub has followed the link.  Usually because it has mistaken the link for a link to an image.
