### ISSUE TITLE
Please add site https://gravitynovels.com/

### ISSUE THREAD

**Issue by AzaleaBehati** [dteviot/WebToEpub#1222]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this. (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
Did you try using the Default Parser for the site? If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

What settings did you use? What didn't work?
URL of first chapter
CSS selector for element holding content to put into EPUB
CSS selector for element holding Title of Chapter
CSS selector for element(s) to remove
If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
- Sorry, I don't have any friends that have a develope skills huhu

I've tried Default Parser but it says it doesn't have content element. Please, do help me again. 

Error: Could not find content element for web page 'https://gravitynovels.com/chapter/362-2/'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/DefaultParserUI.js:154:23

**Comment by ImLJS** [comment]
Use "#chapter-content" as value for "(required) CSS selector for element holding content to put into EPUB:".

@AzaleaBehati

**Comment by dteviot** [comment]
@AzaleaBehati 
Work by @ImLJS  has been merged in. Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@AzaleaBehati 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
