### ISSUE TITLE
Please add site https://www.wuxiaone.com/

### ISSUE THREAD

**Issue by TrailNumber** [dteviot/WebToEpub#1224]
The site recently changed its name from WuxiaGo to WuxiaOne, and after that, I couldn't use Webtoepub.

**Comment by dteviot** [comment]
@TrailNumber 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by TrailNumber** [comment]
Thank You!

**Comment by dteviot** [comment]
@TrailNumber 
Reopen, so I know to notify you when version in Chrome and Firefox stores updated.

**Comment by dteviot** [comment]
@TrailNumber 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
