### ISSUE TITLE
pls also add this site, if it's okay >> https://storyseedling.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1226]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://storyseedling.com/series/81592/**

### Did you try using the Default Parser for the site?  If not, why not?

I encountered a similar problem with this site in grabbing too much unnecessary source data... And also, when using the Default Parser, due to the site structure, the grabbed chapters from the table of contents also pulled in the "date of chapter release" which made it rather messy (and including how the chapters were generated in a decremental order, rather than by proper sequence).

Thank you again.

**Comment by AzaleaBehati** [comment]
i second to that

Error: Could not find content element for web page 'https://storyseedling.com/series/22874/v1/1/'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/DefaultParserUI.js:154:23

https://storyseedling.com/series/22874/v1/1/

What should I use for "(required) CSS selector for element holding content to put into EPUB:" ?

**Comment by dteviot** [comment]
@AzaleaBehati 
Read https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

**Comment by ImLJS** [comment]
Use "div.mx-auto .mb-4" as value for "(required) CSS selector for element holding content to put into EPUB:".

Or Wait until owner merges my Code into extension

@AzaleaBehati @plsbenice-immadeofjelly

**Comment by AzaleaBehati** [comment]
Thank you! And duly noted!

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly @AzaleaBehati 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by plsbenice-immadeofjelly** [comment]
@ImLJS @dteviot 

Thank you very much!!!!

**Comment by dteviot** [comment]
Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
