### ISSUE TITLE
The footnotes for this site don't appear in the epub -- https://idleturtle-translations.com/

### ISSUE THREAD

**Issue by norabelle101** [dteviot/WebToEpub#1227]
Hello! This source uses the commonly employed "span tooltip" tags for footnotes, which is the click + hover to see the footnote method, like other sites use. In some cases, the written footnote would be placed within the chapter text, i.e. next to the tooltip tag, but with this source, only the "span tooltip" tags are pulled into the epub, leaving the actual footnote info written in the hovering bubble to be completely omitted from the outputted epub. Was wondering if the footnotes could possibly be generated into the epub for this source, please? Thank you! :)

Example TOC: **https://idleturtle-translations.com/break-up-next-bun/bun-list-of-chapters/**

Example Chapter with Footnotes: **https://idleturtle-translations.com/2020/04/30/bun-chapter-6-blame-tired-heart/**

Reference Image:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/be78d71a-2c0e-4d87-9a0a-7cc5fe8eb084)

**Comment by dteviot** [comment]
@norabelle101 

Tricky.  It's **almost** the same as https://bookswithqianya.com/ and with the same problems  See: https://github.com/dteviot/WebToEpub/issues/1069  

I've managed to extract the footnotes, but there's HTML formatting mixed in with the text, so you get footnotes that look like

![image](https://github.com/dteviot/WebToEpub/assets/5157081/b2115198-cae4-4c72-b6e6-e2cdb2a039c1)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://idleturtle-translations.com/2020/04/30/bun-chapter-6-blame-tired-heart/

For my notes: 52 minutes work

**Comment by norabelle101** [comment]
Thank you!! That's perfectly fine! :)

**Comment by dteviot** [comment]
@norabelle101 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
