### ISSUE TITLE
 [Feature Request] error(s) logging

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#123]
This time on the right place...

I'd like to ask for a little feature.
Right now webtoepub will tell you there were errors here and there when grabbing, at the moment the error happens (like, for an image link).
It would be nice if those "report" were also available later, as a log, possibly in the same directory as the epub.
Would this be possible?

**Comment by dteviot** [comment]
@typhoon71
New commit to ExperimentalTabMode branch.
Added "Write recent error messages to file" button to the Advanced Options area.
The button is found just above the "Developer Stuff" check box.
When clicked it writes all errors that have been previously shown to the user to the file "WebToEpub.Errors.txt".
Does this satisfy your request?

**Comment by typhoon71** [comment]
mmm, it does help, but I'll shamelessy ask for some improvements...

1. I was thinking of this more as an option (a checkbox) that is on or off, unchecked by default, that enables /disables error logs saving. The button works fine, but being in the advanced settings it's not immediate to use.

2. It would be nice if the log filename was the same of the epub that had errors while fetching.

Would this be possible? Thanks.

**Comment by dteviot** [comment]
@typhoon71 
> I was thinking of this more as an option (a checkbox) that is on or off, unchecked by default, that enables /disables error logs saving

Sorry, but I just can't get that to work.  (Under Chrome, when running in popup mode it opens a "Save As" dialog which makes the extension's popup close,   Which terminates the extension before it can save the second file (the error logs.)

> It would be nice if the log filename was the same of the epub that had errors while fetching.

You can't have two files with the same name in the same directory.  However, I can give it a similar name.

**Comment by dteviot** [comment]
@typhoon71 
> It would be nice if the log filename was the same of the epub that had errors while fetching.

New commit to ExperimentalTabMode branch implements this.

**Comment by dteviot** [comment]
@typhoon71 
> I was thinking of this more as an option (a checkbox) that is on or off, unchecked by default, that enables /disables error logs saving.

Latest commit to ExperimentalTabMode branch now does this.  Please let me know what you think.  
Note, you no longer get a SaveAs dialog on Firefox.  That had to go to make it work.

**Comment by typhoon71** [comment]
Perfect, it works as I had in mind. Now errors hunting will be easier.

Regarding the Firefox issue: actually I don't use webtoepub with firefox anymore T_T.
Manually loading addons / updating in crome is as easy as a double click (I scripted it), while in firefox there's always something going wrong... complaint, complaints...

Thanks and sorry for the late reply.

**Comment by dteviot** [comment]
@typhoon71 
>Manually loading addons / updating in crome is as easy as a double click (I scripted it),

Can you provide the script, or a link to where you found out how to do this?

**Comment by typhoon71** [comment]
Sure, it really isn't anything special, just some .bat script on windows.

del WebToEpub-ExperimentalTabMode.zip
del jszip-master.zip
wget --no-check-certificate https://github.com/dteviot/WebToEpub/archive/ExperimentalTabMode.zip -O WebToEpub-ExperimentalTabMode.zip
wget --no-check-certificate https://github.com/Stuk/jszip/archive/master.zip -O jszip-master.zip
rmdir /s /q WebToEpub-ExperimentalTabMode
7z x WebToEpub-ExperimentalTabMode.zip 
7z x jszip-master.zip
rmdir /s /q WebToEpub-ExperimentalTabMode\plugin\jszip
move jszip-master WebToEpub-ExperimentalTabMode\plugin\jszip
del WebToEpub-ExperimentalTabMode.zip
del jszip-master.zip`

The .bat file must be in the same directory as the webtoepub directory.
You'll need 7zip and wget installed and also to add wget to the %path%.

So it deletes leftover downloads, it downloads new webtoepub and jszip, unzips them, deletes the old addon, puts the new stuff inside it, deletes leftover downloads.
I had put the 2 delete lines both at the start and at the end becaue sometimes the files weren't deleted.

So when a new release is available I close crome if open and double click on it, wait, done.
I didn't post it but I got a couple of lines that change the icon with one I like more...

I suppose this will work till crome changes how they deal with unpacked addons, but for now it saves time (you do the install in crome only the first time).
