### ISSUE TITLE
Please add daotranslate.us (former daotranslate.com)

### ISSUE THREAD

**Issue by Y518A** [dteviot/WebToEpub#1234]
The previous site (daotranslate.com) worked fine, with the new site the chapters are not detected.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://daotranslate.us/series/margraves-bastard-son-was-the-emperor/

### Did you try using the Default Parser for the site? 
Yes, since the chapters did not appear, in advanced settings, in the manual parser option I selected default. Subsequently:

URL of first chapter: https://daotranslate.us/margraves-bastard-son-was-the-emperor-chapter-1/
css content: .epcontent
css tittle chapter: .epheader

And with that configuration it worked.

![PrtScr capture](https://github.com/dteviot/WebToEpub/assets/78008257/bb5c15f9-46ce-4530-b11a-4fb5f51d0a08)

**Comment by dteviot** [comment]
@Y518A 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@Y518A 
Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
