### ISSUE TITLE
SufficientVelocity/SpaceBattles/XenForo gives TypeError: Cannot read properties of null (reading 'parentElement') when retrieving third chapter

### ISSUE THREAD

**Issue by Kiradien** [dteviot/WebToEpub#1237]
**Describe the bug**
Failure to generate Epub on a particular fanfic. TypeError is generated when retrieving a specific chapter.

**To Reproduce**
1. Go to 'https://forums.sufficientvelocity.com/threads/a-flung-light-worm-minor-toaru-cross.124037/'
2. Click on '....' under the Threadmarks to show hidden Threadmarks
3. Open WebToEpub
4. Set first chapter to "Power Curriculum" (Chapter 3)
5. Pack EPUB
6. See Error. (If step 4 is skipped, error still occurs when generating Power Curriculum)

**Expected behavior**
Successful generation of epub

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/68683574/7518130f-a918-4564-a3a9-24ce9169dae7)
![image](https://github.com/dteviot/WebToEpub/assets/68683574/1ce1a55c-b609-46cb-a962-9cf2c9529aae)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 122.0.6261.95 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
This can be considered fairly low priority; this is an outlier and most fics on SV and SB work fine. I will also look into this myself when I have a bit of time.

EDIT: This is not an outlier, and seems to affect all fics on SV. SB seems unaffected.

**Comment by Kiradien** [comment]
Hmm, also happens on third chapter at https://forums.sufficientvelocity.com/threads/philosophers-tinker-worm.127516/

This may not be as rare as expected?

**Comment by ImLJS** [comment]
I looked at it. Found that some chapter at spacevelocity has different format.

https://forums.sufficientvelocity.com/threads/philosophers-tinker-worm.127516/#post-30669169 - Extension Worked
https://forums.sufficientvelocity.com/threads/philosophers-tinker-worm.127516/post-30724429 - Caused Error

Only difference was that the last bit does not have a hashtag. Spacebattles still use hashtag in chapter urls

I Uploaded the Trial Extension Here: [Mediafire](https://www.mediafire.com/file/llf1okv271p9tqt/WebToEpub0.0.0.158.zip/file) . Test it out.

**Comment by masteoo** [comment]
@ImLJS hello, sorry to disturb, do you think is possible to save gobi3.com previews? Thanks for your work

**Comment by masteoo** [comment]
@ImLJS 
credentials for gobi3.com:
CSUSBfaculty@csusb.edu
Password: Library4U!

Thanks for your time

**Comment by ImLJS** [comment]
@masteoo Can you tell me where those previews are located. Can't Find Them.

**Comment by masteoo** [comment]
@ImLJS if you search for a ebook like 
_Title: SEMIOTIC OF ETHNICITY: IN (RE)COGNITION OF THE ITALIAN/AMERICAN WRITER.
Author: TAMBURRI, ANTHONY JULIAN_
you can click Preview button and a page opens with ebook

**Comment by ImLJS** [comment]
@masteoo Checked just now. It actually embeds a pdf within the website. In that case it is not possible to get content form the website using the extension. Sorry about that.

**Comment by ImLJS** [comment]
It actually does not matter if the content is in epub or pdf. What matters is that the text should be present within the website and not as a whole file.

Example:
<img width="488" alt="image" src="https://github.com/dteviot/WebToEpub/assets/109210868/87bd55c3-a085-48ae-8615-3d9dd5b7b110">

In above image, you can see that the text is present within website content.

<img width="635" alt="image" src="https://github.com/dteviot/WebToEpub/assets/109210868/9bcae178-cb0e-4b31-8144-77d415f9819b">

In the above one, a file is placed as a content in the website. In the above case, we can't extract it. Only way, is to download it.

**Comment by masteoo** [comment]
@ImLJS 😔 .. thanks for explanation, all clear. If you have suggestion how to adapt the script I linked I appreciate for your help (I m not a programmist). Thanks again

**Comment by ImLJS** [comment]
@masteoo Checked Now. It turns out the URL of the book is not supported by the program. So, can't do anything about that.

**Comment by masteoo** [comment]
@ImLJS thats the problem, ebook links are similar but not the same, don't know how to adapt the script for my preview links. Thanks anyway

**Comment by dteviot** [comment]
@masteoo 
Also, as the file you're trying to get is a pdf, you can download it with your web browser.
At a high level, the steps are
1. Obtain the URL of the pdf.  (Look at the HTML source, https://www.lifewire.com/view-html-source-in-chrome-3466725) the URL is the bit in the &lt;iframe in the clip from ImLJS above.)
2. Type the URL into the browser.
3. PDF will download.  (Note, you may need to adjust the browser to download instead of viewing. https://www.howtogeek.com/721441/how-to-download-pdfs-instead-of-previewing-them-in-chrome-firefox-and-edge/)  Remember to reverse setting when you're done.  Or, once you're viewing the PDF, I think you can save it.

**Comment by masteoo** [comment]
@dteviot thanks for the feedback. Only ebook cover is pdf I think and most of the ebooks I need are stored as a content. No right clicks for copy/paste are allowed :(

**Comment by dteviot** [comment]
@masteoo 
To use Chrome's developer tools, select Menu (three dots) > More tools > Developer tools.  
This works when right click is disabled.

**Comment by masteoo** [comment]
@dteviot thanks for the suggestion but text selection on dev tool is a mess cause there are too many paragraph marks (see photo). I can also select text and Ctrl+c for every chapter but there are too many chapters to do 😅
![Screenshot_20240305_084215_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/120033556/075a9c3c-56be-49aa-b68d-dda88309eaff)

**Comment by dteviot** [comment]
@masteoo 
We should take this conversation to a new issue.  It's spamming the original people who raised this who don't care about Gobi.  That said, I think you probably need to use a different tool.

@ImLJS 
Experimental version at usual place has been updated.

**Comment by Kiradien** [comment]
Just a small update regarding this - note that **the fix still works**, however the bug now also affects SpaceBattles as well. 

It looks like this was caused by an update to XenForo, so it's possible other platforms on XenForo may run into the same issue in the future as they update their versions.

I'll rename this to hopefully reduce duplicate tickets until patch goes live.

**Comment by ImLJS** [comment]
@Kiradien I just looked at it. I put out fix for spacebattles and spacevelocity together. Experimental version of extension is working properly for both the websites. Try That Out.
