### ISSUE TITLE
Generic parser 'ends on' feature

### ISSUE THREAD

**Issue by StefKalders** [dteviot/WebToEpub#124]
Currently if I want to use the generic parser I need to point to the div where it starts. Unfortunately some blogs have loads of clutter at the bottom but in the same div, like comments/reviews. An 'ends on' feature would be great. Any way to do this?

Site that I'm trying to parse: http://blastron01.tumblr.com/kumoko-contents

**Comment by dteviot** [comment]
@StefKalders
> Any way to do this?

The short answer is, "it's complicated".
If you've got some basic javascript knowledge, then the easist way to do this is write a new parser and implement the removeUnwantedElementsFromContentElement(element)
function.

If I look at the URL you provided, I can see that the clutter elements are:
* a &lt;ul&gt; element with a class of "meta"
* a &lt;div&gt; element with a class of "permalink-footer clearfix"

So, off the top of my head the function would be

removeUnwantedElementsFromContentElement(element) {
    util.getElement(element, "ul", u => u.className === "meta").remove();
    util.getElement(element, "div", u => u.className.startsWith("permalink-footer")).remove();
}

Unfortunately, I can't see a way to explain how to do this to someone who does not have javascript knowledge.  
(As it would also need to include "how to debug if/when it doesn't work".)
Hence, the reason it's not available in the Default parser.
Obviously, if you've got any suggestions on how I could solve this problem, I'd love to hear them.

Also, if you have basic javascript knowledge, then creating a new parser for something like this is only 10 minutes work.
Basic steps are:
1. Install from Source, using instructions at https://github.com/dteviot/WebToEpub
2. Copy the file "Template.js" in the folder plugin/js/parsers.
3. Rename the copied file, based on the site you want to parse e.g. in this case, you'd call it BlastronParser.js.
4. Add link to the new parser to popup.html.
5. Text replace "Template" in the file with the new Parser name (BlastronParser)
6. Uncomment the functions of the template you need, modifying the sample implementations as required.

If you'd like to try implementing a new parser and the above is insufficient, I'd be delighted to assist you further.
In case it's not obvious, I'd like to do everything I can to make it as easy as possible for people to write their own parsers, so I don't have to keep on doing it.
So anything you can tell me to make it easier would be appreciated.

**Comment by dteviot** [comment]
Closing due to lack of response from @StefKalders
