### ISSUE TITLE
Please add site https://midnightrambles.in/

### ISSUE THREAD

**Issue by Naanaa28** [dteviot/WebToEpub#1241]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://midnightrambles.in/2021/07/14/cub-raising-association/?expand_article=1

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
yes.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you tried writing a parser, and it doesn't work.  Attach the parser here.

ISSUE:  
The webtopub page loads normally, but when I click "Pack Epub" I receive this error, even when I tried changing the parser.

 Error: Could not find content element for web page 'https://midnightrambles.in/2021/07/16/cra-ch-85/'.
    at chrome-extension://immimmokppigcgcpliapdafdecdkfoha/js/Parser.js:501:23
    at async Promise.all (index 0)
    at async MidnightramblesParser.fetchWebPages (chrome-extension://immimmokppigcgcpliapdafdecdkfoha/js/Parser.js:470:17)

**Comment by Naanaa28** [comment]
Sorry! It worked when I tried again and set the throttle delay to 10 seconds (didn't work at 5 seconds). anyways Excuse me

**Comment by dteviot** [comment]
Reopen to investigate.  From description , chapter 85 on site might have different format.

**Comment by dteviot** [comment]
@Naanaa28 

Are you sure WebToEpub is working for you?

Site seems to have changed layout.  Looks like it's now a Wordpress derivative, but riddled with ezoic adds.
e.g. 
https://midnightrambles.in/2023/09/28/part-time-taoist-priest-pttp-bl/, first chapter doesn't work with existing parser.

For my notes: 23 minutes work

**Comment by Naanaa28** [comment]
> @Naanaa28
> 
> Are you sure WebToEpub is working for you?
> 
> Site seems to have changed layout. Looks like it's now a Wordpress derivative, but riddled with ezoic adds. e.g. https://midnightrambles.in/2023/09/28/part-time-taoist-priest-pttp-bl/, first chapter doesn't work with existing parser.

Hello! Yes! Looks like it works even without throttle delay using the Wordpress parser! Even with the link you provided ^^ (first chapter being 1.1 Star Bone). 

However packing it without manually selecting the wordpress parser from advance options does gives the error. (So it seems the throttle delay doesn't really make a difference so my previous comment solution was wrong. Pls excuse me. ^^;)
Error: Could not find content element for web page 'https://midnightrambles.in/2023/10/02/pttp-ch-1-1-star-bone/'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:501:23
    at async Promise.all (index 0)
    at async MidnightramblesParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:470:17)

It is true the site changed though. I was able to smoothly pack from there before but at least looks like it's still okay now.


> Reopen to investigate. From description , chapter 85 on site might have different format.
For this one, chapter 85 is the regular format but chapter 84 is for a different site that seems to now be obsolete so I skipped that chapter. 

anyways again Thank You! and excuse me. ^w^

**Comment by dteviot** [comment]
@Naanaa28 

I've  updated WebToEpub so should now work for midnightrambes without you needing to do anything.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://midnightrambles.in/2023/09/28/part-time-taoist-priest-pttp-bl/, chapters 1 &amp; 2

For my notes: 35 minutes work

**Comment by dteviot** [comment]
@Naanaa28 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
