### ISSUE TITLE
Tapas fails with Network error 400

### ISSUE THREAD

**Issue by japzone1** [dteviot/WebToEpub#1242]
**Describe the bug**
After logging into Tapas and maybe downloading one novel, second novel cannot be parsed and returns error:

Firefox:

    Fetch of URL 'https://tapas.io/series/info/episodes?page=1&sort=OLDEST&max_limit=9999' failed with network error 400. onResponseError@moz-extension://23a2e397-4868-4a50-8303-14571021208a/js/HttpClient.js:32:25
    checkResponseAndGetData@moz-extension://23a2e397-4868-4a50-8303-14571021208a/js/HttpClient.js:188:45
    wrapFetchImpl/<@moz-extension://23a2e397-4868-4a50-8303-14571021208a/js/HttpClient.js:182:31

Kiwi(Chromium):

    Error: Fetch of URL 'https://tapas.io/series/info/episodes?page=1&sort=OLDEST&max_limit=9999' failed with network error 400.
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:32:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:188:45)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:182:31
    at async TapasParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/TapasParser.js:14:21)

**To Reproduce**
1. Go to 'Tapas.io' and download a novel (ex: [https://tapas.io/series/solo-leveling-novel/info](https://tapas.io/series/solo-leveling-novel/info)\) with Web2Epub
2. Open another novel (ex: [https://tapas.io/series/solo-leveling-ragnarok-novel/info](https://tapas.io/series/solo-leveling-ragnarok-novel/info)\) and try to download with Web2Epub
3. You'll see "Searching for URLs. Please wait."
4. And then the error from above appears.

**Expected behavior**
TOC to be parsed so I can download the novel

**Screenshots**
![2024-03-05 17_39_52](https://github.com/dteviot/WebToEpub/assets/6744865/73415809-2fca-4ec8-b8f9-08b4f8aff674)
![2024-03-05 17_41_48-Default-2021 - WebToEpub — Firefox Developer Edition](https://github.com/dteviot/WebToEpub/assets/6744865/18eb7923-0bb2-41fa-a90b-7a4eb31fc70a)
![2024-03-05 17_40_58-Default-2021 - WebToEpub — Firefox Developer Edition](https://github.com/dteviot/WebToEpub/assets/6744865/ff35c5fa-8e84-4196-be61-d819fd3432f7)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Browser Firefox
 - Version 122.0b7

**Smartphone (please complete the following information):**
 - Device: Asus ROG Phone 6
 - OS: Android 13
 - Browser Kiwi (Chromium based)
 - Version 120.0.6099.116

**Comment by dteviot** [comment]
@japzone1 

@ImmortalDreamer provided some fixes for Tapas.io.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by japzone1** [comment]
> @japzone1
> 
> @ImmortalDreamer provided some fixes for Tapas.io.
> 
> Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with Firefox. 

It does seem to fix the issue, as TOC is being parsed properly and chapters download fine. Only other thing I notice is that for some reason it's grabbing my Tapas username as the book title and filename, instead of the actual novel title. Can be manually corrected, but it is annoying.

**Comment by dteviot** [comment]
@japzone1 
> Only other thing I notice is that for some reason it's grabbing my Tapas username as the book title and filename, instead of the actual novel title. 

Any chance you can send the HTML of the page with you logged in?  And tell me what your name is, so I can find it in the HTML.

**Comment by japzone1** [comment]
> @japzone1
> 
> > Only other thing I notice is that for some reason it's grabbing my Tapas username as the book title and filename, instead of the actual novel title.
> 
> Any chance you can send the HTML of the page with you logged in? And tell me what your name is, so I can find it in the HTML.

Censored it with "GITHUBUSER"
[Read Solo Leveling Tapas Web Novels.txt](https://github.com/dteviot/WebToEpub/files/14612297/Read.Solo.Leveling.Tapas.Web.Novels.txt)

**Comment by dteviot** [comment]
@japzone1 

Should be fixed now.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://tapas.io/series/solo-leveling-ragnarok-novel/info

For my notes: 10 minutes work

**Comment by japzone1** [comment]
> @japzone1
> 
> Should be fixed now.
> 
> Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes. Tested with:
> 
>     * https://tapas.io/series/solo-leveling-ragnarok-novel/info
> 
> 
> For my notes: 10 minutes work

Yep, all working. Thanks for the help. 👍

**Comment by dteviot** [comment]
@japzone1 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
