### ISSUE TITLE
Please add/update site https://www.fannovels.com/

### ISSUE THREAD

**Issue by xancia** [dteviot/WebToEpub#1243]
The site used to be named fannovel but now it's fannovels with an "s". Can you update it so it works with the new url? Thank you

**Comment by dteviot** [comment]
@xancia 

fannovels was added to experimental branch 5 days ago by @ImLJS.  Version in Chrome and Firefox stored has not been updated yet.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 4 minutes work.

**Comment by dteviot** [comment]
@xancia 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
