### ISSUE TITLE
Please add https://novelactive.org/

### ISSUE THREAD

**Issue by xanatos** [dteviot/WebToEpub#1244]
Please can you add support for https://novelactive.org/ ? Thanks!

**Comment by dteviot** [comment]
@xanatos 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@xanatos 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.

**Comment by xanatos** [comment]
Thanks!
