### ISSUE TITLE
Stopped working properly on Spacebattles.com

### ISSUE THREAD

**Issue by nakie08** [dteviot/WebToEpub#1248]
**Describe the bug**
Packing of EPUB on Spacebattles stops after 3 chapters.

**To Reproduce**
1. Go to https://forums.spacebattles.com/
2. Select a fanfiction with more than 4 chapters like this one for example https://forums.spacebattles.com/threads/sublight-drive-star-wars.1095425/
3. Pack EPUB
4. Plugin stops at the 3rd or 4th chapter and throws an error

**Expected behavior**
All chapters are packed

**Screenshots**
![ERROR](https://github.com/dteviot/WebToEpub/assets/43413471/535065c6-638f-473e-acd4-8d1a5d1c8e15)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome but I also tested it on Firefox with same result
 - Version 122.0.6261.112

**Additional context**
I'm not sure if this is just a problem on my end, but I have been using this app for about a year now on SB and this is the first time it stopped working for me.

**Comment by dteviot** [comment]
@nakie08 @ImLJS 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
