### ISSUE TITLE
Please add or update site https://www.wuxiabee.org

### ISSUE THREAD

**Issue by Mielanjelo** [dteviot/WebToEpub#1250]
Please update www.wuxiabee.org , its not working anymore, thank you

**Comment by dteviot** [comment]
@Mielanjelo 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
