### ISSUE TITLE
lightnovelreader URL update to  --> https://readlitenovel.com/  

### ISSUE THREAD

**Issue by ghus3rz** [dteviot/WebToEpub#1251]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://readlitenovel.com/  

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
I had checked and it seems the last URL updated for this was  "lnreader.org". However this is the same site as it was redirecting users to new sites over the course of few months and this is now latest site

I try adding it on local copy of LightnovelreaderParser.js which did work, unfortunately I am not familiar with github other then to update this information as issues 

### What settings did you use? 
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
add the lines below to LightnovelreaderParser.js as I noticed some novel URLs were on .com while some seem to be on .app URL
parserFactory.register("readlitenovel.com", () => new LightnovelreaderParser());
parserFactory.register("readlitenovel.app", () => new LightnovelreaderParser());

it is working for me by updating the test copy of the extensions locally but just updating the information here in case the main parser can be updated so it will also be in the official version

Thanks

**Comment by dteviot** [comment]
@ghus3rz 

Fix provided by ImLJS

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@ghus3rz 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
