### ISSUE TITLE
Please add site https://www.wuxiabee.org

### ISSUE THREAD

**Issue by sml1961** [dteviot/WebToEpub#1255]
https://www.wuxiabee.net    now rediriges to    https://www.wuxiabee.org
also
https://www.wuxiahub.com  now rediriges to     https://www.wuxiaone.com
https://www.fannovel.com    now rediriges to     https://www.fannovels.com
https://www.novelmtl.com    now rediriges to    https://www.wuxiazone.com
https://www.novelmt.com     now rediriges to    https://www.wuxiafox.com

all these sites use  the ReadwnParser

Thank you

**Comment by sml1961** [comment]
Oops.  Seems  that these sites had already  been requested.
Sorry

**Comment by dteviot** [comment]
@sml1961 

https://www.wuxiafox.com/ wasn't included.  Is now.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiafox.com/novel/transmigrated-canon-fodder-please-calm-down.html

For my notes: 10 minutes work

**Comment by dteviot** [comment]
@sml1961 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
