### ISSUE TITLE
The footnotes in this site are repeated twice --> https://storyseedling.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1260]
Hello! Sorry for being back again with another issue, but the footnotes in this source are repeated twice for each note, one within the chapter text and the second one (which is correct) is stored at the bottom of the respective chapter. Is it perhaps possible to solely remove the first occurrence (the hover tooltip one) that's currently written into the chapter text please?

**Example Table of Contents:** https://storyseedling.com/series/91120/

**Example Chapter with Footnotes:** https://storyseedling.com/series/91120/1.1/

![image](https://github.com/dteviot/WebToEpub/assets/161710539/fc3dd61c-2eec-4424-b795-ee11beb8e6bb)

Thank you again for your help~ :)

**Comment by ImLJS** [comment]
Hey I looked at it. Here is the trial version [Mediafire](https://www.mediafire.com/file/adveluomdcwkro1/WebToEpub0.0.0.158.zip/file). Test it out and check if it is working.

**Comment by plsbenice-immadeofjelly** [comment]
Hello! Thank you for your help! But that actually deleted both the footnote and the required <sup></sup> tags as well, which link it to the footnotes at the bottom of the chapter (second occurrence). Though, I was able to make it work with the ePubEditor! :D But, thank you again for all your continued help, it's much appreciated xx
