### ISSUE TITLE
SpaceBattles not working due to Null Return on Parser

### ISSUE THREAD

**Issue by OffTheCuff424** [dteviot/WebToEpub#1261]
**Describe the bug**
Firefox WebToEPUB fails to download all threadmarks of a story from SpaceBattles.

**To Reproduce**
1. Go to any Creative Writing story thread page 1 with 30+ threadmarks (or enough for SpaceBattles to truncate the threadmark list at the top of the page)
2. Click on '...' in the truncated threadmark list at the top of the webpage to fully expand full threadmark list
3. Open WebToEPUB extension, use default settings, click 'Pack' button
4. WebToEPUB begins but once it hits a link not part of the original truncated threadmark list (first link of the expanded portion of threadmark list), the download will error out and allow you to save a very incomplete epub of the story.
5. At this point, the WebToEPUB page will show that only the first few out of all the threadmark links were packed (for example: 3 out of 25)
6. Resulting ErrorLog.txt:
fetchedDom.getElementById(...) is null fetchChapter@moz-extension://1e2a1a21-fc56-4765-9325-624ff061cc68/js/parsers/SpacebattlesParser.js:40:33

**Expected behavior**
All threadmarks are packed (for example: 25 out of 25) and the saved EPUB will have all chapters from the threadmarks.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.7.2
 - Browser: Firefox 115.8.0esr (64-bit)
 - Version WebToEPUB 157

**Comment by ImLJS** [comment]
@OffTheCuff424 Issue is already fixed. Use the experimental version of the Extension.

**Comment by ImLJS** [comment]
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@OffTheCuff424 

Updated version (0.0.0.158) is now available from Chrome and Firefox stores.
