### ISSUE TITLE
Please add site https://18.foxaholic.com/

### ISSUE THREAD

**Issue by Funkylionz** [dteviot/WebToEpub#1262]
First of all thank you so much for making this app i appreciate you work.
The app works but it does not pull all the chapters sometimes it does tho i don't know why its not because they are locked sometimes the app pulls all chapter including one locked one  i tried the default parser but still no dice for the parser i used div.test-left for the content.

here's the link https://18.foxaholic.com/novel/after-a-one-night-stand-with-the-male-lead/

Again thank you.

**Comment by dteviot** [comment]
@Funkylionz 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://18.foxaholic.com/novel/after-a-one-night-stand-with-the-male-lead/ chapter 1

For my notes: 15 minutes work

**Comment by Funkylionz** [comment]
Thank you for your work. but the same issue remains the app grabs the unlocked chapters, but the locked ones remain 
unless that's by design or am i doing something wrong ?

**Comment by dteviot** [comment]
@Funkylionz 
Not so much by design, as the site doesn't provide a URL for the locked chapters.
e.g. Hover over the chapter link, and you should see the URL for the chapter.
For unlocked chapters, you get the URL with the chapter text.
For locked chapters, you get the URL of the ToC page.

Do you have permission for the locked chapters?

**Comment by Funkylionz** [comment]
I see, no i don't thank you though and i apologize for wasting your time.

**Comment by Jwjshhi** [comment]
> I see, no i don't thank you though and i apologize for wasting your time.

I tried to make am epub out of this
https://18.foxaholic.com/?s=The+Clueless+Girl+Gets+F**ked+Every+Day&post_type=wp-manga
But i am facing captcha issue.
I think its the cloudflare bypass that's causing the issue . 
Is there any solution for this. I can't make an epub from this site

**Comment by Funkylionz** [comment]
> > I see, no i don't thank you though and i apologize for wasting your time.
> 
> I tried to make am epub out of this https://18.foxaholic.com/?s=The+Clueless+Girl+Gets+F**ked+Every+Day&post_type=wp-manga But i am facing captcha issue. I think its the cloudflare bypass that's causing the issue . Is there any solution for this. I can't make an epub from this site
 
maybe use a different browser i just tried it and it works fine.

**Comment by dteviot** [comment]
@Jwjshhi 
Usually with Cloudflare you browse the site normally to trigger the captcha and once that's done you can run WebToEpub.

**Comment by dteviot** [comment]
@Funkylionz @Jwjshhi

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
