### ISSUE TITLE
secondlifetranslations.com doesn't download after pack is done.

### ISSUE THREAD

**Issue by Elthara** [dteviot/WebToEpub#1265]
**Describe the bug**
Trying to save this story: https://secondlifetranslations.com/novel/just-want-to-be-his-lover/

After hitting 'pack' there was an error when trying to save the cover page with the story info and table of contents. After unchecking that it proceded to pack as normal.
When the bar filled up it just stopped, no download pop-up. I also re-tried with 'Don't popup 'SaveAs' dialog when save Epub' turned on, and nothing saved. No error log was generated, either.

**Expected behavior**
I was expecting it to save when finished packing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 124.0.1

**Additional context**

**Comment by dteviot** [comment]
@Elthara 

It worked for me.  If you can provide the error message, I might be able to do more.

**Comment by Elthara** [comment]
There wasn't an error message at all though, it just finished and nothing happened, no dialogue, no pop up, nothing. But I tried it again just now and it worked perfectly fine, so I'm guessing it was just a connection or site issue last night.

Sorry to bug you!

**Comment by dteviot** [comment]
This error message
> there was an error when trying to save the cover page with the story info and table of contents.
