### ISSUE TITLE
The chapter content on this site is all jumbled and all paragraphs are misplaced (from where it's originally positioned on the webpage)

### ISSUE THREAD

**Issue by bonnetchuu** [dteviot/WebToEpub#1267]
Hello!

I'm not sure what the issue with this site [**https://www.cntranslations.com/**] is, but the chapter content isn't scrambled per se, the paragraphs are simply jumbled and placed all over the page but entirely varies from where it's originally placed on the webpage when viewing online. Like, for example, a paragraph at the very end of the chapter will instead be outputted at the beginning of the chapter when the epub is generated.

**[For convenience, I also attached the epub file with these errors in a zip to use for reference. See the very bottom of this issue for downloadable file.]**

There are also multiple usages of `<sub>` tags throughout the chapter so the text sizes vary too, but the font sizes of the chapter content on the webpage is all normal so perhaps this is by design for copy protection? Because the text ensconced in these `<sub>` tags are part of the chapter content, but the text is just scattered in all the wrong places within the chapter (once outputted into the epub)...

For some reason as well, translator/author notes at the bottom of the chapter will randomly be generated alongside a paragraph within the chapter (out of nowhere), meshing with the actual chapter content.

On the webpage:

![image](https://github.com/dteviot/WebToEpub/assets/141732398/a4eb8c6c-ad49-499b-bf8c-35b0323c5e7b)

In the epub:

![image](https://github.com/dteviot/WebToEpub/assets/141732398/16436ca6-f33c-43b2-a0ff-cefe80923064)

![image](https://github.com/dteviot/WebToEpub/assets/141732398/3e628ffe-8e97-4edd-9190-34304eb62d12)

The example TOC I used for the above issue is: **https://www.cntranslations.com/p/the-long-road-ahead.html**

Example Chapter (with all these factors): **https://www.cntranslations.com/2022/04/the-long-road-ahead-c01.html**

I apologise for my poor explanation and for the inconvenience my request may cause. If this is too laborious, please let me know and I'll close this issue. Thank you again for all the help and apologies for the trouble :)

[Example ePub with this Error.zip](https://github.com/dteviot/WebToEpub/files/14775191/Example.ePub.with.this.Error.zip)

**Comment by dteviot** [comment]
@bonnetchuu 

Interesting.  Looks like what they've done is :
1. Take the original paragraphs
2. Then add in lots of other paragraphs and spans. The original text remains, but it's buried in the "noise".
3. Tag the noise in various ways, so browser hides it when viewing site normally.  There are at least two mechanisms.
   3.1 Have an attribute of aria-hidden='true'
   3.2 Javascript list of classes to hide.  Although it looks like the wanted paragraphs all contain a br element.
   
So, the following EpubEditor script will remove nearly all the noise.
```Javascript
            for(let p of [...dom.querySelectorAll("span[aria-hidden='true']")]) {
                    p.remove();
            }

            for(let p of [...dom.querySelectorAll("p")]) {
                if (p.querySelector("br") === null) {
                    p.remove();
                }
            }
            return true;
```

Note: 
1. It doesn't fix the random author/translator note.
2. Footnotes are still mixed in with the text.  They have a class of "tooltiptext" so could be ripped out.
   Actually migrating them to footnotes at bottom of page would require a more complex script

Tested with https://www.cntranslations.com/p/the-long-road-ahead.html, Chapters 1 and 2
For my notes: 58  minutes work

**Comment by bonnetchuu** [comment]
Thank you very much!! This fixed the issue really well! :D
