### ISSUE TITLE
[Wordpress] Keep the url of the current page in chapter url list

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#127]
Currently only the urls linked in the page where WebToEpub is activated is listed in the chapter list, but not the page itself.
While many wordpress sites post links to chapters in a single page, some people post full text pages as well. [Kondee Translations](https://kondeesite.wordpress.com/omae-o-otaku-ni-shiteyaru-kara-ore-o-riajuu-ni-shitekure-volume-3/) for example. 
So it would be nice to have a link for the current page at the top of the chapter url list.

**Comment by dteviot** [comment]
https://kondeesite.wordpress.com/omae-o-otaku-ni-shiteyaru-kara-ore-o-riajuu-ni-shitekure-volume-3/  does not look like a "links" page, it's an entire volume on a single web pages.  (Something like a Baka-Tsuki "full text" page e.g. https://www.baka-tsuki.org/project/index.php?title=BlazBlue:Phase_0).
The "chapter list" pages for that site appear to be:
- https://kondeesite.wordpress.com/omae-o-otaku-ni-shiteyaru-kara-ore-o-riajuu-ni-shitekure/
- https://kondeesite.wordpress.com/translation-projects-list/the-youthful-lariat/
- https://kondeesite.wordpress.com/chuuko-demo-koi-ga-shitai/
etc.

I'll also add, it's possible to add that you can manually enter additional pages by clicking on the "Edit Chapter URLs" button.

That said, I'll see what I can do.  Might be a little while, I'm currently trying to implement creating EPUB version 3 files.

**Comment by dteviot** [comment]
@toshiya44
I've added a "Add Page with Chapters to Chapters List" checkbox to "Advanced Options".
Checked into the Experimental Tab branch.
Please let me know if this is what you wanted.
Note.  Only applies to pages you visit AFTER it has been checked.
Also, if you can give bettter label for checkbox, that would be appreciated.

**Comment by dteviot** [comment]
Version 0.0.0.39 (which has fix) has been submitted to the Google WebStore.
