### ISSUE TITLE
Can you please fix the proper order of the chapters for this site https://bloomingsilk.blogspot.com/p/but-i-fell-in-love-with-you-h.html?m=1

### ISSUE THREAD

**Issue by Blakemontefalco** [dteviot/WebToEpub#1270]
https://bloomingsilk.blogspot.com/p/but-i-fell-in-love-with-you-h.html?m=1

Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@Blakemontefalco 
Going to say no.
There are 3 stories on the site.  Each one orders the chapters differently.
* **The Little Princess** is 15 chapters, in reverse order.  And finished.
* **Young Master, come and possess me!** - has not been updated in more than a year. - Is blocks of 10, in reverse order. I suggest reversing the order, then copy/paste blocks of 10
* **But I fell in love with you** Finished. - Chapters are blocks of 10, but order inside blocks is not the same.

For my notes: 41 minutes work.
