### ISSUE TITLE
Thank you. Please add https://daotranslate.us

### ISSUE THREAD

**Issue by louie023** [dteviot/WebToEpub#1271]
I know that you are busy sir and might not see this. But I just want you to know Im one of those grateful that you made this app. Thank you so much for your hard work Im still studying and reading is one of my fun things to do which relieved me stress. If I have started working and has fund Im willing to contribute to this app and get you some helpers. I hope you can add this site Im not techy and I really needs some help when it come to this programming stuff. Once again thank you.
https://daotranslate.us/series/regressor-of-the-fallen-family/

**Comment by ImLJS** [comment]
@louie023 Checked just now! It is Working btw. If it is not working for you, try to use the experimental version of the extension.

**Comment by louie023** [comment]
> @louie023 Checked just now! It is Working btw. If it is not working for you, try to use the experimental version of the extension.

Thank you for your kind reply sir It works with the experimental version.

**Comment by dteviot** [comment]
@louie023 
I checked the commit history.  
Support was added in 2024-03-02
Version 0.0.0.158 was posted to Chrome and Firefox stores on 2024-03-23
So latest version in stores should work. 
Please check that you have version 0.0.0.158
