### ISSUE TITLE
https://kaystls.site/  fails to grab chapters

### ISSUE THREAD

**Issue by kevin01523** [dteviot/WebToEpub#1275]
**Describe the bug**

**To Reproduce**
1. Go to 'https://kaystls.site/the-reincarnator-is-reborn-into-a-former-famous-aristocratic-family-on-the-frontier-born-into-a-family-where-muscles-and-power-are-considered-the-embodiment-of-justice-he-is-a-good-natured-maverick/'
2. Click on 'webtoepub icon'
3. scroll down
4. see that theres no chapters

**Expected behavior**

clicks webtoepub extension icon 
and webtoepub gets title and chapterlists completely

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/8380242/6a9c1bb0-cbc8-42e4-a1c0-65360f1de377)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]fedora 39 aka nobara linux 
 - Browser [e.g. chrome, safari] tested on brave and chromium
Brave
[Version 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)](https://brave.com/latest/)

Chromium
Version 123.0.6312.86 (Official Build) Fedora Project (64-bit)

**Comment by dteviot** [comment]
@kevin01523 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kaystls.site/the-reincarnator-is-reborn-into-a-former-famous-aristocratic-family-on-the-frontier-born-into-a-family-where-muscles-and-power-are-considered-the-embodiment-of-justice-he-is-a-good-natured-maverick/ chapter 1
* https://kaystls.site/prince-i-dont-want-to-be-killed-by-you-this-time-the-poor-lady-who-was-framed-by-the-saint-avoids-being-skewered-the-second-time/, chapter 1 &amp; 2

For my notes: 23 minutes work

**Comment by dteviot** [comment]
@kevin01523 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
