### ISSUE TITLE
Indenting first line in paragraphs

### ISSUE THREAD

**Issue by michel-de-mont** [dteviot/WebToEpub#1277]
Hello! Is there a way to make WebToEpub indent the first line of paragraphs so that it is formatted like a normal book or ebook, instead of like web text? My apologies if this is the wrong place to ask, thanks.

**Comment by dteviot** [comment]
@michel-de-mont 

The answer is "It will depend on the site."  Assuming the site has formatted each paragraph inside a &lt;p&gt; tag, then yes.
Under the advanced options, there is a CSS option.  You just need to update this to include an instruction to indent text in &lt;p&gt; tags.  https://blog.hubspot.com/website/how-to-indent-css#:~:text=The%20CSS%20text%2Dindent%20property,be%20intended%20to%20the%20left.

Note, you could also update the style sheet in any epub you have already downloaded using a tool like Calibre.

However, you'll find not all sites use &lt;p&gt; tags.  Some use &lt;div&gt; tags instead.  You could also try adding an instruction to indent &lt;div&gt; tags as well.  But &lt;div&gt; tags are used for other things than paragraphs, so this might have unexpected side effects.
