### ISSUE TITLE
Chapter fetching error (503)

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#128]
URL: http://liberspark.com/novel/tales-of-the-reincarnated-lord

Probably because of the Cloudflare thing this site uses, content fetching fails in both tab and pop-up mode. 

```
Fetch of URL 'http://liberspark.com/read/tales-of-the-reincarnated-lord/chapter-173' failed with network error 503. checkResponseAndGetData@moz-extension://b7fcfe72-d3ee-4674-9346-45c26ac1ce2f/js/HttpClient.js:31:35
wrapFetchImpl/<@moz-extension://b7fcfe72-d3ee-4674-9346-45c26ac1ce2f/js/HttpClient.js:24:20
```
----------

WebToEpub ver 0.0.0.39
Firefox 54.0.1

**Comment by dteviot** [comment]
@toshiya44 
Beldandu mentioned seeing this previously.
His suggestion was to have some Advanced Setting Options to
- How many times to retry page when a 50x series HTTP error is received.
- How long (in seconds) to wait between retries.

Any thoughts?

**Comment by dteviot** [comment]
@toshiya44, @Beldandu

I've added "Retry" and "Cancel" ability when some HTTP errors occur.  (e.g. You will get it for a 503 error, you won't get the ability if the Network isn't working.) to the Experimental Tab Branch.
I'd appreciate if you try it and let me know how it works for you.

**Comment by toshiya44** [comment]
The site in question is no longer giving the error. I'll have to find a new novel site to reproduce the error with the old version of the extension and check the changes are working as intended...

I picked a random site with cloudflare protection and got the 503 error along with the retry buttons. So I think the feature is working.

That being said, the extension is currently not working in Firefox Dev edition (56.0b10). These are probably due the ongoing change in add-on architecture. It works fine in the release version of Firefox though.

There are a number of errors in the browser console so you can check them out if you want to. Although I think you should wait a bit before trying to fix this, because the browser itself is a bit buggy right now.

**Comment by dteviot** [comment]
Thanks.
