### ISSUE TITLE
Error 403 - FlowerManga

### ISSUE THREAD

**Issue by kilandra** [dteviot/WebToEpub#1280]
**Describe the bug**
Site https://flowermanga.com/ was working fine until recently, now it's showing error 403

**To Reproduce**
1. Go to 'https://flowermanga.com/manga/a-promessa-nao-e-minha/'
2. Click on 'WebToEpub Extension'
3. Click on 'Pack EPUB'

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/99921002/666d86c9-1de2-4a9f-aa9e-5ba22cdb2a75)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 124.0.2 (64-bit)

**Additional context**
Website does not require login, all chapters are accessible without it.

**Comment by dteviot** [comment]
@kilandra 

Notes.
Site is blocking downloading the images.
Can see this, if look at chapter: https://flowermanga.com/manga/a-promessa-nao-e-minha/capitulo-01/

First image has URL of: https://cdn2.flowermanga.com/manga_656ec43e659af/827246a3c786b999ba64f8207278a5e8/00.jpg
If open a new browser and try to access the image, get rejected.
I suspect it's keying off the Sec-XXX request headers, which WebToEpub can't modify.

1. Probably isn't going to be easy to work around, and
2. Working around it is probably a violation of Googles terms for Chrome extensions.

**Comment by kilandra** [comment]
@dteviot I really forgot to try and open the images independently.
Thank you for the analysis, I'll try to find another option.

**Comment by dteviot** [comment]
@kilandra 

Closing.  Unable to assist.  Sorry, I don't know of any scrapers that might be able to handle this.  I think you'd need to drive a WebBrowser using Selenium, but I'm not sure how well that would work to obtain the images.  Might need to put a proxy in the path and extract the image files on the fly.
