### ISSUE TITLE
Remove author notes

### ISSUE THREAD

**Issue by Jwjshhi** [dteviot/WebToEpub#1281]
**Remove author note option isn't working for scribblehub website **

**Expected behavior**
Author note should've been removed after i filled the tick option of "remove author notes"

I tried it on this novel
https://www.scribblehub.com/series/124643/the-incubus-system/
I am using rmx2040(realme )
And kiwi browser with extension on Android

**Comment by Jwjshhi** [comment]
> can you post a screenshot as an example of author notes? from original site and the epub screenshot too so its much clearer

Yeah sure
Authors note
![Screenshot_2024-04-14-22-06-31-52](https://github.com/dteviot/WebToEpub/assets/113590464/8d1f9929-0554-4d23-8bd8-e65537f25bb7)
And the website novel interface
![Screenshot_2024-04-14-22-04-14-18_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dteviot/WebToEpub/assets/113590464/e82a1256-2222-4e8b-839e-3c969dd27677)
And this is the epub screenshot
![Screenshot_2024-04-14-22-10-05-88_5d76bc05ed5857511cf7820bf94979b9](https://github.com/dteviot/WebToEpub/assets/113590464/bcf72f6d-4314-4f77-ac7d-717e89dc7d45)
The author note is very big since i use tts it's very problematic for me . To add more the author adds his patreon member names in his note which makes thing even more annoying.
Thanks

**Comment by dteviot** [comment]
@Jwjshhi 

* Chapter 307. (Un)peaceful Dinner I
This isn't an Author note, it's just text at the bottom of the chapter.

The other example you give seems to be Chapter 410. "Between Father and Son II"
And again, it's just text at the bottom of the chapter.
So, not really possible to automatically remove, as I see no way to easily distinguish between this and wanted text.

For chapters with Author notes, look at: 
* Chapter 37. "Dangerous Game"
* Chapter 276. Pain?

In both cases, the text IS in an Author note, and is removed.

For my notes: 35 minutes.  (Mostly spent trying to find chapters.)

**Comment by Jwjshhi** [comment]
Thanks man for looking onto it. I totally understand.

**Comment by dteviot** [comment]
@Jwjshhi @kevin01523 

Closing.  Not able to do anything about this.
