### ISSUE TITLE
Not Grabbing the Chapter Index Page

### ISSUE THREAD

**Issue by UnknownSora** [dteviot/WebToEpub#1282]
Hey, so recently another bug has been happening where if you begin downloading the story, it’ll immediately stop and not download the page after info, the one with all the chapter names and such. The whole book is still there, and when viewing it on a epub reader, you can still see the table of contents, but the page in the book just can’t download strangely. Here’s the bug 

undefined is not an object (evaluating 'json.chapterInfo') preprocessRawDom@chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/QidianParser.js:58:46
@chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:496:40

It worked fine before. Anyways this isn’t a big deal, just wanted to let you know

**Comment by UnknownSora** [comment]
Of course, just pressing the continue button after will restart the download without it and it works fine after that

**Comment by dteviot** [comment]
@UnknownSora 

Does the missing page appear in the list of chapters to fetch when you open WebToEpub?

**Comment by dteviot** [comment]
@UnknownSora 
I'll close, as I think there's nothing for me to fix.
