### ISSUE TITLE
converter for webp 

### ISSUE THREAD

**Issue by T-Man2000** [dteviot/WebToEpub#1284]
Is it possible to include a converter for images in webp format (optional use via the advanced options) so that they can also be read by ebook readers?

**Comment by dteviot** [comment]
@T-Man2000 

Short answer:  Theoretically, it could be done.  But I'm not going to do it.

Long answer, I tried to build a webp to jpg converter, but the results were really awful.
If you hunt around, you might find a better tool for doing it.  

Although I think you'd probably need to do something like:
1. Unpack the epub into its files.  (Calibre or a zip tool)
2. Use ImageMagic https://imagemagick.org/ to convert the images as a batch.  e.g.
>convert *.webp -set filename:base "%[basename]" "%[filename:base].png"

4. Use Calibre (or similar) to re-pack the epub.
