### ISSUE TITLE
Not using the filename field to save the epub

### ISSUE THREAD

**Issue by cstrife1** [dteviot/WebToEpub#1285]
**Describe the bug**
When downloading from boxnovel.com (only site tested) it will download all chapters but save with a random file name, not the specified file name. The advanced option to use full name has no effect.

For example, it'll generate a file named like so:

d9b33806-1b0d-4257-a192-7c987e37022e.epub

This is randomized as multiple saves of the same novel will generate a different filename.

**To Reproduce**
Can run from any novel on boxnovel

https://boxnovel.com/novel/the-human-emperor/

**Expected behavior**
It is saved using the Filename field.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11 x64
Chrome Version 123.0.6312.124 (Official Build) (64-bit)

**Comment by cstrife1** [comment]
I realized later all downloads were getting a bad name, so it's not the extension.

**Comment by dteviot** [comment]
@cstrife1 

Seen similar reports in the past.  It's probably one of the other extensions you have loaded.
