### ISSUE TITLE
Content detection bug

### ISSUE THREAD

**Issue by Infel1** [dteviot/WebToEpub#1288]
Well the problem here is that when I use Webtoepub on some online pages it detects "chapters" that are not: other things that are not chapters
![Captura de pantalla_22-4-2024_17389_akiljllkbielkidmammnifcnibaigelm](https://github.com/dteviot/WebToEpub/assets/36248950/1bc6e2a0-3791-4cf5-8785-c5ac3dcafe08)
I tried to use the default parser with the CSS selector and what happened was this other error
![Captura de pantalla_22-4-2024_17418_akiljllkbielkidmammnifcnibaigelm](https://github.com/dteviot/WebToEpub/assets/36248950/d7f7dda9-5b7e-4a52-8f0f-a3e7b7f30779)
And yes, I had Javascript activated

![image](https://github.com/dteviot/WebToEpub/assets/36248950/4456d5dc-80a0-4a5e-a010-dc1b4efb067c) This is the second image cropped

**Comment by dteviot** [comment]
@Infel1 

The problem with this site is WebToEpub thinks this site has different story layouts.
Most of the stories are like https://tunovelaligera.com/novelas/un-reemplazo-para-el-diablo/, which WebToEpub can handle without a problem.
However, https://tunovelaligera.com/novelas/xian-ni-tnl/?lcp_page0=1, and WebToEpub tries to handle it thinking it's like the other story, well, it doesn't work.  The chapter links are not where it expects them.  So, you're getting whatever links it found.

Note, WebToEpub is pretty stupid.  To handle the site, I'd need to write a new parser.

So, If you'd like a parser for that site, please request one and I'll put the request in the queue.  If you're asking for a change to WbeToEpub to make it smarter, you're out of luck.  I don't have the time or inclination for the work required.
