### ISSUE TITLE
Please add site https://readfreebooksonline.org

### ISSUE THREAD

**Issue by JoshOm21** [dteviot/WebToEpub#1289]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://readfreebooksonline.org/books/corrupted-chaos-an-enemies-to-lovers-forced-proximity-romance-tarnished-empire/

### Did you try using the Default Parser for the site?  If not, why not? Yes
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@JoshOm21 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://readfreebooksonline.org/books/a-game-of-hearts-and-heists-a-steamy-lesbian-fantasy-romance-girl-games-book-1/, chapter 1

For my notes: 9 minutes work.  This was an easy one.  Same layout as https://noblemtl.com/

**Comment by JoshOm21** [comment]
![IMG_20240424_231452](https://github.com/dteviot/WebToEpub/assets/93379319/b2c2373f-beb1-41cd-8b4d-fef902d5fe08)

What to do? No chapters

**Comment by dteviot** [comment]
@JoshOm21 

Is the URL https://readfreebooksonline.org/books/a-deal-with-the-devil-a-grumpy-boss-romance-the-grumpy-devils-book-1/?
It's working for me.
My best guess, something went wrong with trying to load the test version of WebToEpub.

**Comment by dteviot** [comment]
@JoshOm21 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
