### ISSUE TITLE
Kemono ignores embedded images

### ISSUE THREAD

**Issue by T-Man2000** [dteviot/WebToEpub#1290]
Kemono ignores embedded images. Have there been any changes to the website or the extension?

Example: kemono.su/patxxxx/user/7423653/post/92943946

**Comment by dteviot** [comment]
@T-Man2000 
That link doesn't seem to work.
Records show, significant changes made around 20th January.  But nothing since.

**Comment by T-Man2000** [comment]
The correct link is [kemono.su/patreon/user/7423653/post/92943946 ](https://kemono.su/patreon/user/7423653/post/92943946)

**Comment by dteviot** [comment]
@T-Man2000 

Interesting.  It's an attachment, not part of the post__content.  Try this.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kemono.su/patreon/user/7423653, post 92943946

For my notes: 26 minutes work

**Comment by T-Man2000** [comment]
It works. The image is added to the epub file. Thank you very much.

**Comment by dteviot** [comment]
@T-Man2000 
Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
