### ISSUE TITLE
Patreon site update

### ISSUE THREAD

**Issue by PolarisFx** [dteviot/WebToEpub#1293]
**Describe the bug**
Patreon updated their content section yesterday. W2E now fails with:

Could not find content element for web page
 
I've had others attempt to create epubs from patreon with similar results.

**Comment by dteviot** [comment]
@PolarisFx 

Yes, site has changed it's layout again.
Not fun, had to completely re-write the parser.
Notes:
1. You need to manually expand the list of posts/chapters before you open WebToEpub.  WebToEpub can't walk list of chapters without a LOT more work than I'm willing to do.
2. I can't tell if it correctly finds links for paid posts you have access to.  I've only tested with an author which has some public posts.  But links to public posts are available in ToC.  Links you don't have access to are not.
3. Likewise, I can't tell if it will correctly fetch paid posts you have access to.  (Probably will, as site is unlikely to give those a different format.
4. I can't say if images will be downloaded correctly.  Public posts I know of don't have images.  (My best guess is probably not, as content is JSON.  Images will probably be in a different member.)  Would need a HAR file, or link to publicly accessible page with images.  (Idea: create author account and post some stuff.)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.patreon.com/ddwebb

For my notes: 133 minutes work

**Comment by PolarisFx** [comment]
Beautiful, as for point 4 I think you making a Patreon for donations to the project would be a good way to get you access to a paid tier page. Honestly this addons continued existence is worth a monthly fee to me.

**Comment by PolarisFx** [comment]
Well... it can't find chapters, even if expanded. 
![Web2epub-original](https://github.com/dteviot/WebToEpub/assets/12600197/6acbd3c8-d043-4099-893b-339b2bdb6efc)

if I edit urls and create the chapters manually it works. But doesn't search chapters. 
![Web2epub-editurl](https://github.com/dteviot/WebToEpub/assets/12600197/cda715e2-816b-450a-b8c3-aa5a89f7ae6b)

**Comment by dteviot** [comment]
@PolarisFx 
I'm guessing this is a site with content you've paid for.  Post the HTML for the ToC page, and I'll see how it differs from what I've looked at.

**Comment by PolarisFx** [comment]
[toc-unmin.txt](https://github.com/dteviot/WebToEpub/files/15130793/toc-unmin.txt)

**Comment by dteviot** [comment]
@PolarisFx 

Try latest.  Should be fixed for HolyMouse.  Note, obviously, I'm unable to fully test.  But I'm 90% confident it will work.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.patreon.com/ddwebb
* https://www.patreon.com/HolyMouse  (sort of.  More like, examined supplied HTML, and compared with ddwebb).

For my notes: 26 (additional) minutes work.  (149 total)

**Comment by chrisdcarpenter** [comment]
The issue has been resolved for content creator TheFirstDefier. Wanted to provide feedback that the fix worked beyond HolyMouse.

**Comment by PolarisFx** [comment]
Weird that it works for Chris on the DoTF page, it doesn't work for me at all, so I had some of my friends install the latest version and it doesn't work for them either on the stories they're subbed to. It will grab the chapter if you create the chapter entries using edit chapters but it's unable to find chapters.

**Comment by dteviot** [comment]
@PolarisFx 


Did it work for HolyMouse?

Note, I found another author with some public chapters.  https://www.patreon.com/catvi. Seemes to work fine there.

**Comment by PolarisFx** [comment]
@dteviot 

Sorry, I had to format and it took me some time to get back into things. Using the latest version provided on the GDrive did not work for me. However, it appears that the store version 0.158 is working again. Both for finding chapters and creating epubs.  

So whatever Patreon changed, they must have changed back.

**Comment by dteviot** [comment]
@PolarisFx 

Based on your description that version 0.0.0.158 is working, I've had another go at trying to fix W2E for Patreon.
Can I get you to give the new test version another try?

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.

Thanks in advance.

**Comment by PolarisFx** [comment]
@dteviot 

Tried the latest version, and it worked successfully on all my subs. All chapters detected. Thanks for the hard work.
