### ISSUE TITLE
https://arcanetranslations.com

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#1294]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://arcanetranslations.com/series/i-reincarnated-into-a-game-filled-with-mods/

### Did you try using the Default Parser for the site?  If not, why not?

Default Parser won't load, it jumps straight into whatever template WTE already has but the chapter URLs aren't snatched.

### What settings did you use?  What didn't work?
* URL of first chapter
* https://arcanetranslations.com/%ef%bd%a1-%e2%9c%a7-chapter-0-%e2%9c%a7-%ef%bd%a1-3/

* CSS selector for element holding content to put into EPUB
.epcontent

* CSS selector for element holding Title of Chapter
.entry-title

* CSS selector for element(s) to remove

**Comment by dteviot** [comment]
@Tenome 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://arcanetranslations.com/series/i-reincarnated-into-a-game-filled-with-mods/, chapters 1 &amp; 2

For my notes: 12 minutes work. This was an easy one. Same layout as https://pandamtl.com/

**Comment by dteviot** [comment]
@Tenome 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
