### ISSUE TITLE
Please add site --> https://crimsontranslations.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1297]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://crimsontranslations.com/7-i-made-the-horror-game-boss-fall-for-me**

### Did you try using the Default Parser for the site?  If not, why not?
Yes, I did, but I no CSS Selector worked at all no matter what input I entered because I couldn't use the "Test" function since the same error kept showing up: **You need to enable Javascript to run this app.**

I'm not sure if this site is parsable because I recall encountering this issue before with another site when I tried to use the Default Parser (from issue #1266) but was hoping to see if there was a possible workaround to this new issue because the layout for this source doesn't seem as complex :D Thank you for your time and efforts~

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.crimsontranslations.com/8-slaying-immortal, chapter 1

For my notes: 30 minutes work

**Comment by plsbenice-immadeofjelly** [comment]
Thank you very much!! :) Although it did indeed work to pull in all the chapter content, there's a slight error, which I hope is not too troublesome. For some reason, the entire body content is only wrapped in **one** singular paragraph element, whereas on the novel's source itself, each paragraph was seen to be separated via two break tags. May I ask if this fix is able to be incorporated into the parser of this site? But, regardless, thank you very much for your help! :D

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Apologies.  This site does not include the content text in the HTML.  Instead a REST call is needed, and I have to construct the HTML from the JSON.  In this case, some of the chapters have slightly different formatting, so the JSON to HTML conversion doesn't quite work.  I believe I have it fixed now.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.crimsontranslations.com/5-sea-salt-mint-and-freesia, chapter 1

For my notes: 45 minutes work (running total)

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Yes, that error message is computer speak for site has changed it's layout.  
More specifically, site has changed the JSON schema of the REST call used to return chapter content.  But that distinction is probably means nothing to you.

Anyway, I'll look into it shortly.

Also, in future, please raise a new issue for something like this, rather than add comments to an existing closed one.  It makes it easier for me to track things.  (I've made an exception in this case.)

**Comment by plsbenice-immadeofjelly** [comment]
Thank you for looking into this error :) I'm sorry for adding on the inconvenience, I'll be sure to open a different issue, should a problem with an existing source crop up. But, thank you for making an exception~

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

>  I'm sorry for adding on the inconvenience,
No problem.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.crimsontranslations.com/7-i-made-the-horror-game-boss-fall-for-me, chapter 1

For my notes: 8 minutes work

**Comment by dteviot** [comment]
Reopen.  I need to tell you when version in store is updated.

**Comment by plsbenice-immadeofjelly** [comment]
Thank you!!!! It works again!!! :D

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
