### ISSUE TITLE
Please add site https://m.qqxs.vip

### ISSUE THREAD

**Issue by TheFirstProgenitor** [dteviot/WebToEpub#1299]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://m.qqxs.vip/125_125756/all_30.html
### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Tried-fetches 20 at a time 
### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove
Similar to 38xs.
'www.38xs.com' is now 'm.38xs.com' so it doesn't work unless url 8s input with 'm' changed to 'www'.
### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
Not really.

**Comment by dteviot** [comment]
@TheFirstProgenitor 

Please note, the URL you supplied is NOT the correct link to start from.  It should be https://m.qqxs.vip/125_125756/, to allow fetching cover image and summary.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://m.qqxs.vip/356_356047/ chapter 1
* https://m.qqxs.vip/125_125756/ chatper 1

For my notes: 132 minutes work

**Comment by dteviot** [comment]
@TheFirstProgenitor 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
