### ISSUE TITLE
Failure to fetch image stops fetch of rest of images

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#13]
(Note for me.)
Sometimes the attempt to get the high resolution version of an image fails.  (e.g. WayBackMachine did not preserve the file.)
In this case, the HTTP exception that is thrown aborts the "fetch all images" operation.

Need an option to say "fetch rest of images on image failure".  In which case, use the thumbnail image on the original page and try fetching the rest of the images.

**Comment by belldandu** [comment]
Noticed this too. Depending on the error it should wait a few seconds and try to refetch the image (like when it says service unavailable)

**Comment by dteviot** [comment]
See also https://github.com/dteviot/WebToEpub/issues/27, at minimum, need to return more useful error message when there is a network failure.

**Comment by dteviot** [comment]
I believe this is fixed by https://github.com/dteviot/WebToEpub/issues/128
