### ISSUE TITLE
Please add site https://topnovelfull.com/

### ISSUE THREAD

**Issue by swanknight** [dteviot/WebToEpub#1307]
This is basically a mirror of https://novelfull.com/ now they redirect to the new domain automatically. But nothing else has changed as far as I could tell, so I assume the existing https://novelfull.com/ parser should work for the new domain.

**Comment by dteviot** [comment]
@swanknight 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* Untested.  (I trust ImLJS)

**Comment by swanknight** [comment]
@dteviot 

Just tested on Firefox, and it's working as intended. Thanks.

**Comment by dteviot** [comment]
@swanknight @ImLJS 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
