### ISSUE TITLE
Questionablequesting.com updated their Site

### ISSUE THREAD

**Issue by Maxlemore97** [dteviot/WebToEpub#1309]
**Describe the bug**
Questionablequesting.com updated their Site and now the extension isn't working anymore

**To Reproduce**
1. Go to Questionablequesting.com
2. Open Threadmark
3. Try to download

**Expected behavior**
That it indexes the chapters and then downloads the whole thing as eBook

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Comment by Kiradien** [comment]
A fix for this has been uploaded but is not yet in the live build; You can get it early by downloading the ExperimentalTabMode branch and following the **How to install from Source** instructions in the readme.
Epub generation follows the steps used on SpaceBattles/SufficientVelocity with the new update.

**Comment by dteviot** [comment]
@Maxlemore97 
To expand slightly on @Kiradien's comment with links

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by Maxlemore97** [comment]
Thanks a lot guys!!

**Comment by dteviot** [comment]
@Maxlemore97 @Kiradien 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
