### ISSUE TITLE
https://www.lightnovelworld.co/

### ISSUE THREAD

**Issue by MasterSunless** [dteviot/WebToEpub#1313]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@MasterSunless 

Why are you asking for this?
To the best of my knowledge, this is already supported.
I've just done a quick test of https://www.lightnovelworld.co/novel/greatest-legacy-of-the-magus-universe, chapter 1, and as far as I can tell it's working.
Git history says support was added in 2024-02-23, so it's available in the latest version (0.0.0.158).

**Comment by dteviot** [comment]
Closing.  No response.
