### ISSUE TITLE
Unwanted elements being included in Scribble Hub stories.

### ISSUE THREAD

**Issue by nozwock** [dteviot/WebToEpub#1314]
Tested on some random story with `Remove Author Notes` turned on, https://www.scribblehub.com/series/1029428/chronicles-of-the-amber-dragon/

The first and last page of the EPUB end up including the link for previous and next page respectively.
```html
<div class="nav_chp_fi" dpmb="yes">
    <div class="prenext"><a title="Shortcut: [Ctrl] + [&lt;-]" href="#" class="btn-wi btn-prev disabled"
            dpmb="yes">Previous</a></div>
</div>

<div class="nav_chp_fi" dpmb="yes">
    <div class="prenext"><a title="Shortcut: [Ctrl] + [-&gt;]" href="#" class="btn-wi btn-next disabled"
            dpmb="yes">Next</a></div>
</div>
```

And every page has the favorite count included at the bottom.
![](https://github.com/dteviot/WebToEpub/assets/57829219/7a9ae276-8ac4-4cdd-b937-f1c0e6fd89c8)
```html
<div style="height: 35px; text-align:center;">
    <div class="ta_c_bm" dpmb="yes">
        <span class="chp_stats_feature" title="Favorite This Chapter" dpmb="yes">
            <i dpmb="yes" class="fa fa-heart chp" aria-hidden="true"></i>
            <span id="heart_cnt btm" dpmb="yes">27</span>
        </span>

        <span class="bm_chp_e"></span>
    </div>
</div>
```

Version: `0.0.0.158`

**Comment by Kiradien** [comment]
I can confirm these have long been included in scribblehub epubs; I've always subconsciously ignored them.

A really easy fix is available by swapping the findContent selector to `"div#chp_raw"` instead of `"div#chp_contents"` - I just confirmed it does include the author note section as well. I should have a pull request up in a few.

**Comment by dteviot** [comment]
@nozwock @Kiradien 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
