### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by you-sunshine** [dteviot/WebToEpub#1316]
After running npm run build，Will report an error

<img width="1017" alt="image" src="https://github.com/dteviot/WebToEpub/assets/54009155/e8dc06b8-3140-4c02-b274-2f837637bbed">

**Comment by dteviot** [comment]
@you-sunshine 

Error suggests you're checking out in unix mode.  But eslint is expecting the lines to be Windows style.
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style

**Comment by nozwock** [comment]
@you-sunshine

This will work as a temporary workaround.

```diff
@@ -19,7 +19,7 @@
     "up": "npm add jszip@latest && npm install",
     "postinstall": "copyfiles -V -u 1 node_modules/jszip/dist/jszip.min.js plugin",
     "test": "http-server -o unitTest/Tests.html",
-    "lint": "cd eslint && node pack.js && eslint packed.js",
+    "lint": "cd eslint && node pack.js && eslint --fix packed.js",
     "build": "cd eslint && node pack.js",
     "release": "node eslint/release.js"
   },
```

**Comment by gamebeaker** [comment]
abandoned from issue creater.
