### ISSUE TITLE
[RoyalRoad] Small issue with chapter titles

### ISSUE THREAD

**Issue by guiverunit** [dteviot/WebToEpub#132]
The chapter title at the beginning of each chapter shows the book title not the chapter title as it should.

In the parser `<h2>` is used to get the chapter title when it should be `<h1>` ( in findChapterTitle)

**Comment by dteviot** [comment]
Thank you.
Fixed.  
https://github.com/dteviot/WebToEpub/commit/d95f470fdfd5dabd91a689278b0f0f9b7178c7c8
Note, may be a few days before version in Chrome store is updated.

**Comment by dteviot** [comment]
Version 0.0.0.39 (which has fix) has been submitted to the Google WebStore.  Your version should update automatically.
