### ISSUE TITLE
https://phoenixwalktranslations.com parser

### ISSUE THREAD

**Issue by SkyMoon-2020** [dteviot/WebToEpub#1320]
I've tried everything within my limited scope of knowledge (I'm not from a tech background), but nothing is working for this site. Right-clicking doesn't work on this page, so inspecting individual pages' dev tools isn't an option either. Adding the CSS part for the parser didn't work too. After checking everything, I'm finally requesting help. Can anyone help me create a parser for this site or suggest what I can do to make it work? It would be really helpful.

This is this the site: https://phoenixwalktranslations.com

Thanks in advance.

**Comment by dteviot** [comment]
@SkyMoon-2020 

If right-clicking doesn't work.  You can inspect by:
1. Click on the three vertical dots on the top right corner of Chrome
2. Select "More Tools" > "Developer Tools"
3. Click on elements tab on the window that appears.

That said, try the following in the default parser:
1. ".cm-entry-summary" for "CSS Selector for the content". Don't include quotes, do include the full stop
2. Leave rest blank.

If this doesn't work, put writing parser for this site to my task list.

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020
> 
> If right-clicking doesn't work. You can inspect by:
> 
> 1. Click on the three vertical dots on the top right corner of Chrome
> 2. Select "More Tools" > "Developer Tools"
> 3. Click on elements tab on the window that appears.
> 
> That said, try the following in the default parser:
> 
> 1. ".cm-entry-summary" for "CSS Selector for the content". Don't include quotes, do include the full stop
> 2. Leave rest blank.
> 
> If this doesn't work, update this incident and I'll put writing parser for this site to my task list.


>>> Hello !! I tried it and it worked for me. thank you so much for the help.
