### ISSUE TITLE
Please add site https://www.webnovelpub.pro/

### ISSUE THREAD

**Issue by emrys90** [dteviot/WebToEpub#1324]
When I attempted to add the site, I filled out the settings for body/chapter selectors, but then I receive a 403 access denied error. Not sure how to resolve it. I refresh the website and there isn't any login or captcha requirements.

The story I am trying to download is:
https://www.webnovelpub.pro/novel/supreme-magus-webnovel-05122224/chapters

**Comment by dteviot** [comment]
@emrys90 

Site seems to be an alias for https://www.lightnovelworld.co.  e.g. See https://www.lightnovelworld.co/novel/supreme-magus-webnovel-05122224.  And that site is already handled by WebToEpub.

Anyway, easy to update WebToEpub to handle this.  So, your other option is:

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.webnovelpub.pro/novel/greatest-legacy-of-the-magus-universe, chapter 1

For my notes: 9 minutes work

**Comment by emrys90** [comment]
Thanks for the quick answer! While I do see that lightnovelworld.co has support, I'm getting the same captcha error. Any ideas?
![image](https://github.com/dteviot/WebToEpub/assets/20632855/a6c9ca00-bd01-4ffb-a15d-ddf527321a5b)

**Comment by gamebeaker** [comment]
@emrys90 probably related to #1306.

**Comment by dteviot** [comment]
@emrys90 

Test build has fix for #1306, so your options are:
1. Use the test build
2. Wait until I update version in stores.
