### ISSUE TITLE
Fannovels.org shows error on use

### ISSUE THREAD

**Issue by 1k-7** [dteviot/WebToEpub#1326]
**Describe the bug**
403 error 
WAANING: Site 'www.fannovels.org' has sent an Access Denied (403) error. You may need to logon or satisy a CAPTCHA before WebToEpub can continue,
**To Reproduce**
1. Go to 'https://www.fannovels.org/novel/hogwarts-dont-you-all-have-the-eye-of-god.html'
2. Click on 'WebToEpub'
3. Wait...

**Expected behavior**
Work as usual

**Screenshots**
Shouldn't be needed as exact error text provided 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Samsung A73 5G]
 - OS: [One UI 6.1]
 - Browser [Kiwi]
 - Version [124.0.6327.2]

**Additional context**

**Comment by 1k-7** [comment]
Same problem with others that use readwnparser

**Comment by Kiradien** [comment]
Are you using the Chrome version of WebToEpub? Or Firefox or some other browser?
Are you using version 0.0.0.159 of WebToEpub? (Right click on the extension and manage extension to see the version)
If not, I suggest updating and trying again.


Originally when I saw this bug I thought it would be connected to the FFNet Cloudflare 403 issue, but was not able to replicate it. It might still be the same issue due to some localized issues - It can't hurt to try: [Link to that fix here](https://github.com/dteviot/WebToEpub/issues/1306#issuecomment-2124462658).

I hope one of those options works... If not, providing answers to the other details asked above might help in replication.

**Comment by 1k-7** [comment]
Used 0.0.0.159 from abt a few weeks ago.
Updated from drive now.
Result : no 403 error
Instead
![Screenshot_20240524_214103_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/169595478/ef971ddb-c1a4-49a2-a01c-4c3ac97aac6f)

TypeError: Error in invocation of cookies.getAll(object details, function callback): Error at parameter 'details': Unexpected property: 'partitionKey'.
    at HttpClient.setPartitionCookies (chrome-extension://mncobnhifkahpfkfboiblehgplpaaecm/js/HttpClient.js:209:48)
    at async HttpClient.wrapFetchImpl (chrome-extension://mncobnhifkahpfkfboiblehgplpaaecm/js/HttpClient.js:172:9)
    at async ReadwnParser.getChaptersFromAllTocPages (chrome-extension://mncobnhifkahpfkfboiblehgplpaaecm/js/Parser.js:672:27)
    at async ReadwnParser.getChapterUrlsFromMultipleTocPages (chrome-extension://mncobnhifkahpfkfboiblehgplpaaecm/js/Parser.js:658:16)

I used with Warp+ and without any vpn. Still nothing.
Shosetsu works tho.

**Comment by 1k-7** [comment]
Issue persists when on kiwi in work profile (fresh app).

**Comment by dteviot** [comment]
@1k-7 @gamebeaker 

I think I can explain this error.
> TypeError: Error in invocation of cookies.getAll(object details, function callback): Error at parameter 'details': Unexpected property: 'partitionKey'.
at HttpClient.setPartitionCookies (chrome-extension://mncobnhifkahpfkfboiblehgplpaaecm/js/HttpClient.js:209:48)

Matching code is:
https://github.com/dteviot/WebToEpub/blob/e00323a6cf4d6569258dc2ebc6590e6745485fd3/plugin/js/HttpClient.js#L209

So, error is saying "This browser (Kiwi) does not know what to do with the "partitionKey" value it's been given".
You may need to update to a version of the browser that supports cookie partitionKeys.  Note, I see you're using a very recent version, so I'd doubt the very latest has added partitionKeys support.  You could ask the developers.  And/Or raise a support issue.
Another option, the latest version of WebToEpub on the Mozilla store supports the Android (mobile) version of Firefox.   And Firefox doesn't have issues with partition keys.

**Comment by gamebeaker** [comment]
For Information it looks like kiwi is based on chromium version 105 it needs to be version 119 to work right. ([https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll)) 
I am surprised that @1k-7 was able to install the extension as in [manifest.json](https://github.com/dteviot/WebToEpub/blob/ExperimentalTabMode/plugin/manifest.json) "minimum_chrome_version": "119" is specified.
@dteviot i think there are going to be new issues in github if WebToEpub is no longer compatible with kiwi browser. I tested the WebToEpub version 0.0.0.159 on Firefox for Android and it looks like it is working.

**Comment by dteviot** [comment]
@gamebeaker 

I'm thinking, as a short term fix, could wrap the getAll in a try/catch.  Not ideal, as the partitionKeys still isn't going to work for Kiwi, so cloudflare may be a problem.  But it will be usable otherwise.

**Comment by 1k-7** [comment]
I tried Firefox nightly begore raising the issue and it worked pretty well.
Kiwi doesn't and i mostly use kiwi, which is exactly why i raised the issue.

**Comment by gamebeaker** [comment]
@dteviot if try catch is implemented i would add to the 403 error message something like: if you are using Kiwi try using an other browser.
until it is fixed in Kiwi.

**Comment by dteviot** [comment]
@1k-7 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
