### ISSUE TITLE
failed on downloading a specific chapter's content on asianfanfics.com

### ISSUE THREAD

**Issue by seravi3116** [dteviot/WebToEpub#1327]
**Describe the bug**
although webtoepub does managed to download it with no error messages whatsoever, but when i open the said file it shows nothing except the link url and the chapter title

**To Reproduce**
1. Go to a specific chapter (ex. https://www.asianfanfics.com/story/view/1553634/7/chapter-7 or https://www.asianfanfics.com/story/view/1482484/13/not-so-sinful-2 or https://www.asianfanfics.com/story/view/1482484/32/bust-or-bust-2)
2. Click on WebToEpub via the browser extensions and download via 'Pack EPUB' (i don't change anything on the settings at all except to check 'skip images' box because i don't really need them)
3. Open the downloaded file

**Expected behavior**
work as intended, download the chapter with it's contents

**Screenshots**

for "https://www.asianfanfics.com/story/view/1553634/7/chapter-7"
![01](https://github.com/dteviot/WebToEpub/assets/170742088/601c8e75-f089-40fb-a5ca-596f262ba341)
![02](https://github.com/dteviot/WebToEpub/assets/170742088/f1eafd93-ba36-4829-b24c-e576969efb6c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Brave
 - Version: 125.0.6422.113 (Chrome) 1.66.113 (Brave)

**Additional context**
as provided on the screenshots, this bug happens on multiple stories and chapters. i also tried downloading with the 'skip images' box unchecked but sadly it still didn't work. hope this gets fixed and thanks in advance OP!

**Comment by dteviot** [comment]
Notes/Questions:

When I went to https://www.asianfanfics.com/story/view/1482484/13/not-so-sinful-2, I needed to click a "Are you over 18?" button. After that, I note that page requires subscribing to obtain full text of chapter.  I'm going to assume you did this.
Also of note.  Content is NOT on the initial page.  Instead need to get content from GET call to REST URL https://www.asianfanfics.com/chapter/api/5253493/chapter_039be7047f6ffdfdf0d97f4456052ef7.json.  This URL can be obtained from this element in original document.

```HTML
<script>var postApi = "/chapter/api/5253493/chapter_039be7047f6ffdfdf0d97f4456052ef7.json";</script>
```

To investigate, do all chapters require this?

Time elapsed: 19 minutes

**Comment by dteviot** [comment]
@seravi3116 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.asianfanfics.com/story/view/1482484/lab-results, chapters 1 and 13

For my notes: 53 minutes work

**Comment by dteviot** [comment]
@seravi3116 

Spoke to soon.  Looked at chapter 30.  Looks like the JSON request might fail, in which case, need to add "?v=1" to request.
Updated.

Revised test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. 

For my notes: 90 minutes work.  (Total)

**Comment by seravi3116** [comment]
> @seravi3116
> 
> Spoke to soon. Looked at chapter 30. Looks like the JSON request might fail, in which case, need to add "?v=1" to request. Updated.
> 
> Revised test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.
> 
> For my notes: 90 minutes work. (Total)

hello. i downloaded the "WebToEpub0.0.0.160.Chrome" version and while it did managed to work fine downloading "https://www.asianfanfics.com/story/view/1553634/7/chapter-7" and "https://www.asianfanfics.com/story/view/1482484/13/not-so-sinful-2" perfectly, sadly for others it still doesn't work. although there is a minor thing that happened in that an "undefined" text is now visible on the epub files that aren't downloaded properly. additionally, the revised test version also managed to fix other chapters that i didn't included on my initial post, i'll include them on this just for your reference ("https://www.asianfanfics.com/story/view/1499678/10/miss-athletic-boa", "https://www.asianfanfics.com/story/view/1435918/36/beach", "https://www.asianfanfics.com/story/view/1420454/12/dangerous-jessica")

added some new examples of broken downloads

"https://www.asianfanfics.com/story/view/1482484/32/bust-or-bust-2" also chapters 32 and 34 of this story
![01](https://github.com/dteviot/WebToEpub/assets/170742088/ec3bc3b5-01c7-41c0-903d-f2b6a861ce2e)

"https://www.asianfanfics.com/story/view/1561603/5/just-the-beginning-ft-t"
![02](https://github.com/dteviot/WebToEpub/assets/170742088/545db36d-8810-45dc-8738-4493e593cdf1)

"https://www.asianfanfics.com/story/view/1516544/11/one-night-stand"
![04](https://github.com/dteviot/WebToEpub/assets/170742088/9aca4987-7416-4a1b-84f0-6052940e5295)

"https://www.asianfanfics.com/story/view/1493029/6/day-6-face-sitting-face"
![05](https://github.com/dteviot/WebToEpub/assets/170742088/33daa333-6ef4-46af-baff-ea4d31cd1de0)

**Comment by dteviot** [comment]
@seravi3116 
Running with Desktop Chrome.

* https://www.asianfanfics.com/story/view/1482484/32/bust-or-bust-2, fails.  
When I try to open the page normally in browser, I get page that shows "Please [Subscribe] to read the full chapter".
I think you might be running into this.  Note, you might also need to flush the browser's cache.  i.e. Steps.
1. Flush cache
2. Subscribe
3. Check you can access page in browser normally.
4. Run WebToEpub.

* https://www.asianfanfics.com/story/view/1561603/5/.  Works, although I did open it with browser beforehand.  (Also didn't need the ?v=1 filename
* https://www.asianfanfics.com/story/view/1516544/11/. Fails. When I try to open the page normally in browser, I get page that shows "Please [Subscribe] to read the full chapter".
* https://www.asianfanfics.com/story/view/1493029/6/day-6-face-sitting-face, Fails, When I try to open the page normally in browser, there is no text.

**Comment by seravi3116** [comment]
@dteviot 
hello. i'm subscribed to those stories so i don't think that's a problem. also for some reason, without changing and trying anything new, i tried to download them again and these chapters got fixed and downloaded properly: 

https://www.asianfanfics.com/story/view/1482484/32
https://www.asianfanfics.com/story/view/1561603/5
https://www.asianfanfics.com/story/view/1516544/11
https://www.asianfanfics.com/story/view/1493029/6

these chapters remains broken:

https://www.asianfanfics.com/story/view/1482484/34
https://www.asianfanfics.com/story/view/1482484/36

and this chapter broke again even though it got fixed from the revised test version that you first provided (so it was originally broken, then got fixed when i tried downloading it with the revised test version, then broke again):

https://www.asianfanfics.com/story/view/1482484/13

**Comment by seravi3116** [comment]
> * https://www.asianfanfics.com/story/view/1493029/6/day-6-face-sitting-face, Fails, When I try to open the page normally in browser, there is no text.

i'm sorry for the late reply, but i think this is the problem that we're both having, albeit we experienced it on different chapters for some reason...so i think this issue could be considered fixed now? since it seems to be the problem of the website instead of the extension. thanks for answering OP!
