### ISSUE TITLE
https://novelplex.org

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#1328]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelplex.org/novel/15/

### Did you try using the Default Parser for the site?  If not, why not?
I parsed it just fine, I'm just submitting this so you can easily add it (please).

### What settings did you use?  What didn't work?
* URL of first chapter
[ https://novelplex.org/novel/15/](https://novelplex.org/novel/15/1022)
* CSS selector for element holding content to put into EPUB
.halChap--wrap
* CSS selector for element holding Title of Chapter
.hCJud--head
* CSS selector for element(s) to remove
.headBackbut, .halChap--donateA, .halChap--futer, pt_aBody, pt_aButton

**Comment by dteviot** [comment]
@Tenome 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://novelplex.org/novel/15/, chapters 1, 82, 184

Note, I don't know if you'll get the full text of chapters that you've paid "cookies" for.

For my notes: 50 minutes work  (Got distracted reading the story.  Then browsing the site.)  So, really, about 25 minutes

**Comment by dteviot** [comment]
@Tenome 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
