### ISSUE TITLE
Please add site https://booktoki339.com/novel/5919

### ISSUE THREAD

**Issue by sonakshi613** [dteviot/WebToEpub#1330]
### URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://booktoki339.com/novel/5919?stx=0살부터+슈퍼스타

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
On trying to use it showed the following as a pop-up:
WARNING: Site 'booktoki339.com' has sent an Access Denied (403) error.  You may need to logon or satisy a CAPTCHA before WebToEpub can continue.

Then on ok, it showed the following error:
Error: Error: Fetch of URL 'https://booktoki339.com/novel/2805537?stx=%ED%95%99%EC%82%AC%EC%9E%AC%EC%83%9D&book=%EC%99%84%EA%B2%B0%EC%86%8C%EC%84%A4&spage=1' failed with network error 403. This is an intermittent error. If you retry in a few minutes, it may succeed.
    at FetchErrorHandler.promptUserForRetry (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:55:19)
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:48:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:188:45)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:182:31
    at async Booktoki152Parser.fetchChapter (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:540:17)
    at async Promise.all (index 0)
    at async Booktoki152Parser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:470:17)

### What settings did you use?  What didn't work?
I tried to find CSS selector in inspect elements, but I'm not sure it is correct
* URL of first chapter - https://booktoki339.com/novel/46062?book=일반소설
* CSS selector for element holding content to put into EPUB - 
* CSS selector for element holding Title of Chapter - 

on trying the same it still showed the following error - 
WARNING: Site 'booktoki339.com' has sent an Access Denied (403) error.  You may need to logon or satisy a CAPTCHA before WebToEpub can continue.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I dont have any developer friends

I appreciate your time and effort. Thanks :)

**Comment by Kiradien** [comment]
Can confirm that I can replicate this bug, however the FFNet fix resolves it. Downloading and installing the patch noted in this https://github.com/dteviot/WebToEpub/issues/1323#issuecomment-2126776646 should resolve your issues.

**Comment by sonakshi613** [comment]
I was able to ddl. Thank you so much!

**Comment by sonakshi613** [comment]
I was able to ddl. Thank you so much!

**Comment by dteviot** [comment]
@sonakshi613 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

**Comment by GuPuSi7ff** [comment]
Had a similar experience before, seems to be site-side related.
https://booktoki.site/

**Comment by dteviot** [comment]
@GuPuSi7ff 

This is a old, closed issue.  Generally, not much point adding comments to it.  Better to raise a new issue.
That said https://booktoki.site/ seems to just be a pointer to the current address of booktoki.
