### ISSUE TITLE
https://gravitytales.com/ . problem at making epub

### ISSUE THREAD

**Issue by H4n4n** [dteviot/WebToEpub#1333]
**Describe the bug**
while using the the extension for the page works and shows the presence of chapters
![image](https://github.com/dteviot/WebToEpub/assets/131601319/b635d460-8a7a-4232-a617-feb957b7d705)

at the moment of cliciking "pack epub" it just makes a file without any chapters in it and then show the following message

![image](https://github.com/dteviot/WebToEpub/assets/131601319/1e9a7cac-7dd1-43a4-b667-63ffe4b8dfbb)

**To Reproduce**
1. Go to 'https://gravitytales.com/index.php/category/xianxia/kmmt/'
2. Click on 'pack epub'

**Expected behavior**
the epub file being downloaded with the chapters in it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version : chrome Versión 125.0.6422.113 (Build oficial) (64 bits)

**Comment by dteviot** [comment]
@H4n4n 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://gravitytales.com/index.php/category/xianxia/kmmt/, chapter 1
* https://gravitytales.com/index.php/category/xianxia/martial-sister/, chapters 0, 1

For my notes: 34 minutes work

**Comment by H4n4n** [comment]
Just tried it with https://gravitytales.com/index.php/category/xianxia/kmmt/ and it works fine. Thanks you very much

**Comment by dteviot** [comment]
Reopen, so I know to notify you when Chrome and Firefox stores are updated.

**Comment by dteviot** [comment]
@H4n4n 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
