### ISSUE TITLE
Spacebattles award links

### ISSUE THREAD

**Issue by nakie08** [dteviot/WebToEpub#1335]
**Describe the bug**
Spacebattles award links on threadmarks are getting picked up as chapter URLs

**To Reproduce**
1. Go to a fiction on Spacebattles with atleast 1 award. This one https://forums.spacebattles.com/threads/a-greater-game-b5-btech.1140373/ for example has an award on the first chapter and several awards on chapter 20 and onwards.
2. Click on WebToEpub plugin
3. Check to see the extra "chapters" which are the ribbon URLs. On the link I provided it would have 2 chapter 1s and a chapter "1" after chapter 23.
4. Try to pack epub only to fail at extra chapters since it can't parse them.

**Expected behavior**
The plugin disregards the ribbon award links on threadmarks

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
You can just manually deselect the extra chapters ofcourse but it may get tedious on fictions with large number of chapters and awards. Also I'm not sure what award gets picked up. For example on the link I provided the awards on chapter 1 and 23 are getting picked up while the rest aren't.

**Comment by dteviot** [comment]
@nakie08 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://forums.spacebattles.com/threads/a-greater-game-b5-btech.1140373/

For my notes: 12 minutes work

**Comment by nakie08** [comment]
Tested it with several other fics. Seems like it's fixed now. Thank you!

**Comment by dteviot** [comment]
@nakie08 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
