### ISSUE TITLE
readlightnovel.com has turned to readlightnovel.meme

### ISSUE THREAD

**Issue by Retro-s** [dteviot/WebToEpub#1338]
exactly as the title says, i am not well versed with this stuff so idk how to put the wrong css selectors to remove and stuff which is why i request for an official update for the site

**Comment by dteviot** [comment]
@Retro-s 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.readlightnovel.meme/crap-the-villain-is-forced-to-play-the-role-of-the-heroine, chapter 1

For my notes: 13 minutes work

**Comment by dteviot** [comment]
@Retro-s 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

**Comment by Retro-s** [comment]
woah that was really fast, thanks a lot man!
