### ISSUE TITLE
https://www.69shuba.pro

### ISSUE THREAD

**Issue by candy3848** [dteviot/WebToEpub#1339]
https://www.69shuba.pro/

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

Table of Content Varied, since, you have to click on novel to have chapter list

### Did you try using the Default Parser for the site?  If not, why not?

I don't have developer skill, or have anyone to help. 
It looks confusing to do myself. So if anyone can help, thanks.

**Comment by dteviot** [comment]
@candy3848 

I'm not quite sure what you're asking for.
WebToEpub works if you go to the story page for a book.  e.g. https://www.69shuba.pro/book/56042.htm
Note, WebToEpub does NOT work if you go to a Table of Contents page.  e.g. https://www.69shuba.pro/book/46565/

For my notes: 7 minutes work

**Comment by dteviot** [comment]
Closing, due to no response.
