### ISSUE TITLE
Woopread Access Denied 403

### ISSUE THREAD

**Issue by Perfectcandy550** [dteviot/WebToEpub#1340]
I keep getting the following message when I try to pull anything off of woopread, even after logging in and doing the initial human verification. 

WARNING: Site 'woopread.com' has sent an Access Denied (403) error.  You may need to logon or satisy a CAPTCHA before WebToEpub can continue.

Desktop, windows, using chrome

**Comment by dteviot** [comment]
@Perfectcandy550 

Works for me for https://woopread.com/series/the-great-mage-returns-after-4000-years_novel/, chapter 1.
Are you using the version from the Chrome store (version 0.0.0.159), or the Test build from the Google Drive (0.0.0.160)?
Note that the test build has fixes to deal with Cloudflare's "Are you a human?" page.  The version in the Chrome store does not.

For my notes: 5 minutes work.

**Comment by Perfectcandy550** [comment]
That seemed to have fixed it, I was using the chrome store version (0.0.0.159) and not the google drive one - thanks for your help!

**Comment by dteviot** [comment]
Reopen, so I know to notify you when Chrome and Firefox stores are updated.

**Comment by dteviot** [comment]
@Perfectcandy550 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

**Comment by abradr** [comment]
Using the latest Updated version (0.0.0.167), I am facing the same issue.

https://woopread.com/series/bastian/

The novel I was trying to convert

Error Codes
![error code 2](https://github.com/user-attachments/assets/3d42d2cd-7da9-435a-b241-c754aaa0c805)
![error code](https://github.com/user-attachments/assets/06a45040-c46d-4fb8-a41e-137e02be3e9f)

**Comment by dteviot** [comment]
@abradr 
You might try the latest development build.  IIRC, there have been some changes in the recent releases of Firefox in this area, and WebToEpub needed changes.  They have not been added to version in store.

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by abradr** [comment]
Thanks for your quick reply, I can wait for a new official version. Just wanted to point out that the error was occurring. I am in no hurry and appreciate your good work. Just drop me a reply when the new version is out.

**Comment by dteviot** [comment]
@abradr 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
