### ISSUE TITLE
Would it be possible to add Reddit or users from Reddit?

### ISSUE THREAD

**Issue by Saladitas** [dteviot/WebToEpub#1344]
I just wanted to see if adding Reddit would be possible. There are some communities that have novels, like HFY that I would like to download from. I just haven't seen any way of downloading some of them, especially some that have upwards of 30 chapters.

https://www.reddit.com/r/HFY/

**Comment by dteviot** [comment]
This looks like a table of Contents page
* https://www.reddit.com/r/HFY/wiki/series/builders_in_the_void/

**Comment by Saladitas** [comment]
Yes there are TOC and Wikis, but, I prefer to download them and use an app like Moon+ Reader Pro. I use to read them on the Reddit app, but, after using Moon Reader its a day and night difference in how enjoyable my reading experience is. 
There is no real way to organize them on reddit or keep track of how much you've read among other thing.
If its not possible then its okay, I just wanted to know if it planned feature or not.

**Comment by dteviot** [comment]
@Saladitas 
You misunderstand.  WebToEpub needs to start from a Table of Contents page.  So it knows the URLs of the chapters to fetch.
This seems to be an example of one Table of Contents.  Ideally, I'd like URL of several more, so I can study them and figure out how to write a parser for WebToEpub to handle them.

**Comment by Saladitas** [comment]
Aah I see, well the vast majority of series are here https://www.reddit.com/r/HFY/wiki/series/
Excluding the newer sires, this has a vas majority of them and should be easier to get working.

The newer ones only really have a 

> First | Prev | Next | Patreon

in there chapter post and no wiki so I would be more difficult to make it work for those.

This is an example of one of the newer ones that doesn't have a Wiki/TOC https://www.reddit.com/r/HFY/comments/1dgls32/harmless_human_sacrifice_16/

**Comment by dteviot** [comment]
@Saladitas 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

**Comment by Saladitas** [comment]
Thanks for the update! Tested it and it works.
Tested with series https://www.reddit.com/r/HFY/wiki/series/the_explorer/
