### ISSUE TITLE
menus and navigation included with each chapter for novel bin

### ISSUE THREAD

**Issue by spg19132** [dteviot/WebToEpub#1345]
**Describe the bug**
Both the top and bottom menu, as well as navigation links before and after chapter, are included with each chapter.
**To Reproduce**
1. Go to https://novelbin.com/b/forgotten-legend-of-the-bloodied-flower#tab-chapters-title
2. Click on "pack epub" (have the following options selected: "no Additional Metadata," "less tags," "Skip Images," and "Add Information page to Epub" selected)
3. returns an ePub file with the extra described above.

**Desktop (please complete the following information):**
 - MacOS
 - chrome
 - Version 0.0.0.159

Thank you for your help :)

**Comment by dteviot** [comment]
@spg19132 

Annoying.  The chapters appear to be scattered across multiple hosts.
Or, at least, multiple host aliases.  Which has confused WebToEpub.

Hosts seem to be variation of:
*.novelcenter.net  or
*.noveljar.org

Try adding pattern match for these hosts. 
Note, if doesn't work, might be easier to provide a script for https://github.com/dteviot/EpubEditor to clean up chapters after downloading.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelbin.com/b/forgotten-legend-of-the-bloodied-flower#tab-chapters-title, chapters 1 to 3

For my notes: 27 minutes work

**Comment by dteviot** [comment]
@spg19132 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

**Comment by swanknight** [comment]
> Try adding pattern match for these hosts. Note, if doesn't work, might be easier to provide a script for https://github.com/dteviot/EpubEditor to clean up chapters after downloading.
> 

The current version (0.0.0.160) didn't fix the issues for me. So I decided to make a script and run it after the fact, I only tested on one novel so far, but I'll leave it here in case it helps ayone in the future. This script will clean all the Novelbin garbage, and properly creates the chapter titles as best as it could.

```
let ntitle = dom.querySelector("a.novel-title");
let ctitle = dom.querySelector("a.chr-title");
let header = dom.querySelector("header");
let cnav = dom.querySelector("div.chr-nav");
let nav = dom.querySelector("div.navbar-breadcrumb");
let comments = dom.querySelector("div.comments");
let footer = dom.querySelector("footer");
let h2 = dom.querySelector("h2");
let h3 = dom.querySelector("h3");
let hr = dom.querySelectorAll("hr");
let scripts = dom.getElementsByTagName("script");
let p = dom.querySelectorAll('p');

if (ntitle) {
    ntitle.parentNode.removeChild(ntitle);
}

if (ctitle) {
    ctitle.parentNode.removeChild(ctitle);
}

if (header) {
    header.parentNode.removeChild(header);
}

if (cnav) {
    cnav.parentNode.removeChild(cnav);
}

if (nav) {
    nav.parentNode.removeChild(nav);
}

if (comments) {
    comments.parentNode.removeChild(comments);
}

if (footer) {
    footer.parentNode.removeChild(footer);
}

if (hr && hr.length > 0) {
    hr.forEach(element => {
        element.parentNode.removeChild(element);
    });
}

if (h2) {
    h2.parentNode.removeChild(h2);
}

for (var i = scripts.length - 1; i >= 0; i--) {
    scripts[i].parentNode.removeChild(scripts[i]);
}

let fline = p[0].textContent.trim();
let chapterMissing = fline.match(/^\d/);
if (fline.startsWith('Chapter') || chapterMissing) {
    var parent = p[0].parentNode;
    var newElement = dom.createElement("h1");
    
    if (chapterMissing){
       fline = "Chapter " + fline;
    }

    newElement.textContent = fline;
    parent.replaceChild(newElement, p[0]);
}

if (h3){
   var parent = h3.parentNode;
   var newElement = dom.createElement("h1");
   newElement.textContent = h3.textContent;
   parent.replaceChild(newElement, h3);
}

for (i = 0; i < p.length; ++i) {
    if (p[i].textContent.includes('Transl') && p[i].textContent.includes('Edit')) {
        p[i].parentNode.removeChild(p[i]);
    }
}

return true;
```

**Comment by dteviot** [comment]
@swanknight 

Try https://github.com/dteviot/EpubEditor/blob/master/mutators/CleanNovelbin.js

Also, FYI, Javascript now has a better way of doing 
```javascript
    nav.parentNode.removeChild(nav);
```

try
```javascript
    nav.remove();
```

https://developer.mozilla.org/en-US/docs/Web/API/Element/remove

**Comment by dteviot** [comment]
Note, problem is site keeps changing the name of the site for the chapters.  This confuses WebToEpub so it doesn't select the correct parser to decode the pages.  But I've got an idea how to fix.

**Comment by swanknight** [comment]
> @swanknight
> 
> Try https://github.com/dteviot/EpubEditor/blob/master/mutators/CleanNovelbin.js
> 
> Also, FYI, Javascript now has a better way of doing
> 
> ```js
>     nav.parentNode.removeChild(nav);
> ```
> 
> try
> 
> ```js
>     nav.remove();
> ```
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Element/remove

Thanks for the tip, as well as the clean script. 👌
I used your script, and added to it the extra stuff I wanted to fix. 
I also added comments to make it easier to understand the purpose of the extra block.

**Comment by dteviot** [comment]
@swanknight 
I see a couple more teachable moments.

```javascript
if (content) {
    content.removeAttribute('style');
}
```

can be

```javascript
    content?.removeAttribute('style');
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

and 

```javascript
        parent.replaceChild(newElement, p[0]);
```

can be

```javascript
        p[0].replaceWith(newElement);
```
https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith

**Comment by dteviot** [comment]
Going to reopen, because problem has reappeared.  Need to fix like

> Note, problem is site keeps changing the name of the site for the chapters. This confuses WebToEpub so it doesn't select the correct parser to decode the pages. But I've got an idea how to fix.
Basically, set the chapter URLs to match the current host and rely on redirection to get to the wanted page.

(**PROBABLY BETTER SOLUTION**) when get chapter list, register the hostnames as using the NovelBin parser

**Comment by swanknight** [comment]
> @swanknight I see a couple more teachable moments.

Thanks, @dteviot sensei. 😁

**Comment by dteviot** [comment]
@spg19132 @swanknight 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelbin.com/b/forgotten-legend-of-the-bloodied-flower#tab-chapters-title, chapters 1 to 6

For my notes: 47 minutes work

**Comment by swanknight** [comment]
> Test versions for Firefox and Chrome have been uploaded
> For my notes: 47 minutes work

Tested with [this novel](https://novelbin.com/b/i-maximize-my-item-dropping-rate), chapters 1 through 50. All good. 👍

![image](https://github.com/user-attachments/assets/5ee15481-332c-4403-a91e-08037252f66e)

**Comment by dteviot** [comment]
@swanknight @spg19132 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
