### ISSUE TITLE
Please Update Parser for Pages with Different Format on --> https://chaleuria.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1346]
Hello! :D

There's not quite an issue with this site per se, but **some** pages on this source have a different format whereby the body content is wrapped in a different element which the current parser doesn't account for and I was wondering if the parser could be updated to also address the second format please? Also, I think the heading is still `<h1>` so that's no issue there.

**Example TOC:** https://chaleuria.com/novels/complete-guide-use-care-personal-assistant/

<hr />

Current Format Webtoepub Works For (Including the Table of Contents): https://chaleuria.com/novels/complete-guide-use-care-personal-assistant/chapter-030/

> CSS Selector for Body Content:

` .entry-content`

Different Format Webtoepub Cannot Parse: https://chaleuria.com/cgpa-c031/

> CSS Selector for Body Content:

`div[class^='elementor-widget-container']`

<hr />

And, I've tried using the Default Parser for the chapters with the divergent format, but to no avail, so came here hoping to receive a fix to this issue~ Thank you very much for your help again! xx

**Comment by Kiradien** [comment]
There's a bit of a format difference between the format between the standard and paid chapter formats, most notably chapter titles, but I've thrown up a pull request with this fix in mind. 
The fix has a chance of running into issues in the future if chaleuria shifts to using both styles in a single page, but I can't see it in existing pages.

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* Untested (by me)

@Kiradien Thank you for your hard work.

**Comment by plsbenice-immadeofjelly** [comment]
@Kiradien @dteviot

Thank you both!!! :D It worked perfectly!! <3

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
