### ISSUE TITLE
Please add site https://daodivinetl.com/

### ISSUE THREAD

**Issue by meeny123** [dteviot/WebToEpub#1348]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://daodivinetl.com/book/pretending-as-the-immortal-emperor
### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes, I tried using the default parser and also trying to use CSS selector to manually make the epub as well. But, I was never able to get anything but a blank page.
### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB <--- this one didn't work
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
sorry I don't know any dev friends :(. Thank you very much for your hard work, this extension/add-on is very important part of reading web novels. Being able to collate and export my epub to whatever device and use it online/offline while having a standardized format that I personally enjoy is a huge difference maker. To me this extension is just as important as adblockers and dark mode which have millions of users!

**Comment by dteviot** [comment]
@meeny123
Duplicate.  See: https://github.com/dteviot/WebToEpub/issues/1217
