### ISSUE TITLE
Auto convert not-supported websites using readability library

### ISSUE THREAD

**Issue by matejdro** [dteviot/WebToEpub#1349]
Currently, WebToEpub seems to rely on hand-writing parsers for individual websites. But this is very non-scalable process.

Most web pages are not that complex and they do not require extra chapter support etc. and Mozilla has already exposed their readability library that exposes pure page content, while removing all the cruft such as menus: https://github.com/mozilla/readability

Any chance this could be incorporated into the addon?

**Comment by Kiradien** [comment]
I remember playing with this a few years back; It usually worked with general chapter contents, but ran into more issues on JSON loads...

It might(?) be better now, as far as I'm aware it won't work on the actual problem cases, but implementing it into the base parser logic might remove the need for the findContent and extractTitleImpl methods... But custom logic will still be needed to grab the chapter list.

**Comment by dteviot** [comment]
@matejdro 

To expand on Kiradien's comments: 
1. I'm not sure that readability provides much benefit over the "default" parser, where someone can manually supply CCS to specify the main content element.
2. IIRC, the Readability library was large, complicated, and I forget how many dependencies it has.  I'm not looking forward to doing a security audit of it.

That said, WebToEpub is open source.  So, if you'd like to try and get something working with Readability, I'd certainly give any merge requests careful consideration.

**Comment by matejdro** [comment]
Thanks for your answer. I guess I will close the issue then for now.
