### ISSUE TITLE
Please add site, thank you! --> https://novelversetranslations.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1350]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://novelversetranslations.com/what-to-do-when-the-boss-takes-a-liking-to-you/**

Hello! Apologies for being back again so soon with another request. Though this site does indeed work with Webtoepub, the format used for the Table of Contents is a bit different (somewhat resemblant to scribblehub) and requires switching between "pages" to view all chapters. So, Webtoepub doesn't automatically detect **all** chapters without manually inserting them into the extension. If possible, could a workaround be made for auto-detection of all chapters in the listing, please? Thank you very much again! xx

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelversetranslations.com/what-to-do-when-the-boss-takes-a-liking-to-you/, chapter 1 and 75

For my notes: 51 minutes work

There's 3 stories on the site, and at least one is finished.  This isn't the best use of my time.  In future, check how many stories are on site before I do something like this.

**Comment by plsbenice-immadeofjelly** [comment]
Apologies for wasting your time again, and although I usually would request sites with more content, but this source is fairly new and updates extremely fast with new novels, despite it only being a few weeks since they started translating, so I thought it wouldn't hurt to request support to be added for it early on. But I understand the need to be called out for the inconvenience, so I'll keep that in mind. I apologise again, and thank you for still doing as I've requested, your efforts are much appreciated :)

**Comment by dteviot** [comment]
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
