### ISSUE TITLE
Please add site https://novelhulk.net/

### ISSUE THREAD

**Issue by Ketboga** [dteviot/WebToEpub#1354]
Thank you very much beforehand.

**Comment by dteviot** [comment]
@Ketboga 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelhulk.net/novelhulk/dungeon-diver-stealing-a-monsters-power, chapter 1

For my notes: 8 minutes work.  (Yet another alias for NovelNext.  They're not even trying to hide it.  The page header says NovelNext.)

**Comment by dteviot** [comment]
@Ketboga 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
