### ISSUE TITLE
storyseedling.com needs update

### ISSUE THREAD

**Issue by dnshipit** [dteviot/WebToEpub#1355]
**Describe the bug**
Site download no longer work due to website update.

This following selector:

https://github.com/dteviot/WebToEpub/blob/8946f6db28e8319352e403ddac98b293e5d02e9e/plugin/js/parsers/StorySeedlingParser.js#L11

no longer point to the link itself. They have updated the structure of the chapter list which we can easily fix if we replace said selector with the this selector I think.

```js
flex.items-center.p-2.rounded.bg-accent.hover:bg-accent-hover
```

**To Reproduce**
1. Go to any story on the website
2. Click on webtoepub plugin
3. Instantly crash with error

> link.querySelector(...) is null linkToChapter@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/parsers/StorySeedlingParser.js:17:26
> getChapterUrls/<@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/parsers/StorySeedlingParser.js:12:31
> getChapterUrls@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/parsers/StorySeedlingParser.js:12:14
> onLoadFirstPage@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/Parser.js:378:14
> processInitialHtml@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/main.js:47:24
> populateControlsWithDom@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/main.js:252:27
> onMessageListener@moz-extension://8eceaf37-86d2-4b0b-b5fa-ff3db78b0fc9/js/main.js:16:36
> 

**Expected behavior**
Working as it used to be

**Desktop (please complete the following information):**
 - OS: Debian bookworm 12.4
 - Browser: Firefox
 - Version: 115.11.0esr

**Comment by dteviot** [comment]
@dnshipit 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://storyseedling.com/series/185591/, chapter 1
* https://storyseedling.com/series/183623/, chapter 1

For my notes:  20 minutes work
