### ISSUE TITLE
Wetriedtls.com error?

### ISSUE THREAD

**Issue by Naanaa28** [dteviot/WebToEpub#1356]
**Describe the bug**
I tried downloading this book from them and it loads alright, but by the end I get this error and the file doesn't save.
![Screenshot 2024-06-23 121413](https://github.com/dteviot/WebToEpub/assets/151754223/582daa0c-e4da-449c-9799-501351dfcdea)
![Screenshot 2024-06-23 115556](https://github.com/dteviot/WebToEpub/assets/151754223/53b04399-f0e8-4d51-8d62-ec709a21667b)

**To Reproduce**
1. Go to '...' https://wetriedtls.com/series/sss-class-hunter-who-dies-to-live
2. Click on '....' pack epub
3. Wait for the book to finish packing

**Expected behavior**
Like every other epub for a pop-up window to appear asking me to save the file.

**Screenshots**

![Screenshot 2024-06-23 121413](https://github.com/dteviot/WebToEpub/assets/151754223/582daa0c-e4da-449c-9799-501351dfcdea)
![Screenshot 2024-06-23 115556](https://github.com/dteviot/WebToEpub/assets/151754223/53b04399-f0e8-4d51-8d62-ec709a21667b)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dteviot** [comment]
@Naanaa28 

Site seems to have changed layout again.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://wetriedtls.com/series/sss-class-hunter-who-dies-to-live, chapter 1
* https://wetriedtls.com/series/the-little-prince-in-the-ossuary, chapter 1

For my notes: 35 minutes work

**Comment by dteviot** [comment]
@Naanaa28 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

Note, due to site changes, it is no longer supported by WebToEpub
