### ISSUE TITLE
Fetch of URL 'http://xn--chng-mgb3g/' failed with network error Failed to fetch.

### ISSUE THREAD

**Issue by k3ltfalcon** [dteviot/WebToEpub#1357]
I try to make a epub from this url 
https://daylatayan.wordpress.com/ngay-xuan-oanh-hot-hai-thanh-na-thien-nga-2/
But it's fail

**To Reproduce**
1. Go to 'https://daylatayan.wordpress.com/ngay-xuan-oanh-hot-hai-thanh-na-thien-nga-2/'
2. Click on 'WebtoEpub'
3. Scroll down to click on 'Pack Epub.'
4. See error 'Fetch of URL 'http://xn--chng-mgb3g/' failed with network error Failed to fetch.'

**Expected behavior**
I want to a epub from this url.

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/162257733/3995edbd-cdf4-42fe-bfc6-7f3b8e2144bb)

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version [0.0.0.160]

**Comment by dteviot** [comment]
@k3ltfalcon 

Looks like the link for chapter 56 is broken.  Click the "Show URLs of Chapters" buttons and you will be able to see the URLs.
Options:
1. Click the "Edit Chapter URLs" button and type in the correct URL.
2. Contact the site owner and ask them to fix it.
3. Remove chapter 56 from list.

**Comment by k3ltfalcon** [comment]
Thank for your support
