### ISSUE TITLE
Please update site parser again with footnotes, thank you! --> https://www.crimsontranslations.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1358]
Hello! I apologise for requesting another update with this same source, but I've noticed that the novels which include both footnotes and translator notes are not detected within the configured scope of the "body content" that the existing parser already pertains to, and was hoping for a update to also grab the footnotes for this site.

**Example TOC:** https://www.crimsontranslations.com/39-whispers-of-love-in-the-right-ear

**Example Chapter with Both Footnotes and Translator Notes:** https://www.crimsontranslations.com/39-whispers-of-love-in-the-right-ear/310

Both the **footnotes** and **translator notes** are generally located right under the element holding the novel content in these tags: `<div class="flex flex-col p-2 border-t-2 border-tertiary break-words text-md text-justify w-full">`

Thank you again for all your assistance and apologies in advance for the inconvenience caused :)

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.crimsontranslations.com/39-whispers-of-love-in-the-right-ear/310

For my notes: 25 minutes work

**Comment by plsbenice-immadeofjelly** [comment]
Thank you again for the continued help with this same source and apologies for the inconvenience :) it worked as always~

**Comment by dteviot** [comment]
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
