### ISSUE TITLE
error to get chapter list with https://phoenixtls.wixsite.com

### ISSUE THREAD

**Issue by H4n4n** [dteviot/WebToEpub#1364]
**Describe the bug**
at the moment to use the extension it show this image and then never shows the chapters
![image](https://github.com/dteviot/WebToEpub/assets/131601319/0a3aab1a-e867-426b-89a1-da4c4c720249)

![image](https://github.com/dteviot/WebToEpub/assets/131601319/e1e58d04-8d1a-4b40-8187-d753ab4feffa)

**To Reproduce**
1. Go to 'https://phoenixtls.wixsite.com/phoenixtl/chapter-index'
2. Click on 'web to epub extension'
3. Scroll down to 'the beggining'
4. See error: See the added pictures

**Expected behavior**
to get the chapter list and then download the epub

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Version Versión 126.0.6478.127 
**Additional context**

**Comment by dteviot** [comment]
@H4n4n 

This seems to be a very different format to the usual wixsite layout.
I think you'll need to use the default parser to get this story.

Instructions.
1. Click the "OK" button on the error message.
2. Click on the "Advanced Options" button
3. Make sure "Skip chapters that return HTTP 404 error" is checked.
4. On "Manually Select Parser:"  Select "Default"
5. Set "CSS selector for element holding content to put into EPUB" to "div.post-content__body"  (ignore the quotes)
6. Set "CSS selector for element holding Title of Chapter:" to "h1"
7. Leave the other two blank, and click "Apply"
8. Unselect the links that are not chapters.  (Beware of "Discord" at the bottom.)
9. Click "Pack EPUB"

For my notes: 30 minutes work
