### ISSUE TITLE
Removing epub from Library does not reset include status

### ISSUE THREAD

**Issue by Kiradien** [dteviot/WebToEpub#1365]
**Describe the bug**
When adding a chapter to an epub, it automatically registers the story in your Reading List. Deleting the epub (often to resolve generation issues) does not reset this status, leaving the chapters forever unchecked.

**To Reproduce**
1. Add a story to the library
2. Remove the story from the library
3. Open the page again, epub is gone but still in reading list.

**Expected behavior**
Removal from library also removes from reading list.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version [WebToEpub 0.0.0.160] [Chrome 126.0.6478.127]

**Additional context**
A pull request for this fix will be in place soon. This was a complex but low priority problem that has existed for a fairly long time and just annoyed me enough today to dig into it. Complex enough that it absolutely needs a ticket.

**Comment by dteviot** [comment]
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.

**Comment by dteviot** [comment]
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
