### ISSUE TITLE
Site request: https://novelcranel.org/

### ISSUE THREAD

**Issue by Shumpus** [dteviot/WebToEpub#1367]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelcranel.org/series/i-became-a-thief-who-steals-overpowered-skills/

### Did you try using the Default Parser for the site?  If not, why not?
Tried using the automatic parser by clicking the extension on the site but it breaks and everything is blank, tried using the default parser (which I have used successfully before) but the test page does not load and it's all unresponsive. Have tried on a few different days on different books.

### What settings did you use?  What didn't work?
Nothing worked in the default parser for this site, unsure why

**Comment by dteviot** [comment]
@Shumpus 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelcranel.org/series/i-became-a-thief-who-steals-overpowered-skills/, chapter 1

Note, you'll need to open "Advanced Options" and set "Skip Images", as the site is doing something to make downloading the cover image a problem.

For my notes: 11 minutes work.  (Site is using same layout as Noblemtl)
