### ISSUE TITLE
Tapas.io error 

### ISSUE THREAD

**Issue by Wilhelmia** [dteviot/WebToEpub#1368]
**Describe the bug**
When I go to Tapas.io and try to get an epub from their novel page I get an error. Until last week it worked very well and I could fetch some epubs, now the error looks like this:

Error: Fetch of URL 'https://tapas.io/series/266599/episodes?page=1&sort=OLDEST&max_limit=9999' failed with network error 500.
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:32:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:192:45)
    at HttpClient.wrapFetchImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:182:31)
    at async TapasParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/TapasParser.js:14:21)

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/174390898/fa3525ec-5ad0-44b8-abad-755a8638e7b4)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Vivaldi]
 - Version [6.9.3392.10]

**Comment by Kiradien** [comment]
Hmm, it looks like the api changed to not accept a max_limit greater than 20.
https://tapas.io/series/266599/episodes?page=1&sort=OLDEST&max_limit=20 works, but 21 does not.
The parser needs to be shifted to a more standardized pagenation format with multiple requests.

I may do a deeper peek into it a bit later, but it doesn't look like too bad to fix. Still, it's annoying that they gave a 500 error on that.

**Comment by Wilhelmia** [comment]
> Hmm, might be more of a revamp than originally expected. It looks like most of the selectors across the parser might be invalid now, but I'm not sure I'm running it from the right view.
> 
> @Wilhelmia - can you confirm the url you opened WebToEpub from? Does the url match the following: https://tapas.io/series/villains-are-destined-to-die-novel ? Or was there a specific "table of contents" page?

Hello!
Thank you for looking into it. I open the special table of contents page which is this link: [https://tapas.io/series/villains-are-destined-to-die-novel/info](https://tapas.io/series/villains-are-destined-to-die-novel/info)

![image](https://github.com/dteviot/WebToEpub/assets/174390898/20dde1aa-bdf8-40ea-966b-f2f3fd2197bb)

**Comment by japzone1** [comment]
As a temp workaround, I was able to get it working using the Default parser, at least for the novel "[Master Villainess the Invincible!](https://tapas.io/series/master-villainess-the-invincible-novel/info)", though I had to cleanup a lot of things. Chapter titles had excessive whitespace by default and that carried over to excessively large filenames, which many ereaders cried foul over. So I had to copy the chapter list into a text editor and filter out the whitespaces. After that the EPUB was functional and I was able to import it into Calibre and edit the file to fix things like font colors, random elements that weren't removed, and cleanup the TOC to look nicer.

It would help if adding multiple selectors to the elements to remove box worked, but commas don't seem to work.

![2024-07-04 16_37_30-Default-2021 - WebToEpub — Firefox Developer Edition](https://github.com/dteviot/WebToEpub/assets/6744865/228ee850-de29-48be-8fb6-49af8218d4af)
![2024-07-04 16_38_36-Default-2021 - WebToEpub — Firefox Developer Edition](https://github.com/dteviot/WebToEpub/assets/6744865/3271d0be-6c48-4f1a-9803-a361307699f6)

**Comment by dteviot** [comment]
@japzone1 
You can use EpubEditor to do more extensive cleanup.  See: https://github.com/dteviot/EpubEditor/issues/4

**Comment by japzone1** [comment]
> @japzone1 You can use EpubEditor to do more extensive cleanup. See: [dteviot/EpubEditor#4](https://github.com/dteviot/EpubEditor/issues/4)

Thanks for the suggestion, currently Calibre's Editor works fine for me. It'd just be nice if I could remove multiple elements right from W2E's Default Parser. Right now it only seems to use the first CSS Selector entered. But that's off topic in this issue.

**Comment by dteviot** [comment]
@Wilhelmia @japzone1 

@Kiradien's fix has been merged into the experimental branch.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* Caution! untested.

**Comment by japzone1** [comment]
@dteviot Seems to work in Firefox v128.0b7 for me. No issues with output that I've noticed so far.

**Comment by Wilhelmia** [comment]
Thank you @dteviot! I tried the chrome version and could finally download some novels again. It worked fine for me on Vivaldi V6.8.3381.55. 😊
