### ISSUE TITLE
https://www.asianovel.net Could not find content element

### ISSUE THREAD

**Issue by bookimp** [dteviot/WebToEpub#1369]
**Describe the bug**
Error downloading chapters

**To Reproduce**
1. Go to https://www.asianovel.net/story/2792/
2. Download story
3. See error 
Error: Could not find content element for web page 'https://www.asianovel.net/chapter/chapter-471468/'.     at chrome-extension://mbpphpinkdklcliheabobbdchiicgjoe/js/Parser.js:501:23     at async Promise.all (index 0)     at async AsianovelParser.fetchWebPages (chrome-extension://mbpphpinkdklcliheabobbdchiicgjoe/js/Parser.js:470:17)

**Expected behavior**
Story to download, I had a partial copy a couple weeks ago that worked fine

**Desktop (please complete the following information):**
OS: Windows 11 Home 64bit
Browser: Opera LVL5 (core: 109.0.5097.130)
WebToEpub Version
0.0.0.161

![image](https://github.com/dteviot/WebToEpub/assets/20101896/81f4ccce-e123-4df6-95eb-0eda27de4f0c)

**Comment by dteviot** [comment]
@bookimp 

Seems to be working.  Tested with https://www.asianovel.net/story/2792/, chapters 1 to 24.
Note that https://www.asianovel.net/chapter/chapter-471468/ is chapter 2.
Possibly the site is testing out different layout, or randomly sends garbage pages to make life difficult for people who scrape it.

Please try again and let me know how it goes.

For my notes: 7 minutes work.

**Comment by bookimp** [comment]
You're right it does seem to be fine now. Odd, ok thanks. Be reassured I did try it 3x that day before opening an issue. Ch2 was where it was stalling.

**Comment by dteviot** [comment]
@bookimp 

No problem.  It's not unknown for sites to do funny things.
