### ISSUE TITLE
Please add site https://blossomtranslation.com

### ISSUE THREAD

**Issue by Naanaa28** [dteviot/WebToEpub#1372]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://blossomtranslation.com/story/life-reversal-with-item-copy/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
I did but I'm sorry there were way too many elements for me to discern.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
I have no developer skills.

**Comment by dteviot** [comment]
@Naanaa28 
Try default parser.  
1. Replace "body" with "section#chapter-content", 
2. Leave the others blank.
and I think it will work.  Note, you might need to remove some of the incorrect URLs W2E finds.

Note, this isn't tested.  If it doesn't work, add note to this incident and I'll build a proper parser.

**Comment by Naanaa28** [comment]
> @Naanaa28 Try default parser.
> 
> 1. Replace "body" with "section#chapter-content",
> 2. Leave the others blank.
>    and I think it will work.  Note, you might need to remove some of the incorrect URLs W2E finds.
> 
> Note, this isn't tested. If it doesn't work, add note to this incident and I'll build a proper parser.

Thank you! It works!! I added Title for the chapter titles though because they don't appear otherwise but works 100% thanks again.

**Comment by dteviot** [comment]
@Naanaa28 
For reference (if anyone looks at this in the future) please supply the CSS you used for the title.
