### ISSUE TITLE
ScribbleHub extractor seems to be broke

### ISSUE THREAD

**Issue by fake-name** [dteviot/WebToEpub#1373]
**Describe the bug**
Trying to convert a scribblehub page to epub fails with an error, generating a ~4kb epub file.

```
Error: Could not find content element for web page 'https://www.scribblehub.com/series/997267/maou-shoujo-magical-chaos/'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:501:23
    at async Promise.all (index 0)
    at async ScribblehubParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:470:17)
```

**To Reproduce**
1. Go to a series page 'https://www.scribblehub.com/series/997267/maou-shoujo-magical-chaos/'
2. Try to save as epub
3. If you include the info page (the first page the chapter list extractor finds), that page fails to extract, generating the above exception.

**Expected behavior**
Previously, this stuck the series info page as the first "chapter" in the book, which was super handy.
 
**Additional context**

I _think_ this can be fixed as easily as changing the content selector to `div.fic_row, div#chp_raw`.

**Comment by fake-name** [comment]
Ok, I managed to load the unpacked extension and can confirm that change resolves the issue. See https://github.com/dteviot/WebToEpub/pull/1374

**Comment by dteviot** [comment]
@fake-name 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.

**Comment by fake-name** [comment]
Test version for chrome at least seems to be working.
