### ISSUE TITLE
Web2Epub Error : Failed to fetch

### ISSUE THREAD

**Issue by NightHawk007** [dteviot/WebToEpub#1377]
Hi i tried to download epub of a novel Absolute Resonance & shadow slave on different sites, but all stopped after some chapters maybe 1-129,1-200 or 1-3,1-817 etc, tried on the same and different sites multiple times and the number always varies and stops and not able to get the full download of all chapters tried on these sites

https://ranobes.top/novels/1072291-absolute-resonance-v741610.html
https://ranobes.top/novels/1205249-shadow-slave-v741610.html
https://novelfull.com/shadow-slave.html
https://novelfull.net/shadow-slave.html
https://novelbin.me/novel-book/shadow-slave#tab-chapters-title
https://freewebnovel.com/shadow-slave.html

Also tried the experimental version, install from source too (https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing) in firefox it also stopped after some chapters.

Ranobes
TypeError: Failed to fetch

freewebnovel
TypeError: Failed to fetch
Warning, unable to convert chapter 'Chapter 431 Fall From Grace' from 'https://freewebnovel.com/shadow-slave/chapter-431.html' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
Conversion error message was: (This page contains the following errors:error on line 1 at column 3635: Specification mandates value for attribute freewebn
Below is a rendering of the page up to the first error.)
Warning, unable to convert chapter 'Chapter 432 First Day of Nothing' from 'https://freewebnovel.com/shadow-slave/chapter-432.html' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
Conversion error message was: (This page contains the following errors:error on line 1 at column 1893: error parsing attribute name
Below is a rendering of the page up to the first error.)

**Comment by gamebeaker** [comment]
@NightHawk007 do you have [Manual Throttle|Delay per chapter](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#manual-throttledelay-per-chapter) active? I am at Chapter 600 on both with 4 Max web pages to fetch simultaneously and 3 Manual Throttle|Delay per chapter.

**Comment by gamebeaker** [comment]
I was able to download both without a problem (Besides one image res. warning for absolute resonance and the two valid xhtml for shadow slave).

**Comment by NightHawk007** [comment]
@gamebeaker I tired the settings you mentioned, 4 Max web pages and 3 Manual it also stopped after reaching 400 something chapters. After that i tried again with 4 Max web pages and 5sec Manual and it worked and got the full chapters. Thank you for pointing it out.

**Comment by dteviot** [comment]
@NightHawk007 

This error
> TypeError: Failed to fetch

Usually means there are network connectivity problems.
Specifically, this is the error message that the browser gives WebToEpub when WebToEpub requests a page (chapter) and NOTHING comes back.

There's really nothing I can do to fix these.

I just pinged https://novelfull.net/ and got a "Site Down" response.

**Comment by gamebeaker** [comment]
@dteviot as an idea maybe select a value for [Manual Throttle|Delay per chapter](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#manual-throttledelay-per-chapter) in the "default" configuration meaning if someone installs the extension for the first time. The reason is that a lot of sites have a cloudflare protection or something similar. I also know a few pages that if your ip gets on a blocklist they don't send a 4xx code but an empty document. And to get unblocked you have to wait.
If you want to implement it i would set 1 sec/chapter as default.

**Comment by dteviot** [comment]
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
