### ISSUE TITLE
[Question] Separating extension and core "module"

### ISSUE THREAD

**Issue by AzSiAz** [dteviot/WebToEpub#138]
There was a question about creating an app and a server mode to create epub without installing chrome extension, is this still on the table ?

Because one way to move forward with this (or event just better maintainability) would be to separate the core functionality of this extension into a npm module and just update the chrome extension when a new version of the core module is out to support the latest update

**Comment by dteviot** [comment]
No.  This has not been done.
And to be perfectly honest, as bugs are being reported (and feature requests made) faster than I can deal with them, I don't see this ever being done.
