### ISSUE TITLE
NovelRingan: Each chapter has two copies of the content

### ISSUE THREAD

**Issue by rektpartyaftermath** [dteviot/WebToEpub#1380]
**Describe the bug**
The chapter is duplicated, only visible when viewed using plain text.
**To Reproduce**
Create epub on Novelringan, open the epub as zip and view one of the chapter on plain text, look for display:none.

**Expected behavior**
To not include those duplicate chapter.

**Additional context**
It actually doesn't affect normal epub reader as it set to display:none, but legado reader will show that duplicate chapter, and also its kinda inefficient having that duplicate.

**Comment by dteviot** [comment]
@rektpartyaftermath 

You have not supplied a URL, I'm going to assume you're using site https://novelringan.com/.
You can remove the duplicated text by using EpubEditor https://github.com/dteviot/EpubEditor/issues/4 with the following script

```javascript
let toChange = [...dom.querySelectorAll("[style='display:none']")];
for(let s of toChange) {
    console.log(s);
    s.remove();
}
return 0 < toChange.length;
```

For my notes: 20 minutes work

**Comment by rektpartyaftermath** [comment]
yup it is novelringan.com.
i remember there's an separate parser for novelringan, is it changed or something?

**Comment by dteviot** [comment]
WebToEpub is currently using the Basic WordPress parser for this site.  That's been around for a long time.
Checking the Git history, I can find no reference to novelringan

**Comment by rektpartyaftermath** [comment]
ok then, thx for your respond.
