### ISSUE TITLE
Filename not working

### ISSUE THREAD

**Issue by Arsur3215Loki** [dteviot/WebToEpub#1381]
I don't know if it's only happening to me or what but what I put on the filename to be downloaded as, and instead download as random code or something (f396b4a5-2711-4ba0-9ee0-20c1c95db7f8.epub). I had to babysit and download it one by one or had to open the file just to know the name and rename it.

 - OS: Windows 10
 - Browser Opera GX

**Comment by gamebeaker** [comment]
@Arsur3215Loki deactivate all other extensions and try again.

**Comment by Arsur3215Loki** [comment]
Found what causing it, I don't know if it would be helpful but the name of the extension that is causing the problem is **[XDM Integration Module](https://xtremedownloadmanager.com)**

**Comment by dteviot** [comment]
@Arsur3215Loki 
> it seems that I need to find something else.

Probably won't help.  Due to the way Chrome works, all extensions that do downloads conflict.
