### ISSUE TITLE
Please enable a feature wherein I can add a custom text at the bottom of each xhtml files

### ISSUE THREAD

**Issue by TimeLimit67** [dteviot/WebToEpub#1385]
Hello!

I hope this is the right place to ask. Otherwise, I apologize in advance yet I still hope that anyone with idea how to do it will be able to help me.  Well, this can be achieved by adding the text manually in each xhtml file but that's too time-consuming and frustrating, isn't it?

Is it possible to add a **button/box wherein you can add a custom text** (For intance, your name as the creator and editor of the epub, disclaimer, links, etc.)?

You can type the content you want in there. If granted, I hope it can also support emojis. _The packed epub will show this custom text at the end of each xhtml file_ which can be manipulated (change the font, font size, color, alignment) by editing the epub's CSS.
This way, you won't be adding it manually. It can be done in one go.

Otherwise, you can give me a website, online tool, css codes, plug-in or anything I can use to achieve this, if there is any.

It looks something like this:

![Screenshot (19)](https://github.com/user-attachments/assets/e67bc802-3d6a-4a5a-ac49-76ce35fa061a)

**Comment by gamebeaker** [comment]
@TimeLimit67 test.epub is your file. 

- Extract it as a zip archive with 7zip or rename it to test.zip and than extract it. 
- Open the extracted folder with vscode. 
- Open OEBPS->Text->XXXChapter.xhtml got to the end and copy "</body></html>" at the end of the document. 
- Press CTRL+Shift+H on the left side it should open a Search and Replace field. 
- Copy in the Search field "</body></html>" and in the Replace field "your text in xhtml format </body></html>". 
- The search should find 1 result in 1 file as you search the end of a file. Press "Replace All".
- Close vscode
- zip the folder
- rename the zipped foder to XXXX.epub
Hope this helps.

**Comment by dteviot** [comment]
@TimeLimit67 
This isn't quite correct. 
Re-zipping the file doesn't quite work.  Some epub readers require the mimetype file to be the very first file in the zip.
So, you're best to use a tool like Calibre to re-pack the epub.
I think you can also use Calibre to do a global search/replace as well.  (Although I have not tested it.)

Actually, thinking about this a little bit more.  I think we can do what you want with EpubEditor.  https://github.com/dteviot/EpubEditor/issues/4 You just need to write a script to inject something into the XML, rather than remove it.  I'm a bit busy at moment, but I'll try and put together an example in the next day or so.

**Comment by dteviot** [comment]
Aside: I asked ChatGPT to "write a calibre plugin that can add the same text to the end of every chapter".

I got this back
```python
from calibre.customize import EditBookToolPlugin
from calibre.ebooks import epub

class AddTextToEndPlugin(EditBookToolPlugin):
    name = 'Add Text to End of Chapter'
    version = (0, 1, 0)
    author = 'Your Name'
    supported_platforms = ['windows', 'osx', 'linux']

    def __init__(self, *args, **kwargs):
        EditBookToolPlugin.__init__(self, *args, **kwargs)
        self.create_action(
            name='add_text_to_end',
            text='Add Text to End of Chapter',
            function=self.add_text_to_end
        )

    def add_text_to_end(self, editor, paths):
        for path in paths:
            book = epub.open(path)
            for item in book:
                if isinstance(item, epub.EpubHtml):
                    content = item.content
                    # Modify content (append text to end of each chapter)
                    modified_content = content + "<p>Text to add at the end of each chapter</p>"
                    item.content = modified_content
            book.save()

# Instantiate and register the plugin
plugin_instance = AddTextToEndPlugin()
```

**Packaging and Testing**
Package your plugin for Calibre. Ensure you test it thoroughly to handle different formats and edge cases, considering factors like HTML structure variations in ebooks.

**Notes:**
Calibre Plugin API: Refer to Calibre’s plugin documentation for detailed guidance on plugin development.

**Comment by TimeLimit67** [comment]
Hello. Many thanks for the response.

Unfortunately, I don't have any idea how apply that plug-in you've provided.

But I did found a JavaScript code before that I tried to use using EpubEditor but it did not work. Here's the certain script:

var toInsert = document.createElement("div");
toInsert.innerHTML = "text to insert";
toInsert.style.position = "absolute";
toInsert.style.bottom = "0px";
toInsert.style.textAlign = "center";
toInsert.style.width = "100%";
document.body.appendChild(toInsert);
Expand

I found it on this forum after searching for a while: https://stackoverflow.com/questions/26981201/javascript-to-put-centered-text-at-the-bottom-of-the-page

JavaScript code that can insert a text at the end of xhtml file can work too. 

Many thanks for the patience 🙏😊🙏😇.

**Comment by dteviot** [comment]
@TimeLimit67 

Almost.  Try:
```javascript
var toInsert = dom.createElement("p");
toInsert.innerHTML = "text to insert";
toInsert.style.position = "absolute";
toInsert.style.textAlign = "center";
toInsert.style.width = "100%";
dom.body.appendChild(toInsert);
return true;
```

Obviously, you'll want to change the "text to insert".

Tested with: https://gravitytales.com/index.php/category/xianxia/sword-sect/
For my notes: 23 minutes work.
