### ISSUE TITLE
Helscans.org not working anymore

### ISSUE THREAD

**Issue by X-Xadro** [dteviot/WebToEpub#1386]
Helscans.org which used to be working now only shows this:

![2024-07-17 11_22_38-WebToEpub - Brave](https://github.com/user-attachments/assets/38de7001-5ece-48af-bddb-6131ec349680)

Hope you can fix it!

**Comment by dteviot** [comment]
@X-Xadro 

This is an easy one.  Site has changed name from https://helscans.com/ to https://helscans.org/

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://helscans.org/manga/this-world-needs-a-hero/

For my notes: 7 minutes work

**Comment by X-Xadro** [comment]
Yep can confirm it works, thanks!

**Comment by dteviot** [comment]
@X-Xadro 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
