### ISSUE TITLE
Wetriedtls not working

### ISSUE THREAD

**Issue by Displayeddd** [dteviot/WebToEpub#1388]
**Describe the bug**
When clicking on the PACK EPUB button you get an error:
TypeError: Cannot read properties of null (reading 'parentNode')     at WetriedParser.getInformationEpubItemChildNodes (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/WetriedParser.js:60:53)     at WetriedParser.populateInfoDiv (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:354:27)     at WetriedParser.makeInformationEpubItem (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:342:14)     at WetriedParser.webPagesToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:314:33)     at WetriedParser.epubItemSupplier (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:302:30)     at packEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:187:37)     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:154:20

**To Reproduce**
1. Go to 'https://wetriedtls.com/series/sss-class-hunter-who-dies-to-live'
2. Click on 'WebtoEpub Exrtension and Pack Epub'
3. Wait for error

**Expected behavior**
The extension working.

**Screenshots**
![image](https://github.com/user-attachments/assets/f1641179-173a-40b4-b4bb-fcbc1ce3b360)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [0.0.0.160]

**Additional context**
I saw the other issue that had the same error and tried downloading the extension to see if it worked but instead of getting an error, it prompts the download file on the first chapter.

**Comment by dteviot** [comment]
@Displayeddd 

Site has modified it's design to make it difficult for WebToEpub to extract the content.  Removed site from supported list.
For my notes: 30 minutes work
