### ISSUE TITLE
Xenforo generation sometimes selecting the wrong post? (Spacebattles/SufficientVelocity)

### ISSUE THREAD

**Issue by Kiradien** [dteviot/WebToEpub#1390]
**Describe the bug**
When generating the epub from the following domain, several chapters are pulling content from the wrong post - Steel 1.1 is pulling from post id 100798309 instead of 100800052 - the next post in the same thread.

**To Reproduce**
1. Go to https://forums.spacebattles.com/threads/simply-a-projection-worm-projection-quest.1158463/
2. Generate epub
3. Open chapter 2 from epub (Steel 1.1), compare against Steel 1.1 on Spacebattles

**Expected behavior**
Retrieve the correct post

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 126.0.6478.127 
 - WebToEpub Version 0.0.0.160

**Additional context**
I first noticed this issue when I was on vacation a few days ago. Seemed a bit funky - I think it might be due to the ads, but I haven't been able to investigate.
I'll be settled in a few days and be able to better dig into it, but a bug this weird should be posted.

**Comment by NopexTheFrist** [comment]
This also happens for the Sufficient Velocity website.

**Comment by Kiradien** [comment]
> This also happens for the Sufficient Velocity website.

That's a bit concerning, but good to know that it's an underlying problem parsing Xenforo; Did you just notice this issue yourself, or is it long running?

**Comment by NopexTheFrist** [comment]
I noticed it yesterday and was going to report the issue today, but it was already done.

**Comment by dteviot** [comment]
@Kiradien

Problem is that the site is violating the rule that id values need to be unique on a page.  e.g. for Steel 1.1, there are two &lt;articles&gt; which contain a &tl;span&gt; with an id of "post-100800052"

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://forums.spacebattles.com/threads/simply-a-projection-worm-projection-quest.1158463/, chapters 1.1 to 1.5

For my notes:  50 minutes work

**Comment by dteviot** [comment]
@NopexTheFrist @Kiradien 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
