### ISSUE TITLE
Issue about Epubeditor

### ISSUE THREAD

**Issue by Magico03** [dteviot/WebToEpub#1391]
My Epubeditor isn't working anymore. After using/ clicking "dragging and dropping" or "add file" option, "clean..." button doesn't appear anymore. Can you please tell me how can I slove this issue?

**Comment by dteviot** [comment]
@Magico03 
EpubEditor hasn't changed, so I'd guess either
1. Something with your browser, or
2. You've managed to delete one of the Epubeditor's files.

My suggestions would be 
1. use Epubeditor with a different browser.  e.g. Firefox (if you've been using Chrome) or Edge,
2. Fetch the Zip with Epubeditor again, unpack and try again.

**Comment by Magico03** [comment]
Okay, I'll try that. Thank u ❤️

**Comment by dteviot** [comment]
@Magico03 
Closing, due to no reply.
FYI.  As this concerns EpubEditor, should really raise this against EpubEditor https://github.com/dteviot/EpubEditor, not WebToEpub.
