### ISSUE TITLE
Can't download from https://www.scribblehub.com/

### ISSUE THREAD

**Issue by aureshion** [dteviot/WebToEpub#1393]
**Describe the bug**
I tried downloading from scribble.hub yesterday. the first time I loaded it showed everything just fine. but once I tried downloading a novel it gave a rate limit error of some kind (I think? I accidentally clicked it away without getting a chance to read it in full)

Ever since then I haven't been able to load anything from scribble.hub at all. it just give an error message (included [attachment)](url)

**To Reproduce**
Basically what I mentioned above. download from scribble hub without a specific rate limit set.

**Expected behavior**
I'd have expected scribble.hub to have temporarily stopped it from working but return to normal after a while. but it's still the same even after 24 hours

**Screenshots**
![WebtoEpub_errormessage](https://github.com/user-attachments/assets/45faefcb-bf6e-49bf-bc6d-86529af62905)

**Desktop (please complete the following information):**
 - OS: windows 11 23H2
 - chrome
 - 126.0.6478.182

**Additional context**
Download seemed to work fine running on my Steamdeck using chrome (running steamos in desktop mode). It's worth nothing that I was on a different network when I tried this.

**Comment by gamebeaker** [comment]
@aureshion can you visit the website normal in your browser or do you get an empty page? What is the website? (scribble.hub doesn't exist did you mean [scribblehub.com](https://www.scribblehub.com))

**Comment by aureshion** [comment]
Ah, my mistake on getting the url wrong.

So really weird thing. for some reason it does work again now. even though I didn't do anything. so I feel like I kinda wasted your time there. sorry about that

To answer your question. I used the extension while on the page of the novel I was trying to download. so I was able to visit the website. the issue hasn't occurred again since it started working again because I now have a fetch delay.

again, sorry for wasting your time. genuinely don't know what caused it to stop and then start working again.

**Comment by gamebeaker** [comment]
@aureshion can you provide an example story where it happend?

**Comment by aureshion** [comment]
Alright, I've figured it out finally. turns out I very much incorrectly assumed that you could use the extension from any chapter page. not sure why I came to that conclusion. but yeah. turns out I just needed to use the "main" story page.

Once again. sorry for wasting your time '-.-

**Comment by gamebeaker** [comment]
@aureshion xD xD
if it is now clear please close this issue.
