### ISSUE TITLE
Please add site https://novelnext.dramanovels.io/

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#1395]
Hi, Is it possible to add this website ? 

I think it changed the domain, it was https://novelnext.com/. But now, if we choose a novel on the Home page, the domain change.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelnext.dramanovels.io/nw/cultivation-online-novel

### What settings did you use?  
* URL of first chapter : https://novelnext.dramanovels.io/nc/cultivation-online-novel/chapter-1
* CSS selector for element holding content to put into EPUB #chr-content
* CSS selector for element holding Title of Chapter .chr-text
* CSS selector for element(s) to remove

I used those settings, and it seems to works.

Thanks for your works !

**Comment by dteviot** [comment]
@Flwk 

Added new domain.  Also added the Novelnext parser to the "Manually Select Parser" dropdown list under "Advanced Options".  So the next time this happens, you can fix this without needing my help.  But please drop me a note so I can update the auto detection code.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelnext.dramanovels.io/nw/cultivation-online-novel

For my notes: 21 minutes work

**Comment by Flwk** [comment]
Thank you very much !

**Comment by dteviot** [comment]
@Flwk 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
