### ISSUE TITLE
Please add site https://www.bqka.cc/

### ISSUE THREAD

**Issue by Alastorwill** [dteviot/WebToEpub#1399]
Please to add this site

**Comment by dteviot** [comment]
@Alastorwill 

Seems to be same layout as shw5.cc

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.bqka.cc/book/3315/, chapter 1

For my notes:  8 minutes work

**Comment by dteviot** [comment]
@Alastorwill 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
