### ISSUE TITLE
Advanced Options button

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#14]
(note for self)
Put "Advanced Options" button to right of progress bar.
Button is only visible if Parser advertises that it has advanced options.
If clicked, additional options are put on dialog.
e.g.
- [x] Fetch Highest Resolution images. (default on)
- [x] ~~Add List of source URLs to end of ePUB. (default off)~~ No need for this to be visible to most readers.  Instead is encoded in &lt;source&gt; elements in contents.opf.
- [x] URL for cover image
- [x] Optional stylesheet
- [x] Include source URL in images (default on)
- [x] Move "Remove Duplicate Images" to advanced options. (default off)
- [x] ~~Setting needed for retrying on non 404 error pages (default off) and allowing setting of max retries (default 3)~~ Proved too difficult to implement.  Instead, tell user there was problem and give option to retry

Also note
- [x] Setting need to be saved to localStorage so they can be remembered. between invocations.
- [x] ~~Also, need to preserve settings when generator updates itself from Chrome store.~~ Seems to do this automatically.

**Comment by dteviot** [comment]
Following have been implemented
- Optional stylesheet.  (Note is not currently saved to local storage.)

**Comment by belldandu** [comment]
Updated this issue to use task lists @dteviot

**Comment by belldandu** [comment]
Need to move 
Remove Duplicate Images: 

Cover from URL:

to advanced options btw as they havent been moved in 0.0.0.11

**Comment by belldandu** [comment]
https://github.com/dteviot/WebToEpub/issues/22 is part of Remove Duplicate Images
See also https://github.com/dteviot/WebToEpub/issues/13 for my comment on adding an option for retying on non critical errors (such as error pages that aren't 404) and setting a max amount of retries.

**Comment by dteviot** [comment]
@typhoon71 @dreamer2908@toshiya44
Latest commit to https://github.com/dteviot/WebToEpub/tree/AdvancedOptions
I would appreciate it if you'd take it for a test drive.  Thanks.

added UserPreferences saved to local storage.

* Remove Duplicate Images from Image Gallery (defaults to false)
* Stylesheet
* Store URL of image as SVG description. (defaults to true)  Should fix https://github.com/dteviot/WebToEpub/issues/22
* Fetch highest resolution image.  (defaults to true)

**Comment by typhoon71** [comment]
UserPreferences works on chrome, well done.
Not storing the link of images is working (workaround for sumatra nad others).
I'm cleaning up/rebuilding my firefox profile so testing there is out for a while, sorry.

I noticed that I get a white page here: "https://www.baka-tsuki.org/project/index.php?title=Chronicle_Legion:Volume_1"; also, the tab with nation names is cut in two (brutally), with a cut in the middle of a line. Nothing else spotted.

**Comment by dteviot** [comment]
@typhoon71 

> I'm cleaning up/rebuilding my firefox profile so testing there is out for a while, sorry.
No problem.  I'm grateful for whatever you can do.

> I noticed that I get a white page here: "https://www.baka-tsuki.org/project/index.php?title=Chronicle_Legion:Volume_1"; also, the tab with nation names is cut in two (brutally), with a cut in the middle of a line. Nothing else spotted.

I wanted to get the preferences in, so that you can try tweaking the <image> settings without me needing to do a rebuild of the extension.  Things to try;
[x] Allow setting the max height percentage.
[x] Use <img> elements, instead of svg <image>.  (I think this will work better on newer readers.)

**Comment by typhoon71** [comment]
Oh, new options to play with, nice.

Btw: now I have no issue with "https://baka-tsuki.org/project/index.php?title=The_Unexplored_Summon_Blood_Sign:Volume1&printable=yes", which was the one I had issues before (white pages and cut images).

I'm curious on how tabs can be treated when they don't fit on a single page...

**Comment by toshiya44** [comment]
Tested the new options and features, I don't see any issue so far. Thanks for the "Fetch highest resolution image" option.
(Tested on Firefox 49.0a2, non-e10 window)

**Comment by dteviot** [comment]
@typhoon71 

> I'm curious on how tabs can be treated when they don't fit on a single page...

Me too.  I didn't think I'd made any changes there.  Another item to add to my ToDo list.

@toshiya44 
> Tested the new options and features, I don't see any issue so far

Thank you.
> Thanks for the "Fetch highest resolution image" option.

Actually, it's been fetching the highest resolution image for some time.  (That was the second change belldandu made to the code.)  I prefer the lower res images.  Quicker to download, and significantly smaller epub file.  The change was for me, it's really a "fetch reduced resolution images", by turning it off.  :)

**Comment by toshiya44** [comment]
Yup, low res images looks fine when I'm reading on phone and doesn't take up too much space. It's great :D

**Comment by dteviot** [comment]
@toshiya44 @typhoon71 
Advanced Options now has "Include list of fetched URLs"
If checked, adds a "chapter" to end of EPUB that is a table listing the URLs that were collected to make the EPUB.
Can you please try it out and suggest improvements.  (Or should I scrap it?)
For your information, the (long term) plan is to support being able to automatically update an epub with new chapters.
i.e. You drop the old EPUB file onto Web to Epub, and it then checks the chapter list for new chapters, and if found, creates a new EPUB, adding the new chapters to it.

**Comment by typhoon71** [comment]
I'll test it tomorrow, but I can make some suggestions.
- does it takes note of the editable forms? Like the title, author, chapters names, filename? It would be a good idea to recover all of those from the loaded epub, so one doesn't have to edit manually again.
- how does it work with handmade chapter lists? does it just import the existing links, and one can add the new content? 
- instead of a chapter you could add the list into the metadata, or did you make the chater non readable by the reader?
- bakatsuki: here an automated update would be great: expecially for partially translated volumes, since right now it's all manual work (before they publish the full text)

As of now, I use to do lists of customized links + chapter names... and paste into the urls fetched by web to epub: so NO, don't scrap this idea! It's a good one, really.

**Comment by toshiya44** [comment]
>For your information, the (long term) plan is to support being able to automatically update an epub with new chapters.

I think it's best left as a comment in a specific file or in a text file inside the epub. Readers don't need to see this.

>i.e. You drop the old EPUB file onto Web to Epub, and it then checks the chapter list for new chapters, and if found, creates a new EPUB, adding the new chapters to it.

Will it be able to *update* an epub as well? For example, redownloading the chapters in an epub based on the list of URLs?

**Comment by dteviot** [comment]
@typhoon71 @toshiya44 I've created https://github.com/dteviot/WebToEpub/issues/145 specifically for the Automatically Update EPUB feature.  What I'd like to know is if you think there's any value in the user being able to see the list of fetched URLs (chapters and images.)  Toshiya has explicitly said He doesn't think there's value in readers seeing the information, and I think typhoon implies it with his comment 
> instead of a chapter you could add the list into the metadata, or did you make the chapter non readable by the reader

i.e. This information should not be visible to user.

**Comment by typhoon71** [comment]
Good, the extra data being hidden is good.
Btw, since the goa is to update an epub, I suppose it'll create a new file, so if something goes wrong there's stil lthe old file.

**Comment by dteviot** [comment]
Looks like I should use &lt;source&gt; metadata elements for associating content with original URLs.
```XML
    <element name="source">
      <ref name="OPF20.optional-id-attribute"/>
      <ref name="OPF20.optional-xml-lang-attribute"/>
      <ref name="DC.metadata-common-content"/>
    </element>

**Comment by dteviot** [comment]
Source URL for each item recorded in <source> elements in contents.opf.
