### ISSUE TITLE
Please Update Parser to Include Author Notes --> https://storyseedling.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1401]
Hello! I would like to request for an update to the parser for site "**https://storyseedling.com/**" to include Author Notes at the bottom of some chapters, which the current settings do not account for, thereby wholly omitting the related text past the configured range of content to grab.

Example TOC: https://storyseedling.com/series/187426/

Example with Author Notes [**Chapter 10**]: https://storyseedling.com/series/187426/10/

Example Image of what Author Notes look like (please refer to the text ensconced within the red box): 
![image](https://github.com/user-attachments/assets/af8be02e-c434-4dbb-8bca-c3212497092a)

Thank you!!!! xx

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Tricky, there's nothing to explictly tag an element as holding an author's notes.
Best I can do, if there's a second element with a "mb-4" style, assume it's an author note.  And we all know what they say about assumptions.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://storyseedling.com/series/187426/10/

For my notes: 32 minutes work

**Comment by plsbenice-immadeofjelly** [comment]
Thank you!!! It still worked out well and was able to grab the author notes precisely!! Not much else was affected, I think, since only a select few elements contained the "mb-4" style (from what I gathered in the html source data) :D

...tho I might trace back to this issue if I notice something off with the format in a different epub (albeit it's only probable kek~)

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
