### ISSUE TITLE
1 Sec/Chapter

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#1405]
I keep getting banned from https://69shuba.cx/index.html because the download speed is too fast. And 3 Secs/Chapter takes too long.

**Comment by gamebeaker** [comment]
@Iadders you can set [Max web pages to fetch simultaneously](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#max-web-pages-to-fetch-simultaneously) to 2 or 4.

**Comment by Iadders** [comment]
> @Iadders you can set [Max web pages to fetch simultaneously](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#max-web-pages-to-fetch-simultaneously) to 2 or 4.

Huh, that works. 
Still pretty slow, but it will do. Thanks.

**Comment by gamebeaker** [comment]
@Iadders as a warning you could have this problem #1359 i am not sure if these sites are the same.

**Comment by gamebeaker** [comment]
#1094 would also solve it.

**Comment by Charity29614** [comment]
make it 1.5 seconds, one second will probably be too short

**Comment by Kiradien** [comment]
For the time being, I'm marking this as completed - but not yet deployed. The dev version of WebToEpub has 69shuaba's parser set to default 1 second minimum as mentioned in #1378 - if it becomes a problem in the future with this version in use, we can change that minimum period.

Note: the 1-second minimum is designed to work with default settings, and may require rollback on simultaneous settings.

**Comment by gamebeaker** [comment]
@Kiradien why can't you run lint locally?

**Comment by gamebeaker** [comment]
You can download the latest compiled versions here: [https://github.com/dteviot/WebToEpub/actions](https://github.com/dteviot/WebToEpub/actions)
For example the latest commit is this [https://github.com/dteviot/WebToEpub/actions/runs/10300694773](https://github.com/dteviot/WebToEpub/actions/runs/10300694773) and under Artifacts is a zip wich contains both compiled versions [https://github.com/dteviot/WebToEpub/actions/runs/10300694773/artifacts/1789920348](https://github.com/dteviot/WebToEpub/actions/runs/10300694773/artifacts/1789920348)

**Comment by dteviot** [comment]
@Iadders 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
