### ISSUE TITLE
Close issues

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#1406]
These are a few issues that i think can be closed.

Here are 3 issues with the same request i would close 2 and only keep one:
https://github.com/dteviot/WebToEpub/issues/172
https://github.com/dteviot/WebToEpub/issues/613
https://github.com/dteviot/WebToEpub/issues/998

abandoned:
https://github.com/dteviot/WebToEpub/issues/566
https://github.com/dteviot/WebToEpub/issues/881
https://github.com/dteviot/WebToEpub/issues/1316

not planed:
https://github.com/dteviot/WebToEpub/issues/746
https://github.com/dteviot/WebToEpub/issues/1162
https://github.com/dteviot/WebToEpub/issues/1173

fixed:
https://github.com/dteviot/WebToEpub/issues/55 ([readme.md](https://github.com/dteviot/WebToEpub/blob/ExperimentalTabMode/readme.md))
https://github.com/dteviot/WebToEpub/issues/173 (i think it is fixed [Add Information page to Epub](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#add-information-page-to-epub))
https://github.com/dteviot/WebToEpub/issues/251 (fixed with the [library](https://github.com/dteviot/WebToEpub/wiki/Library) function)
https://github.com/dteviot/WebToEpub/issues/279 (website doesn't exist anymore)
https://github.com/dteviot/WebToEpub/issues/383 (i think this is the current design)
https://github.com/dteviot/WebToEpub/issues/444 ([Additional Metadata URL](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#additional-metadata-url))
https://github.com/dteviot/WebToEpub/issues/812 (fixed with the [library](https://github.com/dteviot/WebToEpub/wiki/Library) function)
https://github.com/dteviot/WebToEpub/issues/997 (server slows down)
https://github.com/dteviot/WebToEpub/issues/1116 (server slows down)
https://github.com/dteviot/WebToEpub/issues/1146 (it is compatible)
https://github.com/dteviot/WebToEpub/issues/1361 (captcha got fixed)
https://github.com/dteviot/WebToEpub/issues/1332 (captcha got fixed)

**Comment by Kiradien** [comment]
Adding on to the above.
Fixed:
#1368 

Alternative Provided (Not Planned):
#1375 


If I find more, I'll edit this comment.

**Comment by dteviot** [comment]
@gamebeaker @Kiradien 
I have granted both of you authority, go ahead and close.

**Comment by gamebeaker** [comment]
As i don't want this to become another abandoned issue i am going to close it.

**Comment by dteviot** [comment]
@gamebeaker 
Just want to say "thank you very much for your hard work."
