### ISSUE TITLE
Please add this site: botitranslation.com/

### ISSUE THREAD

**Issue by Charity29614** [dteviot/WebToEpub#1408]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

i see. well i hope you look into this. i kinda am addicted to this webnovel. also thanks for making this extension

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
botitranslation.com/book/19516-library-of-heaven-s-path-2-eternal-destiny

### Did you try using the Default Parser for the site?  If not, why not?
When using the default parser, and downloading the chapters as an epub. when checking out the epub. for some reason the only thing that got downloaded for the epub is everything but the actual "text" of the story.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

this is the URL for the first chapter: https://www.botitranslation.com/chapter/1599309-chapter-1-stableman
i have no idea what that CSS stuff means, never used it before. so i guess I'm using the default settings.

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

i have absolutely no experience with javascript. i can barely code in Unity.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

i wish i had such a magical friend. that said. wanna be friends??

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
i didn't

**Comment by dteviot** [comment]
Notes.

Had a quick look, looks doable.
1. Wrong URL for ToC page.  https://www.botitranslation.com/book/19516-library-of-heaven-s-path-2-eternal-destiny
2. Need to make REST calls to get content for chapters.

Chapter 3 URL is https://www.botitranslation.com/chapter/1599311-chapter-3-the-scolding-horse
REST URL is https://api.mystorywave.com/story-wave-backend/api/v1/content/chapters/1599311

Chapter 4.  URL is https://www.botitranslation.com/chapter/1599328-chapter-4-yu-xiaoyu
Content is https://api.mystorywave.com/story-wave-backend/api/v1/content/chapters/1599328

Time spent: 22 minutes

**Comment by dteviot** [comment]
@Charity29614 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.botitranslation.com/book/19516-library-of-heaven-s-path-2-eternal-destiny, chapters 1 and 2
* https://www.botitranslation.com/book/19522-golden-core-is-a-star-and-you-call-this-cultivation, chapters 1 and 2

Time taken: 71 minutes (total)

Aside: I did not know there was a sequel to "Library of Heaven's Path"

**Comment by Charity29614** [comment]
![Screenshot_20240812_094553](https://github.com/user-attachments/assets/fb48b300-4441-41ae-be29-dc51f7fcba4e)
![Screenshot_20240812_094431](https://github.com/user-attachments/assets/f8ef613a-3800-4ea9-b4fd-ffa2c4b7d71c)
![Screenshot_20240812_094439](https://github.com/user-attachments/assets/304d3d03-aa1c-4f04-a5f5-defccb96bccf)

FIRST IMAGE:
I installed the chrome extension on my kiwi browser (android app).
SECOND IMAGE:
Went to the source TOC (table of content) page of library of heaven's path and clicked web2epub. 
THIRD IMAGE:
But no chapters showed up in web2epub.

**Comment by Charity29614** [comment]
However it does work on my Brave browser (Brave is like Chrome without ads) on my laptop.
![works](https://github.com/user-attachments/assets/c26482ca-b780-42a5-8ad6-912554787f2e)

can you make it work on mobile too (it works everytime in mobile with all the other parsers).

**Comment by dteviot** [comment]
@Charity29614 
The most likely reason it's not working on a mobile device is because your browser has told the site it's a mobile device, and the site has returned web pages formatted differently to a desktop browser.  And WebToEpub doesn't know how to handle this format.
The solution is to set your mobile browser to tell the site that it is a desktop device.
And no, I'm not going to code WebToEpub to handle both mobile and desktop formats, because that would more than double my work.

**Comment by Charity29614** [comment]
Wow that actually worked!
![Uploading Screenshot_20240813_033604.jpg…]()


![Screenshot_20240813_033614](https://github.com/user-attachments/assets/7887f61c-58a1-40df-a0e7-869cd6e5a6b8)

Thanks alot.

**Comment by dteviot** [comment]
@Charity29614 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
