### ISSUE TITLE
Add some tags for better search result ranking in AMO

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#141]
I noticed that the extension doesn't have many tags in Firefox AMO. You can add some tags related to WebToEpub so that people have a easier time finding it.
Currently the extension doesn't come up when I search for `ebook`, but I think it should.

I suggest these tags `articles, book, ebook, epub, html2epub, htmltoepub, download, converter, productivity`. But you can add more related tags.

**Comment by dteviot** [comment]
Done.
