### ISSUE TITLE
https://helheimscans.com/ add site?

### ISSUE THREAD

**Issue by Sev3nHeads** [dteviot/WebToEpub#1412]
Hi. 
Helscans.org changed to (https://helheimscans.com/).
The site is fully revamped and the extension not working. 
Is there a chance of supporting it again?
Thanks

**Comment by dteviot** [comment]
@Sev3nHeads 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://helheimscans.com/series/376ef410a8g/, chapter 1
* https://helheimscans.com/series/199b8de4703/, chapter 1

Time taken: 38 minutes

**Comment by Sev3nHeads** [comment]
Thank you. It works fine now.

**Comment by dteviot** [comment]
@Sev3nHeads 
Reopen, so I know to notify you when Chrome and Firefox stores are updated.

**Comment by dteviot** [comment]
@Sev3nHeads 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
