### ISSUE TITLE
Please add site Second Life Translations or create parser to remove gibberish parts from this site

### ISSUE THREAD

**Issue by TimeLimit67** [dteviot/WebToEpub#1415]
Hello. I hope this message finds you well.

I am not sure if the issue I've raised is redundant but I'll just put it up.

There's no problem extracting chapters from Second Life Translations. However, there are gibberish parts. Like this chapters 1-29.3 of Dwarf in the Future.

![Screenshot 2024-08-11 085753](https://github.com/user-attachments/assets/8da9b5c6-63ad-4819-b415-e22cb330de6b)

**Link:** https://secondlifetranslations.com/novel/dwarf-in-the-future/

I tried using EpubEditor and using the button for Clean Chrysanthemum Garden, hoping maybe the anti-aggregators setting of CG might be the same with second life. But it did not solve the issue. I don't know what to do with this one. If I miss something or if this issue was already solved or something, please let me know.

Please help. Many thanks in advance.

**Comment by gamebeaker** [comment]
@TimeLimit67 

Please see https://github.com/dteviot/WebToEpub/issues/683 for solution

**Comment by TimeLimit67** [comment]
Hello. I am grateful for the reply. 
Thank you very much. The js code worked like magic. Thanks for the patience and have a wonderful day/night ahead.

**Comment by dteviot** [comment]
@TimeLimit67 

Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.
