### ISSUE TITLE
Better way of showing download progress

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#142]
Currently shows progress in downloading chapters with progress bar and setting value in the "Loaded" column from "No" to "Yes".  This doesn't work very well, as
1. Change in the column is too subtle for most to notice.
2. When there are 100's of chapters, progress bar is not very good at showing how much is left in absolute terms.

 @typhoon71, @toshiya44
Suggested fix: Change the color of the URLs as they're downloaded.
I've made this change to the Experimental Tab branch.  Do you think it's a good solution or not.
If not, can you make a better suggestion?

**Comment by typhoon71** [comment]
Tested with WMW (1000+ chapters), seems fine to me.
You could also colore the undone chapters, for example in orange, so the it's more clear that's the status of the link/download.

My suggestion would be a counter near the bar, like "x of n chapter downloaded".
Maybe a bit oldschool... but you can use fancy fonts and blur effects! XD

**Comment by dteviot** [comment]
Thanks.

**Comment by toshiya44** [comment]
I think colored icons would be a much better for indicating changes. (e.g red cross mark to indicate failure/network error, green checkmark for success, an icon similar to the sync/update button for indicating "in progress" etc). 

Color alone don't work very well, specially if a person is colorblind, or has a non-default color configuration on their browser.

As typhoon71 mentioned, displaying "x of n chapter downloaded" would be nice as well.

**Comment by typhoon71** [comment]
I second the colored status symbol/icon idea.

**Comment by Maradar** [comment]
Don't know why but this error started to show:
```
TypeError: Cannot set property 'textContent' of null
    at Function.updateText (chrome-extension://elafmbgpoefkmamjicnfbcgdnegeoofk/js/ProgressBar.js:36:63)
    at Function.setValue (chrome-extension://elafmbgpoefkmamjicnfbcgdnegeoofk/js/ProgressBar.js:17:21)
    at chrome-extension://elafmbgpoefkmamjicnfbcgdnegeoofk/js/Parser.js:244:29
    at <anonymous>
```

Also maybe because of that the buttons for Edit chapter as well as Reverse chapter stopped working completely.

**Comment by dteviot** [comment]
@Maradar 
Well, that's embarrassing, somehow I managed to leave part of the previous commit out.
Has been fixed now.

**Comment by Maradar** [comment]
@dteviot 
You created and are maintaining this great addon so Thank you.
Problems here and here are bound to happen. :-D

**Comment by dteviot** [comment]
@toshiya44 @typhoon71 
Added icons for "in progress" and "download successful".
Have not added for "failure" due to fact error handling is asynchronous and complicated.
Also, if fetch of web page fails, plugin stops at that point.

**Comment by toshiya44** [comment]
Tested on https://frozensama.blogspot.ca/p/majo-no-tabitabi-jo.html 
Didn't notice any errors.

**Comment by dteviot** [comment]
@toshiya44 thank you.  Calling this done.

**Comment by typhoon71** [comment]
Just a small detail: with pages full of images, for example galleries, the checkmark appears when it's still downloading. I'm pretty sure it always was like that, and it's really minor, but if you feel like doing it... I won't stop you!

**Comment by dteviot** [comment]
@typhoon71 You're absolutely correct.  Will need to fix.

**Comment by dteviot** [comment]
@typhoon71 
Checkmark should now appear when images for page have been downloaded.
