### ISSUE TITLE
Can't extract the chapters from Chaleuria

### ISSUE THREAD

**Issue by TimeLimit67** [dteviot/WebToEpub#1422]
Hello. I hope your morning sunshine is lovely and warm.

I don't have problems making epub from Chaleuria before. However, when I tried making an epub of the novel **The Complete Guide to the Use and Care of a Personal Assistant** just now, no chapters appeared. The links for each chapter in the site were working properly. They aren't dead links.

**To Reproduce**
1. Go to` https://chaleuria.com/complete-guide-personal-assistant/`.
2. Activate WebToEpub browser extension.
3. The error appears here. 

Not even a single chapter appeared even though the links in TOC page is working. In other words, I can't extract chapters thus rendering me unable to make an epub.

![Screenshot 2024-08-12 092204](https://github.com/user-attachments/assets/79e48fe4-2653-4bc4-8eb2-d39b7283c7cd)

 - Windows 11
 - Google Chrome (same thing happened when I tried in Firefox)
 - WebToEpub 0.0.0.161

Please let me know if I made a mistake. Many thanks in advance.

**Comment by dteviot** [comment]
@TimeLimit67 

Sorry, closed by mistake when merged fix from ImLJS

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* Untested.  I trust ImLJS

Time taken: 5 minutes

**Comment by dteviot** [comment]
@TimeLimit67

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
