### ISSUE TITLE
Please add site https://genesistudio.com 

### ISSUE THREAD

**Issue by nandakishore2009** [dteviot/WebToEpub#1423]
Hi.
https://genesistls.com is changed to https://genesistudio.com
The site is fully revamped and the extension not working.
Is there a chance of supporting it again?
Thanks

**Comment by dteviot** [comment]
@nandakishore2009 
Sorry, site is doing things to disable the site when it detects dev tools being used.  This makes it difficult to write a parser for the site.  I could probably work around by using Fiddler, but to me it's not worth the effort.

Time taken: 14 minutes

**Comment by gamebeaker** [comment]
It looks like they use this here to prevent it: [https://github.com/theajack/disable-devtool](https://github.com/theajack/disable-devtool)
To prevent this js from loading you can block it with uBlock Origin. I blocked this url and it looks like it works: `https://genesistudio.com/_app/immutable/chunks/disable-devtool*`

**Comment by dteviot** [comment]
@gamebeaker 

Thank you for your efforts.  Unfortunately, the Google rules are that Chrome extensions are not allowed to circumvent copyright protection measures. And I suspect the site is doing this for at least partly this reason.

So, not going to support this site in version released to stores.  But might do it for the experimental builds.  Will take a look at the site for curiosity's sake.

**Comment by dteviot** [comment]
@gamebeaker 

For my future reference, how did you figure this out?

**Comment by dteviot** [comment]
Looking at the network traffic now.
To get content for a chapter, is POSTing a REST call, to https://analytics.genesistudio.com/api/send with URL in the JSON "/viewer/723", which is same as the hyperlink for chapters.  But there's other stuff in the payload.  But it looks like the response is encrypted.  So, this is another site where you'd probably need to load each page normally, let the browser unscramble the text and then extract it.

So, not going be able to handle this site.  It's job for a different tool.

**Comment by gamebeaker** [comment]
@dteviot  I first tried to open dev tools -> that didn't work (I used the shortcut CTRL+Shift+E to open them).  I googled how to detect dev tools open and found this [https://stackoverflow.com/questions/7798748/find-out-whether-chrome-console-is-open/24327093#24327093](https://stackoverflow.com/questions/7798748/find-out-whether-chrome-console-is-open/24327093#24327093) answer. 
I realized that
To test if this method is used i prevented the console from clearing in firefox 
![image](https://github.com/user-attachments/assets/150dd05e-cf23-44df-82dd-c9c64590df95)
After opening the page the console looked like this.
![image](https://github.com/user-attachments/assets/4ac9c807-bbf0-46f0-91b4-18fd6b408fdc)
At the bottom is this link [https://theajack.github.io/disable-devtool/404.html?h=genesistudio.com](https://theajack.github.io/disable-devtool/404.html?h=genesistudio.com) I went to his github and found this tool: [https://github.com/theajack/disable-devtool](https://github.com/theajack/disable-devtool)
I enabled persisten logs in the network tab of the dev tools 
![image](https://github.com/user-attachments/assets/b3fb5d89-0b73-4c8e-9b0a-5fd1871c5bbd)
I searched the Network requests after disable-devtool and found the network request: [https://genesistudio.com/_app/immutable/chunks/disable-devtool.min.DS0Hrg-C.js](https://genesistudio.com/_app/immutable/chunks/disable-devtool.min.DS0Hrg-C.js) I am not sure if the end DS0Hrg-C is dynamic. That is why the uBlock Origin filter is `https://genesistudio.com/_app/immutable/chunks/disable-devtool*`

**Comment by gamebeaker** [comment]
@dteviot 
> Looking at the network traffic now. To get content for a chapter, is POSTing a REST call, to https://analytics.genesistudio.com/api/send with URL in the JSON "/viewer/723", which is same as the hyperlink for chapters. But there's other stuff in the payload. But it looks like the response is encrypted. So, this is another site where you'd probably need to load each page normally, let the browser unscramble the text and then extract it.
> 
> So, not going be able to handle this site. It's job for a different tool.

I don't think it is encrypted. In my opinion it doesn't get the content from the api but a nomal get request from the Chapter url [https://genesistudio.com/viewer/1099](https://genesistudio.com/viewer/1099) but it is similar to #1403 reaperscans.com as in it is buried in script elements.

**Comment by gamebeaker** [comment]
@nandakishore2009 Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://genesistudio.com/novels/yar
* https://genesistudio.com/novels/nw

**Comment by dteviot** [comment]
@nandakishore2009 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
