### ISSUE TITLE
Please add site: https://veyrithele.me/

### ISSUE THREAD

**Issue by yuyu-cloud** [dteviot/WebToEpub#1425]
Hello. Although I'm aware that this site does not yet have many novels since it's a new source, they do release content frequently, so I came to ask for the possibility of adding support to this source early on. Also, the protections on this site are rather stringent and the html source data is a bit messy to specifically select only certain elements without pulling in any excess.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://veyrithele.me/2024/07/26/are-you-ok-english-translations/**

### Did you try using the Default Parser for the site?  If not, why not?
Yes I did. But, the output was still extremely messy because there are numerous "div" tags with similar attributes. When using the Default Parser, Webtoepub generally only selects the first occurring element containing that pinpointed attribute. But, owing to the sheer number of elements which include the same attributes, it was difficult to manuever Webtoepub to effectuate a decrease in the pull of redundant source data.

Also, based on the TOC link given above, the relevant content that I wanted to output into the epub was from the **main heading** at the very top of the page and stops at the "form" element, which is wrapped around the text [**Novel Suggestions**]. The element I had selected below for the "body content" in the Default Parser did achieve this, but the volume of "div" tags wrapped wtihin even more "div" tags was just really disorderly...

**Main Heading:**

![image](https://github.com/user-attachments/assets/130996de-8ea4-4122-a742-f2bd9fc6aabf)

**Where to Configure the Stopping Point in the Parser:**

![image](https://github.com/user-attachments/assets/9c3889c8-48a3-4b94-9904-3879f14580bc)

### What settings did you use?  What didn't work?
* URL of first chapter: **https://veyrithele.me/2024/07/26/chapter-1-medicated/**
* CSS selector for element holding content to put into EPUB: **div[data-elementor-type]**
* CSS selector for element holding Title of Chapter: **.elementor-heading-title**
* CSS selector for element(s) to remove: **.elementor-heading-title**

**Note:** The images on this site are also protected. This is a new copyright mechanism that I haven't seen on other sites before so I'm not sure if it's possible to bypass (kind of seems like a 404 error), but although the images can be viewed normally on the site itself, when Webtoepub extracts the protected image into the epub, all images are covered in the following text: "**WATERMARK**", multiple occurrences of the "**www.mywebsite.com**" and "**This image is protected**". 

![image](https://github.com/user-attachments/assets/b96f0ec2-6963-4537-8a38-ca8f6dfa607f)

Hoping there is a fix to these issues with your assistance, thank you~

**Comment by dteviot** [comment]
@yuyu-cloud 

I'm a little confused.  I just tried the site and WebToEpub seems to handle it fine.
Note, it selected the Wordpress parser for the site.  
* So, if you're getting the default parser, you will need to open the "Advanced Options" and on the "Manually Select Parser" dropdown, select "Wordpress".
* You might also like to try using the latest test version.  It's possible there's been a fix somewhere.

**Comment by yuyu-cloud** [comment]
@dteviot

Hello! The options I had input for the Default Parser seemed to have achieved the same output, as with manually selecting "Wordpress". But I can probably make do with the numerous "div" tags if there's no workaround to decreasing their pull into the epub.

Though, regarding the images problem on this site, is there no way to bypass it? Because all images are still outputted with the "WATERMARKS" since they're protected files. If it's not doable to remove this protection mechanism, I'll close this issue since using the Default Parser was just as workable haha~ Thank you for your assistance :)

**Comment by dteviot** [comment]
@yuyu-cloud 
> Though, regarding the images problem on this site, is there no way to bypass it?


The Google rules are that Chrome extensions are not allowed to circumvent copyright protection measures.  Doing so will get the app banned.

**Comment by yuyu-cloud** [comment]
@dteviot 

Ah yes I'm aware. Apologies for not being clear enough. I meant not through Webtoepub's parser directly. As in **post-output** by using ePubEditor to somehow clean the protected images of all three watermarks that I had mentioned? Just wondering if there was a writable method to wipe all images clean of the protective text currently defacing the overall quality via ePubEditor :)

**Comment by gamebeaker** [comment]
@dteviot @yuyu-cloud it looks like you get different images depending on the headers sent. If you set the referer header to https://veyrithele.me you receive the right image. Example with curl: `curl --header "Referer: https://veyrithele.me" https://veyrithele.me/wp-content/uploads/2024/07/51FBvGjKimL.jpg -o image.jpg` downloads the right image i am not sure how to implement this.

**Comment by dteviot** [comment]
@yuyu-cloud 

Probably a bit of a manual process.
1. Browse to page with normal web browser.
2. Save the image to a file
3. Unzip the epub, and replace the images with the new ones.
4. Zip up the epub again.

Note, steps 3 and 4 could be done with something like Calibre.
IIRC, WebToEpub records where the image files come from in the Epub's opf file.  Which is in XML format.
So, someone could probably make a tool that reads the opf file, fetches the image using the correct referrer value, and then replaces image file in Epub.

**Comment by dteviot** [comment]
Or, could hack the Firefox version of WebToEpub to set the referrer when requesting images.  Can't do it for Chrome, due to needing extra permissions, but the Firefox version already has them.

**Comment by yuyu-cloud** [comment]
@gamebeaker @dteviot Thank you both for your assistance. Since the images were quite few in number, I did indeed opt to go for the manual route and just edited the images by reverting them back to their original state by directly sourcing them from the site :)
