### ISSUE TITLE
Please add site https://novelsemperor.net/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#1426]
pls add https://novelsemperor.net/

TQ

**Comment by ImLJS** [comment]
Fixed in PR. #1427

**Comment by dteviot** [comment]
@Finks82 

Reopen, so I can notify you when version in Chrome and Firefox stores updated.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* untested by me.

**Comment by gille90** [comment]
worked yesterday. today I got this warning:

TypeError: Failed to construct 'URL': Invalid URL     at HttpClient.setPartitionCookies (chrome-extension://gahdmbhclblmpkfffkjfechmnjeojail/js/HttpClient.js:212:29)     at HttpClient.wrapFetchImpl (chrome-extension://gahdmbhclblmpkfffkjfechmnjeojail/js/HttpClient.js:181:26)     at HttpClient.wrapFetch (chrome-extension://gahdmbhclblmpkfffkjfechmnjeojail/js/HttpClient.js:155:27)     at NovelsemperorParser.walkTocPages (chrome-extension://gahdmbhclblmpkfffkjfechmnjeojail/js/Parser.js:707:37)     at async NovelsemperorParser.getChapterUrls (chrome-extension://gahdmbhclblmpkfffkjfechmnjeojail/js/parsers/NovelsemperorParser.js:12:17)

**Comment by dteviot** [comment]
@Finks82 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
