### ISSUE TITLE
Please add site https://novelsect.com

### ISSUE THREAD

**Issue by mikan01** [dteviot/WebToEpub#1428]
Can you please add https://novelsect.com?

Thanks.

**Comment by dteviot** [comment]
@mikan01 

Site crashed when I was looking at it.
Notes.
* To get chapter list, make REST GET call to URL like https://novelsect.com/api/fetchchapterlist?novelId=51&page=2
* Don't yet know how to get novelId.  Note that response returns 100 chapters, plus totalChapters and totalPages.
* Possible title selector: "div.text-2xl"
* Possible content selector: "main"
* Site lacks explicit tags for many elements.

Time so far: 25 minutes.

**Comment by mikan01** [comment]
The site was working now and I tried to use the possible CSS selector you provided, but it didn't work. Thanks for your time and effort, really appreciate it,

**Comment by dteviot** [comment]
@mikan01 
I haven't finished yet.  Just could not progress with site not working.

**Comment by dteviot** [comment]
@mikan01 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelsect.com/novel/wen3jian4xiu1xian1-zheng3ge4xiu1xian1jie4dou1shi4wo3jia1, chapters 1, 52, 162

Note, you will need to browse a chapter to two until the Cloudflare "are you a human" appears, before WebToEpub will be able to download content.

Time taken: 178 minutes (total)

**Comment by mikan01** [comment]
Thank you, it worked now. :)

**Comment by dteviot** [comment]
@mikan01 
Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
