### ISSUE TITLE
Edit chapter URL button broken

### ISSUE THREAD

**Issue by Maradar** [dteviot/WebToEpub#143]
Hello,

I am trying to edit chapter list through button but when I press it there are no links just empty window.
After pressing Apply changes the whole chapter list is empty.

For now I tried it only with lnmtl.com.

P.S.: I am using the latest version from Github, ExperimentalTabMode branch.

**Comment by dteviot** [comment]
@Maradar 
Should now be fixed.
Sorry for the problem.
Thank you for telling me about it.
