### ISSUE TITLE
Mtlarchive is denying the access 

### ISSUE THREAD

**Issue by Legendoras** [dteviot/WebToEpub#1432]
**Describe the bug**
Mtlarchive.com is denying the access of web to epub and I can't download the book 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [ Redmi 5]
 - OS: []
 - Browser [ firefox nightly , kiwi browser ]
 - Version []

**Additional context**
Whenever I try to convert the web book in e pub , the site denies the access

**Comment by gamebeaker** [comment]
@Legendoras what is the link of the Website?

**Comment by Legendoras** [comment]
https://mtlarchive.com/novel/super-academic-master-start-with-the-return-of-teaching

**Comment by dteviot** [comment]
@Legendoras 

Site is using cloudflare.
1. Use the latest test build of WebToEpub.
2. You'll need to browse a few chapters until the Cloudflare "are you a human" appears.  Then WebToEpub will work.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://mtlarchive.com/novel/super-academic-master-start-with-the-return-of-teaching, chapters 1, 2, and 3

**Comment by Kiradien** [comment]
Adding a note here: The pre-release version just released, referenced [here](https://github.com/dteviot/WebToEpub/releases/tag/developer-build) has a change for this specific issue, and should minimize future occurrence. Otherwise, I'd suggest setting the Throttle to 3 seconds in Advanced Options.

**Comment by dteviot** [comment]
@Legendoras 
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers.

**Comment by dteviot** [comment]
@Legendoras 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
