### ISSUE TITLE
Chrome 403 errors on Cloudflare - Cont.

### ISSUE THREAD

**Issue by Kiradien** [dteviot/WebToEpub#1444]
This is a continuation of #1439 - said bug is fixed for mtlarchive, but other sites are still problematic. As the main site mentioned has been fixed, I am raising a separate issue for other domains still having said issues.

Domains in question:
Fanfiction.net
Scribblehub.com - Actually still generates, but still missing cf_clearance, it will likely  fail during high load periods.

Chromium Ticket: https://issues.chromium.org/issues/361862746

Note, the current fix also results in a variety of errors showing up in the dev console, however these are relatively easy to fix once we have a permanent solution:
![image](https://github.com/user-attachments/assets/27646120-d079-49d4-90a3-67b7b235fdc8)

@gamebeaker - poking you on this since you found the initial solution and while MTLArchive is fixed, issues persist. 

Feel free to add other domains where this issue persists in the comments, I will try to keep the above list up to date.

**Comment by gamebeaker** [comment]
@Kiradien i think i found and fixed the problem. I explained it here: #1445
Keep issue open for a few days maybe there are more problems with 403.

**Comment by gamebeaker** [comment]
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://www.fanfiction.net/s/14168168/1/Fairy-Tail-The-Complete-Series

**Comment by dteviot** [comment]
@Kiradien 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
