### ISSUE TITLE
Automatically Update EPUB with new chapters

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#145]
The (long term) plan is to support being able to automatically update an epub with new chapters.
i.e. You drop the old EPUB file onto Web to Epub, and it then checks the chapter list for new chapters, and if found, creates a new EPUB, adding the new chapters to it.

@typhoon71 commented
>* does it takes note of the editable forms? Like the title, author, chapters names, filename? It would be a good idea to recover all of those from the loaded epub, so one doesn't have to edit manually again.
>* how does it work with handmade chapter lists? does it just import the existing links, and one can add the new content?
>* instead of a chapter you could add the list into the metadata, or did you make the chapter non readable by the reader?
>* bakatsuki: here an automated update would be great: expecially for partially translated volumes, since right now it's all manual work (before they publish the full text)
>* As of now, I use to do lists of customized links + chapter names... and paste into the urls fetched by web to epub: so NO, don't scrap this idea! It's a good one, really.

@toshiya44 commented
>* I think it's best left as a comment in a specific file or in a text file inside the epub. Readers don't need to see this.
>* Will it be able to update an epub as well? For example, redownloading the chapters in an epub based on the list of URLs?

**Comment by dteviot** [comment]
@typhoon71 @toshiya44

> does it takes note of the editable forms? Like the title, author, chapters names, filename?

It will

> how does it work with handmade chapter lists?

I haven't thought about that.

> instead of a chapter you could add the list into the metadata

Noted.

> bakatsuki: here an automated update would be great: expecially for partially translated volumes, since right now it's all manual work (before they publish the full text)

This seems related to https://github.com/dteviot/WebToEpub/issues/98.  Do you want to put more details there?

> Will it be able to update an epub as well?

That should be possible.

Note, at this point in time, this entire "Auto Update" feature is NOT something I promise to do.  It's pretty low on my priority list.  I only raised the issue because I was closing out the items in https://github.com/dteviot/WebToEpub/issues/14, and keeping track of the list of downloaded URLs was a necessary prerequisite for this feature.

**Comment by typhoon71** [comment]
Yes, I basically bumped up #98, which I opened. ;)
If you do it we'll be grateful, but we won't hate you if you don't: personally I'm really happy about this addon, I can't really ask for more... but if it happens I won't refuse! ;)

**Comment by dteviot** [comment]
Using Reading List feature (track last chapter collected for a web novel) with MergeWebToEpub (https://github.com/dteviot/MergeWebToEpub) provides what amounts to the same functionality.
