### ISSUE TITLE
How to warn people about viruses/ malware?

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#1456]
In the last few days there were multiple comments which posted links to malware etc.
example: https://github.com/dteviot/WebToEpub/issues/1454#issuecomment-2325651144 https://github.com/dteviot/WebToEpub/issues/1449#issuecomment-2310494826 https://github.com/dteviot/WebToEpub/issues/1447#issuecomment-2309464912

@xypha got lucky that his browser warned him. In the other examples was the virus encrypted in a zip to prevent these type of warnings.

@MoonShadowIllusion wrote that his account got hacked and he is sorry, as i can't find his comment and account anymore i guess he got banned.

Does anyone has an idea how to warn people?
Maybe a warning to only download from the github release page in readme?

@xypha where would you like to see such a warning?

**Comment by xypha** [comment]
> where would you like to see such a warning?

@gamebeaker 
Not sure. A warning in readme may help.
also consider that download links to external sites in GitHub comments are not rare - not even in this repo (example: download link to [GDrive](https://github.com/dteviot/WebToEpub/issues/1323#issuecomment-2126776646) containing zip files).

**Comment by gamebeaker** [comment]
@xypha thanks for your feedback the link to gdrive was in the past now the new test versions can be downloaded on github here: [developer-build](https://github.com/dteviot/WebToEpub/releases/tag/developer-build)

**Comment by gamebeaker** [comment]
As there where no new malware links i am going to close it and hope it was an irregularity.

**Comment by gamebeaker** [comment]
[Theo - t3.gg](https://www.youtube.com/@t3dotgg) made a video about this issue:
https://www.youtube.com/watch?v=34UDLyf94oA
