### ISSUE TITLE
systemtranslation.com Parser Broke + 69Shuba Change

### ISSUE THREAD

**Issue by X-Xadro** [dteviot/WebToEpub#1458]
URL Tested: https://systemtranslation.com/series/dragon-ball-god-mu/

Result: 
![2024-09-04 03_35_08-WebToEpub](https://github.com/user-attachments/assets/a17e3fbc-b038-48a1-9f5e-2114dc1a1e2d)

URL Tested: https://69shu.me/book/44386.htm

The domain for 69Shuba changed again, but the parser still works, however the chapter list is in reverse order.

Also shown in that screenshot is that it adds the Novel main overview page to the chapter list:

`<a href="https://69shu.me/book/44386.htm">你管这叫幕后黑手？目录</a>`
`<a href="https://69shu.me/txt/44386/31277804">完本感言</a>`
`<a href="https://69shu.me/txt/44386/31277733">第396章 所谓不朽（大结局）</a>`
`<a href="https://69shu.me/txt/44386/31272337">第395章 突如其来的权柄</a>`

![2024-09-04 03_39_02-WebToEpub](https://github.com/user-attachments/assets/8aac3722-478a-419f-9c00-2c003f1002af)

The 69Shuba is a small thing because you can reverse the list order with the button and just uncheck the novel main page from the chapter list. But since i was posting an issue anyway....

Thanks for your hard work!

**Comment by gamebeaker** [comment]
@X-Xadro Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://systemtranslation.com/series/dragon-ball-god-mu/ (Chapter 1-3)

**Comment by dteviot** [comment]
@X-Xadro 
In future, please create separate issue for each site.  Makes keeping track of the work easier when it can't all be done at once.

@gamebeaker, 
FWIW, we can probably remove the SystemTranslationParser.  Anything using the eplister should be able to be handled by NoblemtlParser now.

**Comment by X-Xadro** [comment]
@gamebeaker Tested it and both work, thanks!

@dteviot Will do!

**Comment by gamebeaker** [comment]
@X-Xadro is this https://github.com/dteviot/WebToEpub/issues/1359 still a problem?

**Comment by X-Xadro** [comment]
@gamebeaker 
> @X-Xadro is this #1359 still a problem?

A couple days ago i re-downloaded the novel which i had issues with before because it had new chapters and just now I checked a couple chapters, including the one that was broken for me last time. And it was exactly like on site itself. So it seems to be 'fixed'

A while ago they also had a different protection where they pasted your IP address in the chapters if you used a downloader to get the story. So i guess they are experimenting or the site changes hands with every domain change lol

**Comment by dteviot** [comment]
@X-Xadro 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
