### ISSUE TITLE
69SHU URL Changed to 69shu.me

### ISSUE THREAD

**Issue by steve30990** [dteviot/WebToEpub#1459]
69shu URL has changed from www.69shuba.cx to
https://69shu.me

Parser needs to be updated with the correct URL. Thanks

**Comment by gamebeaker** [comment]
@steve30990 The url should still open the right parser. I changed the logic to fetch chapters like described here #1458 in this commit: #1460

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by gamebeaker** [comment]
@steve30990 is this #1359 still a problem?
