### ISSUE TITLE
Please add site https://genesistudio.com/novels/cfz

### ISSUE THREAD

**Issue by Wonkie-wow** [dteviot/WebToEpub#1462]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Default Parser was tried and did not work quite exactly, with the parser only scraping ~8 random chapters out of 200+
Sometimes would scrape chapters 1-8, other times scraping 170-178, or 230-238.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by Wonkie-wow** [comment]
Attempting to create a parser

**Comment by dteviot** [comment]
@Wonkie-wow 
Duplicate.  https://github.com/dteviot/WebToEpub/issues/1423 might be helpful for you.

**Comment by gamebeaker** [comment]
@Wonkie-wow Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://genesistudio.com/novels/yar
* https://genesistudio.com/novels/nw
