### ISSUE TITLE
Please add site https://fictionzone.net

### ISSUE THREAD

**Issue by Franzeeee** [dteviot/WebToEpub#1463]
Can you please add https://fictionzone.net parser. This is just the new domain for the mtlarchive.com. Thank you.

**Comment by gamebeaker** [comment]
@Franzeeee thanks for the tip, that it is the same as mtlarchive.com

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://fictionzone.net/novel/my-identity-as-the-first-emperor-was-exposed-by-a-strange-princess (Chapter 1-3)

**Comment by dteviot** [comment]
@Franzeeee 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
