### ISSUE TITLE
Please add site https://novellive.app

### ISSUE THREAD

**Issue by jvthomas90** [dteviot/WebToEpub#1469]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://novellive.app/book/doctor-player but since the TOC is paginated only 40 chapters are shown per list before you have to click next i.e. navigate from https://novellive.app/book/doctor-player/1 to https://novellive.app/book/doctor-player/2 and then /3 and /4 and so on in order to see the rest

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

I did. At first I failed miserably because I misunderstood how to identify CSS selectors 😅 Pretty sure I have a good grasp of it now though, but in the process of figuring this all out I realized that not only does NovelLive.com and later on NovelLive.net exist but also that both of these have been added to WebToEpub already in the past.

However when I try to invoke WebToEpub from the "main" TOC page on those sites I still run into an error since it seems that any subsequent /2 /3 /4 etc TOC navigations as well as the navigations to chapter pages themselves automatically redirect the URL from .com and .net to the .app variant domain instead. 

And NovelLive.app isn't currently supported by the extension _(which is what started my journey into educating myself on how to identify CSS selectors started in the first place)_

### What settings did you use?  What didn't work?
* URL of first chapter
    * https://novellive.app/book/doctor-player/chapter-1
* CSS selector for element holding content to put into EPUB
    * div.txt
* CSS selector for element holding Title of Chapter
    * span.chapter _(although I'm pretty sure leaving this out should work too since the chapter title is also included as an h4 header within the div.txt)_
* CSS selector for element(s) to remove
    * div.top _(is it possible to add multiple elements to this field? If so, I'd also like to add div.chapter-end , ul.ul-list7 and a.error too)_

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

Only just saw these instructions as I was writing up this feature request! So I'm actually going to try just that soon after this is submitted

No "dev skills" though, full disclosure, so I'm just gonna try to see what I can do with the .com and .net templates (if/assuming they exist) and see if I can adapt it for the new .app domain if it isn't too troublesome to figure out and accomplish on my own.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

I suppose... that was why I opened up this feature request? Aside from whatever advice or assistance I can get on here (either from the dev or anyone else in the community who subsequently comments with suggestions or solutions) I don't think I have anyone in my IRL sphere of influence who could really help me with it tbh

**Comment by gamebeaker** [comment]
@Franzeeee thanks for the tip, that it is the same as NovelLive.net i only needed to add one line because of this tipp.

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://novellive.app/book/doctor-player/ (Chapter 1-3)

**Comment by jvthomas90** [comment]
Sweet! 🥳 That was way quicker than I thought lol, and just a one line fix to boot 😂

Can confirm that the latest dev-build update successfully detects and downloads the TOC contents of NovelLive.app for me as well, thanks! 👍🏽

**Comment by gamebeaker** [comment]
@jvthomas90 Reopen to notify you when version in Chrome store is updated.

**Comment by jvthomas90** [comment]
Whoa, why such a massive bump in the new version number??

**Comment by gamebeaker** [comment]
@jvthomas90 it is a new numbering scheme look: #1410
