### ISSUE TITLE
Create better documentation for WebToEpub

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#147]
Use https://github.com/blog/2233-publish-your-project-documentation-with-github-pages to create Help and FAQ documentation for WebToEpub.
Topics to be covered.
- [x] How to use "Edit Chapter URLs" to easily select a range of URLs to include in EPUB.
- [x] How to configure the Default Parser for a new site.
- [x] How to use Network in the developer tools to view download progress.
- [x] Limitations of automatic selection between Baka-Tsuki "Full Page" and "Series Page" parsers.  And how to use "Manually Select Parser" to correct when WebToEpub gets it wrong.
- [x] Structure of WebToEpub (for anyone who wants to work on it.)
- [x] How to add a new parser.

**Comment by dteviot** [comment]
@typhoon71, @toshiya44 
I've started putting together a FAQ for WebToEpub at: https://dteviot.github.io/Projects/webToEpub_FAQ.html.
You feedback would be greatly appreciated.
e.g. 
1. What additional items need to be added to the FAQ?
2. How to make existing items better?  (Obviously, I need to do the ToDos, but it's a work in progress.)

**Comment by toshiya44** [comment]
> Privacy Policy
> WebToEpub potentially exposes some of your web browsing history. Specifically:

Should be "WebToEpub **uses** some of your web browsing history to perform various functions"

There should be a few more point stating the following (please rephrase as necessary, I'm not very good at this):

* The collected information does not go to the author of WebToEpub and does not leave the browser/extension's data files. Only the list of downloaded items' URLs will stay inside the ePub file if you enable the option to do so.
* Although WebToEpub does not use any analytics, the sites you vist may track which pages you download.

----------------------------

>How to select a sub-range of URLs to include in an EPUB?

I think an explanation of the format of the URL list should be included in here, which is `<a href="URL_TO_DOWNLOAD">Title</a>` and that the order of the URLs is the same as the order in which they are displayed in the book.

---------------------------

> How to convert a new site using the Default Parser?

The general outline would be something along the lines of:

1. Use the "Dom Inspector" of the browser of your choice. (Add a very short instruction on how to open and use it. e.g `CTRL+Shift+C` in Firefox)
2. Go to the very beginning of the text.
3. Check for an HTML element that encloses the entire piece of text you want in the book and note its class/id.
4. Enter the element name and class/id in the relevant fields in WebToEpub and see if it works.

**Comment by dteviot** [comment]
@toshiya44, thanks.

**Comment by typhoon71** [comment]
A little suggestion, non mandatory ;) 

"Only the list of downloaded items' URLs will stay inside the ePub file if you enable the option to do so."
This should became:

"Only the list of downloaded items' URLs will stay inside the ePub file and only if you enable the option to do so (disabled by default)."

The double use of "only" makes clear the URL list is the only thing that wil be written to the epub, and only if the extension is set to do so by the user.

You could add something about "full source available on github... " and so on.

**Comment by dteviot** [comment]
@typhoon71 
Thanks for the feedback.

> "Only the list of downloaded items' URLs will stay inside the ePub file and only if you enable the option to do so (disabled by default)."

I think you're referring to the "Include URL of Images" option.  However, even if that is unchecked, I'm still writing URLs into the EPUB.  This suggests a need for a couple of privacy options.  i.e 
- "Don't write URLs into the EPUB", and 
- "Don't store Default Parser settings".

However, not putting URLs into the EPUB requires significant re-writing of WebToEpub, and it's a somewhat pointless exercise as the EPUB has the CONTENT from the web site anyway.  So,
1. Looking at the content gives someone a much better idea of a user's preferences than the URLs. And,
2. The URLs could be found by putting chunks of the text into Google.

**Comment by dteviot** [comment]
I'm a retard. https://gist.github.com/alphamu/c42f6c3fce530ca5e804e672fed70d78

**Comment by toshiya44** [comment]
I don't think it has to be that formal, but you can import some items and terminology from there.

**Comment by dteviot** [comment]
@toshiya44, @typhoon71
Revised privacy policy https://dteviot.github.io/Projects/webToEpub_PrivacyPolicy.html
I hope you find it entertaining.
