### ISSUE TITLE
Just a missing tag and declaration

### ISSUE THREAD

**Issue by Saladitas** [dteviot/WebToEpub#1474]
Missing doc type Declaration in toc.xhml file.
``<!DOCTYPE html>``

Missing title tag in toc.xhml file.
Missing ``<title></title>`` tags within ``<head></head>``, should be ``<head><title></title></head>``

Seems to a general thing that affects all EPUBs. Tested on Royal Road and Scribble Hub.

**Comment by dteviot** [comment]
@Saladitas 

1. Should be simple to fix, but it may be a few weeks before the version in the Chrome and Firefox stores is updated and available.
2. Until this is fixed, you could get WebToEpub to create Epub v2 files.
3. Is this actually causing a problem?

**Comment by Saladitas** [comment]
It's not causing any actual problems when reading, I'm using my phone and the moon reader app.
The error comes up when I open the ePub file on my PC using Sigil, to clean up any text or fix some tags. It throws an error every time I open an epub file telling me the toc file is incorrectly formatted and that it needs to be mended.

It's not a super big problem tbh, I just thought I would bring it up.

**Comment by dteviot** [comment]
@Saladitas 

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://ntruyen.vn/truyen/ta-hoa-naruto-gioi-ninja-muoi-tu-deu-bi-hu-53844.html

Time taken: 36 minutes

**Comment by dteviot** [comment]
@Saladitas 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
