### ISSUE TITLE
https://novelfire.docsachhay.net/home

### ISSUE THREAD

**Issue by BJZ3k** [dteviot/WebToEpub#1485]
Linking and example with the table of contents. 
https://novelfire.docsachhay.net/book/the-regressed-son-of-a-duke-is-an-assassin/chapters

Would appreciate the whole site in general to be added. Thank you for all your work and this awesome extension.

Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by Displayeddd** [comment]
CSS selector for element holding content to put into EPUB: div#content
 
 CSS selector for element holding Title of Chapter: div#content p strong
 
 CSS selector for element(s) to remove: div.box-ads, p.box-notification

**Comment by dteviot** [comment]
@BJZ3k 

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelfire.docsachhay.net/book/untouchable-a-vrmmo-litrpg-manhwabook, chapters 1 and 2

Notes:
Time taken: 62 minutes  
I thought this would be easy, It's same layout as https://www.lightnovelworld.co/
Except, it's not quite the same.
* Chapter Content had different CSS
* Links in ToC did not have a .chapter-no element
* CSS for Summary is different and in base parser is a mess.

**Comment by dteviot** [comment]
@BJZ3k 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
