### ISSUE TITLE
Please add site https://botnovel.us/series/black-corporation-joseon/

### ISSUE THREAD

**Issue by Jokakun** [dteviot/WebToEpub#1492]
Please add the function to download translated chapters, because if we didn't do anything and directly click to the chapter, it is in korean.
There should be a button there that translates the chapter.

**Comment by Jokakun** [comment]
found a workaround

**Comment by dteviot** [comment]
@Jokakun 

Care to tell me what you did?  I just tried https://botnovel.us/series/debut-or-die/, and except for having problems downloading the cover image, it all worked.

**Comment by Jokakun** [comment]
https://botnovel.us/series/black-corporation-joseon/

For this series, I managed to download Chapter 378 - 1187 in english, but the last few chapters are in korean. Do you know what happened here? I just opened the site on one tab, then copied the title link on another.

**Comment by dteviot** [comment]
@Jokakun 
> For this series, I managed to download Chapter 378 - 1187 in english, but the last few chapters are in korean.

Try looking at the chapters in your browser normally.  If they appear in Korean (which they do for me) it's a problem with the site.  Send a message to the site owners.  Their contact details can be found at https://botnovel.us/contact-us/
