### ISSUE TITLE
Force the default parser to load instead.

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#1494]
Sometimes, webtoepub doesn't work on a site (such as Genesis Studio just now) despite having a parser, so I have to go into the zip and delete the included parser just so the manual one loads instead.

Can there be an option to load the default parser so we don't have to do this in the future?

**Comment by gamebeaker** [comment]
@Tenome you can select the default parser.
![image](https://github.com/user-attachments/assets/a4c8ee4e-d01d-4fc1-9d7b-8436fd425489)
Hint: for gegenesistudio.com i guess it will not work because there are api calls etc.

**Comment by Tenome** [comment]
Oh! My mistake, I didn't know that option was available. I'm stupid!

**Comment by gamebeaker** [comment]
@Tenome Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://genesistudio.com/novels/yar
* https://genesistudio.com/novels/nw

**Comment by dteviot** [comment]
@Tenome 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
