### ISSUE TITLE
69shuba Bug - crawling Error and Stopped Working

### ISSUE THREAD

**Issue by steve30990** [dteviot/WebToEpub#1498]
Hi, i 69shuba Crawling is Error
Ex Link: https://69shuba.cx/book/46781.htm

When Crawling on Chrome = It Directly shows
WebToEpub
WARNING: Site '69shuba.cx' has sent an Access Denied (403) error. You may need to logon to site, or browse site normally until you get a Cloudflare "Are you a human" page or satisfy some other CAPTCHA before WebToEpub can continue. Open Page?

When Crawling on 69shuba on Firefox
After a few minutes 
WebToEpub
WARNING: Site '69shuba.cx' has sent an Access Denied (403) error. You may need to logon to site, or browse site normally until you get a Cloudflare "Are you a human" page or satisfy some other CAPTCHA before WebToEpub can continue. Open Page?

Tried slowing down to 5 Sec per page =
WebToEpub
WARNING: Site '69shuba.cx' has sent an Access Denied (403) error. You may need to logon to site, or browse site normally until you get a Cloudflare "Are you a human" page or satisfy some other CAPTCHA before WebToEpub can continue. Open Page?

Slow Down to 10 Sec per Page = Shows
Error: Fetch of URL 'https://69shuba.cx/txt/46781/31216326' failed with network error 403. This is an intermittent error. If you retry in a few minutes, it may succeed. promptUserForRetry@moz-extension://699d03a2-177f-48d3-a47e-e62fca5f93b4/js/HttpClient.js:55:19
onResponseError@moz-extension://699d03a2-177f-48d3-a47e-e62fca5f93b4/js/HttpClient.js:48:25
checkResponseAndGetData@moz-extension://699d03a2-177f-48d3-a47e-e62fca5f93b4/js/HttpClient.js:201:45
wrapFetchImpl@moz-extension://699d03a2-177f-48d3-a47e-e62fca5f93b4/js/HttpClient.js:191:31

Macbook Pro M3
MacOS Sonoma Version 14.6.1
Brower: Chrome, Firefox

**Comment by gamebeaker** [comment]
@steve30990 unable to reproduce. I was able to download 50 Chapter in Chrome.
Did you solve the Captcha after you got the error?
What is your WebToEpub version?

**Comment by dteviot** [comment]
@steve30990 

Other thing to try, when error appears, try going to page with browser normally and see if get 403 error.  The page may give you more details.  Or, if you have dev skills, open Browser's Dev Tools on WebToEpub and look at the network traffic, in particular the full 403 response.

**Comment by steve30990** [comment]
I see this problem gone, after checking today, i think it was that day, 69shu updated their site, and cloudflare was relogin nonstop.

**Comment by steve30990** [comment]
It seem like its a issue just pops up again. Same at Chrome
Firefox i suppose will have issue like i mention above, but i think VPN can help Firefox crawl Temporarily.

Below image is Chrome WebtoEpub Version: 0.0.0.167

![IMG_0274](https://github.com/user-attachments/assets/adcc7abc-2cd6-4c06-a24d-80f34658a681)

**Comment by gamebeaker** [comment]
@steve30990 can you browse the page normally?

**Comment by gamebeaker** [comment]
@steve30990 i found the error it is the same as #1439. I tested with the latest test version while you have version 0.0.0.167
@dteviot as it is a cookie issue maybe release a new version to the chrome store as all user should be impacted.
@steve30990 you can use the test versions for Firefox and Chrome.
They have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@gamebeaker 
> maybe release a new version to the chrome store 

Yes, it's probably about time for a new release.  Before I do that, can you please check if it's still working on Firefox Android?  Site asks me to confirm I've checked, so I can tick the "Works on Android" box in the submission.  And I'd rather not lie about it.

**Comment by gamebeaker** [comment]
@dteviot i tested it in Android.

**Comment by dteviot** [comment]
@steve30990 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
