### ISSUE TITLE
null error on novel18.syosetu.com

### ISSUE THREAD

**Issue by asdfqwerty1029** [dteviot/WebToEpub#1499]
**Describe the bug**
When parsing a novel from novel18.syosetu.com, I see the following error in firefox:
```
dom.querySelector(...) is null fetchAndAttachInfoPage@moz-extension://160fc07a-34c6-417b-bf46-fc76ceb43f57/js/parsers/SyosetuParser.js:22:33
getChapterUrls@moz-extension://160fc07a-34c6-417b-bf46-fc76ceb43f57/js/parsers/SyosetuParser.js:13:20
onLoadFirstPage@moz-extension://160fc07a-34c6-417b-bf46-fc76ceb43f57/js/Parser.js:379:14
processInitialHtml@moz-extension://160fc07a-34c6-417b-bf46-fc76ceb43f57/js/main.js:48:24
populateControlsWithDom@moz-extension://160fc07a-34c6-417b-bf46-fc76ceb43f57/js/main.js:253:27
onMessageListener@moz-extension://160fc07a-34c6-417b-bf46-fc76ceb43f57/js/main.js:16:36
```
And a similar error in chrome:
```
TypeError: Cannot read properties of null (reading 'href')
    at SyosetuParser.fetchAndAttachInfoPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/SyosetuParser.js:22:81)
    at SyosetuParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/SyosetuParser.js:13:20)
    at SyosetuParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:379:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:48:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:253:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)
```

**To Reproduce**
1. Go to https://novel18.syosetu.com/ and choose a novel
2. Click on the webtoepub extension button

**Expected behavior**
The webtoepub tab should open with the parsed novel

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox (127.0.2), Chrome (129.0.6668.58)

Thanks very much for this extension, it has been very helpful on several sites!

**Comment by gamebeaker** [comment]
@asdfqwerty1029 i don't know japanese can you post a novel link? I don't find a novel on [https://novel18.syosetu.com/](https://novel18.syosetu.com/) only redirect links to https://yomou.syosetu.com/ or https://noc.syosetu.com/top/top/ etc.

**Comment by BeetleBobsai79** [comment]
same issue also happens on ncode.syosetu.com with any novel.

**Comment by asdfqwerty1029** [comment]
@gamebeaker sure thing, here are a couple of examples:
https://novel18.syosetu.com/n8333im/
https://ncode.syosetu.com/n6316bn/

**Comment by gamebeaker** [comment]
@asdfqwerty1029 @BeetleBobsai79 
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novel18.syosetu.com/n8333im/
* https://ncode.syosetu.com/n6316bn/

**Comment by asdfqwerty1029** [comment]
Thanks @gamebeaker, the new version works great!

**Comment by dteviot** [comment]
@asdfqwerty1029 @BeetleBobsai79 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
