### ISSUE TITLE
Metadata improvements

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#15]
Please add field to enter translator's name. 
Split author's name input field into lastname-firstname parts and update the way it's recorded in the opf.
`<dc:creator opf:file-as="last, first" opf:role="aut">first last</dc:creator>`
As for the translator's name:
`<dc:contributor opf:file-as="name" opf:role="trl">name</dc:contributor>`

Edit: Since there's no response from dteviot yet, I'll add one more metadata issue.
The meta cover tag has content before name.
Current:     `<meta content="image0000" name="cover"/>`
Should be: `<meta name="cover" content="image0000"/>`

**Comment by belldandu** [comment]
From what i've seen. Translator names much less author names are even on the volume pages. Even thinking about doing this requires loading of the main series page.

**Comment by toshiya44** [comment]
You misunderstood. I'm only asking for the fields to be added in the UI. I'll put the names by myself.

**Comment by belldandu** [comment]
Shouldn't be to hard. Gotta wait for #10 to be merged though.

**Comment by belldandu** [comment]
@toshiya44 i forgot about this. I apologize. This is the next thing on my todo list.

**Comment by dteviot** [comment]
There's a minor complication.  The parser tries to find the Author in the file (which isn't directly available for Baka-Tsuki in the main story text) and we really don't know what the order of names is.  And for many stories the Author's name is a single word.

**Comment by toshiya44** [comment]
@dteviot The author and translator's name can be directly inputted by the user. So the extension only has to get the input from the field and put them in a credit page or metadata.
>  And for many stories the Author's name is a single word.
True, and that creates some complications of what to do with the comma.
I think modifying author's name can wait. Including translator's name is more important and should be easier too, since it will be inserted in almost the same way as author's name but with a slightly different tag.

**Comment by belldandu** [comment]
This is low priority for me atm

**Comment by dteviot** [comment]
@toshiya44

In latest version (0.0.0.10). click on the "Advanced Options" button.
- Added field to supply "translator".
- Added field to supply author's "file-as"

>The meta cover tag has content before name.
>Current: <meta content="image0000" name="cover"/>
>Should be: <meta name="cover" content="image0000"/>

To the best of my knowledge, the order of attributes in an XML element is irrelevant.

Please let me know if this satisfies your request.

**Comment by dteviot** [comment]
@toshiya44, apologies for the spam, but is https://github.com/dteviot/WebToEpub/issues/15 fixed to your satisfaction?

**Comment by toshiya44** [comment]
Yup, it works as intended.
