### ISSUE TITLE
Please add site https://www.book18.org/

### ISSUE THREAD

**Issue by Sheolofdeath** [dteviot/WebToEpub#1501]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.book18.org/book/%E6%96%97%E7%BD%97%E5%A4%A7%E9%99%86%E2%80%94%E6%B0%B8%E6%81%92%E7%9A%84%E7%82%AE%E5%8F%8B

### Did you try using the Default Parser for the site?  If not, why not?
Yes I try it. But I don't like at every end of sentence always have book18.org, I don't know how to delete that.
Like this:
(一位少年站在一處傳送陣中，揮手向一位美婦人告別，少年英俊非凡，氣質出眾，正如陌上人如玉，公子世無雙。 book18.org

而美婦人穿著一件寬鬆的便衣，但卻衣衫不整，整件衣服滑落而下，將她那雄偉壯觀的大奶裸露在外，白嫩似雪的肌膚在陽光下閃爍著耀眼的光芒，婦人很美，如同一顆熟透的果實，美味而又多汁，柳眉杏眼櫻桃嘴，豐胸細腰蜜桃臀，好一個美艷絕倫的美婦人。 book18.org)
Conversion error message was: (But Warning, unable to convert chapter '斗羅大陸—永恆的炮友(1-3)作者：零零碎碎' from 'https://www.book18.org/17660' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. )

### What settings did you use?  What didn't work?
* URL of first chapter (https://www.book18.org/17660)
* CSS selector for element holding content to put into EPUB (div.content)
* CSS selector for element holding Title of Chapter (li.list-group-item)
* CSS selector for element(s) to remove 

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
I don't understand how to do that.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I don't have friend that can do that.

**Comment by dteviot** [comment]
@Sheolofdeath 
It's Chinese (which I don't know), and I can't figure out how to get page with a table of contents for a story.  If you can provide a link to such a page, I'll take another look.

**Comment by Sheolofdeath** [comment]
Here:
https://www.book18.org/book/%E5%8F%8D%E6%B4%BE%EF%BC%9A%E6%88%91%E7%9A%84%E6%AF%8D%E4%BA%B2%E6%98%AF%E5%A4%A7%E5%B8%9D
https://www.book18.org/book/%E6%96%97%E7%BD%97%E5%A4%A7%E9%99%86%E2%80%94%E6%B0%B8%E6%81%92%E7%9A%84%E7%82%AE%E5%8F%8B#new

**Comment by X-Xadro** [comment]
@Sheolofdeath 

This seemed to work for me, it also removed the `book18.org` that's after each paragraph

Hostname: `www.book18.org`
URL of first chapter: `https://www.book18.org/119678`
CSS selector: `div#content`
CSS Title: `h1.title py-1`
CSS Remove: `span.d-none`

It seems to be correct but you would have to read the full chapter to make sure though

I checked both your links but there doesn't seem to be any watermarks.

**Comment by gamebeaker** [comment]
@X-Xadro tanks for the help.

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*https://www.book18.org/book/%E6%96%97%E7%BD%97%E5%A4%A7%E9%99%86%E2%80%94%E6%B0%B8%E6%81%92%E7%9A%84%E7%82%AE%E5%8F%8B#new
but not really tested because i don't know chinese, it looks right to me.

**Comment by Sheolofdeath** [comment]
Thanks, it's working.

**Comment by dteviot** [comment]
@Sheolofdeath 

Reopen, so I know to notify you when Chrome and Firefox stores are updated.

**Comment by dteviot** [comment]
@Sheolofdeath @X-Xadro 
Updated version (1.0.0.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
