### ISSUE TITLE
Create github issues semi automatic

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#1510]
**Is your feature request related to a problem? Please describe.**
In the chrome/ firefox store are reviews that site xy isn't supported.
![image](https://github.com/user-attachments/assets/59108aed-367d-4f52-b40c-f1d7906b1a8a)
Is it written somewhere that they can request new sites in github? (I think there is a disconnect between the user and that issues should be reported in github.) 

**Describe the solution you'd like**
It is possible to create new issues in github with a link.
Example:
https://github.com/dteviot/WebToEpub/issues/new?title=foo&body=bar
or open the template
https://github.com/dteviot/WebToEpub/issues/new?assignees=&labels=&projects=&template=add-site-request.md&title=Please+add+site+https%3A%2F%2F%3F%3F%3F%3F
The Solution would be to create an option in WebToEpub to automatically create the Context of the issue. (The title for the issue gets generated dynamically from which site the user opened WebToEpub)

![image](https://github.com/user-attachments/assets/1a4dde82-081a-4310-8b89-95b810bff869)

**Describe alternatives you've considered**
More hints in the chrome/ firefox store descriptions that issues/ new site requests should be reported on github.

**Comment by dteviot** [comment]
The obvious downside of this is we will get more requests from people to add parsers, without them even **trying** to help themselves.

**Comment by gamebeaker** [comment]
@dteviot you are right if they press help it redirects to github.
I am closing it as not planned.
