### ISSUE TITLE
Please add site https://m.88xiaoshuo.net

### ISSUE THREAD

**Issue by etn3912** [dteviot/WebToEpub#1517]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://m.88xiaoshuo.net/Partlist/98781/

### Did you try using the Default Parser for the site?  If not, why not?
Yes I did. The default parser works but it only accounts for single pages. To get the link of chapters from other pages you much manually copy the chapter links and paste them together.

### What settings did you use?  What didn't work?
* URL of first chapter - https://m.88xiaoshuo.net/Partlist/98781/152850617.shtml
* CSS selector for element holding content to put into EPUB - div.content
* CSS selector for element holding Title of Chapter - #chapter > h1
* CSS selector for element(s) to remove - n/a

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
I tried but I am not sure if my parser didn't work or I just didn't do it right.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I tried developing a parser myself but I couldn't get it to run. 

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
[m_88xiaoshuo_net - Copy.js.txt](https://github.com/user-attachments/files/17157177/m_88xiaoshuo_net.-.Copy.js.txt)

**Comment by gamebeaker** [comment]
@etn3912 Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://m.88xiaoshuo.net/Partlist/98781/
* https://m.88xiaoshuo.net/Partlist/52664/

**Comment by etn3912** [comment]
I just tested it. It works fine for the most part but, it only captures the current chapter list page.

**Comment by gamebeaker** [comment]
@etn3912 can please report a problematic link?
What is your browser? Operating system?
I tested it with:
https://m.88xiaoshuo.net/Partlist/98781/
https://m.88xiaoshuo.net/Partlist/98781
https://88xiaoshuo.net/Partlist/98781/
https://88xiaoshuo.net/Partlist/98781
they all work for me.
Hint go to: https://m.88xiaoshuo.net/Partlist/98781/ -> click WebToEpub -> it should load 1520 Chapters

**Comment by etn3912** [comment]
@gamebeaker 
go to: https://m.88xiaoshuo.net/Partlist/98781/ -> click WebToEpub -> it should load 1520 Chapters
I did this ^ but it shows 50 chapters

can please report a problematic link?
What is your browser?  - Chrome Version 129.0.6668.70 (Official Build) (64-bit)
Operating system? - Win 10


"To use it navigate to the full chapter list from the book link:
https://m.88xiaoshuo.net/book/98781/
to
https://m.88xiaoshuo.net/Partlist/98781/
and start WebToEpub without further navigation."
I just tried this suggestion, it still didn't work.

**Comment by gamebeaker** [comment]
@etn3912 what is your browser? Operating system?

**Comment by gamebeaker** [comment]
@etn3912 as another point you need to have the page in the original language not translated to english.
Why?
It gets the last Chapter list link from "尾页" if you have it translated it can't find it because it is "Last page" instead of "尾页" and it can't find it.

**Comment by etn3912** [comment]
@gamebeaker Got it. Yes the first solution works for me. I previously had it "always translate to English".  Let me give that a try. Btw if I create a parser do I need to add the file name somewhere?

**Comment by gamebeaker** [comment]
@etn3912 yes in popup.html at the end are all parser.js files listed. The are sorted.
https://github.com/dteviot/WebToEpub/blob/8bd11887c8a4d913714aa8799cf89ca553f1d441/plugin/popup.html#L533-L540

**Comment by etn3912** [comment]
@gamebeaker 
I modified the 88xiaoshuoParser that you updated hoping to work for the following:
"m.shuhaige.net", () => new _ShuhaigeParser()); - not working
m.xpaoshuba.com" - works
m.ttshu8.com" - works
"m.ilwxs.com" - works
"m.qbxsw.com" - not working
"m.38xs.com" - not working

"not working" meaning only captures 50 chapters currently on the page.

[ShuhaigeParser.js.txt](https://github.com/user-attachments/files/17171861/ShuhaigeParser.js.txt)

**Comment by gamebeaker** [comment]
test urls:
https://m.88xiaoshuo.net/Partlist/208802/
https://88xiaoshuo.net/Partlist/208802/
https://m.ttshu8.com/book/111495/
https://www.ttshu8.com/book/111495/
https://m.xpaoshuba.com/Partlist/211883/
https://www.xpaoshuba.com/Partlist/211883/
https://m.shuhaige.net/266994/
https://m.qbxsw.com/du_201845/
https://m.38xs.com/267117/

problems:
http://m.ilwxs.com/
![image](https://github.com/user-attachments/assets/ca3e6c72-4f56-44ce-8e55-32ba8c86027e)
@etn3912 is the url right?

**Comment by gamebeaker** [comment]
@etn3912 Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@etn3912 

Updated version (1.0.1.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours (typical) to 21 days.
