### ISSUE TITLE
Please add site https://m.shuhaige.net

### ISSUE THREAD

**Issue by etn3912** [dteviot/WebToEpub#1522]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://m.shuhaige.net/228600/

### Did you try using the Default Parser for the site?  If not, why not?
Yes. It only captures first page. The rest has to be manual

### What settings did you use?  What didn't work?
* URL of first chapter - https://m.shuhaige.net/276319/104887699.html
* CSS selector for element holding content to put into EPUB - div.content
* CSS selector for element holding Title of Chapter - h1.headline
* CSS selector for element(s) to remove - n/a

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Done. Doesn't do well.

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
[ShuhaigeParser.js.txt](https://github.com/user-attachments/files/17171976/ShuhaigeParser.js.txt)

**Comment by gamebeaker** [comment]
@etn3912 Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
