### ISSUE TITLE
Download fails when "Do Not Track" turned on for Chromium 65.0.3319.0 (Maybe)

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#153]
Since some time in chrome webtoepub doesn't save the ebook in .epub format, and just saves a .zip file, like "87e21119-6006-46b3-ad31-5ace57ddb5e1.zip".
I noticed that at the same time ffox56 started to ask for filename when saving epubs with webtoepub.
Any idea if it's a bug?

**Comment by dteviot** [comment]
That sounds like https://github.com/dteviot/WebToEpub/issues/136. Are you running in incognito mode on Chrome?
The whole problem started when Firefox went multithreaded.  At that point, the code to "download" the aseembled EPUB stopped working. (it was a hack.)  However, the official API for doing it has different bugs on Chrome, Firefox and Firefox for Android.  So, it's become something of a mess.

**Comment by dteviot** [comment]
@typhoon71 
Are you confusing "do not track" https://www.techrepublic.com/article/how-to-enable-chrome-do-not-track-for-better-mobile-privacy/ with "incognito".  https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DDesktop&hl=en

Also, I thought I'd fixed the issue with incognito mode.  Can you confirm problem is related to "do not track"?  And exactly which version of browser and Web To Epub are you using?  I need to see if I can reproduce the problem, if it's re-appeared.

**Comment by typhoon71** [comment]
No, I'm not confusing "do not track" with "incognito" (but I understand why you asked) and I confirm the issue happens with "do not track" enabled.

I don't use "incognito" mode at all since I need to have my session saved nor I use the "do not track" option, since I do not trust websites to honor it.

I sometime do change option(s) on the browser(s) to test what actually changes,, forgetting to put it back after I'm done, like I did this time.

WebToEpub 0.0.0.45 on Chromium 65.0.3319.0 (Build) (32 bit) - W7 (64bit)

**Comment by dteviot** [comment]
@typhoon71 
I haven't been able to reproduce the problem with Chrome 65.0.3322.0 (Build) (32 bit)  (It's a chrome Dev branch build)
Note, that's not quite the same build you reported.
When you have some time, can you please
1. Confirm you can make the problem appear and disappear by toggling "do not track" on and off?
2. Confirm if problem still occurs if you use Chrome 65.0.3322.0
3. Give me the details to get Chromium 65.0.3319.0

Note, I'm having trouble understanding how turning on "Do not track" would impact the download operation, as all that "Do not track" is supposed to do is add an additional element to any HTTP headers Chrome sends to a server.

Thanks.

**Comment by typhoon71** [comment]
I can't do it right now, I will try as soon I get some spare time.

**Comment by dteviot** [comment]
@typhoon71

Any update?

**Comment by typhoon71** [comment]
Sorry, no update actually: I've been reall busy with my new job, and couldn't do any testing.

I accidentally delete my chromium profile too (overwritten actually), and with the new clean profile nothing happens, I mean I don't see any difference toggling "do not track" on or off.

Here's the link for Chormium builds: https://download-chromium.appspot.com/?platform=Win&type=continuous.
It should be a "last good one" kind of link, so I don't think I'll be able to get the same build.

Feel free to close this issue, if there isn't any good news on firefox side (the manual saving issue).

**Comment by dteviot** [comment]
@typhoon71 
Thanks very much for responding.  However, when you say:

> I mean I don't see any difference toggling "do not track" on or off.

I'm not sure if mean now "it works" or "it does not work"?

And good luck with your new job.

**Comment by typhoon71** [comment]
I meant the epub downloads fine.

**Comment by dteviot** [comment]
Great. Thanks. Closing.

**Comment by dteviot** [comment]
@typhoon71
Please see https://github.com/dteviot/WebToEpub/issues/191
In short, were you running any other extensions that effect downloads?

**Comment by typhoon71** [comment]
No, I'm not running extensions that effect downloads (on Chrome), only UBlock0 (and it whitelists addon space as far as I remember).
