### ISSUE TITLE
Not Compaible With Xen 1

### ISSUE THREAD

**Issue by Ariel-Schnee** [dteviot/WebToEpub#1533]
**Describe the bug**

It doesn't work when I try to download threadmarked things in XenForo 1. They were threadmaked with Threadsmarks Pro.

**To Reproduce**

https://www.fanficparadise.com/fpforum-sfw/index.php?threads/testing-the-threadmarks.26/#post-32

https://www.fanficparadise.com/fpforum-sfw/index.php?threads/testing-the-threadmarks.26/#post-32

https://www.fanficparadise.com/fpforum-sfw/index.php?threads/testing-the-threadmarks.26/#post-32

4. Click on the WebToEpub icon in browser.

5. See error

It just produces something I don't understand.

**Expected behavior**

I had expected it to put all the threadmarked post into an epub.

**Screenshots**

https://www.geocities.ws/arielschnee/gallery/FP-Ariel_Schnee/WebToEpub_Error_01.png

https://www.geocities.ws/arielschnee/gallery/FP-Ariel_Schnee/WebToEpub_Error_02.png

https://www.geocities.ws/arielschnee/gallery/FP-Ariel_Schnee/WebToEpub_Error_03.png

**Desktop (please complete the following information):**
 - OS: Windows XP Pro SP3 (32-bit)
 - Browser Mypal 68
 - Version 68.13.7b (32-bit)

**Smartphone (please complete the following information):**

I don't have a phone.

**Additional context**

I just want ti to work now.

**Comment by gamebeaker** [comment]
@Ariel-Schnee Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
tested with: https://www.fanficparadise.com/fpforum-sfw/index.php?threads/testing-the-threadmarks.26/#post-32
You have to display all links before opening WebToEpub:
![grafik](https://github.com/user-attachments/assets/65ef87de-cce2-4b6e-90c8-29646dbeb3b0)

**Comment by Ariel-Schnee** [comment]
It's working now.

I was using WebToEpub1.0.0.0.Firefox.zip, and didn't work well.

Now I'm using WebToEpub1.0.0.13.Firefox.zip, which does work.

**Comment by dteviot** [comment]
@Ariel-Schnee 

Updated version (1.0.1.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours (typical) to 21 days.

Again thanks to @gamebeaker and @Kiradien for the time they've spent looking into this.
