### ISSUE TITLE
Rename WebToEpub For Baka-Tsuki in firefox store

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#1534]
@dteviot In the firefox store https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/ is the name "WebToEpub For Baka-Tsuki"
![image](https://github.com/user-attachments/assets/6e89eb3a-8c86-48bd-a40f-613e374db0ec)
In the chrome store it is "WebToEpub" https://chromewebstore.google.com/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm
![image](https://github.com/user-attachments/assets/4eecda56-0133-4b77-96a9-388be438a608)
The request is to unify the names in the stores.
I would be for just "WebToEpub" as it supports more sites than just Baka-Tsuki

**Comment by dteviot** [comment]
@gamebeaker 
Not possible.  WebToEpub was already taken when I first tried to add it to the Firefox store.
WebToEpub was first created for Chrome.

**Comment by gamebeaker** [comment]
@dteviot ok is it now possible?
I can't find an WebToEpub addon https://addons.mozilla.org/en-US/firefox/addon/webtoepub/
So maybe they deleted it.

**Comment by dteviot** [comment]
@gamebeaker 
Whoops, closed by mistake.
Anyway, just went to Mozilla site, changed the name, and it seemed to be accepted.
Can I get you to visit the Mozilla store tomorrow and check if the name actually has changed?

**Comment by gamebeaker** [comment]
@dteviot worked.
![image](https://github.com/user-attachments/assets/de1ea8ee-7115-46ca-86ff-25742c8c8168)
