### ISSUE TITLE
CSS coding is appearing at the end of each chapter of the book.

### ISSUE THREAD

**Issue by SkyMoon-2020** [dteviot/WebToEpub#1535]
Whenever I download this book (https://www.novelupdates.com/series/my-dear-miss-medical-examiner/), at the end of each chapter, there's an issue with how it appears in most e-readers. I'm downloading it from this site: https://littlepandatranslations.com/my-dear-miss-medical-examiner/
![Screenshot 2024-10-02 004949](https://github.com/user-attachments/assets/50f07bb4-bbb0-4f06-b226-609f33b912a6)

The book looks normal in only two apps — Calibre ebook reader and Aquile Reader — but in other reading apps, especially mobile ones, the problem persists at the end of each chapter. I tried re-downloading the book to double-check, but I keep facing the same issue. Is there any way I can fix this?

Thank you.

**Comment by gamebeaker** [comment]
@SkyMoon-2020 what is the link from the book?
novelupdates.com doesn't host chapters.

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020 what is the link from the book? novelupdates.com doesn't host chapters.

I added the site in post my. Here it is : https://littlepandatranslations.com/my-dear-miss-medical-examiner/

**Comment by gamebeaker** [comment]
@SkyMoon-2020 thanks for the link. Can you be more specific which apps have the problem? I use calibre on pc and tolino on mobile and on both does it work fine.

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020 thanks for the link. Can you be more specific which apps have the problem? I use calibre on pc and tolino on mobile and on both does it work fine.

In mobile I use "ReadEra" Premium version , in that app I face this issue first. Then saw same thing in another E-reader app name : "eBoox". And in my desktop it's "Freda ebook reader". Basically, this thing is occurring in certain apps & looking normal in others. 
![Screenshots_2024-10-02-01-38-49](https://github.com/user-attachments/assets/a39e1177-b2b4-41e1-81c1-a05ecc6a8778)

**Comment by gamebeaker** [comment]
@SkyMoon-2020 As a fix in calibre you can just convert it to epub and it should be cleaned up.

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020 As a fix in calibre you can just convert it to epub and it should be cleaned up. Please let me know if it worked.

Yeah it worked for me. Thank you so much.
