### ISSUE TITLE
Difficulty with downloading the full book 

### ISSUE THREAD

**Issue by SkyMoon-2020** [dteviot/WebToEpub#1536]
I was trying to download books from this site: https://words81.wordpress.com/my-translations/. However, I can't seem to download them with all the chapters; there are always chapters missing from the content list or not showing up. I even tried using WordPress's default parser, but it didn’t work. Can you guide me on how I can download these books from this site without missing any chapters?

**Comment by gamebeaker** [comment]
@SkyMoon-2020 
Example: https://words81.wordpress.com/category/da-dang/
1. Load all Chapter on one page
![image](https://github.com/user-attachments/assets/1e8f3bce-0b61-404d-9848-666ac0a8413d)
2. Click WebToEpub
3. Advanced Options -> Manually Select Parser: -> Default
4. Change the required fields to these parameter:
Hostname:
`words81.wordpress.com`
URL of first chapter:
`https://words81.wordpress.com/2023/01/26/prologue/`
(required) CSS selector for element holding content to put into EPUB:
`article`
CSS selector for element holding Title of Chapter:
`.entry-title`
CSS selector for element(s) to remove:
`#jp-post-flair, footer, .entry-author, .entry-meta`
5. Click "Test" -> look at the preeview how a chapter would look like.
6. Click "Apply"
7. Scroll down to the Chapter list and click "Reverse Chapter URLs Order"
8. Deselect all "Chapter that aren't Chapter.
![image](https://github.com/user-attachments/assets/0c8242da-1fc3-4ab5-911f-1bef91374c29)
![image](https://github.com/user-attachments/assets/f301050e-e003-4b29-bf78-4cab34d53a14)
9. Pack EPUB

**Comment by SkyMoon-2020** [comment]
> 4\. `.entry-title`
I followed everything you mentioned here, but when I try to pack the EPUB, it’s not downloading the entire book. Instead, it’s only downloading one chapter at a time. Also, when I open them, they are showing up blank.

**Comment by gamebeaker** [comment]
@SkyMoon-2020 here is a video how it works for me:

https://github.com/user-attachments/assets/43bd4308-d7c7-412e-bd65-5de945923526

> Also can you write me "CSS selector for element holding content to put into EPUB", this part ? I just want to check if I'm writing it right or not.
You can test if the css selector wor or not with the "Test" button

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020 Example: https://words81.wordpress.com/category/da-dang/
> 
> 1. Load all Chapter on one page
>    ![image](https://private-user-images.githubusercontent.com/9269847/372941988-1e8f3bce-0b61-404d-9848-666ac0a8413d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODcwMTAsIm5iZiI6MTcyNzg4NjcxMCwicGF0aCI6Ii85MjY5ODQ3LzM3Mjk0MTk4OC0xZThmM2JjZS0wYjYxLTQwNGQtOTg0OC02NjZhYzBhODQxM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTYzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjMyOWRmMWIyZDdjYWMyNzRlMzVlYTkyMzhiZTA5ZGExNWY5OTE3ZjczZjFiYTI2NzRhMzMzZTdhYmQ2MjFiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cF-egZAsnd4SwyENMoXq0kxU48UphEUNDlfMhh9ERpg)
> 2. Click WebToEpub
> 3. Advanced Options -> Manually Select Parser: -> Default
> 4. Change the required fields to these parameter:
>    Hostname:
>    `words81.wordpress.com`
>    URL of first chapter:
>    `https://words81.wordpress.com/2023/01/26/prologue/`
>    (required) CSS selector for element holding content to put into EPUB:
>    `article`
>    CSS selector for element holding Title of Chapter:
>    `.entry-title`
>    CSS selector for element(s) to remove:
>    `#jp-post-flair, footer, .entry-author, .entry-meta`
> 5. Click "Test" -> look at the preeview how a chapter would look like.
> 6. Click "Apply"
> 7. Scroll down to the Chapter list and click "Reverse Chapter URLs Order"
> 8. Deselect all "Chapter that aren't Chapter.
>    ![image](https://private-user-images.githubusercontent.com/9269847/372944107-0c8242da-1fc3-4ab5-911f-1bef91374c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODcwMTAsIm5iZiI6MTcyNzg4NjcxMCwicGF0aCI6Ii85MjY5ODQ3LzM3Mjk0NDEwNy0wYzgyNDJkYS0xZmMzLTRhYjUtOTExZi0xYmVmOTEzNzRjMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTYzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGFkM2YwNDNhOGJkYjEyZGM0NzhiMTEyM2Y5Y2I3YTJlMjRhNDdjMGVlM2M3ZDIzZDA3OGJjY2U3YjIzZTA0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VvLCoNW48YBotsYEXclYSsupCd4OO7RgDMQrKQLRYsQ)
>    ![image](https://private-user-images.githubusercontent.com/9269847/372944335-f301050e-e003-4b29-bf78-4cab34d53a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODcwMTAsIm5iZiI6MTcyNzg4NjcxMCwicGF0aCI6Ii85MjY5ODQ3LzM3Mjk0NDMzNS1mMzAxMDUwZS1lMDAzLTRiMjktYmY3OC00Y2FiMzRkNTNhMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTYzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTZiNTBjYTM3YjhiZTIxYmYxMGRmNGNlNmVlN2VkMjU0YzQyMGE4NDMxMTc4YmVhZjFkZTM4NWFhNGQ4MzZhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9BQ0WtDKkvBheuw8PrCK3R7qU3hN7wutSLtjiYPn-sU)
> 9. Pack EPUB

Thank you so much. It worked me.

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020 here is a video how it works for me:
> 
>  2024-10-02.19-23-51.mp4 
> > Also can you write me "CSS selector for element holding content to put into EPUB", this part ? I just want to check if I'm writing it right or not.
> 
> You can test if the css selector wor or not with the "Test" button

Thank you so much for this! Actually, it was my mistake that it didn’t work the first time. I kind of missed the “Article” part. I retried with it, and it worked for both books. Thanks again, you’re truly a saviour! and sorry for the misunderstanding.

**Comment by dteviot** [comment]
@gamebeaker @SkyMoon-2020 
I wonder if putting together a YouTube video of how to do this might be useful?

**Comment by SkyMoon-2020** [comment]
> @gamebeaker @SkyMoon-2020 I wonder if putting together a YouTube video of how to do this might be useful?

Is this related to my issue? It's already solved. But If you want to post guide videos to help others with similar issues, I think that would be a nice idea. But then again, downloading books from these sites isn't exactly legal, so I'm not sure if it's alright to post them on YouTube. 😅 Nonetheless, you can still make guide videos.

**Comment by gamebeaker** [comment]
@SkyMoon-2020 i think the question is more like if a tutorial video would have helped you to solve the problem without help instead of written instructions https://github.com/dteviot/WebToEpub/wiki/FAQ#how-to-convert-a-new-site-using-the-default-parser

**Comment by SkyMoon-2020** [comment]
> @SkyMoon-2020 i think the question is more like if a tutorial video would have helped you to solve the problem without help instead of written instructions https://github.com/dteviot/WebToEpub/wiki/FAQ#how-to-convert-a-new-site-using-the-default-parser

Probably, yes. I'm from a non-tech background, so sometimes it gets harder to understand things, especially the part where I have to pick the CSS element. It works for me sometimes, but most of the time I have a hard time understanding which one to choose or what exactly to write. Written articles don't always work for me due to different structures and all, so yeah, video instructions are a bit more helpful. Although, in this case, my issue was pretty much solved with your written instruction once I added "Article" in the CSS element.
