### ISSUE TITLE
Could You Make This Version?

### ISSUE THREAD

**Issue by Ariel-Schnee** [dteviot/WebToEpub#1537]
Could you make a WebToHTML version of this?

**Comment by gamebeaker** [comment]
@Ariel-Schnee I don't really understand your request please elaborate.
Hint: you can use 7zip to extract a ".epub" file and there you can find one ".xhtml" file per chapter.

**Comment by Ariel-Schnee** [comment]
I mean could you make one that saves it all in a .html file instead of .epub?

**Comment by dteviot** [comment]
@Ariel-Schnee 
Are you asking for WebToEpub to read the multiple chapters of a story, and then write a single html file with all the chapters in it?
Why would you do that? 
What are you trying to achieve?

**Comment by Ariel-Schnee** [comment]
"Are you asking for WebToEpub to read the multiple chapters of a story, and then write a single html file with all the chapters in it?"

Yes.

That is correct.

"Why would you do that?"

To have a .html file to read offline on my computer.

"What are you trying to achieve?"

See above answer.

**Comment by gamebeaker** [comment]
@Ariel-Schnee You can archive this with [calibre](https://calibre-ebook.com/). This program can convert a epub file to .zip or .htmlz
After the conversion you have to extract the .zip file or the .htmlz file with 7zip
The .zip file creates one .html file per Chapter and you can navigate with "next Chapter" or an Index
The .htmlz file creates one large index.html file in which the content of all chapter is.
Why is it more than just one file?
The main reason are picture which are linked to be displayed in the .html files.
>To have a .html file to read offline on my computer.

If you just want to read offline on your computer you can read the .epub file with a reader like [calibre](https://calibre-ebook.com/) no reason to convert it to .html etc.

**Comment by Ariel-Schnee** [comment]
Nevermind. Found this place - https://www.onlineconverter.com/epub-to-html . It does the job I need done well.

Even if I do have to edit the file it produces.

It still does quite well now though.

"If you just want to read offline on your computer you can read the .epub file with a reader like [calibre](https://calibre-ebook.com/) no reason to convert it to .html etc."

I see you do not "get it". And it would be pointless to try and explain it. I will do as I choose to.

**Comment by gamebeaker** [comment]
> I see you do not "get it". And it would be pointless to try and explain it. I will do as I choose to.

Have you even tried my solution with [calibre](https://calibre-ebook.com/)?
I don't think so. Why?
https://www.onlineconverter.com/epub-to-html uses [calibre](https://calibre-ebook.com/) on the server side. (Open the index.html in an editor and you can read "calibre" everywhere.)
The .zip which you download is the same file as when you convert it to .htmlz just renamed to .zip and as you have to extract the .zip from the website in the same way i described extracting .htmlz there is no difference between these files.

**Comment by Ariel-Schnee** [comment]
"Have you even tried my solution with calibre?"

Yes.

"I don't think so."

You think what you want to think.

"Why?"

It's slow. The website is faster. Less time waiting.

"https://www.onlineconverter.com/epub-to-html uses calibre on the server side. (Open the index.html in an editor and you can read "calibre" everywhere.)"

They use a better version than I have on my computer.

"The .zip which you download is the same file as when you convert it to .htmlz just renamed to .zip and as you have to extract the .zip from the website in the same way i described extracting .htmlz there is no difference between these files (the website deletes the file metadata.opf where the local version keeps it)."

I don't need the metadata file.

**Comment by gamebeaker** [comment]
@Ariel-Schnee I didn't consider that the online version could be faster/ better.
It's good that you found a solution to the problem.
Do you want to share what your use case is? (Why does it need to be a .html file? My idea would be local website hosting or something in this direction)

**Comment by dteviot** [comment]
@Ariel-Schnee 
Have you considered using something like the EpubReader browser extension for viewing the epub files?
https://chromewebstore.google.com/detail/epubreader/jhhclmfgfllimlhabjkgkeebkbiadflb
