### ISSUE TITLE
Please add site https://www.powanjuan.cc/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#1541]
pls add https://www.powanjuan.cc/

thank you.

**Comment by dteviot** [comment]
@Finks82 

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.powanjuan.cc/wxxz/18957.html, chapters 1 &amp; 2

Notes
* Site does not say it's using gb2313 encoding.
* Time taken:  36 minutes

**Comment by dteviot** [comment]
@Finks82 

Updated version (1.0.1.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours (typical) to 21 days.
