### ISSUE TITLE
mtlnovel.com url change

### ISSUE THREAD

**Issue by TheFirstProgenitor** [dteviot/WebToEpub#1545]
mtlnovel.com >> mtlnovels.com
ui looks similar to what it was before.
but just changing url in parser didn't seem to work

**Comment by dteviot** [comment]
@TheFirstProgenitor 

Site seems to be somewhat broken at the moment.
Opening the following pages in a normal browser and then trying to expand the list of chapters fails.

* https://www.mtlnovels.com/hello-changan/
* https://www.mtlnovels.com/traveling-through-the-beast-world-counterattack-after-binding-the-childbirth-system/
* https://www.mtlnovels.com/one-skill-point-per-second-i-turn-the-fireball-into-a-forbidden-spell/

If site is broken, WebToEpub can't make it work.
Please let me know when site is working again.
