### ISSUE TITLE
Please add site https://raeitranslations.com

### ISSUE THREAD

**Issue by Y518A** [dteviot/WebToEpub#1546]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://raeitranslations.com/i-pretended-to-have-amnesia-and-now-the-heros-party-is-obsessed-with-me

### Did you try using the Default Parser for the site?  If not, why not?
Yes, i try. 
But give this mistake: Could not find content element for web page 'https://raeitranslations.com/i-became-a-6-gacha-character/0'. testDefaultParser/<@moz-extension://b3915b2d-d224-4054-9928-be8cd8ef38a1/js/DefaultParserUI.js:154:23 

I think is because the CSS selector is expressed in this way: div.chapter-content.content-container.no-copy  

### What settings did you use?  What didn't work?
* URL of first chapter: https://raeitranslations.com/i-pretended-to-have-amnesia-and-now-the-heros-party-is-obsessed-with-me/0
* CSS selector for element holding content to put into EPUB: .chapter-content
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

**Comment by dteviot** [comment]
@Y518A 

Site was working, but now WebToEpub seems to be triggering some sort of anti-scrapping response from Cloudflare.
I don't think I can fix without a great deal of work.

Notes: 
26 minutes work.

**Comment by dteviot** [comment]
@Y518A 

Well this is embarrassing.

Mistake on my part.  Should now be working.

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://raeitranslations.com/i-pretended-to-have-amnesia-and-now-the-heros-party-is-obsessed-with-me, chapter 3

Notes
1. Time taken: XXX minutes
2. Site had changed the URL needed for the REST call to get chapter content.  When I updated WebToEpub to use the new URL, it had a typo in it, so it was triggering the Cloudflare response.  Fixed typo, and it now all seems to be working. Only noticed my mistake when typing up my notes.

**Comment by Y518A** [comment]
Thanks!!!!!

**Comment by dteviot** [comment]
Reopen, so I know to notify you when version in Firefox and Chrome stores updated

**Comment by dteviot** [comment]
@Y518A 

Updated version (1.0.1.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours (typical) to 21 days.
