### ISSUE TITLE
Limited max download

### ISSUE THREAD

**Issue by miki99smok** [dteviot/WebToEpub#1547]
when i try get chapters from  this site it only goes up 30 chapter
https://novelbin.me/novel-book/the-return-of-the-iron-blood-sword-hound#tab-chapters-title
![Screenshot_20241016_222620_Kiwi Browser](https://github.com/user-attachments/assets/d4c58619-e38c-455a-bb97-eabce089ce0a)
![Screenshot_20241016_222559_Kiwi Browser](https://github.com/user-attachments/assets/6203014a-9af7-45db-bd76-bfc15ac2f007)

**Comment by gamebeaker** [comment]
@miki99smok are you in desktop mode?

**Comment by miki99smok** [comment]
@gamebeaker  i didn't Turn on on desktop mode

**Comment by gamebeaker** [comment]
@miki99smok as kiwi isn't supported and it works on firefox android i am closing this issue.
