### ISSUE TITLE
Issues Importing Previous WebToEpub Epubs Into WebToEpub Library

### ISSUE THREAD

**Issue by dastrdly6585** [dteviot/WebToEpub#1550]
**Describe the bug**
Epubs previously created by WebToEpub cannot be imported into the WebToEpub library. Two different situations occur:

1. If attempting to import an Epub created by WebToEpub _prior_ to this issue occurring, it gets stuck on 'In Progress...'
2. If attempting to import an Epub created by WebToEpub _after_ this issue started occurring, you get an error message: 
> Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html readEndOfCentral@moz-extension://62913b9f-45ab-446f-b87b-d91b99bb16ac/jszip/dist/jszip.min.js:13:38885
> load@moz-extension://62913b9f-45ab-446f-b87b-d91b99bb16ac/jszip/dist/jszip.min.js:13:40597
> [11]</t.exports/<@moz-extension://62913b9f-45ab-446f-b87b-d91b99bb16ac/jszip/dist/jszip.min.js:13:11680

After this error occurs an entry shows up in the library but it appears broken.

**To Reproduce**
1. Open the WebToEpub extension in browser
4. Click on 'Library'
5. Select 'Show Advanced Library Options' checkbox
6. Click on 'Upload Epub'
7. Choose a 'epub' file previously generated by WebToEpub
8. One of the two previously described outcomes occurs (either gets stuck on 'In Progress...' or an error message appears).

**Expected behavior**
WebToEpub should be able to successfully ingest previously created Epub files.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome & Firefox
 - Version 130.0.6723.59 (Chrome), 131.0.3 (Firefox)

**Smartphone (please complete the following information):**
N/A

**Additional context**
- Epubs produced by WebToEpub after this issue started occurring still appear to be well-formed for Epub readers.
- This issue appears to have started happening sometime within the last week.
- If I download the new chapters, manually add them to a WebToEpub created prior to this issue occurring (correcting the xhtml file names to match the rest of the files), and then try to upload the merged Epub to the WebToEpub library I get the error message outcome. If I do the extra step of modifying the content.opf in the merged file to use the correct ids (i.e., xhtml????) and manually add the appropriate dc:source entries, then WebToEpub instead gets stuck on 'In Progress....' when uploading.

**Comment by gamebeaker** [comment]
@dastrdly6585 can you please upload the problematic .epub here: https://nx39171.your-storageshare.de/s/Fy49MaWNTX4WwNn
(It is possible that i am able to see metadata from the file.)
or if you don't want to upload your file please share your story link and which chapters are in it.
Please write in this issue to notify me if you uploaded your file.

**Comment by dastrdly6585** [comment]
@gamebeaker I have uploaded an example of a problematic epub to the link you provided. The epub was produced by WebToEpub about a week and a half ago and was recently modified by manually adding in chapters downloaded from the current WebToEpub using the Calibre editor. I've modified the content.opf file so that the metadata should conform to the original chapters after merging.

The series the epub came from is here: https://fenrirtranslations.com/series/the-conjurer-of-the-academy/

And here are screenshots of the error and what shows up in the library after attempting to upload: 
![image](https://github.com/user-attachments/assets/b7106b4b-3c27-4089-889f-93b61389b26c)
![image](https://github.com/user-attachments/assets/9f93a3ca-a4e0-41c4-ab7d-e57a8b255067)

**Comment by gamebeaker** [comment]
@dastrdly6585 i found the issue if you delete "OEBPS\toc.ncx" it works for me.
Why?
toc.ncx is similar to content.opf i guess if you edit it correctly it should also work.
If you delete the file your EPUB is no longer [version 3](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#create-epub-3) but EPUB version 2.

> was recently modified by manually adding in chapters downloaded from the current WebToEpub using the Calibre editor.

you can use the the advanced Option [Add Chapter from different EPUB](https://github.com/dteviot/WebToEpub/wiki/Library#add-chapter-from-different-epub) to add Chapter from an different EPUB instead of doing it manually.

**Comment by gamebeaker** [comment]
I am going to investigate it futher as firefox seems to have a problem with it.

**Comment by dastrdly6585** [comment]
> @dastrdly6585 i found the issue if you delete "OEBPS\toc.ncx" it works for me in chrome. Why? toc.ncx is similar to content.opf i guess if you edit it correctly it should also work. If you delete the file your EPUB is no longer [version 3](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#create-epub-3) but EPUB version 2.

This doesn't seem like the correct solution. 'toc.ncx' is the Table of Contents file, while the 'content.opf' is the file containing metadata about what individual files are actually inside the epub. Deleting the toc.ncx file just wipes the Table of Contents and opening it with any epub editor automatically recreates the file anyways.

> you can use the the advanced Option [Add Chapter from different EPUB](https://github.com/dteviot/WebToEpub/wiki/Library#add-chapter-from-different-epub) to add Chapter from an different EPUB instead of doing it manually.

This is what I had been doing in the past, which is why I would like the upload feature to be fixed. I've just been doing the manual addition of new chapters as a backup since the upload is broken.

**Comment by gamebeaker** [comment]
@dastrdly6585 i tested your file and without changing anything and it works for me in chrome (not firefox wtf?) i get an console error but the book is added to the library and if i download the epub from the library it is a working epub. I am now really confused as to what the problem is and am going to look more into it. (as i mentioned above i have little time at the moment so it can take a while)

**Comment by gamebeaker** [comment]
@dastrdly6585 can you please upload more problematic epubs?
I am now unable to reproduce the error in chrome and don't even get an console error anymore?!
In firefox it fails with this error 
![grafik](https://github.com/user-attachments/assets/4634d5ff-68f2-4a56-9201-72c03c2816d2)

**Comment by dastrdly6585** [comment]
@gamebeaker Sure, I've uploaded two additional epubs to the previous link.

One epub is unmodified from one and a half weeks ago and is sourced from here: https://helheimscans.com/series/2146298df01/

The other epub was originally produced by WebToEpub a week and a half ago, then hand-modified a day ago using new chapters also downloaded via WebToEpub but manually added, and then I added new entries to the table of contents and fixed the content.opf to match WebToEpub convention.  It is sourced from here: https://fenrirtranslations.com/series/the-return-of-the-limited-time-sword-master/

**Comment by dastrdly6585** [comment]
Here's a screenshot of the error I'm getting when attempting to upload in chrome. It basically looks identical to the Firefox error except for some application specific plugin hashes: 
![image](https://github.com/user-attachments/assets/26324d29-a08e-4af5-8f61-9802d9dd3244)

**Comment by dastrdly6585** [comment]
Searching up where this error comes from, it appears to be coming from the jszip library from this specific place in the source code: https://github.com/Stuk/jszip/blob/2ceb998e29d4171b4f3f2ecab1a2195c696543c0/lib/zipEntries.js#L166

No idea why jszip thinks the epub is an invalid zip file. After changing the extension to zip, my normal archivers can open the file fine.

**Comment by gamebeaker** [comment]
@dastrdly6585 I am sorry i am unable to reproduce this error in chrome and firefox here is a video how i tried it. If i did something different please point is out.

https://github.com/user-attachments/assets/f3e57d4f-3f0e-4c7d-830c-025cd8ac356e

Do you have special hardware?
Do you have an ARM processor instead of x86?
Is it running in an VM?
etc.

**Comment by dastrdly6585** [comment]
@gamebeaker Nope, as far as I'm aware I have standard hardware. Just a laptop with an Intel CPU, x86, not a VM. And like I said, it was working up until this week without problems. Just suddenly stopped working for no particular reason? Maybe the only thing that's changed is a Windows 10 update that occurred within the past week (KB5001716)? This computer is a bit dated (about 10 years old?). Here are the basic specs: 
![image](https://github.com/user-attachments/assets/79adc7f4-677f-44c8-9419-99132498608e)

If you feel like uploading the epubs here will help troubleshoot the issue, feel free to.

**Comment by gamebeaker** [comment]
Here are the files if someone wants to try it.
[library issue.zip](https://github.com/user-attachments/files/17452137/library.issue.zip)
@dastrdly6585 can you try these files please maybe they got altered during the up/ download.

**Comment by dastrdly6585** [comment]
@gamebeaker Just tried the files again, still getting an error message.

As an update, when I tried creating a new Firefox profile and doing the upload there, I instead got the situation where it gets stuck in the 'In Progress...' forever. Is it possible there's some sort of corruption with WebToEpub's library directory? And if so, is there a way to fully clear it out? Uninstalling/reinstalling WebToEpub doesn't seem to work, nor does creating a new Firefox profile.

**Comment by gamebeaker** [comment]
@dastrdly6585 at the moment i am inclined to think that it is a problem with your system (I hope you have a backup in case your laptop dies).
Why did i affirm your problems in my first few responses? It was because i used my local developer version and in this version i changed jszip a little bit for me locally to test a few things. In the video i used WebToEpub from the extension stores.

**Comment by dastrdly6585** [comment]
While the issue remains unsolved, I'll just use the MergeWebToEpub tool that was created a while back to update my epubs.

**Comment by dastrdly6585** [comment]
@gamebeaker Update: I just downloaded a epub fresh using WebToEpub and when I tried doing an upload to library instead of the jszip error I'm now getting the console error you screenshot earlier, but in both Firefox and in Chrome: 
Firefox error in console:
![image](https://github.com/user-attachments/assets/74cbbabf-bc13-4c07-b7c8-66635b818ec6)

Chrome error in console:
![image](https://github.com/user-attachments/assets/1d51cd5d-6b04-41ee-b661-89e408c16b83)

Additionally, I've determined that the only difference between me getting the jszip error vs. getting the console error (and it getting permanently stuck on 'In Progress....' is this one metadata line that Calibre appears to add to the toc.ncx file when you make modifications to the Table of Contents via Calibre's Table of Contents editor:
`<meta name="dtb:generator" content="calibre (7.20.0)"/>`
With this metadata line, I get the jszip error. Without this metadata line, I get the above console errors and the stalled 'In Progress....'.

Utilizing some debugging in the console, it appears that the console error is triggered due to either an incorrect call to the `LibConvertDataUrlToBlob` function for a wrong type of data URL or due to an issue with the stripping of the prefix of the data URL. Namely, it appears that line 631 of Library.js assumes the data URL's prefix is: `"data:application/epub+zip;base64,"`, but when I set a breakpoint at the console error the data URL's prefix is instead: `"data:image/epub;base64,"`. Because the two prefixes are different lengths, the slice incorrectly cuts off more of the data URL than it should resulting in a broken base64 string that can't be decoded by `atob` hence the error.

**Comment by dastrdly6585** [comment]
@gamebeaker I have identified and solved the problem. Apparently in the process of updating the various software on my computer, one of the applications (likely a thumbnailing application) changed the .epub file extension Content Type in the Windows registry from 'application/epub+zip' to 'image/epub' This change meant that when FileReader attempts to read in an epub, it returns a MIME type of 'image/epub' instead of 'application/epub+zip' which messes up the WebToEpub processing. Editing my registry to restore the original 'application/epub+zip' content type fixes all of the associated issues I've been getting with uploading previous epubs into the library.

**Comment by gamebeaker** [comment]
@dastrdly6585 wow that's a niche bug. Nice find 👍
I don't know if i should change the code to catch the bug.
The solution would be to change here:
https://github.com/dteviot/WebToEpub/blob/6cdc65fe03a40a5c88fbe840c65224f92ab27c75/plugin/js/Library.js#L630-L638
`var dataString = DataUrl.slice(("data:application/epub+zip;base64,").length);`
to
`var dataString = DataUrl.slice(DataUrl.search(";base64,")+(";base64,").length);`
The current code takes no time to execute and the solution takes longer e.g. 0-0,1s depending on the epub size.
