### ISSUE TITLE
Cloudflare Always Triggers on HelheimScans with Firefox

### ISSUE THREAD

**Issue by dastrdly6585** [dteviot/WebToEpub#1551]
**Describe the bug**
Attempts to download any chapters from HelheimScans trigger a 403 error from Cloudflare. Can use 'Open URL for captcha' and verify as a human on the captcha, but Cloudflare immediately blocks on retry and the visited chapter still isn't successfully downloaded.

**To Reproduce**
1. Go to series page on HelheimScans (e.g., https://helheimscans.com/series/5d98787945a/)
2. Open WebToEpub
3. Choose any number of chapters
4. Hit 'Pack Epub'
5. Get error

**Expected behavior**
Chapters should be downloaded with only the rare occasion of a Cloudflare block, which after going to the URL and solving the captcha, should fix the downloading for at least a while.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 131.0.3

**Smartphone (please complete the following information):**
N/A

**Additional context**
- I can normally browse the chapters on HelheimScans without Cloudflare constantly asking me to verify, but any WebToEpub usage immediately gets blocked.
- There are no problems downloading chapters after verifying with Cloudflare using the Chrome version of WebToEpub.

**Comment by Elthara** [comment]
I'm having exactly the same issue on Foxaholic trying to grab this: https://www.foxaholic.com/novel/little-love-song/.

Same version of windows and firefox involved.

**Comment by dteviot** [comment]
@gamebeaker 
Have you considered trying the Storage Access API?  https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning#storage_access_api  In particular, https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess

**Comment by gamebeaker** [comment]
@Battlespike1 @dastrdly6585 @Elthara is the bug still present with the new Firefox version 132.0?

**Comment by gamebeaker** [comment]
@dastrdly6585 can you please try it with all other addons disabled?

**Comment by dastrdly6585** [comment]
@gamebeaker Still getting the issue even with all other addons disabled besides WebToEpub.

**Comment by dastrdly6585** [comment]
@gamebeaker Update, I seem to have fixed it by going into Firefox's settings and clearing out all website data for helheimscans.com.

**Comment by Elthara** [comment]
> @Battlespike1 @dastrdly6585 @Elthara is the bug still present with the new Firefox version 132.0?

I just saw dastrdly's post and tried clearing out cookies for foxaholic and NOW it works fine. Before I did that it wasn't working; I tried both with and without extensions disabled.
