### ISSUE TITLE
Fanfiction not working

### ISSUE THREAD

**Issue by Battlespike1** [dteviot/WebToEpub#1554]
**Describe the bug**
a tempting to download chapters form fan fiction immediately comes up with

WARNING: Site 'www.fanfiction.net' has sent an Access Denied (403) error. You may need to logon to site, or browse site normally until you get a Cloudflare "Are you a human" page or satisfy some other CAPTCHA before WebToEpub can continue. Fetch of URL 'https://www.fanfiction.net/s/14027124/1/A-Nascent-Kaleidoscope' failed with network error 403. This is an intermittent error. If you retry in a few minutes, it may succeed. promptUserForRetry@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:57:19 onResponseError@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:48:25 checkResponseAndGetData@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:207:45 wrapFetchImpl@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:197:31 async*retryFetch@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:77:27 async*onResponseError@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:40:25 checkResponseAndGetData@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:207:45 wrapFetchImpl@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:197:31 async*wrapFetch@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/HttpClient.js:157:27 fetchChapter@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/Parser.js:551:34 fetchChapter@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/parsers/FanFictionParser.js:60:31 fetchWebPageContent@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/Parser.js:504:27 async*fetchWebPageContent@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/parsers/FanFictionParser.js:69:32 fetchWebPages/<@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/Parser.js:477:69 fetchWebPages@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/Parser.js:477:41 async*fetchContent@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/Parser.js:449:21 fetchContentAndPackEpub@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/main.js:153:16 EventHandlerNonNull*addEventHandlers@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/main.js:464:9 window.onload@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/main.js:584:13 EventHandlerNonNull*main<@moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/main.js:579:5 @moz-extension://02022dd5-761e-4535-9524-ada80ad168e4/js/main.js:598:3

**To Reproduce**
1. click on the web to epub extension
2. click pack epub

**Expected behavior**
to download the book

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Firefox
 - Version 131.0.3 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gamebeaker** [comment]
this issue is the same as #1551

**Comment by Kiradien** [comment]
Is this issue persistent/still happening? There was some issue on Fanfiction last week (Server side) so it might be related, but this looks more like an attempt to generate without entering through initial Cloudflare capcha.

If you're still getting this, can you try navigating to the latest chapter before doing generation?

**Comment by gamebeaker** [comment]
@Kiradien i am unable to reproduce the bug since a few days ago. I don't know what changed not only fanfiction but all sites using cloudflare.

**Comment by dteviot** [comment]
My suspicion/hypothesis is Mozilla did something with handling of partitioned cookies in Firefox.   Not sure if it has been fixed.

**Comment by gamebeaker** [comment]
@Kiradien @dteviot i was just able to reproduce the error on https://www.foxaholic.com/novel/little-love-song/ ...

**Comment by gamebeaker** [comment]
I just got an update to version 132.0 and i couldn't recreate the issue. Let's hope it really went away and isn't just weird.

**Comment by dteviot** [comment]
@gamebeaker 
Based on this, I plan on updating version in stores in a couple of days.
Can you please confirm WebToEpub is working for Firefox for Android?

**Comment by gamebeaker** [comment]
@dteviot there was no code change to WebToEpub that adressed this issue or did i miss something? 
I can validate it for Firefox-Android on the 05.11 as i have no access to my pc at the moment.

**Comment by gamebeaker** [comment]
@dteviot there was no code change to WebToEpub that adressed this issue or did i miss something? 
I can validate it for Firefox-Android on the 05.11 as i have no access to my pc at the moment.

**Comment by dteviot** [comment]
@gamebeaker 

> there was no code change to WebToEpub that adressed this issue or did i miss something?

There was no code change to WebToEpub.  However, you said

> I just got an update to version 132.0 and i couldn't recreate the issue. 

So, I'm going to assume (until I hear otherwise) the problem was with Firefox.  So, no reason to hold up the release.  
Unless I'm missing something?  (I was holding up the release until this issue was resolved.)

**Comment by gamebeaker** [comment]
@dteviot i understand it was a missunderstandding on my part.
> Unless I'm missing something?

You aren't missing something.
As mentioned can i not validate the Firefox-Android version at the moment.

**Comment by Battlespike1** [comment]
as  far as i can tell it is working

**Comment by dteviot** [comment]
@Battlespike1 
> as far as i can tell it is working

Are you referring to the Development build that you need to download from https://github.com/dteviot/WebToEpub/releases/tag/developer-build?  And for Firefox on Android, or Firefox on the Desktop Windows/Mac?

**Comment by Battlespike1** [comment]
no i did not change any thing it as far as i can tell just started working yesterday i do not know what change. and i am on fire fox on the PC latest version.

**Comment by gamebeaker** [comment]
@dteviot sorry that i took so long i have a few busy days at the moment.
I was able to validate it on firefox-android additionally was i able to validate it with an Android emulator (No need for an Android phone). I am going to add it to the docs in short i used [bluestacks](https://www.bluestacks.com/de/index.html) and it worked for testing.
Note: Write up what/how it gets tested in the docs.

It looks like this issue and #1551 are "solved" if the local data in firefox is cleared (thanks @dastrdly6585)
