### ISSUE TITLE
Please add site https://wetriedtls.com/novels

### ISSUE THREAD

**Issue by AppleDots** [dteviot/WebToEpub#1559]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
**[Here](https://wetriedtls.com/series/demon-sword)**

### Did you try using the Default Parser for the site?  If not, why not?
**Yes**

### What settings did you use?  What didn't work?
* URL of first chapter
*  - [Here](https://wetriedtls.com/series/demon-sword/chapter-1)
* CSS selector for element holding content to put into EPUB
*  - div#reader-container.p-5.rounded.shadow-lg.text-left.leading-normal.space-1.bg-background.text-foreground.baskervville-regular
* CSS selector for element holding Title of Chapter
* - p
* CSS selector for element(s) to remove
*  - None/Not Sure

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Don't Have Developer Skills.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
Don't know anyone that has developer skills.

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
Did not attempt to write a parser.

**Comment by dteviot** [comment]
@AppleDots 

Duplicate, See. https://github.com/dteviot/WebToEpub/issues/1388
Site will not be supported.
