### ISSUE TITLE
Wuxiaworld Support for new UI

### ISSUE THREAD

**Issue by sfblackl** [dteviot/WebToEpub#157]
Wuxiaworld just updated their site layout (http://www.wuxiaworld.com/announcement/new-site-features).  webtoepub no longer is able to come up with a listing of content.

1) If on a page like http://www.wuxiaworld.com/novel/heavenly-jewel-change, the content is all the links that are a child - like http://www.wuxiaworld.com/novel/heavenly-jewel-change/hjc-book-1-chapter-1-01

2) Or if you are reading DOM, it is all the items in <li class="chapter-item">
Example

<ul class="list-unstyled list-chapters">
--
  | <li class="chapter-item">
  | <a href="/novel/heavenly-jewel-change/hjc-book-1-chapter-1-01">
  | <span>Chapter 1 – Big Sis, I’m afraid this is a misunderstanding! (1)</span>
  | </a>
  | </li>
  | <li class="chapter-item">
  | <a href="/novel/heavenly-jewel-change/hjc-book-1-chapter-1-02">
  | <span>Chapter 1 – Big Sis, I’m afraid this is a misunderstanding! (2)</span>
  | </a>
  | </li>

**Comment by dteviot** [comment]
@sfblackl
Thanks.  I've updated the parser.
However, there's not much I can do about the images being in webp format.  If your epub reader doesn't cope with that.

**Comment by sfblackl** [comment]
Thanks for the fast change - works great
