### ISSUE TITLE
Chapters not showing for NovelBin.com

### ISSUE THREAD

**Issue by itsWoj** [dteviot/WebToEpub#1578]
Sorry if I'm just not understanding what im doing wrong but I cant seem to get the chapters to show up when i try to create a epub for novelbin.com. I did try all the parsers and even followed how to make a default parser but it keeps showing either the chapter im viewing or a list of menu options 

![Screenshot 2024-11-24 234939](https://github.com/user-attachments/assets/6eb6f316-6f3c-4f35-bb32-8b1d8856c4e3)
![image](https://github.com/user-attachments/assets/d611a27d-831f-43d4-9a33-e828056a7e76)

**Comment by gamebeaker** [comment]
@itsWoj you have to select no manual parser for novelbin.com.
Example:
https://novelbin.com/b/chaos-heir#tab-chapters-title
You have to click "Chapter List" before using WebToEpub.
![image](https://github.com/user-attachments/assets/43c64406-8d1d-4602-b62b-a4d4bdbfaff0)
Than all Chapter should be visible.

**Comment by itsWoj** [comment]
@gamebeaker  Thank you so much this worked perfectly and thanks for the recommendations.
