### ISSUE TITLE
Make it easier to select/unselect a range of chapters

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#158]
A number of users have complained about lack of ability to check/uncheck a range of chapters by multi-selecting the chapters in the range they want. e.g. click on the first chapter and then shift-click on the last chapter they want.  then have all the check boxes between the two update to the same state.

Note, the behaviour can be obtained by clicking on the "Edit Chapter URLs" button.
So, the fact that I get the complaint tells me that users don't understand what that button is doing.

In an attempt to provide a more easily discover-able solution to this "multi-select" issue, I've added two drop down lists to allow user to specify a range of chapters the "Select All" and "Unselect All" buttons will be applied to.

Note, I've also added shift-click multi-select ability.  However, as it's not obvious, I have a help message pop up when user clicks on 6 adjacent chapters in a row.

**Comment by dteviot** [comment]
@typhoon71, @toshiya44
If you have some time, can you try out the latest Experimental Tab mode branch and let me know what you think of the "Make it easier to select/unselect a range of chapters" changes. Make it easier to select/unselect a range of chapters.  In particular, try to select or unselect a range of 10 chapters or so.
Thanks.

**Comment by typhoon71** [comment]
Late to the party, but I can say it works nicely, and I do prefer this compared to the other editor, which is too advanced for basic needs: say I have dozens of chapter, and want to keep only 8 in the center, now I can unselect all click and shift click, done. It was not that fast before. Thanks a lot.
Too bad thi hasn't landed on firefox yet.

**Comment by dteviot** [comment]
typhoon71

Feedback is much appreciated.
Firefox should land in a day or two I think.
