### ISSUE TITLE
Please add site https://novelhi.com/

### ISSUE THREAD

**Issue by Deveshsk** [dteviot/WebToEpub#1588]
The Website - https://novelhi.com/

URL of the story's Table of Content's Page - https://novelhi.com/s/index/Legend-of-the-Cultivation-God

I'm sorry, I don't have a computer and I only use my android phone as I'm blind so I'm not able to do the techy stuff.

I'm not sure what exactly the issue is but as far as I can guess, I think the extension is unable to find the URL's of the chapters. 

* URL of first chapter - https://novelhi.com/s/Legend-of-the-Cultivation-God/1
![IMG_20241206_212128](https://github.com/user-attachments/assets/dbe54862-bb8b-4e1e-9154-5506d461751c)
.

**Comment by ImLJS** [comment]
@Deveshsk The extension is working properly for the desktop version of the site. Since you are using the extension on Android, turn on desktop mode for the site and then use the extension.

**Comment by Deveshsk** [comment]
Yes, I just tried it and it's now working with desktop mode. Thank you.

**Comment by dteviot** [comment]
@ImLJS 
Thank you for taking care of this.
