### ISSUE TITLE
Internationalzation support.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#16]
(note for self)
https://developer.chrome.com/extensions/i18n

**Comment by belldandu** [comment]
@dteviot here is the firefox one https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n

**Comment by dteviot** [comment]
@typhoon71 

I've noticed some of your screenshots show text which I think is Spanish.
The latest commit to the https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode branch includes support for non-English languages.  Specifically text that is shown to user is now all read from the messsages.json file.  If you want to make a Spanish version of this file, it should be possible to have the extension present a Spanish interface.   More details can be found here.  https://developer.chrome.com/extensions/i18n

**Comment by typhoon71** [comment]
Actually it's Italian. How many DL from Italy does the addon gets?
I'm fine with English interface, but if it's worth it I may make an effort... maybe.

**Comment by dteviot** [comment]
@typhoon71
> Actually it's Italian

D'oh!

>  How many DL from Italy does the addon gets?

I don't know.  The only number I see is the total.  Currently 3,100.

> I'm fine with English interface, but if it's worth it I may make an effort... maybe.

If you're happy with English, then no problem.  I just thought you might like Italian.

**Comment by typhoon71** [comment]
Oh, thanks for the thought then.

**Comment by dteviot** [comment]
Going to call this done.  Release 0.0.0.18 has a Vietnamese translation
