### ISSUE TITLE
Please add site https://foxaholic.com/

### ISSUE THREAD

**Issue by novelkla** [dteviot/WebToEpub#1601]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

_**https://www.foxaholic.com/novel/tsgwtkm/**_

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

**Sorry, I don't know how**

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

_**https://www.foxaholic.com/novel/tsgwtkm/**
**https://www.foxaholic.com/novel/tsgwtkm/chapter-1/**_

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Sorry, I don't know.**

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

**I don't have a friend sorry.**

**Comment by ImLJS** [comment]
@novelkla Checked just now, the extension is working fine for the site. on what device are you using the extension. If you are on android using kiwi/firefox browser, turn on desktop mode and try again

**Comment by novelkla** [comment]
So I using Google Chrome on a laptop and it had like a 403 denied access error. Somehow, it seemed like it works now for this site when I tried it just now. Thank you!
