### ISSUE TITLE
Issue with webnovel.com

### ISSUE THREAD

**Issue by RalphC11** [dteviot/WebToEpub#161]
The site has added series in volume format, For ex - https://www.webnovel.com/book/7920706906001505/NEET-Receives-a-Dating-Sim-System It has added Volume 0 & Volume 1. When we try to make epub it will only show Volume 0 chapters and completely skip all other volume chapters. On another there was no volume 0 but Volume 1 & Volume 2, it only showed all chapters of Volume 1. Can you please check it.

Thanks in advance.

**Comment by dteviot** [comment]
@RalphC11
Fixed in version 0.0.0.48 which has just been uploaded to Chrome web store. Your version should automatically update within 24 hours.
