### ISSUE TITLE
chapter error on webnovel.com

### ISSUE THREAD

**Issue by Dan211q** [dteviot/WebToEpub#1618]
The chapters on webnovel.com error on android. 
i used kiwi browser and firefox, but neither works (already use desktop mode). 
![Screenshot_20241230-072404_1](https://github.com/user-attachments/assets/1bcf1dab-b5dd-439d-a9c9-9a2b2eb5225a)
![Screenshot_20241230-072427_1](https://github.com/user-attachments/assets/7bac2dc2-98e7-4b01-aa09-42dfa754ae0d)

**Comment by ImLJS** [comment]
@Dan211q Checked just now, the extension is working fine for the site. SInce you are using kiwi, turn on desktop mode and try again

**Comment by Dan211q** [comment]
oh, the extension need to desktop mode too. thanks , now already work.

**Comment by dteviot** [comment]
@Dan211q 
Why did you reopen this?

**Comment by Dan211q** [comment]
@dteviot oh sorry, its look like i accidentally reopen this. i didn't notice that, sorry again.
