### ISSUE TITLE
Wuxiaworld Title Problem

### ISSUE THREAD

**Issue by Maradar** [dteviot/WebToEpub#162]
Hello,
Since Wuxiaworld changed the design chapter in novels like Desolate Era does not have Title in in their chapters. It has only content.

Ok I tried and if this is added to Wuxiaworld parser it will put title back.

```javascript
    findChapterTitle(dom) {
        return dom.querySelector("h4[class='']");
````

I am not a programmer so if this solution is wrong please somebody skilled please correct it.

**Comment by dteviot** [comment]
@Maradar 

You're almost correct.
Updated version submitted to Chrome store.
