### ISSUE TITLE
Remove Images

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#168]
When browsing royal road sometimes an image is removed or the website hosting it removes it, but it still leaves the symbol. From what I've seen this gives an error or something in the code of the epub. Also some images are just corrupted so that also creates errors. An option like

[ ] remove images

would be very great.

**Comment by dteviot** [comment]
@JeremyStarten 
> From what I've seen this gives an error or something in the code of the epub

I'm not entirely sure what you mean by this.  I've just recently updated Web To Epub's handling of missing images.  See:
- https://github.com/dteviot/WebToEpub/issues/164 
- https://github.com/dteviot/WebToEpub/issues/166
- https://github.com/dteviot/WebToEpub/issues/166

Do you perhaps mean messages like these?
> Warning: Attempt to fetch imgur image(s) 'http://imgur.com/a/l24eE' for page 'https://royalroadl.com/fiction/8463/the-arcane-emperor/chapter/126807/chapter-60-abyssal-plane' failed with network error Error: Fetch of URL 'http://imgur.com/a/l24eE?grid' failed with network error 404..

> Error: Fetch of image 'https://s23.postimg.org/rqwq95l1n/New_Canvads.jpg?noredir=1' for page 'https://royalroadl.com/fiction/8463/the-arcane-emperor/chapter/126807/chapter-60-abyssal-plane' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://mfmddnfhonanhoiefonlenohoccckpml/js/HttpClient.js:24:31)
    at chrome-extension://mfmddnfhonanhoiefonlenohoccckpml/js/HttpClient.js:88:33


If so, they're not "errors" in the code.  They're messages to tell the user that Web To Epub was unable to get the image, so the page in the Epub will not have the image.  (A stub is placed, so in theory at least, someone might be able to manually obtain the image and fix up the epub with something like sigil

**Comment by JeremyStarten** [comment]
What I'm talking about is not a problem with retrieving the images from the websites. I mean like an option to only have the text retrieved and leaving the images and stuff. This helps because sometimes images retrieved are corrupted.

An example would be, try to use webtoepub on [RRL Sing Crier](https://royalroadl.com/fiction/8386/sing-crier). It would seem normal and all at first but if you use [sigil](https://sigil-ebook.com/) and the plugin [epubcheck](https://www.mobileread.com/forums/showthread.php?p=2950625#post2950625) you would get the error "ERROR(PKG-021):  Corrupted image file encountered." for "0001_Streya_FNL3". This might not matter for some epub viewers but I personally upload my epubs to google play books and having something like a corrupted images causes "This file cannot be processed." error.

Also now that I think about it an option to remove the images would also be good because it would help make the epub smaller, even by a little bit.

**Comment by dteviot** [comment]
@JeremyStarten
My new project https://github.com/dteviot/EpubEditor should remove the "broken" images from an epub.
Please give it a try and let me know how it works out.

**Comment by dteviot** [comment]
@JeremyStarten
Unfortunately, removing the images (or more precisely, not collecting the images) breaks parts of WebToEpub in ways that are not easy to fix without complicating the existing code more than I'm willing to do.  However, I've just added a "Remove all images" feature https://github.com/dteviot/EpubEditor/commit/f538d9cbb0083f0b51d5706922b16d6a635e3b54 to my EpubEditor that should give the same net result.
