### ISSUE TITLE
[email protected]

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#169]
When using Web to Epub I would randomly encounter these when an email is used. But alot of the times it's a fake email in the story or not even an email at all and all of a sudden theres just [email protected]. I don't really understand the point of this because it's easy to find the email if it is gathered by web to epub. Like if an author is like email me here for ____. You would find the email either way even if it is blocked.
So would there be a way to remove it?

**Comment by dteviot** [comment]
@JeremyStarten.  You wrote:
> When using Web to Epub I would randomly encounter these when an email is used.. 

Please provide a URL to a web page showing this behaviour and I'll see what I can do.  If possible, several web pages would be even better.
