### ISSUE TITLE
Open Spoilers on RoyalRoadL

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#170]
Sometimes authors use spoilers and when that happens the text doesn't appear when reading the epub. This is very annoying. However, I found that it does take the text still just doesn't show it, in the code. Using sigil to view the code just changing

 class="spoiler"><div class="smalltext" style="margin-bottom:2px"><b>Spoiler</b> : </div>
<div class="spoilerContent"><div style="display: none;">

to

hrefclass="spoiler"><div class="smalltext" style="margin-bottom:2px"><b> </b> : </div>
<div class="spoilerContent"><div style="display"> 

seems to fix it but I'm no professional coder. Would there be a way to make this be done automatically?

**Comment by dteviot** [comment]
@JeremyStarten.  You wrote:
> Sometimes authors use spoilers and when that happens the text doesn't appear when reading the epub. 

Please provide a URL to a web page showing this behaviour and I'll see what I can do.  If possible, several web pages would be even better.

**Comment by JeremyStarten** [comment]
I'm just gonna give one example because it's all basically the same on RRL even if the content of the spoiler is different.

From the story [The Demon and The Angel (Complete)](https://royalroadl.com/fiction/1738/the-demon-and-the-angel-complete):

Example [Chapter 33 Training Year Part 3 End
](https://royalroadl.com/fiction/1738/the-demon-and-the-angel-complete/chapter/18011/chapter-33-training-year-part-3-end) In this chapter there are spoilers used to hide status windows(at the bottem of the chapter). When using webtoepub on it the epub will just show **Spoiler:** and the texts in the spoiler will not appear when normally viewing the book. However as I said before the text seems to still be retrieved just hidden. Using [sigil](https://sigil-ebook.com) code viewer mode you can find the text under "div class="spoiler" div class="smalltext" style="margin-bottom:2px" b Spoiler /b  :  /div 
 div class="spoilerContent" div style="display: none;"" (I had to remove the <> so it would show.)

Sorry about my previous comment, What I did was copy and paste some code and I had no idea that github automatically made what the code wrote instead of the code itself. 

> class="spoiler">
> 
> Spoiler :
> to
> 
> hrefclass="spoiler">
> 
> :

was suppose to be
div class="spoiler" div class="smalltext" style="margin-bottom:2px" b Spoiler /b  :  /div 
 div class="spoilerContent" div style="display: none;"

to

div class=" " div class="smalltext" style="margin-bottom:2px" b Spoiler /b  :  /div 
 div class="spoilerContent" div style="display"

**Comment by dteviot** [comment]
@JeremyStarten 
The issue is the &lt;div&gt; element has style="display: none;"
Which says, "Don't show this element".
To display element, you'd just remove the style.
It should be trivial for me to modify the Royal Road parser to do this automatically.
Question:  Is it only Royal Road that has these spoilers?

**Comment by JeremyStarten** [comment]
While I can only really confirm that Royal Road is the only one who consistently uses spoilers in it, I have done some quick research on some of the websites. 

**ArchiveOfOurOwn** - I believe it can, from reading whats [here](https://archiveofourown.org/admin_posts/119). More specifically this part "You can use CSS to style the main body of your work, and in notes fields. You can't use it in summaries, because these show up in indexes, where user-input CSS is not supported. So, if you want to use styled text to include warnings or **spoilers**, you'll need to put these in the notes field."
**FanFiction** - I don't think so but don't quote me. From trying to look up if it does, I just found a bunch of people saying "how do I make my story spoiler free"
**Wuxiaworld** - No, I have used and read like a thousand chapters on this site and I have never seen a single spoiler. However their forums support it (all forums kinda do). It also could just be so rare or never utalised 
**readlightnovel** - Not that I found, now that I think about it, the websites that just do translating don't really utalise this. It's more the ones that let you write your own.
**novel update** - No, well since it uses the website of the author, if the author set it up so it has spoilers than yes but NU itself doesn't. Actually I'm pretty sure you don't support it because of one of the previous issues.
