### ISSUE TITLE
Suggestion to add an Information page

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#173]
Option to add information page after the cover. It would have the changed title from the previous suggestion and extra. Something like the author, genre, and synopsis.
Example for [The Dungeon Pact](https://royalroadl.com/fiction/14658/the-dungeon-pact):
Information page:

> (RRL) The Dungeon Pact (Hiatus)
> by Alexis Keane
> 
> Warning This fiction contains:
> Gore Profanity Traumatising content
> 
> Genre: Original, Action, Adventure, Fantasy, Anti-Hero Lead, Magic, Male Lead, Multiple Lead, Characters Non-Human lead, Reincarnation, Summoned Hero
> 
> Synopisis: "Hey there, just a quick fyi. I'm currently in the midst of preparation for uni finals so this fic will be on a brief hiatus until around about the 15th of may. In the immortal words of Arnold Schwarzenegger, I'll be back,
> They must live, and so, a god must die.
> Luneil, a unique dungeon, awakens in the wilderness. He must learn to adapt, or face oblivion.
> Bas, a member of a lost race of humans, arrives on the magical world of Era. He must adjust to a new way of life using only his wits and an old physics book.
> Era is in flux. Harmony is shattered and a tyrannical goddess begins to muster her full might in a crusade against anyone who will not bow.
> They cannot weather the coming storm alone. A deal must be struck.
> Luneil was born a monster. Can Bas become one?
> No matter what, Era will never be the same.
> This is the story of how a deathtrap becomes a haven, and how a good man becomes a killer.
> This story is eventually intended for publishing via Amazon, however, you have my word it will be left up for at least five weeks from the time it is completed (at which point I might be posting the second installment on here), so you don't need to worry about it disappearing overnight. Also, bear in mind that this is all a first draft before any significant edits. There will likely be spelling, grammar and continuity errors, I will address them as soon as I spot them or you point them out. I read every comment (and reply, time permitting). Please feel free to criticize (I suspect I have a somewhat longwinded writing style, shouting really does help :) ), and above all enjoy."

Reason: Sometimes I pack a bunch of epubs at once or I don't read it immediately. This can cause me or orther people to forget what the story was about. This allows the person to get the general information straight from the book instead of having to go back to the website.

**Comment by gamebeaker** [comment]
is fixed [Add Information page to Epub](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#add-information-page-to-epub)
