### ISSUE TITLE
Bug when using the chrome Plugin

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#174]
When using the chrome plugin you normally just click on the tab with the story you want to turn into an epub and it automatically does the thingy and you just press "Pack EPUB". This is all ok when you are doing just one epub at a time. The bug happens when more than one epub is done. 

What happens is if you used the plugin button on one story, then you do it on another story while the first story is being packed, the previous story is stoped and the tab is replaced with it packing for the new one.

it's kinda hard putting it into words so I'm going to write a step by step on what to do to show the bug.

First, open a story like [Chronicles of a Dungeon Core](https://royalroadl.com/fiction/17716/chronicles-of-a-dungeon-core).
Next, click the plugin so a new tab appears with the stuff to pack the story.
Then, go to a new story like [The Iron Teeth: A Goblin's Tale](https://royalroadl.com/fiction/4293/the-iron-teeth-a-goblins-tale).
After that, click the plugin so a new tab appears with the stuff to pack this story.
Finally, go back to the previous tab that was supposed to pack [Chronicles of a Dungeon Core](https://royalroadl.com/fiction/17716/chronicles-of-a-dungeon-core) and you will see it has been replaced with the one to pack [The Iron Teeth: A Goblin's Tale](https://royalroadl.com/fiction/4293/the-iron-teeth-a-goblins-tale)

This is annoying for me who likes to pack a bunch of stories at once. The only workaround I've found is having to get a blank webtoepub tab and manually copying the url and using the load & analyze feature.  This gets really tedious though since I have to use a trackpad to select and navigate through a sea of tabs instead of just clicking "Pack EPUB".

**Comment by dteviot** [comment]
@JeremyStarten
I committed a fix for this (also Spoilers and Protected Emails) to Experimental Tab branch.  Please try loading from source (https://github.com/dteviot/WebToEpub/user-content-how-to-install-from-source, use instructions for "Current Development Branch") and let me know how it goes.

**Comment by JeremyStarten** [comment]
umm the link is a 404 not found

**Comment by dteviot** [comment]
@JeremyStarten
Sorry should have been.
https://github.com/dteviot/WebToEpub#user-content-how-to-install-from-source

**Comment by JeremyStarten** [comment]
Got a new Laptop and I'm back. Anyways I followed the directions and have WebToEpub 0.0.0.51.
However it does show an ERROR

> Unrecognized manifest key 'applications'.

Don't know if thats important because it seems to still work

**Comment by dteviot** [comment]
@JeremyStarten 
> Unrecognized manifest key 'applications'.

It's not important.  It's a property that's needed for the extension to run on Firefox, but Chrome doesn't recognize it.
