### ISSUE TITLE
Suggestion to split a story into multiple epubs.

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#178]
So I'm going to use the newer 0.0.0.51 version of webtoepub to remake some of my stories and that would take alot of time. Especially because some authors split there story into different "Volumes" or "Parts" while being on the same story page. I'm wondering if it's possible to put like a checkpoint on a chapter so after it a new epub is created after the first one. This is helpful because it helps organizing the stories and stops massive books. This also great for Wuxiaworld stories which tend to all be 1000+ Chapters and makes it so you don't have to keep track of what chapter you stopped when making new epubs.

Example for RRL [The Wandering Inn](https://royalroadl.com/fiction/10073/the-wandering-inn)
The_Wandering_Inn
to
The_Wandering_Inn(V1)
The_Wandering_Inn(V2)
The_Wandering_Inn(V3)

Example for WuxiaWorld [Emperor’s Domination](https://www.wuxiaworld.com/novel/emperors-domination)
Emperors_Domination
to
Emperors_Domination(1-100)
Emperors_Domination(101-200)
Emperors_Domination(201-300)
etc

**Comment by dteviot** [comment]
@JeremyStarten 
I'm not sure what you're asking for.  
How does this differ from using the "First Chapter" and "Last Chapter" drop downs to split up a book?

**Comment by JeremyStarten** [comment]
Well using the first chapter last chapter would require you to go back and forth constantly as well as having to wait for an epub to finish packing inbetween which can become really time consuming, reptitive, and needs constant manuel input. What I'm suggesting is just putting like 1 or 2 checkpoints at places where you want the current epub to finish and a new one to start automatically. This is so you just have to do it once and you can leave while webtoepub splits the book for you.

**Comment by dteviot** [comment]
@JeremyStarten
I believe I've fixed it so you can do multiple downloads at the same time now.
That said, I think you're asking for is a way to say:  "Process this list of URLs into multiple epubs."
If you can suggest a User Interface for doing this that is sufficienty obvious, I'll see what I can do.

In the meantime, I think you can use Calibre to split an epub into multiple books.  So, you could get WebToEpub to collect all the chapters in a single fetch, and then use Calibre to split it.

**Comment by dteviot** [comment]
@JeremyStarten
Closing due to lack of response.

**Comment by dipique** [comment]
> [@JeremyStarten](https://github.com/JeremyStarten) I believe I've fixed it so you can do multiple downloads at the same time now. That said, I think you're asking for is a way to say: "Process this list of URLs into multiple epubs." If you can suggest a User Interface for doing this that is sufficienty obvious, I'll see what I can do.

I would have liked this too, but I won't reopen it for myself. But I will suggest a UI that would make sense to me.

* Add a "Split into volumes" checkbox
* If selected, the user sees a list of identified volumes, each of which shows its chapter range. Each has a checkbox that can be selected for it to be included in the export. The user can also enter a name and range to add a new volume to the list (for "custom" volumes). This is assuming that volumes can either be pre-configured or automatically detected. For example, if not manually configured, for Wandering Inn you might say that Volume N is everything >= the first instance of N.?? and < the first instance of (N+1).??. I've vaguely aware that there is already series-specific configuration, and volume detection is the kind of thing that could be stored either as an interface js function (for detection) or just json (for manual volume creation).

In any case, from an export perspective, Pack to ePub would now regard this as multiple jobs (essentially running copies of the job with different ranges). So above the existing progress bar, it might have the text "Job 1 of 6 - Volume 3" (if Volume 3 were the first job being exported). They would just run in sequence. And you'd probably want a replacement text variable added for volume name in the output filename, but that'd more of a nice-to-have.

If you want to avoid the multi download issue, you could generate all epubs and have them downloaded as a zip file.

I think that's all the hairy UI stuff.

**Comment by gamebeaker** [comment]
@dteviot i am sorry for no response i forgot it. Will have a look now.

edit: mistook the issue for this PR #2524
