### ISSUE TITLE
[BUG] Packing epub fails

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#18]
Uhm, I got this today, while trying out the 0.0.0.6 release.

![bs](https://cloud.githubusercontent.com/assets/1866248/16361849/b0a5f0a2-3b9d-11e6-8658-71504d762d54.png)

I tried the Zashikiwarashi vol 9 before this one, and it did pack it.

Btw: I tried with 0.0.0.7 (sonako) manually installing it, the same happens both on firefox and chrome.
[google store has  0.0.0.6 avail right now, as for mozilla I can't even find it]

**Comment by belldandu** [comment]
Will be fixed in 0.0.0.8

**Comment by typhoon71** [comment]
Faaast! Thanks.
As you can see, the most I can do to help is finding issues.
Hey, 2nd epub I tried on the plugin got an issue! XD

**Comment by belldandu** [comment]
@dteviot @typhoon71 fixed in #19

**Comment by belldandu** [comment]
@typhoon71 if you no longer get this issue in 0.0.0.7 then please close this.

**Comment by typhoon71** [comment]
OK, packing works now, closing.
