### ISSUE TITLE
Issue w/Gravity Tales Parser

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#182]
(This is using the Chrome Extenstion Version)

So when creating an epub for Gravity Tale it gives the error "Error: Could not find content element for web page 'http://gravitytales.com/novel/the-storys-name#null'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:341:27" or something like that. Also it seems that the error is that it decides to every story link and information link around. It looks like this:

> Got it!
> More info
> Read translated Chinese and Korean light novels
> Abyss Domination
> Ace of Ace
> .
> .
> .
> Login
> (RRS)
> Donor Hall of Fame
> Chapter One
> Chapter Two
> Chapter Three

Just manually removing the top part
> Got it!
> More info
> Read translated Chinese and Korean light novels
> Abyss Domination
> Ace of Ace
> .
> .
> .
> Login
> (RRS)
> Donor Hall of Fame

and keeping
> Chapter One
> Chapter Two
> Chapter Three

Causes it to work like normal.

**Comment by dteviot** [comment]
Site changed layout. 
Links to chapters were no longer in expected place.
Parser was falling back to all hyperlinks.
Updated parser with new location to check for hyperlinks.
