### ISSUE TITLE
Suggestion for a Gravity Tale Chapter Header Change

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#183]
When an epub is successful made w/a Gravity Tale story everything is ok.

However, there is a kinda annoying thing at least to me. Every chapter has a bold **"Story Name"** above it then the chapter name. In my opinion, it should have a bold **"Chapter Name"** and not having the Story Name repeating in every chapter. 

This is a problem because when skimming through a story or not paying as much attention you lose where you are. Also since the **"Story Name"** uses header 1, epub readers who generate their own table of contents will just give you a list of:

> Story Name
> Story Name
> Story Name
> .
> .
> .

Also, it makes it hard to change the epub table of contents as well.

It just seems like something unnecessary because we already know the story name.

**Comment by dteviot** [comment]
D'oh! Fixed.
