### ISSUE TITLE
Epub file not always saved to disk.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#185]
Reported by @typhoon71
> On Chrome, when WebToEpub attempts to report an issue with collecting an EPUB, the download of the epub fails.

> Steps to reproduce
> 1. In Chrome, set Settings -> Downloads -> Location to "D:\"
> 2. In chrome, go to https://zirusmusings.com/gcr-toc/
> 3. Click on the WebToEpub button on toolbar
> 4. Click the "Unselect All" button
> 5. Check button for URL https://pirateyoshi.wordpress.com/gcr2-prologue/
> 6. Click "Pack EPUB"
> 7. Screen shows "Fetch of URL 'https://discordapp.com/invite/YSBTnHe' returned HTML, expected an image.", but epub does not download.

Additional notes:
1. Refer https://github.com/dteviot/WebToEpub/issues/184#issuecomment-397859355 for more details
2. If ask where to save each file before downloading is set, it works.
3. I'm not able to reproduce the problem.

**Comment by dteviot** [comment]
@typhoon71
1. I'm still not able to reproduce the problem.
2. Are you running incognito mode?
3. I'm suspecting it may be some interaction with the permissions on the directory.  If you change the destination to the normal downloads location (usually C:\Users\&lt;YourUsername&gt;\Downloads) and turn off the "Ask where to save..." option does it work?
4. Open the file Download.js in the extension and replace the function saveOnChrome  with the following
```javascript
    static saveOnChrome(options, cleanup) {
        return new Promise(resolve => {
            chrome.downloads.download(options, 
                downloadId => Download.onDownloadStarted(downloadId, 
                    () => { 
                        const tenSeconds = 10 * 1000;
                        setTimeout(cleanup, tenSeconds);
                        resolve(); 
                    }
                )
            );
        }
    }
```
And let me know if this fixes the problem.  (Note this code doesn't work on chrome in incognito mode.) And it should force "Save As" to always be requested.

**Comment by dteviot** [comment]
@typhoon71  
Sorry, typo in sample code.  (Forgot to test before sending.  Corrected version
```javascript
    static saveOnChrome(options, cleanup) {
        return new Promise(resolve => {
            chrome.downloads.download(options, 
                downloadId => Download.onDownloadStarted(downloadId, 
                    () => { 
                        const tenSeconds = 10 * 1000;
                        setTimeout(cleanup, tenSeconds);
                        resolve(); 
                    }
                )
            );
        });
    }
```

**Comment by typhoon71** [comment]
2. I wasn't using incognito mode

3. I don't have any special permission on D:, but I gave this a try.
a) I changed the download path to the defaut dir (C:\Users\YourUsername\Downloads), tested and it works.
b) so I changed it back to D:, and it still works!

It makes no sense; it wasn't fixed by a reboot since the issue survived between reboots, at least I think so.
The crome setup was a clean one, fresh profile, and it stopped working suddenly. 
Sorry to make you lose valuable time.

4. I tested the provided code and the addon behaves like firefox with it, opening a save as window.
Why doesn't firefox save without dialog anyway? Permissions?

**Comment by dteviot** [comment]
@typhoon71 
> Sorry to make you lose valuable time.
It wasn't a waste of my time.
If there's an issue, I'd like to know about it as soon as possible.
Anyway, in this case, it has motivated me to change the download code, which fixes at least one other outstanding bug.  (Possibly two).

> Why doesn't Firefox save without dialog anyway?
Because Firefox (and the above code I sent you) save file using the Downloads API, instead of a nasty hack via a &lt;a&gt; tag.  And I've set the API to open the Save As dialog (hich gives fewer issues.
