### ISSUE TITLE
Request Patreon Support

### ISSUE THREAD

**Issue by collierc** [dteviot/WebToEpub#186]
Hi, I use this all the time! I may be overlooking support for patreon but I can't seem to get it to work correctly.

**Comment by dteviot** [comment]
You'll need to give me more information.
Please describe:
1. what you do, so I can reproduce what you did.  (At minimum, give me the URLs that don't work.)
2. what happens
3. What you think should happen.

**Comment by dteviot** [comment]
@collierc
I'm closing this due to no response from you.  Feel free to reopen and supply additional information when you can.
