### ISSUE TITLE
Request parser for creativenovels.com and noveluniverse.com

### ISSUE THREAD

**Issue by diablo348** [dteviot/WebToEpub#187]
https://creativenovels.com/ and https://www.noveluniverse.com/
they have a lot of novels, and Novel Universe seems to be copying Qidian International's website

also is it possible to grab all link from toc like this?
http://zenithnovels.com/starchild-escapes-arranged-marriage/

**Comment by dteviot** [comment]
@diablo348

Done.  Version 0.0.0.52 has been uploaded to Chrome and Firefox stores.
