### ISSUE TITLE
Suggested improvement to wuxiaworld behavior.

### ISSUE THREAD

**Issue by LaineOtto-Rognlie** [dteviot/WebToEpub#189]
Announcements on wuxiaworld cause the extension to only grab the announcement, not the entire chapter text. I found a fix by setting: Class is fr-view.  Might be something to look at? Anyways, thanks for the wonderful extension!

**Comment by dteviot** [comment]
@LaineOtto-Rognlie  
I'd be happy to look into it.  
To save me some time, please give me the URL of a page that has an announcement.  
Or better yet the URLs of several pages with announcements.

**Comment by LaineOtto-Rognlie** [comment]
https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens/issth-book-1-chapter-1
https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens/issth-book-1-chapter-2
https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens/issth-book-1-chapter-3
https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens/issth-book-1-chapter-4
https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens/issth-book-1-chapter-5

This is the only story I've read on this site, but I looked and it seems like it's on every story.

**Comment by wintersnew** [comment]
also this one has a problem
"https://www.wuxiaworld.com/novel/emperors-domination"
from 1 - latest (currently chapter 1593).
