### ISSUE TITLE
Problem with GravityTales 

### ISSUE THREAD

**Issue by RalphC11** [dteviot/WebToEpub#192]
When I tried to create epub of series So Pure So Flirtatious [http://gravitytales.com/novel/so-pure-so-flirtatious], it gave me error that it could not convert chapter from 105 onwards. 

Warning, unable to convert chapter 'Chapter 105: Also Use the Ability for Treasure Hunting' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-105' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 106: Like Her' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-106' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 107: Yang Ming Hit The Jackpot' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-107' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 108: Found A Treasure' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-108' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 109: Are You Sure?' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-109' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 110: Wealth at My Fingertips' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-110' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 111: Rock Gambling' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-111' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

Warning, unable to convert chapter 'Chapter 112: Lan Ling Has a Secret' from 'http://gravitytales.com/novel/so-pure-so-flirtatious/spsp-chapter-112' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

When I tried to create the following chapter manually by copy and paste in Sigil it didn't show any error. Can you please check it.

**Comment by dteviot** [comment]
How to investiage this error.
1. Rename the .epub file to .zip and unpack it.
2. Find the .xhtml file that coresponds to the chapter in the OPES\Text directory.  (There will be a xhtml file for each chapter in the epub.)
3. Open the file with Chrome (or Firefox) browser.

You'll see an error message.  In this case, for chapter 105 the error message is
> error on line 101 at column 146: Specification mandates value for attribute ms

If we look at this line in the xhtml with a text viewer, we can see that it is
```html
<p style="box-sizing: inherit; margin: 0px 0px 1em; outline: 0px !important; padding: 0px; color: rgb(68, 73, 80); font-family: " trebuchet="" ms",="" "helvetica="" neue",="" helvetica,="" tahoma,="" sans-serif;="" font-size:="" 14px;="" font-style:="" normal;="" font-variant-ligatures:="" font-variant-caps:="" font-weight:="" 400;="" letter-spacing:="" orphans:="" 2;="" text-align:="" start;="" text-indent:="" 0px;="" text-transform:="" none;="" white-space:="" widows:="" word-spacing:="" -webkit-text-stroke-width:="" background-color:="" rgb(255,="" 255,="" 255);="" text-decoration-style:="" initial;="" text-decoration-color:="" initial;"="">-- So Pure, So Flirtatious is a novel translated on Gravity Tales. Please visit: <a href="../Text/0000_Information.xhtml" rel="noreferrer noopener" tabindex="0" target="_blank" title="http://gravitytales.com/novel/so-pure-so-flirtatious" style="box-sizing: inherit; background: 0px 0px; text-decoration: none; outline: 0px !important;">http://gravitytales.com/novel/so-pure-so-flirtatious</a></p>

```
The bit that's blowing up is  ms",="" 
That's not valid for an attribute.  Looking at the original html for the element, it looks like the style element has been mangled.

There's not much I can do to automatically fix this problem.
What's happening is that EPUB2 requires files to be XHTML.  So WebToEpub needs to convert the HTML to XHTML.  And the parser just isn't smart enough to solve this case.
Note, if your EPUB viewer is not bothered by the malformed XHTML you can simply ignore these warnings from WebToEpub.
If your viewer does have a problem with it, then just remove the unwanted bits from the chapter notes.

**Comment by Synteresis** [comment]
@dteviot I believe this can be closed. GravityTales is no longer operating.
