### ISSUE TITLE
webnovel.com problem

### ISSUE THREAD

**Issue by diablo348** [dteviot/WebToEpub#193]
can't grab links from toc anymore

**Comment by yougotwill** [comment]
@dteviot I still get this issue.

**Comment by dteviot** [comment]
@diablo348, @yougotwill
Did you click on the "Table of Contents" tab before opening WebToEpub?
The ToC links are not loaded into the web page until you click on the tab.

**Comment by yougotwill** [comment]
@dteviot I did not sorry. Thanks for replying so soon :)
