### ISSUE TITLE
Another Parser Request: Novelspread

### ISSUE THREAD

**Issue by diablo348** [dteviot/WebToEpub#197]
I just found a good aggregator website:

https://www.novelspread.com

It looks neat and similiar to webnovel.com so I think we could get cleaner results from there.

**Comment by dteviot** [comment]
*Notes*
Seems to be REST based.

Example 
ToC page 
https://www.novelspread.com/novel/the-demonic-king-chases-his-wife-the-rebellious-good-for-nothing-miss

To obtain JSON for chapters, use the URL https://www.novelspread.com/novel/catalog/115
The got get ID for this, looks like it's in the following element 
```xml
<div class="main-body" data-novel="115" data-collcetion=""></div>
```

However, the HTML for each chapter does not have content.
e.g. Chapter 1 URL is 
https://www.novelspread.com/chapter/the-demonic-king-chases-his-wife-the-rebellious-good-for-nothing-miss/c-1-the-heart-wrenching-betrayal

But to obtain text, need URL https://www.novelspread.com/chapter/64327
ID can be found in 
```xml
<div class="text-body" data-chapter-id="64327"></div>
```

**Comment by dteviot** [comment]
@diablo348
I believe I have WebToEpub working for NovelSpread. Please go to https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode and follow the instructions for Loading from Source from the current development branch. Let me know if you have any issues.

**Comment by dteviot** [comment]
Closing. No response from requester.
