### ISSUE TITLE
Issues with the Blue Boxes in RRL

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#198]
This is mainly a problem on phones with smaller screens but happens sometimes on computer epub viewers as well.

Royal Road Legends let authors put blue boxes in their stories and sometimes it gets messed up when it is turned into an epub. Usually, the word is just cut off, but sometimes entire sentences or even paragraphs are messed up. This is mainly an issue when it used as a status window or something of the sort.

Example of this is in [Oblivion Online](https://www.royalroad.com/fiction/16577/oblivion-online). Chapters [3](https://www.royalroad.com/fiction/16577/oblivion-online/chapter/193268/chapter-3) and [12](https://www.royalroad.com/fiction/16577/oblivion-online/chapter/193951/chapter-12).

Chapter 3 Original: 
![untitled2](https://user-images.githubusercontent.com/39293934/45938400-679e1d00-bf7e-11e8-8e0e-5040e612cdb4.png)

Chapter 3 Phone:
![screenshot_20180923-221823](https://user-images.githubusercontent.com/39293934/45938435-d24f5880-bf7e-11e8-8cb4-6b0ff73c7357.png)

Chapter 12 Original:
![untitled4](https://user-images.githubusercontent.com/39293934/45938491-50136400-bf7f-11e8-94be-8c1c76ffe275.png)

Chapter 12 Computer:
![untitled3](https://user-images.githubusercontent.com/39293934/45938497-5dc8e980-bf7f-11e8-8cdb-b028993e895c.png)

(On the computer sometimes it offers a magnifine glass that opens a window to see the whole thing, but here it doesnt)

Another thing with the boxes is sometimes it shows the blue box and other times it doesnt. Here's an example of when it does on [Haven in a Dangerous World](https://www.royalroad.com/fiction/12373/haven-in-a-dangerous-world). Chapter [1](https://www.royalroad.com/fiction/12373/haven-in-a-dangerous-world/chapter/141463/11-reincarnation-force)

Chapter 1 Original:
![untitled5](https://user-images.githubusercontent.com/39293934/45938592-31619d00-bf80-11e8-8d58-0a6899aa814d.png)

Chapter 1 Phone:
![screenshot_20180923-222707](https://user-images.githubusercontent.com/39293934/45938609-5d7d1e00-bf80-11e8-8613-d8e278a63a75.png)

The second this is not as important but helps because sometimes the change is not obvious.

**Comment by dteviot** [comment]
Closing, as issues have been moved to 
- https://github.com/dteviot/WebToEpub/issues/199
- https://github.com/dteviot/WebToEpub/issues/200
- https://github.com/dteviot/WebToEpub/issues/201
