### ISSUE TITLE
[Enhancement] Add wayback machine archival support.

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#2]
Since the wayback machine tries to preserve the integrity of each site there should be no real change to any parser stuff except for maybe small parts. 
```parserFactory.register("web.archive.org/web/*someregexthatallowsnumbersonly*/http://www.baka-tsuki.org", function() { return new BakaTsukiParser() });```

This is just a suggestion and it would be neat to have implemented. I emailed you already about this so yeah.

**Comment by belldandu** [comment]
Looked into this some more and decided to change it up a bit.

```parserFactory.register({url: "www.baka-tsuki.org", allowedArchives: ["web.archive.org"]}, function() { return new BakaTsukiParser() });```

Also after doing some testing i noticed that sometimes the archive site gives a 
![gen](https://cloud.githubusercontent.com/assets/5639384/16183782/ba6c07e4-3683-11e6-9a11-79238671bc4c.png)
I'm Guessing there is a rouge image that doesn't follow your image scheme somewhere on the archival page. Which means you would have to make sure that its actually following the image scheme before putting it in the list of images you want to parse.

**Comment by dteviot** [comment]
URL that has problem please?
If you can identify the rouge image, even better.

**Comment by belldandu** [comment]
https://web.archive.org/web/20140803022146/http://www.baka-tsuki.org/project/index.php?title=Toaru_Majutsu_no_Index:Volume1
https://web.archive.org/web/20140805114418/https://www.baka-tsuki.org/project/index.php?title=CubexCursedxCurious:Volume1
https://web.archive.org/web/20140810093554/http://baka-tsuki.org/project/index.php?title=High_School_DxD:Volume_1
https://web.archive.org/web/20140803143924/https://www.baka-tsuki.org/project/index.php?title=No_Game_No_Life:Volume_1
Etc etc

**Comment by belldandu** [comment]
Well that's quite odd. It looks like its having trouble replacing the cover image file on the archive because that's the url returned. It doesn't matter which file i select as the cover either.

**Comment by belldandu** [comment]
It looks like this issue is occuring on the thumbnail images. Specifically the ones that appear twice on the page (for whatever reason). I would suggest making the list ignore duplicates as thats the underlieing issue here. The parent element is already replaced and then it tries to replace it a second time when none exists. @dteviot

**Comment by belldandu** [comment]
At this point the easiest thing to do is to check if parentElement is not null.
If its not then continue if it is then ignore it as that shouldn't be possible under normal circumstances.

**Comment by belldandu** [comment]
Ok gonna submit a pull request now.

**Comment by dteviot** [comment]
Well, this is embarrassing.
I found and fixed that problem yesterday.
```
let img = util.getElement(dom, "img")
```

It's in the sonako branch.
Also, why are you doing this
```
    var isWebArchive = function(hostName) {
        return extractHostName(hostName).startsWith("web.archive.org") ? 1 : 0;
    }
```
rather than
```
    var isWebArchive = function(hostName) {
        return extractHostName(hostName).startsWith("web.archive.org");
    }
```

**Comment by belldandu** [comment]
oh woops i will fix that real quick Also

```let img = util.getElement(dom, "img")``` 

I removed because your getting the waterd down version of the image when you should be getting the full image. which you do like this.
```
BakaTsukiImageCollector.prototype.updateImageInfoFromImagePage = function(dom, imageInfo) {
    let div = util.getElement(dom, "div", e => (e.className === "fullMedia"));
    let a = util.getElement(div, "a");
    let img = new Image();
    imageInfo.imagefileUrl = img.src = a.href;
    imageInfo.height = img.height;
    imageInfo.width = img.width;
    return imageInfo;
}
```

**Comment by belldandu** [comment]
Woops dont merge yet for some reason thats not working like it should.

**Comment by belldandu** [comment]
Hrm its grabbing the url properly so why doesnt it show in calibre?

**Comment by belldandu** [comment]
Ok figured that one out. Can't beleive i forgot about that. 
```
BakaTsukiImageCollector.prototype.updateImageInfoFromImagePage = function(dom, imageInfo) {
    let div = util.getElement(dom, "div", e => (e.className === "fullMedia"));
    let a = util.getElement(div, "a");
    let img = new Image();
    imageInfo.imagefileUrl = img.src = a.href;
    img.onload = function() {
        imageInfo.height = img.height;
        imageInfo.width = img.width;
        return imageInfo;
    }
}
```

**Comment by belldandu** [comment]
Ok Pushed
