### ISSUE TITLE
Lower row(s) of tables are clipped/removed when table is too long to fit on single "page".

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#200]
Royal Road Legends let authors put blue boxes in their stories and sometimes it gets messed up when it is turned into an epub. Usually, the word is just cut off, but sometimes entire sentences or even paragraphs are messed up. This is mainly an issue when it used as a status window or something of the sort.

Example of this is in [Oblivion Online](https://www.royalroad.com/fiction/16577/oblivion-online). Chapter [12](https://www.royalroad.com/fiction/16577/oblivion-online/chapter/193951/chapter-12).

Chapter 12 Original:
![untitled4](https://user-images.githubusercontent.com/39293934/45938491-50136400-bf7f-11e8-94be-8c1c76ffe275.png)

Chapter 12 Computer:
![untitled3](https://user-images.githubusercontent.com/39293934/45938497-5dc8e980-bf7f-11e8-8cdb-b028993e895c.png)

**Comment by dteviot** [comment]
@JeremyStarten
This might be an issue with the pagination logic of your epub viewer.
Can you please tell me which one it is? (and ideally, supply a URL to download it from.)

**Comment by JeremyStarten** [comment]
I open it with Microsoft Edge. It basically opens a tab with the book in it.

**Comment by dteviot** [comment]
@JeremyStarten
Seems to be bug with Edge.  Calibre does not show issue.
I've created a bug report for Edge.  https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19154870/

**Comment by dteviot** [comment]
Update.  Edge no longer supports viewing epubs.

**Comment by dteviot** [comment]
@JeremyStarten
Closing.  Edge no longer supports viewing epubs.
