### ISSUE TITLE
Tables from RoyalRoad sometimes have a blue background

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#201]
An annoying thing with the boxes is sometimes it shows the blue box and other times it doesn't. Here's an example of when it does on [Haven in a Dangerous World](https://www.royalroad.com/fiction/12373/haven-in-a-dangerous-world). Chapter [1](https://www.royalroad.com/fiction/12373/haven-in-a-dangerous-world/chapter/141463/11-reincarnation-force)

Chapter 1 Original:
![untitled5](https://user-images.githubusercontent.com/39293934/45938592-31619d00-bf80-11e8-8d58-0a6899aa814d.png)

Chapter 1 Phone:
![screenshot_20180923-222707](https://user-images.githubusercontent.com/39293934/45938609-5d7d1e00-bf80-11e8-8613-d8e278a63a75.png)

**Comment by dteviot** [comment]
@JeremyStarten
Note, you could use Calibre to alter the CCS file inside an existing epub, rather than recreate the epub with WebToEpub.  (The CCS file is found at OEBPS/Styles/stylesheet.css inside each epub.)
And if you could confirm I correctly understand the problem, that would be appreciated.

**Comment by JeremyStarten** [comment]
Oh so basically if you go back to one of the previous issues on the blue boxes, you will see they are not colored in. This used to be an extension of the longer version that was split up noting how sometimes it would show the colored background of the box and other times it wouldn't. This is just an example of when it does.

**Comment by dteviot** [comment]
@JeremyStarten
Closing,  As mentioned above, there's not much I can do to fix.
If you've got any ideas, feel free to reopen and tell me them.
