### ISSUE TITLE
Suggestion: Add website

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#214]
1. https://comrademao.com/                       [better MTL than poor lnmtl]
2. https://m.chinesefantasynovels.com/     [Complementer with wuxiaworld.co "which has few novels only" both have title each chapter]

Thanks

**Comment by dteviot** [comment]
@3dycosmo  Committed to ExperimentalTabBranch.
Please install from source and try.  The Chairmanmao site was difficult, so may not work for all novels/chapters.  Please let me know if there are any issues.

**Comment by 3dycosmo** [comment]
Thanks a lot, I go check it out
