### ISSUE TITLE
DefaultParser does not remove <o:p> tags

### ISSUE THREAD

**Issue by dadelion** [dteviot/WebToEpub#216]
I have noticed problem while trying to download novel chapters with <o:p> code. Is there any way to fix it?

Sample of error message:
"Warning, unable to convert chapter 'XX' from 'URL XXX' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
Conversion error message was: (This page contains the following errors:error on line 3 at column 161: Namespace prefix o on p is not defined
Below is a rendering of the page up to the first error.)"

PS. I am not a developer just a normal bookworm that stumbled by this wonderful extension :)

**Comment by dadelion** [comment]
I use it on this site https://my.dek-d.com/dek-d/writer/view.php?id=559528
So after I downloaded file to epub via extension I have to import to Calibre and replace <o:p> with <p> ?

**Comment by dteviot** [comment]
@dadelion
> replace &lt;o:p&gt; with

&lt;o:p&gt; tags are paired with a closing tag  &lt;/o:p&gt;.  You will need to delete both.  (i.e. replace them with an empty string)

**Comment by dteviot** [comment]
That said, looks like you have this problem because you're using the default parser and it doesn't remove the windows garbage.  I should have that fixed in a few days, if you'd like to wait.

**Comment by dteviot** [comment]
@dadelion WebToEpub at Chrome store has been updated.
