### ISSUE TITLE
Suggestion: new icon

### ISSUE THREAD

**Issue by asifm91** [dteviot/WebToEpub#217]
The extension icon looks very poor, especially in the dark mode/theme. I was thinking something like the following may be more appropriate. I've designed this icon based on a typical ebook reader:

![icon](https://user-images.githubusercontent.com/31449072/47452608-94826180-d7c2-11e8-9b4c-06e6f0b43ad2.png)

What do you think? Any comments/suggestion about its design/color?

**Comment by dteviot** [comment]
See: https://github.com/dteviot/WebToEpub/issues/33

**Comment by snnsnn** [comment]
This does not communicate webpage to epub conversion. Plus, comic sans font is one of the most hated fonts.

**Comment by snnsnn** [comment]
I was planning on designing an icon that hints web-page to ebook conversion, but detailed icons seemed impractical for small sizes like 16px. So I go with something clearly visible even for small sizes. 

Dark transparent background:
![dark-icon-128](https://user-images.githubusercontent.com/16473630/49040250-148d5400-f1d3-11e8-83d1-bbee8c261787.png)

Dark solid background:
![dark-icon-128-solid-bg](https://user-images.githubusercontent.com/16473630/49040251-148d5400-f1d3-11e8-9795-6611cd848aec.png)

Light transparent background:
![light-icon-128](https://user-images.githubusercontent.com/16473630/49040253-1525ea80-f1d3-11e8-8923-f40d123738c1.png)

Light with solid background:
![light-icon-128-solid-bg](https://user-images.githubusercontent.com/16473630/49040254-1525ea80-f1d3-11e8-831e-1614dc317cea.png)

If you like I can submit a pull request including raw files in gravit.

**Comment by dteviot** [comment]
@snnsnn
I like the Dark transparent background.
I don't know how to switch icons between dark and light modes, however.

**Comment by snnsnn** [comment]
> I don't know how to switch icons between dark and light modes, however.

I am not familiar with chrome extension api, but a quick check shows you need to implement user setting.

https://stackoverflow.com/questions/36784029/chrome-extension-get-current-theme-background

I think dark transparent background will work for light and dark backgrounds equally well.

**Comment by typhoon71** [comment]
Really nice icon, thanks a lot.

**Comment by snnsnn** [comment]
@typhoon71 Thank you. It was a pleasure.
