### ISSUE TITLE
Spurious link after images with some readers (Baka-Tsuki)

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#22]
In sumatrapdf there's a link after every image.
Happens to both the images at the start and those in the middle of chapters.
Doesn't happen in calibre (or sigil, but that's not a reader).
I checked in icecream too: the starting images are replaced by a bunch of links, exept the cover which is fine; the images in the middle of chapters are fine too.

**Comment by belldandu** [comment]
Most likely these readers are attempting to parse the desc tag. This is not correct behavior. I suggest filing bug reports to those readers.

**Comment by typhoon71** [comment]
OK, I suppose it makes sense to file a bug to those readers (or maybe check if there's some more recent releases of them).
I suspected it could be something on the reader side since sigil was ok. But I hoped... :P
Btw, do you have any suggestion for an epub reader that is complaint?

**Comment by belldandu** [comment]
Well i always recommend calibre because its usable on even mobile (although some features are disabled). However i do still recommend reporting these bugs so that other people do not experience the same issues.

**Comment by typhoon71** [comment]
OK, good to know calibre is loved. 
Also, thanks to this I noticed my calibre wasn't up to date so I'll test again with the newer one and if the issue persist I wil report the bug to them. l suppose I can link your answer right? (the stuff about the standard)

**Comment by belldandu** [comment]
Yep

**Comment by dteviot** [comment]
@belldandu,
I agree that our behaviour is perfectly valid.
However, there may be people who can't update their readers and this will be fustrating for them.  So I suggest we add an option to "Not include source URL in images", or something like that.  Not a high priority however.

**Comment by belldandu** [comment]
@dteviot if we do that than it should be a part of #14

**Comment by dteviot** [comment]
@belldandu.
> if we do that than it should be a part of #14

Agreed.  Plus, we've got a request to do so.

**Comment by belldandu** [comment]
Sorry tagged that wrong.

**Comment by dteviot** [comment]
Added option to turn off the description in the <image> tag.

**Comment by belldandu** [comment]
Added bug in reader tag because of https://github.com/sumatrapdfreader/sumatrapdf/issues/567 No need to reopen this issue.
