### ISSUE TITLE
If packing process errors out "pack Epub" button gets disabled, making user unable to retry

### ISSUE THREAD

**Issue by snnsnn** [dteviot/WebToEpub#223]
When you  have error during packing process, "pack epub" buttons get disabled and there is no way to retry it, even if you fixed the issue causing the error. So user has to start the whole thing all over again or manually remove "disabled" attribute from the button via dev tools. 

I was asking if there is there a way not to set the button attribute disabled, so that we can retry in case of failure.

**Comment by dteviot** [comment]
@snnsnn
> When you have error during packing process, "pack epub" buttons get disabled

That's not exactly correct.
The "pack epub" button is disabled as soon as you click on it.  (See function fetchContentAndPackEpub() in main.js) 
This is to stop users double clicking the button and having the parser try to create two epubs at the same time.  (Which doesn't go well.)
If the web pages are successfully collected, then the Pack Epub button is enabled in function fetchWebPages() (file Parser.js)  However, if an error occurs, the button is not enabled due to the error handling case bypassing the button enabling code.  
Failing tor re-enable the button is might be an oversight on my part. On the other hand, I'm not sure what needs to be done to reset the UI to correctly display progress for a second attempt.

**Comment by snnsnn** [comment]
> That's not exactly correct.

You are right, I should have written remain disabled.

> I'm not sure what needs to be done to reset the UI to correctly display progress for a second attempt.

`<button id="packEpubButton" class="expandedButton" disabled>Pack EPUB</button>` You can remove "disabled" attribute from the button, whether packing process succeeds or errors.

**Comment by dteviot** [comment]
@snnsnn
> I'm not sure what needs to be done to reset the UI to correctly display progress for a second attempt

I was thinking of how to adjust the state of the "chapters to collect" list.  There are icons indicating which ones have been fetched.  I'm not sure if anything else on the UI needs to be adjusted so that if another "Pack Epub" is done everything displays correctly.

**Comment by snnsnn** [comment]
I used react.org website for experimenting:

For the sake of experimenting, I did not remove external links from the urls list:
`<a href="https://reactjs.org/">React</a>
<a href="https://reactjs.org/docs/getting-started.html">Docs</a>
<a href="https://reactjs.org/tutorial/tutorial.html">Tutorial</a>
<a href="https://reactjs.org/community/support.html">Community</a>
<a href="https://reactjs.org/blog/">Blog</a>
<a href="https://reactjs.org/versions">v16.6.1</a>
<a href="https://github.com/facebook/react/">GitHub</a>
<a href="https://reactjs.org/redirect-to-codepen/hello-world">CodePen</a>
<a href="https://codesandbox.io/s/new">CodeSandbox</a>
<a href="https://raw.githubusercontent.com/reactjs/reactjs.org/master/static/html/single-file-example.html">download this HTML file</a>
<a href="https://reactjs.org/docs/add-react-to-a-website.html">add React to an HTML page in one minute</a>
<a href="https://reactjs.org/docs/create-a-new-react-app.html">several JavaScript toolchains</a>
<a href="https://reactjs.org/docs/hello-world.html">guide to main concepts</a>
<a href="https://www.taniarascia.com/getting-started-with-react/">this overview of React by Tania Rascia</a>
<a href="http://reactfordesigners.com/">these resources</a>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript">this JavaScript overview</a>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript">MDN</a>
<a href="http://javascript.info/">javascript.info</a>
<a href="https://reactjs.org/docs/thinking-in-react.html">Thinking in React</a>
<a href="https://reactjs.org/community/courses.html">a list of commonly recommended resources</a>
<a href="https://reactjs.org/docs/context.html">context</a>
<a href="https://facebook.github.io/react-native/">React Native</a>`

I used 'article class is css-174qq1k' settings for selecting scraping area.

What I observed when I manually removed disabled attribute  from the Pack Epub button and clicked on it:
- Button becomes clickable (obviously)
- when clicked on it, errored link is removed automatically from the chapter Urls list and packing process started from the beginning.

I don't know the internals but the result is favorable for me, because I don't have to remove erroring link manually. Usually some overlooked external links are to blame for the error.
