### ISSUE TITLE
Asian Hobbyist isn't working

### ISSUE THREAD

**Issue by yougotwill** [dteviot/WebToEpub#225]
Not sure if the site has changed since the parser was updated? Tried urls https://www.asianhobbyist.com/hs-229/ and https://www.asianhobbyist.com/category/heavenly-star/

Keep up the good work 👍

**Comment by dteviot** [comment]
@yougotwill 
This site is something of a pain as many of the stories are formatted differently.
And I haven't tested every story.
So congratulations, you've found yet another format.  
I'll see what I can do.  This may take a few days.

**Comment by 3dycosmo** [comment]
> Not sure if the site has changed since the parser was updated? Tried urls https://www.asianhobbyist.com/hs-229/ and https://www.asianhobbyist.com/category/heavenly-star/
> 
> Keep up the good work 👍

just go novelplanet, the most complete and currently trying adding title on each chap

**Comment by yougotwill** [comment]
> @yougotwill
> This site is something of a pain as many of the stories are formatted differently.
> And I haven't tested every story.
> So congratulations, you've found yet another format.
> I'll see what I can do. This may take a few days.

@dteviot Thank you. Yeah that site is a disaster. Which I why I'm so grateful for this extension 😄 

> > Not sure if the site has changed since the parser was updated? Tried urls https://www.asianhobbyist.com/hs-229/ and https://www.asianhobbyist.com/category/heavenly-star/
> > Keep up the good work 👍
> 
> just go novelplanet, the most complete and currently trying adding title on each chap

@3dycosmo Nice thanks for the source. 👍

**Comment by yougotwill** [comment]
@dteviot Thank you so much 👏
