### ISSUE TITLE
Errors Royal Road

### ISSUE THREAD

**Issue by forlrn** [dteviot/WebToEpub#227]
Error message below
Retry Skip
--
Error: Error: Fetch of image 'https://hydra-media.cursecdn.com/smite.gamepedia.com/thumb/a/ad/SkinShot_SunWukong_DarkLord.png/389px-SkinShot_SunWukong_DarkLord.png' for page 'https://www.royalroad.com/fiction/10058/what-is-it-like-to-be-eternal-completed/chapter/126809/chapter-64-the-fall' failed with network error 504. This is an intermittent error. Trying again may succeed.     at FetchImageErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:33:19)     at Function.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:122:33)     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:116:31
----------------------------------------------------------------------------------------------------------------
This is killing the task

**Comment by dteviot** [comment]
@forlrn

I don't know what you're asking of me.

As the error message says, when WebToEpub tired to read page https://www.royalroad.com/fiction/10058/what-is-it-like-to-be-eternal-completed/chapter/126809/chapter-64-the-fall it found the image tag https://hydra-media.cursecdn.com/smite.gamepedia.com/thumb/a/ad/SkinShot_SunWukong_DarkLord.png/389px-SkinShot_SunWukong_DarkLord.png.  WebToEpub then attempted to retrieve the image (so it could be included in the EPUB) and received a HTTP 504 error.  504 is a (possibly) intermittent error, which might work if you try again.  (See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504),  So, WebToEpub gives you the option of either trying again to fetch the image, or skipping the image.

Note There does appear to be a bug in the code that handles the retry case.  (So retry fails with a different error.)  However, 
1. I've just posted an updated WebToEpub (version 0.0.0.62) that fixes that problem, and
2. You haven't included the error message for that problem.  So I assume that's not your issue.

Please provide more details of the problem.  (e.g. Describe what happens, and how this differs from what you think should happen.)

**Comment by dteviot** [comment]
@forlrn 
> This is killing the task

D'oh!  Sorry, I missed that bit.
I believe that's the bug I fixed that I mentioned in previous post.

**Comment by dteviot** [comment]
@forlrn 
I believe I've fixed the problem, so closing.
Please reopen if I'm in error.
