### ISSUE TITLE
[Error] LNMTL

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#229]
https://lnmtl.com/novel/mad-cultivator [All LNMTL Pages]
--
Error: Fetch of URL 'http://lnmtl.com/chapter?page=1&volumeId=5708' failed with network error Failed to fetch.     at FetchErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31)     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:111:45

**Comment by dteviot** [comment]
@3dycosmo  It's working for me (using Chrome).
Error message suggests a problem getting the Table of Contents for story.
I suggest using the network activity tab to get more error information.
Steps.
1. When WebToEpub shows the above error.
2. Open the network activity tab.  https://developers.google.com/web/tools/chrome-devtools/network-performance/
3. Reload the WebToEpub tab showing the error.  (i.e. Go to WebToEpub Tab, right click and select "reload"
4. Look at the request in the network tab for more detailed error information.

**Comment by 3dycosmo** [comment]
> @3dycosmo It's working for me (using Chrome).
> Error message suggests a problem getting the Table of Contents for story.
> I suggest using the network activity tab to get more error information.
> Steps.
> 
> 1. When WebToEpub shows the above error.
> 2. Open the network activity tab.  https://developers.google.com/web/tools/chrome-devtools/network-performance/
> 3. Reload the WebToEpub tab showing the error.  (i.e. Go to WebToEpub Tab, right click and select "reload"
> 4. Look at the request in the network tab for more detailed error information.

it's fine now, Thanks
