### ISSUE TITLE
[Error] Skip and Retry

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#234]
Please, make option Retry and Skip (#160)  auto by default

Retry Skip
--
Error: Error: Fetch of image 'https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&gadget=a&no_expand=1&resize_h=0&rewriteMime=image%2F*&url=https%3a%2f%2fwww.baka-tsuki.org%2fproject%2fthumb.php%3ff%3dHorizon6-B005_001.png%26width%3d300%26width%3d1784' for page 'https://novelplanet.com/Novel/Kyoukai-Senjou-no-Horizon/v6-b-preface?id=300756' failed with network error 502. This is an intermittent error. Trying again may succeed.     at FetchImageErrorHandler.onResponseError (chrome-extension://lmbnpjbchobaogjkleaobhkonglfjnjm/js/HttpClient.js:33:19)     at Function.checkResponseAndGetData (chrome-extension://lmbnpjbchobaogjkleaobhkonglfjnjm/js/HttpClient.js:119:45)     at chrome-extension://lmbnpjbchobaogjkleaobhkonglfjnjm/js/HttpClient.js:113:31

**Comment by dteviot** [comment]
@3dycosmo  You said
> Please, make option Retry and Skip (#160) auto by default

I don't understand.

**Comment by 3dycosmo** [comment]
> @3dycosmo You said
> 
> > Please, make option Retry and Skip (#160) auto by default
> 
> I don't understand.

we need to click retry, so many times, why not make it auto retry until e.g. 10 times if still error retrieve images, then auto skip

**Comment by dteviot** [comment]
@3dycosmo
Unfortunately, it's not easy to tell what to do automatically.
It doesn't help that the code is complicated (the relevant words are "asynchronous", "recursive", "error handling") and difficult to test.
That said, I've committed a change to the ExperimentalTabMode branch to automatically retry a number of times before giving up and asking for help.
If you'd load from source and let me know if it helps, that would be appreciated.

**Comment by dteviot** [comment]
Closing, due to lack of response from @3dycosmo
