### ISSUE TITLE
[Error] Retrieve Comrademao

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#236]
https://comrademao.com/novel/wicked-soldier-king/
[All Comrademao pages]
--
Error: Error: Fetch of URL 'https://comrademao.com/wp-admin/admin-ajax.php?action=get_wdtable&table_id=3&wdt_var1=53640' failed with network error 500. This is an intermittent error. Trying again may succeed.     at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:33:19)     at Function.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:119:45)     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:113:31

N.B.
Can't retrieve all pages from Comrademao, need to manually show all chapters

**Comment by dteviot** [comment]
Site has changed params of "request chapters" AJAX call again.  It's changed from table_id=3 to table_id=4.
Fix is line 59 of file ComrademaoParser.js
I should have a fix shortly.  However, as you've discovered, just set the original ToC page to show "all chapters" and things will just work.
