### ISSUE TITLE
Removing non-text scripts/HTML (like comments and other page elements)

### ISSUE THREAD

**Issue by ezlinn** [dteviot/WebToEpub#238]
For a site where there's no parser found, the default parser doesn't remove page elements like comments, ads, or subscription panels. So each chapter gets a ton of clutter. 

Could there be an advanced option to detect/remove all non-text tags?

Examples of clutter:

```
<a rel="nofollow" href="#comment-1579" onclick="return addComment.moveForm( &quot;comment-1579&quot;, &quot;1579&quot;, &quot;respond&quot;, &quot;875&quot; )" aria-label="Reply to X">Reply <span><i></i></span></a>`

<script type="text/javascript"><![CDATA[
/* <![CDATA[ */
var WPGroHo = {"my_hash":""};
/* \]\]\> */
]]></script>
```

Sample site: http://www.ironteethserial.com/table-of-contents/

**Comment by dteviot** [comment]
Closing.  It's now possible to tell the default parser what elements to remove.
