### ISSUE TITLE
Remove "empty" <div> sections.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#24]
"Guest" wrote:

Using the "remove duplicate images" option leaves a bunch of empty
```html
<div>
	
		</div>
<div>
			
		</div>
```
scattered around in the illustrations html.
I mean, I guess it doesn't really affect the user-facing result so it's hardly high priority, but it does seem a wee bit untidy.

**Comment by belldandu** [comment]
Causes #28

**Comment by belldandu** [comment]
@dteviot can this be closed.

**Comment by dteviot** [comment]
I want to write a couple of test cases for it.

**Comment by belldandu** [comment]
ok

**Comment by belldandu** [comment]
@dteviot Have you added those test cases?

**Comment by dteviot** [comment]
Yes. https://github.com/dteviot/WebToEpub/commit/338e07bfd5b9768109786e3127f84ae11c383d2d
