### ISSUE TITLE
LNMTL [Error]

### ISSUE THREAD

**Issue by Maradar** [dteviot/WebToEpub#240]
Hello,

When I try the latest version of the plugin WebToEpub 0.0.0.65 on LNMTL it shows download window after every link after which once I click save it shows this error:
```
'Error: Could not find content element for web page 'https://lnmtl.com/chapter/talisman-emperor-book-9-chapter-898'.
    at chrome-extension://elafmbgpoefkmamjicnfbcgdnegeoofk/js/Parser.js:422:23
```
I tried it in many browsers (Latest chrome included) and it shows the same problem in all of them.
The page is https://lnmtl.com/novel/talisman-emperor

**Comment by dteviot** [comment]
@Maradar 

Looks like site has changed, there's no text for chapters until you logon to site, then it includes text for chapters.
Note, I don't know what it does if you try downloading lots of chapters, but when I logon and then try downloading 2 chapters it works.

**Comment by Maradar** [comment]
@dteviot 
Yes you are right once I logged in it works as it should. Thanks.
