### ISSUE TITLE
Import/Export Default Parser settings.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#242]
From typhoon71 (issue https://github.com/dteviot/WebToEpub/issues/202)
> The parser remembers the settings
Is it easy to save or export? Thinking of sharing it between browsers or just a backup of stuff one doesn't want to redo from scratch.

**Comment by dteviot** [comment]
@typhoon71
In latest commit to the ExperimentalTabMode branch I've added "Write Options to file" and "Read Options from file" buttons to the botton of the "Advanced Options" section.
These will read and write all options (including the Default Parser settings) to a file. So you can use this to copy the settings between browsers.
Please try it out and let me know what you think of it.

**Comment by typhoon71** [comment]
Late reply is late.
Anyway thanks for this, it'll soon be helpful to me.
