### ISSUE TITLE
[ADD] Scribblehub

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#243]
new webs, please add
https://www.scribblehub.com

**Comment by RalphC11** [comment]
+1

**Comment by dteviot** [comment]
@3dycosmo @RalphC11 
I believe I have a working parser for Scribblehub. Please go to https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode and follow the instructions for "Install from Source" from the current development branch. Let me know if you have any issues.
