### ISSUE TITLE
[ADD] Boxnovel

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#244]
Good and have the title on each chap, thanks

https://boxnovel.com/

**Comment by dteviot** [comment]
@3dycosmo

Instructions for writing a new parser:
- https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
- https://dteviot.github.io/Projects/webToEpub_CustomizingParserTemplate.html

**Comment by dteviot** [comment]
@3dycosmo Updated version posted to Chrome store
