### ISSUE TITLE
Scraping protection on pastebin

### ISSUE THREAD

**Issue by tellall** [dteviot/WebToEpub#245]
Will it be possible to add usage of Scraping API while scraping from pastebin.com ?
After few tries IP gets blocked when not using their Scraping API.
![screenshot_2019-02-02 pastebin com - access denied warning](https://user-images.githubusercontent.com/20305387/52169731-8fc43680-273d-11e9-9a32-1b8c5ab3bfb7.png)

**Comment by dteviot** [comment]
@tellall 
It may be possible.  Can you provide a typical URL that you'd want to collect?
Note to self: API spec https://pastebin.com/api_scraping_faq

**Comment by dteviot** [comment]
@tellall
After reading the documentation on the pastebin scraping API, it looks like it has two requirements:
- You need to have a LIFETIME PRO membership.
- You need to use a different URL to specify the pages to fetch.

Assuming you have the LIFETIME PRO membership, then you just need to use the correct URLs.
It looks like the change is convert URLs from
> https://pastebin.com/0CeaNm8Y

to
> https://scrape.pastebin.com/api_scrape_item.php?i=0CeaNm8Y

i.e. You replace "//pastebin.com/" with "//scrape.pastebin.com/api_scrape_item.php?i="
And you can do that in WebToEpub by 
1. On WebToEpub's page with list of URLs to fetch, Click on the "Edit Chapter URLs" button
2. Copy the resulting text to a text editor.
3. Do "serach and replace" to change the URLs
4. Paste the updated text back into WebToEpub
5. Click the "Apply Changes' button.

**Comment by dteviot** [comment]
@tellall
Please tell me why you closed this.  For example, did my above suggestion work?
Also, please give me a URL to a pastebin item that you'd like to convert to an epub? 
The reason I ask is that I'm thinking it may be possible to get it to work for people without a LIFETIME PRO membership by introducing a delay of perhaps 120 seconds per page fetch.
