### ISSUE TITLE
[Suggestion] Some rearranging and aestetical fixing.

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#246]
Here are a couple of mock-ups to improve the aestetics end coherency.
np if they won't get implemented, they're suggestin after all ;)

_Originally posted by @typhoon71 in https://github.com/dteviot/WebToEpub/issues/202#issuecomment-464498761_

**Before:**
![setup_now](https://user-images.githubusercontent.com/1866248/52918464-88815900-32f7-11e9-98fd-cae3db2f270d.png)

**After:**
![setup_mod](https://user-images.githubusercontent.com/1866248/52918467-920ac100-32f7-11e9-8674-caad7d195668.png)

- Here I resized pack button, moved the options button to the side, moved some of the chapter option buttons on the same line

**Before:**
![start_now](https://user-images.githubusercontent.com/1866248/52918472-a3ec6400-32f7-11e9-8f51-92438e391f8b.png)

**After:**
![start_mod](https://user-images.githubusercontent.com/1866248/52918475-a77feb00-32f7-11e9-85e3-6ebf893abd35.png)

- Here I resized the help button, renamed the finish button to something more general/intuitive, added 1px of white before the help text

The ideas are that:
- buttons should have the same height
- buttons should be on the same line if they are relevant to the same stuff
- text should have a bit of space before it, just òlike in the other boxes

What do you think?

**Comment by dteviot** [comment]
@typhoon71 
Thank you.

**Changed**
- Help button on Default Parser dialog same size as other buttons.
- Changed text on "Finished' button to "Apply"
- Add space to left of text in box
- Put chapter selection buttons all on same row

**Not changed**
- I'm keeping "Pack EPUB" button large, becuase new users need to find it.
- Not moving "Advanced Options" button, because I'm not sure how to align it.

**Comment by typhoon71** [comment]
I was expecting the Pack Epub button to stay big.

Btw, I just noticed the "box" labels some times have the ":", sometime they don't: I'd make their use consistent, personally  I'd be removing the ":", but being consistent between windows would be/look best.
