### ISSUE TITLE
Issue with novelonlinefull.com

### ISSUE THREAD

**Issue by wintersnew** [dteviot/WebToEpub#247]
It seems it cannot generate chapters from novelonlinefull.com. Even when I am already in table of contents area its still can't generate.

**Comment by dteviot** [comment]
@wintersnew
novelonllinefull.com seems to be an alias for novelonlinefree.com, which **is** handled by WebToEpub.
So, until I update WebToEpub, try https://novelonlinefree.com instead.

**Comment by wintersnew** [comment]
@dteviot 
Its working, thank you very much.
