### ISSUE TITLE
Slow Conversion Rate

### ISSUE THREAD

**Issue by dprohd** [dteviot/WebToEpub#248]
When trying to convert the EPUB output to any other format, for me, takes longer than it should. Using Calibre or any other conversion program.

**Comment by dteviot** [comment]
@dprohd
Can you quantify the problem?
For example.  
- What is the epub file you are using? 
- What are you converting it to?
- Exactly what are the steps you perform to do the conversion.
- How long does it take?
- How long should it take?  How do you know this is correct?

**Comment by dprohd** [comment]
I am converting any EPUB from most websites with over 400 chapters, or above ~1-2 MB. I convert it to MOBI, AZW3, or PDF. To convert, I open Calibre and drag the file in, clicking convert and selecting whichever file extension. Sometimes it takes 30 minutes, others up to an hour and thirty minutes. With EPUBs from a different archaic parser made a few years back that is no longer supported and cant parse all websites, the conversion rate will take usually under 10 minutes if not 15 max. Also, when using the Amazon Previewer program to convert the EPUBs to MOBi, the converter window will have a notification signifying that the conversion is "taking longer than usual". In calibre, it is generally stuck on converting a file called something which i have forgotten, i will check now.

**Comment by dteviot** [comment]
@dprohd
- What is the "different archaic parser"?  Where can I get it?
- Can you email me an epub made with the the "archaic parser"? (dteviot@gmail.com)

**Comment by dprohd** [comment]
The original subreddit is: https://www.reddit.com/r/LightNovels/comments/3fgjsz/convert_web_novels_to_epubpdf/
The github link is:
https://github.com/Mitch528/WebNovelConverter

**Comment by dprohd** [comment]
[Strongest Abandoned Son - Copy.zip](https://github.com/dteviot/WebToEpub/files/2882508/Strongest.Abandoned.Son.-.Copy.zip)
This is an epub file made from the parser, except the file extension name was just changed to .zip

**Comment by dteviot** [comment]
@dprohd 

As a **very** quick and dirty test, I tried comparing the file you supplied against the biggest epub I had on hand
Results of initial test (Using Calibre 3.9)

|file | size(kB) | chapters | time(secs) | kB/sec | chapters/sec |
|-----|-----|------|-----|-----|------|
| WebNovelConverter | 4478 | 1198 | 359 | 12.473 | 3.337 |
| WebToEpub | 1005 | 277 | 95 | 10.578 | 2.915

As you can see, speed (both kB/sec and chapters/sec) is about the same.  WebNovelConverter is slightly faster (about 15%).

Looking at the Calibre log files, I note most time seems to be taken by "Flattening CSS and remapping font sizes..."
And I note that WebToEpub includes a stylesheet, while the WebNovelConverter  epub does not.
However, removing the stylesheet and rerunning the conversion had no effect.

At this point, I suggest asking on the Calibre forums if anyone can suggest how to speed up converting epubs.  Or possibly raise an issue against Calibre regarding the slow conversion.
If you get anything useful back, please let me know and I'll see what I can do.

**Comment by dprohd** [comment]
Thank you for taking the time to reply to my issue. I couldn't find a way to convert to Mobi faster, however, converting to the other native Kindle format AZW3 took only minutes.

**Comment by dteviot** [comment]
Closing due to no further response from original opener.  If there's a problem, let me know and I'll re-open
