### ISSUE TITLE
API Dependency Support

### ISSUE THREAD

**Issue by kairusds** [dteviot/WebToEpub#252]
is there any plans for making webtoepub's api a separate npm package?

**Comment by dteviot** [comment]
@kairusds
What API are you referring to?

**Comment by AzSiAz** [comment]
probably something like this one #138

**Comment by dteviot** [comment]
@kairusds
> is there any plans for making webtoepub's api a separate npm package?

At this point in time, no.
I still don;t have the time.  However, if you know someone who's interested, I might be able to answer any questions they have.

**Comment by kairusds** [comment]
got it @dteviot.
