### ISSUE TITLE
Website request

### ISSUE THREAD

**Issue by ammasakshay** [dteviot/WebToEpub#253]
Can you add support for https://www.novelspread.com, its probably one of the best light novel sites. I want this more specifically because nearly every other site indexes chapters with the chapter number not the chapter name resulting in a ToC being generated without the name of the chapter. With Webnovels, that go over 1k chapters, having the chapter name makes navigating much easier. It also has several Korean and JP webnovels not found as commonly on other sites.
(for this website, id like the ToC to be in the format (Chapter No. - Chapter Name) If possible, which can be done from novelspread quite easily because it lists all chapter names in the index.

(Moved second request to new topic)

Thank You

**Comment by dteviot** [comment]
@ammasakshay
This is two requests.  For my tracking purposes, it's much better if you do one request per incident.
So, please create a second incident and move the "automatic updates" request to that. (I'd do it myself, but then you would not be automatically emailed progress updates.

That said, is https://github.com/dteviot/WebToEpub/issues/145 what you're looking for?

**Comment by ammasakshay** [comment]
Alright I have moved the second request to another topic. Is novelspread.com doable, in the way I asked? Also in some sites, the Translator and editor name is mentioned in every chapter and therefore pulled in every chapter rather than once at the start of the book. Can we be extra careful that it doesn't happen in this source? Thank you for your time and fast response.

**Comment by dteviot** [comment]
@ammasakshay 
WebToEpub had previously supported the NovelSpread site.  Unfortunately, changes to the site broke the parser.  I've committed fixes to the Experimental Tab branch, but I'm unable to fully test them as the site won't let me download more than 50 chapters unless I create an account and log in.  Which I'm not willing to do.
Please test it out by going to https://github.com/dteviot/WebToEpub#user-content-how-to-install-from-source and follow the instructions for "current development branch".

As requested, I've added chapter number to the chapter titles.  However, I have not done anything about removing translator or editor, as I don't have any pages that show this behavior.

**Comment by ammasakshay** [comment]
The download itself worked perfectly thank you. As for the request chapter request, I ment something like,
![TOC](https://user-images.githubusercontent.com/48739144/55015936-cae33780-5013-11e9-859c-ef89433fb47c.PNG)
Also the metadata page has not formatted well. It looks like this
![MD1](https://user-images.githubusercontent.com/48739144/55016103-1eee1c00-5014-11e9-9c55-f98593b11c41.PNG)
![MD2](https://user-images.githubusercontent.com/48739144/55016104-1f86b280-5014-11e9-86cc-aed9a568f869.PNG)
![MD3](https://user-images.githubusercontent.com/48739144/55016102-1eee1c00-5014-11e9-9b92-b048b5126130.PNG)
which means due to large amounts of random spacing the information is split over 3 pages instead of one.
A better possible format is
![MD4](https://user-images.githubusercontent.com/48739144/55016253-607ec700-5014-11e9-9c6e-2722a351be06.PNG)
As you can see it is very clean with all the information on a single page. Of course you dont have to add all the extra information such as word count, but this simple clean formatting that allows all information on a single page as well as title/authors name is much more elegant, because after all, the reason we go to the trouble of downloading (at least for me) is for archive purposes.

Other than the metadata/description page it works very well, though a bit slower than other sites. Thank you very much for your quick response and fix. (You did it within a day!)

**Comment by dteviot** [comment]
@ammasakshay
The chapters in the Table of Content (ToC) in the EPUB come from the ToC on the web site.  As you can see, they have the chapter number as the start of the chapter title.
![ToCScreenshot](https://user-images.githubusercontent.com/5157081/55034193-c2bde300-5079-11e9-9d47-6342f9b9be51.png)


I'm not going to try to insert the word "Chapter", as that can do funny things when language isn't English.  
(Yes, I know for this site the text is only English, but it's a habbit.  I know people use WebToEpub to make Epubs that are not English. e.g. Vietmanese and Chinese.)


I also agree, the information page is ugly, as WebToEpub is just grabbing chunks off the web page and not trying to reformat it.
There are two reasons for not reformatting the text
1. It usually takes me several hours to figure out the logic.  (And I don't have that much time.)
2. It's very brittle, it only takes one small change on the web site to break it all.

So, the compromise is the info page logic is kept simple so it doesn't break, and doesn't take long to write.  The downside is, it's ugly.
However you could always fix it up manually with Calibre.  And it's usually a lot easier to delete things than add them.

**Comment by dteviot** [comment]
Closing due to lack of response from issue creator.
