### ISSUE TITLE
[Error] Retrieving Lists Comrademao

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#259]
Hello, dteviot

failed to get the list of Comrademao (stay empty)

Thanks

**Comment by dteviot** [comment]
@3dycosmo
They've changed the pagination again.
Unfortunately, I'm very busy this week with other things. It's likely to be a few days before I get this fixed.

**Comment by 3dycosmo** [comment]
> @3dycosmo
> They've changed the pagination again.
> Unfortunately, I'm very busy this week with other things. It's likely to be a few days before I get this fixed.

@dteviot 
Thanks, take your time
I can waiting

**Comment by dteviot** [comment]
Fixed in version 0.0.0.71 which has been uploaded to Chrome web store.
