### ISSUE TITLE
[BUG] Filename has parts replaced by "..."

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#26]
Well, it's like this:

Link: https://baka-tsuki.org/project/index.php?title=Ultimate_Antihero:Volume_4
Title: Ultimate Antihero:Volume 4 (this is what is shown in the tag)
Filename: Ultimate_A...roVolume_4.epub

I suppose proper filename should be "Ultimate_Antihero-Volume _4.epub"; I noticed it changed from before, when the space were stripped instead of sobstituted with "_", maybe that introduced this.

**Comment by toshiya44** [comment]
It's a feature. It was done to avoid long filename issues on some systems.
You can change the filename before clicking on "pack epub" or after you've saved the file.

**Comment by typhoon71** [comment]
Oh, so it's for things like "I'm a High School Boy and a Bestselling Light Novel author, strangled by my female classmate who is my junior and a voice actress".
Makes sense. And since one can copy the "right" filename from the metadata shown above it's not a problem (one will probably edit the metadata anyway).
