### ISSUE TITLE
website request

### ISSUE THREAD

**Issue by Rainiu** [dteviot/WebToEpub#261]
Could I please get support for Truyenyy.com (and truyenfull.vn) as the TOC is across multiple Web Pages and my skills aren't good enough to create my own parser.
Thanks.

**Comment by dteviot** [comment]
@Rainiu
I _THINK_ I've built parsers for sites truyenfull.vn & truyenyy.com and committed to the Experimental Tab branch.
My Vietnamese is limited, so I'm not 100% sure I've got it right.
Also, I only tried a couple of stories from each site.

Please:
1. Install from Source (from the Experimental Tab branch)  https://github.com/dteviot/WebToEpub#how-to-install-from-source
2. Try them out
3. Let me know if there are any problems.

Thanks.

**Comment by Rainiu** [comment]
Thanks, he experimental tab branch works.
As for creating the parser, I don't want to waste your time as I have 0 skill.

All I did was opening the zenithnovels parser and edit everything under zenith to truyenyy.

**Comment by dteviot** [comment]
Updated version has been uploaded to chrome (and Firefox) stores.  Should automatically update within 24 hours.
