### ISSUE TITLE
Font for EPUB

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#263]
Chose the font for epub and not based on the website. I like the font that similar to Newyorker, WSJ, NYT for chapter list, heading, paragraph, etc.

Thanks, for the updates, function the reading list [your wonderful works]

**Comment by dteviot** [comment]
@3dycosmo
> Chose the font for epub and not based on the website. I like the font that similar to Newyorker, WSJ, NYT for chapter list, heading, paragraph, etc.

I'm not quite sure what you're asking for.
You should be able to set the font in most cases by using the stylesheet that's in the Advanced Settings.
However, it's possible that some web sites will explicitly set the font on a "per element" basis.  Scrubbing that out could get tricky.

> Thanks, for the updates, function the reading list [your wonderful works]

Umm.  You're welcome?

**Comment by dteviot** [comment]
@3dycosmo
Can you provide URL to Table of Contents of a story that is giving you a problem with fonts?
I might be able to modify another tool I have (https://github.com/dteviot/EpubEditor) to remove font information from the HTML elements in an epub.

**Comment by 3dycosmo** [comment]
> @3dycosmo
> Can you provide URL to Table of Contents of a story that is giving you a problem with fonts?
> I might be able to modify another tool I have (https://github.com/dteviot/EpubEditor) to remove font information from the HTML elements in an epub.

At that time there are no problems with fonts, thankfully. I just wonder if they could be customized than the same boring fonts;

1. https://www.wuxiaworld.co/Forty-Millenniums-of-Cultivation/
2. https://novelplanet.com/Novel/The-Legendary-Mechanic

like some kind of template and make them in the same format as this

1. https://www.gutenberg.org/files/47285/47285-h/47285-h.htm (Gutenberg and NYT have much readable formatting for reading experiences)

**Comment by 3dycosmo** [comment]
> @3dycosmo
> Can you provide URL to Table of Contents of a story that is giving you a problem with fonts?
> I might be able to modify another tool I have (https://github.com/dteviot/EpubEditor) to remove font information from the HTML elements in an epub.

At that time there are no problems with fonts, thankfully. I just wonder if they could be customized than the same boring fonts;

1. https://www.wuxiaworld.co/Forty-Millenniums-of-Cultivation/
2. https://novelplanet.com/Novel/The-Legendary-Mechanic

I prefer like some kind of template (option/setting to be available) and make them in the same format as this

1. https://www.gutenberg.org/files/47285/47285-h/47285-h.htm (Gutenberg and NYT have much readable formatting for reading experiences)

**Comment by dteviot** [comment]
@3dycosmo
You're talking about a Sans-serif font (the "boring" one) vs a Serif font ("not boring").
See: https://www.w3schools.com/css/css_font.asp

As the above links shows, you can use CSS to control the font.
And WebToEpub lets you specify the CSS used.
Open the Advanced Options (click on "Advanced Options" button)
Then look for "Stylesheet;"  (It's the big text box under the "Advanced Options" button)
You can then add font family to each rule in the style sheet.  Although you probably only need to update the rules for &lt;p&gt;, &lt;h1&gt;, &lt;h2&gt;, &lt;h3&gt;, &lt;h4&gt;, &lt;h5&gt; and &lt;h6&gt; elements.  e..g. Change this
```ccs
p {
  overflow-wrap: break-word;
}
```

to  this
``ccs
p {
  font-family: "Times New Roman", Times, serif;   
  overflow-wrap: break-word;
}
```

and this
```ccs
h1, h2 {
   text-align: center;
   page-break-before: always;
   margin-bottom: 10%;
   margin-top: 10%;
}
```

to this
```css
h1, h2 {
   font-family: "Times New Roman", Times, serif;   
   text-align: center;
   page-break-before: always;
   margin-bottom: 10%;
   margin-top: 10%;
}
```

etc.

**Comment by dteviot** [comment]
Closing due to no response from original opener.  If there's a problem, let me know and I'll re-open
