### ISSUE TITLE
somehow got crash

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#266]
----
Error: Fetch of image 'https://www.cite.com.my/images/p_download/822398.jpg' for page 'https://boxnovel.com/novel/alchemy-emperor-of-the-divine-dao/chapter-3' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:155:45
    at async Promise.all (index 2)

Error: Fetch of URL 'https://boxnovel.com/novel/alchemy-emperor-of-the-divine-dao/chapter-10' failed with network error Failed to fetch.
    at FetchErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:155:45
    at async Promise.all (index 1)

Google Chrome | 76.0.3785.0 (Official Build) canary (64-bit)
Revision | c88cba96b02d402a2023dbc6a311405c7b595145-refs/branch-heads/3785@{#1}

> it's got again while the sites worked 
> I changed to wuxiaworld.co and the same crash apply

> **tho eventually i change to firefox and it worked on but chrome**

>

**Comment by dteviot** [comment]
@3dycosmo
The "Failed to Fetch" error usually indicates a networking problem.  WebToEpub sent out a request, and got no response back at all.  i.e. The server being called made no response at all.  (Or it made a response, but the response did not make it back to WebToEpub, or WebToEpub's request never made it to the server.)

I just tried https://boxnovel.com/novel/alchemy-emperor-of-the-divine-dao and have no problem with latest version 0.0.0.73 on Chrome. So I'm suspecting some sort of temporary network problem that has been solved.

Incidentally, When I look at the source for https://boxnovel.com/novel/alchemy-emperor-of-the-divine-dao/chapter-3, I can find no reference to the image https://www.cite.com.my/images/p_download/822398.jpg.  Do you see that image if you look at the page itself?
