### ISSUE TITLE
Website request

### ISSUE THREAD

**Issue by RalphC11** [dteviot/WebToEpub#267]
I would like to request this website - http://www.tapread.com

Thanks in advance

**Comment by dteviot** [comment]
Done (maybe)
Updated version (0.0.0.74) has been uploaded to Chrome and Firefox stores and should update automatically within 24 hours.
Note that the submission to the Firefox store generated the following warning.  So the Firefox version of the extension may not work for tapread until I fix it.
> Unsafe assignment to innerHTML
>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
>
>js/parsers/TapreadParser.js line 56 column 9
