### ISSUE TITLE
lightnovelbastion support

### ISSUE THREAD

**Issue by Mapsred** [dteviot/WebToEpub#269]
Hi,

Is it possible to add support for lightnovelbastion.com ?

It does not fetch the chapters, and when I add them manually, it gives me the following error : 
Could not find content element for web page 'https://lightnovelbastion.com/novel/death-mage/volume-9/chapter-179'. fetchWebPageContent/<@moz-extension://b962f4a5-9ff1-4760-82b9-4652dbf0ff4b/js/Parser.js:440:23

**Comment by dteviot** [comment]
@Mapsred 
Site has changed layout. This broke existing code. I've committed fix to the ExperimentalTabMode
I'll upload the new version to the Chrome and Firefox stores in a day or two.

Or you can follow these instructions https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#how-to-install-from-source to install from source.

**Comment by dteviot** [comment]
@Mapsred
Updated version uploaded to Chrome and Mozilla stored
