### ISSUE TITLE
BakaTsuki - Content list (table of contents)

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#27]
Small fix needed.
If the table of content is hidden while viewing a BakaTsuki novel, the plugin will show a page like this.

![ee](https://cloud.githubusercontent.com/assets/1866248/16405986/c5a10f40-3d0b-11e6-8342-3e9488cd84d8.png)

Can an option be added to remove it completely if it's hidden?
And maybe another option to automaticlly "show" it instead?

**Comment by belldandu** [comment]
Toc is actually stripped from the novel https://github.com/dteviot/WebToEpub/blob/7f3bbcbd7071cf8ec686e9bd3f186cd5c8fe0e99/plugin/js/parsers/BakaTsukiParser.js#L101

The problem here is that the class changes to "toc tochidden" when you click hide. Which causes it to remain.

simple fix would be to compare the id instead of the class. @dteviot

**Comment by belldandu** [comment]
@typhoon71 can this be closed?

**Comment by typhoon71** [comment]
Uhm, I don't see any difference from 0.0.0.7? Did the "simple fix" above get implemented?
If it won't, I'm fine closing this anyway because I just need to not hide the toc on the novel page.

**Comment by dteviot** [comment]
@typhoon71
It should have been.
The code change has been committed.
https://github.com/dteviot/WebToEpub/commit/d40170336cc55d1a4d626f2eb9c3448d45edfbd6,
lines 119 - 120.
That said, fix looked so simple I did not test it.
And it's always possible I sent the wrong file to Google.

**Comment by typhoon71** [comment]
OK, I'm testing v0009 from sonako with firefox (oogle still on v0008).
I get this with every novel I try.

![ufff](https://cloud.githubusercontent.com/assets/1866248/16467504/f0577c64-3e47-11e6-83d9-3108e7eac1eb.png)

Happens with "Set Cover" both selected or unselected.

**Comment by dteviot** [comment]
@typhoon71
I will have to look into this tonight.  Currently busy at my day job.

I'll point out v0.0.0.9 is just because I bump the version number
immediately after a release. Code wise, 0.0.0.9 from sonako branch is same
as the 0.0.0.8 release.

**Comment by typhoon71** [comment]
np, do it when you can/want, I'm already happy I won't have to do the html -> epub (or pdf) by hand...

**Comment by belldandu** [comment]
@typhoon71 That fetch of url error happens because the server returns a response other then 200.

@dteviot this ties into #13 

We really also need to put in #14 an option for retrying if a server returns something other than 404 when it doesn't return 200.

**Comment by typhoon71** [comment]
I don't know wh ythat error happens, and it's strange because I was able to fetch the whole thing before without issues. It seems it's still avail to me?

**Comment by dteviot** [comment]
@typhoon71 Belldandu is saying that the server is returning some response other than 200 (success), I'm going to guess you were getting a 50x series network error (unable to get file, usually due to some problem with the CDN.)  Under that case, the generator just gives up.  Obviously, better error reporting is required.

**Comment by typhoon71** [comment]
But it should give success, if I just browse to the images I can open them... so the CDN should be working.
I mean, in this case I would expect a 200 -only-, nothing else.

**Comment by dteviot** [comment]
@typhoon71  Stupid questions, 
* is it only Firefox that has problems, or does the Crome version have same problem?
* Does it work for older Firefox versions?  If so, which ones?

**Comment by belldandu** [comment]
@typhoon71 Another stupid question,
[*] does this only happen on [this](https://baka-tsuki.org/project/index.php?title=The_Zashiki_Warashi_of_Intellectual_Village:Volume9) specific page?

**Comment by dteviot** [comment]
Interesting, on Firefox, the images download and the epub is built, but the xhtml files are not correct.
The style information is visible in an epub viewer.  Will investigate further, later.

**Comment by typhoon71** [comment]
Not a stupid question at all, didn't think of checking that.
I manually installed the plugin in chrome (to be 100% sure it's the same as in firefox) and it packs the epub.
There are 2 buts: the plugin manager windows has some errors after loading it:

![errors](https://cloud.githubusercontent.com/assets/1866248/16514165/77f1ea74-3f6a-11e6-97a6-9d2fcc105a9a.png)

and sigil sometime complains about malformed html on some novels.
https://baka-tsuki.org/project/index.php?title=This_title_is_too_long%21%3AVolume2 is affected, for example.

Since I started using this plugin I didn't update firefox, it's always been 47.0; I started having issues with the plugin 0.0.0.8, before it worked (I mean, it didn't just trow that error and stop).

To answer the last question, the problem with firefox happens on any page, it's not limited to the one I linked you.

**Comment by typhoon71** [comment]
Not a stupid question at all, didn't think of checking that.
I manually installed the plugin in chrome (to be 100% sure it's the same as in firefox) and it packs the epub.
There are 2 buts: the plugin manager windows has some errors after loading it:

![errors](https://cloud.githubusercontent.com/assets/1866248/16514165/77f1ea74-3f6a-11e6-97a6-9d2fcc105a9a.png)

and sigil sometime complains about malformed html on some novels.
https://baka-tsuki.org/project/index.php?title=This_title_is_too_long%21%3AVolume2 is affected, for example.

Since I started using this plugin I didn't update firefox, it's always been 47.0; I started having issues with the plugin 0.0.0.8, before it worked (I mean, it didn't just trow that error and stop).

To answer the last question, the problem with firefox happens on any page, it's not limited to the one I linked you.

**Comment by typhoon71** [comment]
Small update, happens with Firefox 47.0.1 too (just updated).
I see minimum_firefox_version is set to 48... which is still beta... it would be sensible to set it to 47 instead.

**Comment by belldandu** [comment]
The reason the minimum firefox version is 48 is because its using WebExtensions which is only supported by BETA/Aurora Firefox @typhoon71 @dteviot 
The reason he is getting these issues is more then likely because he is trying to use the extension on an unsupported version.

**Comment by typhoon71** [comment]
I understand why you're using WebExtensions, but wouldn't it make sense to wait to intruduce them till Firefox 48 is released? Even keeping < Firefox 48 would be nice, after all there's the matter of what will happen when Mozilla will kill XUL & friends; some may decide to stay on older releases to wait and see what happens to the extensions... (a bloodbath I suppose).
This from a Firefox user standpoint; from a chrome user standpoint, it's irrelevant.

**Comment by belldandu** [comment]
The reason we have not waited is for people to test it on the Aurora release so that we can scratch away any bugs before it becomes a stable version of firefox.

**Comment by belldandu** [comment]
Also as for those manifest key errors thats because the firefox manifest and chrome manifest are one file so chrome doesn't know what to do with the keys. You can safely ignore those errors.

**Comment by typhoon71** [comment]
OK, so I guess that I'll have to use chrome to make epubs, since the plugin now doesn't work on Firefox < 48...
I won't ask to not use WebExtensions, I just hope that Firefox 48 doesn't break anything...

**Comment by belldandu** [comment]
@dteviot can confirm this happens in Aurora Firefox @typhoon71 why did you close this?

**Comment by typhoon71** [comment]
my bad, wrong button.

**Comment by belldandu** [comment]
Just Test on https://baka-tsuki.org/project/index.php?title=CubexCursedxCurious:Volume1 seems to work fine. Although i do get your error message on https://baka-tsuki.org/project/index.php?title=CubexCursedxCurious But i think its obvious why.

**Comment by belldandu** [comment]
see #37

**Comment by typhoon71** [comment]
About the issue on firefox: I suppose it works in aurora, but I'll wait for ffox 48 to be released before testing.

About Sigil complaints, I get none on C3 volume 1. Maybe in some cases it happens, in some it doesn't.
Regarding "https://baka-tsuki.org/project/index.php?title=This_title_is_too_long%21%3AVolume2", the malformed html seems to be "0005_Afterword.xhtml", but I don't see anything strange opening the epub with calibre or even sumatra.

**Comment by dteviot** [comment]
As far as I can tell, all issues raised here are either fixed or documented as part of other issues.  So closing.
