### ISSUE TITLE
Not working on comrademao

### ISSUE THREAD

**Issue by darkharrycracker** [dteviot/WebToEpub#272]
i tried using it on (https://comrademao.com/novel/monster-pet-evolution/) and it didn't find any chapter.

**Comment by dteviot** [comment]
@darkharrycracker
Why did you close this?

**Comment by darkharrycracker** [comment]
it works just takes quite a long time like 5mins XD

**Comment by dteviot** [comment]
@darkharrycracker
I did warn you in https://github.com/dteviot/WebToEpub/issues/270 that fetching the ToC is going to be slow.

Note, you can see progess by 
1. opening devtools for the WebToEpub page.
2. Clicking on the Network tab.
Google "Chrome DevTools Network" for more information.

You might like to ask the owners of the site if there's a REST API to call to get the list of chapters in one call.
