### ISSUE TITLE
Support for wordexcerpt.com and babelnovel.com possible?

### ISSUE THREAD

**Issue by T-Man2000** [dteviot/WebToEpub#273]
Hello. Is support for [wordexcerpt.com](wordexcerpt.com) and [babelnovel.com](babelnovel.com) possible? It could be the same CMS in the background. I see a similar page structure with more and more Light Novel pages.

**Comment by dteviot** [comment]
They might look similar, but underneath they seem to be quite different.
wordexcerpt looks to be easy to build a parser for.  babelnovel, not so much.

**Comment by dteviot** [comment]
@T-Man2000
Well, this is embarassing.  
On closer inspection, babelnovel.com seems to be an alias for novel.babelchain.org, which I've already done.
Anyway, changes have been committed to the ExperimentalTabBranch.
Please follow these instructions https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#how-to-install-from-source for installing from source and let me know how it works for sites babelnovel and wordexcerpt.

**Comment by T-Man2000** [comment]
The attempt to test it with the current Nightly unfortunately gave me only an error message.

> There was an error during the temporary add-on installation.
> Error details
> Extension is invalid
> Reading manifest: Error processing incognito: Invalid enumeration value "split"

**Comment by dteviot** [comment]
@T-Man2000
My apologies, it's been so long since I loaded from source into Firefox the instructions are slightly out of date.
There's one additional step you need to do.
* Open the file manifest.json in the plugin directory with a text editor and delete the line that goes: 
> "incognito": "split",

**Comment by T-Man2000** [comment]
Thanks for the changed documentary and the script. I tested 2 stories. https://wordexcerpt.com/series/bodyguard-of-the-goddess/ and https://babelnovel.com/books/my-cold-and-beautiful-ceo. In both cases WebToEpub worked without problems.

**Comment by dteviot** [comment]
@T-Man2000
Updated version has been uploaded to Chrome and Mozilla stores.  Should be available in a few hours and update automatically in within a few days.
