### ISSUE TITLE
Allow more than one element removal

### ISSUE THREAD

**Issue by giaez** [dteviot/WebToEpub#275]
I have trouble finding how to remove more than one element

**Comment by dteviot** [comment]
@giaez
I'm assuming you're referring to what value to put into the "CSS selector for elements to remove" item on the Default parser.  The answer is: use a comma  e.g.
```javascript
div.advertisment, section#comments
```
Will select all elements of type &lt;div class="advertisment"&gt; and &lt;section id="comments"&gt;.

**Comment by dteviot** [comment]
Closing due to no response from original opener.  If there's a problem, let me know and I'll re-open
