### ISSUE TITLE
Remove support for comrademao.com

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#279]
From Tyr Ant
> Hi mate,
>
>I'm administrator of comrademao.com and I would like to kindly ask you to remove all support for scraping and making epubs from comrademao.com website. Normally, we wouldn't care but unfortunately when people use your plugin to scrape the chapters from our website the cpu loads spike up and the process itself disturbs the whole experience for every other reader.

**Comment by gb001** [comment]
dont man
we need it administrator of comrademao.com
DON`T DO THAT
plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by dteviot** [comment]
@gb001

I'm sorry, but there are over 100 people hitting comrademao with WebToEpub simultaneously.  And the site just can't handle it.
That said, the administrators don't mind epubs being made and they're willing to look at providing some sort of pre-built epubs.  It's just not a priority for them at the moment.
My suggestion is, contact them on Discord and see if they're willing to do some sort of arrangement.
For example, allow one person to create epubs on a scheduled basis (weekly maybe?) and then make them available somewhere for general download (e.g. patreon.)

**Comment by AlenToma** [comment]
comon man, we really need this to work on comrademao. Admin please find a way. make it work only on some specific time on a weekend or something.

I cant read throw the website on my mobile otherwise.

**Comment by dteviot** [comment]
@AlenToma

There isn't anything I can do.  Site staff were nice enough to ask me to stop supporting them.
They could have just complained to Google and had WebToEpub banned.

**Comment by dteviot** [comment]
@AlenToma 

I just realized, you're a developer.  So, there is a solution.
You can install from source (instructions https://github.com/dteviot/WebToEpub) and remove the ComradeMao lockout.
https://github.com/dteviot/WebToEpub/blob/14056cadb7da7bbdb4a8c22515418a55ef3bc2a3/plugin/js/parsers/ComrademaoParser.js#L10-L12

Note, looks like the site has changed a bit, so you may need to make some additional changes to the parser to cope.

**Comment by AlenToma** [comment]
Ok, I dont know if i really should say that but forked this and made some changes to parse Comrademao.

https://github.com/AlenToma/WebToEpub

Admin delete this entry if its not ok thx

**Comment by dteviot** [comment]
@AlenToma
No problem,  thanks for the update.

**Comment by dteviot** [comment]
@AlenToma
A few more changes that might interest you.
https://github.com/dteviot/WebToEpub/commit/efc3913b218bb514e842051c3a0701bdc959210a
* Most notable is fixing up chapter titles.
* Rest is just getting rid of stuff that's no longer relevant.

**Comment by ArunSriKrishna** [comment]
> Ok, I dont know if i really should say that but i forked this and made some changes to parse Comrademao.
> 
> https://github.com/AlenToma/WebToEpub
> 
> Admin delete this entry if its not ok thx

Nah man, it inst working. getting some error messages instead

**Comment by ArunSriKrishna** [comment]
> Ok, I dont know if i really should say that but i forked this and made some changes to parse Comrademao.
> 
> https://github.com/AlenToma/WebToEpub
> 
> Admin delete this entry if its not ok thx

It is not working, i get an error in CommardeMao: 

ReferenceError: JSZip is not defined
    at EpubPacker.assemble (chrome-extension://hmfnnefhpicfefmccjfhjakecenhfjnj/js/EpubPacker.js:41:23)
    at packEpub (chrome-extension://hmfnnefhpicfefmccjfhjakecenhfjnj/js/main.js:161:21)
    at chrome-extension://hmfnnefhpicfefmccjfhjakecenhfjnj/js/main.js:136:20

just before I can save the epub

**Comment by AlenToma** [comment]
Ok i have anabled `ComrademaoParser` Download the addons agen now it should work.

Note you may have to download the latest update from https://github.com/Stuk/jszip also

**Comment by ArunSriKrishna** [comment]
> Ok i have anabled `ComrademaoParser` Download the addons agen now it should work.
> 
> Note you may have to download the latest update from https://github.com/Stuk/jszip also

Thanks man! very cool!

**Comment by ArunSriKrishna** [comment]
> Ok i have anabled `ComrademaoParser` Download the addons agen now it should work.
> 
> Note you may have to download the latest update from https://github.com/Stuk/jszip also

Yeah works fine!

**Comment by maou-213** [comment]
> Ok i have anabled `ComrademaoParser` Download the addons agen now it should work.
> 
> Note you may have to download the latest update from https://github.com/Stuk/jszip also

if i may ask how do i use the file to let webtoepub access comrademao.com

**Comment by dteviot** [comment]
@maou-213
@AlenToma has made a modified version of WebToEpub.at https://github.com/AlenToma/WebToEpub
1. Follow the "How to install from Source" instructions at https://github.com/AlenToma/WebToEpub#how-to-install-from-source 
Note, because you'll want AlenToma's version, replace "dteviot" in the URLs to fetch with "AlenToma"

**Comment by AlenToma** [comment]
The website has changed, I dont think that the parser still work? 

By the way I have started working on a mobile project that can view novels from many sites. Check it out [here](https://github.com/AlenToma/NovelManager) I have not yet publish it. it will be published in few days.

**Comment by dteviot** [comment]
@AlenToma
> The website has changed, I dont think that the parser still work?

I don't know.  I don't track that site.
>By the way I have started working on a mobile project that can view novels from many site

Screenshots look awesome.  I wish you the best of luck with it.

**Comment by maou-213** [comment]
> @maou-213
> @AlenToma has made a modified version of WebToEpub.at https://github.com/AlenToma/WebToEpub
> 
> 1. Follow the "How to install from Source" instructions at https://github.com/AlenToma/WebToEpub#how-to-install-from-source
>    Note, because you'll want AlenToma's version, replace "dteviot" in the URLs to fetch with "AlenToma"

I seem to be having a problem downloading epub because at the end of the download it saids that jszip is not defined how do i fix it

**Comment by dteviot** [comment]
@maou-213
> it says that jszip is not defined

You probably haven't installed jszip correctly. it's steps 4 and 5.
However, there might be an easier alternative.
1. Get the assembled zip for Firefox or Chrome from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.
2. Unzip the zip file.
3. Replace the file ComrademaoParser.jz with the one you got previously from AlenToma.

**Comment by maou-213** [comment]
> @maou-213
> 
> > it says that jszip is not defined
> 
> You probably haven't installed jszip correctly. it's steps 4 and 5.
> However, there might be an easier alternative.
> 
> 1. Get the assembled zip for Firefox or Chrome from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.
> 2. Unzip the zip file.
> 3. Replace the file ComrademaoParser.jz with the one you got previously from AlenToma.

Should i replace the comrademaoparser.jz with the three files in the drive or should i choose One of the three files in the drive

**Comment by DebanganThakuria** [comment]
@dteviot You can add a "1 second sleep" between parsing of each chapter. This won't overload the sites we scrape.

**Comment by dteviot** [comment]
@DebanganThakuria 
It's not that simple.
The site owners have nicely asked me to remove support.
They COULD have just told Google it's being used to DDOS their site.
And Google would immediately ban WebToEpub.

**Comment by akash333777** [comment]
Somebody help please.....i am not a coder and dont know nothing about program language .....but i really want to read "EDGE OF APOCALYPSE" novel from comrademao site. Web to epub is not working.....
Could anyone send me the packed epub file to akashvijay1997@gmail.com

**Comment by gamebeaker** [comment]
@akash333777 hi i send it to you the content is from comrademao i used max. 4 fetch simultaneously and 3sec/chap to prevent server spikes as a tipp for the future simple google the name and look if other pages have the same story i found https://wuxiaworld.online/166572/edge-of-the-apocalypse after one search and this site isn't locked in webtoepub.

**Comment by NotAProgramNerd** [comment]
Hello guys, im also in need of the version of @AlenToma but i cant seem to follow his instructions. Can i ask any kind souls here to please send me the link or file of the finished version at christianlinares1207@gmail.com. I really want to read novels and its my life but i cant do it online cause of financial problem and only offline reading is best for me. Thank you for helping me!

**Comment by gamebeaker** [comment]
@NotAProgramNerd i would recommend using the github app https://desktop.github.com/ and fork or clone https://github.com/dteviot/WebToEpub than you simple go to plugin->js->parsers->comrademaoparser.js open in notepad or something like that write "/*" in line 9 and "*/" in line 18 without the " . now you should be able to use it in chrome or firefox if you follow this guide remember you have downloaded it und don't need to download it again. 
chrome at point 6
firefox at point 8
https://github.com/dteviot/WebToEpub#how-to-install-from-source

**Comment by NotAProgramNerd** [comment]
Thank you very much! I really appreciate your effort 😊 Many many thanks!

Sent from Mail for Windows 10

**Comment by NotAProgramNerd** [comment]
> @NotAProgramNerd i would recommend using the github app https://desktop.github.com/ and fork or clone https://github.com/dteviot/WebToEpub than you simple go to plugin->js->parsers->comrademaoparser.js open in notepad or something like that write "/*" in line 9 and "*/" in line 18 without the " . now you should be able to use it in chrome or firefox if you follow this guide remember you have downloaded it und don't need to download it again.
> I am sure the server would appreciate it if you would set Max web pages to fetch simultaneously to 4 and Manual Throttle|Delay per chapter to 3sec/ chapter to prevent server spikes which was the reason it got locked. If you have time you can make it even slower.
> chrome at point 6
> firefox at point 8
> https://github.com/dteviot/WebToEpub#how-to-install-from-source

oh sorry, i need to clarify something. after i forked the program then edited it in github by adding the / , i should click propose changes? i clicked that and i dont know what to do next.

**Comment by gamebeaker** [comment]
@NotAProgramNerd hi could you please send me your discord on my email play4freenew@gmx.de i think this would be faster

**Comment by gamebeaker** [comment]
@NotAProgramNerd or join this discord server https://discord.gg/F78fQZ3u

**Comment by Finks82** [comment]
https://www.readwn.com/  - it have all comrademao.com novel [including newly added one]
