### ISSUE TITLE
Novelplanet [Images]

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#280]
Never success to get the IMAGES from this [site](https://novelplanet.com/Novel/Boku-no-Kanojo-Sensei)
is this WordPress restriction 

https://novelplanet.com/Novel/Boku-no-Kanojo-Sensei

**Comment by dteviot** [comment]
@3dycosmo 
Looks like Novelplanet is lazy loading images.  https://www.sitepoint.com/five-techniques-lazy-load-images-website-performance/
So, I need to figure out where the real images are.
Until I get that fixed, it looks like NovelPlanet grabbed the story from https://cclawtranslations.com/boku-no-kanojo-sensei/, and it looks like WebToEpub has no problem with that site.

**Comment by dteviot** [comment]
@3dycosmo
New version (0.0.0.81) uploaded to chrome store.  Fixed problem for Boku-no-Kanojo-Sensei.
Please let me know if there are any other titles with issues.

**Comment by 3dycosmo** [comment]
There are, all novels with messages

> Click the arrows to see the illustrations
> These illustrations are from the inside front cover

<a href="https://novelplanet.com/Novel/Is-it-Tough-Being-a-Friend/v4-illustrations?id=740090">Is it Tough Being a Friend? Volume 4 illustrations</a>


```
Error: Fetch of image 'https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&gadget=a&no_expand=1&resize_h=0&rewriteMime=image%2F*&url=https%3a%2f%2fi0.wp.com%2f2slow2latemtl.icu%2fwp-content%2fuploads%2f2019%2f10%2fi-0001_01.jpg%3fresize%3d825%252C1180%26ssl%3d1' for page 'https://novelplanet.com/Novel/Is-it-Tough-Being-a-Friend/v4-illustrations?id=740090' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:155:45
    at async Promise.all (index 0)
```

**Comment by 3dycosmo** [comment]
> @3dycosmo
> New version (0.0.0.81) uploaded to chrome store. Fixed problem for Boku-no-Kanojo-Sensei.
> Please let me know if there are any other titles with issues.



There are, all novels with messages

> Click the arrows to see the illustrations
> These illustrations are from the inside front cover

<a href="https://novelplanet.com/Novel/Is-it-Tough-Being-a-Friend/v4-illustrations?id=740090">Is it Tough Being a Friend? Volume 4 illustrations</a>


```
Error: Fetch of image 'https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&gadget=a&no_expand=1&resize_h=0&rewriteMime=image%2F*&url=https%3a%2f%2fi0.wp.com%2f2slow2latemtl.icu%2fwp-content%2fuploads%2f2019%2f10%2fi-0001_01.jpg%3fresize%3d825%252C1180%26ssl%3d1' for page 'https://novelplanet.com/Novel/Is-it-Tough-Being-a-Friend/v4-illustrations?id=740090' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:155:45
    at async Promise.all (index 0)
```
