### ISSUE TITLE
selection menu is partially broken?

### ISSUE THREAD

**Issue by T-Man2000** [dteviot/WebToEpub#281]
I think the selection menu is partially broken. If I select the 78 as the First Chapter and the Last Chapter is 140, the URL list starts at chapter 77 and stops at 139.

![parser](https://user-images.githubusercontent.com/37932342/60617079-2ec78a00-9dd3-11e9-8fb9-80a240b76a2c.JPG)

I noticed this here: http://www.divinedaolibrary.com/omni-magician/.
But on other pages I saw that again and again today. I changed the chapters manually via "Edit Chapter URL's".

**Comment by dteviot** [comment]
@T-Man2000 
D'oh!  Fix one bug, introduce another. (whack-a-mole.)
Found a bug where the header row of the chapters table was being deleted.  Now the selection control is off-by-one.
Easy to fix.

**Comment by dteviot** [comment]
@T-Man2000 
New version (0.0.0.81) uploaded to chrome store.
