### ISSUE TITLE
Support for flying-lines.com and hiscension.com possible?

### ISSUE THREAD

**Issue by T-Man2000** [dteviot/WebToEpub#282]
Hello. Is support for flying-lines.com and hiscension.com possible?

hiscension.com based on Wordpress.
flying-lines.com has a similar code as wordexcerpt.com

**Comment by dteviot** [comment]
@T-Man2000
* hiscension.com has been done.  You can install from source and try if you like
* flying-lines.com is proving more difficult.  They're doing something to detect scraping and return chapter text along the lines of "Stop trying to steal our work".

**Comment by T-Man2000** [comment]
hiscension.com works.

**Comment by dteviot** [comment]
@T-Man2000
I've pushed commit for flying-lines, as it stands.  So you can try it if you like.
Sometimes works, sometimes doesn't.  
I _think_ when it doesn't work, if you open the first chapter of a story on a tab, then open WebToEpub on the ToC and try collecting chapters it works.
I'm not sure what to do with this.  It's not really fit for general release.

**Comment by T-Man2000** [comment]
A test (flying-lines.com/novel/i-m-in-hollywood)from today gave the following error message.

> Fetch of URL 'https://www.flying-lines.com/chapter/1464' failed with network error 404. onResponseError@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/HttpClient.js:28:25
> checkResponseAndGetData@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/HttpClient.js:163:45
> wrapFetchImpl/<@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/HttpClient.js:157:31
> promise callback*wrapFetchImpl@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/HttpClient.js:156:12
> fetchJson@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/HttpClient.js:137:27
> fetchChapter/<@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/parsers/FlyingLinesParser.js:40:31
> promise callback*fetchChapter@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/parsers/FlyingLinesParser.js:38:42
> fetchWebPageContent@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/Parser.js:435:27
> fetchFunc@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/Parser.js:406:43
> fetchWebPages/</sequence<@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/Parser.js:414:46
> promise callback*fetchWebPages/<@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/Parser.js:413:37
> promise callback*fetchWebPages@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/Parser.js:408:68
> fetchContent@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/Parser.js:384:21
> fetchContentAndPackEpub@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/main.js:134:16
> EventHandlerNonNull*addOnClickEventHandlers@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/main.js:379:26
> window.onload@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/main.js:403:36
> EventHandlerNonNull*main<@moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/main.js:398:5
> @moz-extension://b5f01583-6f2c-4a77-83ac-4afe8f1507f1/js/main.js:416:3

**Comment by dteviot** [comment]
@T-Man2000 
Seems to be some sort of server problem at the site.  Trying to fetch the host page returns a HTTP 500 error for me.  Try contacting them and ask.

**Comment by dteviot** [comment]
Closing due to no response from original opener.  If there's a problem, let me know and I'll re-open
