### ISSUE TITLE
Website Request

### ISSUE THREAD

**Issue by KiraYamatoSD** [dteviot/WebToEpub#283]
Hi, Can you add support for the following sites?
Thank you!

1. https://listnovel.com/
2. https://readwebnovel.xyz/

**Comment by dteviot** [comment]
@KiraYamatoSD 
Interesting.  The two sites are, in terms of HTML schemas, identical.  So same parser can be used for both.
Changes have been committed to the ExperimentalTabBranch.
Please follow these instructions https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#how-to-install-from-source for installing from source and let me know how it works.
For future reference, https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser tells you how to build your own parsers.
