### ISSUE TITLE
Wuxiaworld advertisement imported instead of chapter

### ISSUE THREAD

**Issue by FrederickEngelhardt** [dteviot/WebToEpub#284]
Looks like the announcement banner is getting added into the chapter instead of the actual chapter content for the WuxiaParser.

Steps to repeat
1. https://www.wuxiaworld.com/novel/terror-infinity
2. Create an epub using WebToEpub
3. Volume 5 chapter 3-2 & 3-3 will be advertisements instead of the epub content.

Edit: Without diving too deeply into the code it looks like WuxiaParser or something related to it needs to ignore `#announcement-78994` & `#announcement-79268`

### Temp solution
*Go to advanced and choose default parser*
Custom css selectors: `.post-content span`
Removed CSS elements: `img, td, tr, li, .top-bar-area, #sidebar, .footer, #announcement-79268, #announcement-78994, a`

**Comment by dteviot** [comment]
@FrederickEngelhardt
Updated version (0.0.0.82) uploaded to Chrome and Firefox stores.  Your browser should update automatically within 24 hours.
