### ISSUE TITLE
How to compile everything into a Single EPUB file?

### ISSUE THREAD

**Issue by Rajvir8** [dteviot/WebToEpub#288]
Currently it's saved as a ZIP file when downloading from Royal Road, 

After extracting the ZIP it has an EPUB that works off references and thus can't be put into AIReader or Google Books.

I ended up putting all the HTML files it saved into Calibre, converting the files into the EPUB format and then merging them all together into one proper EPUB file, but the entire process takes several extra steps and takes a lot longer.

Is there any way to directly create an EPUB file using WebtoEPUB?

**Comment by dteviot** [comment]
@Rajvir8 
See: https://github.com/dteviot/WebToEpub/issues/191

Short answer:
Assuming the file your getting has a name like 69dfd590-d947-420a-b7ef-943f12c80a09.zip, then just rename the file to {titleOfYourChoice}.epub and it should work.
(epub files are zip files.)

You're probably running into a conflict with one of the other extensions you have.

**Comment by Rajvir8** [comment]
This indeed fixed my issue, at first I was confused as Windows 10 hid the extensions but after I found them and changed it to EPUB it did indeed fix it.
