### ISSUE TITLE
[BUG] on Firefox the plugin panel is too small

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#29]
This is what's happens in Firefox 47.0:

![s](https://cloud.githubusercontent.com/assets/1866248/16413790/7a971340-3d34-11e6-9c5e-2d54b4a2f010.png)

In Chome the panel is like 2x wide, and it's way more useable.

**Comment by typhoon71** [comment]
Nevermind. It doesn't happen with stock theme (this is the awesome TTDeepDark).
Will ask the theme developer for help.

**Comment by toshiya44** [comment]
@typhoon71 use the dev theme.

**Comment by typhoon71** [comment]
I like TTDeepDark more, but the dev theme isn't bad either.
Sadly TTDeepDark dev seems busy, he usually answers but this time he didn't.
Giben time it'll get fixed I suppose.
