### ISSUE TITLE
kobatochan.com chapters split into different pages.

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#291]
The chapters on the website are sometimes long enough to be put into multiple pages

Here is an example https://kobatochan.com/everyone-else-is-a-returnee-chapter-15/

This just results in the first page being copied with the link at the bottom.

**Comment by dteviot** [comment]
@JeremyStarten
Fix has been committed to ExperimentalTabMode branch.  Seems to work for URL you supplied.
Please let me know if there are other issues.
