### ISSUE TITLE
Allow area to post links instead of using website.

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#293]
Sometimes websites use dropdowns, weird tables, or don't even have a ToC. This makes it much more difficult to make an epub with them. An area like a blank notepad where you can paste all the links in the order you want. I think having it as an option next to the load and analyze button would be great. Maybe a modified version of the edit links where it automatically adds the hyperlinked stuff like
http://test.com Test
instead of 
` <a href="http://test.com">Test</a>`

I know it can work cause sometimes I do just use the edit link area but it takes so much extra time to add the stuff around the link and chapter name.

**Comment by dteviot** [comment]
@JeremyStarten 
I'm tempted to say you're doing it wrong.
Make up a string like
` <a href=""></a>`
Copy paste it lots of times.  Then paste in the link and desired title text.

**Comment by dteviot** [comment]
Closing due to no response from original opener.  If there's a problem, let me know and I'll re-open
