### ISSUE TITLE
Chinese Characters Not Being Properly Reflected

### ISSUE THREAD

**Issue by Bsubs** [dteviot/WebToEpub#296]
Was trying to use the extension to download a novel from sto.cx. the extension managed to process all the link I inputted and packed the epub. However, some of the downloaded characters are reflected as %e5%94%87 instead of the actual characters. Is there something wrong with my system or the way that I'm using the app?

**Comment by dteviot** [comment]
Bsubs
I'll do what I can.  However, I don't know Chinese.
From the description, it sounds like most characters work, but some don't.  Can you confirm this is the case?
Also, I'm not able to search the whole site for the problem cases. you'll need to tell me exactly where to find the problem.
i.e. For a couple of instances, I will need
1.  The URL of a chapter with the problem
2.  The URL of the Table of Contents page for the story with the chapter
3. The sentence in the chapter with the issue.

Thanks

**Comment by Bsubs** [comment]
Thanks for the reply dteviot,
I have attached a drive link below containing a copy of the epub that I generated as well as the table of contents that I manually generated for input.

For some specific cases:
https://www.sto.cx/book-40390-2.html 
In the 11th line of text the "露出" is missing from the epub and replaced with %e9%9c%b2%e5%87%ba
In the 53rd line of text "手触" is replaced with %e6%91%b8

https://www.sto.cx/book-40390-3.html
In the third line of text "咬" is replaced with %e5%92%ac
In the 4th line of text "胸" is replaced with %e8%83%b8

If any more information is required please let me know.

https://drive.google.com/drive/folders/1pybEqq0fom6-iiTB12hg4A_YPAWw_11N?usp=sharing

**Comment by dteviot** [comment]
@Bsubs 
Thanks.  that's enough for now.
This is going to take a while to solve.  Can't give you an ETA.

**Comment by dteviot** [comment]
@Bsubs 
Facts
1. The "%e9%9c%b2%e5%87%ba" strings are coming from the server.
2. They seem to be a weirdly escaped UTF-8.  e.g. the characters "露出" are represented in UTF-8 by the byte sequence e9 9c b2 e5 87 ba

I suspect this is some sore of "anti-scrapping" measure, where some of the text is being scrambled to make it unpleasant to read the raw HTML from the server.  I suspect there's JavaScript in the background of the page that de-scrambles these runs when viewing in a web browser.

Will need to write my own de-scramble code.  Complication is I don't know what the edge cases look like.

**Comment by dteviot** [comment]
@Bsubs
Updated version (0.0.0.90) has been pushed to Mozilla and Chrome stores.  Should be available within a few hours.  Your existing version should update automatically within 48 hours.
Note, I *think* it will work, but I'm not 100% sure it will in all cases.  Please try it out and let me know.

**Comment by Bsubs** [comment]
Hi dteviot,
Thanks so much for the hard work in creating this fix! It works perfectly now.
