### ISSUE TITLE
[ERROR] Image not Include

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#298]
**Can not get Images**
Novelplanet always error for getting the Images

- Novel URL: [e.g. https://novelplanet.com/Novel/Kujibiki-Tokushou-Musou-H%C4%81remu-ken/v3-illustrations?id=191578]
- Chrome Canary Version: [80.0.3951.0] Mac

<a href="https://novelplanet.com/Novel/Kujibiki-Tokushou-Musou-H%C4%81remu-ken/v3-illustrations?id=191578">Kujibiki Tokushou: Musou Hāremu ken Volume 3 illustrations</a>

**Comment by dteviot** [comment]
@3dycosmo
Can you be more specific about the problem?
When I try that URL, I get all but one of the images.  (One returns a 404 error)
There are warning messages, that look like this, but they can be ignored.
> Fetch of URL 'https://paichuntranslations.com/1-24/' returned HTML, expected an image.
Fetch of URL 'https://paichuntranslations.com/2-19/' returned HTML, expected an image.
Fetch of URL 'https://paichuntranslations.com/3-17/' returned HTML, expected an image.
Fetch of URL 'https://paichuntranslations.com/4-19/' returned HTML, expected an image.

What's happening in this case is, when WebToEpub sees an &lt;img&gt; element that is enclosed in &lt;a&gt; element, it tries to follow the hyperlink, assuming it's a link to the full size image. However, if the hyperlink returns a web page, then WebToEpub just uses the image.  The warning can be igored, or tells me that code needs to be added to find the image in the returned HTML.
The 404 error seems to due to the image URL being corrupted HTML in the &lt;img&gt; tag.
That said, NovelPlanet is an exaggerator site,  That particular story seems to be from the site https://paichuntranslations.com.  I suggest you try fetching it from there.

**Comment by 3dycosmo** [comment]
> @3dycosmo
> Can you be more specific about the problem?
> When I try that URL, I get all but one of the images. (One returns a 404 error)
> There are warning messages, that look like this, but they can be ignored.
> 
> > Fetch of URL 'https://paichuntranslations.com/1-24/' returned HTML, expected an image.
> > Fetch of URL 'https://paichuntranslations.com/2-19/' returned HTML, expected an image.
> > Fetch of URL 'https://paichuntranslations.com/3-17/' returned HTML, expected an image.
> > Fetch of URL 'https://paichuntranslations.com/4-19/' returned HTML, expected an image.
> 
> What's happening in this case is, when WebToEpub sees an <img> element that is enclosed in <a> element, it tries to follow the hyperlink, assuming it's a link to the full size image. However, if the hyperlink returns a web page, then WebToEpub just uses the image. The warning can be igored, or tells me that code needs to be added to find the image in the returned HTML.
> The 404 error seems to due to the image URL being corrupted HTML in the <img> tag.
> That said, NovelPlanet is an exaggerator site, That particular story seems to be from the site https://paichuntranslations.com. I suggest you try fetching it from there.

Message;
Error: Could not find content element for web page 'https://novelplanet.com/Message/PrivacyPolicy'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:442:23
    at async Promise.all (index 1)

File;
[Kujibiki...remu_ken.zip](https://github.com/dteviot/WebToEpub/files/3781804/Kujibiki.remu_ken.zip)

**Comment by 3dycosmo** [comment]
Thx, yeah, I DL from ttps://paichuntranslations.com.

[ERROR] message from
https://novelplanet.com/Novel/Kujibiki-Tokushou-Musou-H%C4%81remu-ken;

`OK
Fetch of URL 'https://paichuntranslations.com/1-24/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/1-30/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2-19/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/2-24/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/3-17/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/3-22/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/4-24/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/4-19/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/5-24/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/5-19/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/6-19/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/6-24/' returned HTML, expected an image.

Error: Fetch of URL 'https://paichuntranslations.files.wordpress.com/2016/1%20%20%20%20%20%20%20%20%3Cdiv%20style=' failed with network error 404.
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:25)
    at Function.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:163:45)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:157:31
    at async Promise.all (index 0)

Fetch of URL 'https://paichuntranslations.com/8-19/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/7-24/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/9-17/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/8-23/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/10-15/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/9-21/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/10-18/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/11-16/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/12-16/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/13-15/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/14-14/' returned HTML, expected an image.

Fetch of URL 'https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/15-9/' returned HTML, expected an image.`

**Comment by dteviot** [comment]
@3dycosmo 
I'm thinking that changing the error message to something like
> Attempt to retrieve higher resolution version of image https://i1.wp.com/paichuntranslations.com/wp-content/uploads/2016/12/18.jpg from https://paichuntranslations.com/2017/04/28/kujibiki-tokushou-chapter-87/13-15/' failed.  Falling back to lower resolution image.

What do you think?  Or can you suggest a better message?
