### ISSUE TITLE
[ADD] Qinxiaoshuo

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#305]
Please add the following web sites
- [x] http://qinxiaoshuo.com/
- [x] https://www.wenku8.net
- [x] https://kakuyomu.jp
- [x] https://novel18.syosetu.com
- [x] https://xiaoshuogui.com/lightnovel/

http://qinxiaoshuo.com/
Please add this web
it contains many JP LN RAW [CN Lang]

https://www.wenku8.net/zt/sugoi/2019.php
Complete JP LN (RAW) coz many haven't been translated to EN

https://kakuyomu.jp/works/1177354054884043614
This web is second to syosetu on JP WN

https://novel18.syosetu.com/n0280z/
The same parser with syosetu

Thx, dteviot

**Comment by dteviot** [comment]
**Notes**
1. http://qinxiaoshuo.com/book/OVERLORD seems to be English.  So examine this to build parser.

**Comment by 3dycosmo** [comment]
> **Notes**
> 
> 1. http://qinxiaoshuo.com/book/OVERLORD seems to be English.  So examine this to build parser.  Nope. Google translate had a go at it.
> 2. Some chapters are across multiple pages.  See: http://qinxiaoshuo.com/read/0/1545/5d77d0dd56fec85e5b0ffd1a.html

How about this, the sister site of wenku8
https://xiaoshuogui.com/lightnovel/

and this web 
https://kakuyomu.jp/works/1177354054884043614
is second largest after syosetu, JP RAW tend to be deleted by author after book published, so offline saving for future gen

**Comment by dteviot** [comment]
@3dycosmo 
It's just taken me 4 hours to do qinxiaoshuo.com and you're immediately asking for more?!
I'm wondering why I even bothered to write https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

That said, based on the fact your asking for English, Japanese and Chinese sites, can I assume you can read Japanese?  In which case, I have a large favor to ask.

**Comment by dteviot** [comment]
@@3dycosmo 
Regarging the wenku8 site..
I seem to be missing something.
I go to the main page for a title, say https://www.wenku8.net/book/1943.htm
But I can't see any ToC/Volmues/Chapters lists
There are some download options like
https://www.wenku8.net/modules/article/packshow.php?id=1943&type=txtfull
But following them seems to be single file with all text.

**Comment by dteviot** [comment]
@3dycosmo
I've implemented parsers for all but www.wenku8.net in the ExperimentalTab branch.
I'll need your help for that one, as I can't seem to find a Table of Contents entry.
That said, you might like to try installing from source the ExperimentalTab branch and let me know if there are any issues with the other sites.

**Comment by dteviot** [comment]
@3dycosmo
Nevermind.  I think I've figured it out.
If the URL is like: https://www.wenku8.net/book/1973.htm
then making the following call will return the ToC: https://www.wenku8.net/modules/article/reader.php?aid=1943

**Comment by 3dycosmo** [comment]
> @3dycosmo
> It's just taken me 4 hours to do qinxiaoshuo.com and you're immediately asking for more?!
> I'm wondering why I even bothered to write https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
> 
> That said, based on the fact your asking for English, Japanese and Chinese sites, can I assume you can read Japanese? In which case, I have a large favor to ask.

Sorry, my misunderstanding.
the reply said (Nope. Google translate had a go at it.) I thought that you refused qinxiaoshuo.com so, I exchange it to xiaoshuogui.com in which the same as wenku8.net but new, the same account could be used in both site.
And yeah, I have yet read the DIY parser, link it to Html (I will go for it), Favour? well for Japanese only normal one, though I would glad
Thx

**Comment by dteviot** [comment]
@3dycosmo
And that's the last of them.
Note,www.wenku8.net  may be problematic. It seems to use a mixture of encodings.  Mostly GBK, but also Big5 and UTF-8 in various places.  And it doesn't tell the caller what the encoding is.
So, WebToEpub assumes GBK.  When it's not, it will produce garbage.  Please try and let me know how it goes.  (Note you'll need to install from source the ExperimentalTab branch, as I haven't committed to master or pushed to the Chrome store, until you've given them a sanity check.)

> the reply said (Nope. Google translate had a go at it.) 

That wasn't a reply, that was a note for me. (That's why it had "Notes" at the start.)  But yes, it wasn't clear.  I meant, no, the story was not in English, I just thought it was because Chrome had run the page through Google translate and I hadn't noticed.

> Favour? well for Japanese only normal one, though I would glad

Thanks.  Please send an email to dteviot@gmail.com and I'll send you the details.

**Comment by dteviot** [comment]
Closing due to lack of response.  I assume it's working
