### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yonkyunior** [dteviot/WebToEpub#307]
**404 Error URL Status Auto Skip**
If the extension detect bad URL link with 404 status, skip the link to next URL

**ADD URL LIST (Edit Chapter URLs Button)**
sometimes i did workaround without starting URL, 
i created a list myself with excel, and paste in Edit Chapter URL
`<a href="WWW.URL.COM/TITLE-chapter-2/">Chapter 1</a>`

**Button for testing parser in front**
When No Parser Found, the extension detect automatically.
I found this very helpful, so i can test, and put manual selector.

**Comment by dteviot** [comment]
@yonkyunior 
Please submit one suggestion per incident.  It makes tracking/finding/responding easier for me. 
Also, can you provide more details because I'm not sure what you're asking for?  
Ideally, in the form of a use case. 
e.g. Describe it as if you were talking a user though doing it it step by step over the phone. 
1. What do they see
2. What do they do
3. What happens next.
4 Repeat from step 1.

**Comment by 3dycosmo** [comment]
1. auto skip, it uses when the page missing or not found it happens a lot when I am adding pages manually via the  "edit URL", in the current Webtoepub it stops the parsing, so all the list after the error page couldn't be parsed
2. add URL, basically the same as edit URL anyway (passed)
3. button? ain't clicked the Webtoepub button be done, it shows the tester parser (passed)

**Comment by dteviot** [comment]
@yonkyunior 
I believe my commit solves the "404 Error URL Status Auto Skip".  (@3dycosmo you might like to install from source and let me know what you think.)
In short, under the Advanced Options, I've added "Skip chapters that return HTTP 404 error"  If you check this, if a chapter can't be fetched, a placeholder will be inserted into the epub and WebToEpub will continue trying to fetch the following chapters.

If you want me to do anything about the other two items, you will need to create new issues for them.  (I'd do it myself, but then you won't be automatically notified about them.)
If you do create new issues, please include a description of the problem you're trying to solve as well as what you want.
For example, I don't understand the request for 
> ADD URL LIST (Edit Chapter URLs Button).  

Why you can't just click the "Edit Chapter URLs" button and paste in links?

As regards 
> Button for testing parser in front

I don't even understand what you're asking for.
Please see : https://github.com/rstudio/rstudio/wiki/Writing-Good-Feature-Requests
