### ISSUE TITLE
BabelNovel - After downloading about 60+ chapters, all subsequent chapters show only the first paragraph

### ISSUE THREAD

**Issue by 8917489712a** [dteviot/WebToEpub#308]
So was downloading a book with about 500+ chapters and while reading noticed that after around chapter 60+ all subsequent chapters only had about the first paragraph shown.

**Comment by dteviot** [comment]
@8917489712a 
Babel Novel has some sort of rule.  You can see the first 50 chapters or so of a story for free.  After that you have to "pay" for them somehow.  Note, I'm not sure how it works, I don't read anything from that site.  For the chapters you have to pay for, you only get the first paragraph/sentence of a chapter.
