### ISSUE TITLE
Should we place content in the blank space mentioned in #28, and if so then what should we put?

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#31]
This question is for everyone including the creator of this project. 

Since we cannot get rid of the blank section in Novel Illustrations without causing issues, the next best thing is to fill it with some kind of content.

Should we fill it with copyright disclaimer information, or something else maybe?

You guys decide.

**Comment by typhoon71** [comment]
I don't think it would be a good idea.
Btw, I updated #28, there's more to it (sadly)

**Comment by belldandu** [comment]
see #30 already took care of that.

**Comment by dteviot** [comment]
As we're now removing the blank section, this question no longer needs an answer.

**Comment by belldandu** [comment]
Awesome
