### ISSUE TITLE
Add support for the site "https://dark-novels.ru/"

### ISSUE THREAD

**Issue by togri** [dteviot/WebToEpub#311]
Add support for the site "https://dark-novels.ru/"

**Comment by dteviot** [comment]
@togri 
Tricky.  I _suspect_ to get the content for a chapter with a ToC entry of https://dark-novels.ru/read/348/204864, I need to call https://api.dark-novels.ru/v1/books/chapter/ passing it a form with 
b: 348
f: html
c: 204864

However, the response is not directly usable. It seems to be binary data.  Figuring out it's encoding will take a while, especially as I don't know Russian.

**Comment by dteviot** [comment]
@togri
I believe I have a working parser for dark-novels.ru. However, I'm not able to do much testing or checking as I can't read Russian. Please go to https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode and follow the instructions for "Install from Source" from the current development branch. and test it out. Let me know if you have any issues.

**Comment by togri** [comment]
Works great with chapters from free access. The site has "VIP" access and does not download chapters from it :( Will there be time to figure it out? I can provide an account.

**Comment by dteviot** [comment]
@togri 
> Will there be time to figure it out? I can provide an account.

Email me the account details (dteviot@gmail.com) and I'll have a try.  I can't make any promises.
That said
1. I assume you logged in with the account before opening WebToEpub.
2. When you do that, does the chapter list shown by WebToEpub show all chapters, including the paid ones?  (When not paid, all chapters have same URL, so WebToEpub removes them as duplicates.)

**Comment by togri** [comment]
I sent along with the video how it goes

**Comment by dteviot** [comment]
@togri
I'm afraid the news isn't good.There's a number of issues.
1. It looks like the paid content is sent as image files, not as html.  So any epub is going to get big, fast.
2. The form params are different for the paid content.  So, would need to figure out if page is free or paid and adjust accordingly.  Not impossible, but would take some time. 
3. Paid request has token value in the header which is not present when WebToEpub makes request.  Figuring this out is likely to take a lot of effort.

**Comment by togri** [comment]
By me, the epub format is used to read from a phone with a small screen (480 × 320) and I don’t think it will be convenient to read from pictures. Thank you for your help, you can close if there is no way to read comfortably from the phone. Thank you again.

**Comment by togri** [comment]
I saw a message in the email. Thank you and good luck :)

**Comment by dteviot** [comment]
Some final thoughts, in case anyone else wants to pursue this further.

As regards finding the value of the token to include in the request's header.  Quick and dirty way is tell browser to open a new window to dark-novels, and use the "webRequest" API to read the value of the token from the communications done by the window.  (See file Firefox.js) for code using the API.  Note, Google don't like this API (it's used by Add Blockers) and will be removing it shortly. So this would only work for Firefox.

I had thought it might be possible that server sending the response as image (in the zip) might not be an issue.
I note that when fetching paid content, the 'f' parameter of the form was set to "png" not "html", I hypothesize that setting this to "png" returns an image, while setting to "html" would return "HTML".
Testing the hypothesis by try fetching a non-paid chapter with 'f' parameter set to "png" returned a 400 error.  Suggesting that using "html" for a paid chapter probably won't work.

**Comment by dteviot** [comment]
@togri
New version (0.0.0.95) with support for dark-novels.ru (free content only) has been submitted to Chrome https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm and Firefox https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/ stores. Updated version is now available from Firefox store.
Chrome version will be available once it passes review (I'd guess that will take a week, given the holidays) Check the version number on the page to see which version is available.
Note, Chrome should automatically update your installed version of extension within a few days of it becoming available.
