### ISSUE TITLE
Add Support https://fastnovel.net/ and https://novelsrock.com/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#312]
https://novelsrock.com/
https://fastnovel.net/

**Comment by dteviot** [comment]
@Finks82
New version (0.0.0.95) has been submitted to Chrome https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm and Firefox https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/ stores. Updated version is now available from Firefox store.
Chrome version will be available once it passes review (I'd guess that will take a week, given the holidays) Check the version number on the page to see which version is available.
Note, Chrome should automatically update your installed version of extension within a few days of it becoming available.
