### ISSUE TITLE
Class element shows when reading the packed epub novel of "webnovelonline.com"

### ISSUE THREAD

**Issue by wintersnew** [dteviot/WebToEpub#315]
Hi @dteviot, I'm currently having a problem on how to remove the class element here. (please see the red box below):
![Capture](https://user-images.githubusercontent.com/38267997/71352973-a8864680-25b2-11ea-916c-50ce8637e54b.PNG)
Note: That's already a packed epub using your tool. I don't know the reason why those class elements appeared.
![Capture2](https://user-images.githubusercontent.com/38267997/71353094-09158380-25b3-11ea-9465-dfbdeab5969b.PNG)
Please help me on how to resolve this.
Here is the link btw: https://webnovelonline.com/chapter/the_beginning_after_the_end/chapter-121

**Comment by dteviot** [comment]
@wintersnew 
The chapters I initially looked at had their content formatted as text, so needed to be converted to HTML.  The chapters you're showing me are HTML.  So they need to be treated differently.
This can always be a problem, site doesn't format all stories (or even all chapters of a story the same way.)  And I certainly don't check more than a couple of chapters.

Fix is reasonably easy.  Look at the content, make educated guess if text or HTML and treat accordingly.  I've committed fix https://github.com/dteviot/WebToEpub/commit/11da015fa04ed6f034cc8517fbaee56823810287 to the Experimental branch, if you'd like to install from source and let me know how it goes.
