### ISSUE TITLE
https://novelsrock.com/      half page missing

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#316]
When I make epub from https://novelsrock.com/ I notice some text are missing
example https://novelsrock.com/novel/reincarnation-in-naruto-world/chapter-885/
 I try DL batch chapter or just that single chapter its missing half of the page on the copy.

same result on chrome and firefox

**Comment by dteviot** [comment]
@Finks82
My apologies.
The chapters I initially looked at had all the content in the &lt;div class="reading-content"&gt; element.
Other chapters have only some in that element, and the parent element, &lt;div class="read-container"&gt; has all the chapter content.
Updated version 0.0.0.96 of WebToEpub has been pushed to Chrome and Mozilla stores.
Firefox version is avaiable for download.
Chrome version needs to pass review by Google, so will won't be avaiable for a few days (based on previous experience).
