### ISSUE TITLE
https://novelsrock.com/novel/naruto-madman/   & https://novelsrock.com/novel/long-live-the-hokage/  Error

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#317]
Error: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/ChapterUrlsUI.js:244:36
    at Array.forEach (<anonymous>)
    at Function.resizeTitleColumnToFit (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/ChapterUrlsUI.js:244:16)
    at ChapterUrlsUI.populateChapterUrlsTable (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/ChapterUrlsUI.js:39:23)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:338:27

-----------------------------
Unable to create epub from  https://novelsrock.com/novel/long-live-the-hokage/  and https://novelsrock.com/novel/naruto-madman/   

Other old file is fine when creating epub, seems like only the newly added novel have problem.

**Comment by dteviot** [comment]
@Finks82 
There are two issues.
1. The Table of Contents for some stores has two URLs for each chapter.  One with the chapter name, the other with an image.  Code is selecting the one with the image, which lacks the chapter names.  This results in second error
2. With no chapter names, can't calculate length of input control to allow user to manually input chapter titles.

**Comment by dteviot** [comment]
@Finks82
Updated version 0.0.0.97 of WebToEpub has been pushed to Chrome and Mozilla stores.
Firefox version is available for download.
Chrome version needs to pass review by Google, so will won't be available (based on previous experience)for a few days .
