### ISSUE TITLE
Add Advanced Option "Skip images"

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#321]
Requested by @c-h-u-c-k
>  add a specific skip images advanced option to not even try them? As I generally don't care about pictures, just the text.

(Copied from https://github.com/dteviot/WebToEpub/issues/160, as this is really a different feature request.)

**Comment by dteviot** [comment]
@c-h-u-c-k
New version (0.0.0.99) of WebToEpub for Firefox has been pushed to https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/.
I've added "Skip images" to the advanced options, if you want to give it a try.

**Comment by c-h-u-c-k** [comment]
This solves the problem for me, thank you!
