### ISSUE TITLE
Cannot convert chapters in Mtlnovel

### ISSUE THREAD

**Issue by yourboy-design** [dteviot/WebToEpub#323]
Theres an error in converting chapters in Mtlnovel

**Comment by dteviot** [comment]
@yourboy-design 
Please provide more details.
1. URL of chapter with problem.
2. Description of the error.

**Comment by yourboy-design** [comment]
1.https://www.mtlnovel.com/mini-world-of-endless-fun-awaits/
2.after converting it seems there is an error in parsing name attribute name
ex.(This page contains the following errors:error on line 1 at column 422: error parsing attribute name
Below is a rendering of the page up to the first error.)

**Comment by yourboy-design** [comment]
when will webtoepub be updated

**Comment by dteviot** [comment]
@yourboy-design
Version 0.0.0.100 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/developers/addon/webtoepub-for-baka-tsuki/edit
Google tells me they need to review the new version for Chrome, and it might be days to weeks before it's approved (if at all, they've changed the process and require me to provide explanations for all the permissions it requires.)
