### ISSUE TITLE
Request for parser for spacebattles and sufficient velocity

### ISSUE THREAD

**Issue by minshimun** [dteviot/WebToEpub#325]
I tried webtoepub on spacebattles now my head aches with frustration.it does not follow the threadmarks.

https://forums.spacebattles.com/

https://forums.sufficientvelocity.com/

**Comment by dteviot** [comment]
@minshimun 
For Spacebattles, can I assume you've opened the full list of threadmarks before opening WebToEpub?
So WebToEpub can use that for the Table of Contents?

**Comment by dteviot** [comment]
*Private Notes*
Notes:
For space battles, looks like the stories start at https://forums.spacebattles.com/forums/creative-writing.18/
Picking a story, say 
https://forums.spacebattles.com/threads/the-travelling-merchant-and-wandering-mage-multi-cross-si.814331/
Then need to see all the threadmarks.
Note, need to use the # part of the URLs to get the post IDs for the title.

**Comment by minshimun** [comment]
![Screenshot_2020-03-03-19-44-03](https://user-images.githubusercontent.com/61673504/75772672-5ec29500-5d87-11ea-8143-610ed58abea1.png)


???

**Comment by dteviot** [comment]
@minshimun
My apologies, I wasn't very clear.
What I meant was, I'm going to add support for Spacebattles (and sufficientvelocity).
However, for WebToEpub to work, you'll need to browse to the threadmarks for the story (the marks list the posts that make the chapters) and have it display all the threadmarks so WebToEpub can find the chapters.

Anyway, changes have been made and new version 0.0.0.101 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved

**Comment by minshimun** [comment]
Thanks
