### ISSUE TITLE
request

### ISSUE THREAD

**Issue by sephile** [dteviot/WebToEpub#326]
requesting this site https://www.novelhall.com/......

oh awsome job by the way for those other pages

**Comment by dteviot** [comment]
@sephile 
Changes have been made and new version 0.0.0.101 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved
