### ISSUE TITLE
Can't read past Chapter 156 Legion of Nothing.

### ISSUE THREAD

**Issue by macezar** [dteviot/WebToEpub#327]
Trying to convert to epub Legion of Nothing, on Royal Road website, but for some reason, it stops at the chapter 156 and doesn't convert all chapters to epub.

https://www.royalroad.com/fiction/6455/the-legion-of-nothing
![PrtScr capture_2](https://user-images.githubusercontent.com/5649304/75715985-48083980-5cc6-11ea-90f2-33de7659ca05.jpg)

**Comment by dteviot** [comment]
**Initial Hypothesis.**
Looks like problem might start at https://www.royalroad.com/fiction/6455/the-legion-of-nothing/chapter/97827/three-part-17
This has an &lt;img&gt; tag with no src attribute.
```html
<img class="wp-more-tag mce-wp-more" title="Read more..." alt="">
````

**Comment by dteviot** [comment]
@macezar 
While I have just committed a fix for this problem, I've just received three other requests, so it's going to be several days before I will have a new WebToEpub available.

As a quick fix, check the "Skip images" check box and try again.
Problem is a malformed &lt;img&gt; tag that halts the parser.
Checking that box tells WebToEpub to ignore all &lt;img&gt; tags.

**Comment by macezar** [comment]
Thanks brother, you're the best. <3

**Comment by dteviot** [comment]
@macezar
Just remember to un-check "Skip images" when you're done

**Comment by dteviot** [comment]
@macezar
Changes have been made and new version 0.0.0.101 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved
