### ISSUE TITLE
WLPublishingParser fails for chapters with 3+ pages

### ISSUE THREAD

**Issue by tcgoetz** [dteviot/WebToEpub#328]
Fix:

[WLPublishingParser.js.patch.zip](https://github.com/dteviot/WebToEpub/files/4279142/WLPublishingParser.js.patch.zip)

**Comment by dteviot** [comment]
@tcgoetz
Can you give the the URL of a chapter with 3+ pages, I'd like to look at this in more detail.
Is there a reason you didn't offer this as a pull request? https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by tcgoetz** [comment]
https://finestories.com/s/10041/the-trail-west

> dom.querySelector is not a function findContent@moz-extension://40997e61-9b6f-114b-a947-9c5ac456cbef/js/parsers/WLPublishingParser.js:32:20
> fetchChapterPage@moz-extension://40997e61-9b6f-114b-a947-9c5ac456cbef/js/parsers/WLPublishingParser.js:101:35
> fetchChapter/</<@moz-extension://40997e61-9b6f-114b-a947-9c5ac456cbef/js/parsers/WLPublishingParser.js:74:28
> fetchChapter/<@moz-extension://40997e61-9b6f-114b-a947-9c5ac456cbef/js/parsers/WLPublishingParser.js:73:23

**Comment by tcgoetz** [comment]
> Is there a reason you didn't offer this as a pull request?

I've known it was broken for a while, but have had trouble finding time to fix it properly. I thought offering the patch was better than nothing. Sorry!

**Comment by tcgoetz** [comment]
BTW, stories that have no chapter listing (single page stories) are also broken, but I have no fix for those at this time.

They could be fixed by using the multi-page chapter code if a chapter listing is not found. I'll try to get to that eventually.

**Comment by dteviot** [comment]
@tcgoetz 
Firstly, thanks for the prompt reply, it's really appreciated.

> I've known it was broken for a while, but have had trouble finding time to fix it properly. I thought offering the patch was better than nothing. Sorry!

I'm grateful for your effort.  But I wish you'd told me about the problem sooner.  Then I could have taken care of it.  

Also please ignore my suggestion to submit a pull request, I think I've got a simpler way to fix the 3+ page issue. Basically, replace the Promise.then() with async/await.  Which is something I was planning to do anyway.

> They could be fixed by using the multi-page chapter code if a chapter listing is not found. I'll try to get to that eventually.

Don't worry about it I'll take care of it.

**Comment by tcgoetz** [comment]
OK, thanks for fixing it.

**Comment by dteviot** [comment]
@tcgoetz
Changes have been made and new version 0.0.0.101 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved
