### ISSUE TITLE
www.mtlnovel.com - every page now show some vote stat, So please help remove it.

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#329]
www.mtlnovel.com - every page now show some vote stat, So please help remove it.
Example - https://www.mtlnovel.com/restart-home/chapter-400-living-specimen-room/ 

More Action Novels

Boss Level Face-Slapping Specialist [Quick Transmigration]
4.4 (5 votes) - 117.3K views
Chaotic Sword God
4.7 (3 votes) - 39.1K views
Godly Alchemist
5.0 (1 votes) - 3.1K views
Venerated Venomous Consort
4.7 (3 votes) - 34.1K views
Unparalleled Emperor
4.5 (2 votes) - 66K viewsView more »
Popular Today

My Fantasy Comes to One Billion Years Later (17.3k views today)
Reincarnation Of The Businesswoman At School (11.2k views today)
Super God-level Technology Empire (9.8k views today)
Bewitching Prince Spoils His Wife: Genius Doctor Unscrupulous Consort (8.7k views today)
Infinite Evolution (7.5k views today)View more »
New Novels

Young Master Mo, Are You Done Kissing? (1 hour ago)
Knight of the Light (2 hours ago)
The Boss Behind The Game (4 hours ago)
My Abducted Tsundere Husband (6 hours ago)
Lin Yuanxing (8 hours ago)View more »
Recently Updated

Great Doctor Ling Ran: Chapter 1087 rain
Overriding the Heaven: Chapter 1808 Real world where you can show your strength
War Sovereign Soaring The Heavens: Chapter 3915 Feng Shui turns
Titan and Dragon King: Chapter 1279 Of course please me
Co-renting Immortal Doctor: Chapter 6694 It's your father!

**Comment by dteviot** [comment]
@Finks82
Changes have been made and new version 0.0.0.101 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved
