### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#33]
I noticed there was something along the lines of changing the icon, so... I suggest this one:

http://www.flaticon.com/free-icon/books_150360

It's the one I use on Firefox; since you already have to unzip, zip, change extension... one can just replace the icon .png. The strange thing is that the default icon is OK.-ish on chrome, but renders horribly on Firefox.

**Comment by dteviot** [comment]
Thanks, will look into in more detail when I have time.
My read is that to use it I'd need to add a credits page to the app.
At moment fixing Icon is right at the bottom of my priority list.

**Comment by typhoon71** [comment]
Yes, I understant it's low priority, np.
The icon was nice (and a lil credit should be ok) so I let you know.
Should this be kept open?

**Comment by dteviot** [comment]
@typhoon71
Yes, leave it open please.

**Comment by dteviot** [comment]
I contaned flaticon support and confirmed, use of that image would require adding a credit page to app.  And personally, I think the app layout is already getting too messy.

**Comment by typhoon71** [comment]
mmm, I understand, too bad.

Since my original issue was that the addon icon looked bad in firefox (only), I took the liberty of trying to fix it: I removed the white lines on the borders of the 128x128 png, so now that is transparent too.
I suppose that wasn't part of the intended design (an open book).

**OLD**
![book128](https://cloud.githubusercontent.com/assets/1866248/21238285/bcca65f6-c302-11e6-9113-3a8fcde9395a.png)

**NEW**
![book128](https://cloud.githubusercontent.com/assets/1866248/21238035/b3481588-c301-11e6-99ab-ca342ab2f7f5.png)

You won't see the difference on github bacause the page is white. 
The icon looks the same on chromium and now looks the same on firefox, with the white removed.

I understand making the icon look good is not a primary objective, but this little fix should be feasible.

Thanks anyway.

**Comment by toshiya44** [comment]
I can do some simple stuff on gimp... If you make a sketch I can probably give it a try. :D

**Comment by dteviot** [comment]
@typhoon71
Thank you for the updated bitmap, I'll apply it shortly.  

@toshiya44
Thank you for the offer.  What I'd like to see would be a web, with the EPUB logo picked out as part of the web.  That said, I'd be happy with any public domain image that's vaguely suitable.

**Comment by typhoon71** [comment]
**@toshiya44**
If you make an icon, don't forget there's users of dark themes too ;)

**Comment by belldandu** [comment]
Closing this as it appears complete.
