### ISSUE TITLE
Could not find content element for web page 'https://thesylthorian.com/2016/04/15/chapter-2-ma/'. fetchWebPageContent/<@moz-extension://16c83e2a-da81-47ff-8555-b9e406c2349a/js/Parser.js:454:23

### ISSUE THREAD

**Issue by minshimun** [dteviot/WebToEpub#330]
Webnovel Content not found

**Comment by dteviot** [comment]
@minshimun 
I'm not quite sure what happened here.
I think you've used Firefox, gone to https://thesylthorian.com/wn-ma/, and tried to convert Map 1, Map 2 and the other chapters into an epub.
It looks like the URL for Map 1, returns a format that WebToEpub can't handle.
The URL is https://imgur.com/gallery/bEiacMR?grid
If you remove the gallery part of the URL i.e. Change it to https://imgur.com/bEiacMR?grid, then WebToEpub works.  (You can change the URL by clicking the "Edit Chapter URLs" button.)
It also seems to work fine if you don't include "Map 1" in the list of chapters.

Additional note, WebToEpub is falling back to the default parser.  Which means each chapter/page has a lot of unwanted stuff at the bottom.  I probably need to provide a parser specifically for this site.

**Comment by minshimun** [comment]
it's still not working the migh
