### ISSUE TITLE
Packing an Epub while one is still being packed

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#331]
FYI: This isn't that big a deal, just annoying if you don't realize, want to change something in the epub, or accidentally clicked the pack epub button multiple times.

Example Situation:
You click pack epub then realize it has the wrong title so you change it and click pack epub again while the former one was still in progress.

Result:
The counter on the progress resets and when it is complete you end up with two different epub files. The first epub file is the one with the initial settings and is complete, the second one is the epub with modified settings but is incomplete. The second epub seems to start off opposite to the point you clicked pack epub.

ie if you double-clicked the pack epub for a story with 50 chapters you would get one epub with chapters 1-50 and a second one with just chapter 50, or if some time passes between clicks it would be an epub with chapters 1-50 and a second one with just chapters 30-50.

Problem:
Changing the settings and seeing the progress bar resets implies that the second epub would be a complete epub with the new settings, instead, it results in one incomplete epub with the correct settings and one complete epub with the incorrect settings. This usually occurs with big epubs such as web serials which generally have an author <unknown> and attempting to change it mid packing.

**Comment by dteviot** [comment]
@JeremyStarten
Thank you for bringing this to my attention.
"Pack EPUB" button should now be disabled when creating an EPUB.

**Comment by dteviot** [comment]
@JeremyStarten
Changes have been made and new version 0.0.0.102 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved
