### ISSUE TITLE
Doesn't get cover for scribble hub

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#332]
Title

**Comment by dteviot** [comment]
@JeremyStarten
I tried a couple of titles, 
* https://www.scribblehub.com/series/100985/system-is-accepting-applications/
* https://www.scribblehub.com/series/100857/be-careful-of-what-you-wish-for/

they all had a cover image.
Please provide more information
* URL of at least one story that has the problem
* A better description of the problem.

**Comment by JeremyStarten** [comment]
Sorry, it doesnt work when using firefox on the phone. Tried both links with firefox on the phone and the cover link was empty

**Comment by dteviot** [comment]
@JeremyStarten 
Thanks, I see the problem now.
When using a mobile browser, the site returns different HTML to a desktop.
In mobile mode, the cover image is in a &lt:div&gt; element with a class of "novel-cover_mb", in desktop mode, the  &lt:div&gt; element has a class of "novel-cover".

Easy to fix, but I'm currently working on something else, so may be a few days before I upload new version to Chrome and Firefox stores.

**Comment by minshimun** [comment]
Try following this [guide](https://support.mozilla.org/en-US/questions/1114055) then use webtoepub again works only on Firefox

**Comment by dteviot** [comment]
@JeremyStarten
Changes have been made and new version 0.0.0.102 has been submitted to Chrome and Firefox stores.
Firefox version has been approved and is available for download. https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Google tells me they need to review the new version for Chrome, and will be a few days before it's approved
