### ISSUE TITLE
AO3 every chapter has "chapter text" instead of the actual chapter name.

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#334]
Tested on 
https://archiveofourown.org/works/20300992/chapters/48126469
https://archiveofourown.org/works/20664290
https://archiveofourown.org/works/1536152
Both phone and computer

Examples
![Screenshot_20200318-225400_Moon+ Reader Pro](https://user-images.githubusercontent.com/39293934/77036048-654a3280-696b-11ea-8bae-6eca8d685ca1.jpg)
![Screenshot_20200318-225427_Google Play Books](https://user-images.githubusercontent.com/39293934/77036070-709d5e00-696b-11ea-8b33-76058ef75e42.jpg)

**Comment by dteviot** [comment]
@JeremyStarten 
I didn't see this issue until just after I uploaded the previous set of fixes to Chrome and Firefox.
I've got a fix and committed to Github.  However, as Chrome takes a few days to clear, I won't update the version in the stores until next week.

**Comment by dteviot** [comment]
@JeremyStarten
Also note, the AO3 site already provides the ability to download as an epub.  Steps are:
1. Click on the downloads button, usually at the top right of the page.
2. In the set of choices, select "EPUB"

**Comment by dteviot** [comment]
@JeremyStarten
Updated version (0.0.0.103) has been posted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.
