### ISSUE TITLE
request add hentai-foundry.com

### ISSUE THREAD

**Issue by minshimun** [dteviot/WebToEpub#335]

**Comment by dteviot** [comment]
@minshimun 
I'd like you to try it out before I upload to stores.
If I give you a test build, can you try it on a desktop version of Firefox or Chrome?  If so, which do you prefer.
I can't give you a Firefox for Android build.  That needs to be signed by Mozilla.

**Comment by minshimun** [comment]
I'll just wait then.thanks

**Comment by dteviot** [comment]
@minshimun 
I assume you're using Firefox on Android then.
Updated version (0.0.0.103) has been posted to Chrome and Firefox stores.
If there are any issues, Just add a comment to this issue and I'll reopen.
