### ISSUE TITLE
request add www.mtlnovel.com

### ISSUE THREAD

**Issue by Xreylolz** [dteviot/WebToEpub#336]

**Comment by dteviot** [comment]
@Xreylolz
It is already **supposed** to be supported.
I just tried https://www.mtlnovel.com/the-female-supporting-character-ran-off-with-the-bun/, with Desktop Chrome version v0.0.0.102 and it seems to work fine.

- Can you provide URL of story with problems?
- And description of what happens?
- Also, what web browser are you using?  (Note, some sites serve up different version to Android.  (I don't test all sites against mobile android.)

**Comment by Xreylolz** [comment]
> @Xreylolz
> It is already **supposed** to be supported.
> I just tried https://www.mtlnovel.com/the-female-supporting-character-ran-off-with-the-bun/, with Desktop Chrome version v0.0.0.102 and it seems to work fine.
> 
>     * Can you provide URL of story with problems?
> 
>     * And description of what happens?
> 
>     * Also, what web browser are you using?  (Note, some sites

**Comment by Xreylolz** [comment]
thx u its work now after restart pc
