### ISSUE TITLE
unable to fetch URL in mtlnovel

### ISSUE THREAD

**Issue by itsyahma** [dteviot/WebToEpub#338]
When I try to fetch the url, this appears
(Fetch of URL 'https://www.mtlnovel.com/json/90257-c-6-1.json' failed with network error 404. onResponseError@moz-extension://5a3c349f-a405-4d57-9caf-3bc91182363a/js/HttpClient.js:28:25
checkResponseAndGetData@moz-extension://5a3c349f-a405-4d57-9caf-3bc91182363a/js/HttpClient.js:160:45
wrapFetchImpl/<@moz-extension://5a3c349f-a405-4d57-9caf-3bc91182363a/js/HttpClient.js:154:31)
  
So I don't know if it's the site that has the problem or its Webtoepub.

**Comment by dteviot** [comment]
@itsyahma 
This looks very similar to https://github.com/dteviot/WebToEpub/issues/337.
If you can provide me with the URL to the Table of Contents for the story, I will investigate further.

**Comment by itsyahma** [comment]
https://www.mtlnovel.com/super-dragon-evolution/chapter-list/

Here is the URL

**Comment by Finks82** [comment]
#337 here, have the same problem, try clicking advance setting > Manually Select Parser > select one of the "default" parser. not perfect but you can DL.

**Comment by itsyahma** [comment]
Thanks but I hope you can take care of it in the future

**Comment by dteviot** [comment]
@itsyahma 
Thanks.  I didn't know that existed.
What I was thinking of was https://www.mtlnovel.com/super-dragon-evolution/.  If you go there, then click on the chapters and try to expand any of the tags, e.g. "Chapters 1-250", you'll see they don't work.  If you record network activity, you'll see a call to the same URL that WebToEpub calls, and failing with a 404 error.
However, now that I know about the .../chapter-list/ URLs, I can get WehToEpub to use them instead.

**Comment by itsyahma** [comment]
No problem, just happy to help

**Comment by dteviot** [comment]
@itsyahma, @Finks82 
Thank your for your help.
Updated version (0.0.0.104) has been posted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.
If there are any issues, Just add a comment to this issue and I'll reopen.
