### ISSUE TITLE
issue in machine-translation.org/

### ISSUE THREAD

**Issue by itsyahma** [dteviot/WebToEpub#340]
For some reason I can't parse novels in this site using Webtoepub. Can you please check this out.

**Comment by dteviot** [comment]
@itsyahma 
Please provide more details.
I'm running Chrome version 81.0.4044.122, and was able to go to https://www.machine-translation.org/novel/9f44d6d2c6a1e5ea/this-slime-is-poisonous.html, and collect chapter 1.  Then  view it in an epub reader without issues.

I need to know
1. What Web Browser are you using?
2. What is the URL of story that has problem?
3. What does "can't parse novels" mean?  e.g. 
* Opening WebToEpub does not give list of chapters to view?
* Running WebToEpub gives errors when collecting chapters?
* Trying to view the generated EPUB fails?

**Comment by itsyahma** [comment]
1. Firefox

2.
https://www.machine-translation.org/novel/7825e3a20a1e5027/the-death-mage-who-doesnt-want-a-fourth-time.html

3.Opening WebToEpub does not give list of chapters to view

**Comment by dteviot** [comment]
@itsyahma 
I've just tried opening it with Firefox (standard desktop version).  It seems to work fine.  See attached screen shot.
1. Are you using mobile version of firefox?
2. Does the page https://www.machine-translation.org/novel/7825e3a20a1e5027/the-death-mage-who-doesnt-want-a-fourth-time.html show all chapters before you try opening WebToEpub?
3. Can you provide a similar screenshot of WebToEpub showing the problem?

![WebToEpub Issue340](https://user-images.githubusercontent.com/5157081/81140661-4a388e00-8fbe-11ea-817e-4ff92891a367.png)

**Comment by itsyahma** [comment]
1. Yes
2. Yes
3.

**Comment by dteviot** [comment]
@itsyahma
You need to tell me if you're using the mobile version of firefox.
The problem is, on mobile devices, site layout can be different from a desktop device. 
And I build WebToEpub on a desktop (because developing on a mobile device is difficult.)
So, sometimes WebToEpub fails for sites on a mobile device.  Which is what is happening in this case.

**Comment by dteviot** [comment]
Updated version (0.0.0.106) has been posted to Firefox store and is available.  There is no chrome version because Chrome on Android does not support extensions.

**Comment by dteviot** [comment]
@itsyahma
If the new version is working, please let me know.  And if it doesn't work, I really want to know.

**Comment by itsyahma** [comment]
It's working fine. Sorry for the late reply
