### ISSUE TITLE
please support Wordpress with Madara Theme 

### ISSUE THREAD

**Issue by T-Man2000** [dteviot/WebToEpub#343]
Wordpress and Madara Theme are becoming increasingly popular for LightNovels. Originally the theme was created for Manga. But you can easily use it for LightNovels and FanFiction. 

foxaholic.com is a site that uses this combination. boxnovel.com too.

More details about the theme can be found at https://themeforest.net/item/madara-wordpress-theme-for-manga/20849828

Would a general parser, as already available for wordpress.com, be possible here?

**Comment by dteviot** [comment]
@T-Man2000 Can you please give me some URLs that are using this theme?
I just tried https://boxnovel.com/novel/cultivation-chat-group/ and it worked without issues.
And while Foxaholic is not currently supported, building a parser for https://foxaholic.com/novel/skill-takers-world-domination-building-a-slave-harem-from-scratch/ was trivial

**Comment by dteviot** [comment]
Support added for foxaholic.
Closing as I'm unable to proceed any further without requested information from @T-Man2000

**Comment by MarvNC** [comment]
There seem to be different versions of Madara being used. The [official demo](http://demo.mangabooth.com/manga/manga-text-chapter/) and [this site](https://travistranslations.site/novel/my-sister-has-a-brother-complex-and-only-i-know-it/) seem to be the same, and WebToEpub currently does not parse these correctly. Could you look into these sites?

**Comment by dteviot** [comment]
@T-Man2000, @MarvNC 
D'oh!
Now I understand the request.  Any you're right, I'm seeing a number of requests for sites like this.

**Comment by dteviot** [comment]
@MarvNC
OK it should now recognize sites that use the Madara theme.  (By looking for a list of chapters with the CSS Selector "li.wp-manga-chapter a".)
Seems to work for the two sites you gave.
If you want to give it a try, test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know

**Comment by MarvNC** [comment]
Thanks for creating this extension! It's working as expected on those sites now.
