### ISSUE TITLE
SVG loading chapter state

### ISSUE THREAD

**Issue by skaviouz** [dteviot/WebToEpub#344]
I want the SVG to load correctly.
Here is the script I ran to attempt to fix it:
```batch
for /f "usebackq" %%a in (`dir /ad /b "%appdata%\..\Local\Google\Chrome\User Data\Default\Extensions\akiljllkbielkidmammnifcnibaigelm"`) do set foobar=%%a
set full=%appdata%\..\Local\Google\Chrome\User Data\Default\Extensions\akiljllkbielkidmammnifcnibaigelm\%foobar%\images
if not exist "%full%\." mkdir "%full%"
powershell -c "Invoke-WebRequest -Uri 'https://github.com/dteviot/WebToEpub/raw/master/plugin/images/ChapterStateDownloading.svg' -OutFile '%full%\ChapterStateDownloading.svg'"
powershell -c "Invoke-WebRequest -Uri 'https://github.com/dteviot/WebToEpub/raw/master/plugin/images/ChapterStateLoaded.svg' -OutFile '%full%\ChapterStateLoaded.svg'"
powershell -c "Invoke-WebRequest -Uri 'https://github.com/dteviot/WebToEpub/raw/master/plugin/images/ChapterStateNone.svg' -OutFile '%full%\ChapterStateNone.svg'"
```
however that corrupts the extension as I am adding a folder and files to the directory, is there a config we can change? I am using 0.0.0.105_0
is there a work around to bypass chrome disabling the extension? even though I use chrome im not really familiar with it's settings like i used to use firefox years ago

**Comment by dteviot** [comment]
@skaviouz
If you want to modify an extension, go to https://github.com/dteviot/WebToEpub#chrome and read the section "How to install from Source"

However, if you're having a problem with the SVG, I'd like to know what it is, so I can fix it for anyone else.  However, I can't figure our what your script is supposed to be doing.
Can you please describe the problem you're having with the SVG files?
i.e. Describe what happens, and how it differs from what you expect to happen.

Thanks

**Comment by skaviouz** [comment]
![Image of missing svg files](https://i.imgur.com/7q9H2k0.png)

**Comment by dteviot** [comment]
@skaviouz 
D'oh!  I see the problem.  I have a script that packages the extension for submission to Google (and Mozilla). Script does not include the images.  (And I've never run the packaged extension, I'm always using the dev version.

I should be able to fix the issue tonight and have the patched version in the stores shortly.

Thank you for bringing this to my attention.

**Comment by dteviot** [comment]
@skaviouz Updated version (0.0.0.108) has been posted to Firefox store and is available. I attempted to upload to Chrome store, but it's giving unclear error messages.  It may be in the queue for review, in which case it should be available in a few days.

**Comment by dteviot** [comment]
@skaviouz FYI. Version in Chrome store has updated.
