### ISSUE TITLE
[Enhancement request] Filenames not automatically getting (1) when a file with the same name is present

### ISSUE THREAD

**Issue by jeancinq** [dteviot/WebToEpub#345]
I really would like, If at all possible, to have an option to not automatically add (1) (or (2) if (1) already there...) at the end of the filename when a file with the same name is already present. That would make updating an Epub story much less cumbersome.
I don't know if it's relevant, but I use the Firefox plugin version of WebToEpub on Windows 7.
Thanks in advance for any consideration given to this particular issue.

**Comment by dteviot** [comment]
@jeancinq  I'm sorry, but I don't think I can do anything about this.
Adding the number is done automatically by Firefox.
Note, if you can find an alternative to the Download API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download to write the EPUB to disk, I'd happily investigate further.  Note, the chrome.FileSystem isn't usable.  I've already looked at it:
1. Can't control which directories it has access to.
2. It will be removed at some point in the future.
3. Limits on file size.

**Comment by jeancinq** [comment]
Maybe it's possible to do with the download API you indicated: 
The API indicate [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/FilenameConflictAction) that there is an option allowing to decide if the conflict between two filenames is resolved by modifying the name of the new file or by overwriting the old file. Maybe WebToEpub could be configured to allow to use the overwrite option?
Even if it's not possible, thanks for having looked into it.

**Comment by dteviot** [comment]
@jeancinq
Thank you for pointing that out to me.
I can provide an Advanced Option "Overwrite on filename conflict" that defaults to false.
Sadly, Firefox does not implement the "prompt" alternative.

**Comment by dteviot** [comment]
@jeancinq 
The bad news, the conflictAction option does not seem to work as described. Even though I set it to "overwrite", if there's a file with the same name already there, I get a pop-up asking if you want to replace the existing file or not.  i.e. It's doing the "prompt" behavior.  Note, I'm running a desktop version of Firefox.

Incidentally, I'm not very comfortable offering the option to automatically overwrite existing files.  (Well, I guess I'm not, as it's prompting.)
I much prefer writing to a unique filename.  Then you can always delete the old epub and rename the new one once you've confirmed the new epub has everything you want.
For my own curiosity, could you tell me how automatically overwriting would be a significant benefit to you? Are you possibly using Firefox for Android?

Thanks for your time.

**Comment by jeancinq** [comment]
I'm using Firefox on desktop.
My main problem with the current behavior was that it is annoying to have to remove the (1) each time I update an epub, and sometimes I forget, and then have duplicates files for the same story uselessly using space.
A prompt work just as well for me as an automatic overwrite (maybe even better because its less likely to induce mistakes).
it's my pleasure, and thank you.

**Comment by dteviot** [comment]
@jeancinq 
Done.  Version 0.0.0.109 for Firefox is now available from https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/.
As you're the only person who asked for this, and you're using Firefox, I haven't updated the Chrome version.
