### ISSUE TITLE
Improvement: Provide option to toggle "First Chapter" and "Last Chapter" drop downs between sourceURL and title

### ISSUE THREAD

**Issue by nandakishore2009** [dteviot/WebToEpub#346]
https://github.com/dteviot/WebToEpub/blob/d8a4c3e77e8d93a508950e3b8cd3d0f9ee001788/plugin/js/ChapterUrlsUI.js#L237

It is more user friendly to display chapter **Title** instead of chapter **Source URL** in **First Chapter** and **Last Chapter** drop down.

Solution:
```javascript
 select.add(new Option(chapter.title, value));
```

**Comment by dteviot** [comment]
@nandakishore2009 
Actually, it depends on the site, for some sites the title is more useful, for others, the URL.  (There are sites where the titles just have chapter number (with no volume) and the chapters start with 1 for each volume.  So the titles go chapter 1, chapter 2, ... chapter 20, chapter 1, chapter 2..., chapter 20, .... chapter 1, etc.
However, your point is taken.  I should probably provide option to toggle between URLs and titles for the  **First Chapter** and **Last Chapter** drop down.

**Comment by dteviot** [comment]
@nandakishore2009
I've committed change to the **ExperimentalTabBranch**
As you've suggested, the range selections now default to title.
I've also added a check box to allow toggling between showing URL and Title.

Would you like to load form source https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know what you think?

Note, I'm not sure there's a lot of need for the ranges, as you can do the same thing by "shift clicking" a range of check boxes on the list of chapters that appears below the drop down selectors.

**Comment by dteviot** [comment]
@nandakishore2009
Apologies for the late update.  Version in Chrome and Firefox stores has change. Let me know if there are any issues.
