### ISSUE TITLE
Add darkmode theme

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#348]
I know this might be useless since the use case for the plugin is usually very short but I find myself blinded by the blaring white colour page. Best regards

**Comment by dteviot** [comment]
@DicerX  
1. What Operating System are you running on?  e.g Android, Windows, iOS
2. What browser and version are you using?
3. How do you turn on darkmode theme?

**Comment by DicerX** [comment]
1- Windows 10, browser Brave, WebtoEpub plugin.
2- Brave browser latest version as of 05/06/2020.
3- I usually have a darkmode switch plugin in Brave. I use it constantly at night.

Hope this helps out. Thanks for the swift reply and continued development of the plugin. 
Best regards.

**Comment by dteviot** [comment]
@DicerX
Sorry, but I'm not the person that can fix this.
You'll need to raise a bug with whoever makes the darkmode extension.
From what I can tell, the way they work is to inject some CSS into the web pages.
So, I think it's failing to inject the CSS into the HTML the WebToEpub extension uses for it's UI.

**Comment by dteviot** [comment]
@DicerX, Appologies, it looks like I was wrong.  Extension should be able to support Dark Mode by itself.
Refer: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by dteviot** [comment]
@DicerX, 
OK, I've confirmed I can get dark mode to work with the extension.
However, I probably need some decent styling.  Any chance you can assist?

**Comment by DicerX** [comment]
I'm willing to test any beta product, but I'm illiterate when it comes to
coding. Apologies.

**Comment by dteviot** [comment]
@DicerX 
I'll take you up of the offer.
Here's a build which should support dark mode
https://drive.google.com/file/d/1EPf5WbhCVe70Lsbd9W1Zw2NFZ5JhAwvo/view?usp=sharing
Here's how to install it on chrome https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/
Note, you can skip the .crx to .zip step, I've already done that.
Also, I'm not sure the steps work for Brave.

**Comment by DicerX** [comment]
All good, I ditched brave for chromium Edge. If all fails will try on
Chrome.
Regards.

**Comment by DicerX** [comment]
Alight, so far the extension is functioning, but I just whipped up
photoshop and "borrowed" Microsoft's edge settings design to make a draft
of my idea of Web-to-epub modern design. Hope it can be adopted because as
of now I am addicted to reading wuxia, and your extension is the only way
to make decent epubs. Hope you like it, best regards.

**Comment by dteviot** [comment]
@DicerX 
> Alight, so far the extension is functioning,

Thank you.

>make a draft of my idea of Web-to-epub modern design

I don't see it.

**Comment by DicerX** [comment]
That's weird; it's attached to the email. Here's a link that I just made:

This is zoomed out to show the scroll bar modernised:

https://imgur.com/8UGCA6W

This is the zoomed-in draft, and how I would expect to use it:

https://imgur.com/MuRDCS3

**Comment by dteviot** [comment]
@DicerX 
FYI, I think you need to go to the incident on GitHub and add the images there.  That said, I can follow the hyperlinks

**Comment by DicerX** [comment]
Yup, I thought we were communicatibg via email mb.

**Comment by dteviot** [comment]
@DicerX
If you like to email me directly, it's dteviot@gmail.com
We cam discuss wuxia there, I've started reading "Cultivation Chat Group" (This probably isn't the right place to discuss further)

**Comment by DicerX** [comment]
All good. The novel has a great start but gets stale midway that I dropped
it like a rock. That's aside, what are your thoughts on the modern design?
Would love to see it on Webtoepub

**Comment by dteviot** [comment]
@DicerX
>  what are your thoughts on the modern design?

I'll see what I can do.  No promises, I'm not a graphic designer.  I'm thinking, if I can set the background and outline color for the text boxes, I might be 80 - 90% of the way there.

**Comment by DicerX** [comment]
Alright, I can't wait to see it. Would like to give you my appreciation for
the work you put into this mate. Thank you for indulging me by listening to
my requests.

**Comment by dteviot** [comment]
@DicerX 
Updated test version https://drive.google.com/file/d/13jSUe1OoRHrn-9HCJ7R5v9wEE8pLdcBG/view?usp=sharing
![DarkModeScreenShot](https://user-images.githubusercontent.com/5157081/93070349-daa47f00-f6d2-11ea-8e2f-a808bef043c5.png)

At this point, you could try tweaking yourself.  Basically, change the bits here
https://github.com/dteviot/WebToEpub/blob/bae89feafde5b201b685715971a0aa97cc9838a7/plugin/popup.html#L53-L59

**Comment by DicerX** [comment]
After I played around a bit and I noticed that the following go much better
than crisp black colours.

>   @media (prefers-color-scheme: dark) {
            body {
                background: #333333;
                color: #eee;
            }

            input, button, select, progress, textarea {
                background: #2b2b2b;
                color: #eee;
            }
        }

And I highly recommend using Roboto font instead of any other. Finally, I
always found it weird that the content of webtoepub are left-aligned
instead of centered.

I am currently testing the extension by opening the popup.html and editing
the style sheet with note++.

**Comment by DicerX** [comment]
Realised I am an idiot because I can just test the extension by replacing the popup.html in the zip and import it to Edge... So far so good. The only thing that is odd the borders of the cells are, they've some sort of depression which makes it merge with the background. The modern version [I imagine it to be like this](https://imgur.com/a/slaW9Xc) where the border is fully shown and the edges are rounded. The same ought to be applied to the buttons.

**Comment by dteviot** [comment]
@AlenToma
Works nicely on Firefox.  Thank you very much.
You probably didn't notice, but I'm also trying to add dark mode support. https://github.com/dteviot/WebToEpub/issues/348
And I have to tell you, that styling looks awesome in dark mode.

Unfortunately, when the browser window (Firefox or Chrome) isn't full screen, important parts of the screen are cut off (see screenshot below)
Which makes me a bit concerned how it will work on Mobile Devices.
Although they are kind of moot at the moment.  Mozilla no longer allows WebToEpub to run on Firefox for Android.  (Actually, they've blocked nearly all extensions.)

Anyway, if you can tell me how to fix the clipping, I'll accept with thanks.
I've just started putting a commit together with your changes, and dark mode, and changes to build script to include the new css file, and credits.
![image](https://user-images.githubusercontent.com/5157081/93453152-6a456a00-f92d-11ea-8881-ba5ebdc2bd47.png)

**Comment by dteviot** [comment]
@DicerX
If you're OK with the new look, please close this issue.  Otherwise, let me know what needs fixing

**Comment by DicerX** [comment]
It's great, thought you can close it from your side. Will do so now.
Regards

**Comment by dteviot** [comment]
>you can close it from your side.

I'm aware of that.
But you raised the problem.  If you're not happy with it, I should not be closing it.
FYI. If you don't want to wait for latest version (with ChapterURLs column hidden) to be available in Chrome store,,
I've created a shared Google Drive folder and put fixed builds for Chrome and Firefox there. https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing
