### ISSUE TITLE
please add support for wuxia.blog

### ISSUE THREAD

**Issue by darkharrycracker** [dteviot/WebToEpub#349]
with novelplanet gone im trying to find other good websites to get my novel and i think wuxia.blog is a nice one.
Please also add:
bestlightnovel.com

**Comment by dteviot** [comment]
@darkharrycracker Updated version (0.0.0.110) with support for both wuxia.blog and betlightnovel.com has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.

Please let me know how it works for you.
