### ISSUE TITLE
CSS selector error; Multi-page ToC; Allow following links; Allow extracting from embedded text

### ISSUE THREAD

**Issue by buthub** [dteviot/WebToEpub#350]
Hi, thank you dteviot and everyone for their great work on this project. Not really issues, but suggestions. Sorry if I put this in the wrong place.

1. I can't figure out how to select a div class where the input includes a space. Quotations didn't do it. The help page could use more depth. 
EDIT: After googling around and testing, I guess it's done this way: for 'div class="text here"', it becomes div[class="text here"], and if it's ID instead of class, it's div[ID="text here"], etc.
Please add stuff like this to the help page. Thanks.

2. Can you add a way to include a Table of Contents that spans multiple pages/frames?

3. Allow a way for the manual parser to find the URL (after we tell is where to look; e.g. with the href text of "Direct link") & extract the chapter from that page (where the real content is) following the link in the ToC? 
for example,
ToC -> Fake Chapter Page -> Real Chapter Page.
This is not for novelupdates.com but elsewhere, as shown in #4 below.

4. Similarly, allow a way for the manual parser to extract text that's been embedded where the content is hosted elsewhere. e.g.
https://bluesilvertranslations.wordpress.com/chapter-list/
https://bluesilvertranslations.wordpress.com/2015/01/19/000-prologue-tang-third-young-master-crossing-over-v2/
https://docs.google.com/document/d/1ufS451Nukyw7fgCKaGxntZ4mBCBIMvvGqrgU12vxNak/pub?embedded=true

5. Small thing. Can you make an option to have W2E remove the word "Chapter " from the chapter titles? My kindle displays the chapter title when I touch to navigate, but the word "Chapter " itself takes up like a quarter of what's shown. It's just to allow us to see more of the actual chapter title.

Could you add compatibility for www.novels.pl? It includes multi-page ToCs unfortunately. The CSS selector seems to be
div[class="panel-body article"]
if that helps.

Any chance in hell of updating addon on Firefox 52.9?

Thanks again.

**Comment by dteviot** [comment]
@buthub
> 1. I can't figure out how to select a div class

It looks like you've figured it out.  
That page is in the Git repository https://github.com/dteviot/dteviot.github.io
You're most welcome to submit a pull request with your suggested changes.

> 2. Can you add a way to include a Table of Contents that spans multiple pages/frames?

Unfortunately, this is not easy to do.
First, you need a way to say how to find the URLs of all the pages that have part of the ToC  (In most cases, this requires writing javascript code, as the full set of URLs is not on the page. You need to calculate the pages using the avaiable data.)
Then, you need to specify how to extract the Chapter URLs from each of the pages.
Basically, to do this, the level of complexity is so high, I can't see any way to provide a UI to do this for someone who doesn't know how to program.
So, this boils down to a "Need to write a new parser" problem.

> 3. Allow a way for the manual parser to find the URL (after we tell is where to look;

I think I understand.  This is the case where the link in the ToC takes you to a page that announces the chapter, but you need to follow a link to the actual page.  I suppose this might work in some cases by adding an additional selector to say how to find the real chapter. I'm not sure how to make it clear to users what it's for. Suggestions would be appreciated. 

> 4. Similarly, allow a way for the manual parser to extract text

That's starting to get difficult.  To be honest, I have not yet figured out how to extract text from Google docs.

> 5. Small thing. Can you make an option to have W2E remove the word "Chapter"

That's the sort of feature that I think only a few people would want, others not want, and adding it complicates the W2E UI.  (It's something else for people to try and figure out.)
So, for something like that, my preference would be to use a different tool to modify the epub after capturing it with W2E.
Fortunately, I've received similar requests in the past, hence one of my other projects: https://github.com/dteviot/EpubEditor. 
I think it would be pretty easy to  add an option to strip the word "Chapter" from each chapter's header.

If you don't think you can do it yourself, please raise an issue on that project.

> Could you add compatibility for www.novels.pl? 

I'll look into it.  If you create a new issue for this, it will be easier for you and me to track progress.

> Any chance in hell of updating addon on Firefox 52.9?

I'm sorry, that's not feasible.  W2E uses javascript features that are only available in 63 and above.

**Comment by dteviot** [comment]
@buthub 
Small correction to your point one.  When a class has a space in it.  e.g. Something like
>div class="text here"

This means that the div has two class values "text" and "here".  The way to handle this in a CSS Selector is
> div.text.here
  i.e. a div that belongs to the "text" and "here" classes.  Note, in many cases, you'll only need to use one of the classes, and not both to identify the wanted element.

**Comment by dteviot** [comment]
@buthub 

> Small thing. Can you make an option to have W2E remove the word "Chapter"

https://github.com/dteviot/EpubEditor has been updated to do this.  After following the instructions to set it up, drop the epub in the requested place, then ciick the "Run script above to modify Epub" button that appears.

> Could you add compatibility for www.novels.pl?

Done.

**Comment by dteviot** [comment]
Closing, due to no response from @buthub
