### ISSUE TITLE
Chapters being parsed actually being less than the actual number of chapters 

### ISSUE THREAD

**Issue by itsyahma** [dteviot/WebToEpub#352]
The number of chapters shown in mtlnovel is less than the actual number of chapters in this Novel, I think because the table of contents of the site only shows some of the chapters, can you fix this ? Check for yourself https://www.mtlnovel.com/spare-tire-major-league/

**Comment by dteviot** [comment]
@itsyahma
Seems to be fine for the link you give.
All the chapters seem to be there.  Site claims there's 2555 chapters. (on link you refer to.)
WebToEpub claims it found 2555 chapters.  (It's above the "Select All", "Unselect All" buttons.)
Note, Chapters don't all follow expected numbering.  e.g. There's extra between 52 and 53, and 96 and 97

**Comment by itsyahma** [comment]
It looks like this, I don't know because I'm using a phone

**Comment by itsyahma** [comment]
Yeah it's because it's I'm using phone thnx

**Comment by dteviot** [comment]
@itsyahma
Apologies, I've been distracted and forgot about this.  I'd also forgotten you're using Firefox mobile.
Could you please explain what you mean by "It looks like this", as I don't see any sort of screenshot.

**Comment by itsyahma** [comment]
![Uploading Screenshot_20200703-130200.png…]()

**Comment by itsyahma** [comment]
It's fixed now, I think it's because Firefox updated or something

**Comment by dteviot** [comment]
>It's fixed now, I think it's because Firefox updated or something

Thanks for letting me know.
