### ISSUE TITLE
Website request: systemtranslation.com

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#353]
https://systemtranslation.com/
Please

**Comment by dteviot** [comment]
@sigmatc
I've added a parser for systemtranslation.com.  I'll probably update the version in Chrome and Firefox stores this weekend, as there may be some additional bug fixes I need to do elsewhere.  If you don't want to wait, you can follow the "How to install from Source" instructions for the ExperimentalTabMode branch at https://github.com/dteviot/WebToEpub

**Comment by dteviot** [comment]
@sigmatc version (0.0.0.112) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.
