### ISSUE TITLE
Website Request: chrysanthemumgarden.com

### ISSUE THREAD

**Issue by JasCU100** [dteviot/WebToEpub#354]
Can you please have support for [this](https://chrysanthemumgarden.com/) website? Thank you!

**Comment by dteviot** [comment]
@JasCU100 
It already seems to work, at least for Chrome on the desktop.  I browsed to https://chrysanthemumgarden.com/novel-tl/ff/, opened WebToEpub and was able to build an epub with all 112 chapters.

You'll need to tell me what problem you're having for me to be able to help you any further.

**Comment by JasCU100** [comment]
Oh because I think they have protections in place...some words are replaced with gibberish when I use the plugin. :)

**Comment by dteviot** [comment]
@JasCU100 
Please give me a URL that has the problem, (or story and chapter) and tell me exactly what gibberish you're seeing.  
Sorry, but I don't have time to go searching.

**Comment by JasCU100** [comment]
Every chapter that I download has a sign "we're sorry MTLers..." and some words are turned to gibberish like this (Tfa atfgf kjr rbwfatlcu atja Hl Tecgeb mbeiv cba kgjq tlr wlcv jgbecv. “Qts vlv kf rcfjx bea?” Lf xfqa tlr nblmf ibk. “Po atf qglcmf frajaf kjcafv qfbqif, kbeivc’a la ajxf pera j kbgv obg atfgf ab yf mgbkvr bo qfbqif ja atf vbbg, agslcu ab rtbk boo atflg qgbvema?” ) like in this [chapter](https://chrysanthemumgarden.com/novel-tl/fpyq/fpyq-19/).

**Comment by dteviot** [comment]
@JasCU100 
OK, pretty sure it's another case of https://github.com/dteviot/WebToEpub/issues/89
i.e. the “protection” appears to be a simple substitution cypher probably using a custom font.
e.g In the font, the codepoint for 'T' produces the glyph 'Y', 'f' gives 'e', etc.

As discussed in the thread, if I decode this in WebToEpub, the extension will be removed from the Chrome and Firefox stores.
What I can do, if you can provide me with the transform alphabet string (see 3rd post on the above issue), I can provide you with tool to fix an epub once you've created it.

**Comment by JasCU100** [comment]
Ok thank you! I'll try to decode it!

**Comment by dteviot** [comment]
@JasCU100
Actually, hold off on providing the transform alphabet.  I've had an idea for how I can get the browser to do it for me.
I'll let you know how it goes.

**Comment by JasCU100** [comment]
> @JasCU100
> Actually, hold off on providing the transform alphabet. I've had an idea for how I can get the browser to do it for me.
> I'll let you know how it goes.

Thank you!

**Comment by dteviot** [comment]
Note to self, was able to get browser to give me transform alphabet.  Steps
1. Open a chapter from the site.
2. Open Developer tools
3. Open "Elements" tab and find element with encrypted text (in this case has style of "jum")
4. Replace text in element with "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".  Can do this by right clicking on element in "Elements" tab and select "Edit Text" from drop down.
5. HTML view will now show the transform alphabet.

@JasCU100
I've added an option to https://github.com/dteviot/EpubEditor to clean up Epubs from chrysanthemumgarden.com
Go there and follow the instructions.  If you have any problems, please email me at dteviot@gmail.com

**Comment by JasCU100** [comment]
> Note to self, was able to get browser to give me transform alphabet. Steps
> 
> 1. Open a chapter from the site.
> 2. Open Developer tools
> 3. Open "Elements" tab and find element with encrypted text (in this case has style of "jum")
> 4. Replace text in element with "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".  Can do this by right clicking on element in "Elements" tab and select "Edit Text" from drop down.
> 5. HTML view will now show the transform alphabet.
> 
> @JasCU100
> I've added an option to https://github.com/dteviot/EpubEditor to clean up Epubs from chrysanthemumgarden.com
> Go there and follow the instructions. If you have any problems, please email me at [dteviot@gmail.com](mailto:dteviot@gmail.com)

Thank you very much!
