### ISSUE TITLE
Website request: www.moonquill.com

### ISSUE THREAD

**Issue by defendurname** [dteviot/WebToEpub#355]
Hello, I tried to use this plugin on chrome but it seems to only download the 1st chapter of text with some broken html code as well. Any chance the plugin could be updated to work on this website? For reference this is what I was trying to download:

https://www.moonquill.com/book/reaper-of-the-martial-world

Many thanks for all your work!

**Comment by dteviot** [comment]
@defendurname
ated version (0.0.0.112) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.
