### ISSUE TITLE
Compatibility with oder firefox / waterfox classic

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#357]
I noticed that this addon no longer updates on older firefox / waterfox classic / ...

I use both modern and older browser (well, more the older ones) and didn't notice till now, but the last version is 0.0.0.65!

Would it be possible to keep those browser supported? Is the addons using really specific code that won't work with them?

I think a lot of ppl are still on older browsers, mostly for addons that were killed by the WE migration, so it could be useful.

Not high priority, since it still works fine with the sites I use, but it would be nice. Thanks.

**Comment by dteviot** [comment]
@typhoon71 
>Would it be possible to keep those browser supported? Is the addons using really specific code that won't work with them?

Yes, the add on is using features not supported by the older browsers.
Looking at the commits, between version .65 and .66, the required minimum version of firefox changed from 52 to 57.
That said, I'm not sure what features I used that required 57. 

In theory WebToEpub could probably be re-written to work with older browsers but it would be a lot of work.  And I just don't have the time available.

That said, I would not object if someone wanted to fork the code at the .65 version and maintain going forward.
