### ISSUE TITLE
Req Support - https://vipnovel.com/vipnovel/kung-fu-beyond-the-world/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#358]
https://vipnovel.com/vipnovel/kung-fu-beyond-the-world/  not able to download from this site please help.

**Comment by dteviot** [comment]
#Finks82
Updated version (0.0.0.113) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.
