### ISSUE TITLE
Make UI look nice

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#36]
The popup on firefox looks a little goofy compared to chrome. Suggest styling it a bit with some css hacks if need be.

**Comment by dteviot** [comment]
Sounds reasonable, but firefox isn't priority at moment.  First get all features working on Chrome, then get Firefox port looking nice.

**Comment by belldandu** [comment]
#29

**Comment by dteviot** [comment]
@belldandu
Given that extension now opens (by default) as a full tab in Firefox, is this still relevant?
If it is still relevant, exactly what bits look "goofy" and how do you recommend fixing them?

**Comment by belldandu** [comment]
Actually Since it open in a full tab by default, we could (should really but) give it a more modern look (something like googles material design see https://material.io/ ) using html5 and css.

**Comment by dteviot** [comment]
If someone wants to work on making the UI look nicer, they're welcome to try.
However, I lack the necessary skills for this.

**Comment by dteviot** [comment]
Going to claim this was done by https://github.com/dteviot/WebToEpub/issues/383
