### ISSUE TITLE
novelupdates.com support as table of contents

### ISSUE THREAD

**Issue by Pokemod97** [dteviot/WebToEpub#361]
Allow WebToEpub to use novelupdates as a table of contents. There are several sites where WebToEpub doesn't work because the table of contents is incomplete or a malformed(toc links to post that links to the real content) or where WebToEpub can't find the table of contents even though it's on the page. This might require https://github.com/dteviot/WebToEpub/issues/251 to work or might make https://github.com/dteviot/WebToEpub/issues/251 easier for users of novelupdates.

**Comment by dteviot** [comment]
@Pokemod97 
I've previously asked NU for permission to do this and have been given a very definitive "no".

**Comment by codelif** [comment]
> @Pokemod97 I've previously asked NU for permission to do this and have been given a very definitive "no".

That kinda sucks, especially when most of the information there is provided by volunteers.

But I can understand their concerns. Like spam.
