### ISSUE TITLE
Flying-Lines help

### ISSUE THREAD

**Issue by shonetypto** [dteviot/WebToEpub#362]
I'm having a bit of an issue with the flying-line website. The ext doesn't recognize which parser to use and so I've been trying to create one, however it doesn't catch anything and gives me a "fetching" error code. While expecting elements on the page I can read and copy the css of the chapter but I don't see the same codes in "view source." Playing around with enabling and disabling javascript, the entire page blanks out once disabled, which may be the issue with retrieving the chapter contents. I just don't know how to make the ext select the element I see while inspecting the page vs the page source. 

This is novel I am attempting to archive: https://www.flying-lines.com/novel/i-just-want-to-be-in-a-relationship

Any and all help would be greatly appreciated. And thank you for all your hard work on the extension!

**Comment by dteviot** [comment]
@shonetypto 

**Short answer:**
Go to site that has story where WebToEpub works.  Try this link: https://www.readlightnovel.cc/I-Just-Want-to-Be-in-a-Relationship/

**Long answer:**
> The ext doesn't recognize which parser to use

That's odd. WebToEpub has a parser for Flying-Lines. https://github.com/dteviot/WebToEpub/blob/master/plugin/js/parsers/FlyingLinesParser.js

However, it looks like the site has changed breaking the parser.
Also, it looks like the content for each chapter is now being sent encrypted.  So, it's not so simple to extract the chapter text.
For my notes: 
Looks like if chapter URL is 
https://www.flying-lines.com/chapter/i-just-want-to-be-in-a-relationship/c-7-im-gonna-call-you-tonight-1

Then the content is returned in the JSON response to a POST call like:
https://www.flying-lines.com/h5/novel/i-just-want-to-be-in-a-relationship/7?accessToken=&isFirstEnter=1&sign=06d1cb599d4ece3a9b643c239b9fe406&webdriver=0&time=1596527713088

(specifically, the data.content element of the JSON)

Cracking the encryption is probably too much work.  Simpler solution is probably to open each chapter in a tab (e.g. https://github.com/dteviot/WebToEpub/blob/8ec91b1e401e1267ed6efb0cecfffd0dd9b43666/plugin/js/parsers/MangaHereParser.js#L43-L45),  and then inject a content script (https://developer.chrome.com/extensions/content_scripts) into the tab to retrieve the decrypted text. 

For your purposes, probably easier just to go do different site with story where WebToEpub works.

**Comment by shonetypto** [comment]
Thank you! I'll try both so I can archive the novel and so I can play around with scripts a bit more!
