### ISSUE TITLE
Website request: jpmtl.com

### ISSUE THREAD

**Issue by wintersnew** [dteviot/WebToEpub#365]
Can you please have support for this website (jpmtl.com) Thank you!
its currently showing me this:
![image](https://user-images.githubusercontent.com/38267997/90096178-2dea8100-dd65-11ea-8ba9-4481886388d0.png)

**Comment by dteviot** [comment]
@wintersnew
Updated version (0.0.0.116) has been submitted to Firefox store and is available.
I'm currently unable to submit updated version to Chrome store at moment as previous version is still being reviewed.  I'll update the Chrome store as soon as I can.
