### ISSUE TITLE
Website Update: m.wuxiaworld.co

### ISSUE THREAD

**Issue by AlucardDaske** [dteviot/WebToEpub#366]
Hello,
the Website m.wuxiaworld.co got an update and now WebToEpub doesnt work anymore on that site.
Would be greate if you could update it to work with wuxiaworld again.

**Comment by dteviot** [comment]
@AlucardDaske  Thank you for bringing this to my attention.
Updated version (0.0.0.116) has been submitted to Firefox store and is available.
I'm currently unable to submit updated version to Chrome store at moment as previous version is still being reviewed.
