### ISSUE TITLE
Support added for Foxteller

### ISSUE THREAD

**Issue by guinimesa** [dteviot/WebToEpub#368]
Hi dteviot.
Can you add support to www.foxteller.com?
Thanks in advance.
Have a nice day!

**Comment by dteviot** [comment]
@guinimesa 
Sorry, no, not at the current time..
They're doing something to prevent the story text being exposed that I haven't figured out.
Not helped by my ad-blocker disabling much of the stie from loading.
I'd probably have to to something like https://github.com/dteviot/WebToEpub/issues/362 and at the moment I don't have time to work on that.

**Comment by dteviot** [comment]
Note to self if/when I come back to this.
Looks like text is being returned in response to POST call to https://www.foxteller.com/aux_dem
with a payload like
```json
{
    "x1":"247",
    "x2":"10041"
}
```
Where x1 is the story ID, and x2 is the chapter ID

These values can be found in the second to last script element in each chapter's html.
The response is encrypted.  
I hypothesize the function "aux" found in chapter.js makes the POST call and decrypts the response.

This looks like the part of the function that does the response.  (t) is the response.
```javascript
function(t) {
    var n;
    e(".chapter-content").html((n = (n = (n = (n = (n = (n = (n = t.data.aux).replace(/%Ra&/g, "A")).replace(/%Rc&/g, "B")).replace(/%Rb&/g, "C")).replace(/%Rd&/g, "D")).replace(/%Rf&/g, "E")).replace(/%Re&/g, "F"),
    decodeURIComponent(Array.prototype.map.call(atob(n), function(e) {
        return "%" + ("00" + e.charCodeAt(0).toString(16)).slice(-2)
    }).join(""))))
}
```

**Comment by dteviot** [comment]
Additional,
I have proved that decryption code is correct.
However getting the text to decrypt is more difficult.  Looks like POST requires specific "origin" or "referrer" headers, both of which are difficult to manipulate in chrome.  Requires use of WebRequest API.
Probably easier to use alternate method mentioned in https://github.com/dteviot/WebToEpub/issues/362

**Comment by guinimesa** [comment]
Thanks for the work, looks quite complicated however the #362 workaround should work.
Also if you use Chrome you can try the ScriptSafe addon, it stops all scripts from working but you can detect them and allow them, it may help you to indentify which one does what.

**Comment by AlenToma** [comment]
@dteviot Im trying to get the chapter content.

Im not understanding the way #362 work. 

but i looked at fiddler and could see the data gets from  https://www.foxteller.com/aux_dem
and this i could work with, but i cant see where the values x1 and x2 get set. 

Did you look this upp?

**Comment by AlenToma** [comment]
Ok @dteviot 

I was able to create the parser with this, but i hade to use jquery because im not really good with httpPost using only javascript.
you may be able to use js instead any way here is how i did it.

https://github.com/AlenToma/WebToEpub/blob/master/plugin/js/parsers/FoxtellerParser.js


look at code below 

`csharp
    findContent(dom) {
        var novRegex = /.*?novel_id'\s?:\s?'([\w\s]+)'/i
        var chapRegex = /.*?chapter_id'\s?:\s?'([\w\s]+)'/i

        var x1 = undefined;
        var x2 = undefined;
        var html = dom.head.innerText;
        x1 = html.match(novRegex)[1]
        x2 = html.match(chapRegex)[1]
        var result = undefined;
        $.ajax({
            method: "POST",
            url: "https://www.foxteller.com/aux_dem",
            data: { x1: x1, x2: x2 },
            async: false
        })
            .done(function (msg) {
                result =document.createElement("div")
                result.innerHTML = FoxtellerParser.decrypt(msg.aux);
            }).fail(function (e) {
                console.log(e);

            });
        return result;
    };`

**Comment by dteviot** [comment]
@AlenToma
Thank you very much for that.  Now I see what I was doing wrong.
Specifically, when post JSON, need to add the appropriate Content-Type headers.  D'oh!
Anyway, now working Foxteller parser committed to ExperimentalTab branch.

You might like to look at the commit.
A couple of points, in case you write another parser:
1. Please don't assign to innerHTML, it upsets the Mozilla and Chrome malware checking when I submit the extension to the Stores.
2. override fetchChapter() to make the HTTP calls, not findContent().  findContent() is called multiple times for each chapter, and returns the content element in the supplied DOM.  fetchChapter() is called once for each chapter.  Naming convention is functions starting with "fetch" make HTTP calls.
3. There are utility functions Parser.findConstrutedContent() and Parser.makeEmptyDocForContent()

**Comment by AlenToma** [comment]
where can i find the ExperimentalTab branch?

**Comment by dteviot** [comment]
@guinimesa
Updated version (0.0.0.120) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.
