### ISSUE TITLE
Request For Sites

### ISSUE THREAD

**Issue by NightHawk007** [dteviot/WebToEpub#369]
Hi I have using WebtoEpub for a long time thank you Creating it.
I was hoping if you could please add these sites
- [x] https://wuxiaworld.live/
- [x] https://www.wuxiaworld.co/ (This was available earlier but stopped working after they updated the site)
- [x] https://wuxia-world.online/
- [x] https://pery.info/
- [x] https://novelupdates.online/

**Comment by dteviot** [comment]
@NightHawk007 
In future, please submit each site as a separate incident.  It makes tracking easier for me.
That said

> https://www.wuxiaworld.co/ 

Has already been reported as a problem.  A fixed version 0.0.0.1555 of WebToEpub was posted to the Chrome store, but only finished review this morning.  Your version should update within 24 hours.

> https://wuxiaworld.live/
> https://wuxia-world.online/

These appear to be alternate names for wuxiaworld.online, which is supported, but I will add their aliases to WebToEpub.
However, this won't be availabe until the next WebToEpub update, probably early next week.
If you'd like it sooner, you could go to https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode and follow the instructions for "Install from Source" from the current development branch. (Do NOT use the master branch, that tracks the latest version available from the store.) Please let me know if you have any issues.

> https://pery.info/

Seems to be same layout as listnovel.com, so trivial to add.

> novelupdates.online

Is a bit of a problem.  It only gives 10 chapters at a time in the table of contents.

**Comment by dteviot** [comment]
@NightHawk007
Updated version (0.0.0.118) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.
