### ISSUE TITLE
Check baka-tsuki pages for a specific tag or other

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#37]
I think it would be a good idea to check for some tag that's always on the volume pages and if that tag doesn't exist then throw a message at the user saying "Hey this is not a book page" instead of throwing meaningless errors about hrefs and stuff being missing (because its obvious they are missing since the parent element is nowhere on the page).

**Comment by dteviot** [comment]
Agreed, problem is figuring out if such a tag exists.

**Comment by dteviot** [comment]
So, how to recognise page that's not a story?
My working hypothesis is a "series" page will have the following sections.
- Story Synopsis
- Translation  (nope, not always there)
- Updates
- Project Staff
- Series Overview

These looks like they're id-able (excuse pun) by having a &lt;style&gt; element with an id (in English) of 
- Story_Synopsis
- Translation
- Updates
- Project_Staff
- Series_Overview

I'm thinking Series_Overview is probably the best one to take.
However, if page isn't English, tag isn't English.  e.g. it's "Privire de ansamblu" in Romanian

**Comment by AzSiAz** [comment]
Why no just check if 
```html
<h1 id="firstHeading" class="firstHeading" lang="en">
<span dir="auto">Leviathan:Volume 1</span>
</h1>
```
Since firstHeading is here every time why not check if string contains Volume or even chapter ?

**Comment by AzSiAz** [comment]
Why no just check if
```html
<h1 id="firstHeading" class="firstHeading" lang="en">
<span dir="auto">Leviathan:Volume 1</span>
</h1>
```
Since firstHeading is here every time why not check if string contains Volume or even chapter ?

**Comment by dteviot** [comment]
@AzSiAz 

Thanks, I'll look into that some more. One of my first ideas was to look for "Volume" in the name, but there wasn't always one.  That said, I may have been looking in a different place than you were.

**Comment by belldandu** [comment]
Yeah sorry bout that haven't really had time to investigate this into much detail because of the navy stuff.

I'm leaving in 9 hours so this is "technically" on hiatus for me. If anyone wants to provide info that will help with this enhancement during the 6 months i am away please feel free to do so. 

For now i am adding the label "help wanted". Hopefully this will be done before i'm back.

**Comment by dreamer2908** [comment]
One characteristic of volume pages is that they are made by concatenating several chapter pages. It's a customary, or at least I always do that when making volume pages, i.e [OreShura:_Volume_7_Full_Text](https://www.baka-tsuki.org/project/index.php?title=OreShura:_Volume_7_Full_Text).

However, this can be checked only by looking at the raw wikitext, which can be fetched by adding `&action=raw` to the url, i.e [this](https://www.baka-tsuki.org/project/index.php?title=OreShura:_Volume_7_Full_Text&action=raw). 

It usually looks like this `{{:OreShura: Volume 7 Chapter 0}}`. But [other syntaxes exist](https://www.mediawiki.org/wiki/Help:Templates#Usage).

**Comment by dteviot** [comment]
@dreamer2908 
Thanks, I'll look into this some time in the next few days I hope.

**Comment by dteviot** [comment]
@dreamer2908
My apologies, but I’m thinking this incident is no longer relevant.
The main reason for this incident was that previously, when the parser tried to analyse a “volumes” page on Baka-Tsuki, it died with an error message that looked like complete gibberish (to anyone but me.) So, user didn’t realize what they had done wrong (and blamed the parser.)
Thanks to the “nasty little stress test” that dreamer build, the parser no longer has a problem with these pages.

**Comment by belldandu** [comment]
@dteviot side note wayback machine archives don't have `&action=raw` cached

**Comment by dteviot** [comment]
@belldandu
You raised the original issue some time ago, but I'm thinking it's no longer relevant and can be closed.  (See above comment dated 2 Aug)  Do you agree?

Re your &amp;action=raw comment, I don't understand.  It works fine if you DON'T add the &amp;action=raw.  So why would anyone do that?

**Comment by belldandu** [comment]
Yeah closing.

**Comment by dteviot** [comment]
Closing.  See https://github.com/dteviot/WebToEpub/issues/98
