### ISSUE TITLE
Images not downloaded in Highest Resolution

### ISSUE THREAD

**Issue by amit34521** [dteviot/WebToEpub#370]
I was trying to create a epub from the https://graverobbertl.site/
The images from there are not coming with the max resolution. the src data is 
src="https://i0.wp.com/graverobbertl.site/wp-content/uploads/2020/05/001.png?fit=640%2C908&ssl=1"

The images get downloaded corresponding to 640px. Since it is a wordpress based website, is it possible to add a generic wordpress image download fix fox max resolution?

**Comment by dteviot** [comment]
@amit34521
I've attempted to create a fix as suggested above and committed to the ExperimentalTabMode branch.
If you'd like to install from source  using the the "How to install from Source" instructions for the ExperimentalTabMode branch at https://github.com/dteviot/WebToEpub and tell me how it goes, that would be appreciated.

**Comment by amit34521** [comment]
I tried the update and it is working

**Comment by dteviot** [comment]
@amit34521 
Thank you for the response.

**Comment by dteviot** [comment]
@amit34521
Updated version (0.0.0.117) is available from Firefox store.  Has also been submitted to Chrome store and should be available in a few days after it passes review.
Note, I have some concerns that the changes to WebToEpub may mean it fails to get images for some other sites.  (Depending on exactly how they lazy load images.)  If you see any problems, please let me know.
