### ISSUE TITLE
Android compatible

### ISSUE THREAD

**Issue by blacktribulant** [dteviot/WebToEpub#373]
Well I've been using This app alot I rate it 5 star as I very much like it. So it has come to my attention that Firefox updated and because of its update I can't use it as an Android add on I am very well much annoyed .. so as 5 star fan I request that you upgrade this app to be more compatible with Firefox thank you for your excellent work

**Comment by dteviot** [comment]
@blacktribulant 
Can you give me any more details, like which version of Mobile Firefox it doesn't work on?

**Comment by blacktribulant** [comment]
It's the most recent one version 79.0.5

**Comment by blacktribulant** [comment]
It's the most recent one version 79.0.5

**Comment by dteviot** [comment]
@blacktribulant
It's not my doing.  See: https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs?utm_source=leanplum-push-notification&utm_medium=android&utm_campaign=072720-en-fennectofenix-none&utm_content=video#w_items-that-will-be-migrated
Specifically, this bit
>Supported add-ons (note: currently, a limited number of Recommended Extensions are supported. Also, add-ons will be disabled in private mode by default but you can enable them by following these instructions)

The "these instructions" takes you to https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android#w_enable-add-ons-in-private-browsing, which MIGHT help you.  If that doesn't work for you, you'll need to complain to Mozilla.

**Comment by dteviot** [comment]
@blacktribulant
Closing.  Please add a note to this if there's anything else I can do for you, and I'll re-open.
