### ISSUE TITLE
Need Support https://boxnovel.net/warhammer-wizard.novel

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#374]
need support for https://boxnovel.net/warhammer-wizard.novel , no chapter list is showing up for download /o/

**Comment by dteviot** [comment]
Note to self, Looks similar to https://novelupdates.online, but isn't underneath.

**Comment by dteviot** [comment]
@Finks82
Updated version (0.0.0.119) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.
