### ISSUE TITLE
need support or is it just me? https://babelnovel.com/books/all-field-godly-wish-system?tab=Chapters

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#377]
pls help its not working anymore for babelnovel.com https://babelnovel.com/books/all-field-godly-wish-system?tab=Chapters

**Comment by dteviot** [comment]
@Finks82
Site has changed layout again.
Will take some effort to update.  And I've got a large backlog to deal with.
So, don't expect anything soon.

Notes for me.
Looks like chapters can be found in JSON in &lt;script&gt; element with id of "__NEXT_DATA__"
Find member props.pageProgs.methodCacheData.  is string.  Convert to JSON
then look in cache.BookDetailStore-getBookDetail.BookDetailStore-loadChapterGroups

Text for chapter with URL of https://babelnovel.com/books/all-field-godly-wish-system/chapters/c2
Can be found in JSON response to https://babelnovel.com/api/books/all-field-godly-wish-system/chapters/c2/content
Format of JSON looks basically similar to previous.

**Comment by dteviot** [comment]
@Finks82
Updated version (0.0.0.119) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.
