### ISSUE TITLE
Upgrade JSZip library to 3.0.0

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#38]
From Firefox review of plugin.

> Note that old versions of JSZip have known issues which might make extract zip files created with it impossible. Before requesting full review, please upgrade to the latest version.

Also note:
- Update readme to include the version of JSZip library
- Use a Git Submodule to bring in the JSZip library, don't include the minified source.

**Comment by belldandu** [comment]
https://github.com/dteviot/WebToEpub/commit/65df35edfd3f88d9c8ef42d486c553627b10ebd3 Done @dteviot

**Comment by belldandu** [comment]
That and a chrome version bump to 49 in the manifest.json

**Comment by belldandu** [comment]
Changed priority due to this effecting the review status of the firefox plugin.

**Comment by dteviot** [comment]
Thanks.  Note that items https://github.com/dteviot/WebToEpub/issues/50 and https://github.com/dteviot/WebToEpub/issues/49 are going to fail the Firefox review.
I'm working on them currently, but fix may not be easy.

**Comment by dteviot** [comment]
As far as I can tell, once I update the readme this is done.

**Comment by dteviot** [comment]
@belldandu 
And thanks for doing this.

**Comment by belldandu** [comment]
@dteviot No problem :D
