### ISSUE TITLE
Request to Support site:  https://indomtl.com/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#380]
Dear Devs, please add site: _https://indomtl.com/_
Very thankful for your hard work...

**Comment by dteviot** [comment]
@budikesuma
Updated version (0.0.0.119) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.

**Comment by budikesuma** [comment]
Thanks Devs...
