### ISSUE TITLE
Please add support for: https://novelfever.com/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#381]
Dear Devs... Thank you in advance for your quick action to support my indomtl site, if you aren't busy, now I have found a good site to ask you to support it. 
Please add this site: https://novelfever.com/
Thank you very much, Devs

**Comment by dteviot** [comment]
@budikesuma
Have got parser kind of working.  You need to have the list of chapters showing, or WebToEpub can't find them.
You can download a test version from https://drive.google.com/file/d/1fNUkkvkk6gp_A4SXSkQ4lvCN1Yxv4-ic/view?usp=sharing
Here's how to install it on chrome https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/
Skip the .crx to .zip step, I've already done that.
You might also need to uninstall your existing copy of WebToEpub.

Please let me know if this is satisfactory.

**Comment by dteviot** [comment]
@budikesuma
Updated version (0.0.0.120) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.

**Comment by budikesuma** [comment]
Thanks a lot Devs...
