### ISSUE TITLE
Please add support for https://forums.spacebattles.com/

### ISSUE THREAD

**Issue by Snowman1907** [dteviot/WebToEpub#382]
Dear Devs
Please add support for https://forums.spacebattles.com/ and https://forums.sufficientvelocity.com/ if possible please. And thank you greatly for such a wonderful product.

**Comment by dteviot** [comment]
@Snowman1907
 They are already supported.
You just need to go to a page that shows Threadmarks and open WebToEpub.  e.g.
* https://forums.sufficientvelocity.com/threads/hmmph-this-junior-is-a-good-seed-cultivation-management-quest.71541/
* https://forums.spacebattles.com/threads/harry-and-the-shipgirls-goblet-of-feels-a-hp-kancolle-snippet-collection.772633/, then click on "Threadmarks" to open the list
