### ISSUE TITLE
Hide chapters url by default

### ISSUE THREAD

**Issue by AlenToma** [dteviot/WebToEpub#384]
It would be greet if we could hide the chapters Url by default unless the user want to show it,

That way the design dont get to big when the URL are very long

**Comment by AlenToma** [comment]
Ok, I have created button 'Show URLs of Chapters' that will toggle the table URLs. By default those Urls are hidden.

the following update exist in the following files 
1- https://github.com/AlenToma/WebToEpub/blob/master/plugin/popup.html
2- https://github.com/AlenToma/WebToEpub/blob/master/plugin/js/ChapterUrlsUI.js

just copy those files and it should be good to go.

**Comment by dteviot** [comment]
Yes. I've also done it.

**Comment by AlenToma** [comment]
You mean you did before me :)

I though that there was no on Progress tag meant that you did not work on it 👍 

Any way. i tried to take other issues but those seems hard for me right now. 

So if anything i can do will do, should also tell you before hand.

**Comment by dteviot** [comment]
@AlenToma
>I though that there was no on Progress tag meant that you did not work on it 

Sorry about that.  I had 10 minutes spare over my lunchtime and did it then.
I did look at what you did, but I think my implementation is simpler.

Anyway, it you want to take a try at one, I suggest https://github.com/dteviot/WebToEpub/issues/368
You probably want to try solving it by 
In fetchChapter(), open each chapter in a tab, and then injecting a content script (https://developer.chrome.com/extensions/content_scripts) into the tab to retrieve the decrypted text.
You can find examples of opening tabs in ReadComicOnlineParser.js and 
https://github.com/dteviot/WebToEpub/blob/8ec91b1e401e1267ed6efb0cecfffd0dd9b43666/plugin/js/parsers/MangaHereParser.js#L43-L45),
Injecting a content script and listening for the reply can be seen in main.js.
Or you could have a look at another project of mine: https://github.com/dteviot/SyosetuGoogle

**Comment by AlenToma** [comment]
No problem, i will refork the project agen so i get the latest update later.

And will have a look at the issue u provided.

**Comment by AlenToma** [comment]
As the problem is really small so i trust that this should not be a problem anymore even without testing
