### ISSUE TITLE
Way to open Default Parser editor???

### ISSUE THREAD

**Issue by huntermad** [dteviot/WebToEpub#385]
The site I want to download is considered a known site but the parser is wrong or outdated, I just couldn't get the right links.

The problem is the url structure of chapter links is very simple so If i could open default parser and add a single chapter then DONE.

Is there a way to open default parser with a "known" site? I tried to use it on other site to open default parser page but the app simply revert that site not the site i want.

For example, I could use Novelfever site to open default parser and do all the steps for a novel in www.centinni.com/. The app would simply revert to show links in Novelfever when I click on Apply.

**Comment by dteviot** [comment]
@huntermad
Click on "Advanced Options"
On the "Manually Select Parser" dropdown, select "Default"

Alternately, you could write a parser: https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
