### ISSUE TITLE
Toggle theme between always light, always dark and current OS

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#386]
Add Advanced Option "Theme"
Choices are:
* Always Light Mode
* Always Dark Mode
* Use current OS selection
Defaults to "Use current OS selection"
Implement by injecting "DarkMode.css" or "LightMode.css" as required after Default.css

**Comment by AlenToma** [comment]
@dteviot i have removed the switch and cleaned the css file. 
I also add the select under advanced and commited the changes, its up to you now @dteviot 

https://github.com/AlenToma/WebToEpub/blob/master/plugin/popup.html
https://github.com/AlenToma/WebToEpub/blob/master/plugin/css/default.css

**Comment by dteviot** [comment]
@DicerX 
Have implemented option.  Updated zips. 
Also tweaked Dark Mode background to #2f2f2f
If it's all good with you, I will commit changes.

**Comment by AlenToma** [comment]
If you commit to ExperimentalTabMode, i will also test it.

**Comment by dteviot** [comment]
Done.  Calling it a night

**Comment by DicerX** [comment]
Night mate.
