### ISSUE TITLE
Add an extra invalid chapter at the top.

### ISSUE THREAD

**Issue by AlenToma** [dteviot/WebToEpub#387]
The library add an extra invalid chapter at the beginning.

Have a look here
https://m.wuxiaworld.co/The-Second-Coming-of-Gluttony/

The first chapter name is `Chapter 1. Prologue` but you will see that it also add `The Second Coming of Gluttony` with an url `https://m.wuxiaworld.co/The-Second-Coming-of-Gluttony/`

**Comment by dteviot** [comment]
WebToEpub puts a page with the synopsis at the start of the EPUB.
Is that what you're referring to?

**Comment by AlenToma** [comment]
I see but in my case it fail. As it abort and ask me to save the file already. Did u test the link i gave you ?

**Comment by AlenToma** [comment]
I think, that it should try to find the description if it fail then it should continue as the description is not that impotend

**Comment by dteviot** [comment]
Worked fine for me.  Perhaps you have Advanced Option "Add Page with Chapters to Chapters List" turned on?

**Comment by AlenToma** [comment]
Yes i did test manually select parser = default and then selected apply as there was no close button. 

Bu then i diselect it later

Is it already saved somewhere. Where is it saved if i may ask

**Comment by dteviot** [comment]
To local store.  You can dump config to file and load, use "Write Options to File" under Advanced.
Edit file, then "Read Options from file"

**Comment by AlenToma** [comment]
I see you saved it to the coocke :) 

I already removed it and it work now
