### ISSUE TITLE
Wattpad isn't working

### ISSUE THREAD

**Issue by xenychtao** [dteviot/WebToEpub#391]
Good day to you.

For a few days now I have been having several problems trying to convert sites and download them as epub files.
The first thing I have noticed is that the efficiency has noticeably decreased; now it takes almost twice as long to convert a page. And the second thing would be that on many occasions this 404 window has appeared.

I tried it in a random novel and this happened:
![404](https://user-images.githubusercontent.com/72045178/94480242-61b22680-01ac-11eb-9cb3-aba85a477da0.jpg)

What could be the cause?

**Comment by dteviot** [comment]
@xenychtao
My best guess is there have been changes made to the wattpad site, and WebToEpub can't currently handle them.
I'll probably need to make some changes.  
Can you send me a URL to the table of contents of a story with issues?

**Comment by AshenPaladin** [comment]
I have a similar issue on https://isekaicyborg.wordpress.com/
`OK
--
Error: Fetch of URL 'https://isekaicyborg.wordpress.com/isekai-maou-to-shoukan-shoujo-dorei-majutsu/isekai-maou-vol-1-illustrations/' failed with network error 404.     at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:25)     at Function.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:160:45)     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:154:31     at async Promise.all (index 0)
`

**Comment by dteviot** [comment]
@AshenPaladin 
That;s not a bug.
The site has disabled the chapter links for volumes 1 and 2.  If you try to follow them by clicking on them, you'll also get a 404 error.
From the posts by the site's owner, it appears J-Novel club has licensed the books and have instructed him/her to take them down.

**Comment by dteviot** [comment]
My notes on how to get the content for a chapter (untested)

How to get text for chapter.
1. Given URL for a chapter from ToC.  e.g. https://www.wattpad.com/878630872-the-devil%27s-match-chapter-1-lily
2. This will have initial content in element &lt;div class='first-page'&gt;
3. Additional content for chapter, can be found by following URLs like
https://t.wattpad.com/text-223623512-878630872-a5bfd1745-2?subject=gid&expiry=1611556458000&mac=ipMEmSldNGjarvrYXP1Ytf1uKjF4C94Cm1Ae82LMS10%3D

Information on how to construct these "URLs for the chapter's content" is found in &lt;script&gt; element setting variable "window.prefetched"
Relevant section from JSON is
```JSON
{
  "part.878630872.metadata": {
    "data": {
      "pages": 4,
      "wordCount": 3509,
      "text_url": {
        "text": "https://t.wattpad.com/text-223623512-878630872-a5bfd1745?subject=gid&expiry=1611556458000&mac=ipMEmSldNGjarvrYXP1Ytf1uKjF4C94Cm1Ae82LMS10%3D",
        "refresh_token": "https://api.wattpad.com/v4/parts/878630872/token"
      },
    }
  }
}
```

"223623512" is the story ID, 
"878630872" is the Part ID (or chapter ID), 

For additional chapter content, add "-2", "-3", "-4" etc to the pathname part of the URL.
(I hypothesize the "pages" value in the JSON gives number of "pages" with the rest of the chapter's content)

Note that sometimes the call to fetch next content will fail.
In which case, it looks like call the "refresh_token" value.
This will return something like 
```JSON
{"token":"subject=gid&expiry=1611557812000&mac=wi7ETFc5hPE17mS9xkP%2BqIQGUokiW5DPzbjI7gwMQhY%3D"}
```

which should be used as the search part of the URL.

**Comment by dteviot** [comment]
OK, I think I've got it fixed.
At least, it works for https://www.wattpad.com/story/58928-the-wizard-and-the-slayer

Sorry for the delay.
Anyway, updated version (0.0.0.126) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
