### ISSUE TITLE
Request for Questionable Questing

### ISSUE THREAD

**Issue by minshimun** [dteviot/WebToEpub#392]
Tried https://forum.questionablequesting.com/threads/optimistic-game.12817/ but did not work

To get ToC, go to say "https://forum.questionablequesting.com/threads/giving-up-avatar-the-last-airbender.10629/" click on the "Threadmarks" button, select "View all"

**Comment by minshimun** [comment]
Does not work.

**Comment by minshimun** [comment]
> Does not work.

**Comment by minshimun** [comment]
> To get ToC, go to say "https://forum.questionablequesting.com/threads/giving-up-avatar-the-last-airbender.10629/" click on the "Threadmarks" button, select "View all"

Does not work.

**Comment by dteviot** [comment]
@minshimun
Sorry. that was a note for me on how to find the ToC.  I should have labelled it.
Anyway, I had a quick look at it,, it's probably do-able.  But will be a while until I get around to doing it.
I'm currently busy with other things.

**Comment by dteviot** [comment]
Additional note for self.
Site is similar to spacebattles, but notable difference is first chapter does NOT have an anchor in the URL.  However, it's probably the first &lt;article&gt;' on the page.

**Comment by dteviot** [comment]
@minshimun
I think I've got QuestionableQuesting working

As it will be a while before I update versions in stores you might like to install from source.
Firefox and Chrome versions have been uploaded to  https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing

You can use the "Install from Source" instructions at https://github.com/dteviot/WebToEpub.  You can skip the steps about downloading, unpacking and fetching jszip.min.js.  I've already done all that.

Note, for WebToEpub to be able to find the chapters, you need to open the threadmarks before launching WebToEpub.

**Comment by minshimun** [comment]
Thanks imma just wait for the update

**Comment by dteviot** [comment]
@minshimun Updated version 0.0.0.121 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in a few days once it finishes review.
