### ISSUE TITLE
Request: Default the filename to title, filesafe

### ISSUE THREAD

**Issue by cstrife1** [dteviot/WebToEpub#393]
Hi, as per my email. Please default the filename to whatever the title is, but replace non-valid chars with file safe replacements. The default filename is in almost 100% of cases not a good reflection of the book.

Thanks

**Comment by dteviot** [comment]
@cstrife1
The reason for the reduced file name was windows has a limit on maximum path length (including directories) for a file name.
And some of the sites have a long title.  Resulting in a filename that causes problems.
So, name is truncated by default.

I suggest adding an new checkbox in the Advanced settings 
"Use full title as filename"

This is unchecked by default, but if checked, then the filename won't be truncated.
Do you think this will be satisfactory?

**Comment by pkhyber** [comment]
@dteviot There is no such option in advance setting now. It was there previously. Also webtoepub was able to save file with file name but now it just generate random string of names.I am using chrome extension.
I would be immensly thankful if you do that.
![webtoepub](https://user-images.githubusercontent.com/72614862/95593531-740f4880-0a67-11eb-841e-da5947df460d.png)

**Comment by cstrife1** [comment]
> I suggest adding an new checkbox in the Advanced settings
> "Use full title as filename"
> 
> This is unchecked by default, but if checked, then the filename won't be truncated.
> Do you think this will be satisfactory?

Yes, this would be perfect. Thanks.

**Comment by dteviot** [comment]
@pkhyber
I'm somewhat confused by your response, can you please clarify?

>There is no such option in advance setting now. It was there previously. 

What are you referring to?  So far as I can recall, there never was an option for full name in the advanced settings.

>Also webtoepub was able to save file with file name but now it just generate random string of names.I am using chrome extension.

It should not give a random string of names.  It should be truncating the middle of the name.  Please give me an example, listing the title and file name.
Thanks.

**Comment by dteviot** [comment]
@cstrife1 
I've made the change.
As it will be a while before I update the versions in the Chrome and Firefox stores (there are other features/fixes I need to do)
I've posted Chrome and Firefox versions to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing
You can load them using the "Install from source" instructions found at https://github.com/dteviot/WebToEpub#how-to-install-from-source and try it out.

Note, the zip files contain all the files needed. So you can skip most of the steps.
For Chrome, Just do step 2, then go to step 6
For Firefox, Do step 2, then go to step 8

**Comment by dteviot** [comment]
@cstrife1 @pkhyber
Updated version 0.0.0.121 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in a few days once it finishes review.
