### ISSUE TITLE
Sorting of chapters by name or date published in irregular TOC

### ISSUE THREAD

**Issue by pkhyber** [dteviot/WebToEpub#395]
@dteviot 
Would it be possible to sort Chapters Url by Name or date published/modified because in few websites chapter links in TOC is jumbled up for e.g. Odd numbered chapters first(1,3,5,7,....) and then even no. chapters(2,4,6,8 ...)
or TOC links are in batches like
1  6    11
2  7    12
3  8    13
4  9    14
5  10  15
in this case chapters are parsed in order of 1,6,11,2,7,12,3,8,13.....
A sort of chapter based on date published/modified or by name would probably solve the issue
Thanks

**Comment by dteviot** [comment]
Sorting by date would require being able to find the date in the chapter title.  In the general case, this is quite difficult.
Sorting titles by alphabetical order is possible.
Can you give URLs to some TOCs that show this problem?

**Comment by dteviot** [comment]
@pkhyber
A general solution to sorting by chapter number is not easy.
If use alphabetical order, then goes 1, 10, 100, 11, etc.
So need to extract chapter number from title and sort by that.
But chapter number isn't always an integer (might have sub-chapters), or there might be digits in the title as well.

So, I'm not willing to modify WebToEpub to do this.
However, I've tried to patch a different tool I have to do this.
MergeEpubToWeb https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing 

To use.
Steps

1. Download zip and unzip
2. Run executable
3. From "File" menu, select "Open"
4. On "Edit" menu select "Sort Chapters"
5 From "File"menu, select "Save"

You can also manually move chapters by seleccting them, right click "cut", select where you want them then right click "paste".
