### ISSUE TITLE
Add the option to remove the "information" page at the start of every ePub.

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#396]

**Comment by dteviot** [comment]
@DicerX
I've posted updated build for Chrome and Firefox versions to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing
To not create the "Information" page, uncheck "Add Information page to Epub" under Advanced settings.

**Comment by DicerX** [comment]
Terrific just tested it.
