### ISSUE TITLE
Request to support site : https://novelringan.com

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#397]
Dear Devs, please add support: https://novelringan.com/
Very thankful for your hard work...

**Comment by dteviot** [comment]
@budikesuma
Please tell me what the problem is, so far as I can tell, it already works.
I went to https://novelringan.com/series/the-divine-physicians-overbearing-wife/, opened WebToEpub and it fetched the Table of Contents without a problem.
I then created an epub with Chapter 1505, and the chapter contents in the epub seem to match what is seen when I go to the web page

**Comment by budikesuma** [comment]
well, web2epub not only fetches novel chapters, but also fetches all the links contained in the novel's pages, such as: Report Error Link, Genres Links, Etc .. ^^

**Comment by dteviot** [comment]
@budikesuma
> Because this site has many Chapters that are joined together.

Can you tell me which chapters show this?  There's 2800+ chapters, I can't look through them all.

**Comment by budikesuma** [comment]
> 
> 
> @budikesuma
> 
> > Because this site has many Chapters that are joined together.
> 
> Can you tell me which chapters show this? There's 2800+ chapters, I can't look through them all.

Starting from chapters: 3-4, 5-6, 7-8, and so on...

**Comment by dteviot** [comment]
@budikesuma 
> web2epub not only fetches novel chapters, but also fetches all the links contained in the novel's pages, such as: Report Error Link, Genres Links, Etc .. 

Just uncheck them in the list of chapters to fetch.  

> If possible, to add the feature of getting rid of the same chapters (Duplicate chapters) in a future update.

It's difficult to automatically tell if a chapter is a duplicate or not.  I'd suggest manually unchecking them also.
Alternately, you can use a tool like MergeEpubToWeb https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing to remove the chapters you don't want from an Epub.
Steps
1. Download zip and unzip
2. Run executable
3. From "File" menu, select "Open"
4. List will mark chapters that it thinks are out of order.
5. Select the chapters you want removed, right click and select "Delete Item"
6. From "File"menu, select "Save"

**Comment by budikesuma** [comment]
Okay Devs, Thanks ...
