### ISSUE TITLE
Request for sexstories

### ISSUE THREAD

**Issue by MirCton** [dteviot/WebToEpub#398]
Tried to do it myself but
![Screenshot_20201018_100445](https://user-images.githubusercontent.com/73046010/96357195-32e3fc00-112b-11eb-9fa9-1dc96fdd6bd9.jpg)yeah I'm confused. 

https://www.sexstories.com/profile652373/eville_monkey

If someone knows this site and raises an eyebrow yes I'm a degenerate

Edit:same degenerate was the one to request for questionable questing I forgot my password for my Gmail and github account.

**Comment by dteviot** [comment]
@MirCton
Updated version 0.0.0.121 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in a few days once it finishes review.
