### ISSUE TITLE
Please add Support for those Sources

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#399]
Dear Devs, please add support for those following sources:
- [x] https://www.worldnovel.online/
- [x] https://meionovel.id/
- [x] https://indowebnovel.id/
- [x] https://novelgo.id/

thanks in advance.

**Comment by dteviot** [comment]
@budikesuma
In future,, please create an issue for each source.  It makes tracking easier.

**Comment by budikesuma** [comment]
Thanks a lot Devs.

**Comment by dteviot** [comment]
@budikesuma 
Updated version 0.0.0.121 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in a few days once it finishes review.

**Comment by budikesuma** [comment]
Thanks Devs..
