### ISSUE TITLE
[Enhancement] BakaTsuki epub formatting

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#4]
First thing thanks for this extension, for which I'd like to suggest some improvement:

1. Download the hi-res images when available from BakaTsuki ("original image"), not the resized ones, let the epub reader scale it [for better quality].
2. Put one image /page [for cleaner layout and easier printing].
3. Improve formatting; if you compare the now dead BakaTsuki epub Generator output and the output of this plugin you will notice the output is messy. A good example is the "content" table appearing, or the text spacing being messy [for cleaner layout].

I suppose that if the old code could do it should be possible to do it now too.
I hope I don't sound annoying, it's not my intention, I'm asking since the web thing was really handy and had god results quality wise.

**Comment by belldandu** [comment]
Please refer to #3 and #2 for your 1. and do +1 the pull request if you approve. As for 2. and 3.
I will be handleing these in another pull request.

**Comment by typhoon71** [comment]
Good news then, I like how I just have to wait and stuff does itself...
About the "+1": I did it on the first comment, is it OK?

**Comment by belldandu** [comment]
Yep

**Comment by belldandu** [comment]
The new Format will be like this
```
/
	/META-INF
		/container.xml
	/mimetype
	/OEBPS
		/content.opf
		/Images
			/imagename.jpg
		/Styles
			stylesheet.css
		/Text
			ChapterName.xhtml
		/toc.ncx
```

**Comment by dteviot** [comment]
@belldandu
I'm not entirely sure this is what Typhoon is asking for.
I think he's talking about the layout of the "Images" section that appears at the start of the ePUB.

I'll add that I've seen at least three people asking for the images that appear in both the images table and the main body to be removed from the images table.

**Comment by belldandu** [comment]
@dteviot 

Yes i know but the entire file structure needs organizing as well. So i figured i would do that as part of it.

Also because some chapters can have the same names (in the case of some baka-tsuki books)
it will be ```[split_number] ChapterName.xhtml```

**Comment by dteviot** [comment]
> Also because some chapters can have the same names (in the case of some baka-tsuki books)
it will be [split_number]ChapterName.xhtml

I don't understand why you need to do this.
The current code allocates a new unique name to each file it stores in the ePUB, regardless of where it came from.  Perhaps if you gave me an example?

**Comment by belldandu** [comment]
Yes i know your current code does this. However The format is still all over the place. The reason why i am planning to do "OEBPS/Text/[0001]Some Chapter Name.xhtml" instead of "index_split_0001.xhtml" is because its cleaner and less messy. Plus if someone decides they want to manually fix typo's/grammatical mistakes (if they appear especially in the case of baka-tsuki because its translations). Then this format will make it easier to determine where and what to edit.

**Comment by dteviot** [comment]
I have no objections if you want to move to the more common directory
structure for ePUB.
i.e. Put the different types of files in their own "folders".
Appending Chapter name might get a bit ugly.  Some chapters can have long
names and might exceed maximum permitted length for file name.  (Note, I'm
not sure what limits are.)

Side question: would it pay to add comment to XML to indicate original
file's URL?  (May be even more use for images.)

**Comment by belldandu** [comment]
Sure and for the chapter names that get too long we could limit it to like 20 characters?

**Comment by dteviot** [comment]
Works for me.

**Comment by belldandu** [comment]
Figured i would give a status update as to this enhancement.

New format is done.

Images are no longer in lists and gallery text has been removed (because the lists where the reasons the images where not getting there own pages.

I'm still currently working on making it so images are unique (aka images that are elsewhere in the epub will not show up in novel illustrations).

**Comment by typhoon71** [comment]
Just checked v0004, it's getting better. Hi-res images are a treat to the eye. :)
Thanks. 
Later I'll test it against a bunch of old LN and compare with old epubs, to see what may need improvement.

**Comment by belldandu** [comment]
@dteviot i'm actually having trouble determining the best place to do a check for if an image exists on the page (so that i can remove the existing one before placing the new one)

**Comment by dteviot** [comment]
@beldandu
> i'm actually having trouble determining the best place to do a check for if an image exists on the page (so that i can remove the existing one before placing the new one)

I'm not quite sure what you're asking me.
I think it's this.
https://github.com/dteviot/WebToEpub/issues/8

Note, I'm trying to create individual issues. Should make finding requests and tracking their progress easier.

**Comment by belldandu** [comment]
@dteviot Thank you i managed to get it thanks to that. 

So now images are done. Except that when i went to also exclude the cover image i noticed that you don't set isCover to true at any point.

**Comment by belldandu** [comment]
for now i will make the pull request with the current changes.

**Comment by belldandu** [comment]
#10 is complete just waiting to be merged

**Comment by belldandu** [comment]
@typhoon71 your enhancement has been finished. Please close this issue when you get the chance.

**Comment by dteviot** [comment]
@belldandu 

I've made assorted minor changes to your work.  Can be found on https://github.com/dteviot/WebToEpub/tree/PostMerge10Cleanup
If you're happy with them, let me know and I'll merge them into the Sonako branch and send updates to Chrome Store and Mozilla.
Sonako is the release branch at the moment.  Gets merged into master when it's been released for a couple of days with no complaints.

**Comment by typhoon71** [comment]
More like when I'm online...

1st request is indeed perfectly satisfied. Thanks.

2nd request is not yet done, is v 0.0.0.4 the uptodate plugin? This is what I get printing:

![dss](https://cloud.githubusercontent.com/assets/1866248/16355204/fe3c3f86-3aaf-11e6-856c-9f36a0ef44fb.png)

3rd one is partly done: the formatting is generally improved, but the table of content is... messy?
Could be it made optional? (Should I make a new separate request for the ability to make parts of the epub optional? Like optional table of contents, optional images, ...)

**Comment by belldandu** [comment]
@typhoon71 update is not live yet.

@dteviot Looks good but i would have preffered to keep the full relative paths for the footnotes like we do with images just to prevent any funny business.

**Comment by dteviot** [comment]
@typhoon71 version 0.0.0.6 (which has this) has just been submitted to Google and Mozilla.  Chrome should be available in a few hours.  Firefox version should be available now (just not validated.).

> @dteviot Looks good but i would have preferred to keep the full relative paths for the footnotes like we do with images just to prevent any funny business.

I'm not entirely happy with the code either.  I'm thinking it might be better to to use absolute paths like "/OEPB/Text/xxxx" etc.  Means I could get rid of the makeRelative() calls.  But it's sufficient for the time being.  I think we've got more important issues to deal with.

**Comment by belldandu** [comment]
@dteviot Actually i tried to do absolute paths However this creates list index errors within all epub readers. Which is what i meant by funny business.

**Comment by dteviot** [comment]
Hmmm.  Thanks for telling me that.

**Comment by belldandu** [comment]
@dteviot Even if we aren't having issues with it now. I do recommend updating the footnote relative paths to use ../Text/ so that we don't have weird issues with some epub clients in the future.

**Comment by dteviot** [comment]
Will do.

**Comment by belldandu** [comment]
@typhoon71 can you please close this

**Comment by typhoon71** [comment]
oh, right, I forgot to close it.

**Comment by typhoon71** [comment]
I just want to make known that last calibre renders perfectly now (win7 x64 calibre 2.60 x64).
User-side feedback, I'm pretty sure you do test your stuff. ;)
Also, there was a switch for paged mode/flow mode that seems to have stop working (on my side), so even if I tought of being in page mode it was actually in flow mode. Argh!
Upgrading (a clean upgrade since I had no important customization) fixed it.
