### ISSUE TITLE
Update Chromestore WebtoEpub screenshots

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#400]
The screenshots on the chrome store are **ancient**, to say the least, we deserve to get an update.

**Comment by dteviot** [comment]
Updated screenshot sent to Google.  
Hopefully they will approve within a week.

**Comment by dteviot** [comment]
New screenshot is shown in Chrome store.  
https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm?hl=en&authuser=0
Only took 3 days for Google to approve it!
@DicerX Anything else?
