### ISSUE TITLE
Questionable questing problem

### ISSUE THREAD

**Issue by MirCton** [dteviot/WebToEpub#403]
This
![Screenshot_20201025-175414](https://user-images.githubusercontent.com/73046010/97104017-568ae180-16eb-11eb-93cd-4b3e3ef58b73.jpg)
![Screenshot_20201025-175320](https://user-images.githubusercontent.com/73046010/97104021-5e4a8600-16eb-11eb-9506-c72b120e8f92.jpg)
Don't know what's going on.
Link-https://forum.questionablequesting.com/threads/gamer-of-the-void-gamer-multiverse.13092/
Link 2-https://forum.questionablequesting.com/threads/power-corrupts-gamer-si-skyrim.10700/

Edit:I'm on android firefox

**Comment by dteviot** [comment]
@MirCton
Unfortunately, those links don't work for me.  They bring up a logon page, and I don't want an account on that site.
And I can'seem to find the relevant stories.  Might be possible via the search https://forum.questionablequesting.com/search/?type=post, but I can't seem to find them.

The error message, "post is null" at line 67 of QuestionableQuestingParser.js suggest problem is those stories have a different layout.  (WebToEpub is trying to find a post on the thread, and not finding it.)
Unless I can see the actual story HTML, not much I can do.

**Comment by MirCton** [comment]
@dteviot uhh apparently you can't see nsfw stuff without an account

**Comment by dteviot** [comment]
@MirCton
What happens if you try  https://forum.questionablequesting.com/threads/point-me-at-the-skyrim-ward-x-elder-scrolls.11514/, which works for me.
Note steps
1. Open above URL
2. Click on "Threadmarcks" check box that's just above the first post on page, and below the tags
3. Click on "View all 16 threadmarks"
4. Open WebToEpub
5. Click on "Advanced Options" and make sure "Max web pages to fetch simultaneously" is set to 1.
6. Click "Pack Epub"

**Comment by MirCton** [comment]
@dteviot okay the link you gave works

But when i used another sfw link
![Screenshot_20201026_200408](https://user-images.githubusercontent.com/73046010/97177755-91674500-17d1-11eb-92f6-8ac9cde9de35.jpg)
 yeah

Link-https://forum.questionablequesting.com/threads/harry-potter-and-the-lady-thief-harry-potter-au-complete.6052/

And a few other links

Example-https://forum.questionablequesting.com/threads/absolute-divinity-jojo-dio-si.11401/

Yeah apparently stories with chapters above at least 9 has problems.

**Comment by dteviot** [comment]
@MirCton
Well, this is embarrassing.
Looks like I only tested against stores where all chapters were on a single page.
Problem seems to be, when there is more than one page of chapters, additional chapters have an additional entry in the path.
e.g. 
> https://forum.questionablequesting.com/threads/harry-potter-and-the-lady-thief-harry-potter-au-complete.6052/page-2#post-1413294

vs.
>  https://forum.questionablequesting.com/threads/harry-potter-and-the-lady-thief-harry-potter-au-complete.6052/#post-1413294

However, in the raws HTML, the URLs have duplicate entires in the path, so need to be cleaned to get the corect URL.
e.g. 
https://forum.questionablequesting.com/threads/harry-potter-and-the-lady-thief-harry-potter-au-complete.6052/threads/harry-potter-and-the-lady-thief-harry-potter-au-complete.6052/page-2#post-1413294

And the code to clean the links stripped the final entry in path for pages after the first.
Fix committed and new version (0.0.0.122) uploaded to Firefox store and is available.  I've not updated the Chrome version, as you're using Firefox and I don't think many others are using QueestionableQuesting.
