### ISSUE TITLE
Cannot install add-on on Android Firefox

### ISSUE THREAD

**Issue by AncientCatz** [dteviot/WebToEpub#404]
I can no longer install this add-on on Firefox mobile, but I was able to install it in the past. Please fix this problem

**Comment by dteviot** [comment]
Known issue.  
For time being, you need to use the Nightly version of Android Firefox if you want to run extensions.
See: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
