### ISSUE TITLE
Help mtlnovel.com/godly-talent-duplicate-system/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#407]
https://www.mtlnovel.com/godly-talent-duplicate-system/  downlist is only up to 81 and https://www.mtlnovel.com/godly-talent-duplicate-system/chapter-list/ 255 chapter if DL from here.  Other novel on same site doesnt seems to have same problem.

**Comment by dteviot** [comment]
@Finks82
I'm not sure what you're doing.  I tired https://www.mtlnovel.com/godly-talent-duplicate-system/ on both Chrome and Firefox, (Desktop) and they both show 841 chapters.
That said, I think I've seen problems with this site in the past. Yes. see https://github.com/dteviot/WebToEpub/issues/338
I think this site is a bit flaky in how it serves up the table of content entries.
Sorry, but nothing I can do, beyond suggesting you try again, possibly in a few hours.

**Comment by Finks82** [comment]
ok thx i try it again just now,  and it work just fine.
