### ISSUE TITLE
[Question] Is there a way to use this on LNMTL - Reslator userscripts?

### ISSUE THREAD

**Issue by rvindo** [dteviot/WebToEpub#409]
Hello,

Sometimes a novel was dropped and we can only read it on LNMTL. I use "reslator" userscripts to make the translation more readable. Is there any way webtoepub can "catch" the translation result?

Thank you!

**Comment by dteviot** [comment]
@rvindo.
I assume you're referring to https://openuserjs.org/scripts/Spawner/Reslator_-_LNMTL_Plugin
(Note to self, source can be obtained from https://openuserjs.org/src/scripts/Spawner/Reslator_-_LNMTL_Plugin.user.js#bypass=true)
How to you personally use it?

**Comment by rvindo** [comment]
@dteviot 
Yes, that is the correct userscript that I use. I use it by installing tampermonkey extensions on Chrome and when I opened the LNMTL, it correctly translate the chapters. The result of the translation can be seen here: https://imgur.com/GK2UlWc

**Comment by dteviot** [comment]
@rvindo 
What I was trying to understand is what does it do to LNMTL?
If Reslator is not there, LNMTL also shows a translation.  Notes for Reslator suggest it does some sort of lookup against Google/Alibaba, etc.)  But I'm not sure exactly what it's doing.  (The whole thing, or just parts?  If parts, do you trigger it manully? How?) And to be honest, I don't have a lot of time to investigate.  So, was hoping you could tell me.

**Comment by dteviot** [comment]
Closing due to lack of response from @rvindo
