### ISSUE TITLE
Website Request: Graverobber

### ISSUE THREAD

**Issue by wintersnew** [dteviot/WebToEpub#410]
Requesting to have a support for this website as well _https://graverobbertl.site/_ Thank you!
it currently showing me this:
![Capture](https://user-images.githubusercontent.com/38267997/98500064-5e6b8980-2286-11eb-89d1-8df94fa3114b.PNG)

**Comment by dteviot** [comment]
@wintersnew 
New parser added.  Note, it's going to be a while before I upload new version to Chrome + Firefox stores.
However, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know if that solves most of your problems.

Note you'll need to fix up the chapters in TOC a bit.
* Magical★Explorer, chapters 38 and 39 are transposed, and URL for chapter 117 is mangled
* The strongest dull prince, has a number of cases where the chapter has links to 2 chapters.
e.g. 35, 41, 44, 46, 48, 51, 73, 79  

to make thosw work, need to manually add missing chapter links and point them at the actual webpage.

e.g. convert
```HTML
<a href="https://graverobbertl.site/spt-chapter-73-74/">chapter 73</a>
```
to 
```HTML
<a href="https://graverobbertl.site/cry-of-collapse/">chapter 73</a>
<a href="https://graverobbertl.site/duel-of-determinations/">chapter 74</a>
```
Alternately, just download the epub I made, which I put in same folder as the test versions.  (And let me know when you've done that so I can delete it.)

**Comment by wintersnew** [comment]
nice! thank you for adding the site in webtoepub, also I downloaded the epub and the new extension you mention (that's what I need btw.)

**Comment by dteviot** [comment]
@wintersnew
Updated version 0.0.0.123 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Comment by Tenome** [comment]
Needs to be updated, it seems like. Doesn't list the chapters now, Is there a way to force manual mode when it doesn't work as intended?

https://graverobbertl.site/ace-pilot/
