### ISSUE TITLE
Website Requests

### ISSUE THREAD

**Issue by azurymous24** [dteviot/WebToEpub#411]
Hi! If possible, can you please add https://suikatl.carrd.co
Thank you so much!

**Comment by dteviot** [comment]
@azurymous24
For tracking purposes, only one web site per request, please.
i.e. Remove all but one site from this request, then make 4 more requests, with one website in each.

**Comment by azurymous24** [comment]
Okay! Thanks for notif.

**Comment by dteviot** [comment]
@azurymous24 
Unfortunately, I can't do the site https://suikatl.carrd.co.  It's uses Google Docs, and I have not figured out how to get content from them.

**Comment by azurymous24** [comment]
Hi! It's okay, no problem. Thank you so much for your effort. 😊😊
