### ISSUE TITLE
Website Request: http://edanglarstranslations.com

### ISSUE THREAD

**Issue by azurymous24** [dteviot/WebToEpub#416]
Hi, can you please add this site? http://edanglarstranslations.com

**Comment by azurymous24** [comment]
>

**Comment by dteviot** [comment]
@azurymous24 
This site is horrible.
It has 4 stories, and they have different formatting.
That said, "Silent Reading" and "They All Say I've Met a Ghost" already provide EPUBS  (Check each book for "Silent Reading")
And parser works tolerably well for the other two.

**Comment by azurymous24** [comment]
Okay, no problem ! Thanks for checking it out. 🥰🥰🥰

**Comment by dteviot** [comment]
@azurymous24
I believe that's the last of the sites you requested that I can do.
Note, it's going to be a while before I upload new version to Chrome + Firefox stores.
However, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by azurymous24** [comment]
Really?! Thank you so much for your hard work, I'm really grateful. 🥰🥰

**Comment by dteviot** [comment]
@azurymous24
Updated version 0.0.0.123 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Comment by azurymous24** [comment]
Thank you very much. 💓💓💓
