### ISSUE TITLE
Issue with https://www.lightnovelworld.com adding additional text

### ISSUE THREAD

**Issue by ragen123** [dteviot/WebToEpub#419]
This site adds additional text to the epub. Is there a way to not include the text?

This text:  New novel chapters are published on l_ight_novelworld.c_om

There are like 3 lines in between 1 chapter. Thanks

**Comment by dteviot** [comment]
@ragen123
It's a bit tricky. The strings are in &lt'span&gt; elements, but they change the strings, so it's not easy to be sure you've identified the right strings.
e.g. I've seen the following strings:

- This content is taken from lightnovelworld.com
- Follow current novels on light_n_ovel_w_orld.com
- The source of this content is lightnovelworld.com

I could just remove all &lt;span&gt; elements, but that runs the risk of removing parts of the chapter.
So, my suggested solution would be: 
1. Leave WebToEpub alone (so it gets an epub with all the text.)
2. Use Calibre with a regex to remove the &lt;span&gt; elements as a later step.  (Calibre will show you what it's removed, so you can check it hasn't removed something it should not have.)

Alternately, I could modify my MergeWebToEpub to remove the &lt;span&gt; elements, but tell you what it removed, so you can confirm it hasn't removed anything vital.

Let me know what you think.

**Comment by ragen123** [comment]
I can use Calibre to edit the epub, if its so tricky.
Thanks for the help.

**Comment by dteviot** [comment]
@ragen123 
On reflection (It's amazing what a night's sleep can do) I think I've got a solution.
Take the span, remove the underscores and look for " lightnovelworld.com".
It might not get all of them, but it should get most.

**Comment by ragen123** [comment]
Yeah that make sense :D For now I managed to edit it with calibre.

**Comment by dteviot** [comment]
@ragen123
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@ragen123
Updated version 0.0.0.123 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
