### ISSUE TITLE
[Request] Option for delay between web page requests

### ISSUE THREAD

**Issue by jnpl95** [dteviot/WebToEpub#420]
Hi, 

I was wondering if it's possible to add a textbox where the user can specify a custom delay in some unit of time (milliseconds/seconds/hours etc. in a dropdown) where the extension waits that delay before sending the next chapter page request. I imagine it would prevent bot detection on certain websites and reduce server load, so can benefit both the users & website owners for those who input longer delays & don't mind waiting. 

I don't have an example website off the top, but I think it's a good idea in general to implement for scrapers. Searched for "delay" in issues but didn't find this request, so thought I'd raise an issue

**Comment by dteviot** [comment]
@jnpl95
It should not be a necessary.  Assuming you set the rate to 1 pages at a time, WebToEpub will automatically back-of if the site requests it using a 429 response.

**Comment by jnpl95** [comment]
Ohh ok makes sense, that's definitely a smarter way that I didn't consider. I'll close this issue, thanks!
