### ISSUE TITLE
Request to support site: https://morenovel.net/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#421]
Dear Devs,
Please add support for this source: https://morenovel.net/ 
I have used the manual method, but the results are a bit bad.  Still fetching the entire page content of each chapter.
Thanks.
![Screenshot_20201118-130024_MiXplorer](https://user-images.githubusercontent.com/50254552/99492292-dbda7c80-299f-11eb-91d4-28a88d96d962.jpg)

![Screenshot_20201118-130046_MiXplorer](https://user-images.githubusercontent.com/50254552/99492076-81412080-299f-11eb-94af-537b421765b5.jpg)

**Comment by dteviot** [comment]
@budikesuma
Updated version 0.0.0.123 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Comment by budikesuma** [comment]
Thanks for your quick update, The results have been great.
Did you know that there is a *mobile browser* that can handle your
extension?
Since I just tried your update on the android browser, and the results are
equivalent when you use a laptop.
*Of course will eat a lot of RAM, so you can't multitasking.*

**Comment by dteviot** [comment]
@budikesuma
I'm not quite sure what you're asking me.
I am aware that some time ago Firefox for Android was able to run extensions.
But they've changed the rules, and now only the Nightly build of Firefox for Android supports extensions.  (At least, last I checked.)

**Comment by budikesuma** [comment]
@dteviot 
Well, I'm not sure Firefox still supports extensions (oh well, they only support add-ons).  What I'm talking about is another Browser.  
They support extensions from Chrome.  
I'll show you the screenshots, I'm sure you will know what the browser is.
![Screenshot_20201120-071753_Kiwi Browser](https://user-images.githubusercontent.com/50254552/99758578-fe78ac80-2ae9-11eb-968d-1d8bb740598e.jpg)
![Screenshot_20201120-071810_Kiwi Browser](https://user-images.githubusercontent.com/50254552/99758611-105a4f80-2aea-11eb-9595-33048d3005b0.jpg)
