### ISSUE TITLE
Website Request: https://dummynovels.com

### ISSUE THREAD

**Issue by azurymous24** [dteviot/WebToEpub#423]
Hi! Can you please add the site https://dummynovels.com if possible. Thank you so much.

**Comment by dteviot** [comment]
@azurymous24
I believe it's done.  However, it will be a while before I update the Chrome & Firefox stores.
Until then, test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@azurymous24
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Comment by azurymous24** [comment]
Thank you so much. ❤
