### ISSUE TITLE
Website Request: https://hui3r.wordpress.com

### ISSUE THREAD

**Issue by 1jamie7** [dteviot/WebToEpub#424]

**Comment by dteviot** [comment]
@1jamie7
I believe it's done.  However, it will be a while before I update the Chrome & Firefox stores.
Until then, test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, looking at the site, you should have been able to use the default parser.

**Comment by 1jamie7** [comment]
Thank you very much. ☺️

**Comment by dteviot** [comment]
@1jamie7
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
