### ISSUE TITLE
Request to support site : https://idnovel.my.id/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#428]
Dear Devs, 
Please add support for this source: 
https://idnovel.my.id/

Novel link: 
https://idnovel.my.id/novel/rebirth-of-the-thief-who-roamed-the-world

Thanks.

**Comment by dteviot** [comment]
@budikesuma
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@budikesuma
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Comment by budikesuma** [comment]
Thanks devs.
