### ISSUE TITLE
Firefox - WebToEpub breaks if noscript is installed

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#43]
OK, I investigated and found that WebToEpub breaks if noscript is installed (Firefox 49.0a2).
I tested this with a clean profile, and as soon noscript is installed, WebToEpub gives this error:

![uffuffuff](https://cloud.githubusercontent.com/assets/1866248/16685298/86513dfe-450a-11e6-9c4d-09f1b02878be.png)

Since noscript doesn't break any other plugin I have I'm posting this issue here.

**Comment by belldandu** [comment]
@typhoon71 from https://noscript.net/features

> When you install NoScript, JavaScript, Java, Flash Silverlight and possibly other executable contents are blocked by default. You will be able to allow JavaScript/Java/... execution (scripts from now on) selectively, on the sites you trust. You can allow a site to run scripts temporarily, if you're just surfing randomly, or permanently, when you visit it often and you really trust it. This means that NoScript learns from your own browser habits and tends to disappear in the background after a while, but it promptly comes back to save your day if you stumble upon a malicious web page.

**Comment by typhoon71** [comment]
Ahem!... I should have said that everything on Baka-Tsuki was allowed... It should have been so...
But actually I forgot to whitelist Baka-Tsuki on Firefox 49.0a2... sniffle...
It was whitelisted on Firefox 47.0.1, but I was using a temp profile on Firefox 49.0a2 to test WebToEpub and I totally forgot to whitelist it on that too. I feel stupidier than usual.
Sorry for wasting your time.

**Comment by belldandu** [comment]
Its fine I kinda figured that much out anyway from what was said.
