### ISSUE TITLE
Null invalid something Questionable questing 

### ISSUE THREAD

**Issue by MirCton** [dteviot/WebToEpub#430]
https://forum.questionablequesting.com/threads/you-want-me-to-be-a-dark-lord-original-isekai.9965/
![Screenshot_20201129_190515](https://user-images.githubusercontent.com/73046010/100540092-1680c680-3276-11eb-8469-0476582167bb.jpg)
![Screenshot_20201129_190450](https://user-images.githubusercontent.com/73046010/100540096-20a2c500-3276-11eb-9206-b4b615cbce78.jpg)

**Comment by dteviot** [comment]
Note to self, should be fixed by https://github.com/dteviot/WebToEpub/commit/f62fe3b2de773ef7f562d242904263d480ea3818

**Comment by dteviot** [comment]
@MirCton
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
