### ISSUE TITLE
requesting support for Webnovel

### ISSUE THREAD

**Issue by Badr-Zh** [dteviot/WebToEpub#431]
Hi, is it possible to add support for Webnovel.com?? I downloaded the extension after seeing many recommendations that it works on webnovel but it turned out that it doesn't. only this message appeared when I tried it.

--
Error: No chapters found. 
   at QidianParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:435:35) 
   at QidianParser.fetchContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:421:21) 
   at HTMLButtonElement.fetchContentAndPackEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:136:16)

**Comment by dteviot** [comment]
@Badr-Zh
1. Did WebToEpub show a list of chapters before you clicked the "Pack EPUB" button?  (I'm guessing it didn't).
2. In which case, did you click on the "Table of Contents" on the WebNovel.com site so the chapters are showing before opening WebToEpub?

Try the following:
1. Go to story on Webnovel.com.  e.g. I just tired https://www.webnovel.com/book/it's-lonely-to-be-invincible_16005456605644405, and it worked.
2. Click the "Table of Content" tab on the page, so it shows the list of chapters.
3. Open WebToEpub.

**Comment by Badr-Zh** [comment]
> @Badr-Zh
> 
> 1. Did WebToEpub show a list of chapters before you clicked the "Pack EPUB" button?  (I'm guessing it didn't).
> 2. In which case, did you click on the "Table of Contents" on the WebNovel.com site so the chapters are showing before opening WebToEpub?
> 
> Try the following:
> 
> 1. Go to story on Webnovel.com.  e.g. I just tired https://www.webnovel.com/book/it's-lonely-to-be-invincible_16005456605644405, and it worked.
> 2. Click the "Table of Content" tab on the page, so it shows the list of chapters.
> 3. Open WebToEpub.

Thanks a lot, it worked. It didn't work at first because I used it while inside a chapter, not on the main page.
unfortunately, it can't bypass the paywall for locked chapters but at least this will save me from the occasional lock they sometimes put on already unlocked chapters. again thank you. I will leave a five-star review for the extension.
