### ISSUE TITLE
Novelgate error

### ISSUE THREAD

**Issue by NightHawk007** [dteviot/WebToEpub#432]
Hi 
Support for novelgate was added but I'm unable to download anything could you please check.
This is LN I'm trying to download. (https://novelgate.net/monarch-of-time-34/)

**Comment by dteviot** [comment]
If you're running Chrome, it hasn't updated to version 0.0.0.124 yet.
I did say it will take Google anywhere up to a week to review and release.
You can check the versions of your extensions by pasting "chrome://extensions/" without the quotes into url bar.

**Comment by NightHawk007** [comment]
Yes it works in Firefox 
Thank you  
Sorry for the trouble
