### ISSUE TITLE
Website Request: sites.google.com

### ISSUE THREAD

**Issue by 1jamie7** [dteviot/WebToEpub#433]

**Comment by dteviot** [comment]
@1jamie7
I'll need a few more site URLs, please

**Comment by 1jamie7** [comment]
You mean the specific website?
I'm so sorry for this trouble. Some of the novels that I want are on that
site but different translators. They're just using sites.google.com. I
don't know if this is possible but if it's too much, it's fine. ☺️

**Comment by dteviot** [comment]
@1jamie7 
I need to look at the sites to see how they are laid out, so I can figure out how to write a parser for them
If I go to https://sites.google.com/new, I get a site generator, not what I want.
Give me the URLs of the "Table of Contents" page for a couple of the sites and I'll see what I can do.

Until I can examine the sites, I can't tell how difficult it will be.

**Comment by 1jamie7** [comment]
https://sites.google.com/view/qingtranslates/contents-page
https://sites.google.com/view/guomentranslation/table-of-contents

Thank you. ❤️

**Comment by 1jamie7** [comment]
https://sites.google.com/view/xiyangfanyi/sytz-crushing-jade-and-casting-pearls
https://sites.google.com/view/gldzz

**Comment by dteviot** [comment]
@1jamie7 
It's not great, but it's the best I can do.
Note, it's going to be a while before I can upload to Chrome and Firefox stores.
So, test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by 1jamie7** [comment]
Thank you very much. 💞💞💞

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
