### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by JasCU100** [dteviot/WebToEpub#434]
I would like to ask if it is possible to not show the pop-up window after the creation of the epub? The one where we input the file name...can there be an option to save the file name automatically from what we input in 'Title' or 'FileName'? Would be great for the epub to save automatically in a folder.....

Also, can I request for EpubEditor to have a feature to edit batches of epubs (e.g. for CG) or for individual edit to output the zip file with the same file name as the epub inputted instead of text.zip? Thank you!

**Comment by dteviot** [comment]
@JasCU100 
>I would like to ask if it is possible to not show the pop-up window after the creation of the epub?

Sorry, no.  Doing that results in some problematic edge cases.

> EpubEditor to have a feature to edit batches of epubs (e.g. for CG)

I need more details about what you want.  "edit batches" could mean all sorts of things..

>  individual edit to output the zip file with the same file name as the epub inputted instead of text.zip

This I don't understand.  WebToEpub should generate a file called <whatever was in the save file dialog>,epub.
It should not be saving the epub as "text.zip"
I've seen weirdness like that under the following conditions: 
1. Conflicting with another extension
2. Older versions of Epub
3. Browsers other than Firefox and Chrome.

**Comment by JasCU100** [comment]
Oh, sorry I mean the output when I input epub from CG to EpubEditor is test.zip. I use clean CG option. I don't know why but when I use chrome, it outputs test.zip but in firefox, it's test.epub. For the edit batches, I mean if multiple CG epubs can be inputted?

**Comment by dteviot** [comment]
@JasCU100 
I'm sorry, but I'm still not following you.  
1. What's "CG"?  Is it a web site?
2. What's "EpubEditor"?  (I'm assume it's https://www.epubeditor.it/home/home-en/, but I'm not sure)

I'm guessing, you're doing something like.
1. Use WebToEpub to create an Epub from the "CG" web site
2. You're then running the Epub through "EpubEditor" to do some additional cleaning.
3. You'd like WebToEpub to automatically send the epub to EpubEditor, or some way to send a batch of epubs into EpubEditor?

**Comment by JasCU100** [comment]
I'm sorry, by CG I meant [this](https://chrysanthemumgarden.com/) site. I'm using the EpubEditor from https://github.com/dteviot/EpubEditor which you recommended in a [previous post](https://github.com/dteviot/WebToEpub/issues/354) of mine. There's an option there to clean the site specifically. But test.zip or test.epub is the name of the output I get, so I was wondering if it could have the same name as the file name of the epub I input. By batch input, I mean I could drag multiple epub files from CG at EpubEditor at once instead of inputting them individually...because I'm having problems renaming the files haha. 

Thank you for the response! :)

**Comment by dteviot** [comment]
@JasCU100
D'oh!  That EpubEditor.
FYI., if you want that changed, you should raise the issue against that project.
That said, I've just committed a fix so it will try to save the epub with same name. Although it gives it a number to stop the names conflicting.
As regards the batch mode, it's not really designed for a batch mode, and modifying it to do batch mode is more time than I'm willing to spend.

**Comment by JasCU100** [comment]
Thank you!
