### ISSUE TITLE
Support for tumblr image galleries

### ISSUE THREAD

**Issue by Too-Ticki** [dteviot/WebToEpub#435]
Hi, could you please look into image galleries on tumblr? Posts with just one image work fine, but any posts with several images in a gallery, none of the images show up in the epub.

Example of a post with one image that works:
https://songsforgorgons.tumblr.com/post/103923842558/

Example of a post with a gallery that doesn't show up in the epub:
https://songsforgorgons.tumblr.com/post/165445603988

Thank you for a great extension!

**Comment by dteviot** [comment]
@Too-Ticki
Can you provide me with some additional examples of tumblr galleries?

Looking at this one example, it seems that in the raw HTML, there's &lt;div&gt; with a class of "html_photoset".  The URLs for the images to populate it are found elsewhere in &lt;meta&gt; elements.

I need a a couple more examples to see if they're similar.

**Comment by dteviot** [comment]
@Too-Ticki Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
It worked for the image pages from https://kimamanitranslatesnovels.tumblr.com/destruction-flag-otome

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
