### ISSUE TITLE
need support https://m.gzbpi.com/wapbook/2003768_1/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#436]
its a chinese raw site, add support pls.  Main issue when "Apply" is click 

01. only half of the chapter is DL example 
https://m.gzbpi.com/wapbook/2003768/97810874.html <--- chapter 1 first half  downloaded
https://m.gzbpi.com/wapbook/2003768/97810874-2.html <----- chapter 1 2nd half not downloaded

02. each page only show 40 chapter [ as in only 40 chapter we can download per click]

Thx

**Comment by dteviot** [comment]
Notes to Self:
Sample summary page: https://m.gzbpi.com/info/2003768
ToC: https://m.gzbpi.com/wapbook/2003768/

For multipage, look at "next" page hyperlink, if hyphen in path leaf, has additional page.  Might be more than one.

**Comment by dteviot** [comment]
@Finks82
I don't know Chinese, so I'm not sure how good this is.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
