### ISSUE TITLE
Request to support site : https://webnovelindonesia.com/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#439]
Dear Devs, 
Please add support for source:  
https://webnovelindonesia.com/

Novel link: 
https://webnovelindonesia.com/novel/legend-of-the-supreme-soldier/

<i>Manual method didn't works.</i>
Thanks.

**Comment by dteviot** [comment]
@budikesuma
Site doesn't work for me.  I can't get chapter lists, and I can't even open first/last chapter of a title when I click on the link that shows.
You could try writing your own parser:
How to: 
* https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
* https://dteviot.github.io/Projects/webToEpub_CustomizingParserTemplate.html

**Comment by budikesuma** [comment]
well, the site seems to work properly through Linux OS, not for everyone.  
So just forget about this site.  
Thanks in advance..
