### ISSUE TITLE
Improve memory utilization.  Stream content directly to EPUB file.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#44]
Currently plugin downloads all content (chapters and images) before packing them into the EPUB.  This works OK at moment, but may have problems later when try processing items that are very large,.
Should re-architect so packs each piece of content into the epub file on disk as it's downloaded.
Note, this may need to wait until Chrome 52, which implements streams.

**Comment by belldandu** [comment]
Agreed

**Comment by dteviot** [comment]
Closing
- Memory usage doesn't seem to be a major issue, I've created epubs with size > 200 MByte.
- There is some processing that can't be done (e.g. removing links to other pages) until all pages have been fetched.
