### ISSUE TITLE
Request for site Tapread

### ISSUE THREAD

**Issue by JasCU100** [dteviot/WebToEpub#443]
Can you please add support for http://www.tapread.com? Thank you!

**Comment by dteviot** [comment]
Notes for self:
Looks doable.

Sample ToC page URL: http://www.tapread.com/book/detail/94
URL details for chapter list:  
  POST 
  http://www.tapread.com/ajax/book/contents, 
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  FormData is bookId: 94
  Response is JSON,  want element result.chapterlist, wanted fields are chapterId, chapterName.

Content for chapter:
  To get chapter content
  POST
  http://www.tapread.com/ajax/book/chapter
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  FormData is bookId: 94, chapterId: 2846
  Response is JSON,  want elements result.chapterName, result.content

**Comment by dteviot** [comment]
@JasCU100 
I believe it's fixed.
However, it will be a while before I update the versions in the Chrome and Firefox stores,
So, test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by JasCU100** [comment]
Thank you very much!

**Comment by dteviot** [comment]
@JasCU100
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
