### ISSUE TITLE
Set ranges for TOC  Arcs/ Volumes 

### ISSUE THREAD

**Issue by drjoe123** [dteviot/WebToEpub#445]
I'd like the ability to insert breaks in the table of contents delineating Arcs / Volumes.  Preferably, it wouldd also automatically number the chapters by arc / volume. At each break there'd be the option to add a volume cover. Maybe an entry that let's you "add volume beak after chapter xyz" and then a place to insert the volume image link. Currently, I manually insert the volume number in front of each chapter. 

Thanks, 

Joe

**Comment by dteviot** [comment]
> I'd like the ability to insert breaks in the table of contents delineating Arcs / Volumes

Have you considered using Calibre? https://manual.calibre-ebook.com/edit.html#editing-the-table-of-contents
Basically, you add an entry for "Volume" to the Table of Contents, then select the chapters in the volume, right click and select indent.

**Comment by drjoe123** [comment]
I have Calibre on my pc, but mostly manage and generate epubs on my Android tablet. I have a Samsung Galaxy Tab S4 which basically replaces my pc. I have a Windows 10 laptop, but rarely use it for anything. I'll take a look at it.

I like your plug in because I can use it directly in Android - but I had to "freeze" Firefox for Android at version 68.11.0 because they basically obsoleted all plug-ins in the newer builds. At this point, I use Firefox Beta for browsing and Firefox 68.11.0 to generate epubs. I'd really like an "all Android" solution.

My biggest problem is is that I generate tons of epubs... If I don't edit them as I generate them, I may never have the time to go back and edit them.

Thanks for your time,

Take care,

Joe

________________________________

**Comment by dteviot** [comment]
@drjoe123 
I can understand your desire.  However I'm going to close this on the basis:
1. This is more an "edit epub" ability than a "generate epub".
2. What you want to do can be done with a existing (albeit different tool)
3. I can't see a way to do this with an intuitive UI.
4. Will require significant work to implement, which I don't have.

**Comment by dteviot** [comment]
@drjoe123
>  but I had to "freeze" Firefox for Android at version 68.11.0 because they basically obsoleted all plug-ins in the newer builds

FYI. I believe plug-in support is available in the "Nightly" builds of Firefox for Android.

**Comment by drjoe123** [comment]
Thanks, I'll look at it.

Joe

________________________________
