### ISSUE TITLE
Add sites marxists.org and marx2mao.com

### ISSUE THREAD

**Issue by poopingpenis** [dteviot/WebToEpub#446]
These sites have a lot of good books and texts that are not available on epub anywhere. Would love to see them added. :)
https://www.marxists.org/
http://www.marx2mao.com/

**Comment by dteviot** [comment]
@poopingpenis
One site per incident, please.  It make tracking easier for me.

**Comment by poopingpenis** [comment]
@dteviot Should I close this one and make them separately?

**Comment by dteviot** [comment]
@poopingpenis
Actually, you just needed to remove one from this issue and create a single new issue with the removed site.
But, closing this and creating two new issues also works.
