### ISSUE TITLE
Add marxists.org

### ISSUE THREAD

**Issue by poopingpenis** [dteviot/WebToEpub#447]
This site has a lot of good books and texts that are not available on epub anywhere. Would love to see it added. :)
https://www.marxists.org

**Comment by dteviot** [comment]
Note to self:
This looks like a Table of Contents page:  https://www.marxists.org/archive/rappoport/index.htm

**Comment by dteviot** [comment]
@poopingpenis
This site looks trivial to do.  You probably don't even need to write a parser for it, you could just use the default parser.
If you want to try writing a parser, instructions are at https://dteviot.github.io/Projects/webToEpub_CustomizingParserTemplate.html

**Comment by poopingpenis** [comment]
> 
> 
> Note to self:
> This looks like a Table of Contents page: https://www.marxists.org/archive/rappoport/index.htm

This is actually a list of the person's works, and some of them might have chapters and/or ToCs of their own. For example, https://www.marxists.org/history/international/comintern/sino-soviet-split/cpc/leninism.htm has 6 chapters or parts, though no table of contents.

**Comment by poopingpenis** [comment]
I'll test some things out with the default parser, sorry if the request was redundant.

**Comment by poopingpenis** [comment]
The epub on the first document I posted didn't generate a ToC but that's not too shocking, and the second had the site's headers and footers in every chapter, but the site's formatting is really inconsistent so automating against that would be pretty difficult. marx2mao shares a lot of the same library and is far more consistent in its formatting, so it would be more suited to its own parser. Better just leave it up to that if possible. 👍
