### ISSUE TITLE
Can't fetch this particular novel in MTLNOVEL

### ISSUE THREAD

**Issue by itsyahma** [dteviot/WebToEpub#449]
Don't know if this is due to my wifi or not 
The novel: https://www.mtlnovel.com/demon-king-dad/

**Comment by itsyahma** [comment]
I just tested fetching other novels, it works but didn't on this specific novel

**Comment by itsyahma** [comment]
Webtoepub was not able to fetch  this specific novel

**Comment by dteviot** [comment]
@itsyahma 
Seems find to me
I do note that you've had problems with other stories on this site. 
Which seem to fix themselves after a few days.
I think it's simply the site is not very stable.

**Comment by dteviot** [comment]
Incidentally "not able to fetch this novel". Isn't very helpful.
Was the problem:
1. List of chapters to fetch was empty/missing entries
2. Unable to fetch some/all chapters?  (if so, what were the error messages?
3. Chapters were corrupt?
4. Something else?

**Comment by itsyahma** [comment]
Webtoepub is able to list all the chapters in its page but when i try to create the epub, the number of chapters fetched is 1 and it creates an epub with only the title and information chapters inside with no story chapters.

**Comment by itsyahma** [comment]
I don't know if my explanation is sufficient, I suggest you to try and see it for yourself

**Comment by dteviot** [comment]
@itsyahma
The URL for chapter "~ Sixth Year Story 037" is mangled.
it is https://www.mtlnovel.comhttps//www.mtlnovel.com/demon-king-dad/sixth-year-story-037/
If you change it to https://www.mtlnovel.com/demon-king-dad/sixth-year-story-037/
then everything will work.

You might like to send a note to the site operators.

**Comment by itsyahma** [comment]
Ok i Will see to it

**Comment by itsyahma** [comment]
The url is not mangled and it still not fetching any chapters

**Comment by itsyahma** [comment]
I'm stupid I changed the wrong url

**Comment by itsyahma** [comment]
It works, thank you

**Comment by dteviot** [comment]
@itsyahma 
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
