### ISSUE TITLE
Add support for https://www.gunnerkrigg.com/

### ISSUE THREAD

**Issue by BenGoldberg1** [dteviot/WebToEpub#451]
I tried to create a epub for this web comic, starting at https://www.gunnerkrigg.com/archives/ but the parser only found the first page of each chapter, i.e. urls ending in "/?p=1", "/?p=17", up to "/?p=2398".

However, the story runs from page 1 up to page 2408.

All of each chapter's page numbers are contained inside of option values.

**Comment by dteviot** [comment]
@BenGoldberg1
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, it looks like some chapters have an "information" page at the end.
These pages do not appear as links on the archive page you give.
e,g, Chapter 1 is pages 1 to 15, Chapter 2 starts with page 17.  https://www.gunnerkrigg.com/?p=16 is not a story page, but gives background information.

The GunnerkriggParser I have written does not collect these information pages.  If you want them, I will let you modify the parser to do so. You should be able to figure it out from the commit, but if you need a hand, let me know.

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
