### ISSUE TITLE
Encoding problem on xbiquge.cc

### ISSUE THREAD

**Issue by AndyEr2** [dteviot/WebToEpub#452]
Hi!

I try to download this book - **https://www.xbiquge.cc/book/10208/** , I do everything as usual, it downloads, but instead of the text I see incomprehensible characters, as if the encoding is wrong.

Book text in browser - **https://prnt.sc/wey3qy**

And here's what the add-on downloads - **https://prnt.sc/wey467** This is a preview directly in the add-on. Any reader shows the same.

**Comment by dteviot** [comment]
@AndyEr2 
The short answer is, looks like site is using GBK to encode the characters set, but not advertising this in the response headers.  So WebToEpub is assuming it's UTF-8 and failing.  Solution is to write a parser which includes the correct encoding.

**Comment by dteviot** [comment]
@AndyEr2
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.  (Warning, I don't know Chinese)

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Comment by Hogesyx** [comment]
> Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

Hi @dteviot, there seems to be a couple of different site that uses the same engine as Biquge, currently my own branch I have rename XbiqugeParser to BiqugeParser and added additional parserFactory.register to the parserfile.

```
parserFactory.register("www.xbiquge.cc", () => new BiqugeParser());
parserFactory.register("biquge.com.cn", () => new BiqugeParser());
parserFactory.register("biquge.tv", () => new BiqugeParser());
parserFactory.register("biquge.co", () => new BiqugeParser());
```

What is your opinion on standardizing this? using regex for url?

**Comment by dteviot** [comment]
@Hogesyx
I'd do just what you've done.  I wouldn't bother with a regex.  Because the parserfactory uses a map to match hostnames.
Although if you really want, you could use parserFactory.registerUrlRule() instead.  BlogspotParser shows an example of its use.

To handle the encoding, I'd modify the constructor to take the decoder value, and pass that in the constructor.

e.g.
```javascript
parserFactory.register("xbiquge.cc", () => new BiqugeParser("gbk"));

    constructor(decoder) {
        super();
        this.decoder = decoder;
    }

        let options = { 
            makeTextDecoder: () => new TextDecoder(this.decoder) 
        };
```
