### ISSUE TITLE
Prevent Server from overload or saying too many requests.

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#454]
**Is your feature request related to a problem? Please describe.**

Hi if you want to create a epub from www.royalroad.com as example it goes fine but since a few weeks ago it is pretty slow and i think the reason is, that it tries to fetch them too fast and the server says  "Slow down!" you can get this massage in chrome if you create in bookmarks a folder and puts 10 different stories from www.royalroad.com in this folder. Than try right click on this folder and open all. Some pages don't load with the message "Slow down!".

**Describe the solution you'd like**

My dream solution would be if you can select under advanced Options maby under "Max web pages to fetch simultaneously"  "☐ throttle fetch speed to max. __per second" and an option to write the amount to wich it is throttled. (Maybe write a tipp if you can enter decimal numers like 0.5 per second)

**Describe alternatives you've considered**

A Check box wich throttles the fetching speed to one per second.
"☐ throttles fetching speed to one per second."

**Additional context**

I think that if you only fetch one per second it is slow enough to not trigger "Slow down!" but faster than it is at the moment.

**Comment by dteviot** [comment]
@gamebeaker 
WebToEpub is slowing down because the site is asking WebToEpub to slow down.
See: https://github.com/dteviot/WebToEpub/issues/420

Unless WebToEpub is failing to (eventually) fetch all the requested content, I don't see a problem.
However, as I've received a number of people making this request, am I missing something?
Are you actually running into a problem, or are downloads from www.royalroad.com just slow?

**My additional thoughts**

The back-off logic used could be improved.

Specifically, when receiving a 429 reply WebToEpub preforms an exponential back-off, This simplifies the code, by using the same common code for other HTTP errors.  Unfortunately, it ALSO means that once a 200 is received, WebToEpub goes back to full speed.
Ideally, WebToEpub should probably:
1. If given a 429 message, should remember this for additional fetches..
2. Parse the reply's-"after header" in the response for back-off duration. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After   (Note that when this is a date value, parsing is a pain.)

Unfortunately, the error handling code in WebToEpub is VERY complicated, and I'm reluctant to touch it in case I break it.
So, it's a case of it's not ideal, but it's good enough.

Alternate thought: response from RoyalRoad shows a reply-after of 1 second.  So, I can set the RoyalRoad parser to 1 fetch per second.

**Comment by gamebeaker** [comment]
@dteviot "Unless WebToEpub is failing to (eventually) fetch all the requested content, I don't see a problem.
However, as I've received a number of people making this request, am I missing something?" 
It fetchs all the content so no problem. It is only an optimization for speed, because in the past royalroad didn't send 429.(i think)

Example: https://www.royalroad.com/fiction/16946/azarinth-healer
This Story contains ~600 Chapter and to download this it took ~31 minutes ( 31min*60sec/min = 1860sec ; 1860sec / 607chapter = 3sec/chap ) This means it only downloaded one Chapter each 3 seconds in the average. In the reality it is ~5 chapter superfast and than it receives 429 and waits.

"Alternate thought: response from RoyalRoad shows a reply-after of 1 second. So, I can set the RoyalRoad parser to 1 fetch per second."

I think this would slove the problem for this website because with 1sec/chap it isn't to fast to receive 429.(1sec/chap * 607chap = 607sec ; 607sec / 60sec/min = 10min ; 10min < 31min) 

I don't know if "Parse the reply's-"after header" in the response for back-off duration. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After (Note that when this is a date value, parsing is a pain.)"
answers my question. Maybe i get it wrong and this is the answer but it is possible to make "Retry-After: <delay-seconds>" <delay-seconds> variable so that you can change it under advanced Options maybe not completly freely but like max. Chapter with 100,200,500,1000,2000,5000,10000 or max web pages to fetch simultaneously with 1,2,4,8. So you can change from idk standart 5s to 1,2,3,4,5.

**Comment by dteviot** [comment]
@gamebeaker
Well, I tried to add throttling, but it doesn't work very well when running "Max web pages to fetch simultaneously" with a value of 8.
That said, looks like RoyalRoad was taking about 1 to 2 seconds to send a page anyway. So if you set "Max web pages to fetch simultaneously" to a value of 2 does that work better?  Note you can use the chrome "Network" DevTool to see the network  activity https://medium.com/@ConnorFinnegan/how-to-effectively-inspect-network-activity-in-chrome-dev-tools-fd18592a735a .  Also, if 2 doesn't work, does 1?

**Comment by gamebeaker** [comment]
@dteviot ok i tested it again with 8 max. fetch it took 43min and with 1 max. fetch it took 32min. (not simultaneously in two tabs; one after another) So i think that if i have selected 8 the server sends 429 faster than if you only fetch 1 that is why 1 is faster.

**Comment by dteviot** [comment]
@gamebeaker
I suggest you try with "Max web pages to fetch simultaneously" set to 2.
As RoyalRoad throttles to a rate of 1 page / second, then 600 pages should take 10 minutes.
If downloading at one page at a time takes 32 minutes, then at two pages at a time should take 16 minutes, which is still above the throttling limit (on average), but will be significantly better than 32 minutes.  (And not TOO much worse than 10 minutes.)

**Comment by gamebeaker** [comment]
@dteviot Max web pages to fetch simultaneously set to 1 don't download 1per second it downloads more i think it only parse one per time not simultaneously. You can test this here https://m.wuxiaworld.co/Godly-Model-Creator/ (only selected 30 chapter). Without the cover it took 10sec .

**Comment by dteviot** [comment]
@gamebeaker
> Max web pages to fetch simultaneously set to 1 don't download 1per second it downloads more i think it only parse one per time not simultaneously

That is correct.  And different sites take a different amount of time to send each page.
e.g. I think RoyalRoad has been updated so it takes 1 to 2 seconds to send each page.  However, it can send multiple pages simultaneously.  So, if you do 2 pages at the same time, it's faster than one by one.  Hence, if you try doing more than 2 pages simultaneously, you'll trip the rate limiting.
Other sites are faster (mostly, the big ones) and some are a lot slower (mostly, the sites run by individuals.)

**Comment by gamebeaker** [comment]
@dteviot 

> Example: https://www.royalroad.com/fiction/16946/azarinth-healer
This Story contains ~600 Chapter and to download this it took ~31 minutes ( 31min*60sec/min = 1860sec ; 1860sec / 607chapter = 3sec/chap ) This means it only downloaded one Chapter each 3 seconds in the average. In the reality it is ~5 chapter superfast and than it receives 429 and waits.

I did this and 

> In the reality it is ~5 chapter superfast and than it receives 429 and waits.

In the progress bar i see it like this.

**Comment by gamebeaker** [comment]
Ok i have found a custom "solution" for me. I open Object inspector and throttle my Internet speed to 300kB/s i select 4 max fetch simul... and start the epub creating. With this Settings i only need 5min50sec to download the hole book.

To fetch one Chap. it needs~2sec and with 4chap simultaneously i don't get 429 error thats why it is faster.

**Comment by dteviot** [comment]
@gamebeaker
Congratulations on finding a solution.  (I should have thought of throttling the connection.)
I'm going to call this closed.
