### ISSUE TITLE
Can't Get Mtlreader to work

### ISSUE THREAD

**Issue by Kiiiddd** [dteviot/WebToEpub#455]
Been try to get a novel off of Mtlreader But the selector just wont grab the element
The selector I was using was 
#app > div > div > div > p 
which holds the element but I keep on pulling the error
Error: Could not find content element for web page 'https://www.mtlreader.com/novels/80/chapters/16163'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/DefaultParserUI.js:154:23

**Comment by dteviot** [comment]
@Kiiiddd
That's because the the initial web page returned from https://www.mtlreader.com/novels/80/chapters/16163 does not have the text.
Instead, that web page has javascript that makes a HTTP Get call to https://www.mtlreader.com/api/chapter-content/16163, which is the content for the chapter.

You can't use the default parser for that site,i'll have to write a parser.

**Comment by dteviot** [comment]
@Kiiiddd
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, you might also like to pass on a message to the operators of the site.
It looks like they might have a problem handling angle brackets.
For URL https://www.mtlreader.com/novels/1/chapters/131, I think the last line is supposed to be:
>Anos had a look on his face that it would be natural for a reincarnated baby to use &lt;growth (kurst) magic.&gt;

But what shows is 
>Anos had a look on his face that it would be natural for a reincarnated baby to use 
 
The &lt;growth (kurst) magic.&gt; has been turned into an HTML tag.
 
I tried to do it myself, but that requires creating an account and is more hassle than I want to deal with.

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
