### ISSUE TITLE
Add site https://wondernovels.com/

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#458]
https://wondernovels.com/

**Comment by dteviot** [comment]
@sigmatc
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by sigmatc** [comment]
Thank you
IT's working, finally figured out hot to do it.

**Comment by dteviot** [comment]
@sigmatc  
Updated version (0.0.0.126) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
