### ISSUE TITLE
Add site https://lightnovelbox.com/

### ISSUE THREAD

**Issue by Ketboga** [dteviot/WebToEpub#459]
https://lightnovelbox.com/

I tried to grab the content using css but no matter what, I could not do it, so I can only suggest adding this website.

Thank you for your help in advance.

**Comment by dteviot** [comment]
@Ketboga
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Ketboga** [comment]
Works well, thank you for your efforts.

**Comment by dteviot** [comment]
@Ketboga 
Updated version (0.0.0.126) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
