### ISSUE TITLE
Calibre has problems with three dots in image filenames

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#46]
Reported by dreamer2908

> Ugh, apparently Calibre has problems with three dots in image filenames if I enable --smarten-punctuation option. Maybe I should report it to them when I stop being lazy.

Maybe replace the three dots (which are supposed to indicate an elipsis) with something else.  Not sure what would be best.  Some options are:
- underscore(s)
- hyphen(s)
- maybe  '-xxx-'

**Comment by toshiya44** [comment]
Underscrores, single hyphen or -xx- will do. (there might be some issue with multiple hyphens, so it's best avoid that)

**Comment by dreamer2908** [comment]
The --smarten-punctuation option converts plain quotes, dashes and ellipsis to their typographically correct equivalents.

Apparently, it doesn't skip all tags, so three dots `...` becomes ellipsis glyph u2026. Actual images aren't renamed, so it can't find the referenced file.

I ran ebook-convert (Calibre ebook converter CLI) a few times and here is the console output: http://pastebin.com/9qPeRdsP

In the first run, `--smarten-punctuation` was on. It couldn't find the images. In the output, images got replaced with big blue question marks: https://i.imgur.com/UeB5ffb.png . Well, it's weird that it could find the cover image just fine.

In the second run, without `--smarten-punctuation`, it had no problem. The output is normal: https://i.imgur.com/XYqscv9.png

In the third and fourth runs, I edited the epub file in Sigil, and renamed images: three dots into two dots, a single dot, one/two hyphens, underscore, -xxx-, single quotes, etc. ` --smarten-punctuation` was on, but it had no problem.

It seems that it only has problems with three dots. Underscores is the safest, I guess.

**Comment by dteviot** [comment]
@dreamer2908
That's a really detailed analysis.
Sounds like it is a bug in Calibre.  As you say, it's renaming the <image> tags.

I note this in the Calibre output, looks like I have more work to do.
> The cover image has an id != "cover". Renaming to work around bug in Nook Color

**Comment by belldandu** [comment]
Hrm thanks @dreamer2908 @toshiya44 for this detailed bug report. I agree with the -xxx- replacement for ... although calibre should REALLY not be doing this so someone should report this to calibre as a bug. Please feel free to link to this issue if you need to. 

@dteviot Yeah fun. 

Also i might be away for a few days because of joining the navy (for several reasons) But i'll do my best to keep up with stuff.

**Comment by dteviot** [comment]
@dreamer2908
Logged bug with Calibre team.
https://bugs.launchpad.net/calibre/+bug/1602100

You may want to add OS and Calibre version.

**Comment by dreamer2908** [comment]
The bug is said to have been fixed last week: https://bugs.launchpad.net/calibre/+bug/1598465

I've checked out the latest version 2.62.0 and it seems to have no problem with three dots. Good, good.

**Comment by belldandu** [comment]
@dteviot @dreamer2908 awesome

**Comment by belldandu** [comment]
If there are no further issues i'm going to close this for now since calibre no longer seems to have this issue.

If you need this issue reopened then just @ me in a comment on this issue and i will reopen it.
