### ISSUE TITLE
Activetranslations.xyz stuck after a certain amount of chapters... And epub chapters are scrambled

### ISSUE THREAD

**Issue by Mkjafu** [dteviot/WebToEpub#460]
After 30 or so chapters scraped from activetranslations.xyz it gets stucked
and I don't know if this is exclusive to activetranslations.xyz but epubs that I've scraped from there have jumbled chapters.

Issue #1
1.Go to activetranslations.xyz
2.Scrape chapters from a novel
3.Get stuck after scraping 31 chapters when "Max web pages to fetch simultaneously" is set to "1" and 61 chapters if "Max web pages to fetch simultaneously" is set to "8"
4.After getting stuck Error:"429 Too Many Requests by Booter - Bots & Crawlers Manager" appears.
*throttle solution from Issue #457 does not work

Issue #2 
1.Go to activetranslations.xyz
2.Scrape a novel then make an epub.(I recommend doing this with https://activetranslations.xyz/eer/ as it only has 26 chapters)
3.After a certain amount of perfectly fine chapters. the text will be scrambled (I got a total of 5 chapters that were fine in EER in the 6th chapter the text is jumbled and my tts won't recognize some. with :svg:(change the : to >or<) popping up everywhere.

Also, please add proper support for Activetranslations.xyz if possible

**Comment by dteviot** [comment]
@Mkjafu 
Re: issue 2, please put the epub you created somewhere, and provide a link for me to download.

**Comment by Mkjafu** [comment]
I'm sorry for the late reply.

I used a PC epub reader and it's not jumbled but using @Voice Aloud Reader on android gives it jumbled text. but [you can  still see that the TTS is only recognizing some of the text,](https://drive.google.com/file/d/1pvgiiutLTzJLm7nvKxBY_gKDcoQdzQ0U/view?usp=sharing)

 [here is the link for the epub](https://drive.google.com/file/d/1nVhX3voxcFh6K-xjariFuZ2d1MeJMpxK/view?usp=sharing)

**Comment by dteviot** [comment]
@Mkjafu
I can't see anything obviously wrong with the HTML for chapter 358 in the EPUB.
As your problem is with the Aloud reader, I suggest you contact them.

**Comment by dteviot** [comment]
@Mkjafu
Additional, I was able to use Windows Narattor https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1 to read chapter 358 from the Epub.
So, I think the problem is with the Aloud reader.

**Comment by Mkjafu** [comment]
> @Mkjafu
> Additional, I was able to use Windows Narattor https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1 to read chapter 358 from the Epub.
> So, I think the problem is with the Aloud reader.

sorry for the late reply but the problem starts at Chapter 359

**Comment by dteviot** [comment]
@Mkjafu
OK, I think I see what's happening.
Basically, it's taking HTML that would be like this
````HTML
<p class="">“Oh, well, you really came out.”</p>
````

And splitting it up like this
````HTML
<p class=""><span class=" wf4214c10952dc478f1fb93d23f43555a"> came </span></p>
<style> 
             .wf4214c10952dc478f1fb93d23f43555a::before {
                                content: '“Oh, well, you really';
                            }
                            .wf4214c10952dc478f1fb93d23f43555a::after {
                                content: 'out.”';
                            }
</style> 
````

It should be possible to unscramble, but it's going to take me a while to get around to getting it done.

**Comment by dteviot** [comment]
@Mkjafu
OK, I think I've got the scrambled text sorted.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Mkjafu
Updated version (0.0.0.126) with fix for scrambled pages has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, Have not tried fixing the "stuck after a certain amount of chapters" bug

**Comment by Mkjafu** [comment]
> @Mkjafu
> Updated version (0.0.0.126) with fix for scrambled pages has been submitted to Firefox and Chrome stores.
> Firefox version is available now.
> Chrome might be avaiable in 1 to 3 weeks.
> If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
> 
> Note, Have not tried fixing the "stuck after a certain amount of chapters" bug

Thank you very much for fixing the issue. I hope the "stuck after a certain amount of chapters will be fixed soon"
