### ISSUE TITLE
add site https://chrysanthemumgarden.com

### ISSUE THREAD

**Issue by PleaseReadMe** [dteviot/WebToEpub#462]
Please add [chrysanthemumgarden.com](chrysanthemumgarden.com) without any gibberish parts

**Comment by dteviot** [comment]
@PleaseReadMe|
Please provide more details.
At minimum, URL of a chapter that has gibberish, plus example of the gibberish.

This will let me know where to look for an example of the problem, and what to look for.

**Comment by gamebeaker** [comment]
@dteviot 
Between the content in the html code is "gibberish" with the class='jum' 
example: https://chrysanthemumgarden.com/novel-tl/fog/fog-1/
or: https://chrysanthemumgarden.com/novel-tl/embers/embers-3/
but not all chapter have "gibberish" i think it is a new feature 
example: https://chrysanthemumgarden.com/novel-tl/dm/dm-8/ (without gibberish)
https://chrysanthemumgarden.com/novel-tl/dm/dm-9/ (with gibberish)

**Comment by dteviot** [comment]
@PleaseReadMe, @gamebeaker
D'oh!  Known issue.  https://github.com/dteviot/WebToEpub/issues/354
Solution: 
> I've added an option to https://github.com/dteviot/EpubEditor to clean up Epubs from chrysanthemumgarden.com
Go there and follow the instructions. If you have any problems, please email me at dteviot@gmail.com

**Comment by PleaseReadMe** [comment]
Thank you
