### ISSUE TITLE
Filename Problem

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#463]
In CHROME, 
When making an epub if i change the [Filename] before packing, then there will be strings of number and letters when the packing is complete.
I have seen it several times, when the filename is not changed, the file name remains the same on the downloaded file. but after the filename is changed once, it will be strings of number and letters.
Can we rename the Filename and still have it downloaded in the same name because when i am packing multiple epubs. the strings of numbers are quite confusing.
Is there a solution to it?

**Comment by dteviot** [comment]
@sigmatc
This does not happen for me. It does sound a bit like https://github.com/dteviot/WebToEpub/issues/191
So, things you might try:
1. Are you running any other extensions?  If so, if you disable them, does WebToEpub save with correct name?  (You can then enable them one by one to find the conflict.)
2. Are you running in incognito mode?
3. Does Firefox have this problem?

Final question, when you say 
> i change the [Filename] before packing

do you mean:
1. You're changing the filename on the WebToEpub main window (that shows chapters, title image, etc.), or
2. On the "Save As" dialog that appears to collect the filename.

**Comment by sigmatc** [comment]
@dteviot 
it was Free Download Manager 3.0.52.

Thank you for the help.

EXTRA 
When i change [Filename] before packing, it was changing the filename on WebToEpub main window.

**Comment by dteviot** [comment]
Going to call this solved
