### ISSUE TITLE
Support for alphapolis.co.jp

### ISSUE THREAD

**Issue by JasCU100** [dteviot/WebToEpub#467]
Can https://www.alphapolis.co.jp/ be supported? Thank you!

**Comment by dteviot** [comment]
@JasCU100,
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Thanks to @gamebeaker for doing the work.  Note, I can't read Japanese, so I can't verify the work.

**Comment by dteviot** [comment]
@JasCU100
Updated version (0.0.0.127) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
