### ISSUE TITLE
Add site https://www.lightnovelworld.com/ and Web site throttling

### ISSUE THREAD

**Issue by Mkjafu** [dteviot/WebToEpub#470]
https://www.lightnovelworld.com/ please add this site.
I tried to scrape it, but I get stuck after a certain amount of chapters.

**Comment by gamebeaker** [comment]
Hi this is no issue with webtoepub it is a protection from the server to prevent ddos attacks. After a few chapter the server thinks 'these are too many requests for a human so i block it'. You can see this if you right click -> Inspect (Crt+shift+i in chrome) chose 'network' start 'pack epub' and you will see how each chapter gets downloaded but after a few it stops and the last chapter is red with status'429'. 429 means the server says 'stopp no more requests pls.' and that is the point webtoepub waits a few seconds before it asks the server again.
You can also see it in these issues they are similar: #454 #442

**Comment by dteviot** [comment]
@Mkjafu, 

A minor point,, according to the specs (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) status 429 usually include a "how long to wait before server will respond again" header.  (In my experience, it's usually 60 seconds)  So, WebToEpub will wait before continuing. So, WebToEpub isn't getting stuck, it's waiting for the site to start responding again.  And it you wait, you should see WebToEpub start again.  Note, it site takes longer than (I think) 4 minutes to start responding WebToEpub will give up.
Note, after the server starts responding again, the server will again say "wait".
So, you'll see a burst of pages, followed by a long pause, then another burst of pages, another pause, etc.

I'd also strongly suggest making sure "Max web pages to fetch simultaneously" on the advanced settings is set to 1.

cc @gamebeaker

**Comment by Mkjafu** [comment]
@dteviot Let me check it first then I'll close the issue if what you said really was the case. If not will let this remain open.

**Comment by Mkjafu** [comment]
@dteviot It seems you were correct and lightnovelworld now works perfectly. Thx for the quick response. Closing the issue.

**Comment by Mkjafu** [comment]
Ah, can you tag this as complete instead?

**Comment by dteviot** [comment]
@Mkjafu
I've tagged it as complete.
But why do you want it left open?
Generally, I only leave things open if there's still work to do.  (Open + Completed tag means fixed version hasn't been submitted to Chrome & Firefox stores yet.
