### ISSUE TITLE
Google play failed processing

### ISSUE THREAD

**Issue by dragonphoenix29** [dteviot/WebToEpub#473]
Google play failed processing
when i upload failes frome https://www.mtlnovel.com/

**Comment by gamebeaker** [comment]
@dragonphoenix29 can you elaborate your problem? What do you mean with google play? and why upload? specific link to the problematic novel would be helpful.

**Comment by dragonphoenix29** [comment]
play book

**Comment by gamebeaker** [comment]
@dragonphoenix29 doesn't work by me too don't know the reason i use the app Moon+ reader https://play.google.com/store/apps/details?id=com.flyersoft.moonreader&hl=de&gl=US to read ebooks on my smartphone.

**Comment by gamebeaker** [comment]
@dragonphoenix29 I just found a "solution" Pack ebup on pc and download calibre (https://calibre-ebook.com/) copy ebook inside calibre -> select book-> convert book->output format "Epub"->'OK'->wait until finished->click the book and press 'O' or right click open containing folder now you see inside your explorer a epub. Copy this epub inside your google play book library it should now work.

**Comment by dteviot** [comment]
@gamebeaker, dragonphoenix29 

I've previously seen issues uploading epubs created by WebToEpub to Google play.
Summary:

The most common issues are:
1. Use of webp images
2. Unable to convert HTML into valid XHTML.

WebToEpub should warn you when the create epub has these issues.
And I've got a tool (MergeWebToEpub at https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8) that can check for these problems and convert webp images to jpeg.
Instructions at https://github.com/dteviot/WebToEpub/issues/390#issuecomment-705147284
