### ISSUE TITLE
eslint question

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#474]
Hi i tried to install eslint if i now look at my repository git hub says i have a lot of new files wich would appear in a pull request.
![image](https://user-images.githubusercontent.com/9269847/108508118-9ccc0800-72bb-11eb-95f6-4c433bd04c9a.png)
Is this normal? Should i delete them before i make a pull request?

**Comment by dteviot** [comment]
@gamebeaker
Add these files (or directories) to the .gitignore file.
https://git-scm.com/docs/gitignore
