### ISSUE TITLE
How to delete https://www.lightnovelworld.com/ markers?

### ISSUE THREAD

**Issue by Ketboga** [dteviot/WebToEpub#475]
Hi, I have been using this extension and would like to thank you for your effort firstly.

My problem is the novels I have gotten from  www.lightnovelworld.com have this website's markers almost 11-15 times per chapter, and they are as below;

The novel: Way of the Devil
Taken from: www.lightnovelworld.com
Original Source: Qidian
English Publisher: Webnovel
Tool: WebToEpub

**Chapter 1 Markers:**
''Visit lightnovelworld[./]com for the best novel reading experience''  it looks like this in the HTML view 
p class="ljsdon"> Visit lightnovelworld[./]com for the best novel reading experience

''Visit /lightno//velw/orld[.]com for the best novel reading experience'' 
p class="ljsdon">Visit /lightno//velw/orld[.]com for the best novel reading experience

''New novel chapters are published on l/ightn/o/velworld[.]c/om''
''This content is taken from lightnovelworld[.]c/om''
''The most up-to-date novels are published on //lightno/ve/lworld[.]com''
''This content is taken from /ligh/tnovelworld[.]com''
''This content is taken from lightnovelw/orld[.]com''
''Visit light/nove/lworld[/.]com for the best novel reading experience''
''Follow current novels on lightnove//lworld[.]c/om''
''The source of this content is lightnovelworld[.]com''
''Updated from lightnovelworld[.]com''
''Advertisements''
''The most up-to-date novels are published on lightnov/elw/orld[.]com''

**Chapter 2 Markers:**
''The most up-to-date novels are published on lig/htno/ve/lworld[.]com''
p class="ogloom">The most up-to-date novels are published on lig/htno/ve/lworld[.]com

''Follow current novels on lightn/ov/elworld[.]com'' 
p class="ogloom">Follow current novels on lightn/ov/elworld[.]com

''Visit lightn/ovelwor/ld/[.]com for the best novel reading experience''
''The most up-to-date novels are published on lightnovelworld[.]com''
''Updated from lig//htnovelworld[.]/com''
''Updated from /lightn/o/velworld[.]com''
''New novel chapters are published on lightnovelworld[.]c/om''
''This content is taken from lightnovelworld[.]com''
''The source of this content is li/ght/novel/w/orld[.]com''
''For more, visit l/ightnovelworld[.]/c//om''
''The most up-to-date novels are published on lightn/ov/el/world[.]c/om''

So, is it possible to make these markers disappear?

**Comment by gamebeaker** [comment]
there is a bug i try to fix it.

**Comment by gamebeaker** [comment]
@Ketboga  Hi i was able to make this stuff disappear here is the download
https://github.com/gamebeaker/WebToEpub/archive/ExperimentalTabMode.zip
here is a tutorial how to install: https://github.com/dteviot/WebToEpub#how-to-install-from-source

**Comment by gamebeaker** [comment]
ok i just downloaded way of the devil looks like it doesn't filter all but is pretty good in the 772 chapter it now has only marker in chapter 49,253,260,317,336,449,507,611,636,671,701,754(12 chapter) (it takes ages to download that is why i only saw it now)

**Comment by dteviot** [comment]
@Ketboga
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Ketboga** [comment]
I have downloaded a few novels from lightnovelworld via webtoepub and the test version works great all the markers disappeared thankfully.

Thank you again for your efforts in this @dteviot and@gamebeaker.

**Comment by dteviot** [comment]
@Ketboga
Updated version (0.0.0.127) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
