### ISSUE TITLE
Option to add page with URL

### ISSUE THREAD

**Issue by kairusds** [dteviot/WebToEpub#476]
Please add an option that can allow you to add more pages because some of it aren't detected

**Comment by gamebeaker** [comment]
if you click on Edit Chapter URLs you can add more chapter.
![image](https://user-images.githubusercontent.com/9269847/108596089-10851800-7383-11eb-888f-0168e5081a85.png)

**Comment by gamebeaker** [comment]
You can add more on edit chapter URLs.
![image](https://user-images.githubusercontent.com/9269847/108596357-d157c680-7384-11eb-9d56-c25481a54823.png)
It looks like it is a little buggy. I got it too work if i first open WebToEpub on the main page and click on edit chapter URLs than i open the second page with the other links in another tab and click on WebToEpub. In the second tab i click on Edit Chapter URLs and copy the URLs i want, than i insert them in the first tab and click Apply Changes.

**Comment by dteviot** [comment]
@gamebeaker
Thank you for replying to this.  It really is appreciated.
Note, I'd suggest changing
> It looks like it is a little buggy

in your reply to 
> It'a a bit clumsy
