### ISSUE TITLE
Fix Addon for Firefox Fenix 

### ISSUE THREAD

**Issue by crypticc23** [dteviot/WebToEpub#480]
Background
-Firefox Android changed from Fenic to Fenix in August 2020, which disabled all except a limited whitelist of addons
-However, you can now still install addons on Firefox Fenix in the Firefox Nightlys through the collection feature, and Webtoepub does install (how to here: https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/)

Issue
-While webtoepub runs, and the status bar shows all the chapters being completed, the final step of downloading the file does not happen.
-Storage permissions for Firefox Nightly are on and I have not seen any settings in the Firefox Nightly app itself that might cause this issue and tested that I am able to download files generally in Firefox Nightly.

Requesting a fix so the addon continues to work.  Thanks.

**Comment by dteviot** [comment]
@crypticc23
I'm going to need some help with this.  I no longer have an Android tablet able to run Firefox.  (Long story, short form Malware destroyed it, and I haven't got around to buying another.)
My plan would be, if you're able to load test versions into your tablet, you can run a couple of test versions and we can try and isolate the problem.
So, first thing to try: can you 
1. get the Firefox version of the extension from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing and 
2. Load it into Firefox,  (Note, you might need to change the filename extension to "xpi")
3. Run it. 

From your description,the extension is probably failing in one of two places.
1. Packing the chapters into an epub
2. Writing the epub to downloads.  (My guess is this is failing, but I need to prove it..)

So, additional questions. You say
>  the final step of downloading the file does not happen.

So what does happen?

**Comment by crypticc23** [comment]
It might be that I don't know what I am doing, but the way to get addons into the Android Nightly is to add it to a Firefox collection through "Find add-ons", which as far as I can tell needs it to be searchable on Firefox AMO and as such I can't load it from a self-hosted url or file.  If you are able to get it into a collection I should be able test is using the collection url. (https://addons.mozilla.org/en-US/firefox/collections/X/Y - X and Y are needed to load.)

In terms of what happens - the bar moves as if it is getting the chapters, shows X/X (example 50/50), but nothing happens.  It just stays on the page.  

Thanks

**Comment by dteviot** [comment]
@crypticc23
My apologies, I've just skimmed the  https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/) and it looks like it only works for apps that are in the store.

That said, I've done a little digging and it sounds like the Fenix based Firefox is still under development and doesn't yet support all the functionality for extensions yet.  So, my guess is the Download part hasn't been done yet.  I'm now trying to contact the Mozilla developers to find out more.

**Comment by dteviot** [comment]
@crypticc23
From Mozilla Dev
>The downloads.download API uses the same logic as desktop for validating the URL, and one of the results is that data:-URLs can still not be downloaded. See https://bugzilla.mozilla.org/show_bug.cgi?id=1318564

However, a workaround has been suggested.
```javascript
let blob = URL.createObjectURL(new Blob([output.join('\n')]));
browser.downloads.download({url: blob, filename: 'something'});
```

I will investigate

**Comment by dteviot** [comment]
Looks like the DataURL is not the problem, I am creating a blob URL
https://github.com/dteviot/WebToEpub/blob/2478bac99781063bf2cbc8175769425317dd369e/plugin/js/Download.js#L27-L33

**Comment by dteviot** [comment]
Note for me.  "Debugging extensions for Firefox for Android" (not for the faint of heart)
https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/

**Comment by crypticc23** [comment]
Confirmng this now works.  Thanks!

**Comment by dteviot** [comment]
@crypticc23 
You should thank @Lej77, he's the one who solved it.
