### ISSUE TITLE
lightnovelworld.com changed to lightnovelpub.com

### ISSUE THREAD

**Issue by Jenniyah** [dteviot/WebToEpub#485]
the url had changed to a new one lightnovelpub.com and it no longer pulls. Gives error instead

No parser found for this URL. Default Parser will be used. Please specify how to obtain content from each web page.

Thank you

**Comment by gamebeaker** [comment]
@Jenniyah  Hi you can still use it to create epubs from lightnovelpub.com if you copy the link of the novel you want and open a new tab in it you click on webtoepub. Then you paste the link in the starting URL section and changes the link from lightnovelpub.com... to lightnovelworld.com... click load and analyse. The Cover Image is wrong but you can simple change this link.

**Comment by dteviot** [comment]
@Jenniyah
New version 0.0.0.128 has been posted to the Firefox store and is available at https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Unfortunately, as I submitted a version of WebToEpub to the Chrome store yesterday, it will be 2 to 3 weeks before I can submit an updated version to the Chrome store.  (And then another 2 to 3 weeks for them to approve.)
If you REALLY want a Chrome version,
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
