### ISSUE TITLE
Add website allnovel.org

### ISSUE THREAD

**Issue by maphie14** [dteviot/WebToEpub#490]
https://allnovel.org/ 

same layout with novelfull.com but some novels have more updated chapters

**Comment by gamebeaker** [comment]
A dirty fix would be to Download from source 
https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source
than in the folder js->parsers open novelfullparser.js in editor.
Add to line 7: 
parserFactory.register("allnovel.org", function () { return new NovelfullParser() });
than change in line 36 
if (link.hostname === "novelfull.com") { 
to 
if (link.hostname === "allnovel.org") {

now you can download from allnovel.com but not from novelfull.com

**Comment by dteviot** [comment]
@maphie14 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@maphie14
Updated version (0.0.0.128) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
