### ISSUE TITLE
Please add support for: http://www.quanben.io/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#491]
Dear Devs, 
Please add support for:
http://www.quanben.io/

Novel link: 
http://www.quanben.io/amp/n/taohuazhai/list.html 

Thanks.

**Comment by dteviot** [comment]
@budikesuma 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Please note, I don't know Chinese,, so I can't test them very much.

**Comment by dteviot** [comment]
@budikesuma
Updated version (0.0.0.128) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.

**Comment by budikesuma** [comment]
Great, perfect results for me.. thanks dev
