### ISSUE TITLE
Add site https://novel.naver.com/webnovel/

### ISSUE THREAD

**Issue by zazouze** [dteviot/WebToEpub#495]
https://novel.naver.com/webnovel/
Thank you

**Comment by dteviot** [comment]
@zazouze

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, I don't know Korean, so it's difficult for me to tell how well it works.
This seemed to work: https://novel.naver.com/webnovel/list.nhn?novelId=933819&page=1

**Comment by zazouze** [comment]
hello, the links of the chapters load well but I have no text in the epub
![image](https://user-images.githubusercontent.com/62121714/113032580-4c847780-9190-11eb-8eec-f83541d876bd.png)

**Comment by dteviot** [comment]
@zazouze
1. Please give me the URL for the title that isn't working.
2. Can you send me the epub you created?
3. I tried https://novel.naver.com/webnovel/list.nhn?novelId=933819&page=1, does it work for you?

**Comment by zazouze** [comment]
https://novel.naver.com/webnovel/list.nhn?novelId=868563

[Tentation que vous seul ne connaissez pas (KO) - NanerNovel - 94ch T.zip](https://github.com/dteviot/WebToEpub/files/6231745/Tentation.que.vous.seul.ne.connaissez.pas.KO.-.NanerNovel.-.94ch.T.zip)

I have the same problem on the novel you tested.

As I am in France it is possible that the Request Headers must authorize the French language "accept-language: fr-FR, fr; q = 0.9, en-US; q = 0.8, en; q = 0.7, ko; q = 0.6 "

**Comment by dteviot** [comment]
@zazouze
I think the problem is with your epub viewer.
I can read the epub you made with Calibre and EPUBReader http://www.epubread.com/
The first chapter in the epub looks like the first chapter from the web site.

Note, the text seems to be in Korean, so I don't know why you think the Request Headers must authorize the French language

**Comment by zazouze** [comment]
Ah yes indeed it works with caliber, I used ADE. 
For the Request Headers I had this problem on another US program on a FR website, after reflection it was my mistake to think that this problem would be  on a Korean website.
Thank you very much for your program and adding navernovel.

**Comment by dteviot** [comment]
@zazouze 
> For the Request Headers I had this problem on another US program on a FR website, after reflection it was my mistake to think that this problem would be on a Korean website.

No problem.

> Thank you very much for your program and adding navernovel.

You are very welcome.

**Comment by zazouze** [comment]
Hello again, the epub is loading well (thanks again) only the character dialogue images have a slight problem. The image of the first character is repeated on all the other characters for each chapter. Is there any way to fix this problem?

![image](https://user-images.githubusercontent.com/62121714/113444009-53f78b00-93f3-11eb-9788-549426ca700a.png)

![image](https://user-images.githubusercontent.com/62121714/113443858-09760e80-93f3-11eb-9937-5e99133c26f4.png)

![image](https://user-images.githubusercontent.com/62121714/113445101-7d191b00-93f5-11eb-996c-2448db4480cd.png)


![image](https://user-images.githubusercontent.com/62121714/113445052-61ae1000-93f5-11eb-8bd0-464077ab4ba5.png)

**Comment by dteviot** [comment]
@zazouze

D'oh!  My apologies.  I believe I've found and fixed the problem.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Incidentallly, how are you managing to view the web site in what I think it french?

**Comment by zazouze** [comment]
Oh good! Yes it works very well. Thank you very much!

> Soit dit en passant, comment parvenez-vous à afficher le site Web dans ce que je pense être français?
Yes, it is French. For the translation of the web page, on chrome, I right click on the web page and select translate. And on firefox I installed the extension translate web pages:
https://addons.mozilla.org/fr/firefox/addon/traduzir-paginas-web/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search.
It works very well for the English French translation, a little less for the Korean but we understand the text.

**Comment by zazouze** [comment]
Oh super! Oui ça marche très bien. Merci beaucoup!

> Soit dit en passant, comment parvenez-vous à afficher le site Web dans ce que je pense être français?

Yes, it is French. For the translation of the web page, on chrome, I right click on the web page and select translate. And on firefox I installed the extension translate web pages:
https://addons.mozilla.org/fr/firefox/addon/traduzir-paginas-web/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search.
It works very well for the English French translation, a little less for the Korean but we understand the text.

**Comment by dteviot** [comment]
@zazouze
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
