### ISSUE TITLE
Chrome webstore version of webtoepub is two versions behind the firefox version.

### ISSUE THREAD

**Issue by credulous2skeptic** [dteviot/WebToEpub#496]
**Describe the bug**
Is the chrome webstore version not being updated? The version on chrome webstore is 0.0.0.127 but on AMO it is 0.0.0.129

**To Reproduce**
Go to:
[https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm](url)

[https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/](url)

**Expected behavior**
I expect both stores to have the same version of webtoepub.

**Comment by gamebeaker** [comment]
@credulous2skeptic chrome versions needs a few weeks to get approved Firefox is faster or doesn't check i don't know. @dteviot mentioned it in #467

**Comment by dteviot** [comment]
@credulous2skeptic
@gamebeaker is basically correct.  Mozilla usually approves new versions in 5 to 10 minutes, Google takes weeks.
