### ISSUE TITLE
Request https://ranobes.net/

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#497]
Request https://ranobes.net/ if possible thank you

**Comment by dteviot** [comment]
@Forgeword
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Forgeword** [comment]
@dteviot unfortunately I'm an android user of Firefox I will just wait for the update

**Comment by dteviot** [comment]
@RealNasty 
Thank you.

**Comment by dteviot** [comment]
@Forgeword
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
