### ISSUE TITLE
Fanfiction.net missing Chapter Headers

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#499]
Can't get chapter headers for each chapter
example
goes to chapter no chapter number or title
only chapter text i have to view the table of content to see the title
for fanfiction.net

**Comment by dteviot** [comment]
@kolbdog3333
https://www.fanfiction.net/s/13255743/1/Demon-Lord-s-Adventurers seems to work fine.
Please provide URL of chapter that has a problem.

**Comment by kolbdog3333** [comment]
https://www.fanfiction.net/s/13698381/1/Helluva-Loud-Luck

**Comment by dteviot** [comment]
@kolbdog3333
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by kolbdog3333** [comment]
it works thanks

**Comment by dteviot** [comment]
@kolbdog3333
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
