### ISSUE TITLE
Errors in opf

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#50]
metadata, manifest, spine and guide sections in the opf has `xmlns=""` inserted in them. 

`<metadata xmlns="" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">`
`<manifest xmlns="">`
`<spine xmlns="" toc="ncx">`
`<guide xmlns="">`

Again, calibre can still open the book, but I guess it might be an issue for other lightweight apps.
(using Firefox 49.0a2)

**Comment by belldandu** [comment]
Can confirm i had these issues even when opening Tests.html in firefox aurora. I had initially ignored them because it didn't seem like they cause any issues however you are right it could potentially cause issues in the more light weight readers.

**Comment by belldandu** [comment]
Priority changed due to affecting firefox review.

**Comment by dteviot** [comment]
How To:

http://stackoverflow.com/questions/31052554/is-it-posible-to-create-a-xml-node-with-prefix-in-javascript

http://stackoverflow.com/questions/10995338/how-do-i-add-a-namespace-prefix-to-an-xml-dom-object

**Comment by dteviot** [comment]
@toshiya4, @belldandu, typhoon71

Issues with namespaces should now be fixed in Sonako branch.
I've also tweaked the RoyalRoad parser to delete the "Try the beta reader" advert, if you'd like to give it a go.

**Comment by typhoon71** [comment]
Tried the new build on RoyalRoad, but this happens (chrome):

![uff](https://cloud.githubusercontent.com/assets/1866248/16894620/e94c4c4e-4b5b-11e6-937e-61e2a7d7fce0.png)

I could pack the epub with the previous version (but there was the "Try the beta reader" advert)

Firefox instead does this:

![fuu](https://cloud.githubusercontent.com/assets/1866248/16894651/0cba950e-4b5d-11e6-947f-8f5f19f01b89.png)

The same happens on BakaTsuki.

**Comment by toshiya44** [comment]
`Error packing EPUB. Error: EpubPacker.prototype.assembleAndSave@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/EpubPacker.js:34:13
packEpub@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:111:13
fetchContentAndPackEpub/<@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:101:13
promise callback*fetchContentAndPackEpub@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:100:9
EventHandlerNonNull*window.onload@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:179:9
EventHandlerNonNull*main<@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:177:5
@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:5:13`

**Comment by toshiya44** [comment]
@typhoon71 you have to get JsZip from https://github.com/Stuk/jszip/ and put it in the jszip folder under plugin.

**Comment by typhoon71** [comment]
Oh, so that was it. It needed the whole thing. Works now.

**Comment by belldandu** [comment]
@toshiya44 @typhoon71 @dteviot The path is now `plugin/jszip/dist/jszip.min.js` not `plugin/jszip/jszip.min.js`

This path is also specified in the edited popup.html and UnitTest.html files.

**Comment by dteviot** [comment]
D'oh!
Previously, the jszip library was included directly in WebToEpub's git. i.e. the file jszip.min.js was a file checked into GitHub, so when you got the source, it included jszip.
jszip is has been replaced with a submodule.  So when you do a Git checkout, it goes to the jszip project and pulls the file from there.  Obviously, if you donwload just WebToEpub you no longer get jszip.
I'll update the install from source instructions.

**Comment by belldandu** [comment]
@dteviot you would think that when downloading the zip file it would include the submodule repo's. Not sure if bug or intentionally like that to prevent issues on githubs end.

**Comment by belldandu** [comment]
@dteviot We should probably shoot github an email asking whether this behavior is intentional or not.

**Comment by dteviot** [comment]
@belldandu
I'm pretty sure it's intentional.
https://github.com/wbond/package_control/issues/126#issuecomment-5470380

**Comment by belldandu** [comment]
Lovely

**Comment by toshiya44** [comment]
So, now the solution is to download JSZip from  [Stuck/jszip](https://github.com/Stuk/jszip), unzip it and copy-paste the `dist` folder to `plugin/jszip`.
The namespace issue has been fixed. So I'm closing this and #49 .

**Comment by AzSiAz** [comment]
As say in the git doc for : https://git-scm.com/book/en/v2/Git-Tools-Submodules

```bash
git clone --recursive URL_REPO
```

Or if downloaded zip

```bash
cd webToEpub_Directory
git submodule init
git submodule update
```

Or as toshiya44 say just download JSZip and unzip

**Comment by belldandu** [comment]
@AzSiAz Thanks.
@dteviot I think it would be a good idea to add the above to the readme. What about you?

**Comment by dteviot** [comment]
@belldandu
I'd assumed that anyone who is getting it using Git knows about submodules.  
Most Git GUIs will tell users there are submodules and offer to fetch them.

I've already updated the read me with instructions to download jszip if using source download.
