### ISSUE TITLE
activetranslations scrambled epub (again)

### ISSUE THREAD

**Issue by Mkjafu** [dteviot/WebToEpub#501]
Epubs in "active translations" are scrambled(again much like issue #460)

Epubs made on both .129 and .130 with the .130 file having the suffix of (1).
[activescramblations.zip](https://github.com/dteviot/WebToEpub/files/6243311/activescramblations.zip)

I think the problem is with the HTML(again) might be a website-wide issue(pls confirm) if so, will proper support for "activetranslations.xyz" be expected?

**Comment by Mkjafu** [comment]
So using default manually select parser. I managed to fix the text scramble...
![example 1](https://user-images.githubusercontent.com/47405719/113473861-cb362900-949e-11eb-9d53-dfe9747d1d5c.png)

BUT!!! The text to speech is still scrambled...
https://user-images.githubusercontent.com/47405719/113473965-72b35b80-949f-11eb-9a64-6381746b56a9.mp4
Please fix this Issue!

**Comment by Madrauk** [comment]
Activetranslations uses CSS pseudo-elements as an extremely obnoxious form of anti-piracy, randomly selecting some words from the beginning and end of each sentence to convert into :before and :after pseudo elements that cannot be selected and copied, either directly from the browser or through the html. I haven't found a decent way around it so far, but i'm posting this here just in case the information can be of any use.

**Comment by Mkjafu** [comment]
> Activetranslations uses CSS pseudo-elements as an extremely obnoxious form of anti-piracy, randomly selecting some words from the beginning and end of each sentence to convert into :before and :after pseudo elements that cannot be selected and copied, either directly from the browser or through the html. I haven't found a decent way around it so far, but i'm posting this here just in case the information can be of any use.

Ok, thanks for explaining the issue!  Tbh, although I can understand you I still can't do anything to help since I have zero knowledge of coding, but thanks for the help anyways!

**Comment by dteviot** [comment]
@Madrauk , @Mkjafu

I've tweaked the unscrambling code.  Seems to work for https://activetranslations.xyz/ch/carnivorous-hunter-chapter-1/

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, when site changes there scrambling again, it will probably break again.
Unfortunately, to fix reliably, I'd need to properly parse CSS rules.

**Comment by Mkjafu** [comment]
@dteviot 
Hey man, thank you so much for responding! The issue is now fixed. I hope the fix gets carried into future updates.

Closing the issue

**Comment by dteviot** [comment]
@Mkjafu 
Reopening, so I know to notify you when fixed version submitted to Chrome and Firefox stores.  (Hopefully in a few days.)

**Comment by Flwk** [comment]
> @Mkjafu
> Reopening, so I know to notify you when fixed version submitted to Chrome and Firefox stores. (Hopefully in a few days.)
I'm on the last version (0.0.0.130) from GDrive
When i try a [novel](https://activetranslations.xyz/never-die-extra/), i have this error : 

```
TypeError: Cannot read property 'querySelectorAll' of null
    at Object.removeChildElementsMatchingCss (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Util.js:184:37)
    at ActiveTranslationsParser.findContent (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/parsers/ActiveTranslationsParser.js:17:14)
    at ActiveTranslationsParser.findCoverImageUrl (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:152:32)
    at ActiveTranslationsParser.populateUI (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:143:29)
    at processInitialHtml (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/main.js:45:24)
    at populateControlsWithDom (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/main.js:221:9)
    at onMessageListener (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/main.js:16:13)

```

**Comment by dteviot** [comment]
OK, I think I've fixed that.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
```
TypeError: Cannot read property 'querySelector' of null
    at ActiveTranslationsParser.unscrambleText (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/parsers/ActiveTranslationsParser.js:36:29)
    at ActiveTranslationsParser.removeUnusedElementsToReduceMemoryConsumption (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/parsers/ActiveTranslationsParser.js:32:14)
    at chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:491:24
    at async Promise.all (index 0)
```

it seems there is a new error

**Comment by dteviot** [comment]
@Flwk

Looks like some chapters have a different style for the content element.  ".entry-content-container", instead of ".entry-content".

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
When i try it, i don't work. 

[Here ](https://files.catbox.moe/9q4w12.epub) is the epub that i get. 
It's like it stop before downloading any chapter.

**Comment by dteviot** [comment]
@Flwk
I'm not sure it's WebToEpub.  Now when I try to visit the ActuveTranslations site I'm getting HTTP 403 (You don't have authorization to view this page.) errors.  Even if I try opening the pages in a browser.  Note, you can check if WebToEpub has the same problem by looking at Chrome's network traffic.  Basic steps are
1. After opening WebTopEpub
2. Open Chrome's developer tools
3. Go to Network tab
4. On WebToEpub, click "Pack Epub" button

More details: https://developer.chrome.com/docs/devtools/network/

**Comment by Flwk** [comment]
Hello

When i try, with the network tab, the response of the request is good  

![image](https://user-images.githubusercontent.com/3245665/113775592-3abf4900-9729-11eb-9e86-84b0ec2acf5c.png)

Like you can see in the console, it get the html page, but it stop directly after that and send the epub that i linked before

**Comment by dteviot** [comment]
@Flwk 
That's showing chapter 2.  I'm going to assume you've got multiple chapters selected to fetch, and to fetch multiple chapters at once.
What happens if you just try to get the 1st chapter and no others?  Because that did work for me.

**Comment by Flwk** [comment]
> @Flwk
> That's showing chapter 2. I'm going to assume you've got multiple chapters selected to fetch, and to fetch multiple chapters at once.
> What happens if you just try to get the 1st chapter and no others? Because that did work for me.

If i try from chapter 1, i get this error : 

```
TypeError: Cannot read property 'querySelector' of null
    at ActiveTranslationsParser.unscrambleText (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/parsers/ActiveTranslationsParser.js:39:29)
    at ActiveTranslationsParser.removeUnusedElementsToReduceMemoryConsumption (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/parsers/ActiveTranslationsParser.js:35:14)
    at chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:491:24
    at async Promise.all (index 0)
```

This [epub ](https://youdieifyou.work/files/btkihvddsmqc.epub)file and in the network console : 

![image](https://user-images.githubusercontent.com/3245665/113783076-7b23c480-9733-11eb-9fd8-feaa3f01d912.png)

So i don't really know where is the problem.  I can access the novel from chrome with no problems.

**Comment by dteviot** [comment]
@Flwk
That looks exactly like the error I thought I'd fixed.
Perhaps I did not upload the correct version to Google drive.
I'll check and get back to you.  (Currently at work.)

**Comment by dteviot** [comment]
@Flwk
Looks like I did upload the new version, and the line numbers in the error message you posted suggest you are using the new version.
So, I'm guessing the format has changed yet again.  Can you send me a copy of the response you're getting for chapter 1.  Steps: 1. On network tab, right click on the chapter 1 row and then select "Save as..."
2. Attach the file to this issue.

Also, do any other stories work?  e.g. https://activetranslations.xyz/never-die-extra/

**Comment by dteviot** [comment]
@Flwk
Never mind, was able to get into site again, and yes, it's changed.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, I'm not sure how long it will be before site changes again.

**Comment by Flwk** [comment]
Thank you very much !

**Comment by Flwk** [comment]
SOrry for the double post : 

Here is another error  : 

```
TypeError: this.getCancelButtonText is not a function
    at FetchErrorHandler.promptUserForRetry (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/HttpClient.js:52:32)
    at FetchErrorHandler.onResponseError (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/HttpClient.js:44:25)
    at Function.checkResponseAndGetData (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/HttpClient.js:162:45)
    at chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/HttpClient.js:156:31
    at async ActiveTranslationsParser.fetchChapter (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:530:17)
    at async Promise.all (index 0)
```

Well, if it's too much, don't worry about it.

**Comment by dteviot** [comment]
@Flwk 
That's definitely a bug.  Kind of surprised it hasn't been brought to my attention before now.

**Comment by dteviot** [comment]
@Flwk

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Mkjafu 
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
