### ISSUE TITLE
Add site:fimfiction.net

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#502]
would like to download from fimfiction here is the link to the first chapter.
https://www.fimfiction.net/story/477536/1/cinematic-adventures-corpse-bride/to-the-rescue

**Comment by dteviot** [comment]
@kolbdog3333 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by kolbdog3333** [comment]
there are dashes after every word

**Comment by dteviot** [comment]
@kolbdog3333
> there is no word count or amount of likes or dislikes

Why do you think there should be?
Incidentally, where is the word count?

**Comment by dteviot** [comment]
@kolbdog3333
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by kolbdog3333** [comment]
For this site like to change main url so can get more metadata info. Like wordcount, likes and dislikes excetra,
https://www.fimfiction.net/story/137415/the-dragon-and-the-force
