### ISSUE TITLE
 https://hostednovel.com/

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#503]
Hello

The website  https://hostednovel.com/ doesn't work anymore : 

![image](https://user-images.githubusercontent.com/3245665/113498455-52ba8100-950d-11eb-9ebb-515f2d2bb521.png)

Maybe it did change

Thanks in advance

**Comment by dteviot** [comment]
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
Thanks, it worked fine ! :)

**Comment by dteviot** [comment]
@Flwk
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
