### ISSUE TITLE
Is there a way to change the style of the chapter name specifically in the stylesheet?

### ISSUE THREAD

**Issue by Madrauk** [dteviot/WebToEpub#504]
For some websites, Scribblehub in this case, the format of the chapter name is left to the whims of the author. This means that frequently the chapter name is left as para 01 or para 03 instead of heading 1, which makes it quite difficult to track all of them down when converting to a different format.

With that said, what I want to know is there any way to target the chapter name in the stylesheet? A different font, font size, or a way to directly force it to be h1 would make it much easier to locate. If not, an option to force chapter names to h1 would be greatly appreciated.

Here's a link to an example novel that has this issue:
https://www.scribblehub.com/series/221239/returning-transcendent-opens-an-idol-agency/

**Comment by dteviot** [comment]
@Madrauk 
 
My apologies.  I believe I've fixed the issue with scribblehub.  Chapter titles should now be &lt:h1&gt; elements.
Please let me know if there are other sites that are a problem

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Madrauk
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
