### ISSUE TITLE
Literotica stories summary/introduction 

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#507]
As the title says the summary or introduction, category, ratings and date of the stories should be included in a page with something like a table of contents similar to this style included the tags inside the story
![Screenshot_20210413_221937](https://user-images.githubusercontent.com/81566249/114569821-e3c8ef00-9ca7-11eb-88f8-b81c2f7bc952.jpg)

**Comment by gamebeaker** [comment]
@Forgeword a few links would be nice like where you got it from or an example with a link

**Comment by Forgeword** [comment]
@gamebeaker I don't if this helps https://www.literotica.com/stories/memberpage.php?uid=5672828&page=submissions

**Comment by gamebeaker** [comment]
@Forgeword 
As far as i know it isn't Implemented in epub to write chapter information. I don't know a viewer wich would be able to show this information because it isn't Implemented. That's why i think what you want isn't possible. 
Or did you mean something different?

**Comment by dteviot** [comment]
@Forgeword

As @gamebeaker said, doing that was never implemented in WebToEpub.
However, I've committed a patch that might do something close to what you want. However, it will require a bit of manual work on your part.
The basic idea is, you'll need to add the page with the Table of Content details to the list of chapters to fetch.  Then, when the epub is created, it will have that as the first page.

Steps to add an additional page to fetch
1. Click the "Edit Chapter URLs" button.
2. Add a hyperlink entry for the Table of Contents page to the start of the list.  e.g for the link you provided, you'd add
```HTML
<a href="https://www.literotica.com/stories/memberpage.php?uid=5672828&amp;page=submissions">Table of Contents</a>
```
3. Click "Apply Changes" button
4. Click the "Pack Epub" button.

Note, on the Table of Contents, the link to the topmost chapter in the table will be missing.  (Sorry, can't do much about that, it's being culled by the "next/previous" page link logic.)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Forgeword** [comment]
@dteviot @gamebeaker Thank you!

**Comment by dteviot** [comment]
@Forgeword @gamebeaker 
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
