### ISSUE TITLE
How to delete lightnovelpub.com markers?

### ISSUE THREAD

**Issue by Ketboga** [dteviot/WebToEpub#508]
Hi, as you know https://www.lightnovelworld.com/ became lightnovelpub.com recently and before that, I opened an issue here https://github.com/dteviot/WebToEpub/issues/475

In version 127 the marker issue was resolved, but since the website has changed, those markers started appearing again in light novelpub.com

Could you again implement this feature? thank you for your efforts :)

**Comment by dteviot** [comment]
@Ketboga 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Ketboga** [comment]
Thank you again, it works flawlessly.

**Comment by dteviot** [comment]
@Ketboga
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
