### ISSUE TITLE
Max web pages to fetch simultaneously change while packing epub

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#509]
Is it possible to make it so that while packing epub? Max page fetch can be changed even though it has already started.
Example:it has already started but I want to change the 8 max page fetch to 2 cause of slow Internet there should be a button to set it after I changed it from 8 to 2 so that I or something don't actually accidentally change it from 2 to 8

**Comment by gamebeaker** [comment]
@Forgeword 
you can change "Manual Throttle|Delay per chapter" while downloading and do the math.
Example: 8 fetch sim. ; 3sec/chap. = 2,7 chapter per second. 
But i think that it requests 8 simultaneously and after it got all requests it waits 3 seconds.

**Comment by Forgeword** [comment]
@gamebeaker even though there's a delay that would be a 3 sec delay every 8 chapters or 2 depending on max page fetch

**Comment by dteviot** [comment]
Question for @Forgeword
What are you trying to achieve by doing this?
If site is slow to respond, I usually like to try fetching as many pages at once as possible.
Or is your problem sites that do throttling/rate limiting?

Note to self.
Looks like might be doable.  
Changing fetchWebPages() in Parser.js to use async/await would probably be necessary, but I suspect it would also make the code simpler.

**Comment by Forgeword** [comment]
@dteviot imagine having an Internet speed that all of a sudden just maxs at most 11k/s and at least an unholy 65 bytes per second for days

**Comment by dteviot** [comment]
@Forgeword
I don't need to imagine them.  
I had them for many years.

**Comment by Forgeword** [comment]
@dteviot oof though is it possible

**Comment by gamebeaker** [comment]
@Forgeword 
maybe you have a friend with a nice connection and you are able to place an raspberry pi by him. You can log into your raspberry pi via vnc (with an account via the cloud) and than start the download on the raspberry pi with the good connection after the download you upload the file to your cloud or send it yourself via email and you can download the whole epub and don't have to request so many sites. Maybe this would improve your download speed because it is only one file and the file size is smaller than all requests together.

**Comment by dteviot** [comment]
@Forgeword
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Forgeword
Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
