### ISSUE TITLE
Skips chapters when I start it again

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#511]
There are times where it fails cause the Internet  signal both wifi and mobile data here is so retarded that it outright just stop suddenly and I have to wait for it to come back a few seconds later but when I started again it skips from 1 to 8 (depends on max page fetch) chapters where it failed last time (Note:I never closed the tab and started all over again cause the url search is very time consuming cause again Internet signal sucks)

**Comment by dteviot** [comment]
@Forgeword
I think you'll find the chapters that failed were unselected.  
Under failure conditions that cause WebToEpub to halt, it assume the pages don't exist and so removes them from the list to fetch.
So, just check the list and re-select them if they've been removed.

**Comment by Forgeword** [comment]
@dteviot problem solved by unselecting and selecting
