### ISSUE TITLE
Please add site https://www.novelpassion.com/

### ISSUE THREAD

**Issue by credulous2skeptic** [dteviot/WebToEpub#512]
https://www.novelpassion.com/

**Comment by credulous2skeptic** [comment]
Thank you.

**Comment by dteviot** [comment]
@credulous2skeptic
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by credulous2skeptic** [comment]
I'll check and let you know.

**Comment by credulous2skeptic** [comment]
I tried two novels. It works. Thank you.

**Comment by dteviot** [comment]
@credulous2skeptic
Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
