### ISSUE TITLE
ReadLightNovel has junk in epub

### ISSUE THREAD

**Issue by Mathnerd314** [dteviot/WebToEpub#514]
"Sponsored content" inserts and the "text to speech player is currently unavailable" message are included in the EPUB, it would be nice if they were filtered out automatically or if there was some UI feature to manually filter out elements. (It looks like the default parser has such a textbox, but ReadLightNovel doesn't use the default parser)

1. Go to https://www.readlightnovel.org/above-your-head
2. Click on WebToEPub
3. Filter chapters to just a few to speed it up
4. Pack the epub

**Expected behavior**
"Sponsored content" inserts and the "text to speech player is currently unavailable" message are filtered out.

**Screenshots**
![image](https://user-images.githubusercontent.com/322214/116140719-f6262e00-a694-11eb-94c7-f0386684f378.png)
![image](https://user-images.githubusercontent.com/322214/116140759-01795980-a695-11eb-90ca-bcbcc859f9af.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 88

**Comment by dteviot** [comment]
@Mathnerd314 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Mathnerd314** [comment]
The instructions are out-of-date for firefox, should be something like:
1. Download the extension (no need to unpack)
2. Open Firefox and type "about:debugging" into the URL bar.
3. Close the "Tabs" list and click "Load Temporary Add-on".
4. Select the extension zip or manifest.json file

Anyways, it's better, but there's still extra linebreaks and horizontal rules. The HR's are pretty annnoying.

Looking at [lightnovel](https://www.readlightnovel.org/yume-miru-danshi-wa-genjitsushugisha/chapter-1) vs [the original](https://kinokuratrans.com/2020/10/04/yumemiru-danshi-wa-genjitsu-shugisha-ch-1/), things inserted include:
* br, Chapter X, br (at the beginning)
* br , br, center > adsbyvli, br, br, hr
* center > {script, div#ee88c893-0e49-4cfa-ba8e-37dfdd83dab8}, hr
* br, small.ads-title, br, center, hr
* center > {div#rc-widget-602cb5, script} at the end

I made a PR that removes all of these: https://github.com/dteviot/WebToEpub/pull/516

**Comment by dteviot** [comment]
@Mathnerd314 
Thanks for the PR.

There were a few small issues, which I think I've fixed.  See commit https://github.com/dteviot/WebToEpub/commit/9ff493a76c1934d010c4db94bba615aa18fab347

**Comment by Mathnerd314** [comment]
> Goggle dislikes calling console.log() in extensions

Really? Weird. I've never had any trouble in Firefox. Maybe the right thing to do is to throw an exception. I think it's better to break than to produce an EPUB with junk in it.

> Doesn't work for Chapter 1 of https://www.readlightnovel.org/i-became-the-demon-lord-so-i-created-a-dungeon-and-spend-heartwarming-time-there-with-non-human-girls

The issue here is that a `<center>` can't be in a `<p>`, so it gets parsed as malformed HTML.
```HTML
 <p> [...] <br>HP: 2100/2100<br> <br><small class="ads-title">[...]</small><br>
   <center> [...]</center> <hr>
   MP: 6700/6700<br> [...]
</p>
```
gets parsed as
```HTML
<p> [...] HP: 2100/2100 [...] <small [...]> <br> </p> <!-- note closing p -->
<center [...]> <hr>
MP: 6700/6700 <br> [...]
<p></p> <!-- note empty paragraph -->
```

The "right" solution is probably to use regexes on the unparsed source, or to avoid these terrible aggregator sites altogether. I don't think there's an easy way to fix the HTML once it gets broken. But we can at least remove all the elements properly: https://github.com/dteviot/WebToEpub/pull/517

**Comment by dteviot** [comment]
@Mathnerd314 
{quote}
Goggle dislikes calling console.log() in extensions
{quote}

You misunderstood.  I'm taking about Google's validating process for extensions, not Chrome.
{quote}
The "right" solution is probably to use regexes on the unparsed source,
{quote}

In my experience, that's never the right solution.  I keep on finding edge cases that the regex doesn't work for.

**Comment by dteviot** [comment]
@Mathnerd314
>  I think it's better to break than to produce an EPUB with junk in it.

I disagree.  I think most users would rather have an epub (even if it's messy) than no epub.
Also, once the epub has been created, it can be cleaned up.  See: https://github.com/dteviot/EpubEditor, https://github.com/dteviot/MergeWebToEpub

**Comment by Mathnerd314** [comment]
Well, if not a regex, then some forgiving parser along the lines of https://github.com/fb55/htmlparser2/. The issue is really that the browser's parser is too smart. But it would require changing all of the CSS selectors to use a CSS library reimplementation, so it'd be a pain.

**Comment by dteviot** [comment]
@Mathnerd314 
Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by Mathnerd314** [comment]
I'm on Firefox and it works so I consider it fixed. You can reopen it if you want. There seem to be a lot of open issues that I would consider resolved. (#191, #383, #444, #279)
