### ISSUE TITLE
RoyalRoad missing chapter names

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#52]
I notices stuff grabbed from RoyalRoad is missing chapter names.
Check "http://royalroadl.com/fiction/1233".
It happened after the removing of the "Try the beta reader" line (sonako 16/07/2016).

At the end of the chapter(s) there is an incomplete link to the next chapter on RoyalRoad web (arrow thing), maybe that should be removed too.

**Comment by dteviot** [comment]
@typhoon71
Firstly, thanks very much for the feedback.

> I notices stuff grabbed from RoyalRoad is missing chapter names.

The RoyalRoad parser has never included the chapter names.
They're not in the same <div> that holds the rest of the story, so I've ignored them.  But I can probably add the chapter title.

> At the end of the chapter(s) there is an incomplete link to the next chapter on RoyalRoad web (arrow thing), maybe that should be removed too.

Tricky.  As it's just a link and text, it's not easy to figure out exactly what needs to be removed.

**Comment by dteviot** [comment]
@typhoon71 Latest commit, chapter titles are now added, and I clean up more of the old next/previous chapter links.  (note, not doing it for first/last chapter because it's different.

**Comment by typhoon71** [comment]
Great, like this it's much better. Thanks a lot.
There's still some leftover after the first chapter ("-->"), but it's only after the first one, the rest is fine, and it's easy to clean it manuallly (sigil).

Btw, after the "line" at the end of the chapter there's a new line with a space, but it seem to cause blank pages if this line with a space doesn't fit in the page. 
It happens in calibre but not in sumatra, maybe different rendering.

**Comment by dteviot** [comment]
@typhoon71
> There's still some leftover after the first chapter ("-->")

Thanks, I was aware of that.  That's why I said "not doing it for first/last chapter...".  Basically, I'm having to search for text strings which runs the risk of deleting stuff I shouldn't.  The <--> is fairly distinctive and occurs on every chapter (so removing it is a pain.)  So I thought risk/reward for removing it was enough to justify.  The "-->" is less distinctive and it only occurs on first chapter.  So I'm leaving it.

> Btw, after the "line" at the end of the chapter there's a new line with a space, but it seem to cause blank pages if this line with a space doesn't fit in the page.

I did not notice that.  I might be able to clean up any trailing blank elements using similar technique to Baka-Tsuki.

**Comment by belldandu** [comment]
@dteviot i suggest using `\s` instead of `\t\n\r` for whitespace checks, as `\s` encompasses all forms of whitespace.

**Comment by dteviot** [comment]
@belldandu
I assume you're referring to util.isStringWhiteSpace().
If you follow the link to https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace_in_the_DOM
there's a comment
>  This does not use Javascript's "\s" because that includes non-breaking spaces (and also some other characters).

Given this, I'm not sure what the correct rule is.

**Comment by dteviot** [comment]
@typhoon71 

>> Btw, after the "line" at the end of the chapter there's a new line with a space, but it seem to cause blank pages if this line with a space doesn't fit in the page.

Latest commit to Sonako branch should remove trailing space from end of each chapter.

**Comment by typhoon71** [comment]
Great, it removes the black line too. Well done.
No problem leaving the leftovers after the first chapter, it takes like 10s to fix it manually.
Btw, how is the title formatted when it comes from RoyalRoad?
I get a really big spacing in calibre, is it moddable in the css (advanced section)?

**Comment by dteviot** [comment]
@typhoon71 
> Btw, how is the title formatted when it comes from RoyalRoad?

It's not.  I have to go dig the text out of &tl;div&gt; it's buried in.  I then wrap it in a &tl;h2&gt; tag.
So, you could modify the &tl;h2&gt; in the ccs.  Or I could use a  &tl;h3&gt; or &tl;h4&gt; tag if you prefer.

**Comment by typhoon71** [comment]
I prefer <h2> being modded in the addon to <h3> or <h4> , the one that seems more natural; you culd also just add a white line after the title and use the same format as the text.

**Comment by typhoon71** [comment]
I prefer <h2> being modded in the addon to <h3> or <h4> , the one that seems more natural; you culd also just add a white line after the title and use the same format as the text.

**Comment by typhoon71** [comment]
I prefer it being modded in the addon, with the option that seems more natural; you could also just add a white line after the title and use the same format as the text.

**Comment by belldandu** [comment]
@dteviot Just noticed you did it a bit differently (which works a little better then my method).

**Comment by dteviot** [comment]
I think this is now OK, so closing.
