### ISSUE TITLE
Please add this site: https://m.tapas.io

### ISSUE THREAD

**Issue by Raeyraey** [dteviot/WebToEpub#522]
https://m.tapas.io

**Comment by dteviot** [comment]
@Raeyraey
I'm still looking at doing this, it's just going to take a while.

**Comment by Raeyraey** [comment]
Oh no worries! I just found an alternative way so I closed it. And it seems that it will take more time but if ya still want to add it then I'll gladly accept it. Thank you so much!

**Comment by Raeyraey** [comment]
Hello, sorry for the late reply. It's from Novel Grabber but it only works on pc/laptop and requires the installation of a java.

**Comment by dteviot** [comment]
@Raeyraey 
That's fine, looking at the code it uses for tapas https://github.com/Flameish/Novel-Grabber/blob/master/src/main/java/grabber/sources/tapas_io.java tells me how to do most of the work.
Much easier than trying to figure it out myself.

**Comment by dteviot** [comment]
@Raeyraey
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, I've tested it works on the desktop site: https://tapas.io, but I haven't checked the mobile version https://m.tapas.io

**Comment by dteviot** [comment]
@Raeyraey
Updated version (0.0.0.133) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
