### ISSUE TITLE
69shu.com Parser Broken

### ISSUE THREAD

**Issue by Hogesyx** [dteviot/WebToEpub#526]
**Describe the bug**
The style sheet of 69shu has changed and the current parser has stop working due to href handling.

**To Reproduce**
1. Go to any 69shu novel page
2. Attempt to parse
2. ShuParser.getChapterUrls (error at 69shuParser.js:12:52)

**Comment by dteviot** [comment]
@Hogesyx
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Hogesyx
Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Hogesyx** [comment]
> @Hogesyx
> Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
> Firefox version is available now.
> Chrome might be available in 1 to 3 weeks.
> If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

@dteviot , tested with a couple of different books and it is working well.
