### ISSUE TITLE
Please add site https://www.mtnovel.net/

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#527]
Page of contents - https://www.mtnovel.net/index/5724/
I'm very sorry for any inconvenience

**Comment by dteviot** [comment]
@Forgeword 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes

FYI.  That was not fun.  It had 2 complications:
1. Table of contents was spread across multiple pages
2. Many chapters were spread across multiple pages.

And took nearly 2 hours to do.

**Comment by dteviot** [comment]
@Forgeword
I tweaked the parser for https://www.mtnovel.net, to remove the "Back to top" links from joined chapters.
Test versions on Google drive have been updated.

**Comment by dteviot** [comment]
@Forgeword
Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
