### ISSUE TITLE
Help! Kiwi browser how to install source extension

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#528]
I don't know how to install from source using kiwi browser for android if anyone know anything thank you if it's not possible I'll will close this issue

**Comment by Tetdesu** [comment]
Download the file from the gdrive then open extensions. Make sure developer mode is turned on. Then load the file

**Comment by Tetdesu** [comment]
Kiwi is a little buggy thou. So sometimes the new parser may not work using kiwi but on pc it does.
Tried it with my prev request.

**Comment by Forgeword** [comment]
@Tetdesu does not work already tried that and the chrome install instruction
