### ISSUE TITLE
Epub saved with weird filename

### ISSUE THREAD

**Issue by Helixos** [dteviot/WebToEpub#531]
**Describe the bug**
the title of the epub become weird
**To Reproduce**
I haven't changed anything as usual and I tested it on several sites (royalroad or novel translate for example) and the problem persists
**Screenshots**
![image](https://user-images.githubusercontent.com/74857074/117586845-07524e80-b11b-11eb-9471-dc0ce163b722.png)
**Desktop (please complete the following information):**
- OS: I use a Pc Acer Nitro 5 with window
- Browser : chrome

**Comment by gamebeaker** [comment]
@Helixos 
Hi i tried to replicate it but wasn't able to.
Please disable all other add-ons and download it again.
Hope this fixes the problem.

**Comment by dteviot** [comment]
@Helixos, as suggested by @gamebeaker, the most likely cause is a conflict between WebToEpub and another Chrome extension.
Easiest way to confirm, disable the other extensions and try running WebToEpub again.

**Comment by Helixos** [comment]
yes you where right it was the image downloader addon ( https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj/related )
thanks for the help 👍

**Comment by dteviot** [comment]
@Helixos
Do nothing.  I'll close it.
