### ISSUE TITLE
Please add site https://bnatranslations.com

### ISSUE THREAD

**Issue by pavan3999** [dteviot/WebToEpub#532]
https://bnatranslations.com

**Comment by dteviot** [comment]
@pavan3999 
Updated version (0.0.0.131) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Notes:
1. This took about two hours to do.  Problem is pages at site don't have consistent format.
2. Some of the links in the ToC don't go to chapters, they go to announcements that have a link to the actual chapter.   WebToEpub does NOT do link chasing for them.
3. Works for https://bnatranslations.com/an-a-ranked-adventurers-slow-living/, I did't try anything else.
