### ISSUE TITLE
Help regarding chapter list

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#535]
**Describe the bug**
THe chapter list is jumbled such; chapter 1, chapter 5, chapter 2, chapter 6

**To Reproduce**
1. Go to 'taffygirl13.wordpress.com/yu-brothers-case-book/'
2. Click on 'WebToEpub Extension button'
3. Scroll down to 'Chapter list'
4. See error - the chapter list are jumbled

**Expected behavior**
I expected the chapter list to be like every other site - in chronology.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser = Chrome
 - Version [90.0.4430.212]
![Screenshot 2021-05-19 125540](https://user-images.githubusercontent.com/67751123/118780049-60547c00-b8ab-11eb-8e08-a44b8764a03a.jpg)

**Comment by dteviot** [comment]
@sigmatc
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Notes for my records.  
Took 30 minutes to handle the URL layout.  For 2 stories.  Others were normal.
