### ISSUE TITLE
WebtoEpub saves the compressed image from wattpad 

### ISSUE THREAD

**Issue by rosmontis2154** [dteviot/WebToEpub#536]
**Describe the bug**
i am unable to save the full res images from wattpad

**To Reproduce**
1. Go to any story with images such as
https://www.wattpad.com/962979949
https://www.wattpad.com/story/239507318

2. Click on WebtoEpub
3. Click pack epub
4. It saves the low res images

**Expected behavior**
to download the full images instead of the compressed version

**Desktop (please complete the following information):**
 - OS: win10
 - Browser firefox
 - Version 88.0.1

**Additional context**
image links has ?s=fit&w=720&h=720 at the end, which when removed will link to the full image

**Comment by dteviot** [comment]
@rosmontis2154 
Test versions for Firefox (and Chrome) have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by rosmontis2154** [comment]
Thank you, it gets the full size images now.
For my firefox 88.0.1 i had to access temporary addons from "about:debugging#/runtime/this-firefox" instead of of "about:addons" mention from your instructions.
Other than that everything went nice and simple. Thanks again.

**Comment by dteviot** [comment]
Reopened, so I know to tell you when the copy in Mozilla store has been updated.

**Comment by dteviot** [comment]
@rosmontis2154
Updated version (0.0.0.133) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
