### ISSUE TITLE
Cannot catch chapters. HELP!

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#537]
https://www.lightnovelupdates.com/

After clicking "Pack EPUB" it ends immediately

says this "TypeError: Cannot read property 'querySelectorAll' of null"

**Comment by dteviot** [comment]
That's an unusual site.
I tried two stories. https://www.lightnovelupdates.com/novel/tearmoon-empire-story/ and
https://www.lightnovelupdates.com/novel/it-turns-out-i-am-a-dao-ancestor/
The chapters in the ToC appear to redirect to the original web sites hosting the stories.
e.g. tearmoon c1 redirects to https://pawprinttranslations.blogspot.com/2021/05/Volume-1-Chapter-38.html.
WebToEpub can't handle this. 
However, if you go to the ToC on the original site, it works fine.

**Comment by sigmatc** [comment]
Thanks
