### ISSUE TITLE
Please add site https://goblinsguide.com/

### ISSUE THREAD

**Issue by azmuni234** [dteviot/WebToEpub#538]
I wonder if its possie for you to add https://goblinsguide.com/

**Comment by dteviot** [comment]
@azmuni234 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes:
Required some complicated logic to format Ajax calls to get the ToC pages.
Total time: about 2 hours.

**Comment by azmuni234** [comment]
@dteviot 
My first download goes alright but the few early chapters are out of order but somehow i managed to find the first chapter. I'll see how it goes on my other downloads first.

**Comment by azmuni234** [comment]
@dteviot Second download still out of order.

**Comment by dteviot** [comment]
@azmuni234
URLs for stories that are out of order?

**Comment by azmuni234** [comment]
@dteviot https://goblinsguide.com/god-level-demon/god-level-demon-light-novel/

Chapter 1 is at Chapter 2511 in epub

**Comment by dteviot** [comment]
@azmuni234 
It's not a problem with WebToEpub, it's a problem with the site itself.
The table of content's links are scrambled.
For example, If you try clicking on link titled "Chapter 1" link, it takes you to chapter 22.
Likewise, the "Chapter 2" link takes you to chapter 26.
I sent an email to the site's contact address (diasasx@gmail.com) informing him/them of this.  But you might like to do the same.

**Comment by dteviot** [comment]
@azmuni234
Updated version (0.0.0.133) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

Also site owners have emailed me to say they will fix god-level-demon
