### ISSUE TITLE
Emoticons on Spacebattles stories halt download

### ISSUE THREAD

**Issue by AVolkoff6** [dteviot/WebToEpub#539]
**Describe the bug**
From what I can tell, any Spacebattles story that contains an emoticon of some sort halts the download once it reaches the emoticon, and 
**To Reproduce**
1. Go to 'https://forums.spacebattles.com/threads/the-warcrafter.803647/reader/'
2. Download story with plugin

**Expected behavior**
The story downloading completely

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.0.0.131

**Additional context**
Error message;
URL constructor: /styles/sbforums/smilies/wink.gif is not a valid URL. removeSizeParamsFromWordPressQuery@moz-extension://fadd74a2-911e-48e4-9189-45fe8cb7a2a6/js/ImageCollector.js:411:19
initialUrlToTry@moz-extension://fadd74a2-911e-48e4-9189-45fe8cb7a2a6/js/ImageCollector.js:399:31
fetchImage@moz-extension://fadd74a2-911e-48e4-9189-45fe8cb7a2a6/js/ImageCollector.js:334:31
fetchImages/temp</<@moz-extension://fadd74a2-911e-48e4-9189-45fe8cb7a2a6/js/ImageCollector.js:108:29

**Comment by AVolkoff6** [comment]
I just opened a Pull Request with a fix for this one.

**Comment by dteviot** [comment]
@AVolkoff6
Thanks, but I chose a different way to fix.  Refer above commit.

**Comment by AVolkoff6** [comment]
Thanks! I really appreciate the addon.

**Comment by dteviot** [comment]
@AVolkoff6 
Updated version (0.0.0.133) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
