### ISSUE TITLE
(Firefox & Chromium) Content script does not return sometimes

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#54]
Observed on Firefox:
If target web page is in process of loading, the content script that is injected into the web page does not return.
I suspect it's waiting for whole page to load before it can obtain the pages content, which it returns.

**Comment by belldandu** [comment]
This is actually an easy fix. All we have to do is check the state of the page (more of a cosmetic thing really) and tell the user to wait for the page to finish loading before trying again if its still loading.

**Comment by belldandu** [comment]
@dteviot 
```
if(document.readyState !== "complete") {
        alert("Page has not finished loading, Execution of WebToEpub has halted.");
        // Some function that kills the execution
}else{
        // Do some code here to continue the execution
}
```

Above is an example.

**Comment by dteviot** [comment]
@belldandu
I do need to confirm the problem is what I think it is.
But thanks for the code.

**Comment by belldandu** [comment]
The Same also occurs in chromium as well @dteviot

**Comment by belldandu** [comment]
I should Also not that since chromium is a derivative of chrome that most likely this also occurs in chrome as well.

**Comment by dteviot** [comment]
Based on https://developer.chrome.com/extensions/content_scripts, I think the fix is to call chrome.tabs.executeScript() with runAt set to "document_end"

**Comment by dteviot** [comment]
Should now be fixed.
