### ISSUE TITLE
Insight Browser iOS WebtoEpub

### ISSUE THREAD

**Issue by tochmengleang** [dteviot/WebToEpub#542]
There is a new app on iOS called insight Browser, which can use extension.
Please try it out and find a way to inject add webtoepub extension on it if possible please...
Thanks you.![image](https://user-images.githubusercontent.com/13347983/120703075-0b397c80-c4df-11eb-8c01-876b5cdd8544.png)

**Comment by dteviot** [comment]
@tochmengleang
Thank you for your suggestion.
However, after having a look at it https://www.notion.so/How-to-create-and-edit-extensions-b725def4d366499f92bd60c9047cf46d, extensions written for chrome are not compatible with the insight browser.
To get an extension that does something similar to WebToEpub might be possible (depending on just how tightly Apple require these extensions to be limited.) However, it would require writing a completely new extension.  And I don't have the time or interest to do so.
