### ISSUE TITLE
A stop button for searching url

### ISSUE THREAD

**Issue by Forgeword** [dteviot/WebToEpub#543]
A button to stop searching url cause it already has what I need example I downloaded 1000 chapters of super god gene from ranobes.net then because the Internet here is shit which sometimes disconnect for hours or a day I have to do it again and it takes time for the searching url process to finish

**Comment by dteviot** [comment]
@Forgeword
Do you mean 
1. Searching for the list of chapters, or 
2. Fetching the chapters to build the Epub.

That said, given your network is horrible, might I suggest asking someone with a good network to create the EPUB for you, then put it where you can download the epub.  (e.g. Google Drive, Mega)

**Comment by Forgeword** [comment]
Fetching for list of chapter and I'll try if my friends could do that

**Comment by dteviot** [comment]
@Forgeword
Unfortunately, the code to fetch chapters is different for many parsers.
So, to have a stop button that works for every one will require changing many of the parsers.
So, it's a lot of work.  More work than I'm willing to do,

**Comment by Forgeword** [comment]
@dteviot  Alright thank you

**Comment by lalalasupa0** [comment]
Man, I'd fucking love a feature for this; it's a huge pain waiting for it to stop on its own when I only wanna download *some* recent chapters out of thousands

**Comment by dteviot** [comment]
@lalalasupa0 

Have you considered using the library function? https://github.com/dteviot/WebToEpub/wiki/Library

**Comment by lalalasupa0** [comment]
> [@lalalasupa0](https://github.com/lalalasupa0)
> 
> Have you considered using the library function? https://github.com/dteviot/WebToEpub/wiki/Library

Yeah, no luck with that. Not even sure how it works, but I "Library" my last downloaded chapters and it just started loading the same way later on; "Library" the *whole* series is counter-productive, or at least I think so—thus I didn't try that
