### ISSUE TITLE
Add site? https://www.alternatehistory.com/

### ISSUE THREAD

**Issue by Mildewus** [dteviot/WebToEpub#544]
I've attempted to add it myself, but i don't really know what I'm doing.

Here is a list of chapters
https://www.alternatehistory.com/forum/threads/the-war-of-73-a-tng-ds9-era-au.500510/threadmarks

This is an example of a chapter
https://www.alternatehistory.com/forum/threads/the-war-of-73-a-tng-ds9-era-au.500510/#post-21323692

**Comment by dteviot** [comment]
@Mildewus
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Notes:
1. Site seems to use same layout as Spacebattles.com
2. To get list of chapters, you need to be viewing the set of all threadmarks.  (e.g. https://www.alternatehistory.com/forum/threads/the-forge-of-weyland.500829/threadmarks)
3. For my records, work was negligible.

**Comment by Mildewus** [comment]
Works perfectly, thank you!

**Comment by dteviot** [comment]
@Mildewus
Updated version (0.0.0.133) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
