### ISSUE TITLE
Please add site ?https://www.volarenovels.com/

### ISSUE THREAD

**Issue by pavan3999** [dteviot/WebToEpub#545]
https://www.volarenovels.com/

**Comment by dteviot** [comment]
@pavan3999
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

From the looks of https://github.com/pavan3999, you seem to be a developer.  Why didn't you at least TRY to use the default parser?

For my notes: 30 minutes to write parser.

**Comment by dteviot** [comment]
@pavan3999
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
