### ISSUE TITLE
Download spoiler content in SpaceBattles and Sufficient Velocity

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#547]
SpaceBattles and Sufficient Velocity often has spoiler content in the post but it's not downloaded.
examples:
https://forums.sufficientvelocity.com/threads/wiki-warrior.64766/
https://forums.spacebattles.com/threads/sotsog-worm-celestial-forge.930385/#post-75361042
please fix this.
right now I'm using fichub.net to download from there instead, but that place has their own problem. I'd like to use this one instead.

**Comment by dteviot** [comment]
@SpiralBaka
Updated WebToEpub includes the spoilers in viewable form.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, I think it looks something of a mess, as it's not possible to make the spoilers show/hide on a click with Epub v 2.

**Comment by SpiralBaka** [comment]
Ok. it works just fine for the most part. but there's one problem I encountered.
Path to Munchies (complete) - Part 7: Path to Cinnamon Rolls
https://forums.sufficientvelocity.com/threads/path-to-munchies-complete.37382/#post-8266718
there are three blank spoiler tag. it turns out it contains images. the images itself is downloaded properly, but the one that's shown is a blank image.
not being able to toggle spoiler is just fine. or rather, it's better that way.
however, if you can make spoiler tag into a box (like a table/container) or something, that would be best, but if it's hard then it's fine to not do it. I'd like to be able differentiate what's inside the spoiler and what's not when reading.

**Comment by dteviot** [comment]
@SpiralBaka

1. Should now fetch the images. 
2. I'm not going to put spoilers in boxes.  Too much effort.  Well, probably not a lot of effort.  They've got a style, so should just be a matter of updating the style sheet under the Advanced Options, if you want to try.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by SpiralBaka** [comment]
alright. it works. thank you.

**Comment by dteviot** [comment]
@SpiralBaka
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
