### ISSUE TITLE
https://hostednovel.com/

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#549]
![Screenshot 2021-06-11 213836](https://user-images.githubusercontent.com/67751123/121714318-6f6ec880-cafd-11eb-8518-618dab080c65.jpg)

Can't catch chapters.
I think it was fine a long while back ago.....
??

I remember downloading Legend of great sage

**Comment by dteviot** [comment]
@sigmatc 

Table of Content layout changed.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
@dteviot I've downloaded the latest version, but it didn't detect the chapter : 
![image](https://user-images.githubusercontent.com/3245665/122021252-cc040900-cdc5-11eb-89b6-184b6ac68de1.png)

**Comment by dteviot** [comment]
@Flwk @sigmatc
Site seems to have restored layout.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
@dteviot 

Thank you very much !

**Comment by dteviot** [comment]
@Flwk @sigmatc
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
