### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#55]
@Belldandu, @typhoon71, @toshiya44, @dreamer2908

I've added your nicknames to the credits list in the readme.
If you prefer I use your real names, please e-mail me, including your real names as I only know Belldandu's.

**Comment by belldandu** [comment]
@dteviot I don't mind you using my real name in credits although i would prefer you did in like this 
`Real Name (NickName)`

**Comment by dteviot** [comment]
@belldandu, fine with me.

**Comment by typhoon71** [comment]
@dteviot 
Using my nickname is ok.
I don't think I gave github my real name anyway... XD

**Comment by dreamer2908** [comment]
@dteviot 
I'm okay with my nickname.

**Comment by toshiya44** [comment]
I'm trying to be consistent with nicknames. So I'm fine with my nickname too.
