### ISSUE TITLE
Please add site https:quotev.com

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#550]
here is link to one of the fanfics and to main page
https://www.quotev.com/story/13840353/The-Fall-of-the-Soul-Rider
https://www.quotev.com/

**Comment by dteviot** [comment]
@kolbdog3333
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@kolbdog3333
Apologies, I uploaded the wrong test versions.  Correct versions have been uploaded now.

**Comment by dteviot** [comment]
@kolbdog3333
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
