### ISSUE TITLE
Full title error

### ISSUE THREAD

**Issue by itsgraxiabibi** [dteviot/WebToEpub#551]
**Describe the bug**
I noticed today that every time I finish downloading a book, the title (which was correctly filled out before downloading begins) ends up being a bunch of numbers when Im about to click it "save" on its folder destination. I've attached some screenshots. I tried to remove and install the chrome intension and made sure the "Use full title as file name" has been clicked.

**To Reproduce**
Usual process of downloading an ebook. This error only happened today. 

**Expected behavior**
I was expecting it to have the same name as what I put in the title box just like before.

**Screenshots**
Screenshot: https://prnt.sc/16dg49a
Screenshot 2: https://prnt.sc/16dgakb

**Desktop (please complete the following information):**
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dteviot** [comment]
@itsgraxiabibi 
The most likely cause is a conflict between WebToEpub and another Chrome extension.
Easiest way to confirm, disable the other extensions and try running WebToEpub again.

**Comment by dteviot** [comment]
Closing, no response from @itsgraxiabibi
