### ISSUE TITLE
Activetranslations.xyz not working (Domain has changed)

### ISSUE THREAD

**Issue by zerotowin** [dteviot/WebToEpub#552]
**Describe the bug**
Active Translations changed their site and domain to a-t.nu and now the epubs getting generated are scrambled again.

**To Reproduce**
1. Go to https://a-t.nu/novel/never-die-extra/
2. Click on webtoepub
3. Pack the epub
4. Open the resulting epub in an epub reader and see that it's scrambled.

**Additional context**
I tried downloading the latest addon on google drive and editing the ActiveTranslationsParser.js there, replacing the domain to a-t.nu, unfortunately it didn't work. Looks like they also changed the CSS layout.

**Comment by dteviot** [comment]
@zerotowin 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Seemed to work for first chapters of 
* https://a-t.nu/novel/never-die-extra/
* https://a-t.nu/novel/goblin-workshop-in-me/

Notes, 
1. It looks like there are locked chapters (unless you pay) so I'm filtering them out in the function getChapterUrls(). (I don't know what they look like if you've paid for them.)
2. Site claims to still be under construction (see the details tab on the two links above).
3. For my records, this work took 70 minutes

**Comment by zerotowin** [comment]
@dteviot 
I tested it in firefox and it seems to be working fine for the most part. 
I found a couple of chapters that's still getting scrambled though: 

https://a-t.nu/novel/never-die-extra/chapter-168/
https://a-t.nu/novel/demon-king/demon-king/chapter-152/
https://a-t.nu/novel/a-vip-as-soon-as-you-log-in/a-vip-as-soon-as-you-log-in/chapter-250/

All of them starts the chapter with a line enclosed in { } so the problem might be there.

**Comment by dteviot** [comment]
@zerotowin
> All of them starts the chapter with a line enclosed in { } so the problem might be there.

D'oh!  I believe I've found and fixed that problem.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes, elapsed time to fix is now 110 minutes

**Comment by dteviot** [comment]
@zerotowin
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
