### ISSUE TITLE
Please add site https://www.shubaow.net

### ISSUE THREAD

**Issue by dmbada** [dteviot/WebToEpub#555]
could you please add shubaow.net?
this is one of the example of their toc
https://www.shubaow.net/144_144384/

**Comment by dteviot** [comment]
@dmbada
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Please note, I don't know Chinese, so I'm not totally sure I've got it right.

For my notes, 60 minutes work.  (Filtering the ToC links required some effort to eliminate the duplicates.)

**Comment by dteviot** [comment]
@dmbada
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
