### ISSUE TITLE
Add site https://knoxt.space

### ISSUE THREAD

**Issue by jesh78** [dteviot/WebToEpub#557]
Can you please add this site https://knoxt.space ?
And this is the example for the table of contents https://knoxt.space/i-became-popular-after-online-dating-with-a-big-shot/
Thank you so much!

**Comment by dteviot** [comment]
@jesh78

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes - 20 minutes work

**Comment by jesh78** [comment]
Thank you so much for the hardwork! It works perfectly.

**Comment by dteviot** [comment]
@jesh78
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
