### ISSUE TITLE
Please add site https://manganov.com

### ISSUE THREAD

**Issue by Irakiel-El-Navah** [dteviot/WebToEpub#559]
could you please add manganov.com?
this is one of the example of their toc
https://manganov.com/novel/monarch-of-time

**Comment by sigmatc** [comment]
title h2.mt-1
body div.mn-novel-chapter-content-body

**Comment by dteviot** [comment]
@Irakiel-El-Navah, @sigmatc
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.


For my notes - 40 minutes work

**Comment by dteviot** [comment]
@Irakiel-El-Navah, @sigmatc
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
