### ISSUE TITLE
Optionality for whether or not the main file name is concenated or not

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#56]
As the title says this will NOT affect chapter names and image names, it will affect the main epub file name.

I'm thinking of adding this to #14 but i was looking for opinions on whether its a good idea or not.

If implemented concenation will be on by default and users that want it off can turn it off from advanced options.

**Comment by dteviot** [comment]
@belldandu
I'd say it's not necessary, the save file name is presented to the user as an editable control.  If they want to change it, they can change it there.
I think it's more intuitive than having to go into  the advanced options.

**Comment by belldandu** [comment]
Very well will close this then
