### ISSUE TITLE
When editing chapters url, move the button at the end of the page

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#560]
Hello

When i edit the urls of the chapters, and that there is a lot of chapters, I always have to return to the top of the page to "apply the changes".

Is it possible to move the button to the bottom ? Or made it that the list of the urls is limited in size ? 

It's just a little suggestion, not something very important

Best regards,
Flwk

**Comment by dteviot** [comment]
@Flwk
I think I can just add a second "Apply Changes" button to the bottom of the page.

**Comment by dteviot** [comment]
@Flwk
Something like this?
![image](https://user-images.githubusercontent.com/5157081/125606071-dafd8ffe-82a5-43a0-b789-58bbf2d5c094.png)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
@dteviot Yes, thank you very much !

**Comment by dteviot** [comment]
@Flwk
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
