### ISSUE TITLE
Please add site http://www.zeonic-republic.net/

### ISSUE THREAD

**Issue by mink-r** [dteviot/WebToEpub#561]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
_http://www.zeonic-republic.net/?page_id=181_

### Did you try using the Default Parser for the site?  If not, why not?
Yes, it can't seem to find the div id I'm showing

### What settings did you use?  What didn't work?
* URL of first chapter:  _http://www.zeonic-republic.net/?page_id=3749_ [prologue]
_http://www.zeonic-republic.net/?page_id=4313_ [chap-1]
* CSS selector for element holding content to put into EPUB - _entry_
* CSS selector for element holding Title of Chapter - _title_
* CSS selector for element(s) to remove - unsure

**Comment by dteviot** [comment]
@mink-r
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, I'm not sure how good it is.
Seems to work for the Table of Content URL you gave, but other novels seem a bit dodgy.

For my notes: 30 minutes work.

**Comment by mink-r** [comment]
tested, and worked on other novels also. thanks! Also you should put a buy you coffee link or something similar somewhere on the project page.

**Comment by dteviot** [comment]
@mink-r
> you should put a buy you coffee link 

I appreciate the thought, but I'd much rather you donated to the people who write the stories.  Or do the translations.

**Comment by dteviot** [comment]
@mink-r
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
