### ISSUE TITLE
Ranobes only getting first page

### ISSUE THREAD

**Issue by SirGryphin** [dteviot/WebToEpub#562]
It only fetching 25 chapters (first page) instead of all pages of chapters.

Here is the novel link: https://ranobes.net/novels/396653-the-devils-sleeping-beauty.html

 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Latest extension version]

**Comment by dteviot** [comment]
@SirGryphin 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Should be getting all chapters in Table of Contents now.
For my records, time to fix: 30 minutes.

**Comment by SirGryphin** [comment]
Tested on both Chrome and Firefox, everything works fine now. Thank you so much for quick fix.

**Comment by dteviot** [comment]
@SirGryphin 
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
