### ISSUE TITLE
Please add site https://www.asstr.org/files/Collections/Clitorides/

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#563]
chapt list-https://www.asstr.org/files/Collections/Clitorides/  
Chaphttps://www.asstr.org/files/Collections/Clitorides/SCA0107.txt
 So tried doing it myself but failed.

**Comment by dteviot** [comment]
@Dlordload 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: 30 minutes work.

**Comment by dteviot** [comment]
@Dlordload
Updated version (0.0.0.135) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
