### ISSUE TITLE
Feature Request - Apply Google Translate before Downloading

### ISSUE THREAD

**Issue by ammasakshay** [dteviot/WebToEpub#564]
**Is your feature request related to a problem? Please describe.**
I've read most of the available novels and nowadays I tend to spend time on the Webnovel Source sites and use google translate to read them. (Machine Translation)

Most of the time I use https://www.soxscc.net/

I am able to download all the content using the CSS element selector (using .content)

What I want is for the section to be google translated before it is crawled.

**Describe the solution you'd like**

An option to apply google translate per page before crawling, which will be useful especially considering the large number of untranslated books.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/48739144/127100021-60a8d3fd-5845-448c-8ae2-e124fd211d33.png)

This is an example of what I want. Exactly the same as what the program already does, except it crawls the page after google translate has been applied to it.

**Comment by dteviot** [comment]
@ammasakshay
The way WebToEpub works, this isn't really possible.
The way to work would be to fetch the pages, then use Google's API to translate the fetched text.
However, doing this requires paying Google.  See https://cloud.google.com/translate

**Comment by dteviot** [comment]
@ammasakshay
I'm going to suggest that what you might want is a program that will take an epub and run it through google translate to produce a translated epub.  
Or an epub reader that will run the text through google translate before showing it to you.
