### ISSUE TITLE
Add cover to fanfiction

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#565]
can you please add so cover image is always added to fanfiction.net instead of copying and pasting url

**Comment by dteviot** [comment]
@kolbdog3333
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: 10 minutes to fix.

**Comment by dteviot** [comment]
@kolbdog3333
Updated version (0.0.0.135) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
