### ISSUE TITLE
metadata url

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#566]
i'm not sure where to find that url on sites when in advanced.

**Comment by dteviot** [comment]
@kolbdog3333
Assume you want to get details for "Cultivation Chat Group"
Steps
1. Open a new browser window and go to https://www.novelupdates.com/
2. Open search tool on top right and type in "Cultivation Chat Group"
3. Select title from drop down list
4. That will take you to https://www.novelupdates.com/series/cultivation-chat-group/
5. That's the URL to put into WebToEpub's text box.

Alternately, you can start at https://www.wlnupdates.com which will ultimately give you https://www.wlnupdates.com/series-id/42461/cultivation-chat-group

I should write some sort of help page.  Unless you want to have a go.

**Comment by gamebeaker** [comment]
Explained in wiki [Additional Metadata URL](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#additional-metadata-url).
