### ISSUE TITLE
Extension started not working on hostednovel.com and wondernovels.com

### ISSUE THREAD

**Issue by Ketboga** [dteviot/WebToEpub#567]
The issue is just as written in the title. I tried it on edge, firefox, chrome, etc., with current stable versions on the extension stores and the latest versions that have yet to be released. But, alas, I have faced the same problem. 

The extension looks like it's gonna work, but just as it fetches chapter links, it does not do it and stays that way.

**Comment by Ketboga** [comment]
Forgot to add, thank you for your help beforehand.

**Comment by dteviot** [comment]
@Ketboga
Did you mean hostednovel.com?
I just tried https://hostednovel.com/15/novel/everlasting-immortal-firmament  and it worked without problems.
Please provide full URL that you're having an issue with.

**Comment by dteviot** [comment]
@Ketboga

I've fixed the issue with wondernovels.  (Site had changed layout to Madara theme.)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: time to fix - 10 minutes.

**Comment by Ketboga** [comment]
Thank you very much, yes it was hostednovel.com but just you said, it works now without a problem. It was probably an issue on their end yesternight.

**Comment by Ketboga** [comment]
I have just tried the new test versions on edge, chrome, firefox, and the problem is gone, they work like a charm.

**Comment by dteviot** [comment]
@Ketboga
Updated version (0.0.0.135) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
