### ISSUE TITLE
change fimfiction url to grab from

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#568]
For this site like to change main url so can get more metadata info. Like wordcount, likes and dislikes excetra,
https://www.fimfiction.net/story/137415/the-dragon-and-the-force

**Comment by dteviot** [comment]
@kolbdog3333
I don't understand.  

Please provide more details.
e.g. 
1. Change what URL? And from what to what?
2. What exactly do you want done with the word count, likes, etc.?
3. What problem are you trying to solve?
4. How will it benefit you/others?

FYI.
https://meta.stackexchange.com/questions/258136/how-do-i-write-a-good-feature-request
https://blog.usejournal.com/feature-requests-that-dont-suck-d5b776cef1e2

**Comment by kolbdog3333** [comment]
1.Want it changed from this url https://www.fimfiction.net/story/139832/1/strange-bedfellows/a-light-in-the-sky
to this one https://www.fimfiction.net/story/139832/strange-bedfellows
2. Want it to be shown on the main epub page with the title and description.
3. Longer description and more information
4. Will help people so they can see wordcount and full summary of the fanfiction

**Comment by dteviot** [comment]
@kolbdog3333  

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.


1. Modified to work with URL like https://www.fimfiction.net/story/139832/strange-bedfellows, so is now broken for URLs like https://www.fimfiction.net/story/139832/1/strange-bedfellows/a-light-in-the-sky.  So, you'll need to select the right sort of page before opening WebToEpub
2. This means get longer description on information page.
3. Added Likes and Word Count to information page.

For my reference: 45 minutes work

**Comment by dteviot** [comment]
@kolbdog3333
Updated version (0.0.0.136) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
