### ISSUE TITLE
Wnmtl.com update 

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#569]
Wnmtl.com has been updated it doesn't work anymore
Android firefox

**Comment by dteviot** [comment]
@Dlordload
I just tried using Desktop Chrome with https://wnmtl.com/1116/ and as far as I can tell, it worked fine.
Please provide more details.  What exactly isn't working?

Note, some sites send content to mobile devices that is different to Desktops.
Alternately, is your problem https://github.com/dteviot/WebToEpub/issues/480

**Comment by dteviot** [comment]
@Dlordload
I just tried using Desktop Chrome with https://wnmtl.com/1116/ and as far as I can tell, it worked fine.
Please provide more details.  What exactly isn't working?

Note, some sites send content to mobile devices that is different to Desktops, so you might want to try setting Firefox to "desktop view" https://support.mozilla.org/en-US/kb/how-do-i-change-desktop-view-firefox-android
Alternately, is your problem https://github.com/dteviot/WebToEpub/issues/480?

**Comment by Dlordload** [comment]
@dteviot ah! sorry I meant wnmtl.org very sorry

**Comment by Dlordload** [comment]
imma just close as there is another similar issue
