### ISSUE TITLE
Place GPLv3 in License.md and link to it in the readme

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#57]
In almost all of my projects on github and other git hosting sites i place a copy of the license in license.md.

For completion sake i think its wise to do the same here. What are your thoughts?

**Comment by dteviot** [comment]
Go ahead, My reading of GPL 3 says we're supposed to include a copy of it anyway.
Aside: weird, I would have thought a hyperlink to the license on the GNU site would be sufficient.

**Comment by belldandu** [comment]
Its mainly so the people grabbing the extension also have a physical data copy of the license.

**Comment by belldandu** [comment]
Quick question. Which branch should I put the license.MD file in. @dteviot

**Comment by dteviot** [comment]
@belldandu 

Experimental Tab is the "in development branch".
When I release, it merges into Sonako. and that's what's released.
And Master gets moved up to previous released version of Sonako.
i.e.
- Sonako is latest released version.
- Master is last stable release.
- Experimental Tab is the current development branch.

So, in answer to your question: https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode

**Comment by belldandu** [comment]
Done https://github.com/dteviot/WebToEpub/commit/45f5eb9e8d5512ef9e4ab16f1ae2fb0966ff5613

**Comment by belldandu** [comment]
didn't mean to close yet.

**Comment by dteviot** [comment]
https://github.com/dteviot/WebToEpub/commit/f2bbdcb843a70f5070fe8a661380442b95ec8efe is the commit that adds the GPL 3 license.
