### ISSUE TITLE
Please add site ID/ES/FR version of mtlnovel.com

### ISSUE THREAD

**Issue by anwarfors123** [dteviot/WebToEpub#571]
can you make a version Indonesia/Espanol/Francais from mtlnovel.com
Example:
ID : https://id.mtlnovel.com/billions-of-years-in-the-city/
ES : https://es.mtlnovel.com/billions-of-years-in-the-city/
FR : https://fr.mtlnovel.com/billions-of-years-in-the-city/

webtoepub works at mtlnovel.com but not in other languages

Thanks

**Comment by dteviot** [comment]
@anwarfors123 

My apologies, I did not know those existed.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: 10 minutes work

**Comment by anwarfors123** [comment]
tested, and worked

Thanks man

**Comment by dteviot** [comment]
@anwarfors123
Updated version (0.0.0.136) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
