### ISSUE TITLE
wnmtl.org update

### ISSUE THREAD

**Issue by kuakao** [dteviot/WebToEpub#572]
Hi @dteviot can you check wnmtl.org? Web has been updated it doesn't work anymore, I'm using Chrome windows.
Thank you

**Comment by Cronium** [comment]
I think they are now are using javascript to load/render the content, which is why when the parser tries to scrape it, no content appears.

**Comment by dteviot** [comment]
@Cronium

You are quite correct.

@kuakao
Apologies for delay in responding
1. I've been sick (not covid).
2. Getting this to work will probably take 2 to 3 hours of work (at least.) I'm not going to start until I have that much time available, possibly this weekend.

**Comment by kuakao** [comment]
> @Cronium
> 
> You are quite correct.
> 
> @kuakao
> Apologies for delay in responding
> 
> 1. I've been sick (not covid).
> 2. Getting this to work will probably take 2 to 3 hours of work (at least.) I'm not going to start until I have that much time available, possibly this weekend.

GWS @dteviot speedy recovery take care your health first

**Comment by dteviot** [comment]
Notes for future reference.

Notes.
Looks like, if chapter has a URL of https://wnmtl.org/chapter/148888-untitled
then the REST call to get the chapter content is a GET of https://api.mystorywave.com/story-wave-backend/api/v1/content/chapters/148888
In the response, use data.title and data.content.
content is text, need to convert to html, splitting chapters.  see convertPreTagToPTags()

**Comment by dteviot** [comment]
Notes on fetching list of chapters URLs.
Given a book's ToC URL of https://wnmtl.org/book/2118-monarch-of-evernight
Then need to make a series of REST calls like https://api.mystorywave.com/story-wave-backend/api/v1/content/chapters/page?sortDirection=ASC&bookId=2118&pageNumber=1&pageSize=1000

(Note, bookID needs to be pulled from URL, doesn't seem to be in the actual page)
Returns JSON like
```json
    "code": 0,
    "message": "success",
    "data": {
        "pageSize": 10,
        "totalCount": 1516,
        "totalPages": 16,
        "list": [
            {
                "id": 148992,
                "createTime": 1623933354000,
                "updateTime": 1623933354000,
                "orgId": null,
                "bookId": 2118,
                "title": "Blood For Blood",
                "wordCounts": 2475,
                "chapterOrder": 105,
                "status": "published",
                "paywallStatus": "free"
            },
         ]
      }
```

This would be for a chapter URL https://wnmtl.org/chapter/148992-blood-for-blood
Also note the totalPages value, which says how many REST calls to make

**Comment by kuakao** [comment]
@dteviot Thanks, this is exactly what I was looking for :)

**Comment by dteviot** [comment]
@Dlordload, @Cronium, @kuakao
Updated version (0.0.0.136) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
