### ISSUE TITLE
Ranobes issue

### ISSUE THREAD

**Issue by juliaor** [dteviot/WebToEpub#574]
Haven´t been able to fetch any of the links from ranobes.net for at least the last week in Chrome, both Windows 10 version, and latest Mac OS version, and tested today in Firefox on Mac. Used this link as example: https://ranobes.net/novels/728626-the-ancients-world-v216510.html

Am I missing something?

**Comment by dteviot** [comment]
Investigating.
Note. I just tried it with https://ranobes.net/novels/1045759-comic-system.html and it worked.

**Comment by dteviot** [comment]
@juliaor 
> So it works only with some, and not all? Any idea what could be the reason?

Not yet, but I will.

**Comment by dteviot** [comment]
@juliaor
I believe I've solved the problem.
The filename field is blank, which makes the fetching of chapters fail to start.
Filename is blank because Title is blank.
Title is blank because code to remove subtitle is buggy.

Anyway, as work around, just add value to Title and Filename if missing.
I'll commit a proper fix later today.

**Comment by juliaor** [comment]
Thank you so much!! Adding title and filename makes it work like you said! :D

**Comment by dteviot** [comment]
@juliaor
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes, about 15 minutes to figure out problem, another 10 to fix.

**Comment by dteviot** [comment]
@juliaor
Updated version (0.0.0.136) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
