### ISSUE TITLE
https://archiveofourown.org/series/

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#576]
would like to use webtoepub to grab a series example
https://archiveofourown.org/series/1046538
so all urls are grabbed and saved as one epub instead of multiple and merging into one

**Comment by dteviot** [comment]
@kolbdog3333
Sorry, this is proving to be quite difficult.
I'm not even sure why you're using WebToEpub for this site, It provides a download as EPUB function.

**Comment by dteviot** [comment]
@kolbdog3333
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Seems to work for the link you supplied.  I didn't try any others.

For my notes: 90 minutes work

**Comment by dteviot** [comment]
@kolbdog3333
Updated version (0.0.0.137) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
