### ISSUE TITLE
Please add site https://sweek.com/

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#580]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
Google translate

> I am registered with an account on the site and the list of chapters comes out like this,

**Comment by dteviot** [comment]
I thought To get chapters, would be this, but it's not working.

Seems to make a POST call to https://sweek.com/graphql
Giving it following payload (assumes 1st chapter of story has URL https://sweek.com/read/1/1700039406)

```javascript
{"operationName":null,"variables":{"storyId":1,"storyDevice":"1700039406"},"query":"query ($storyId: Int!, $storyDevice: String!) {\n  getChapters(storyId: $storyId, storyDevice: $storyDevice) {\n    ok\n    errorCode\n    chapters {\n      id\n      device\n      title\n      __typename\n    }\n    __typename\n  }\n}\n"}
```

with a mime type of "application/json",

**Comment by dteviot** [comment]
@bichitoxxx
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Seems to work for 
* https://sweek.com/s/BgQEAgBsCAUFBwgJAwEFB2YCCA==/thehalfbloodprincess/What-If
* https://sweek.com/s/BwQFBmYCCwEFBAsBBwADaggC/AkankshaVerma/Exploring-Lisa

**Comment by bichitoxxx** [comment]
I'm going to try it, I'll tell you how it goes. Thank you

**Comment by bichitoxxx** [comment]
other tests , Only one of the links that you put to work for me.

![Screenshot (2)](https://user-images.githubusercontent.com/29169926/131482688-e7d6572b-ebc2-4cf7-8d99-7c4a82c401e7.png)
![Screenshot (1)](https://user-images.githubusercontent.com/29169926/131482457-25b1d053-e293-4a24-a039-d06375710434.png)
![Screenshot](https://user-images.githubusercontent.com/29169926/131482470-67839c39-4f75-4c5c-96a0-b3ce3884c089.png)

**Comment by bichitoxxx** [comment]
It works for me if I enter from this page, it sometimes fails to obtain the chapter, but it is a failure for every 4 attempts. I have downloaded several without problems, and the structure of the Epub is perfect.

**Comment by bichitoxxx** [comment]
I accidentally closed the subject, sorry.
It works for me if I enter from this page, it sometimes fails to obtain the chapter, but it is a failure for every 4 attempts. I have downloaded several without problems, and the structure of the Epub is perfect.
![Picture0001-1](https://user-images.githubusercontent.com/29169926/131492300-fc83e597-3f74-40fd-a334-b092a107447f.jpg)
![Screenshot (1)](https://user-images.githubusercontent.com/29169926/131492320-fa8e4a6d-d977-42a8-a53d-5240add0b168.png)

If you try to download from the first chapter it fails. 
![Screenshot (2)](https://user-images.githubusercontent.com/29169926/131492659-ea8300dd-afab-42b0-9c6f-51dccb6d4d3a.png)
![Screenshot (3)](https://user-images.githubusercontent.com/29169926/131492670-035c30ed-ef34-4d24-93aa-72ba52c4d46a.png)
So I consider that except for a specific failure, it is perfect now to download from here.
Thank you very much for your time and your work.

**Comment by dteviot** [comment]
@bichitoxxx
Yes, it only works from a story's information page.  Won't work from a chapter.
WebToEpub is looking for the "Leer" button to get the chapters.  That button isn't there on a chapter page.
And can take a while to appear on the information page.

I'm going to call this closed.

**Comment by dteviot** [comment]
@bichitoxxx
If you want asianfacfics supported, raise another issue.

**Comment by bichitoxxx** [comment]
> @bichitoxxx
> ‎Sí, solo funciona desde la página de información de una historia. No funcionará a partir de un capítulo. ‎
> ‎ WebToEpub está buscando el botón "Leer" para obtener los capítulos. Ese botón no está allí en una página de capítulo. ‎
> ‎ Y puede tardar un tiempo en aparecer en la página de información.‎
> 
> ‎Voy a llamar a esto cerrado.‎

all perfect thank you very much for your work

**Comment by dteviot** [comment]
Reopening so I know to tell you when version in Chrome/Firefox store has been updated.
