### ISSUE TITLE
Not selecting correct image for Wattpad covers

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#581]
**Describe the bug**
When you download a book from wattpad it puts random cover images, it does not take the original book. you have to modify it by hand by entering the url of the image.

**Screenshots**
![Screenshot(2)](https://user-images.githubusercontent.com/29169926/131001026-9f027a71-7f83-4b39-bd60-c958263a816b.png)

**Desktop (please complete the following information):**
 - Browser [chrome, firefox]

**Comment by dteviot** [comment]
Google Translate

> Thanks so far it seems that it works in Chrome, I will inform you if there are any errors.
