### ISSUE TITLE
Patreon post retrieval fails after 3/4 posts

### ISSUE THREAD

**Issue by vinaymbharadwaj** [dteviot/WebToEpub#583]
**Describe the bug**
Unable to pack an Epub from Patreon posts. The issue is explained in detail in the "To Reproduce" section.

**To Reproduce**
1. Login to Patreon and open up the account where posts reside (Example: https://www.patreon.com/HPMan/)
2. Click on WebToEpub extension and wait for it to get all post URLs (which it does successfully)
3. Click on "Pack Epub".
4. Packing starts. Green ticks are seen for about 4-5 posts and then it stops and I get a download option (skipping the rest of the posts).
5. This happens even if you give a sleep-time between individual posts in Advanced options.

**Expected behavior**
I should be able to pack an Epub from Patreon posts (regardless of their number).

**Screenshots**
![image](https://user-images.githubusercontent.com/44992125/131218093-fea393f9-027d-4ad0-a75d-a1512041b12a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: Edge:92.0.902.84 and WebToEpub: 0.0.0.136

**Smartphone (please complete the following information):**
Not Applicable.

**Additional context**
Nothing else.

**Comment by dteviot** [comment]
@vinaymbharadwaj
After clicking save does an error message appear?
Probably something like:

Error: Could not find content element for web page 'https://www.patreon.com/posts/chapter-3-hp-new-47639786'.
    at chrome-extension://omliclippfibgegkdnanknpekbaahlhm/js/Parser.js:493:23
    at async Promise.all (index 0)
    at async PatreonParser.fetchWebPages (chrome-extension://omliclippfibgegkdnanknpekbaahlhm/js/Parser.js:462:17)

Note to self.
Looks like there's a third format for content pages.
Look for &lt;script&gt; element with json.
```javascript
 "post": {
  "data": {
   "attributes": {
    "change_visibility_at": null,
    "comment_count": 0,
    "content": "\u003cp\u003eAfter all, 
    "title": "Chapter 3 (HP: New World)",
```
"content" is the HTML content for the page
"title" is the title

**Comment by dteviot** [comment]
@vinaymbharadwaj

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Unfortunately, at the moment, I can't get Patreon to use this new method, so I can't easily test if the code I've written works.
If it doesn't, you'll probably need to tweak the function addContentFromScript() in file PatreonParser.js.

If you know any free Patreon story with lots of chapters, I can try and give it a go.

**Comment by vinaymbharadwaj** [comment]
Yeah. That seems to have done the trick. I used the build from your google drive link and things worked out perfectly!

**Comment by dteviot** [comment]
@vinaymbharadwaj
Updated version (0.0.0.137) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
