### ISSUE TITLE
Mtlreader.com

### ISSUE THREAD

**Issue by Ndonkz** [dteviot/WebToEpub#587]
Parsing need update, please

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at MtlreaderParser.fetchChapter (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MtlreaderParser.js:35:24)
    at async Promise.all (index 0)
    at async MtlreaderParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

**Comment by dteviot** [comment]
@Ndonkz 

My deepest apologies, I'm not sure how I missed this request.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: 30 minutes to fix.

**Comment by dteviot** [comment]
@Ndonkz
Updated version (0.0.0.139) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
