### ISSUE TITLE
the site readlightnovel no longer does its thing on webtoepub

### ISSUE THREAD

**Issue by jillybeans** [dteviot/WebToEpub#590]
the site readlightnovel no longer does its thing on webtoebub, it doesnt just grab chapters read to grab like before and its all funky. sorry if im not explaining better first time leaving a report, long time user

https://www.readlightnovel.me/nano-machine-retranslated-version

it used to work automatically but not anymore. the site used to be a .org if that changes anything

**Comment by dteviot** [comment]
@jillybeans 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: 5 minutes to fix.

**Comment by jillybeans** [comment]
works perfectly thank you

**Comment by dteviot** [comment]
@jillybeans
Updated version (0.0.0.139) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
