### ISSUE TITLE
https://www.novelmt.com/

### ISSUE THREAD

**Issue by mangoxenon** [dteviot/WebToEpub#593]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.novelmt.com/e/extend/fy.php?page=1&amp;wjm=<novel name>

### Did you try using the Default Parser for the site?  If not, why not?
Yes, it only grabbed the first page of toc.  

### What settings did you use?  What didn't work?
* URL of first chapter
https://www.novelmt.com/novel/<novel name>_1.html
* CSS selector for element holding content to put into EPUB
.chapter-content
* CSS selector for element holding Title of Chapter
.chapter-content > p
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@mangoxenon Updated version (0.0.0.140) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
