### ISSUE TITLE
Vipnovel "Cannot read properties of null"

### ISSUE THREAD

**Issue by Arsur3215Loki** [dteviot/WebToEpub#597]
**To Reproduce**
1. Go to '[**Vipnovel**](https://vipnovel.com/)'
2. Select any story
3. Click on 'WebToEpub'

**Screenshots**
![Screenshot 2021-09-17 220537](https://user-images.githubusercontent.com/74763442/133796167-b83a1c73-3d88-4658-bee7-61e92c4640bf.png)

**Desktop (please complete the following information):**
 - OS: [Window 10]
 - Browser Chrome
 - Version 93.0.4577.82

**Comment by Dimava** [comment]
download chrome.zip from <https://github.com/Dimava/WebToEpub/releases/tag/0.0.0.140.pre> and drop it in into `chrome://extensions` page to test ("developer mode" toggle on that page should be on for this)

**Comment by Dimava** [comment]
BTW @dteviot I made a script for publishing releases (see above how it looks like), I'll PR it sometime this or next week

**Comment by Dimava** [comment]
Tho firefox extensions should be signed and that is another question I'm beatin my head of

**Comment by Arsur3215Loki** [comment]
@Dimava should I delete the previous version?

**Comment by Dimava** [comment]
@Arsur3215Loki nah, you mau have two at once
You may temporally disable webstore one so you don't have two same icons to click on
Just remember to delete it when webstore version updates

**Comment by dteviot** [comment]
@Dimava  
>Tho firefox extensions should be signed and that is another question I'm beatin my head of

Mozilla sign the extension.  Gets done as part of the publish to the Firefox store process.
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by Arsur3215Loki** [comment]
> @Arsur3215Loki nah, you mau have two at once
> You may temporally disable webstore one so you don't have two same icons to click on
> Just remember to delete it when webstore version updates

Sorry, that now I just made a reply... but it still wouldn't work, I've been using a different site to get my books to read, and when I finally tried it using the site again I still got the same error. I've decided to use a different site for now and wait for the update.

**Comment by dteviot** [comment]
@Arsur3215Loki Updated version (0.0.0.140) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
