### ISSUE TITLE
Please add site http://www.eugenewoodbury.com

### ISSUE THREAD

**Issue by b3nw** [dteviot/WebToEpub#599]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
http://www.eugenewoodbury.com/twilight/index.html

### Did you try using the Default Parser for the site?  If not, why not?
Yes, doesn't seem to work due to the `<p class=text>` on every line

### What settings did you use?  What didn't work?
* URL of first chapter  - http://www.eugenewoodbury.com/twilight/book1/twilight_01.htm
* CSS selector for element holding content to put into EPUB - unsure
* CSS selector for element holding Title of Chapter - unsure
* CSS selector for element(s) to remove - unsure

**Comment by dteviot** [comment]
@b3nw 
It's not fun.  Different stories have different formats.  (Depending on if they're on http://www.eugenewoodbury.com/ or https://eugenewoodbury.blogspot.com/)
A number of the titles can be downloaded as epubs.  See: http://www.eugenewoodbury.com/downloads.htm
The following settings worked for http://www.eugenewoodbury.com/twilight/index.html
![Untitled](https://user-images.githubusercontent.com/5157081/133920505-2d22ee8c-589a-4b99-8c03-e680f2902ae2.png)

Note, You'll need to remove remove some chapters from the offered list that don't process correctly, e.g. Glossary.  (I suggest you'll want to click on "Advanced Options" and check the "Skip chapters that return HTTP 404 error" option, so it doesn't stop on chapters that don't work.)

**Comment by b3nw** [comment]
Cheers this works, agree had trouble with it as well.
