### ISSUE TITLE
Reset button in tab mode

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#60]
It would be nice to have a reset button in tab mode. So users can easily use the extension for different URLs without having to open the extension from pop-up again.

**Comment by dteviot** [comment]
You could just type in a different URL and hit "Load and Analyse" again.  Except I remove the button once a parser is found.  So, I could just not remove the "Load and Analyse" button.

Does that work?  Or is a reset button needed to make things more obvious?

**Comment by toshiya44** [comment]
I think that works, bu I'd prefer a persistent reset button.

**Comment by dteviot** [comment]
@toshiya44
OK, so that I am sure I understand what you're asking for, is this it?
When "Reset" button is clicked, it should clear the form and put focus to the "URL" control, waiting for user to supply a new URL?

**Comment by toshiya44** [comment]
Yup.

**Comment by dteviot** [comment]
@toshiya44 You might like to give it a try.
It's on the [Advanced Options branch](https://github.com/dteviot/WebToEpub/tree/AdvancedOptions) 
Note, you'll need to open "Advanced Options" on the GUI.  I didn't want to put it on the main UI, because it could be buggy.

**Comment by toshiya44** [comment]
@dteviot It works great.

**Comment by dteviot** [comment]
Closing request.  Raising new issue for bugs.
