### ISSUE TITLE
If the chapter page does not contains title, it will have no h1-title

### ISSUE THREAD

**Issue by Dimava** [dteviot/WebToEpub#600]
![image](https://user-images.githubusercontent.com/20068737/133947325-b3b2d942-6c3a-4632-be5a-599ce052f52b.png)

Due to the fact that rulate website `<h1>` and `<title>` on chapter pages contain the book title as well, and there is no clear way to split them, I did not implement `findChapterTitle`, hoping that extension will fill that for me
... and that suddenly did not work

Should the title be taken from TOC page if it is not provided? How should title be extracted from the TOC page if not?

**Comment by dteviot** [comment]
@Dimava 
The assumption is, if findChapterTitle() is not supplied, then the Chapter's title is within the content and so does not need to be added.
As you're wanting to use the title from the ToC, then I suggest you add addTitleToContent() to RulateParser as something like
```javascript
    addTitleToContent(webPage, content) {
        let titleElement = webPage.rawDom.createElement("h1");
        titleElement.appendChild(webPage.rawDom.createTextNode(webPage.title.trim()));
        content.insertBefore(titleElement, content.firstChild);
    }
```

**Comment by Dimava** [comment]
Mkay, since I have resolved the issue with parser you can mark this `completed`

**Comment by dteviot** [comment]
@Dimava
You created this, so you should be able to close.

**Comment by dteviot** [comment]
Generally, I only close when change committed to stores, so I know to tell requestor it can be picked up.

**Comment by Dimava** [comment]
I mean, like, 
![image](https://user-images.githubusercontent.com/20068737/134594098-a77b8251-befc-4beb-8b2f-5d9e811cb976.png)

**Comment by dteviot** [comment]
@Dimava Updated version (0.0.0.140) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
