### ISSUE TITLE
'SaveAs' window doesn't popup if the WebtoEpub is minimised.

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#603]
I have tested this a couple of dozen times by now. Whereby, if you compile an epub, minimise the tab, and go on with your life, WebtoEpub will not prompt you the "SaveAs" window even if the compiling is at 100%. Do note that I do not have the following option enabled: 

  | Don't popup 'SaveAs' dialog when save Epub

And fiddling with this option does not change anything.

**Comment by dteviot** [comment]
@DicerX
Does it do it with Chrome, Firefox or both?
Note, it's possible that user focus might be required for download to be allowed.

**Comment by DicerX** [comment]
I'm currently on the latest version of Chromium Edge. Apologies for the delayed response.

**Comment by DicerX** [comment]
Regarding the user focus required to initiate the download, I have been using WebtoEpub extensively, and this issue has only begun like a month or two ago. 

This never was an issue, as I minimise the download page to look for a decent book cover for the Epub or watch YouTube. While watching or working on PS, a "SaveAs" window will pop up. 

I'm contrast, once I get the feeling of: "Oh, this compiling is taking too long," I open up the download page to find that the compiling has long been at 100% and a minute of staring at the 100% bar the "SaveAs" will be prompted. 

I failed to report this because I thought my PC is getting old etc. But I replicated this on my new laptop as well.

**Comment by dteviot** [comment]
@DicerX
I don't think I've made any changes recently to WebToEpub would cause this change in behavior.
My suspicion is something has changed in the browser.  (It sounds like some sort of security issue, won't allow a download unless user has focus.)
Please see if Firefox and/or Google Chrome have same behavior.  
Sorry, but I don't have time to investigate myself.

**Comment by DicerX** [comment]
It's alright will give it a shot tonight. Thank you for the continued
support.

**Comment by DicerX** [comment]
Firefox, Chrome, Brave, and Edge all are having this issue. I am really sorry for taking so long with this.

**Comment by dteviot** [comment]
@DicerX 
Interesting.  I *think* the problem might be the zip library I'm using to create the Epub.
I updated it from 3.1.5 to 3.7.1 to deal with complaints I was getting from GitHub.
But it looks like it might only run when chrome has focus.  (i.e. WebToEpub is halting at the "pack pages into epub file" until it gets focus.)

I've built test versions the older version of the library of WebToEpub for Firefox and Chrome and uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
Looks like might be known issue:  https://github.com/Stuk/jszip/issues/741

**Comment by DicerX** [comment]
Will try the older versions now and the three browsers and get back to ya.

**Comment by DicerX** [comment]
Yup, the old version works like a charm on Edge and Chrome and Brave. I skipped Firefox since I only use Chromium browsers. Immediately prompts 'SaveAs.'

**Comment by DicerX** [comment]
Will try larger Epubs, 2000+ chapter novels now.

**Comment by DicerX** [comment]
Large epubs also prompt 'SaveAs' without focus; whatever the old version has clearly solved this issue.

**Comment by dteviot** [comment]
@DicerX Updated version (0.0.0.140) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by dteviot** [comment]
For my notes.
Looks like issue with setImmediate() polyfill, introduced in jszip version 3.2.0
See: Stuk/jszip#741

**Comment by Synteresis** [comment]
@dteviot 

I'm not sure if this would be a suitable solution, but is it possible just to polyfill the polyfill in setImmediate? When I create a dedicated Polyfill.js and load it in the script before JSZip.js containing `setImmediate = (handle) => setTimeout(handle, 0);`, as provided as an alternative on the [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate), the extension will proceed to zip it even in the background.

**Comment by dteviot** [comment]
@Synteresis
That's strange, when I look at the jszip code, the implementation of setImmediate() IS calling setTimeout.
https://github.com/Stuk/jszip/blob/d4702a70834bd953d4c2d0bc155fad795076631a/lib/utils.js#L6

https://github.com/sindresorhus/set-immediate-shim/blob/5261f669523be85b4680c9d23411aee39c2b1d5f/index.js#L1-L6

But I think that's the solution to the problem.  polyfill setImmediate, before the JSZip script.
I feel so stupid.

**Comment by Synteresis** [comment]
I spoke a bit too soon for the simplicity of the polyfill, but looking at the setImmediate changes, it seems that 
```
- var setImmediate = require('core-js/library/fn/set-immediate');
+ var setImmediate = require('set-immediate-shim');
```
was what affected setImmediate from 3.1.5 to 3.7.1. The polyfill use to be https://github.com/zloirock/core-js/blob/01db8b322ae68c638ba287ccfc6a745f2c8e29d3/packages/core-js/internals/task.js#L55.

**Comment by dteviot** [comment]
@Synteresis 
Agreed.
Hence my embarrassment.  I spent hours trying to figure out how to replace/inject a different setImmediate shim implementation into JSZIP.  When all I needed to do was just monkey patch setImmediate itself.

**Comment by dteviot** [comment]
@Synteresis @DicerX 
Updated version (0.0.0.144) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
