### ISSUE TITLE
Please add site https://www.novelmtl.com

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#605]
https://www.novelmtl.com/novel/the-era-of-gods.html
this is similar to the other site that I requested

**Comment by dteviot** [comment]
Seems to be identical theme to https://www.novelmt.com/
Only need 1 line to add.

**Comment by dteviot** [comment]
@Dlordload 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Dlordload 
Updated version (0.0.0.140) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
