### ISSUE TITLE
Please add site https://travistranslations.com

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#606]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
**https://travistranslations.com/novel/12365/how-to-keep-a-distance-from-a-beautiful-girl#toc**
**https://travistranslations.com/novel/26639/yuri-empire/#toc**

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
**I did use it, but it didn't work. the chapter took some time to load. so all I got is "chapter loading..."**

### What settings did you use?  What didn't work?
* URL of first chapter: **https://travistranslations.com/novel/12469/only-i-know-that-my-sister-has-a-brother-complex/chapter-2-2/**
* CSS selector for element holding content to put into EPUB: **div.reader-content**
* CSS selector for element holding Title of Chapter: **h2**
* CSS selector for element(s) to remove

**why it didn't work: the chapter took some time to load. so all I got is "chapter loading..." in the chapter content**

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
**I don't have developer skills.**

**Comment by dteviot** [comment]
@SpiralBaka 
Sorry, I can't help you.
That site seems to be encrypting the page content.
If WebToEpub was to decrypt  it. that would violate the Chrome stores terms of service and get WebToEpub removed from the store.

**Comment by voltrare** [comment]
hello, for travis translations
this should work

for chapter title `h1.leading-none`
for body content `div.my-4.reader-content, div[style*="font-size: 16px; line-height: 24px; font-family: Roboto"]`

**Comment by dteviot** [comment]
@SpiralBaka 
voltrare is giving you the config to use the default parser.
I took a quick look, and I think the site may have stopped doing encryption,  If so this should work.

If you confirm it works, I'll add it as a known parser for the site to WebToEpub.

**Comment by SpiralBaka** [comment]
@dteviot 
it worked. but the title tag should be changed. <h1 class="leading-none"> results in series title, <h2 class="text-lg font-normal"> results in chapter number, after that comes the chapter title using <span> tag. all three above are under the tag <div class="flex flex-col px-6 py-3 text-center rounded header">
so, I used **div.header** for the title css selector

I tested on the two links above, and it worked nicely
@dteviot @voltrare thanks for giving solution and reopening this thing and sorry for the late reply.

**Comment by dteviot** [comment]
@SpiralBaka @voltrare 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with:
* https://travistranslations.com/novel/12365/how-to-keep-a-distance-from-a-beautiful-girl/  (first and last chapters)
* https://travistranslations.com/novel/33767/quick-transmigration-i-just-want-to-die/

For my notes 30 minutes work

**Comment by voltrare** [comment]
it worked nicely and detects chapter links and cover 
for the cover, default link would give low quality image
example :
https://cdn.statically.io/img/travistranslations.com/q=55,f=auto/wp-content/uploads/2021/04/Takane-no-Hana.jpg

but this link should give better quality
https://cdn.statically.io/img/travistranslations.com/q=100,f=auto/wp-content/uploads/2021/04/Takane-no-Hana.jpg
https://travistranslations.com/wp-content/uploads/2021/04/Takane-no-Hana.jpg


tested on
* https://travistranslations.com/novel/12374/i-become-a-rogue-lord-in-a-world-where-only-i-level-up
* https://travistranslations.com/novel/12322/dragon-marked-war-god (random chapters including first and last)
* https://travistranslations.com/novel/12446/takane-no-hana/

thanks for your work :)

**Comment by dteviot** [comment]
@voltrare @SpiralBaka 

Updated version (0.0.0.144) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
