### ISSUE TITLE
Please add site https://dummynovels.com/

### ISSUE THREAD

**Issue by KaterinaSawyer** [dteviot/WebToEpub#610]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://dummynovels.com/novel/i-got-marked-by-my-shadow-guard-after-pretending-to-be-an-alpha/#

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

It actually does seem to work but it only grabbed the table of contents page and not the chapters itself.

<img width="1280" alt="AE7ABC03-2A65-4364-8BF4-21BCE906DE5F" src="https://user-images.githubusercontent.com/90402642/134938920-353a800a-d7a3-46aa-83c3-982738765bcc.png">

### What settings did you use?  What didn't work?
* URL of first chapter 
https://dummynovels.com/novel/i-got-marked-by-my-shadow-guard-after-pretending-to-be-an-alpha/chapter-1/
* CSS selector for element holding content to put into EPUB
unsure
* CSS selector for element holding Title of Chapter
unsure
* CSS selector for element(s) to remove
unsure

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

I have no developer skills

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

No friend with developer skills

**Comment by dteviot** [comment]
@KaterinaSawyer 
Site has changed layout.
I've updated and test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
It worked for me for: 
* https://dummynovels.com/novel/monster/
* https://dummynovels.com/novel/i-got-marked-by-my-shadow-guard-after-pretending-to-be-an-alpha/#

For my notes, time to fix: 18 minutes

**Comment by KaterinaSawyer** [comment]
I'm sorry, I tried understanding the instructions but as someone who's never dabbled in this, I'm not sure what "plugin" directory is and what the location to keep it is supposed to be. 

2. Unpack zip file and move the "plugin" directory to the location you want to keep it.

I know how to unpack the zip file but I can't understand "move the "plugin" directory to the location you want to keep it". I could probably go through step 3 and the rest. Sorry for taking up your time.

**Comment by dteviot** [comment]
@KaterinaSawyer  
D'oh! My apologies.
The plug-in directory only exists if you did step 1 (download zip file from GitHub), which gives you a different zip file to the one from google drive.
If you downloaded the zip from google drive, then all the contents of the zip file are the "plugin".

Obviously, I need to update the instructions.

**Comment by dteviot** [comment]
@KaterinaSawyer 
As regards "to the location you want to keep it".
If you download the zip file, it will probably be in your "downloads" folder, along with everything else you download.  Assuming you don't want to clutter up the downloads folder, with the files extracted from the zip, you can put them somewhere else.

If that's not clear, feel free to ask.

**Comment by KaterinaSawyer** [comment]
May I ask in step 3, how do I create a "dist" directory inside the "jszip" directory?

3. In the "plugin" directory from the previous step there is a "jszip" directory. Create a "dist" directory inside this "jszip" directory.

**Comment by dteviot** [comment]
@KaterinaSawyer 
> May I ask in step 3, how do I create a "dist" directory inside the "jszip" directory

That's only necessary if you've downloaded from GitHub.
The easiest set of steps is using Firefox.
1. Download the Firefox version from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.
2. Open Firefox and type "about:debugging#/runtime/this-firefox" into the URL bar.
3. Click "Load Temporary Add-on".
4. Click on the zip file you downloaded in step 1.
![UseFirefox](https://user-images.githubusercontent.com/5157081/135231503-aea1acb6-becc-48c7-a7c9-53531b9bc35f.png)

**Comment by KaterinaSawyer** [comment]
So I tried the Firefox one and it worked! 
![2078CAE4-E9C0-4D02-B2E8-0DD492E856E6](https://user-images.githubusercontent.com/90402642/135277078-16592d99-b070-477b-b25f-9c738cda22ad.jpeg)

Thank you very much for the help! Really appreciate it

**Comment by dteviot** [comment]
@KaterinaSawyer 
Updated version (0.0.0.141) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
