### ISSUE TITLE
Autofill range of chapters to the title

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#613]
**Describe the solution you'd like**

I always have to add the chapters range to the title, I thought I might as well request it and see if this can be added to WebtoEpub in the future.

**Examples:**

Current title:

[Digging to Survive: I Can See Hints
](https://i.imgur.com/E6j40sJ.png)

Title autofill:

[Digging to Survive: I Can See Hints, Chapter 1 - Chapter 506
](https://i.imgur.com/1XrgrPJ.png)

**Describe alternatives you've considered**

Using my hands to slowly type the chapters range.

**Comment by dteviot** [comment]
@DicerX 
That's not a bad idea.
However, I'm not sure this can be done reliably (and easily) in all cases.
My thought is, scan the titles of the first and last chapters for a number.
If both have numbers, and first is less than second, add suffix like .c0001-0506
Would that work for you?
