### ISSUE TITLE
[Archive of Our Own] and [Scribble Hub]: Please include author's note as an option, like with royalroad.

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#618]
in Ao3, notes are not usually important enough to enjoy the story, but sometimes author notes can be interesting, like this series:
https://archiveofourown.org/works/29139537/chapters/71537127
in that series, there are notes in almost every chapter (chapter 1 not included) and those are like omakes, I'd like to include them in the epub.

in Scribble Hub, the author notes gives an error because the plugin tried to get higher resolution image, and the contents are sometimes important, sometimes not. I'd like to be able to exclude the author notes. example of story with author notes:
https://www.scribblehub.com/series/221239/returning-transcendent-opens-an-idol-agency/
in chapter 1, before chapter content, and in chapter 9 after chapter content.

btw, there are reasons why I prefer to use webtoepub on ao3 rather than download directly:
1. the tags are formatted in a list instead of paragraph. if it's in a list, I don't need to worry too much about accidentally clicking a link there. (I read on android, so there's a chance that I could encounter a page full of links where I have to use volume button to go to the next page)
2. the chapter title include chapter number. direct download actually didn't include them.
3. no author notes. yeah sometimes I want to include author notes, but only sometimes. most of the time I skipped those.

**Comment by dteviot** [comment]
@SpiralBaka 
Updated version (0.0.0.142) with mtlnation disabled has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
