### ISSUE TITLE
Please add site https://www.amor-yaoi.com

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#620]
I have discovered that it works on this page to a certain extent, if I select the url where the list of chapters is, it takes the story but not only the chapters, if not all the links on the page, I can't explain it, I leave the story where I did the test, the problem is that it is cumbersome because you have to go searching chapter by chapter and uncheck the rest including a Reviews page that inserts after each chapter, as an additional chapter. for long stories it is very tedious to go looking for chapters. You have to look for the first and last chapter.

What I would like is that I only select the chapters and not everything that the page contains.

https://www.amor-yaoi.com/fanfic/viewstory.php?sid=73742&index=1

![Screenshot (2)](https://user-images.githubusercontent.com/29169926/138669600-439300ef-eb3d-461f-9798-ba4666a1b168.png)

![Screenshot (3)](https://user-images.githubusercontent.com/29169926/138670188-2e9f9b3c-7f7c-4764-84e3-3ee02e83acc9.png)

![Screenshot (4)](https://user-images.githubusercontent.com/29169926/138670217-73b66c58-8515-4e4f-99b9-399740c0f1bf.png)

**Comment by dteviot** [comment]
@bichitoxxx 
Updated version (0.0.0.142) with mtlnation disabled has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
