### ISSUE TITLE
Fix https://www.ossantl.com fetching chapter list

### ISSUE THREAD

**Issue by kevin01523** [dteviot/WebToEpub#622]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.ossantl.com/series/arafoo-kenja-no-isekai-seikatsu-nikki/

### Did you try using the Default Parser for the site?  If not, why not?

Well before going to this step it fails to get the chapter list.

Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@kevin01523 
Updated version (0.0.0.142) with mtlnation disabled has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
