### ISSUE TITLE
Please remove support for mtlnation.com🥺

### ISSUE THREAD

**Issue by MTLNATION** [dteviot/WebToEpub#624]
Hello. This is the site owner of mtlnation.com. Lately we've been crawled a lot using your plugin, web2epub causing spikes in server resource/load. This causes high latency and the site becomes incredibly slow which we received many complain on our discord server. And also we buy a lot of the content/novels we posted on our site (from b.faloo.com because it can't be found on free or chinese pirated site so it costs us a lot, so we hope that our reader will read it on our site to support us so that we can continue to add more new novel for everyone to read. We would be incredibly gratefully if you could remove the services for mtlnation.com via your plugin. I'm begging you please🥺, Thank you. 

Proof of ownership: https://mtlnation.com/proof-of-ownership.txt

**Comment by dteviot** [comment]
@MTLNATION 
Updated version (0.0.0.142) with mtlnation disabled has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

Out of curiosity, how do you know that it's WebToEpub that's causing the load?

**Comment by MTLNATION** [comment]
> @MTLNATION Updated version (0.0.0.142) with mtlnation disabled has been submitted to Firefox and Chrome stores. Firefox version is available now. Chrome might be available in 1 to 3 weeks.
> 
> Out of curiosity, how do you know that it's WebToEpub that's causing the load?

Hello, Thank you so much for removing support for mtlnarion.com.. This is what our hosting technical staff told to us when we report that our site is getting slow very much, they told us that we got many request from many individual ip which is high likely cause by crawler or bots it cause us a high server load so they recommend to us to have a rate limiting plugin but I'm very against it because it's not good for readers, it sometimes false block a legit user, So we investigate it we used service like datadome to tell which ip is having many request and we found many ip. So we changed the sites structure and after that the site became back to normal. Someone on our discord server asked us why web2epub was no longer working and that was when we found out about your plugin. A while later we started to see the server load issues again, and web2epub had recently updated and had resumed support for  mtlnation.com at around the same time. This lead us to believe that at least a large amount of the people who were causing the issues, were doing so via the web2epub plugin.

Thanks again for removing web2epub support for mtlnation.com.

**Comment by Dere45** [comment]
![Screenshot_2022-04-04-23-35-08-279_com android chrome](https://user-images.githubusercontent.com/103001749/161636247-12695f08-6a5b-4089-abcb-9e73cd536565.jpg)
it denies me access to mtlnation if I do nothing for the 1020 error

**Comment by Dere45** [comment]
Hello i hace a problema with mtlnation because it denies me access to mtlnation if I do nothing for the 1020 error
![Screenshot_2022-04-04-23-35-08-279_com android chrome](https://user-images.githubusercontent.com/103001749/161636552-2029d515-c75d-466e-9e94-c4c2098e95d7.jpg)

**Comment by Dere45** [comment]
![Screenshot_2022-04-05-00-24-11-360_com android chrome](https://user-images.githubusercontent.com/103001749/161641820-dd244599-5a57-41b2-a682-3c2d6a502f26.jpg)
This is

**Comment by dteviot** [comment]
@Dere45 
I think you're asking the wrong person for help.
I have nothing to do with that site.
If your web browser can't get to mtlnation.com, I can't help you.  
And WebToEpub does not work for that site.
