### ISSUE TITLE
Please add site https://rainofsnow.com

### ISSUE THREAD

**Issue by courli79** [dteviot/WebToEpub#627]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://rainofsnow.com/i-will-disappear-grand-duke/#chapter

### Did you try using the Default Parser for the site?  If not, why not?
yes it works but I only have the first page of chapters 0 to 100 but not 101 to 110 because the chapters are on the next page

### What settings did you use?  What didn't work?
* URL of first chapter : https://rainofsnow.com/chapters/disappear-pro/?novelid=43701
* CSS selector for element holding content to put into EPUB : div.zoomdesc-cont
* CSS selector for element holding Title of Chapter : h2
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
[RainOfSnowParser.zip](https://github.com/dteviot/WebToEpub/files/7479787/RainOfSnowParser.zip)

**Comment by dteviot** [comment]
@courli79 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

  Tested with
  https://rainofsnow.com/s-class-dungeons-mistress/
  https://rainofsnow.com/me-her-and-the-ballistic-weaponry-antique/
  
 For my notes: 59 minutes work

**Comment by courli79** [comment]
Hello, the test version works fine but only takes the first 100 chapters because the following chapters are on another page (next page or page 2).

https://rainofsnow.com/i-will-disappear-grand-duke/#chapter => 109 chapters (End)
https://rainofsnow.com/the-tragedy-of-the-villainess/#chapter => 118 chapters
https://rainofsnow.com/my-childhood-friends-are-trying-to-kill-me/#chapter => 150 chapters

**Comment by dteviot** [comment]
@courli79 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Worked for https://rainofsnow.com/i-will-disappear-grand-duke/#chapter
For my records 24 minutes work

**Comment by courli79** [comment]
Hello, this is working very well. Thank you so much!

**Comment by dteviot** [comment]
@courli79
I'm not sure if it will work with a story with hundreds or more than 1,000 chapters.  If you can find one, please let me know.

**Comment by courli79** [comment]
OK

**Comment by dteviot** [comment]
@courli79 
Updated version (0.0.0.143) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
