### ISSUE TITLE
mtlnovel.com specific novel doesn't work

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#628]
this novel won't load chapters https://www.mtlnovel.com/i-sell-games-in-the-cultivation-world/?&ampcf=1

**Comment by dteviot** [comment]
@Dlordload 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://www.mtlnovel.com/zero-to-hero-in-the-martial-arts-library/
For my notes: 30 minutes

**Comment by dteviot** [comment]
@Dlordload 
Updated version (0.0.0.143) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
