### ISSUE TITLE
Please add site https://ontimestory.eu/

### ISSUE THREAD

**Issue by KaterinaSawyer** [dteviot/WebToEpub#630]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://ontimestory.eu/index.php/in-the-future-my-whole-body-is-a-treasure/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Yes, it doesn't grab any chapters

### What settings did you use?  What didn't work?
* URL of first chapter
* https://ontimestory.eu/index.php/2020/10/26/in-the-future-my-whole-body-is-a-treasure-chapter-1-marshal-bride/
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

I have no developer skills.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?

No friends with any developer skills.

**Comment by dteviot** [comment]
@KaterinaSawyer 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested against:
* https://ontimestory.eu/index.php/dramas-of-abusive-scums-causes-comfort/
* https://ontimestory.eu/index.php/in-the-future-my-whole-body-is-a-treasure/

For my notes: 20 minutes work

**Comment by dteviot** [comment]
@KaterinaSawyer 
Updated version (0.0.0.143) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by KaterinaSawyer** [comment]
Hi, sorry for the very very late reply, just wanted to inform that it all worked! Thank you again for the help!
