### ISSUE TITLE
"Headless" Integration

### ISSUE THREAD

**Issue by Synteresis** [dteviot/WebToEpub#631]
**Is your feature request related to a problem? Please describe.**
This is less of a feature request and more of "is it possible" question. I want to know if it is possible so I do not use up my time researching into something that is not possible at all and spent a lot of time only to find out something essential is not possible at the end. 

**Describe the solution you'd like**
I am not very proficient in web development and what is possible with web extensions, but wanted to try integrating the extension with perhaps Selenium on Python or another library in order to be able to use the functions while in a program like Calibre by calling the functions from a Python frontend and Nodejs backend.

Is there a way to tell the extension from the manifest or some other way to tell the extension specific settings to use and to automatically run when a certain site is opened?

**Describe alternatives you've considered**
I tried to port the entire thing over directly to Nodejs and Electron, but I realized that my HTML and CSS skills were terrible as well as potentially having to rewrite a portion of the code to take advantage of having the file access and capabilities of a Nodejs program comparatively to a web extension.
<details>
<summary>This took nine hours of work for me to do</summary>

![image](https://user-images.githubusercontent.com/89273531/140694783-5ef89283-e089-461f-bfdc-7269e4a0a917.gif)
</details>

I also thought about rewriting it for Python entirely, but that would mean that new parser files would each have to be manually converted, or writing a small javascript interpreter that is enough for the parser files to convert the commands into python, but both would have its own pros and cons.

**Additional context**
Potentially, I wanted to integrate it into a python library that would automatically git clone the newest repository, build it with headless settings, and run it via selenium or some other method. This would allow me to create a Calibre extension with it. 

I tried porting the current extension over to Safari and was able to get the Downloads portion to work via the Browser FS Access API over at https://browser-fs-access.glitch.me/ (based on https://github.com/GoogleChromeLabs/browser-fs-access), but when trying the mobile Safari, I ran into a multitude of problems with CORS and such. Maybe these are not hard to solve to an experienced web developer, but they are to someone who only has Windows systems experience.

**Comment by dteviot** [comment]
@Synteresis 
> Is there a way to tell the extension from the manifest or some other way to tell the extension specific settings to use and to automatically run when a certain site is opened?

It is probably possible to create an extension that would do this.  But I think you'd need to make changes to WebToEpub to do so.  I think you'd need to set up a background page https://developer.chrome.com/docs/extensions/mv2/background_pages/ and listen for network activity.
But I would not be willing to put that sort of logic into WebToEpub.

If you want to drive from Calibre, my suggestion would be look at https://github.com/JimmXinu/FanFicFare.

**Comment by Synteresis** [comment]
Alright, I will stick to one of the alternatives and try to make a compatible version. Thank you!
