### ISSUE TITLE
www.webnovel.com/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#633]
Could not find content element for web page 'https://www.webnovel.com/book/in-naruto-reborn-with-talent_18117311705327305'. fetchWebPageContent/<@moz-extension://3bb8cbdc-cd41-40de-b1b4-cd2ff9900f04/js/Parser.js:493:23

**Comment by dteviot** [comment]
@Finks82 
I just tried it, with latest version on Desktop Chrome.  Did not have any problem.
Looking at returned HTML from site, does not seem to have changed.
Looking at URL, that's not the URL of a chapter.  Chapter URLs look like:
https://www.webnovel.com/book/in-naruto-reborn-with-talent_18117311705327305/ch1.-awakening_48634587856825517
Are you trying to include the Table of Contents page as part of the EPUB?
e.g. Have you checked "Add Page with Chapters to Chapters List" on the Advanced Options?

**Comment by Finks82** [comment]
ya found the roblem TQ, I unchecked Add Page with Chapters to Chapters List and it work fine now.
