### ISSUE TITLE
Test Ziru's Musings Parser

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#64]
@typhoon71, @toshiya44, @dreamer2908
I've added a new parser. 
It's at https://github.com/dteviot/WebToEpub/tree/ZirusMusings
Why this might interest you is because this parser required a number of changes to to core engine.  The changes now mean for Multipage sites (e.g. everyone but Baka-Tsuki and Sonako)
- Can now select which chapters (web pages) to download
- Can change the titles that chapters will be given.
- Can collect images across multiple pages.

As you might have guessed, this is a step along the path to handle other sites (like Wuxiaworld).  And the ability to give Royal Road the ability to set a cover image.

Anyway, as it's touched the core, I'd appreciate it if you could try exercising the other sites.  Thanks.

Issues to fix
- [x] Fetch images for page after each page fetched.  i.e. in ImageCollector.fetchImages track which images have been downloaded and only fetch the ones that haven't been downloaded.
- [x] Remove trailing white space from end of chapters.
- [x] Need to fix up footnotes/citations/ids.
- [x] Add an "arc" field to chapter, to allow chapters to be grouped in Table of Contents.
- [x] Don't duplicate images when one is HTTP:// and other is HTTPS://
- [x] Add image source URL as comment, if not included as description.
- [x] Investigate why Cheat Receptionist is missing Vol 1 Illustrations.
- [x] Investigate why "Check all" and "Uncheck All" don't work.
- [x] Might want to optimise the downloading, don't try fetching the HTML page that lists all images if there isn't one.  This may require splitting ImageCollector into a generic base, and then a derived class to handle WikiMedia sources (e.g. Baka-Tsuki)

**Comment by typhoon71** [comment]
Baka-Tsuki is OK, just a white page after pics on "https://www.baka-tsuki.org/project/index.php?title=Clash_of_Hexennacht:Volume1".
Royal Road is OK too (http://royalroadl.com/fiction/1233).
Ziru's Musings is OK, tested for both LDM and Cheat Receptionist, with partials too.

BUG: the "check all" and the "uncheck all" button aren't working, both in the normal paner and in the tab "version". Nothing else spotted for now.

**Comment by dreamer2908** [comment]
Tested with Cheat Receptionist. 

- Vol 1 Illustrations are missing from the chapter list. 
- Misc links at the end of page like amazon slips into the chapter list.
- Blank paragraphs at the end (`<p>&nbsp;</p>`) are not removed.

Other than that, it works fine. "Select All" and "Unselect" buttons both work here.

**Comment by typhoon71** [comment]
About Cheat Receptionist: 
1. my test involved the chapters composing volume 1, the full ones, not the parts, and was done in chrome. 
2. the images at the start are on imgur, maybe that's whay they don't get fetched; I did notice that but since they weren't on the website itself I don't consider it a bug.

**Comment by dreamer2908** [comment]
I got this: https://i.imgur.com/BUgN0PJ.png

The translated illustrations are on pirateyoshi.wordpress.com (same as Prologue), but it is still missing.

**Comment by typhoon71** [comment]
Uuuops, the TL'ed illustration were indeed on pirateyoshi.wordpress.com as the prologue; in this case they should be fetched. I just cheched the non TL'ed ones because that's what I'd get...

**Comment by toshiya44** [comment]
There are pages such as
``http://www.novelupdates.com/series/the-guilds-cheat-receptionist/
 http://booklive.jp/product/index/title_id/282541/vol_no/001
 https://wordpress.com/about-these-ads/``
linked with zirusmusings's page. Since there are no parsers for those pages, it causes the extension to stop. They causes errors like, "TypeError: doc.body is undefined" or "TypeError: dom is null", if left checked. 
There's also an empty box for some reason.
![screenshot 27](https://cloud.githubusercontent.com/assets/20046789/17349542/c4b991ea-58ec-11e6-8e83-ae1fdf2cdd81.png)

**Comment by toshiya44** [comment]
Also, are imgur albums are bugged?
```
Error packing EPUB. Error: constructStandardHtmForImgur@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/parsers/ZirusMusingsParser.js:82:9
findContent@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/parsers/ZirusMusingsParser.js:49:20
convertRawDomToContent@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/parsers/Parser.js:45:23
Parser.prototype.chaptersToEpubItems@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/parsers/Parser.js:123:23
Parser.prototype.epubItemSupplier@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/parsers/Parser.js:113:21
packEpub@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:121:53
fetchContentAndPackEpub/<@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:111:13
promise callback*fetchContentAndPackEpub@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:110:9
EventHandlerNonNull*window.onload@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:265:9
EventHandlerNonNull*main<@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:263:5
@moz-extension://281d2d67-7b26-40e2-ba6e-8a3cb122f3eb/js/main.js:5:13
```
(Firefox 49.0a2)

**Comment by dteviot** [comment]
@toshiya44
> Also, are imgur albums are bugged? 

Depends on which version of WebToEpub you're running.  imgur pages don't have the links directly on the web page.  Instead they're generated on the fly as you look at various sections of the page.  So, I do a really dirty parse of the javascript to figure out what the image files probably are.  My original code was too... specific in what it looked for.  I checked in updated code last night.  So if you get the latest version  On the Ziru's branch it should work.  That said, it did work for LDM on Chrome, so you may be seeing something to do with Firefox.  I didn't test that.

> Since there are no parsers for those pages, it causes the extension to stop. 
Well, yes.  That's why I added the ability to select which chapters to load.  That said, that probably won't work for most users as they won't be able to figure out why it crashes.

On further reflection, providing a parser for Ziru probably wasn't a good idea.  There's only 5 stories, and each one has a different format.  So requires custom parsers for each.  (And one has the chapters on GoogleDocs.  I haven't the faintest idea how to parse those.)  On the other hand, I really like the Lazy Dungeon Master.

**Comment by toshiya44** [comment]
I'd suggest adding pursers for https://hellping.org/ and maybe some of nanodesu projects (the projects usually have the same layout). They're working on a lot of novels.

As for the imgur album, I think I was supposed to deselect it...
Now the issue is duplicate IDs (footnotes and stuff). Some footnote links are not working.

**Comment by dteviot** [comment]
@toshiyaa44 
> As for the imgur album, I think I was supposed to deselect it...

Looks like it's an issue with Firefox.  I'll investigate shortly.

> Now the issue is duplicate IDs (footnotes and stuff). Some footnote links are not working.

Already on my ToDo list at top of this issue.  Can you provide some URLs?

> I'd suggest adding pursers for https://hellping.org/ and maybe some of nanodesu projects

Eventually, yes.  But want to fix the items on this ToDo list first.  Then there's a couple of other sites people have already requested.  And I need to get Tab mode working properly on Firefox.  And HTTP errors handled correctly, and, well, you've seen the list.

**Comment by toshiya44** [comment]
I made an epub for all the valid links in this page https://zirusmusings.com/ldm-toc/
Duplicate links were found in both Chapter 44 and Chapter 74
https://zirusmusings.com/ldm-ch44/
https://zirusmusings.com/ldm-ch74/

**Comment by typhoon71** [comment]
I don't get those "duplicate link" in the epub I made for LDM; what are you talking about?

**Comment by dteviot** [comment]
@toshiya44
Thanks very much for the details.

@typhoon71
They're reported when you run the epub through epubcheck.

Ch44 is error in the original HTML.  There are two links to footnotes, which both have the same id of "r-1"
i.e. this
```HTML
<p>… No, not yet. The bath wasn’t sufficient. If you’re talking about a mountain inn, it has to be an onsen. 
<em>[<a id="r-1" href="#fn-1">1</a>]</em></p>
```
and this
```HTML
“Come to think of it, he also told me that he valued legs.”
<em>[<a id="r-1" href="#fn-1">1</a>]</em>
```
As a human, it's obvious that the second reference should be to the second footnote.

Ch74 is the converse, both footnotes have the same ID of "fn-1"
```HTML
<ul>
<li id="fn-1">Wiki-sensei giving a <a href="https://en.wikipedia.org/wiki/Zashiki-warashi">link</a> to save the day!&nbsp;<a href="#r-1">Return</a></li>
<li id="fn-1">Doesn’t translate well to English—Keima used counter for bodies instead of people here. He then corrected himself.&nbsp;<a href="#r-1">Return</a></li>
</ul>```

Trying to fix this automatically in a general case is difficult.  As a human I can easily deduce that the "fn-" ids are referring to the Footnotes, while the "r-" IDs are references.  From context, I can figure out which ones are supposed to go where.  But to do that in code, for other sites where the IDs have a different format (e.g. Baka-Tsuki) and may even point to other pages?  That's very hard to handle.  So hard that for this case I'm just not going to do it.

**Comment by dteviot** [comment]
@toshiya44 
> Also, are imgur albums are bugged?

Nope.  Turns out my code for handling imgur was really buggy.  (I should have known better, based on my experience with namespaces in the.opf file.)  Anyway, Firefox was fully justified in crashing when it tried to run the code.  I'm amazed that it worked on Chrome.  Anyway, fix has been checked into GitHub.

**Comment by dteviot** [comment]
@toshiyaa44
> There's also an empty box for some reason.

The raw HTML has a &lt;a&gt; tag with no href attribute and no text.  Weird, and useless.

**Comment by typhoon71** [comment]
Cheat Receptionist: images works now.
Cheat Receptionist: the parser does fail on last 3 setected links (amazon, booklive and root of the novel)

**Comment by dteviot** [comment]
@typhoon71 
> Cheat Receptionist: the parser does fail on last 3 setected links (amazon, booklive and root of the novel)

Probably because I haven't tried to fix those yet.  I'll probably just filter out the links for amazon and booklive.

> Select/unselect all still doesn't work.

Works fine for me with Chrome 51.0.2704.106m and Firefox 48.
Exactly which version are you using?
Also what other plug-ins do you have running?

**Comment by toshiya44** [comment]
Select/unselect all is working Firefox 49.0a2 too. Check if you have any script blocking/modifying extension running. 
And if it still doesn't work, try turning off e10/multiprocess mode.

**Comment by typhoon71** [comment]
I tried with chrome only, will try updating it.
I still rebuilding my firefox profile(s), so no tests there.

**Comment by typhoon71** [comment]
OK, tried with latest Vivaldi, select/unselect all is working. 
So it was on my side, tch.

**Comment by typhoon71** [comment]
Can you try "http://royalroadl.com/fiction/1233"? 
It used to work fine for me (both FFOX and chrome) but now I get this: 

![non](https://cloud.githubusercontent.com/assets/1866248/17431716/99dd51da-5afb-11e6-91fc-220a6823a47c.png)

**Comment by toshiya44** [comment]
@typhoon71 I didn't get errors (on Firefox 49).

@dteviot On http://royalroadl.com/fiction/1233 , chapter 25 has two images. Although the images were downloaded, they were not referenced in the epub. I tried unselecting all the chapters except 25, but the problem remains.

**Comment by typhoon71** [comment]
That error is on latest Vivaldi.
I should get around my FFOX thing and test there too.

**Comment by toshiya44** [comment]
Well, it looks like Viviladi is based on Opera. While Opera does support most chrome extensions, there's no guarantee that it will work. 
And since your image fetching failed, it might be related to my comment to dtevoit.

**Comment by typhoon71** [comment]
As far as I know Vivaldi is "based" on chrome (both use Blink), not on Opera.

**Comment by dteviot** [comment]
@typhoon71 @toshiya44

>Can you try "http://royalroadl.com/fiction/1233"? 
It used to work fine for me (both FFOX and chrome) but now I get this: 

The image are not showing because I removed ALL &lt;a&gt; tags to remove assorted unwanted stuff from each story.  (Mostly the “try the new beta reader” elements.)  Unfortunately, as the &lt;img&gt; tags are wrapped in  &lt;a&gt; tags, the &lt;img&gt; tags were also deleted.  So, latest set of commits include not removing links that contain &lt;img&gt; tags.
That said, I don't know why you were unable to get the images.  I get them OK.  Would be useful to know why the fetch failed. (Side note, I've spent hours trying to get useful error messages out of Chrome for XMLHttpRequest errors, with no progress.)

**Comment by dreamer2908** [comment]
@dteviot 

I got parsing error on [Mondaiji-tachi_ga_isekai_kara_kuru_soudesu_yo:Volume_10_Short_Story](https://www.baka-tsuki.org/project/index.php?title=Mondaiji-tachi_ga_isekai_kara_kuru_soudesu_yo:Volume_10_Short_Story). Screenshot: https://i.imgur.com/mkS7ZBL.png
Latest ZirusMusings branch on Google Chrome 52. 

Also, oh my, they put some translations in the thumbnail caption.

**Comment by dteviot** [comment]
@dreamer2908 
That's odd.  Works for me.  I'm using Chrome 52.0.2743.116.
And the latest commit to ZirusMusings.  "Initial support for adding arc information to chapters."  Which I did 3 days ago.  The error message tells me it had problems parsing the thumbnail.

**Comment by dteviot** [comment]
@typhoon71, @toshiya44, @dreamer2908 
I've now updated the following parsers to allow you to (manually) specify an image to use for the cover.
- RoyalRoad
- Wuxiaworld
- ZirusMusings

(Yes, I know the next request is going to be to automatically pick an image.)
As part of this work, WebToEpub no longer packs duplicate images into the epub.
Changes have been checked into ZirusMusing branch.  If you can try it out, I'll fix any issues and release the next build.
Thanks for your help and time.

**Comment by toshiya44** [comment]
When I used the extension at https://zirusmusings.com/gcr-toc/ here were some blank paragraphs after every image in the output of the following URLs,
```
http://imgur.com/DQL0KHd,E2Fmz85,ZXy33mC,Dc8bZa1,vspQ9Fh,0YG978i
https://pirateyoshi.wordpress.com/gcr-toc/gcr-illustrations/
https://zirusmusings.com/gcr2-5-illustrations/
https://zirusmusings.com/gcr3-illustrations/
https://zirusmusings.com/gcr4-illustrations/
```


Request: Please move the Check/Uncheck All button to the top. Currently it's at the bottom and for pages with a lot of links it takes to while to reach. For example http://www.wuxiaworld.com/mga-index/ has a lot of chapters.

That page also has links to several empty pages (which they call placeholders). The purser stops when it encounters those pages and gives error ``Error: Not Found``. Can you please exclude them? 

Vertical scrollbar was missing in popup mode when I used it in wuxiaworld.

There is always a horizontal scrollbar which does not work. It's not even clickable.

That royalroad chapter I mentioned earlier is fixed now :D

(Firefox 50)

**Comment by typhoon71** [comment]
I get the white pages on https://zirusmusings.com/gcr-toc/ too; I'm using chrome instead of FFox, but I get a white page at the end of illustrations gallery too, one each gallery.

**Comment by dteviot** [comment]
@toshiya44
> Setting cover image is working, although I'd really like it to use the first image link as default.

Done.

@toshiya44 @typhoon71
> When I used the extension at https://zirusmusings.com/gcr-toc/ there were blank paragraphs after every image in the output of the following URLs,

I think that's just more of the same problem we have with images. https://github.com/dteviot/WebToEpub/issues/40 It's on my list to fix, but it's going to be a while before I get to it.

> Please move the Check/Uncheck All button to the top

Done.

> That page also has links to several empty pages (which they call placeholders). The purser stops when it encounters those pages and gives error Error: Not Found. Can you please exclude them

Not easy, Parser only knows they're not there when try to fetch them.  Which stops the fetch cycle.  Note, that's a different issue to fix  https://github.com/dteviot/WebToEpub/issues/13.  That said, the generated epub doesn't have the empty chapters.

> Vertical scrollbar was missing in popup mode when I used it in wuxiaworld.

I think that's an issue with FFox 50.  It's there with FFox 49 (or 48, can't remember which) and Chrome.

> Also, there is always a horizontal scrollbar which does not work. It's not even clickable.

I think that's due to making the area scrollable.  But no slider on it because all the width is visible.

**Comment by dteviot** [comment]
@toshiya44 @typhoon71
Also, thanks for the help and feedback.
Version 0.0.0.14 has now been sent to Mozilla and Google.

**Comment by typhoon71** [comment]
I think this last version broke the autoresize on the chapter field.

**Comment by dteviot** [comment]
@typhoon71
> I think this last version broke the autoresize on the chapter field.
Using the general parser.

???
1. By "general parser" do you mean the default parser?
2. "autoresize on the chapter field"?  Do you mean the code moves up head tags if higher levels are missing, i.e &lt;h2&gt; to &lt;h1&gt;, &lt;h3&gt; to &lt;h2&gt; if there's no &lt;h1&gt;.

As far as I can tell, the default parser runs that code.
Note, the code isnt' smart enough to figure out case of the page starting with a (say) &lt;h2&gt; tag and a &lt;h1&gt; tag being elsewhere in the document.
Can you please provide a URL and more detailed description of the problem?

**Comment by typhoon71** [comment]
1. Yes, I meant the default parser, the one that gets used if there's no specific parser for the website.
2. NO, I mean This:

![geh](https://cloud.githubusercontent.com/assets/1866248/18919690/67d9e8a0-859f-11e6-98f8-03edd7b8bf69.png)

I did tell you in the past and you made it to auto-resize.

**Comment by dteviot** [comment]
@Typhoon71
> Column width auto-resize.

Oh.
That.
Truth is, I didn't fix that.
All I did was change styling on the table so that it would use the full page width.
The sizing of the columns is automatic, and unfortunately, it doesn't handle figuring out width of the title column very well.
Probably because it's a "input" element not text.
When the page is wide (i.e. Tab mode) and you've got a large screen, the layout is, well, sort of OK.
It's not easy to fix, because min-width style does not apply to table columns.  http://www.w3.org/TR/CSS21/visudet.html#min-max-widths
My 5th attempt at fixing this has been checked into the Experimental Tab branch. Please let me know what you think.

**Comment by typhoon71** [comment]
OK, it's perfect now, thanks.
As I can see this time the with of the chapter name boxes is the only one that is as large as possible, while the previous time all the "columns" were larger depending on the browser window width.
Both work(ed) but it looks better this way.

**Comment by typhoon71** [comment]
Found a regression.
When editing chapters links, after I hit apply this happens:

Cannot read property 'alwaysOpenAsTab' of undefined TypeError: Cannot read property 'alwaysOpenAsTab' of undefined
at ChapterUrlsUI.populateChapterUrlsTable (chrome-extension://agfpeiicolmhejoffeadiiildggjdkka/js/ChapterUrlsUI.js:27:73)
at ChapterUrlsUI.setTableMode (chrome-extension://agfpeiicolmhejoffeadiiildggjdkka/js/ChapterUrlsUI.js:165:18)

It happens ONLY if I edit the chapters links, if I select/unselect them there are no issues.

**Comment by dteviot** [comment]
@Typhoon71
> Cannot read property 'alwaysOpenAsTab'

D'oh!
Should be fixed now.
Also, I've added a button to clear the "Cover Image URL" text box.  Not quite the checkbox you asked for. Is it satisfactory?

**Comment by typhoon71** [comment]
Thanks for the fix (busy now but I'll test it later).
A button to clear the cover image URL is a better solution than a checkbox, being easier to use; I'm 100% satisfied. Well done.

**Comment by typhoon71** [comment]
Tested, I can confirm it's fixed and that the button is perfect.

**Comment by dteviot** [comment]
Looks like only unfixed issue is white space after some galleries.
Have raised new issue (https://github.com/dteviot/WebToEpub/issues/78) and am closing this one, as it's getting too long with too many bugs.
