### ISSUE TITLE
How to delete the "novel name" that's appearing next to "every chapter name"

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#642]
Hello, I'm using WebtoEpub to convert a wordpress site to epub.

But I would like to **make it so the name of the novel doesn't appear next to every single chapter name**. This has happened when I used it for many sites. I hope anyone could help me on this issue! Thank you!!

**Comment by dteviot** [comment]
@vanessabluellie 
It will depend on the site.
However, if you're not a programmer, probably the easiest way to fix would be to use Calibre to do a text replace.
https://manual.calibre-ebook.com/function_mode.html
