### ISSUE TITLE
Don't have hyperlinks in chapter titles.

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#643]
Hello, I'm currently converting a wordpress page to epub. But I noticed that the "chapter name" is a LINK that literally takes you to the same page where the chapter starts, and wondering whether there's some way to just make the "chapter name" normal text. This doesn't happen for all sites I used webtoepub for though. Thank you!!

**Comment by dteviot** [comment]
@vanessabluellie
Same answer as your previous question.
Probably the easiest way to fix would be to use Calibre to do a text replace.
https://manual.calibre-ebook.com/function_mode.html

That said, I'll treat this as a bug and see if I can fix it.

**Comment by dteviot** [comment]
@vanessabluellie 
To save me a little time, please provide URL to a story that has the chapter name as a link.

**Comment by vanessabluellie** [comment]
> @vanessabluellie To save me a little time, please provide URL to a story that has the chapter name as a link.

Alright! I think it was this site for this novel!
https://dustbunnytranslations.wordpress.com/wushuang-4/

**Comment by dteviot** [comment]
@vanessabluellie 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by vanessabluellie** [comment]
Thank you!

**Comment by dteviot** [comment]
@vanessabluellie 
Updated version (0.0.0.144) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by vanessabluellie** [comment]
> @vanessabluellie Updated version (0.0.0.144) has been submitted to Firefox and Chrome stores. Firefox version is available now. Chrome might be available in 1 to 3 weeks.

Thank you!!
