### ISSUE TITLE
Please add site https://noveltoon.mobi/

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#645]
I have discovered that it works on this page to a certain extent, if I select the url where the list of chapters is, it takes the story but not only the chapters, if not all the links on the page, I can't explain it, I leave the story where I did the test, the problem is that it is cumbersome because you have to go searching chapter by chapter and uncheck the rest including a Reviews page that inserts after each chapter, as an additional chapter. for long stories it is very tedious to go looking for chapters. You have to look for the first and last chapter.
What I would like is that I only select the chapters and not everything that the page contains. the page has a list of chapters

https://noveltoon.mobi/es/detail/656085/episodes
![Screenshot](https://user-images.githubusercontent.com/29169926/142714214-3c3acead-0149-481d-b774-683f69e1d270.png)

![Screenshot (1)](https://user-images.githubusercontent.com/29169926/142714216-16c42409-5ad3-450e-b9de-dedfecd6c417.png)

**Comment by dteviot** [comment]
@bichitoxxx 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested against https://noveltoon.mobi/es/detail/1287206/episodes, it worked for 20 chapters, then site started asking to use App.  But then, I didn't have account on site.

For my notes: 75 minutes work

**Comment by bichitoxxx** [comment]
Now if you take only the chapters of the book and all the data and not the rest of the page. But I get this error
![Screenshot](https://user-images.githubusercontent.com/29169926/142747241-dd4b1557-e272-4f21-b8bf-a04f64925695.png)

![Screenshot (1)](https://user-images.githubusercontent.com/29169926/142747247-36659786-d748-4052-a342-c6b155d38b70.png)

**Comment by bichitoxxx** [comment]
ok is a failure in all books in the same chapter from chapter 21. from that chapter forces you to continue reading in the mobile app. With all the ones that I have tried the same. Thank
![Screenshot (2)](https://user-images.githubusercontent.com/29169926/142747390-1b014063-dd2f-4cc4-befa-d8847fdc2acc.png)
.

**Comment by dteviot** [comment]
@bichitoxxx 
Updated version (0.0.0.144) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by bichitoxxx** [comment]
Thanks I will update it
