### ISSUE TITLE
Modify Template Page to Include Page Target

### ISSUE THREAD

**Issue by Synteresis** [dteviot/WebToEpub#646]
<details>
<summary>Personal Notes</summary>
~~Create two templates? 

One with the technical aspects of each function that specifies exactly how everything works. How it gets cleaned. Where it fails. How it fails. Where is the dom from. How many times the function is called. What page it is called on. Maybe how to resolve promises and such. Maybe how to include error handling in the code so that when it fails, it doesn't fail silently and download whatever remains. Add an option under advanced options called developer options? Lets the toggling of errors within the download so it fails loudly and specifies location of failure instead of failing silently. Provide what manually setting each tag would do. 

The other can be the basics with what page it affects and what you can do with them. You know. Basic.~~
</details>

**Comment by dteviot** [comment]
I think two templates would confuse people.  Which one should they use?  How do they discover both of them?
Also, based on number of people who have written parsers, I'm not sure there's a lot of value in improving the documentation.  Although maybe not many do it because the documentation is inadequate.
Also, while detailed docs are nice, is there a 90%/10% point?  e.g. What 10% of the work gives you 90% of the benefit?

**Comment by Synteresis** [comment]
Hmm. You are right. Perhaps I should write up some docs for personal use in the future.

**Comment by dteviot** [comment]
@Synteresis
Let me save you some work.
The following functions are called against the Table of Contents web page  (usually just once or twice):
* getChapterUrls
* extractTitleImpl
* findCoverImageUrl
* extractAuthor
* extractLanguage
* extractSubject
* extractDescription
* getInformationEpubItemChildNodes

These functions are called for each chapter page:
* fetchChapter
* findChapterTitle
* findContent  (note, this might also be called against the Table of contents page)
* customRawDomToContentStep
* removeUnwantedElementsFromContentElement
* findParentNodeOfChapterLinkToRemoveAt
* preprocessRawDom
* removeUnusedElementsToReduceMemoryConsumption

Special cases:
* onStartCollecting    (called when user presses the "Pack EPUB" button)
* cleanInformationNode (called for each root node returned by getInformationEpubItemChildNodes)

**Comment by Synteresis** [comment]
@dteviot 

Thank you, I had traced to completion only about half the list, so this will be helpful. Ill add a small note to each function as a hotfix for now.
