### ISSUE TITLE
Ranobes first page only

### ISSUE THREAD

**Issue by RealNasty** [dteviot/WebToEpub#647]
It only fetches 25 latest chapters of the page

Link to novel
https://ranobes.net/novels/1165550-divine-path-system.html

 - OS: Android
 - Browser Kiwi
 - Version 96.0

**Comment by dteviot** [comment]
@RealNasty
You're probably running it in mobile mode.
Try running it in desktop mode

**Comment by RealNasty** [comment]
@dteviot 
Tried it but it has the same behavior

**Comment by dteviot** [comment]
For my notes, looks like it's inside the &lt;script&gt; element starting with"window.__DATA__ = "
There's a JSON object with layout
```javascript
{
  "book_title": "Divine Path System",
  "book_link": "https://ranobes.net/novels/1165550-divine-path-system.html",
  "book_id": 1165550,
  "chapters": [
    {
      "id": "1614618",
      "title": "Chapter 206: I Am A Master At Reading Women's Emotions",
      "date": "2021-11-23 21:09:16",
      "showDate": "11 hours ago"
    },
```

I'll see what I can do in the next few days.

**Comment by dteviot** [comment]
@RealNasty @SirGryphin
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with 
* https://ranobes.net/novels/1165550-divine-path-system.html
* https://ranobes.net/novels/1204915-marvels-superman.html

For my notes: aprox 90 minutes work

**Comment by taint-stack** [comment]
It works, thanks

OS: Android
Browser: Kiwi
Version: 93.0

**Comment by SirGryphin** [comment]
Chrome test version working for me now 👍 thank you.

**Comment by Arsur3215Loki** [comment]
Would it also work with Opera? I'm using Opera GX.

**Comment by SirGryphin** [comment]
@Arsur3215Loki chrome extension should work, I've used other chrome extensions without a problem on Opera and Brave without problems.

**Comment by Flwk** [comment]
@dteviot Thank you very much ! :)

**Comment by ziyanoffl** [comment]
Just wanted to let you know that the previous test version that you gave to issue #562 worked too.

**Comment by RealNasty** [comment]
@dteviot works perfectly. thank you

**Comment by dteviot** [comment]
@RealNasty @SirGryphin @Flwk @ziyanoffl @Arsur3215Loki @taint-stack 
Updated version (0.0.0.144) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
