### ISSUE TITLE
[feature request] find missing chapters via wayback and merge

### ISSUE THREAD

**Issue by DefectiveByDesign** [dteviot/WebToEpub#649]
**Is your feature request related to a problem? Please describe.**

It's rather annoying when web novels that have 200+ chapters pull like the first 50 chapters to make you buy them on amazon. This can be easily bypassed with the wayback machine / internet archive, but there is no automatic way to merge missing chapters with the existing chapters afaik.

**Describe the solution you'd like**

I'd like a checkbox feature put under the advanced section that detects when a novel goes from 1-2-3-4--50-51-52, and pulls the missing chapters from internet archive. Some novels don't use numbers though, so some manual intervention might be required for those.

**Describe alternatives you've considered**

Right now? Make a epub from wayback, then the novel site, manually merge them with some utility, or just read one until the skip, and finish it from the other. Either way is extra work, but it's simpler to read multiple files atm. See below for a better suggestion.

**Additional context**

This feature does not need to be specifically implemented if a generic merge feature is implemented. I would be perfectly happy to just do a merge process, which would help with ongoing novels, and that feature has already been requested. I don't think a click and drag approach will work on mobile though, so it would have to work with existing files, if that is possible.

**Comment by dteviot** [comment]
@DefectiveByDesign 
Sorry, no.  That would be violating copyright, which will get WebToEpub permanently banned from the Chrome store.
Also, it would be a great deal of effort to implement. See: https://github.com/dteviot/WebToEpub/issues/634
