### ISSUE TITLE
Bugs with Reset Button

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#65]
The following items are not cleared/reset when Reset is clicked.
- [x] List of Images.
- [x] Chapters list.
- [x] Assorted advanced settings (e.g. Translator)
- [x] Cover image URL

**Comment by belldandu** [comment]
I would imagine that this is being caused by values being stored in a
memory buffer (typical javascript objects).

Best thing to do would be to make the reset button trigger a function that
clears and recreates these objects how they originally where when the page
was first loaded.

**Comment by belldandu** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management

**Comment by dteviot** [comment]
@belldandu 
No, it's caused by me not clearing them when reset is pressed.

**Comment by belldandu** [comment]
Essentially the same thing i said. Your not doing garbage collection so
values stay stored in memory.

**Comment by dteviot** [comment]
> Essentially the same thing i said. Your not doing garbage collection so
values stay stored in memory.

Nope.  Elements are added to UI based on the web page that has been read.  e.g. <img> tags are added to the UI, so that user can pick the cover image.  These elements need to be deleted when reset is pressed.

**Comment by dteviot** [comment]
Items on UI are now cleared.
