### ISSUE TITLE
wnmtl.org failed with network error Failed to fetch

### ISSUE THREAD

**Issue by thanarang** [dteviot/WebToEpub#650]
Error message:

Error: Fetch of URL 'https://api.mystorywave.com/story-wave-backend/api/v1/content/chapters/page?sortDirection=ASC&bookId=2122&pageNumber=1&pageSize=1000' failed with network error Failed to fetch.
    at FetchErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:158:45
    at async WnmtlOrgParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/WnmtlOrgParser.js:13:21)
    
  when attempting to convert to epub.
  
  Was not an issue yesterday.

 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.45

**Comment by dteviot** [comment]
@thanarang 
I just tried https://wnmtl.org/book/8399-ultimate-scheming-system, with chapters 1 and 25.
Seems to be working fine.

The error "failed with network error Failed to fetch" usually means some sort of networking issue, with your browser being unable to contact the server.
If you try putting the URL mentioned above 'https://api.mystorywave.com/story-wave-backend/api/v1/content/chapters/page?sortDirection=ASC&bookId=2122&pageNumber=1&pageSize=1000' into your browser, does it work?
If it does, try using WebToEpub again.

**Comment by thanarang** [comment]
Apologies, must have been an issue on my end.
Removing the extension and reinstalling it again seems to have fixed the issue.
