### ISSUE TITLE
Sqlite3 db update request

### ISSUE THREAD

**Issue by killswordnew** [dteviot/WebToEpub#651]
**Is your feature request related to a problem? Please describe.**
Is it possible to write the chapters to a sqlite3 db file (in a google drive) instead of epub file. Feature to
archive the chapters will help readers maintain copy of the book

**Describe the solution you'd like**
Given a google drive sqlite3 db file link, I expect this plugin will write to it instead of epub file. If the
sqlite3 is not empty, it will append to existing content.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dteviot** [comment]
@killswordnew 
I don't see how this would work. How would you read the chapters if they're in a SQLite database?
I suggest you look at
* https://github.com/Flameish/Novel-Grabber, or
* https://github.com/JimmXinu/FanFicFare
