### ISSUE TITLE
Could not find content element for web page

### ISSUE THREAD

**Issue by lunevale** [dteviot/WebToEpub#652]
On Chrome, when using WebtoEpub default parser, the test comes out fine but when I manually insert the links, the content can't be found.

1. Go to https://cangji.net
2. Click on Qíang Jín Jíu under Novels and start launch webtoepub default parser
3. Received Error: Could not find content element for web page 'https://cangji.net/qiangjinjiu/qiangjinjiu-c1'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:493:23
    at async Promise.all (index 0)
    at async DefaultParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17

I was still able to grab the chapters in April '21 for up to 100 chapters.

**Screenshots**
It looked fine when I tested the page before applying it
![image](https://user-images.githubusercontent.com/73226124/143527031-c7db633d-93da-4516-bd96-b2d216daa9a5.png)

But no content could be found
![image](https://user-images.githubusercontent.com/73226124/143527123-22ac8515-4756-4c23-b3fa-943f8e6d5288.png)

 - OS: Win10
 - Browser Chrome
 - Version 96.0.4664.45

**Additional context**
I don't think they changed the layout of the website and I always used the default parser to grab the chapters before so I'm not sure what's the problem now.

**Comment by lunevale** [comment]
It suddenly works again so I'm closing this issue.

**Comment by dteviot** [comment]
@lunevale 
>It suddenly works again so I'm closing this issue.

Good to hear.
