### ISSUE TITLE
https://www.worldnovel.online/

### ISSUE THREAD

**Issue by Yukasharia** [dteviot/WebToEpub#653]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@Yukasharia 
I just tried https://www.worldnovel.online/novel/i-woke-up-piloting-the-strongest-starship-so-i-became-a-space-mercenary/, first chapter and it seems to work.
Please provide URL to story that doesn't work and description of the problem.

**Comment by dteviot** [comment]
@Yukasharia 
Closing due to lack of response.
