### ISSUE TITLE
Please add site https://www.ptwxz.com/ 

### ISSUE THREAD

**Issue by Hogesyx** [dteviot/WebToEpub#656]
This is actually one of the main site that most other site crawl/scrap raw from. My js is a little rusty so I kinda got stucked here, so not sure if anyone else is up to the challenge. The main issue is the chapter page uses a big div wrapper to wrap multiple components + main text body, however main text body does not have a unique wrapper.

Main site
https://www.ptwxz.com/ 

Sample book page:
https://www.ptwxz.com/bookinfo/1/1000.html
the book id 1000 seems to be a combination of their subfolder + unique id, 1 being the subfolder and unique id in this case is 000

Book cover:
https://www.ptwxz.com/files/article/image/1/1000/1000s.jpg
1/1000 can be retrieved from book main page url, appending book id with s.jpg will return the book cover.

Chapter Index:
https://www.ptwxz.com/html/1/1000/index.html
replacing /bookinfo/ with /html/ will return the index page, chapter can be retrieved using div.centent

Chapter page:
https://www.ptwxz.com/html/1/1000/3223864.html
the number after book id seems to be random, div#content.fonts_mesne basically contains titles+misc links+ chapter body.

**Comment by dteviot** [comment]
@Hogesyx 
I looked at chapter https://www.ptwxz.com/html/13/13369/9687785.html
For chapter content, you want the selector "div#content"
You can remove junk with "div.toplink, table"

To get chapters, try something like
```javascript
    getChapterUrls(dom) {
        let tocUrl = dom.baseURI.replace("bookinfo", "html");
        let tocDom = (await HttpClient.wrapFetch(tocUrl)).xhr;
        let table = xhr.responseXML.querySelector("div.centent");
        return util.hyperlinksToChapterList(table);
    }
```

**Comment by dteviot** [comment]
@Hogesyx 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://www.ptwxz.com/bookinfo/1/1000.html, chapter 1

For my notes: 90 minutes, and not fun.

**Comment by Hogesyx** [comment]
@dteviot will take a look later, this is my half completed version of the parser.

`    async getChapterUrls(dom) {
        let tocUrl = dom.baseURI.replace("bookinfo", "html").replace(".html", "");
        return HttpClient.wrapFetch(tocUrl, this.makeOptions()).then(function (xhr) {
            let menu = xhr.responseXML.querySelector("div.centent");
            return Promise.resolve(util.hyperlinksToChapterList(menu));
        });
    }
    
    makeOptions() { 
         return ({ 
             makeTextDecoder: () => new TextDecoder("gb18030") 
         }); 
     } 
     
    static extractBookId(dom) {
        let bookId = dom.baseURI.replace(/^.*(\\|\/|\:)/, '').replace(".html", "");
        return bookId
    }
    
    findCoverImageUrl(dom) {
        let id = PtwxzParser.extractBookId(dom);
        let cvrUrl = dom.baseURI.replace("bookinfo", "files/article/image").replace(".html", "/"+id+"s.jpg");
        return cvrUrl;
    }`

**Comment by Hogesyx** [comment]
> @Hogesyx Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
> 
> Tested with https://www.ptwxz.com/bookinfo/1/1000.html, chapter 1
> 
> For my notes: 90 minutes, and not fun.

Thanks @dteviot, tested it with a couple of title including large ones and it seems to work great.

**Comment by dteviot** [comment]
@Hogesyx 
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks
