### ISSUE TITLE
StoriesOnline

### ISSUE THREAD

**Issue by balefull** [dteviot/WebToEpub#658]
On https://storiesonline.net behavior has changed for stories on non-member accounts. As a result WebToEpub is now only loading partial chapters for us non-paying readers.

Now, in order to read the end of a story you need to click on a javascript link at the bottom which says, "Click to Load text..." which is then replaced by another link which says, "Another click to load text..." after clicking the second link it will load the end of the story.

You can test that here if your account does not have a membership: 
https://storiesonline.net/s/14679:182473/three-square-meals-chapter-1

**Comment by dteviot** [comment]
@balefull,
Unfortunately, the site has done this to stop downloading without a paid account.
And if I was to modify WebToEpub to bypass this, WebToEpub would be removed from the Chrome store, permanently.

So, sorry, beyond suggesting a paid account, I can't help you.
