### ISSUE TITLE
Images from Previous "Pack EPUB" inserted in new EPUB

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#66]
Steps to reproduce.
1. Browse to site with multiple chapters.  e.g. https://zirusmusings.com/gcr-toc/ and open WebToEpub
2. Select a range of chapters with images. e.g. chapters of book one.
3. Click "Pack EPUB"
4. Now select a different range of chapters with images.  e.g. chapters of book two
5. Click "Pack EPUB"
6. The new EPUB will contain images for book one (even though there are no links to them in the text) as well as book two.

**Comment by belldandu** [comment]
Caused by https://github.com/dteviot/WebToEpub/issues/65 see
https://github.com/dteviot/WebToEpub/issues/65#issuecomment-237022476

**Comment by dteviot** [comment]
@belldandu

No, it's because I don't (yet) clear the map of collected images when we start the pack.  However, this needs to be done carefully or it will break Baka-Tsuki.

**Comment by dteviot** [comment]
Has been fixed for a while now.
