### ISSUE TITLE
https://novelhi.com/

### ISSUE THREAD

**Issue by Vgkd** [dteviot/WebToEpub#662]
https://novelhi.com/
This is a very good website for machine translated novels but my problem is Webtoepub can't detect chapters at all I've tried everything but it didn't work so please will you look into this problem.
Thank you for your time and hardwork

### Provide URL for web page that contains Table of 
Contents (list of chapters) of a typical story on the site
https://novelhi.com/s/index/Martial-Peak

### Did you try using the Default Parser for the site?  If not, why not?

Yes I've tried but it still doesn't detect chapters

**Comment by dteviot** [comment]
@vgkd
Looks doable.  Will probably be a few days before I get this done.


Some notes for me.
1. Looks like doing something with javascript to hide links to chapters.
For novel https://novelhi.com/s/index/Divine-Beast-Adventures
The code associated with chapter was:
```html
<a onclick="gtag_report_conversion('1262260612777096178','1459463965887660032')">
                            <span>Chapter 1</span>
                        </a>
```

2. Chapter 1 called https://novelhi.com/book/1262260612777096178/1459463965887660032.html
3. Which eventually redirected to https://novelhi.com/s/Divine-Beast-Adventures/1

Chapter content looks simple
Wanted content selector is "#readcontent #showReading"
Chapter title selector is "#readcontent .book_title h1"

**Comment by dteviot** [comment]
@Vgkd

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://novelhi.com/s/Divine-Beast-Adventures
Notes 
1. Chapters 105 and beyond were locked (so WebToEpub only got first paragraph.)
2. I think site tries to detect scrapers, and will return 404 for all requests after that point.  Need to hard reset browser after that.

For my notes: 75 minutes work.

**Comment by Vgkd** [comment]
@dteviot 
Thank you for your work.
I've done all above steps but its still not detecting chapters 😭
![Screenshot_2021-12-04-16-09-20-918_com kiwibrowser browser](https://user-images.githubusercontent.com/95336559/144706723-0ec7949f-b390-4ec5-a51c-eaca0518a0ec.jpg)
That is what im getting.

**Comment by Vgkd** [comment]
@dteviot 
Ive tried on laptop and it works thanks 😄
but mostly i use kiwi browser and it doesn't work there but still thank you very much for this wonderful extension🙏

**Comment by dteviot** [comment]
@Vgkd 
If it works on a laptop, but not mobile, set Kiwi browser to desktop mode.

**Comment by Vgkd** [comment]
@dteviot 
Yes I've set my kiwi browser on desktop site but still doesn't detect chapters.

**Comment by Vgkd** [comment]
@dteviot 
I'm happy with this extension working on laptop so you can close this issue 👍

**Comment by dteviot** [comment]
@Vgkd 
Reopen, so I can let you know when I send updated version to Chrome and Firefox stores.

**Comment by Vgkd** [comment]
@dteviot it was working perfectly but now again this message stating to pop up 
![IMG_20211225_094527](https://user-images.githubusercontent.com/95336559/147377420-bfdbd308-014e-471b-a424-733bd51f809d.jpg)

**Comment by dteviot** [comment]
@Vgkd 
Site has changed value of chapter URLs.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://novelhi.com/s/God-Level-Farm

For my notes, 20 minutes work

**Comment by Vgkd** [comment]
@dteviot  

Thanks 🙏🙏

**Comment by dteviot** [comment]
@Vgkd 
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
