### ISSUE TITLE
Please add site https://cangji.net/

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#665]
https://cangji.net/

**### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site**
There's no actual page for a tables of contents, but it appears in a format of a blocky format of chapters listed one by one and cannot be viewed all at once considering there's no TOC. But perhaps if support could be added to this site (https://cangji.net/),  we can take the sites of each chapter and add them in manually one by one by clicking "Edit Chapter URLs". 

**Did you try using the Default Parser for the site? If not, why not?**
Yes, but it doesn't detect any chapters... On the page where all the chapters are listed, no chapters are detected, but if I randomly go to like Chapter 1, WebtoEPUB will detect it, but the EPUB that's generated cannot be opened. And when converted to PDF, the file was empty.

Apologies for the inconvenience. Thank you!!

**Comment by dteviot** [comment]
@vanessabluellie 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with ToC for: 
* "Fox Demon Cultivation Manual"  1st ToC page: https://cangji.net/category/yaohu/
* "Time-Limited Hunt" 1st ToC page: https://cangji.net/category/xianshishoulie/

(and a couple of chapters from each)

For my notes: time taken 19 minutes

**Comment by vanessabluellie** [comment]
> @vanessabluellie Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
> 
> Tested with ToC for:
> 
> * "Fox Demon Cultivation Manual"  1st ToC page: https://cangji.net/category/yaohu/
> * "Time-Limited Hunt" 1st ToC page: https://cangji.net/category/xianshishoulie/
> 
> (and a couple of chapters from each)
> 
> For my notes: time taken 19 minutes

THANK YOU SO MUCH, it worked perfectly!!

**Comment by dteviot** [comment]
@vanessabluellie 
Reopen, so I know to notify you when new version uploaded to Chrome and Firefox stores.

**Comment by vanessabluellie** [comment]
> @vanessabluellie Reopen, so I know to notify you when new version uploaded to Chrome and Firefox stores.

You're so nice, thank you!!

**Comment by dteviot** [comment]
@vanessabluellie
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
