### ISSUE TITLE
Ranobes.net aggressive antibot system

### ISSUE THREAD

**Issue by apaxc** [dteviot/WebToEpub#666]
**Describe the bug**
Overly aggressive antibot system

**To Reproduce**
Go to Ranobes.net and download a novel normally.
The overly aggressive antibot system blocks the browser and WebToEpub stops searching new chapters, leaving the novel halfway done. 
I have turned ' Max web pages to fetch simultaneously ' to 1 from the usual 8 I had. But this does not seem to do much as on ranobes per page there are 25 chapters and WebToEpub crawls through all these at once and therefore triggering the antibot system

**Expected behavior**
When downloading a novel on the site ranobes.net, to get the full epub with all its chapters but currently, it is not possible as the aggressive antibot system detects the browser and therefore blocks.

It would be great to have an option for the extension "WebToEpub" to be able to slow down, the number of pages it crawls through.

For an example as I tried to download the novel it only got 300 chapters out of 2300
https://i.imgur.com/UpkUGdz.png
This is with the setting  'Max web pages to fetch simultaneously 1'

**Screenshots**
https://i.imgur.com/UpkUGdz.png 300 chapters out of 2300

https://i.imgur.com/dBjf8wg.png Ranobes.net Antibot system

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave, Firefox
 - Version Brave. V1.32.115
 -

**Additional context**
Antibot system triggering too easy.

**Comment by dteviot** [comment]
@apaxc 
Duplicate.  See: https://github.com/dteviot/WebToEpub/issues/663

Summary:
Download from test builds (as fixed version has not been submitted to Chrome & Firefox stores yet) then set throttling under advanced options.

**Comment by dteviot** [comment]
@apaxc
Actually, I misread your problem.  Looks like you just need to set the throttling option. 
![image](https://user-images.githubusercontent.com/5157081/144728302-9498dbf8-dbb6-4ec6-b9dc-181b68083eab.png)

**Comment by RealNasty** [comment]
@apaxc what works for me even if it's a colossal novel is to first setup the throttle to 3 sec when fetching chapters, when it's done you can set it back to default and check the  create epub 3 option and keep it as 1 for simultaneous fetching.

**Comment by dteviot** [comment]
@apaxc 
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
