### ISSUE TITLE
Please add site https://www.worldnovel.online/

### ISSUE THREAD

**Issue by Kucingmeong2** [dteviot/WebToEpub#667]
Please fix this, I have make epub from this website only get 100 chapter not full all chapter.
Please fix this 😭😭😭

Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@Kucingmeong2 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.


Tested with:
* https://www.worldnovel.online/novel/library-of-heavens-path/
* https://www.worldnovel.online/novel/its-my-throne/

For my notes 33 minutes work

**Comment by Kucingmeong2** [comment]
Thank you 🙏🙏🙏

**Comment by dteviot** [comment]
@Kucingmeong2 
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
