### ISSUE TITLE
https://meionovel.id/

### ISSUE THREAD

**Issue by Kucingmeong2** [dteviot/WebToEpub#668]
Hello 
Sry for add web novel again, but can you add this web. I have test this web but the chapter not appear.
Please help me 🙏🙏🙏🙏

Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@Kucingmeong2 

You will need to give me more information.  
I just tried, https://meionovel.id/novel/sweetest-top-actress-in-my-home/ and it seems to work fine for chapters 1 and 877

Please provide URL of Table of Contents for story that does not work.

**Comment by Kucingmeong2** [comment]
> @Kucingmeong2
> 
> You will need to give me more information. I just tried, https://meionovel.id/novel/sweetest-top-actress-in-my-home/ and it seems to work fine for chapters 1 and 877
> 
> Please provide URL of Table of Contents for story that does not work.

![Screenshot_20211220-203736_Kiwi Browser](https://user-images.githubusercontent.com/96341505/146768326-36853845-9e89-4977-9c18-f4fa8d5b7309.jpg)
Not work. I use kiwi browser on android not pc 🙏🙏🙏🙏

**Comment by Kucingmeong2** [comment]
![Uploading Screenshot_20211220-203720_Kiwi Browser.jpg…]()

**Comment by Kucingmeong2** [comment]
This 
![Uploading Screenshot_20211220-203720_Kiwi Browser.jpg…]()

**Comment by Kucingmeong2** [comment]
![Uploading Screenshot_20211220-203720_Kiwi Browser.jpg…]()

**Comment by Kucingmeong2** [comment]
![Screenshot_20211220-203720_Kiwi Browser](https://user-images.githubusercontent.com/96341505/146789496-19e2fd0f-d44b-4065-ac2a-5f5d3e51ddbd.jpg)

**Comment by dteviot** [comment]
@Kucingmeong2 
There are a couple of things you could try.
1. After opening https://meionovel.id/novel/sweetest-top-actress-in-my-home/, scroll down until the list of chapters appears, then try opening WebToEpub.
2. Run Kiwi Browser in desktop mode.

**Comment by Kucingmeong2** [comment]
> 

Ok, I try 🙏🙏🙏

**Comment by Kucingmeong2** [comment]
![Screenshot_20211221-115724_Kiwi Browser](https://user-images.githubusercontent.com/96341505/146868540-dfd2172f-f60f-4cee-9100-b662bea80949.jpg)
Thank you 🙏🙏🙏🙏

**Comment by dteviot** [comment]
@Kucingmeong2 
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
