### ISSUE TITLE
wnmtl.org chaps doesn't show

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#671]
it doesn't show up in Android kiwi and Firefox nightly all latest versions

**Comment by dteviot** [comment]
@Dlordload 
It seems to work for https://wnmtl.org/book/2484-tales-of-herding-gods, on Desktop Chrome.
Did you try running in Desktop mode?

**Comment by Dlordload** [comment]
@dteviot okay seems like it was my settings that messed up with my browsers
