### ISSUE TITLE
Parser Request: NovelPub

### ISSUE THREAD

**Issue by B-read** [dteviot/WebToEpub#673]
So [Novelpub](https://www.novelpub.com/index) uses a table contents system that spans across multiple pages like
```
https://www.novelpub.com/novel/reincarnation-of-the-strongest-sword-god-lnv-12121825/chapters/page-1
https://www.novelpub.com/novel/reincarnation-of-the-strongest-sword-god-lnv-12121825/chapters/page-30
```
but the url formatting of each chapter still has a generic format like 
```
https://www.novelpub.com/novel/novel-title/novelcode-chapter-number
```
For example
```
https://www.novelpub.com/novel/reincarnation-of-the-strongest-sword-god/16-chapter-1
https://www.novelpub.com/novel/reincarnation-of-the-strongest-sword-god/16-chapter-2686
```
So far my problem is that I can't seem to find a parser that can take advantage of this formatting. It would be nice to hear some insight about it on whether a parser can be created or not.

Thank you so much for this extension and all the hardwork!

**Comment by dteviot** [comment]
@B-read 
Seems to be same site layout as https://www.lightnovelworld.com/

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

I tested against https://www.novelpub.com/novel/this-young-master-is-not-cannon-fodder

For my notes: 56 minutes.  (site had changed a bit, so parser needed updating.)

**Comment by B-read** [comment]
Aight I got to test it out right now and it worked perfectly! 

Thank you so much!

**Comment by dteviot** [comment]
@B-read 
Reopen, so I know to notify you when updated version submitted to Chrome and Firefox stores.

**Comment by dteviot** [comment]
@B-read 
Updated version (0.0.0.146) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
