### ISSUE TITLE
Please add site https://lightnovelreader.org/

### ISSUE THREAD

**Issue by seizue** [dteviot/WebToEpub#675]
- https://lightnovelreader.org/

**Comment by dteviot** [comment]
Tested against https://lightnovelreader.org/the-regressed-demon-lord-is-kind-824955

For my notes: 45 minutes work

@seizue 
Please leave this open so I know to inform you when version has been submitted to Chrome and Firefox stores.  (Might be in a week or two.  They get a bit testy if I submit too frequently.)

**Comment by dteviot** [comment]
@seizue 
Updated version (0.0.0.146) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
