### ISSUE TITLE
Please update support for website [Archive of Our Own]

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#677]
**Ao3**:
-The chapter title is displayed twice. first using h1 tag, the second using div and h2 tag. please remove this second title
-the notes (author's note) is displayed using div and h2 tag, can you change the h2 tag to other tag? changing tag is impossible using css

I'm using this fic: https://archiveofourown.org/works/31414547/chapters/77693162
screenshot of the chapter using my preferred epub reader:
![Screenshot_2](https://user-images.githubusercontent.com/70971903/150435938-49f21b62-2c98-4ce5-8720-d670e3fa5c3e.png)
![Screenshot_3](https://user-images.githubusercontent.com/70971903/150435947-1b6efc8d-bb36-4941-8bcd-4379d9608aa8.png)

is the screenshot more helping or annoying? if it's not helping, I'll leave it out next time.
Edit: done.

**Comment by dteviot** [comment]
@SpiralBaka
Please split this into two issues.  I makes it easier for me for traceablity.
I suggest creating new issue and putting WebNovel there.
Screenshot is helpful.

**Comment by dteviot** [comment]
@SpiralBaka 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

>The chapter title is displayed twice. first using h1 tag, the second using div and h2 tag. please remove this second title

I think I've fixed the issue with the chapter title appearing twice.


> the notes (author's note) is displayed using div and h2 tag, can you change the h2 tag to other tag? changing tag is impossible using css

You should be able to alter the look of these tags with css.  They're inside a div with a class of "prefix", so I think you can use a css rule like
>.prefix h2 { text-align: left; }

(well, you'll need to add the size info, CSS isn't my strong suit.)

Tested with https://archiveofourown.org/works/31414547/chapters/77693162

For my records: 31 minutes.

**Comment by SpiralBaka** [comment]
It worked. the problem with "notes" is actually the size, I could include css that change that h2 "notes", but my epub reader automatically made header tags bigger without considering the css inside the book. h2 and h1 that are not titles are especially annoying. this is not a big problem though, because I don't include author's notes most of the time.

however, now the notes uses h3 tags. so it's no longer annoying.
thank you. (though it's probably just a coincidence)

**Comment by dteviot** [comment]
@SpiralBaka 
https://github.com/dteviot/EpubEditor might be useful to you.  
You can find a pre-built version at https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8
If you don't have the javascript skill to write a script to change the .prefix h3 elements, let me know and I'll write it.

**Comment by dteviot** [comment]
@SpiralBaka 
Updated version (0.0.0.146) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
