### ISSUE TITLE
Please update support for website [Webnovel]

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#678]
**Webnovel**:
-Please fix the metadata (is that what's it's called?): [book title] and [author] data
-please change the downloaded cover to the one with higher quality. currently it's using [150.jpg], I'd like to to use the [600.jpg] one, the one that's displayed on the actual page.
-please add [remove author note] option to this site as well.
link to the fic: 
https://www.webnovel.com/book/phil---the-owl-in-mcu_22209267905938205
Screenshot:
![Screenshot_4](https://user-images.githubusercontent.com/70971903/150442217-0ae416ff-4358-4525-80fb-5494b0d62106.png)
![Screenshot_5](https://user-images.githubusercontent.com/70971903/150442055-76d30abf-bbde-4242-bccb-8f0824196c3f.png)
![Screenshot_6](https://user-images.githubusercontent.com/70971903/150442062-6e613e37-72e5-4162-a0c7-c31cb25e34c0.png)

**Comment by dteviot** [comment]
@SpiralBaka 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Fixes:
1. Get correct title text
2. Get author
3. Get large size image for cover
4. Option to remove "Creators' Thoughts" (A.K.A "Author Notes")

Tested with https://www.webnovel.com/book/phil---the-owl-in-mcu_22209267905938205

For my records 63 minutes work.

**Comment by SpiralBaka** [comment]
Ok. it worked, thank you.

**Comment by dteviot** [comment]
@SpiralBaka 
Updated version (0.0.0.146) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
