### ISSUE TITLE
how to add chapter urls manually?

### ISSUE THREAD

**Issue by mnioq** [dteviot/WebToEpub#679]
sometimes there are missing chapters i need to bulk copy and paste in the "edit chapter list urls" but the formatting of the links can be an issue if there were many urls since i have to manually edit each line. is there an add urls button i missed or a box needs to be checked for copied links or something? 
sorry for the inconvenience

**Comment by dteviot** [comment]
@mnioq 
It's a bit hard to say unless I know exactly what you're having a problem with.  Some screenshots might help.
That said, what I normally do is: 
1. Copy the text from the edit chapter list screens and paste into Notepad++ and edit it there.  (You can use macros to automate the work.)
2. Then copy back into the WebToEpub screen.

**Comment by mnioq** [comment]
that works! thank you!
