### ISSUE TITLE
WebtoEpub updater (novels)

### ISSUE THREAD

**Issue by K1mH0** [dteviot/WebToEpub#680]
I've been using WebtoEpub for a while and I've been meaning to ask for a function that has been mentioned before. It's a matter of updating books that are being updated constantly; Currently, i'm getting few chapters at a time and merging them manually. I felt that it was unneccarily repetitive and hope for a feature? (or an app on its own) for updating the files (preferably in the calibre library)

= Maybe allowing us to set a website per book may help its direction?

**Comment by dteviot** [comment]
@K1mH0 
Have you looked at https://github.com/dteviot/MergeWebToEpub?
You can pick up the built image from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8

**Comment by K1mH0** [comment]
Yeah I'm currently using MergeWebtoEpub for merging the additional chapters.
Was hoping for a way to update chapters automatically

**Comment by dteviot** [comment]
@K1mH0 
Sorry, but that's the best I can do.  (It's what I do myself.)
Unfortunately, trying to automate updating existing epub files is just to difficult in a web browser.

**Comment by K1mH0** [comment]
No Problem! Was wondering if there was such a way to do so otherwise~ Thanks for you work!
