### ISSUE TITLE
Add regex box to remove junk texts.

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#681]
@dteviot 

Hello devs, 
please add box to remove unnecessary texts in the settings option which supports simple regex.
Thanks...

**Comment by dteviot** [comment]
@budikesuma 
Please provide more details of what you want.  Ideally with an example.
Note, my opinion on your suggestion is: https://blog.codinghorror.com/parsing-html-the-cthulhu-way/
But seriously, a regex in the settings would be applied to every site.  Probably not something you want.

Finally look at: https://github.com/dteviot/EpubEditor, you can write a javascript snippet to edit the epub, and do it much more safely than a regex.  (Pre-built version of EpubEditor can be found at https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.)

**Comment by budikesuma** [comment]
@dteviot  

what i meant is the selector box to remove elements such as in the initial view of unsupported site sources, this must also be in the supported site source view.

Example: 

**Selector for Elements to remove:**  `p[style="text-align: center";], Read only from[^>]*?[.]com`

.
![Screenshot_20220125-171222_Browser~2](https://user-images.githubusercontent.com/50254552/150959630-e65fae02-bbce-4eb9-be6b-011bb3a5aef0.jpg)

**Comment by dteviot** [comment]
@budikesuma 
You can use https://github.com/dteviot/EpubEditor, (which I referred to in my previous post) to do this with epubs you've already collected.
If you want to do this automatically, for a site that WebToEpub already knows, then you should find the parser for the site and update the function removeUnwantedElementsFromContentElement.
https://github.com/dteviot/WebToEpub/blob/755ed01500f02baac96225e924a531683ee6ecc1/plugin/js/parsers/Template.js#L111-L114

Also, you should let me know about it, so I can fix it for the next release.

**Comment by budikesuma** [comment]
Ok, thanks dev.
