### ISSUE TITLE
royalroad changed thumbnail class

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#682]
**Describe the bug**
royalroad changed thumbnail class so the parser isn't able to find the image.
**To Reproduce**
1. Go to https://www.royalroad.com/fiction/44229/my-best-friend-is-an-eldritch-horror
2. Click on WebToEpub
3. No Cover Image URL

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 96.0.3

**Additional context**
Change the RoyalRoadParser.js line 115 from
        let img = dom.querySelector("img.img-offset");
to
        let img = dom.querySelector("img.thumbnail");

**Comment by dteviot** [comment]
@gamebeaker 
Already done.
https://github.com/dteviot/WebToEpub/commit/2c370fdee94ad369aa936dad25d28af787e0ea9b

**Comment by dteviot** [comment]
@gamebeaker 
Updated version (0.0.0.146) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
