### ISSUE TITLE
Gibberish issue with this site too [https://secondlifetranslations.com/]

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#683]
Hello! I was trying to create an EPUB with this site, but saw that this website also has the **same gibberish issue as Chrysanthemum Garden**. I thought to use the Epubeditor just to see if the "Clean ChrysanthememGarden" option would be applicable, but it seems like it didn't work... Is there perhaps another way to unscramble the words? Thank you very much!!!!

![image](https://user-images.githubusercontent.com/55352222/151692055-23cddba8-df25-48a2-9aca-9d299cc1b4fb.png)

**Comment by dteviot** [comment]
@vanessabluellie 
> The following parts of the text will be scrambled to prevent theft from aggregators and unauthorized epub making

My first suggestion would be ask them "How to get the authorized epubs?"

If that doesn't work, you could try the following.
1. Browse to EpubEditor.  https://dteviot.github.io/EpubEditor
2. Replace the text in the box on the RIGHT with the following
```javascript
let decryptTable = new Map();
let crypt = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
let clear = "rhbndjzvqkiexcwsfpogytumalVUQXWSAZKBJNTLEDGIRHCPFOMY";
for(let i = 0; i < crypt.length; ++i) {
    decryptTable.set(crypt[i], clear[i]);
}
let decryptChar = c => decryptTable.get(c) ?? c;
let decryptString = cypherText => cypherText.split("").map(c => decryptChar(c)).join("");
for(let e of dom.querySelectorAll(".jmbl-disclaimer")) {
    e.remove();
}
for(let e of dom.querySelectorAll("span.jmbl")) {
    e.innerHTML = decryptString(e.textContent);
}

return true;
```
3. Drop epub with scrambled text into box on LEFT.
4. Click option "Run script above to modify Epub"
5. Save result, when it finishes.

Seemed to work for https://secondlifetranslations.com/ykeml/ykeml-chapter-1/
For my notes: 47 minutes work

Edit: 2023-12-01  revised script to remove warning message and &amp;nbsp; at end of paragraphs.  See: https://github.com/dteviot/WebToEpub/issues/1126

**Comment by vanessabluellie** [comment]
THANK YOU VERY MUCH!!! It works perfectly!! :D
