### ISSUE TITLE
Please add site [https://www.chickengege.org/]

### ISSUE THREAD

**Issue by NessieBon** [dteviot/WebToEpub#688]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.chickengege.org/novels/tianbao/

The chapters are password locked and that part doesn't need to be bypassed, but even with the password and the chapters loaded, when I used WebtoEPUB, I can't scrap the chapters from the table of contents into an EPUB at all, but it seems they worked and appeared one by one...

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Yes... No chapters appeared at all. Even when I tried with Novel-grabber, chapter links DID appear, but when the EPUB was created, everything (like the translators/editors names) was there, except the chapter itself. 

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

https://www.chickengege.org/translations/tianbao/tianbao-1/

Thank you very much!

**Comment by dteviot** [comment]
@NessieBon 
Do you have URL for chapters that do not require passwords?
I need access to chapters to do much.

**Comment by NessieBon** [comment]
> @NessieBon Do you have URL for chapters that do not require passwords? I need access to chapters to do much.

I did a check and every single link needs a password, except this one, hopefully that will be enough since this one has only a few chapters. https://www.chickengege.org/novels/crossover/

Thank you!!!

**Comment by KaterinaSawyer** [comment]
I've also been looking for a solution for this site. Is it possible to grab chapters where it needs passwords? I have access to them and can provide it for you.

**Comment by dteviot** [comment]
@KatSaw  @NessieBon 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested against https://www.chickengege.org/novels/crossover/

For my records: 17 minutes work.

**Comment by dteviot** [comment]
@KatSaw @NessieBon
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

I am assuming it works.
