### ISSUE TITLE
need help with site https://inoveltranslation.com/

### ISSUE THREAD

**Issue by jono000** [dteviot/WebToEpub#690]
because manual parser didnot work.

div.chakra-skeleton__group.css-itvw0n
or
div.chakra-skeleton.css-cdkrf0

it give no result,

but when i try div.chakra-container.css-nm5t63
it will get the title, some rectangle and comment text.

**Comment by dteviot** [comment]
@jono000 
The default parser isn't going to work.  Text for chapters is from REST calls.
For my notes:
Looks like URL for a chapter is GET https://api.inoveltranslation.com/chapters/1063
Response JSON, relevant fields are "chapter", has number of chapter, "title", which has the title, and "content" which is string with the content text.

However, it's not obvious how to obtain the URL for each chapter.

**Comment by kammerjaeger** [comment]
Here is the chapter api: https://api.inoveltranslation.com/novels/15/feed?limit=100000
The id field is the chapter id

**Comment by dteviot** [comment]
@kammerjaeger 
Thanks.
So.  For Story
> https://inoveltranslation.com/novels/34

URL to get Table of Contents is 
> https://api.inoveltranslation.com/novels/34/feed?limit=100000

**Comment by kammerjaeger** [comment]
Yep that looks right, do you have an existing plugin that uses rest api? Then I can throw something together that does the same with these endpoint. I just currently don't have the time to look through your code and understand it.
Anyways great project, I love reading stuff on my kindle instead of the pc.

**Comment by dteviot** [comment]
@kammerjaeger @jono000 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with 
* https://inoveltranslation.com/novels/34
* https://inoveltranslation.com/novels/32  (first 3 chapters)

For my notes: 96 minutes work

**Comment by kammerjaeger** [comment]
Thanks, it works.
Could you sort it by chapter?
https://api.inoveltranslation.com/novels/15/feed?limit=100000 is not sorted correctly for some reason and the result is wrong then.
Thanks

**Comment by kammerjaeger** [comment]
Thanks, should have checked the other stories :-)

**Comment by dteviot** [comment]
@jono000 @kammerjaeger 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
