### ISSUE TITLE
Please add site https://nyantl.wordpress.com

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#691]
Table of Content:
https://nyantl.wordpress.com/thereafter-of-an-exiled-magician-since-my-engagement-was-cancelled-and-i-was-driven-out-i-will-stop-living-the-tough-aristocrat-life-and-live-leisurely-in-a-distant-foreign-developing-village/

I used "Manually Select Parser" -> Wordpress
it worked nicely, but the chapter title doesn't show in the chapter itself. so I might as well show default parser for the title:

* URL of first chapter: https://nyantl.wordpress.com/2022/01/15/the-wedding-cancellation-which-starts-from-wait-a-minute%e2%91%a0/
* CSS selector for element holding content to put into EPUB: **div.entry-content**
* CSS selector for element holding Title of Chapter: **h1.wp-block-post-title**

**Comment by dteviot** [comment]
@SpiralBaka 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, the prolog for kukuku might not work, (seems to go to permission requesting page, not chapter, so no content.)

Time taken: 19 minutes.

**Comment by dteviot** [comment]
@SpiralBaka 
Updated version (0.0.0.147) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
