### ISSUE TITLE
An attempt to use the addon leads to the immediate closure of the latest version of the Vivaldi browser (5.1.2567.39 Stable x32)

### ISSUE THREAD

**Issue by AndyEr2** [dteviot/WebToEpub#692]
Today I updated the browser and tried to download the book https://www.uukanshu.com/b/126202/, as it happened. Failure occurs when clicking on the add-on icon. I also tried to click on the icons of other installed addons and everything was fine.

Probably, this is a browser bug and will soon be fixed, I just decided to inform you for the sake of statistics. In case, the other addon users will again mention this problem with their browser.

**Comment by dteviot** [comment]
@AndyEr2 
Can you please go to https://vivaldi.com/bugreport/ and report the problem?
Then you can be sure they know about it, and will hopefully fix it.

That said, might https://forum.vivaldi.net/topic/70943/bug-when-the-vivaldi-new-tab-page-is-set-to-be-controlled-by-extension be the problem.

Note, you didn't describe the issue beyond saying "failure", so I can't help you further.
