### ISSUE TITLE
Please add site https://readnovelfull.org/

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#693]
Hello,

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site 
https://readnovelfull.org/bodyguard-of-the-goddess

### What settings did you use?  What didn't work?
* URL of first chapter : https://readnovelfull.org/bodyguard-of-the-goddess/chapter-1-i-married-a-cheap-wife
* CSS selector for element holding content to put into EPUB :   **.content-inner**
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove 

The CSS Selector for the content is right i think, but i don't know how to select all the link of the chapters and select the title ?

Thank you very much !

**Comment by dteviot** [comment]
@Flwk

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested against https://readnovelfull.org/top-level-air-luck-quietly-practiced-for-thousands-of-years-top-tier-providence-secretly-cultivate-for-a-thousand-years

For my records: 57 minutes work

**Comment by Flwk** [comment]
@dteviot Thank you so much !

**Comment by dteviot** [comment]
@Flwk
Reopen, so I know to tell you when version in store has been updated.

**Comment by dteviot** [comment]
@Flwk 
Updated version (0.0.0.147) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
