### ISSUE TITLE
Please add site [https://untamedalley.com/]

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#695]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://untamedalley.com/category/bl/ahwtkah/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Yes... But no chapters could be registered by the extension.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove
https://untamedalley.com/bl/ahwtkah/c1-kill-the-emperor-1/

It seems like this site doesn't have any Table of Contents, but you can select a category (which is the novel) from the drop-down list on the left and continuously click on "OLDER ENTRIES" to find a specific chapter. The format seems similar to [https://cangji.net/category/yaohu/]! Thank you very much!!!!

![image](https://user-images.githubusercontent.com/55352222/154022321-32970365-ee38-47c1-9324-7a5140797c8c.png)

**Comment by dteviot** [comment]
@vanessabluellie 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with: https://untamedalley.com/category/bl/ahwtkah/
Note, some stories don't seem to have a list of chapters.  e.g. https://untamedalley.com/back-to-my-husbands-youth/

For my notes: 43 minutes work.

**Comment by vanessabluellie** [comment]
THANK YOU! It works!!

**Comment by dteviot** [comment]
@vanessabluellie 
Updated version (0.0.0.147) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
