### ISSUE TITLE
inf Searching for URLs. Please wait. - https://www.mtlnovel.com/permanent-martial-arts/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#696]
other novel work just fine on same site, only this novel have problem https://www.mtlnovel.com/permanent-martial-arts/

Searching for URLs. Please wait. ............

**Comment by dteviot** [comment]
@Finks82
The Table of Contents information for the book seems to be messed up.
If you click on the chapters tab it lists 3000 volumes.
If you then open the volumes, only the first one seems to have any chapters.

Note, if you wait long enough, WebToEpub should eventually fetch all the volumes.
If you open a Developer Tools window and go to the Network tab, you can see WebToEpub fetching each volume.

Although I'd suggest dropping a note to the site owners asking them to fix the Table of Contents.

**Comment by dteviot** [comment]
Nothing for me to do
