### ISSUE TITLE
Please add site https://allnovelfull.com

### ISSUE THREAD

**Issue by Shinhardt** [dteviot/WebToEpub#697]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site : 

https://allnovelfull.com/journey-to-become-a-true-god.html

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html :

Yes but not all chapter can registered.

### What settings did you use?  What didn't work?
* URL of first chapter : https://allnovelfull.com/journey-to-become-a-true-god/chapter-1-break-up-with-girlfriends.html
* CSS selector for element holding content to put into EPUB : div.col-xs-12
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove 

Tried default parser but only first 50 chapter on page 1 can registered, I don't know how to register all other chapter. Can you help please? Thanks.

**Comment by dteviot** [comment]
@Shinhardt 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://allnovelfull.com/journey-to-become-a-true-god.html

For my notes: time taken 12 minutes

**Comment by Shinhardt** [comment]
Not work for me, Is the link correct? Download Chrome version from that
link but it was same as the last version. I've check js folder there's no
Allnovelfull parser js in there, maybe that's why it wasn't work. Can you
reupload? Sorry for the trouble...

**Comment by dteviot** [comment]
@Shinhardt 
>Not work for me, Is the link correct? Download Chrome version from that link but it was same as the last version. 

D'oh! I forgot to upload the updated files. This is what happens when I try to do to many things at once.

> I've check js folder there's no Allnovelfull parser js in there,

There isn't.  allnovelfull.com is the same layout as novelfull.com.  So it was just a matter of updating the novelfull parser to recognize allnovelfull.com.

> Can you reupload?

Done.

>Sorry for the trouble

No trouble at all.  I'm the one who needs to apologize.  So, sorry for the screw up.

**Comment by Shinhardt** [comment]
Tried and it work, Thanks...

**Comment by SirGryphin** [comment]
Thank you for this, just about to request it myself

**Comment by dteviot** [comment]
@Shinhardt @SirGryphin 
Updated version (0.0.0.147) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
