### ISSUE TITLE
https://www.wuxiaworld.com is broken 

### ISSUE THREAD

**Issue by Maradar** [dteviot/WebToEpub#698]
**Describe the bug**
https://www.wuxiaworld.com parser is broken becuase page design was changed, chapters are loading/extension does not see them.

**To Reproduce**
1. Go to https://www.wuxiaworld.com/novel/martial-god-asura
2. Click on chapters and extension button in browser
3. Scroll down to chapter list in extension.
4. You will see that it does not load chapters at all.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 (21H2)
 - Browser Vivaldi and Mozilla Firefox Dev Edition
 - Version 5.2.2581.4 (Official Build) (64-bit) and 98.0b9 (64-bit)

**Comment by dteviot** [comment]
@Maradar 
Known issue. See: https://github.com/dteviot/WebToEpub/issues/676
