### ISSUE TITLE
https://www.onlymtl.com/

### ISSUE THREAD

**Issue by Kucingmeong2** [dteviot/WebToEpub#699]
Please add this web 🙏🙏🙏🙏
I cant save story or novel from this web to epub, please help me 😭😭😭😭

**Comment by dteviot** [comment]
Not easy.

Some notes:
Given a ToC page, need to find script element like
```javascript
        var manga = { "ajax_url": "https:\/\/www.onlymtl.com\/wp-admin\/admin-ajax.php", "home_url": "https:\/\/www.onlymtl.com", "manga_paged_var": "manga-paged", "enable_manga_view": "1", "manga_id": "15189" };
```

This provides the manga_id element, which can be used to fetch Chapter URLs
Which requires a HTML POST to https://www.onlymtl.com/wp-admin/admin-ajax.php
With a content-type: application/x-www-form-urlencoded; charset=UTF-8
And payload like:
action: manga_get_chapters
manga: 15189

**Comment by Kucingmeong2** [comment]
Why so hard for save from this web 🥲🥲🥲🥲

**Comment by Kucingmeong2** [comment]
🙏🙏🙏🙏
