### ISSUE TITLE
Please add site https://dreame.com

### ISSUE THREAD

**Issue by asawakoyriego** [dteviot/WebToEpub#700]
Hi! I highly appreciate your work. Free epub convert of  wattpad stories is so heavenly good. But can you add this site. I've been dying to read the books in epub format. Hoping you will read this. Thank you!

Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.dreame.com/novel/h3GrYnIWFXSF7doBJ%2BY9QQ%3D%3D-The-Beast's-Bride.html

**Comment by dteviot** [comment]
@asawakoyriego 
Unfortunately, site seems to be encrypting the content for chapters.  So, sorry, I can't help you.
