### ISSUE TITLE
Open tab as child of current one

### ISSUE THREAD

**Issue by alethiophile** [dteviot/WebToEpub#702]
**Is your feature request related to a problem? Please describe.**
I habitually have dozens or hundreds of tabs open (using Tree-Style Tab). When I open WebToEpub on a given site, it's opened at the end of the tab list, making it annoying to switch back and forth between the WebToEpub tab and the original.

**Describe the solution you'd like**
It would be good to open the WebToEpub tab as a child of the current tab (i.e. the same way it behaves when you open a link in a new tab). In Tree-Style Tab, this makes the new tab a literal child of the current one; in the default tab interface, it just opens the tab directly adjacent to the current one rather than at the end of the tab list. Either way makes it much easier to handle WebToEpub.

**Comment by dteviot** [comment]
@alethiophile 
I assume you're using one of the Tree-Style Tab extensions.
I think you need to contact the maker of the extension, and tell them the problem.
