### ISSUE TITLE
https://wuxiapub.com

### ISSUE THREAD

**Issue by SirGryphin** [dteviot/WebToEpub#703]
I've added this one myself by just editing ReadwnParser.js as it the same site I only needed to add url. Just thought I would post here and ask for it in official release. I would post a pull request but my not very good at using github.

https://www.readwn.com/novel/the-legend-of-randidly-ghosthound.html

**Comment by dteviot** [comment]
@SirGryphin 
Thanks.  Done.
Updated version (0.0.0.147) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
