### ISSUE TITLE
Please add site https://madnovel.com/

### ISSUE THREAD

**Issue by nandakishore2009** [dteviot/WebToEpub#704]
### What settings did you use?  What didn't work?
* URL of first chapter: **https://madnovel.com/cultivation-online/chapter-638-visiting-the-flying-sword-sect**
* CSS selector for element holding content to put into EPUB: **.content-inner**
* CSS selector for element holding Title of Chapter: **h1**
* CSS selector for element(s) to remove: **.ads-banner, .content-inner > br**

### If you tried writing a parser, and it doesn't work.  Attach the parser here.
[MadnovelParser.zip](https://github.com/dteviot/WebToEpub/files/8237427/MadnovelParser.zip)

**PS: I have attached the tested MadnovelParser.js**

**Comment by dteviot** [comment]
@nandakishore2009 
Thank you very much.  Parser added.  Although you should really do it as a pull request, so GitHub tracks your contribution

Updated version (0.0.0.147) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
