### ISSUE TITLE
Not working for theirontreeblooms

### ISSUE THREAD

**Issue by dmbada** [dteviot/WebToEpub#705]
tried to use on https://theirontreeblooms.com/ but the parser created for it doesnt work anymore so i used the default parser and it works for the test but when i tried to pack the epub it shows this error

TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at Object.decodeCloudflareProtectedEmails (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Util.js:138:37)
    at TheirontreebloomsParser.convertRawDomToContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:88:14)
    at TheirontreebloomsParser.webPageToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:178:28)
    at DefaultParser.webPagesToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:312:34)
    at DefaultParser.epubItemSupplier (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:294:30)
    at packEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:172:37)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:144:20

**Comment by dteviot** [comment]
@dmbada 
Please provide URL of story you're having a problem with.  
I don't have time to test all stories on the site until I find the issue.

**Comment by dmbada** [comment]
this one

https://theirontreeblooms.com/2021/01/18/back-to-the-beginning-of-ming-to-do-charity-%E5%9B%9E%E5%88%B0%E6%98%8E%E5%88%9D%E6%90%9E%E6%85%88%E5%96%84/

**Comment by dmbada** [comment]
this one

https://theirontreeblooms.com/2021/01/18/back-to-the-beginning-of-ming-to-do-charity-%E5%9B%9E%E5%88%B0%E6%98%8E%E5%88%9D%E6%90%9E%E6%85%88%E5%96%84/

**Comment by dteviot** [comment]
@dmbada 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://theirontreeblooms.com/2021/01/18/back-to-the-beginning-of-ming-to-do-charity-%E5%9B%9E%E5%88%B0%E6%98%8E%E5%88%9D%E6%90%9E%E6%85%88%E5%96%84/

Notes:
10 minutes work.  Seems that site has gone to a standard WordPress layout, so just remove the custom parser for the site.

**Comment by dmbada** [comment]
it works! thanks

**Comment by dteviot** [comment]
@dmbada 
Reopening, so I know to inform you when new version posted to Chrome and Firefox stores.

**Comment by dteviot** [comment]
@dmbada 
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
