### ISSUE TITLE
AsianHobbyist needs another format added?

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#706]
**Describe the bug**
Doesn't work as intended. I tried manually adding the following to the URLs
`<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-35-part-1/"> part 1</a>`
which results in:

```
Error: Could not find content element for web page 'http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-35-part-1/'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:492:23
    at async Promise.all (index 0)
    at async AsianHobbyistParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)
```

**To Reproduce**
https://www.asianhobbyist.com/series/the-girl-who-ate-a-death-god/
WtE will trigger on this page, but the epub it generates it useless since it doesn't follow the links inside to pull the chapters.

https://www.asianhobbyist.com/the-girl-who-ate-a-death-god/the-girl-ate-death-god-chapter-35/
"Part 1", etc. WtE won't trigger on these sub-pages. This site's a mess, I'm only here to grab some chapters that are hard to find with their original formatting.

**Expected behavior**
The usual.

**Desktop (please complete the following information):**
Chrome, Windows 7.

**Comment by dteviot** [comment]
@Tenome 
> This site's a mess,

Agreed.

Have patched for the-girl-who-ate-a-death-god
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, you will still need to manually add the URLs
```html
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-35-part-1/">Ch. 1.1 - part 1</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-35-part-2/">Ch. 1.1 - part 2</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-35-part-3/">Ch. 1.1 - part 3</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-36-part-1/">Ch. 1.1 - part 1</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-36-part-2/">Ch. 1.1 - part 2</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-36-part-3/">Ch. 1.1 - part 3</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-36-part-4/">Ch. 1.1 - part 4</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-36-part-5/">Ch. 1.1 - part 5</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-37-part-1/">Ch. 1.2 - part 1</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-37-part-2/">Ch. 1.2 - part 2</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-37-part-3/">Ch. 1.2 - part 3</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-37-part-4/">Ch. 1.2 - part 4</a>
<a href="http://asianhobbyist.com/the-girl-who-ate-a-death-god-chapter-37-part-5/">Ch. 1.2 - part 5</a>
```
Because it's too much work to try and get WebToEpub to do this for the above 13 chapters.

For my notes: 35 minutes work

**Comment by Tenome** [comment]
Seems to work as intended. Thanks.

**Comment by dteviot** [comment]
@Tenome 
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
