### ISSUE TITLE
Fix lightnovelreader.org

### ISSUE THREAD

**Issue by nandakishore2009** [dteviot/WebToEpub#707]
Parser for lightnovelreader.org is broken. 

Trying to parse https://lightnovelreader.org/the-beginning-after-the-end-813565 result in not showing any chapters.

PS: Attaching the fix

[LightnovelreaderParser.zip](https://github.com/dteviot/WebToEpub/files/8288514/LightnovelreaderParser.zip)

**Comment by dteviot** [comment]
@nandakishore2009 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Wish I'd noticed the zip you added.

Tested with https://lightnovelreader.org/the-beginning-after-the-end-813565 

For my notes: Time taken 67 minutes.  (Mostly trying to get rid of the "Sponsored Content" lines.)

**Comment by nandakishore2009** [comment]
The fixed implementation for **getChapterUrls** is not working properly.

I have tested the new function with the link https://lightnovelreader.org/once-human-now-a-parasite. Here, only partial chapter are being selected. 

The getChapterUrls function in attached zip is working properly. 
 
```js
async getChapterUrls(dom) {
	let chapterList = [...dom.querySelectorAll(".novels-detail-chapters")]
		.map(x => util.hyperlinksToChapterList(x))
	return chapterList.flat().reverse();
}
```

**Comment by dteviot** [comment]
@nandakishore2009 
D'oh!
Fixed.  
Updated versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. 

For my notes: 11 minutes.
