### ISSUE TITLE
file name problems when downloading from wattpad ver. 0.147

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#710]
with version 0.147 the files are downloaded without a title name I put a screenshot of how the file is saved in Edge and in Chrome, in firefox it works fine. so since I use Edge I had to go back to a previous version that I had manually saved 0.144 that does not give me this error. The download is successful and the book looks fine, but the title of the file is just numbers and letters. I show you the configuration that I have, which is the same as with the previous versions and with the one I use that does not give an error, which is 0.144. He reiterated that it only happens in Egde-Chrome in firefox it goes without problems

https://www.wattpad.com/story/21108194-%C2%A1vendida-3-%C2%BFregresar%C3%A1-james-maslow-____

![Picture0001](https://user-images.githubusercontent.com/29169926/159586482-9d37fbc6-3267-41e9-8841-9096a1de75cc.jpg)
![Screenshot](https://user-images.githubusercontent.com/29169926/159586801-a69bd437-ef2b-41be-8565-8c46cd3da8d6.png)
![Screenshot (1)](https://user-images.githubusercontent.com/29169926/159586816-44e84e5e-57e0-4a00-9838-e66a6b5d2f3c.png)
.

**Comment by dteviot** [comment]
@bichitoxxx 
Most likely you're using another extension that's conflicting with WebToEpub.
See: https://github.com/dteviot/WebToEpub/issues/191

**Comment by bichitoxxx** [comment]
I don't know what it could be, I haven't installed anything new. and the previous version still works fine, that version only gives me problems in browsers based on chrome. I will try to see if deactivating things works, to find the problem

**Comment by dteviot** [comment]
@bichitoxxx 
I tried latest build WebToEpub build with Chrome (99.0.4844.82), and the above story, and it saved with correct name.
I also checked the code history, the code for saving epub file hasn't changed since version 0.0.0.142.

It's very strange.
And if it's not a conflict with extensions, I don't know what's causing the problem.

**Comment by bichitoxxx** [comment]
I keep checking to see if it is the cause of any extension, install a new browser, based on Chrome to see if it causes the problem, that browser is free of everything, I will inform you if I find the conflict problem, thanks
