### ISSUE TITLE
https://soverse.com/

### ISSUE THREAD

**Issue by Okikaemmanuel1** [dteviot/WebToEpub#711]
Please add this site

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

**Comment by dteviot** [comment]
@Okikaemmanuel1 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, you'll need to manually expand the table of contents to show all chapters.
Also, be careful, they don't seem to be all in order.  The first few chapters are at the end, so you'll need to click the the "Edit Chapters URLs" button and move them.

Tested with https://soverse.com/immemorial-dragon-elephant-art/ and a few chapters.

For my notes: 45 minutes work.

**Comment by dteviot** [comment]
@Okikaemmanuel1 
> Also, be careful, they don't seem to be all in order. The first few chapters are at the end, so you'll need to click the the "Edit Chapters URLs" button and move them.

I may have been mistaken. Looking at the chapter timestamps, they seem to be in order.  The chapter numbering however, not so much.

**Comment by Okikaemmanuel1** [comment]
Thanks how do I manually expand table of content

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by Okikaemmanuel1** [comment]
Seen sorry misunderstood the instruction

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by Okikaemmanuel1** [comment]
Thanks working

**Comment by dteviot** [comment]
@Okikaemmanuel1 
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
