### ISSUE TITLE
Please add site secondlifetranslations

### ISSUE THREAD

**Issue by friedchickengege** [dteviot/WebToEpub#712]
Can you please add [this](https://secondlifetranslations.com/novel/after-being-turned-into-a-dog-i-conned-my-way-into-freeloading-at-my-rivals-place/) site?

All downloaded chapters have jumbled words. Thank you so much in advance!

![image](https://user-images.githubusercontent.com/101273696/160340511-a95ca8ae-42bf-411c-a8f6-d4458735fbd3.png)

**Comment by dteviot** [comment]
@friedchickengege 
And to anticipate your next question, here's how to get EpubEditor and start it.
1. Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8 and download EpubEditor.
2. Unzip the file and open main.html in Chrome or Firefox.

**Comment by friedchickengege** [comment]
It worked! Thank you so much ! ! !

**Comment by dteviot** [comment]
@friedchickengege 

Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.
