### ISSUE TITLE
Please add site https://exiledrebelsscanlations.com/

### ISSUE THREAD

**Issue by KatSaw** [dteviot/WebToEpub#715]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://exiledrebelsscanlations.com/novels/spirit-hotel/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
It works but chapter 19 onwards actually have a defence mechanism where the real chapter is in an image while the texts are gibberish. Is there any solution to this?

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@KatSaw 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested against https://exiledrebelsscanlations.com/novels/spirit-hotel/

For my records: 30 minutes work.

**Comment by KatSaw** [comment]
It seems that it doesn't work.

![D8FC3781-82F5-45CB-9A74-344246220174](https://user-images.githubusercontent.com/90402642/161418582-a8cf3ad8-c748-464c-b51e-4a25b43abfa3.jpeg)
This is an extract that's supposed to be the real texts for the chapter.

But it came out like this:
![148F1774-2D64-4197-A8E2-C89208493892_4_5005_c](https://user-images.githubusercontent.com/90402642/161418610-f32094a4-b358-458f-86c8-b3e7276b2ab4.jpeg)
which is pretty much unreadable

It also copies the fake text which is this:
![D4DB1469-3ECE-4631-ACCF-E9C70998EC57_4_5005_c](https://user-images.githubusercontent.com/90402642/161418637-3aec3e67-568c-4193-8a7f-863712de7c22.jpeg)

Is there any possible way to just copy the images of the real text for chapter 19 and onwards? This is one of the few novels in the website that actually have a defence mechanism.

**Comment by dteviot** [comment]
@KatSaw 
Chapter 19 seems to be an issue with your epub reader.
The chapter is returned as a single jpeg image.  
Resulting in a long, narrow image. So, if the viewer tries to show the whole image on screen, it's unreadable. 
If you expand the image to fill the screen width, it's perfectly readable.
My reader (The Firefox EPUBReader extension) did that automatically.)

As regards the other issue you raise, please give me the URL of one of those chapters.

**Comment by KatSaw** [comment]
Oh, I've tried and it's really as you've told, expanding the image works perfectly, thanks a lot for thattt.

As for the second issue where Webtoepub also copies the fake text. It happens on chapter 19 and onwards. It's a way to deviate attention by including both the fake text and real text into one chapter I guess. Here's an example link:
https://exiledrebelsscanlations.com/sh-chapter-19/

**Comment by dteviot** [comment]
@KatSaw
If it's intermittently generating a page with wrong text (i.e. Sometimes does, sometimes doesn't) then it may be deciding you're copying too much at once.  I'd suggest, try again a different day, 
1. Use the advanced options to reduce the collection rate, and
2. Only ask for the chapters that failed previously.

Note, you can use a tool like MergeWebToEpub. (found here: https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8, needs Windows) to merge epubs and replace the bad chapters. 
Or you could use Calibre

**Comment by KatSaw** [comment]
Thanks a lot for the various advice, I decided to use Calibre and managed to delete all the fake texts. Works perfectly. Again, really appreciate all your help, thanksss.

**Comment by dteviot** [comment]
@KatSaw 
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
