### ISSUE TITLE
Please add site https://www.teanovel.com/

### ISSUE THREAD

**Issue by KatSaw** [dteviot/WebToEpub#716]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.teanovel.com/novel/guide-to-raising-the-sick-villain/chapter-list

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes, it doesn't work.

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
I don't have developer skills

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I don't have a friend with developer skills

### If you tried writing a parser, and it doesn't work.  Attach the parser here.

Thank you a lot for your help.

**Comment by dteviot** [comment]
@KatSaw 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://www.teanovel.com/novel/fantasy-farm

Note, don't open WebToEpub on a Table of Contents page (e.g. https://www.teanovel.com/novel/fantasy-farm/chapter-list), open on a novel page, (e.g. https://www.teanovel.com/novel/fantasy-farm),

For my notes: 82 minutes

**Comment by KatSaw** [comment]
It works perfectly, thanks a lottt.

**Comment by dteviot** [comment]
@KatSaw 
Reopen so I know to inform you when Chrome and Firefox stores updated.

**Comment by KatSaw** [comment]
So I've tried making an epub out of this site again but it seems their layout changed.

Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site:

**Comment by dteviot** [comment]
@KatSaw 
Looks like they've renamed the site from  https://www.teanovel.com to https://www.teanovel.net
Easy fix.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by KatSaw** [comment]
Tried it and it works perfectly, thank youuuu

**Comment by dteviot** [comment]
@KatSaw 
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
