### ISSUE TITLE
Please add site https://chrysanthemumgarden.com/. EpubEditor doesn't seem to work anymore.

### ISSUE THREAD

**Issue by laziestperson** [dteviot/WebToEpub#718]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://chrysanthemumgarden.com/novel-tl/acy/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Yes, it works but the texts come out as jumbled. I have tried using Clean Chrysanthemum Garden in EpubEditor but it no longer works. 

I'd also like to ask another thing, is it possible to grab chapters that has password-lock on it? 

Example of chapter:
https://chrysanthemumgarden.com/novel-tl/2013/2013-7/

Table of Contents for the said chapter:
https://chrysanthemumgarden.com/novel-tl/2013/

**Comment by dteviot** [comment]
@laziestperson 
> Yes, it works but the texts come out as jumbled. I have tried using Clean Chrysanthemum Garden in EpubEditor but it no longer works.

I just tried it. It worked for chapters 1, 4, and 40 of https://chrysanthemumgarden.com/novel-tl/acy/
Please give URL of chapter with issue.

> is it possible to grab chapters that has password-lock on it?

As this is supposed to be a temporary situation, not without more effort than I'm willing to put in.

**Comment by laziestperson** [comment]
So I've tried it with this chapter:
https://chrysanthemumgarden.com/novel-tl/pot/pot-1/

And still doesn't work. I've put it through EpubEditor for almost 10 times but still the same result.

And as for my second question, yes, completely understands, thank you for all your help.

**Comment by dteviot** [comment]
@laziestperson 
OK, I just tried https://chrysanthemumgarden.com/novel-tl/pot/pot-1/ and as far as I can tell it worked.
Are the following the steps you did to use EpubEditor?
1. Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing and download EpubEditor.zip
2. Unpack the zip file.
3. In file explorer, open the unpacked zip, right click on the file main.html, and select "Open With" then "Google Chrome".
3. Drag and drop Chrysanthemum Garden epub onto the drop zone.
4. A set of buttons will appear, click the second from bottom labelled "Clean ChrysanthemumGarden"
5. Wait a little bit.  You should get a file dialog asking you for name to save the fixed epub.

Other questions/thoughts:
1. Has EpubEditor ever worked for you?
2. Do you get the "File Save" dialog?
3. Do you want to email me the epub you created (from website, before you tried using EpubEditor) and I'll see if I can fix it and send it back to you?  My email is dteviot@gmail.com

**Comment by laziestperson** [comment]
Yes, I did the following steps.

Other questions:
1. Yes, it's worked before
2. Yes
3. This site has a lot of my favourite novels so honestly, I wanted to save a lot of them as epubs. I can't bother you with every single one.

On another note, I tried switching my laptop (from a Macbook to an MSI) and honestly feels optimistic about it. I have really one small question and definitely won't bother you again;

https://user-images.githubusercontent.com/103273562/162792226-6e039ae2-008e-41d7-90c9-e591f1fde582.mp4

It seems that the file that I dragged and drop doesn't properly go into the box and just created another tab altogether. I did uninstall my ePubReader extension but it still doesn't drop properly. It's small problems like these that shortened my life span slowly.

**Comment by dteviot** [comment]
@laziestperson 
I think one of two things has happened.
1. MacOS knows the file is an epub.  And it knows to open the epub with the epub reader.  So, when you drop the file into Chrome, it's trying to use the epub reader.
Solution: Try to rename the file from .epub to .zip, and then drop it into Chrome.  (Note, I'm not familiar with MacOS, but I believe files have a resource fork that holds metadata about the file, so you may need to change that as well.)
2. Some other extension in Chrome is messing things up.
Solution: use a different browser with no extensions loaded.  I suggest Firefox Developer Edition.  https://www.mozilla.org/en-US/firefox/developer/

**Comment by laziestperson** [comment]
I've tried both options for almost 10 times but it really doesn't work. 

I'd like to ask is it possible for you to add a feature like this?
![WhatsApp Image 2022-04-13 at 9 38 34 PM](https://user-images.githubusercontent.com/103273562/163193221-f3feaf1e-1274-447e-9870-889a1a517af0.jpeg)

It's an example from a PDF to Word Converter online and I find that I could load the file with that.

**Comment by dteviot** [comment]
@laziestperson 
Are you able to run MergeWebToEpub from  https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing (it needs Windows.)?
If you can, I should be able to update it to fix Chrysanthemum Garden

**Comment by laziestperson** [comment]
Yes, I can run it.

**Comment by dteviot** [comment]
@laziestperson 
I've updated the copy of MergeWebToEpub at https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8 to handle chrysanthemumgarden.com

Steps.
1. Download MergeWebToEpub, open the zip and start MergeWebToEpub.exe
2. On "File" menu, select "Open"
3. Select the epub to update
4. On "Edit" Menu, select "Run Cleaners"
5. After a little bit, a dialog saying "Save Changes" should appear.
6. on "File" menu, select "Save".  And pick a name for the new epub.

Tested with chapters 1 and 2 of https://chrysanthemumgarden.com/novel-tl/pot/

For my notes: 30 minutes work

**Comment by dteviot** [comment]
@laziestperson 
I suspect it means you did not unpack the zip file before trying to run MergeWebToEpub.exe.

To explain.  The zip file contains five files, 
* MergeWebToEpub.exe (the executable)
* and four DLL files (e.g. DotNetZip.dll, HtmlAgilityPack.exe, libwebp_x64.dll, libwebp_x86.dll) which the executable needs.

When the .exe starts it looks for the DLL files which should be in the same folder as the MergeWebToEpub.exe.
The error message is saying it can't find DotNetZip.dll.
If you ran MergeWebToEpub.exe directly from the zip file (i.e. without unpacking the zip) then the .exe won't find the .dll files, because they're still in the zip.

So, unpack the zip file (I suggest using 7zip) making sure all four .dll files are extracted into the folder with MergeWebToEpub.exe and then try to run MergeWebToEpub.exe.

**Comment by laziestperson** [comment]
It works perfectly. Thank you very much for the helppp.

**Comment by ANNE0511** [comment]
Hi developer. Can you update the app, it doesb't work anymore
