### ISSUE TITLE
[Enhancement] Remove text before first images

### ISSUE THREAD

**Issue by BaronKrause** [dteviot/WebToEpub#72]
In many projects, the initial set of pictures will have some text like "Novel Illustrations[edit]
These are the novel illustrations that were included in volume 1"

In this book for example https://www.baka-tsuki.org/project/index.php?title=Rakudai_Kishi_no_Eiyuutan:Volume1 after the cover it will generate a page with just the text "Illustrations" followed by another page with just the text "Novel Illustrations
These are the novel illustrations that were included in volume 1"

Then it will show the pictures. That text if at all possible probably shouldn't actually get generated in the epub as it is more just organizational titles for viewing on the web.

Many projects probably use different text so I'm not sure how feasible it would be, but it is the last thing I noticed about the plugin that made the output results distinguishable from a manually converted and edited epub.

**Comment by dteviot** [comment]
@BaronKrause
I've checked a fix into the Experimental Tab Mode branch. https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode

If you'd would install from Source (instructions are on the above link), try it out and let me know if there are problems, that would be appreciated.
I've tried it with:
- https://www.baka-tsuki.org/project/index.php?title=Leviathan:Volume_5  (has text before gallery)
- https://www.baka-tsuki.org/project/index.php?title=Rakudai_Kishi_no_Eiyuutan:Volume1 (has text before gallery)
- https://www.baka-tsuki.org/project/index.php?title=Utsuro_no_Hako:Volume_2 (has cover image before gallery)
- https://www.baka-tsuki.org/project/index.php?title=BlazBlue:Phase_0 (has table of images before gallery)
- https://www.baka-tsuki.org/project/index.php?title=High_School_DxD:Volume_20 (typical)  

And it appeared to work.
Note there may be some other unusual cases I haven't checked.

**Comment by dteviot** [comment]
No response from original requestor.  Assuming works.
