### ISSUE TITLE
Please add site https://www.panda-novel.com (parser attached)

### ISSUE THREAD

**Issue by nandakishore2009** [dteviot/WebToEpub#720]
* Sample TOC URL: https://www.panda-novel.com/details/epic-of-ice-dragon-reborn-as-an-ice-dragon-with-a-system(DN)-1130

> **Note**: Some time the  WebToEpub dynamic TOC loading will not work due to Cloudflare protection timout and in that case we have to refresh the main website page to get the latest Cloudflare cookies.

###  Attaching the tested parser as zip.

> Download Link: [PandaNovelParser.zip](https://github.com/dteviot/WebToEpub/files/8488798/PandaNovelParser.zip)

**Comment by dteviot** [comment]
@nandakishore2009
Firstly, thank you very much.  Appreciate the time this saved me.
 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Notes,

You're using InnerHtml. Which might be a problem getting past Mozilla's audit.
