### ISSUE TITLE
Removing Hostednovel.com's ''read it on hostednovel.com'' and etc other watermarks.

### ISSUE THREAD

**Issue by 159357XxCD** [dteviot/WebToEpub#721]
Hi,

Not a problem with the extension, but a problem of Hostednovel.com. The thing is, under normal circumstances almost all websites have some sort of watermark but you do not see them when reading their materials, Only when you try to copy them or use webtoepub kind of extensions those watermarks appear on the finished epub/product. But hostednovel.com has it another way, even when you read their novels on their own website you see watermarks/watermarkish remarks etc, which I suspect do not fall under the normal watermark category., anyway I digress.

Would it be possible to remove those watermark lines on hostednovel.com novels with webtoepub extension. I mean if possible what would be awesome, but if it is too much of a work do not bother with it, they do not have aggressive watermarks like other websites in the end.

Best Regards.

**Comment by dteviot** [comment]
@159357XxCD 
Tricky, assuming the watermarks are lines like 
>We are hosted novel, find us on google.

or
> This novel is _hosted_ by hosted novel.

Then the watermark are just ordinary paragraphs, there's nothing to distinguish them from the rest of the text.
Best I can offer is using EpubEditor to try to remove them.

1. Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8 and download EpubEditor.
2. Unpack the zip file.
3. In file explorer, open the unpacked zip, right click on the file main.html, and select "Open With" then "Google Chrome" or "Firefox".
3. Replace the text in the box on the RIGHT with the following
```javascript
            for(let p of [...dom.querySelectorAll("p")]) {
                let c = p.textContent;
                if (c.toLowerCase().includes("hosted novel")) {
                    console.log(c);
                    p.remove();
                }
            }
            return true;
```
5. Drag and drop Hostednovel epub onto the drop zone.
6. Click option "Run script above to modify Epub"
7. If using Chrome, Save result, when it finishes.  If running Firefox, I think it will save the result automatically.
