### ISSUE TITLE
Please add site https://www.nanomashin.online/

### ISSUE THREAD

**Issue by hesoyamma785** [dteviot/WebToEpub#722]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.nanomashin.online/reformation-of-the-deadbeat-noble/
### Did you try using the Default Parser for the site?  If not, why not?

Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter https://www.nanomashin.online/reformation-of-the-deadbeat-noble/prologue-the-diary-of-a-villager
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@hesoyamma785 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.


Tested with first couple of chapters from
* https://www.nanomashin.online/reformation-of-the-deadbeat-noble
* https://www.nanomashin.online/descent-of-the-demon-god

For my records: 50 minutes

**Comment by hesoyamma785** [comment]
@dteviot  it works 
thanks

**Comment by dteviot** [comment]
@hesoyamma785 
Reopen, so I know to notify you when version in Google and Mozilla stores updated.

**Comment by dteviot** [comment]
@hesoyamma785 
Updated version (0.0.0.149) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
