### ISSUE TITLE
Please add site https://noveltranslatedbyc.blogspot.com/2021/12/remarried-empress-second-marriage-novel.html

### ISSUE THREAD

**Issue by Kucingmeong2** [dteviot/WebToEpub#723]
Hello 👋👋👋👋
Can I ask againt for add this web or blog🙏🙏🙏🙏🙏🙏
https://noveltranslatedbyc.blogspot.com/2021/12/remarried-empress-second-marriage-novel.html

**Comment by dteviot** [comment]
@Kucingmeong2 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with chapters 1 & 2

For my notes: 35 minutes work

**Comment by Kucingmeong2** [comment]
Thank you 🙏🙏🙏🙏

**Comment by dteviot** [comment]
@Kucingmeong2 
Updated version (0.0.0.149) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
