### ISSUE TITLE
translator

### ISSUE THREAD

**Issue by Battlesp1ke** [dteviot/WebToEpub#724]
hi I have a suggestion

I don't know if this would work but maybe you could get the program to run the chapter through google translator as is got the chapter text? if it can work have it as a toggle option

**Comment by Flwk** [comment]
That's true, if it's possible, we could even rip a novel in chinese ! 

 I know that there is some project for using Google Translate API for free (like [here](https://github.com/vitalets/google-translate-api)), maybe that can help :)

In any case, thank you for all your work !

**Comment by dteviot** [comment]
@Battlesp1ke @Flwk 
The last time I looked into this, Google requires a paid license to do this.  https://translate.google.com/intl/en/about/forbusiness/
While the link you provide is using the free Google translate service, I think it's still a violation of the Terms of Use.
So, I'm not willing to do this.
