### ISSUE TITLE
novels from 1stkissnovel.love takes forever to "Pack Epub"

### ISSUE THREAD

**Issue by seizue** [dteviot/WebToEpub#726]
Hi. novels from 1stkissnovel.love takes forever to "Pack Epub".  500+ chapters take to 1 hour or more just to finish. 
I tried this one https://1stkissnovel.love/novel/my-female-ghost-is-super-fierce/

and it is super slow compare to the other site (e.g mtlnovel, redlightnovel etc). The extension in fact works it just taking it long. This only happen in 1stkissnovel.love

**Comment by dteviot** [comment]
@seizue 
The site rate limits.  Looks like it has a limit of about 10 pages/minute or so.
Nothing I can do about it.

**Comment by seizue** [comment]
> @seizue 
> The site rate limits.  Looks like it has a limit of about 10 pages/minute or so.
> Nothing I can do about it.

alright 😔 ty for trying ^^
