### ISSUE TITLE
Two Chapter Tittles showing up from freewebnovel

### ISSUE THREAD

**Issue by seizue** [dteviot/WebToEpub#728]
Hi. In https://freewebnovel.com/ 
Novels downloaded there have two titles. Can you remove the other one.  😅
I'm fine with either the upper or lower title is not showing up.  what's important is  only one title showing up in the reader 

![IMG_20220504_115412](https://user-images.githubusercontent.com/25120376/166621386-0481d17a-7ad6-4a91-86b2-8859012dfb33.jpg)

**Comment by dteviot** [comment]
@seizue 
The problem is, some chapters have a title in the content part of the page/chapter, and some don't.
So, to make sure each chapter has a title, WebToEpub always grabs the title part of a page/chapter.
This means when the page also has a title in the content part, the epub does as well.
Having two titles never really bothered me, and It beats the alternative of not having a title at all.
And I haven't been willing to make the effort to try and filter out the second title when two titles occur.
Can I ask why this is a problem?

**Comment by seizue** [comment]
ahh I see. It irritates me tbh. It affects my reading experience.. That's fine, I will just dl in the other sites. I just prefer it because 'pack to epub' here is so much faster compare to the other sites but 2 tittles ruining it for me. You can close this issue

**Comment by dteviot** [comment]
@seizue 
I've had a think, and it might not be much work to fix.
Give me a day or two.

**Comment by dteviot** [comment]
@seizue

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://freewebnovel.com/fields-of-gold.html, a couple of chapters)
Note, only removes duplicate titles when they're exactly the same.  
I've seen a couple of chapters where the two titles are not quite the same, in which case the second is not deleted.

For my records: 37 minutes work

**Comment by seizue** [comment]
Thank You! 

That's fine. The 3 novels I want to dl have the same  titles so it won't affect me anyway xd
also I can use an alternative site instead. Thanks again!

**Comment by dteviot** [comment]
@seizure
If you don't mind my asking, what are the stories you're interested in?
I'm always looking for good stories.

**Comment by seizue** [comment]
- Second Life Ranker
- Berserk of Gluttony
- The Villain Wants to Live
- Leveling with Gods 
- Regressor Instruction Manual
- The Author's POV
- The Regressed Demon Lord is Kind
- Trash of the counts family 
- I'm Really Not The Demon God's Lackey
- I am Actually a Cultivation Bigshot
- I am the Fated Villain
- Monster Paradise
- Possessing Nothing
- My House of Horrors
- Black Tech Internet Cafe
- Gourmet of Another World 

They all good! I enjoy reading them. There are also MTL ones but I'll not say it since idk if you like reading MTL Novels. lol

**Comment by dteviot** [comment]
@seizue 
Thanks

**Comment by dteviot** [comment]
@swanknight 
Version in Chrome and Mozilla stores has not been updated yet.  (There's still work to be done on the WebNovel parser.)

You'll need to grab a test version from the link mentioned previously.

Note, I tried it with the chapter you mentioned, and Epub has only one chapter title.

**Comment by swanknight** [comment]
> You'll need to grab a test version from the link mentioned previously.
> 
> Note, I tried it with the chapter you mentioned, and Epub has only one chapter title.

I just did, but I still got the same issue of double chapter titles.
I tested it on this: https://novelfull.com/immortal-devil-transformation.html

**Comment by budikesuma** [comment]
@dteviot 

   I don't think it's a big deal for double chapter titles,  but if you can apply my method to your extension code, it might be able to detect those double chapter headings.  
   Since I'm using the manual scripting method to scrape novel sites, it might be a bit easier on my side than your extension method.  maybe I can share this script here.

For detecting double title chapters: 
```
if(contains(page,title))
{
page=replace(page,title)
}
```
That's simple on my side.

**Comment by swanknight** [comment]
@budikesuma can you explain how are you using the script? I'd like to try it for my own sanity.

**Comment by dteviot** [comment]
@seizue  @swanknight @budikesuma 
Updated version (0.0.0.149) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by swanknight** [comment]
@dteviot I'm still having the same issue. I noticed the title is repeated with slightly different formats.
I tried this script using EpubEditor, but it didn't work (no effect), even though it worked fine when I tested it in a JSFiddle.
Am I missing something?

```
let h1 = document.querySelector("h1");  
let h2 = document.querySelector("h2");  
if (h1 != null && h2 != null)
{
	h1.parentNode.removeChild(h1);
}
```

![2022-06-05 09_32_01-dvv epub -  Beast Armorer_ Infinite Evolution  - SumatraPDF](https://user-images.githubusercontent.com/46474713/172038641-b5b1ff85-eed0-4a19-9192-ff41c9de46cd.png)

**Comment by dteviot** [comment]
@swanknight 
1. You need to return true if text is modified.  EpubEditor expects the script to return true if text is modified and false if it is not changed.
2. Use "dom" not "document". 
e.g.
```javascript
let h1 = dom.querySelector("h1");  
let h2 = dom.querySelector("h2");  
if (h1 != null && h2 != null)
{
	h1.parentNode.removeChild(h1);
	return true;
}
return false;
```

**Comment by swanknight** [comment]
@dteviot I just tested it, and it works. My "OCD" thanks you. :D
