### ISSUE TITLE
https://www.id.joylada.com/story/60c49ef54e008600019abf27

### ISSUE THREAD

**Issue by Kucingmeong2** [dteviot/WebToEpub#734]
Hello :)
Sry for ask again ....can you add this website 🙏🙏🙏🙏

**Comment by Kucingmeong2** [comment]
Cancel

**Comment by dteviot** [comment]
Sorry.
* I can't read the language, 
* I think I need an account to view the content.
* And I can't figure out enough to even start to find things.

**Comment by Kucingmeong2** [comment]
Its ok I get from other web same novel 🙏🙏🙏🙏
