### ISSUE TITLE
Can't select multiple elements for content

### ISSUE THREAD

**Issue by minekasetsu** [dteviot/WebToEpub#736]
I tried using ".top_image , .content" for the css selector for the content, but it only grabs .top_image? using ".top_image" or ".content" works, and flipping it to ".content , .top_image" still only grabs .top_image.

The page I'm testing it on: https://en.touhougarakuta.com/column-en/behind-the-scenes-for-touhou-m-1s-translations

Additionally, I'm using WebToEpub on Kiwi Browser on Android, if that matters.

Sorry in advance to bother, and also for weird use case.

**Comment by dteviot** [comment]
@minekasetsu 
That's because for content it grabs the first element that matches the selection rule.
As I'm guessing you want the header (for first element) and the content following, you'll need to select an element in the tree that holds both.  In this case, it looks to me like ".post_article".

**Comment by minekasetsu** [comment]
Thanks! I had a hard time using css selector on android. I actually want to avoid most of the header besides the image, but I don't even know how to have both the header and the article besides selecting all with .body, which would necessitates me removing a whole bunch of stuff. With .post_article, I only have to remove a few, so thanks again for the help!
