### ISSUE TITLE
Please add site https://shanghaifantasy.com/

### ISSUE THREAD

**Issue by KatSaw** [dteviot/WebToEpub#739]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://shanghaifantasy.com/novel/villain-in-the-kindergarten/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes, did not work.

### What settings did you use?  What didn't work?
* URL of first chapter
https://shanghaifantasy.com/villain-in-the-kindergarten-chapter-1/
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
No, I don't have the skills.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
None of them have the skills.

**Comment by dteviot** [comment]
@KatSaw 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://shanghaifantasy.com/novel/villain-in-the-kindergarten/ chapters 1 & 77

For my notes: 29 minutes work

**Comment by dteviot** [comment]
@KatSaw 
Updated version (0.0.0.149) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
