### ISSUE TITLE
Please add site https://www.spiritfanfiction.com/

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#740]
at first it gives error, but
Note: if you put the address where the list of chapters is, you can select them only to download the chapters, but the content of the chapters is not only the chapters, but also the rest of the links and other things on the page that have nothing to do with it with the chapter.
I wish it would only take the chapters and not insert all the links and ads on the page

![Screenshot (2)](https://user-images.githubusercontent.com/29169926/169927229-1f3c2959-f8c2-415d-a704-bd57e5fc70a6.png)
![Captura web_24-5-2022_25544_](https://user-images.githubusercontent.com/29169926/169927246-ba066465-6cb9-41e6-bcb7-92c6c4bfc15d.jpeg)

**Comment by dteviot** [comment]
@bichitoxxx 
> I wish it would only take the chapters and not insert all the links and ads on the page

Sorry, trying to do that automatically is an hard AI problem.  And it's (usually) easier to delete items if they're not wanted, than add items if they were missed.

**Comment by dteviot** [comment]
@bichitoxxx 
Actually, I may have misunderstood.
I thought you were referring to figuring out the chapter links on the Table of Contents.
If you're referring to the contents on each page/chapter.  Then change "CSS selector for element holding content to put into EPUB" from "basic" to a better CSS selector.  In this case, it would be **div.texto-capitulo**

**Comment by bichitoxxx** [comment]
> @bichitoxxx Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
> 
> Tested with
> 
> * https://www.spiritfanfiction.com/historia/crime-for-love-all-for-you-draken-x-leitora-23737608
> * https://www.spiritfanfiction.com/historia/o-demonio-verde--hero-deku-19983276
> 
> For my notes: 30 minutes work

now it takes only the chapters and within the chapters it skips all the spam content and ads that have nothing to do with the story, so for me it looks good and it's worth it even if I later have to edit some things with caliber, for me it's perfect

**Comment by dteviot** [comment]
@bichitoxxx 
>I don't quite understand what you mean, what should I do?

There's nothing you need to do.
Although if you use the latest test build, it should handle the site without problems.

However, for future reference, when you see WebToEpub copying more from chapters than you want, the solution is to change the "CSS selector for element holding content to put into EPUB" from "basic" to a better CSS selector.

**Comment by dteviot** [comment]
@bichitoxxx 
Updated version (0.0.0.149) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
