### ISSUE TITLE
FireFox addon update

### ISSUE THREAD

**Issue by FrostDuchess** [dteviot/WebToEpub#741]
I just wanna ask if you plan on adding all the new sites you coded into the firefox addon update, and if you are, when?
Thank you for all your hard work and sorry for bugging you

**Comment by dteviot** [comment]
@FrostDuchess 
I assume you mean update the version in the Mozilla store.
Yes, I plan on doing that.  I was just waiting until I got the handling of webnovel site finished.

**Comment by dteviot** [comment]
@FrostDuchess 
Updated version (0.0.0.149) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
