### ISSUE TITLE
Chapter heading from Wattpad

### ISSUE THREAD

**Issue by lastwomanstanding** [dteviot/WebToEpub#744]
**Describe the bug**
Chapter heading shows as the Title instead of the Chapter title on TOC. I have only noticed this when downloading from https://www.wattpad.com

Link: https://www.wattpad.com/story/139729965-maybe-this-time
Generated: May 25, 2022

**Expected behavior**
Chapter heading is the same as the title chapter shown in TOC

**Screenshots**
![TOC](https://user-images.githubusercontent.com/105410957/170198158-24a3b14c-9b5c-4cb3-b6ea-ae2a294ce1de.png)
![Chapter 1](https://user-images.githubusercontent.com/105410957/170198194-4d691054-c70e-426f-a21e-c215aa3a55af.png)
![Chapter 2](https://user-images.githubusercontent.com/105410957/170198214-f68805a8-28a8-448f-8eb3-72a731d16d29.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: LVL3 (core: 86.0.4363.64)

**Comment by dteviot** [comment]
@lastwomanstanding 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with: https://www.wattpad.com/story/139729965-maybe-this-time

For my records: 25 minutes work.  (19 code, 6 minutes publishing.)

**Comment by dteviot** [comment]
@lastwomanstanding 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
