### ISSUE TITLE
Running Webtoepub on old Firefox Android

### ISSUE THREAD

**Issue by drjoe123** [dteviot/WebToEpub#746]
So I've mentioned in some other threads that I'm still running Webtoepub on Firefox for Android ver 68.10.1

Well, I migrated toa new tablet this week and tried to reinstall Firefox with WebtoEpub to much frustration, until I realized that my old tablet was running WebtoEpub 0.0.0.140, and nothing after that would load as an add on. So I have the plug in again. 

Any idea what might have broke? I'll live with the old build, but could the newer builds still run on the old Android Firefox?

Thanks

Joe

**Comment by dteviot** [comment]
@drjoe123 
As part of 0.0.0.141, Minimum Firefox version moved from 63.0 to 79.0.  See: https://github.com/dteviot/WebToEpub/commit/cd60ded02e3e284eae995e915f8d32ed27e1f6de
I wanted to take advantage of the Optional chaining operator.  It results in shorter, easier to read code.

That said, it would probably be possible to grab the latest version of WebToEpub and revert it to work on 68.10.1.
The quick and dirty way would be open the xpi  (it's just a zip file with a different extension), change the manifest.json file and rezip.
So long as you don't use any parsers that use optional chaining, it should just work.
You could also search for optional chaining and replace with ternary operators.  Although that would require a small degree of developer skill.

**Comment by dteviot** [comment]
@drjoe123 
Did a quick check, I'm not using Optional chaining in the core (yet).  So should just work.

**Comment by drjoe123** [comment]
I tried copying the manifest.json file from the 0.0.0.140 file and overwriting it in the most recent file, but the "about:debugging" command doesn't work on Android Firefox. I told Firefox to open the file and it says "unable to download".  

The real issue is that  Chrome for Android doesn't support extensions and Firefox for Android castrated them when they went to the new platform. I think you mentioned once that Firefox Nightly still worked, but doesn't seem to any more.

I really use your extension a lot -- certainly on a several times weekly basis, but mostly on my Windows 11 laptop. I use the Android browser infrequently when I'm in an airport or lazy away from my laptop. I really appreciate the trouble you take supporting it. I ca use the older version in "emergencies" on my tablet and the latest and greatest on my PC.

Thanks again,

Joe

**Comment by Dlordload** [comment]
@drjoe123 kiwi browser supports chrome extensions

**Comment by josephfrances123** [comment]
I'm using this extension with Kiwi browser but I am also facing problems like errors on fetching

**Comment by budikesuma** [comment]
@drjoe123 
Hello...

Firefox both old and nightly versions which are said to support extensions, are no longer able to upload modern extension data.
So you only need to use kiwi browser or yandex browser.
And there is no other choice anymore. My suggestion is to close this issue immediately...

**Comment by drjoe123** [comment]
I'm fine with it. But to reiterate: for folks who synchronize tabs between devices on Firefox and want to stick to one cross-platform browser, there is a last working version for Firefox and Webtoepub that work together. 

Firefox for Android version 88.10.1 
Webtoepub version 0.0.0.140

Both can be downloaded from archives of old versions on their respective pages. After you install Firefox, you need to disable automatic updates for that app.

take care,

Joe

**Comment by drjoe123** [comment]
Thanks,  I'll try it out.

Joe



________________________________

**Comment by gamebeaker** [comment]
#1146 it is android firefox is compatible.
