### ISSUE TITLE
Please add site https://moonlightnovels.com

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#749]
Edit: I think I got it, but I'll leave this up in case anyone else needs it. The CSS selector you need to use is **.elementor-element-d004fdc > div:nth-child(1)**
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://moonlightnovels.com/novels/mystery-clock/
view-source:https://moonlightnovels.com/mystery-clock/mc-chapter-1/ (right click is disabled, you'll have to bypass that however you want if you're viewing the regular page)
### Did you try using the Default Parser for the site?  If not, why not?
It sorta works if I use BODY, but I can't figure out how to precisely make it parse the needed text (it grabs the entire page, Discord etc. and all).

### What settings did you use?  What didn't work?
* URL of first chapter
https://moonlightnovels.com/mystery-clock/mc-chapter-1/
* CSS selector for element holding content to put into EPUB
body
* CSS selector for element holding Title of Chapter
title
* CSS selector for element(s) to remove
script

**Comment by dteviot** [comment]
@Tenome 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://moonlightnovels.com/novels/mystery-clock/

For my notes: 55 minutes work

**Comment by dteviot** [comment]
@Tenome 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
