### ISSUE TITLE
Include translator notes for https://exiledrebelsscanlations.com/

### ISSUE THREAD

**Issue by KatSaw** [dteviot/WebToEpub#750]
**Is your feature request related to a problem? Please describe.**
Translator notes are not included for site https://exiledrebelsscanlations.com/

**Describe the solution you'd like**
Include translator notes at the end pf the chapter. Example of chapter with translator notes:
https://exiledrebelsscanlations.com/iuilbrc-chapter-32/

**Comment by dteviot** [comment]
@KatSaw 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://exiledrebelsscanlations.com/iuilbrc-chapter-32/

Notes:
1. There are some images that are no longer downloadable (so you'll get some warnings, but it still works.
2. You'll need to uncheck "Remove Author Notes"

![image](https://user-images.githubusercontent.com/5157081/172034944-ef9c8289-31f2-4dad-8f32-721b25fe62db.png)

For my notes: 27 minutes work

**Comment by KatSaw** [comment]
It works perfectly, thank you a whole lottt

**Comment by dteviot** [comment]
@KatSaw 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
