### ISSUE TITLE
Please add site https://skydemonorder.com/projects/genius-profiler-hansol-im

### ISSUE THREAD

**Issue by SaraDalbah** [dteviot/WebToEpub#752]
Please add site https://skydemonorder.com/projects/genius-profiler-hansol-im

**Comment by dteviot** [comment]
@SaraDalbah 
Oh, this one's easy.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with:
* https://skydemonorder.com/projects/descent-of-the-demon-god, prolog and chapter 244
* https://skydemonorder.com/projects/reformation-of-the-deadbeat-noble, prolog

For my notes: 26 minutes work

**Comment by SaraDalbah** [comment]
Thank you so much!!!!!

**Comment by dteviot** [comment]
@SaraDalbah 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
