### ISSUE TITLE
webnovel.com - Error: No chapters found

### ISSUE THREAD

**Issue by lastwomanstanding** [dteviot/WebToEpub#754]
**Describe the bug**
Chapters are not populating on non-mobile but on android, it shows that no parser is found. I re-downloaded the extension for Chrome via the GDrive link but still get the same error.

**To Reproduce**
1. Go to (https://www.webnovel.com/book/kinnporsche-the-novel-eng-translation_23194730606532905)
2. Click on WebToEpub extension
3. Wait for the details to populate
4. See error message

**Expected behavior**
Chapters of the novel will populate

**Screenshots**
![error1](https://user-images.githubusercontent.com/105410957/172622629-4a0b1291-be0a-4dad-b298-ebf82eb32c12.png)
![error](https://user-images.githubusercontent.com/105410957/172622666-c2494033-83dc-4a9e-8cc0-853d37f5b3b9.png)
Android tablet error:
![photo_2022-06-08_20-58-23](https://user-images.githubusercontent.com/105410957/172623505-7c7c65d7-b9a3-4065-8c93-736e125c73a9.jpg)
![photo_2022-06-08_20-58-22](https://user-images.githubusercontent.com/105410957/172623521-e8da76bf-9fc2-485c-9c8a-5f0945175fdc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: LVL 3 (core: 86.0.4363.70)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab 3V and Samsung A50s
 - OS: Android 4.4 and Android 11
 - Browser: Kiwi
 - Version 

**Additional context**
I don't know if this is related to the recent issue raised here but to be sure, I opened a new one.

**Comment by dteviot** [comment]
@lastwomanstanding 
Before opening WebToEpub, click on the "Table of Contents" tab so that page is showing the list of chapters.  If page isn't showing any chapters, WebToEpub can't find any.
