### ISSUE TITLE
Please add site https://teenfic.net

### ISSUE THREAD

**Issue by lastwomanstanding** [dteviot/WebToEpub#758]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://teenfic.net/stories/beautiful-belle-and-alpha-grayson-211001342/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes, but there are a lot of elements that are being read as well that I did not know how to remove

### What settings did you use?  What didn't work?
* URL of first chapter - https://teenfic.net/beautiful-belle-and-alpha-grayson-chapter-1-825605637.html
* CSS selector for element holding content to put into EPUB - div.chapter-content
* CSS selector for element holding Title of Chapter - h2.chapter-title
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
I am not a developer

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I do not know anyone who can do it. I'm sorry.

**Comment by dteviot** [comment]
@lastwomanstanding 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with 
* https://teenfic.net/stories/beautiful-belle-and-alpha-grayson-211001342/ chapters 1 and 60
* https://teenfic.net/stories/harry-crow-81652050/, chapter 1

Note, harry-crow had chapters which were split across 2 web pages.  I do not find any chapters split across more than 2 chapters, so I don't know if it will work for them.

For my notes: 54 minutes work

**Comment by dteviot** [comment]
@lastwomanstanding 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
