### ISSUE TITLE
Please add site https://secondlifetranslations.com/ to MergeWebtoEpub

### ISSUE THREAD

**Issue by laziestperson** [dteviot/WebToEpub#760]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://secondlifetranslations.com/novel/departure-gate-no-8/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes, it works but some parts of the chapters come out as gibberish.

### What settings did you use?  What didn't work?
* URL of first chapter
https://secondlifetranslations.com/dgn8/dgn8-chapter-1/
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

I saw this https://github.com/dteviot/WebToEpub/issues/683 and I was wondering if it's possible to add this function to MergeWebtoEpub as I've had a problem using EpubEditor as mentioned in https://github.com/dteviot/WebToEpub/issues/718

**Comment by dteviot** [comment]
@laziestperson 
For traceability, this should be raised against MergeWebToEpub.  
https://github.com/dteviot/MergeWebToEpub/issues.
But I'll see what I can do.

**Comment by laziestperson** [comment]
Oh, my bad, should I repost on MergeWebToEpub then?

**Comment by dteviot** [comment]
@laziestperson 
> Oh, my bad, should I repost on MergeWebToEpub then?
Yes, please

**Comment by dteviot** [comment]
Raised against wrong project.
