### ISSUE TITLE
Allow password entry for sites

### ISSUE THREAD

**Issue by dnmhunter** [dteviot/WebToEpub#762]
Some sites like https://chrysanthemumgarden.com/novel-tl/divorce/ require password to be entered for each page, to stop scrapers
I know you can create a javascript script to auto enter a password, as the text box always has the same element

Is it possible to implement something like this? 
either allow user to enter, the password textbox element, and the password, and if element is found submit the password, before scraping?
cangji.net also has a password on a few novels, but it only needs to be entered once
There are also sites that require multiple passwords, (e.g. one for each arc) but i guess user can just download up to the point the password isn't valid, and do the next arc separately?

(This assumes user has the password)

**Comment by dteviot** [comment]
@dnmhunter 
Sorry, but if site is doing things like that, if WebToEpub was to work around it, it would violate Google's rules for Chrome Extensions, and would get WebToEpub banned from the Chrome store.
