### ISSUE TITLE
Can we download novels in txt files ?

### ISSUE THREAD

**Issue by marodev1** [dteviot/WebToEpub#763]
Hello,

First i want to thank the developpers for this amazing extention.

I just want to know if is it possible to download each chapter in a txt files instead of all chapters in epub.

If not can we create an epub for each chapter ?

Thanks in advance

**Comment by budikesuma** [comment]
No, no one want it m⁸...

**Comment by dteviot** [comment]
@marodev1 
If you want each chapter in a separate file, just unzip the epub file.

**Comment by marodev1** [comment]
@dteviot  Thanks a lot for your response :) i appreciate it. the problem is that i have xhtml and have to convert all the chapters in txt :) so i was wondering if there is an option that let u download each chapters in txt files.

**Comment by dteviot** [comment]
@marodev1 
Have you tried using Calibre?
https://www.epubor.com/how-to-convert-epub-to-txt.html#:~:text=Step%201download%20Calibre%20to,output%20format%2C%20then%20click%20OK.

**Comment by marodev1** [comment]
@dteviot Yes i did but i have all chapters in one txt files. Its okey, i just found a python script that convert xhtml in txt files. Thank u a lot for your suggestions :)
