### ISSUE TITLE
Please add site https://novelebook.com

### ISSUE THREAD

**Issue by lastwomanstanding** [dteviot/WebToEpub#764]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelebook.com/bye-my-irresistible-love-bd1574.html

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes but not working

### What settings did you use?  What didn't work?
* URL of first chapter https://novelebook.com/bye-my-irresistible-love/r69323.html
* CSS selector for element holding content to put into EPUB 
* CSS selector for element holding Title of Chapter h2.chapter-title
* CSS selector for element(s) to remove

**Comment by dteviot** [comment]
@lastwomanstanding 

Sorry, not possible, half the content for each chapter is encrypted.

For my notes: 67 minutes.
