### ISSUE TITLE
Please add site https://skydemonorder.com/

### ISSUE THREAD

**Issue by hesoyamma785** [dteviot/WebToEpub#765]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://skydemonorder.com/
https://skydemonorder.com/projects/reformation-of-the-deadbeat-noble
### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by lastwomanstanding** [comment]
The parse for this site was added recently. See https://github.com/dteviot/WebToEpub/issues/752

 I also checked the link provided and it is working on my end.

**Comment by hesoyamma785** [comment]
![image](https://user-images.githubusercontent.com/77359705/176503357-851429c6-330c-461d-a7a1-302c07573c07.png)
It doesn't work for me.
is it working in beta web2epub? that in #752 said "go to this drive link and download it to see whether it would work or not"?

> The parse for this site was added recently. See #752
> 
> I also checked the link provided and it is working on my end.

**Comment by dteviot** [comment]
@hesoyamma785 
>is it working in beta web2epub? that in https://github.com/dteviot/WebToEpub/issues/752 said "go to this drive link and download it to see whether it would work or not"?

Yes.

**Comment by hesoyamma785** [comment]
@dteviot well mine is Google app store version
Maybe I should check with that one

**Comment by dteviot** [comment]
@hesoyamma785 
I have not yet updated the Google store with a version that supports https://skydemonorder.com/

**Comment by dteviot** [comment]
@hesoyamma785 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
