### ISSUE TITLE
Please add site https://novelonomicon.com

### ISSUE THREAD

**Issue by pavan3999** [dteviot/WebToEpub#766]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelonomicon.com/
https://novelonomicon.com/category/novels/isekai-yururi-kikou/page/27/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter: https://novelonomicon.com/novels/isekai-yururi-kikou/prologue/
* CSS selector for element holding content to put into EPUB: div.g1-content-narrow
* CSS selector for element holding Title of Chapter: h1.g1-giga
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@pavan3999 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
