### ISSUE TITLE
Problem with [https://cangji.net/]. This site doesn't seem to work as it used to anymore.

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#768]
Hello!

I previously requested this website to be added to WebToEpub and it used to be able to **find and load all the chapters from the category** perfectly. But for some reason, it went back to the how it was before and only loads 10 chapters which are the first chapters that appear on the first page of the category, and won't continue to search for the rest of the chapters in the other pages of the entire category?

And sometimes it will stop processing the EPUB mid-way and just generate the chapters partially, freeze for some time and then the save pop-up will appear without finishing processing the rest of the chapters...

I was wondering if there would perhaps be any way to fix this issue with this specific site? I apologise for my poor explanation. Thank you very much for your hard work!

**Comment by dteviot** [comment]
@vanessabluellie 
> only loads 10 chapters which are the first chapters that appear on the first page

Site has probably changed layout, so WebToEpub can't find the rest of the chapter links.  I'll look into that sometime in the next few days.

> generate the chapters partially, freeze for some time and then the save pop-up will appear without finishing processing the rest of the chapters

I suspect problem is you're having problems fetching a chapter, and the default behavior in that case is for WebToEpub to stop at that point.  You can override by opening the advanced options and turn on
> Skip chapters that return HTTP 404 error

However, give me the URL of a story that does this, and I'll see what I can do.

**Comment by vanessabluellie** [comment]
Hello! Very sorry for late reply! But I did a couple more checks with the website and it seems that it wouldn't load and process because I used the wrong password... So unfortunately, I wouldn't be able to pack the epub since I don't have the right password. Sorry for taking up your time with this issue, and thank you as always for your extreme dedication and hard work!
