### ISSUE TITLE
Include footnotes for Chrysanthemum Garden's website

### ISSUE THREAD

**Issue by KatSaw** [dteviot/WebToEpub#769]
**Is your feature request related to a problem? Please describe.**
Chrysanthemum Garden has hovering footnotes so I think that's why WebtoEpub can't generate it. You have to click the underlined words to see the notes. As an example:

![photo1657355286](https://user-images.githubusercontent.com/90402642/178098146-a59e4fc9-9839-4d4e-96ec-38f0411c10ae.jpeg)

Example is from https://chrysanthemumgarden.com/novel-tl/pdsm/pdsm-2/
Table of Contents: https://chrysanthemumgarden.com/novel-tl/pdsm/

**Describe the solution you'd like**
I'd like for the footnotes to be included in the epub if possible.

**Comment by dteviot** [comment]
@KatSaw 

I had a try at doing this for https://chrysanthemumgarden.com/novel-tl/pdsm/pdsm-2/

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 39 minutes

**Comment by KatSaw** [comment]
I did a try with it on https://chrysanthemumgarden.com/novel-tl/lingxi/lingxi-1/

I guess cuz all the translator's notes are gathered at the bottom, it's difficult to distinguish for which sentence is the notes for. It can be fixed with Calibre though.

**Comment by dteviot** [comment]
@KatSaw 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
