### ISSUE TITLE
Make WebToEpub more known/available/useful to EPUB creation sites.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#77]
There are a number of sites that offer free WebToEpub conversion services.  e.g. https://lnwnepubs.wordpress.com
It would be good if they were made aware of the plugin, and I got feed back from them on how to improve it for their use.
One thing that might help, a tutorial showing how the plug-in can be used in "Default" mode to create an EPUB.  And then using Calibre or Sigil to clean up the result.

**Comment by toshiya44** [comment]
Add an image style guide maybe? I'll give it a shot.
I'll also try to advertise it in some of the discord groups when I get a chance. Although this extension was initially made for Baka-Tsuki, it is awesome for making epubs from sites like wordpress (which is website many translators are moving towards). 

Also, any ETA for when the extension gets approved? People will hesitate to install it if it's not marked approved by Mozilla.

**Comment by dteviot** [comment]
@toshiya44
>Also, any ETA for when the extension gets approved? People will hesitate to install if it's not marked approved by Mozilla.

I'm assuming you're referring to the "Has been flagged as experimental" on the Firefox downloads site.
I was not aware this had been done.  That said, I'll be submitting the latest version 0.0.0.19 to Mozilla for full approval tonight once I get the Vietnamese translation merged in.  Based on last time, it will be about 4 weeks to get it validated.

**Comment by dteviot** [comment]
@toshiya44 
>Also, any ETA for when the extension gets approved?

Was approved last night.

**Comment by toshiya44** [comment]
That's good news. 
Can you please add the updated list of supported sites too?

**Comment by dteviot** [comment]
@toshiya44
> Can you please add the updated list of supported sites too?

Done.  Note, list isn't complete because I'm leaving most sites with only a small number of stories off the list to reduce clutter.  (Some made it onto the list because I can't remember all the small ones.)

**Comment by Jaykoerner** [comment]
(not a knock on webtoepub, its more a knock on the inconsistinsy of translators)i doubt any of the good one's will use this, i make personal epubs my self(around 300 at this point) and i find most of the sites so inconsistent with naming conventions, placement of chapter names(i especially hate when it moves in and out of the main div every other chapter), paragraph styles(those stupid non breakable spaces all throughout the content anyone?), ect... that i just manually copy/paste and the most o do to speed things up is use a css styler application to remove all the comments/adds/sidebars off the page and just paste it into libre office and run my set of scripts to remove all blank paragraphs, TL notes, non-breakable spaces, turn all the chapter headings to h1 save as odt, and then just place it into calibre to convert to epub add a cover and meta-data, I can manage 10-15 chapters a minute if i dont care about  adding endnotes for all the TL notes all over the place(honestly most aren't nessasary if you've read a ton of Chinese/Korean/Japanese translated novels already. idk maybe I try too hard i even go through the trouble of using gimp to Photoshop english  titles into some of the covers.
