### ISSUE TITLE
Please add site https://novel35.com/

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#770]
Hello

Is it possible to add this website : https://novel35.com/

Here is an exemple : https://novel35.com/white-online

Thank you very much for all your work ! :)

**Comment by dteviot** [comment]
@Flwk 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with chapter 1 of https://novel35.com/white-online

For my notes
1. Seems to be variant of novelfull
2. Time taken 45 minutes

**Comment by Flwk** [comment]
@dteviot thank you so much !

**Comment by dteviot** [comment]
@Flwk
Reopen, so I know to contact you when Chrome and Firefox stores updated.

**Comment by dteviot** [comment]
@Flwk 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
