### ISSUE TITLE
Please add site https://www.webnovel.com

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#771]
Can you please add this site thanks here is a link to one of the stories
https://www.webnovel.com/book/harry-potter-and-the-rise-of-the-protector_17990253906989505

**Comment by HermanFassett** [comment]
It already works if you select the Table of Contents first. You may need to uncheck the first url though if it's not a chapter, that has caused me some issues before.

**Comment by dteviot** [comment]
@kolbdog3333 
HermanFassett is correct.  You need to select Table of Contents.
