### ISSUE TITLE
Left-align text? 

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#773]
I used this, but it doesn't seem to work.

div.svg_outer {
   display: block;
   margin-bottom: 0;
   margin-left: 0;
   margin-right: 0;
   margin-top: 0;
   padding-bottom: 0;
   padding-left: 0;
   padding-right: 0;
   padding-top: 0;
   text-align: left;
}
div.svg_inner {
   display: block;
   text-align: left;
}
h1, h2 {
   text-align: left;
   margin-bottom: 10%;
   margin-top: 10%;
}
h3, h4, h5, h6 {
   text-align: left;
   margin-bottom: 15%;
   margin-top: 10%;
}
ol, ul {
   padding-left: 8%;
}
body {
  margin: 2%;
}
p {
  overflow-wrap: break-word;
}
dd, dt, dl {
  padding: 0;
  margin: 0;
}
img {
   display: block;
   min-height: 1em;
   max-height: 100%;
   max-width: 100%;
   padding-bottom: 0;
   padding-left: 0;
   padding-right: 0;
   padding-top: 0;
   margin-left: auto;
   margin-right: auto;
   margin-bottom: 2%;
   margin-top: 2%;
}
img.inline {
   display: inline;
   min-height: 1em;
   margin-bottom: 0;
   margin-top: 0;
}
.thumbcaption {
  display: block;
  font-size: 0.9em;
  padding-right: 5%;
  padding-left: 5%;
}
hr {
   color: black;
   background-color: black;
   height: 2px;
}
a:link {
   text-decoration: none;
   color: #0B0080;
}
a:visited {
   text-decoration: none;
}
a:hover {
   text-decoration: underline;
}
a:active {
   text-decoration: underline;
}table {
   width: 90%;
   border-collapse: collapse;
}
table, th, td {
   border: 1px solid black;
}

I used this site to convert it into azw3: https://e-conv.com/ 
and transferred the files to my kindle from my phone via OTG adapter. 

Don't know if it's a problem with the conversion site or the extension. 

I know I could just use calibre, but turning the computer on every time is a hassle.

**Comment by Iadders** [comment]
I just tested it out with calibre

Format: AZW3

Text-Justification: Original

and it stills comes out the same with it being justified, so I don't think it's a problem with the conversion site.

**Comment by dteviot** [comment]
@Iadders 
I'm sorry, but what are you trying to do?
Specifically:
1. What are you seeing?
2. How does it differ from what you want?

**Comment by Iadders** [comment]
@dteviot

1. What I see:
![IMG_20220721_024245](https://user-images.githubusercontent.com/84446964/180087687-c10d098e-53e8-4c37-ac13-9f2fc1c5d604.jpg)

3. What I want to see:
![IMG_20220721_024327](https://user-images.githubusercontent.com/84446964/180087855-793e975b-1670-4084-8182-da809267f264.jpg)

**Comment by dteviot** [comment]
@Iadders 
I think you need to add the "text-align: left;" to the p element in the stylesheet.
e.g.
```css
p {
overflow-wrap: break-word;
text-align: left;
}
```
Notes
1. I'm not an expert at this, and haven't tested it, so I'm not 100% sure this will work.
2. If you're using Calibre, you can probably modify the stylesheet in the epub file without needing to re-create the epub.  Then convert to AZW3

**Comment by Iadders** [comment]
>

**Comment by Iadders** [comment]
> p {
overflow-wrap: break-word;
text-align: left;
}

This worked, thank you!
