### ISSUE TITLE
Please add website https://novelvice.com/

### ISSUE THREAD

**Issue by Vgkd** [dteviot/WebToEpub#774]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://novelvice.com/novel/imperial-beast-evolution-fey-evolution-merchant/chapters/

**Comment by dteviot** [comment]
@Vgkd 
Closing Duplicate.  See: https://github.com/dteviot/WebToEpub/issues/719
As you can guess, based on fact it's still not done, this one's not easy to do.
