### ISSUE TITLE
Suddenly not working in Kiwi Browser

### ISSUE THREAD

**Issue by josephfrances123** [dteviot/WebToEpub#777]
**Describe the bug**
This extension was working on my phone until recently. I can't fetch epub from sites anymore as it always says that there are errors. Like, I tried different sites I've used before but it wasn't working anymore. Even in my laptop, I'm facing the same problem too even though it's Chrome in my laptop.

**Expected behavior**
Hope you can help me, because maybe it's just my phone or something.

**Screenshots**
![IMG_20220722_231139](https://user-images.githubusercontent.com/85727628/180469748-3f7d206a-03d1-409d-b6f4-5bca297d8750.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josephfrances123** [comment]
![Screenshot_20220722_233601](https://user-images.githubusercontent.com/85727628/180474170-b8a7b1c2-7e61-4b2f-8a6c-b882fa25aa96.jpg)

**Comment by dteviot** [comment]
@josephfrances123 
Unfortunately, there's not enough information for me to help you.
The version in the Chrome and Firefox stores hasn't changed since May 25.
Or are you using the test version I upload to Google Drive.
In which case, does the version from the Chrome store work?

The fact that you're having a problem with both Phone and Laptop versions suggests the problem might be your network or the Site.  What Site(s) are you having problems with?

**Comment by Iadders** [comment]
Works perfectly fine for me on the kiwi browser. Probably a problem with your network or the site(s). 

Have you tried using a VPN? I got banned from a couple of sites for setting the max web pages to fetch simultaneously at an 8.

**Comment by josephfrances123** [comment]
Good day. I'm using the one in Chrome Store for my phone. The site that banned me or denied my access is readwn.com and maybe it's because I set the pages to fetch at 8?

And yes, I also tried VPN in my phone but it didn't work.

**Comment by josephfrances123** [comment]
Problem solved!!! My phone solved it for me. Joking aside, I was checking my phone here and there, and viola. I got to fetch pages at the moment. 🥳🥳🥳

Anyways, thank you so much for all your assistance, it really helped me a lot especially when I don't know a thing about programs. I'm just your normal reader who is desperate to read offline epubs. 

Thank you so much and may God bless us all
