### ISSUE TITLE
Please add site https://goblinsguide.com/category/shen-mu-divine-grave-en/

### ISSUE THREAD

**Issue by Okikaemmanuel1** [dteviot/WebToEpub#778]
###https://goblinsguide.com/category/shen-mu-divine-grave-en/

**Comment by dteviot** [comment]
@Okikaemmanuel1 
It's difficult.  Looks like many of the stories don't have working Table of Contents, so it's not possible to get list of URLs for the chapters.
e.g.
* https://goblinsguide.com/i-am-the-richest-heir-of-mankind-en/i-am-the-richest-heir-of-mankind/
* https://goblinsguide.com/category/shen-mu-divine-grave-en/

I did a quick hack for https://goblinsguide.com/master-fu-s-prideful-wife-en/
Which at least gets the chapters that are shown on the page.  (Can manually get groups of chapters.)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Notes:
1. Time spent: 1 hour.
2. It might be possible to get full list of chapters (for some stories) with a POST call to https://goblinsguide.com/wp-admin/admin-ajax.php
With arguments
* action: select_Ajax
* query: catChapters
* cat_id: 2596
* security: 4ae27614f2

Where security and cat_id come from scripts in
>var myajax = {"url":"https:\/\/goblinsguide.com\/wp-admin\/admin-ajax.php","nonce":"0d88340ff8"};

and 
> let cat_id = 2596

**Comment by Okikaemmanuel1** [comment]
Thank u so much had s
