### ISSUE TITLE
 Can u please add https://wtr-lab.com/en/serie-234/humanitys-great-sage

### ISSUE THREAD

**Issue by Okikaemmanuel1** [dteviot/WebToEpub#782]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

###https://wtr-lab.com/en/serie-234/humanitys-great-sage

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by Flwk** [comment]
Hello

Is it possible to add this website @dteviot 

Here is another example : https://wtr-lab.com/en/serie-61/keyboard-immortal

Thanks a lot ! :)

**Comment by dteviot** [comment]
@Flwk @Okikaemmanuel1 
It's going to be a couple of weeks at least before I can get onto this.  
RL issues.

**Comment by dteviot** [comment]
@Okikaemmanuel1 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://wtr-lab.com/en/serie-234/humanitys-great-sage, chapter 1

For my notes: 67 minutes work

**Comment by Flwk** [comment]
@dteviot Thank you so much ! It works very well :)

**Comment by Okikaemmanuel1** [comment]
Thank u very much

**Comment by dteviot** [comment]
@Okikaemmanuel1 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
