### ISSUE TITLE
panda-novel only downloading titles

### ISSUE THREAD

**Issue by autoNMS** [dteviot/WebToEpub#784]
While using epub on panda novel, it is only downloading the titles, and not the chapter content

1. Go to pandanovel
2. select any novel
3. click web to epub

 it populates chapters with proper urls, but when i open epub it only has chapter no and title.

**Comment by Jayanth005** [comment]
Yes, the same thing is happening to me.
Pls, fix this.

**Comment by nandakishore2009** [comment]
Hi @dteviot 

It seems the website chapter contents are dynamically put.

Attaching the fixed parser: 
[PandaNovelParser.zip](https://github.com/dteviot/WebToEpub/files/9277327/PandaNovelParser.zip)

**Comment by autoNMS** [comment]
Working after adding the new parser

**Comment by dteviot** [comment]
@nandakishore2009

**Comment by dteviot** [comment]
@nandakishore2009 
1. Firstly, thank you for the revised parser, it is appreciated.
2. I'd like for GitHub to record you doing this work, so can you submit it as a Pull Request to the https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode banch?
3.  If you are going to submit, there's a couple of changes that would be good.
3.1. Mozilla and Google don't like extensions that write to the innerHTML property.  Preferred way is to use the DOMParser. See https://github.com/dteviot/WebToEpub/commit/8ac62f0cd97d99eee0c9b77c96dd35168c6d8701 for an example of how I've fixed this in the past
3.2 Line 57 uses single quotes, they should be double quotes.
3.3 The empty block on line 59 gives a eslint error, fix with comment like so
```javascript
            } catch (e) { }  // eslint-disable-line no-empty
```

Finally, unfortunately, the PandaNovel site isn't working for me.  Even when I view it in the browser, stories don't show any table of contents.  Do I need to log in?

**Comment by unOmni** [comment]
> Finally, unfortunately, the PandaNovel site isn't working for me.  Even when I view it in the browser, stories don't show any table of contents.  Do I need to log in?
> 

Not at all, you needn't be logged in to view chapters.

**Comment by dteviot** [comment]
@nandakishore2009
Test versions for Firefox and Chrome have been updated with your code and uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, not all chapters work.
e.g this one does not work.  (Attempts to get chapters fail with 403 errors, I'm guessing some sort of permission issue.)
* https://www.panda-novel.com/details/my-daughter-is-a-vampire(AN)-1443 

While this does work
* https://www.panda-novel.com/details/my-cold-and-elegant-ceo-wife(AN)-768

I have not yet investigated why this is.

**Comment by dteviot** [comment]
@unOmni @autoNMS  @Jayanth005 @nandakishore2009 

Very strange.
* https://www.panda-novel.com/details/my-daughter-is-a-vampire(AN)-1443 now worked.
But today.
* https://www.panda-novel.com/details/pornstar-system-1602 did not work.  And then did.  I'm not sure what I did to make it work.  
* Perhaps looked at a chapter? and then tried it again?
* Perhaps multiple tabs open?
If you can figure out what's going on, it would be nice to know.

**Comment by dteviot** [comment]
@unOmni @autoNMS @Jayanth005 @nandakishore2009
PS. 

Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by unOmni** [comment]
@dteviot

From my experience it seems it has something to do with captcha verification. If I enter the site straight using https://www.panda-novel.com/top , it'll take me in without any captcha therefore giving me an error everytime i try to use WTE. However when I go through captcha, WTE works just fine.

**Comment by dteviot** [comment]
@unOmni 
How do you get the captcha?
Also, have you tried to log in with an account?

**Comment by unOmni** [comment]
@dteviot 

I'm always connected with an account.

To get captcha, or to just get the secure connection check process, just simply use panda-novel.com instead of the link I mentioned before.

**Comment by budikesuma** [comment]
> @unOmni How do you get the captcha? Also, have you tried to log in with an account?

@dteviot 

No more account necessary...

In my experience you have to type the main address only or without `https`, or it can be with `http` only.

For example:

panda-novel.com

Or:

http://www.panda-novel.com (remember no `s` letter).
.

**Comment by Ayrsetz001** [comment]
Hi, I'm getting a 403 error when I try to convert. Its been about 2-3 weeks since I've scrapped my first book and I've only ever used webtoepub on this site once.
I've cleared my cache/history and re-downloaded the extention, I guess the only thing that im unable to do is get the captcha when i enter the site. I've followed @budikesuma 's example using just panda-novel.com and http://www.panda-novel.com (without the "s") but the captcha still doesnt show for me.
I've even paid for VPN and changed IP.
Can someone please explain what im doing wrong?

**Comment by Ayrsetz001** [comment]
@budikesuma 
lol I thought vpn would at least change my ip so i can get the captcha haha :'D that's prob not the purpose of vpn tho lolol
:'( but yeah, it's still not working for me. ad blocker is disabled and deleted the "s" on the web link on table of content, the page reloaded but still getting the 403 error...

**Comment by unOmni** [comment]
https is forced this time it seems. can't use http

**Comment by unOmni** [comment]
they updated the site today and it seems to be working again.
