### ISSUE TITLE
Please add site https://inoveltranslation.com/

### ISSUE THREAD

**Issue by kevin01523** [dteviot/WebToEpub#785]
https://inoveltranslation.com/novels/5

The way the sites load the novels seems a bit complicated and cannot be parsed normally 

Just a glance at the devtools and checking the elements seems to suggest its hard to work with. 

edit:tried again on pc and both mobile. i can only successfully parse the chapter title but not the body of the chapter as it wont load with the default parser using the selectors via devtools.

**Comment by dteviot** [comment]
@kevin01523 
It's going to be a couple of weeks at least before I can get onto this.  
RL issues.

**Comment by kevin01523** [comment]
No problem just do your best one thing at a time

**Comment by dteviot** [comment]
@kevin01523 
This is a duplicate request of https://github.com/dteviot/WebToEpub/issues/690

Version in Chrome & Firefox stores has not been updated yet.
However test version does support it.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with a couple of chapters from
* https://inoveltranslation.com/novels/5
* https://inoveltranslation.com/novels/28

For my notes: 31 minutes work

**Comment by dteviot** [comment]
@kevin01523 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
