### ISSUE TITLE
WoopRead text issue

### ISSUE THREAD

**Issue by courli79** [dteviot/WebToEpub#789]
a text that is not part of the story is inserted in the epub on the information page and in each chapter.
example : https://woopread.com/series/the-devilish-duke-cant-sleep-novelg/1/

text : "@media screen and (min-width: 1201px) {
.nlomg62ec16aacf8b5 {
display: block;
}
}
@media screen and (min-width: 993px) and (max-width: 1200px) {
.nlomg62ec16aacf8b5 {
display: block;
}
}
@media screen and (min-width: 769px) and (max-width: 992px) {
.nlomg62ec16aacf8b5 {
display: block;
}
}
@media screen and (min-width: 768px) and (max-width: 768px) {
.nlomg62ec16aacf8b5 {
display: block;
}
}
@media screen and (max-width: 767px) {
.nlomg62ec16aacf8b5 {
display: block;
}
}"

**Comment by dteviot** [comment]
@courli79 
It's going to be a couple of weeks at least before I can get onto this.  
RL issues.

**Comment by dteviot** [comment]
@courli79
Do you mean you're seeing text like this:
> https://github.com/media screen and (min-width: 768px) and (max-width: 768px) {
.nlomg62ec16aacf8b5 {
display: block;
}
}

In which case, I think the problem is with your epub viewer.  
1. I just tried https://woopread.com/series/the-devilish-duke-cant-sleep-novelg/chapter-1/, and don't see this text.  
2. I also looked at the packed epub file, and can't see it either.
3. Finally, this looks like CSS, which should not be shown to you.

What viewer are you using?

**Comment by courli79** [comment]
Hello, yes it is. I use ADE (Adobe Digital Editions). Indeed when reading the epub with Calibre, I don't see "@media screen and (min-width: 1201px) {
.sjdmo62ec162c8d32f {
display: block;
}
}".

**Comment by dteviot** [comment]
@courli79 
If your reader is acting up, I'm unable to assist with that.

**Comment by courli79** [comment]
Hello, the problem is solved on my side with this Parser
[WoopreadParser.zip](https://github.com/dteviot/WebToEpub/files/9500673/WoopreadParser.zip)

**Comment by dteviot** [comment]
@courli79 
I'm not sure how it solves your problem, as it doesn't seem greatly different from the MadaraParser.
However, I've added it to WebToEpub and built test version.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 23 minutes work

**Comment by courli79** [comment]
Thank you
