### ISSUE TITLE
Gravity Tales Broken

### ISSUE THREAD

**Issue by Quaturn** [dteviot/WebToEpub#79]
Hello it is now couple of minutes but [Gravity Tales](http://gravitytales.com) had some troubles with servers and since they fixed the problem WebToEpub stoped working on it.

The error message that it is showing when I try to turn Martial World to epub is:
```
util.getElement(...) is null extractTitle@moz-extension://47463440-fe6f-4bad-a965-067b2b4c5ba8/js/parsers/GravityTalesParser.js:26:16
getEpubMetaInfo@moz-extension://47463440-fe6f-4bad-a965-067b2b4c5ba8/js/Parser.js:137:26
processInitialHtml@moz-extension://47463440-fe6f-4bad-a965-067b2b4c5ba8/js/main.js:42:32
populateControlsWithDom@moz-extension://47463440-fe6f-4bad-a965-067b2b4c5ba8/js/main.js:168:9
onMessageListener@moz-extension://47463440-fe6f-4bad-a965-067b2b4c5ba8/js/main.js:12:9
@moz-extension://47463440-fe6f-4bad-a965-067b2b4c5ba8/js/main.js:28:17
```
I am using Firefox Developers Edition 51.0a2 (2016-10-11) (64-bit)

PS: This is great addon :-D

**Comment by dteviot** [comment]
@Quaturn 
> Hello it is now couple of minutes but Gravity Tales had some troubles with servers and since they fixed the problem WebToEpub stoped working on it.

Thank you for bringing this to my attention.
It looks like the layout of Gravity Tales has been completely changed. So, WebToEpub no longer knows how to handle it. I'll have to write a new set of parser rules.  It's likely to be at least 4 days before I have time to do this.

> PS: This is great addon

Thank you.

**Comment by dteviot** [comment]
@Quaturn
I have committed a “band-aid” fix to https://github.com/dteviot/WebToEpub/tree/sonako
Note, the new Gravity Tales format does not have all chapter URLs on the chapter page.  Instead they're downloaded on the fly as you make selections.
What this means is with this fix, WebToEpub can only find the URLs that are currently shown on the chapters page.  I'm going to have to figure out the sequence of REST calls and returned JSON objects to get the full list to chapters.  I won't have time to do this for several days.

The version of the plug-in on the Chrome store has been updated with the Band-aid fix.
An updated Firefox extension will probably take several weeks to get approved after I submit it, so if you want the fix before then you will need to install the plug-in from source.  The above URL has instructions on how to do this.

**Comment by dteviot** [comment]
@Quaturn 
Version 0.0.0.21 submitted to the Chrome store yesterday should solve the problem with Gravity Tales
It's also been submitted to Mozilla, but it's going to take a while to get approved.

@typhoon71/@toshiya44
RoyalRoad has also changed their format.  Version 0.0.0.22 (on both Experimental Tab and Sonako branch) has been updated and it coped with a couple of stories I gave it.  Care to take it for a test drive please?

**Comment by Quaturn** [comment]
Man you are doing awesome job god bless you :-D

**Comment by Quaturn** [comment]
if possible can you also create parser for http://www.xianxiaworld.net ? I do not know where is designated space for requesting pages for adding :-D

**Comment by dteviot** [comment]
@Quaturn 
> if possible can you also create parser for http://www.xianxiaworld.net ?

Probably, I'll look into it.
Create as a new issue please.  Things get lost when I add additional items to existing issues.

**Comment by dteviot** [comment]
@Quaturn 
OK, version 0.0.0.21 is now in the Mozilla downloads, but has been marked as "experimental".

**Comment by dteviot** [comment]
@Quatrun
> if possible can you also create parser for http://www.xianxiaworld.net ?

I've added a basic parser for XianXiaWorld.
You'll need to install from source from: https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode
Please let me know how well it works.
Thanks.

**Comment by Quaturn** [comment]
Thank you it work perfectly :-D you are doing hell of a great job with this addon :-D 
Also while at it can you specify in more detail how to use eslint for compiling the addon? (like more detailed step by step guide)

**Comment by dteviot** [comment]
@Quaturn
> Thank you it work perfectly :-D you are doing hell of a great job with this addon :-D 

It's nice to be appreciated.

> Also while at it can you specify in more detail how to use eslint for compiling the addon? (like more detailed step by step guide)

I don't understand what you're asking.
eslint doesn't compile the addon.  eslint is a static code checker, used to check for bugs in the code.
That said, I have a node.js script "eslint/pack.js".  This will assemble the addon into a zip file (for chrome) and a xpi file (for Firefox).  It also puts all the addon code into a single file "packed.js" for eslint to examine.
However, the zip and xpi are only needed to load to the Chrome and Firefox App stores.  You can load the unpacked addon into Chrome or Firefox directly.

But the basic steps to get eslint to examine this project are:
- Install node.js.
- Install eslint
- Use node's package manager to download and install the "xmldom" https://www.npmjs.com/package/xmldom package.  (needed by pack.js)
- Go to eslint directory and use node.js to run pack.js.
- This will produce packed.js and zip and xpi packaged versions of the addon.
- use the following command line to get eslint to check for bugs "eslint packed.js >error.txt"

**Comment by dteviot** [comment]
Gravity Tales and XianXiaWorld work with release 0.0.0.23.  Closing.
