### ISSUE TITLE
Paragraph spacing

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#791]
How do I change the paragraph spacing?

Specifically for this: https://www.aznovel.xyz/2022/03/456891.html?m=1

The space between the paragraphs is too big so I want it to only have a single line difference between the paragraphs.

**Comment by dteviot** [comment]
@Iadders 
Looks like there's a lot of paragraph elements that are empty.
So, you could use https://github.com/dteviot/EpubEditor with a script to delete them. 
I think the following will work  (note, not tested)
```javascript
            for(let p of [...dom.querySelectorAll("p")]) {
                let c = p.textContent.trim();
                if (c === "") {
                    p.remove();
                }
            }
            return true;
```

**Comment by dteviot** [comment]
@Iadders 
Closing due to no response.
