### ISSUE TITLE
Please add site https://peachblossomcodex.com/

### ISSUE THREAD

**Issue by KatSaw** [dteviot/WebToEpub#792]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://peachblossomcodex.com/novel/wioatbeosar/

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes, Default Parser does not work.

### What settings did you use?  What didn't work?
* URL of first chapter
https://peachblossomcodex.com/novel/wioatbeosar/wioatbeosar-ch-1/
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

**Comment by dteviot** [comment]
@KatSaw 
It's going to be a couple of weeks at least before I can get onto this.
RL issues.

**Comment by KatSaw** [comment]
Sure, take all your time needed. Hope everything goes well for you.

**Comment by dteviot** [comment]
@KatSaw

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with first chapters of 
* https://peachblossomcodex.com/novel/wioatbeosar/
* https://peachblossomcodex.com/novel/tiawtmwm/

For my notes: 39 minutes work

**Comment by KatSaw** [comment]
Tried it and works perfectly, thanks a lot.

**Comment by dteviot** [comment]
@KatSaw 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
