### ISSUE TITLE
Please add site https://noblemtl.com/

### ISSUE THREAD

**Issue by mynamex1** [dteviot/WebToEpub#793]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* [URL of first chapter](https://noblemtl.com/a-genius-wizard-who-escaped-from-prison-chapter-1/)
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@mynamex1 
It's going to be a couple of weeks at least before I can get onto this.
RL issues.

**Comment by mynamex1** [comment]
news ?

**Comment by dteviot** [comment]
@mynamex1 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with first chapter of
* https://noblemtl.com/series/a-genius-wizard-who-escaped-from-prison/

For my notes: 30 minutes work

**Comment by mynamex1** [comment]
thank you so much! it's working perfectly

**Comment by mynamex1** [comment]
there are some Portuguese sites that I would like to order, but you say to try to register first, it didn't work to register the site, would you like to make a video  how to register the site so it would be easier to understand how to do it

**Comment by Iadders** [comment]
> thank you so much! it's working perfectly

Try to keep max web pages to fetch simultaneously low(1-2), the site owners seem quite against novel scraping with the amount of protection they have set up. If they find out and want the dev to disable the source, the dev will have to comply.

**Comment by dteviot** [comment]
@mynamex1 @Iadders 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
