### ISSUE TITLE
Please add site https://rubymaybetranslations.com/table-of-content-forget-my-husband/

### ISSUE THREAD

**Issue by SaraDalbah** [dteviot/WebToEpub#794]
Please add https://rubymaybetranslations.com/table-of-content-forget-my-husband/

**Comment by dteviot** [comment]
@SaraDalbah 
It's going to be a couple of weeks at least before I can get onto this.
RL issues.

**Comment by SaraDalbah** [comment]
no problem

**Comment by dteviot** [comment]
@SaraDalbah 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with first couple of chapters of 
* https://rubymaybetranslations.com/table-of-content-forget-my-husband/
* https://rubymaybetranslations.com/table-of-content-ygtwhv/

For my notes: 47 minutes work

**Comment by dteviot** [comment]
@SaraDalbah 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
