### ISSUE TITLE
Hiding raws on lnmtl

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#798]
Can I have it so that the raws are hidden on lnmtl and only the english translation is shown?

**Comment by dteviot** [comment]
@Iadders 
Checking the button marked "Remove Original/Raw Text" should do it.
![image](https://user-images.githubusercontent.com/5157081/185763462-713283de-b903-4afe-a825-19b27c194824.png)

**Comment by Iadders** [comment]
Thank you.
