### ISSUE TITLE
Please update https://forum.questionablequesting.com/

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#799]
**Is your feature request related to a problem? Please describe.**
**Issue no. 1. The chapter content is in blockquote tag.** that's a problem because the extra margin from blockquote tag is kinda distracting. Also, because of this tag, I wouldn't be able to tell where the spoiler tag ended.
**Issue no. 2. Some link that lead to image was removed and then replaced with the image itself**

**Describe the solution you'd like**
for issue no.1, I'd like to remove the blockquote tag without removing chapter content.
for issue no.2, the link should stay as a link instead of an image. I like having images, but not at the cost of the text.

**Describe alternatives you've considered**
I don't know any viable alternatives.

**Additional context**
here are two images of the same series from the same website. one is taken using webtoepub, the other using fichub.net.
from chapter 11 of this fiction: https://forum.questionablequesting.com/threads/big-iron-on-his-hip-dc-si.19005/page-15#post-5823258

Screenshot for the one taken using webtoepub:

> ![c11 webtoepub](https://user-images.githubusercontent.com/70971903/185833506-98e602a9-61aa-4681-8d9b-428a6ea4fa63.png)

Screenshot for the one taken using fichub.net:

> ![c11 fichub](https://user-images.githubusercontent.com/70971903/185833563-eb2f0f63-7a81-4b2a-ada8-3e08d9099ef3.png)

**Comment by dteviot** [comment]
@SpiralBaka 
It's going to be a couple of weeks at least before I can get onto this.
RL issues.

**Comment by SpiralBaka** [comment]
Thank you for your response. I'll be waiting patiently for your return.

**Comment by dteviot** [comment]
@SpiralBaka 

If you don't want the images inserted, on "Advanced Options", tick "Skip Images".
![image](https://user-images.githubusercontent.com/5157081/188360055-fcb1c247-c537-42ba-ba7c-f702d800583e.png)

Updated WebToEpub to remove &lt;blockquote&gt; elements.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 79 minutes work.  (Spent an hour going down the wrong rabbit hole initially.)

**Comment by SpiralBaka** [comment]
thank you.

**Comment by dteviot** [comment]
@SpiralBaka 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
