### ISSUE TITLE
Remove duplicate images from image gallery at start of Web Page

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#8]
Many Baka-Tsuki web pages have an image gallery at the start of the web page.
Some of these images also appear in the story text.
Provide an option to have the ePUB generator remove any images in the gallery that also appear in the text.

**Suggested implementation notes**.
1. - BakaTsukiImageCollector.prototype.findImagesUsedInDocument() is used to do an initial scan of the document, collecting information on each image.  This scan should be updated to check if image element is nested inside a list element of class gallerybox.  If image element is not nested inside gallerybox, add flag to imageInfo that it appears outside gallery. 
2. - Later on BakaTsukiParser.prototype.processImages() is used to replace the image elements.  This should be updated to check that if element is nested inside a gallery box, and the image is also not in a gallery box, then remove the element.

(Obviously, the above processing needs to be done BEFORE the images in the gallerybox are “flattened” to be outside the box.)

**Comment by belldandu** [comment]
Finished in #10

**Comment by dteviot** [comment]
Implemented in release 0.0.0.4
