### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by TheOne320** [dteviot/WebToEpub#80]
Maybe you guys could contact the other and work together or something similar?
https://github.com/Mitch528/WebNovelConverter

**Comment by Evolution0** [comment]
They are written in entirely different languages so I doubt it.

**Comment by dteviot** [comment]
@TheOne320
Interesting.

This is closer.
https://github.com/haroldtreen/epub-press-clients

**Comment by dteviot** [comment]
Last commit to WebNovelConverter was 6 months ago, and Mitch528 did not respond to my attempts to contact him.
