### ISSUE TITLE
unable to download novels from https://www.royalroad.com/

### ISSUE THREAD

**Issue by mhussaincov93** [dteviot/WebToEpub#802]
when trying to download this novel via this url, I get error.
https://www.royalroad.com/fiction/18225/molting-the-mortal-coil
the error message is as folows.

--
Error: Could not find content element for web page 'https://www.royalroad.com/fiction/18225/molting-the-mortal-coil'.     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:500:23     at async Promise.all (index 0)     at async RoyalRoadParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:470:17)
running on linux using google-chrome latest.
stepps to repro
1.
go to
https://www.royalroad.com/fiction/18225/molting-the-mortal-coil
2.
press pack epub.
3.
an error message is displayed.
Majid

**Comment by dteviot** [comment]
@mhussaincov93 
Sorry, I'm unable to reproduce.
What browser are you using?

**Comment by mhussaincov93** [comment]
hi, version is
Chromium 105.0.5195.102 Arch Linux
using web to epub via the chrome store.
Majid

**Comment by mhussaincov93** [comment]
hi,
an update
running the extention from your google drive link functions.
with the site, so will close this issue as fixed.
sorry for the false issue,
it'll teach me to try all avanews before makeing issues.
just one thing,
will the chrome extention auto update I ask because I am using the unpacked extention.
Majid

**Comment by dteviot** [comment]
@mhussaincov93 
Yes, the chrome version will autoupdate when I update the version in the chrome store and Google have approved it.
However, I'll notify you when I've uploaded to the store.
Hopefully will update store in a week or two.
(I've had RL issues, and seem to have a large backlog of requests to deal with.)

**Comment by dteviot** [comment]
Reopen, so I know to notify you when store is updated.

**Comment by mhussaincov93** [comment]
thank you so much sir,
you are a treasure.

**Comment by dteviot** [comment]
@mhussaincov93 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
