### ISSUE TITLE
Please add site https://noblemtl.com/

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#803]
ToC example: https://noblemtl.com/series/the-main-heroines-are-trying-to-kill-me/

Would really appreciate it if you add support for this site.

**Comment by dteviot** [comment]
@Iadders 
Duplicate of https://github.com/dteviot/WebToEpub/issues/793
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by Iadders** [comment]
Works perfectly, thank you.

**Comment by dteviot** [comment]
@Iadders 
Reopen, so I know to notify you when Chrome and Firefox stores are updated.
