### ISSUE TITLE
Please add site https://booktoki152.com

### ISSUE THREAD

**Issue by courli79** [dteviot/WebToEpub#805]
### What settings did you use?  The default parser works with :
* URL of first chapter : https://booktoki152.com/novel/566955?sst=as_good&sod=desc&yoil=%EC%99%84%EA%B2%B0&spage=1
* CSS selector for element holding content to put into EPUB : div.view-padding
* CSS selector for element holding Title of Chapter : div.toon-title
* CSS selector for element(s) to remove : div.padding

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
yes I tried, I attach the file. But I haven't been able to add it back to the temporary Firefox add-on so I don't know if it works.

[Booktoki152Parser.zip](https://github.com/dteviot/WebToEpub/files/9484325/Booktoki152Parser.zip)

**Comment by dteviot** [comment]
@courli79 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with first chapter of
* https://booktoki152.com/novel/108576?sst=as_good&sod=desc&yoil=%EC%99%84%EA%B2%B0

For my notes: 32 minutes work

**Comment by courli79** [comment]
Hello, thank you for your work! I tested the parser, it works at first but at some point the connection of the web page is cut and displays "403 Forbidden" if we wait a bit for the web page to come back. So I don't have all the chapters of the novel, only the first 30 to 50 before the web page was cut. Has this happened to you too?

**Comment by dteviot** [comment]
@courli79 
It sounds like the site is placing limits on how much/quickly you can download.
You could try setting the Advanced Options to reduce the download rate.

**Comment by courli79** [comment]
Yes, by setting the delay per chapter to 3 secs/chapter, the download of all chapters works. Tested with a novel of 348ch OK

**Comment by courli79** [comment]
Thank you!

**Comment by dteviot** [comment]
@courli79 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
