### ISSUE TITLE
Please add site https://novelsemperor.com/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#807]
Please add site https://novelsemperor.com/

**Comment by dteviot** [comment]
@Finks82 

Seems to be same layout as noblemtl.com

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with
* https://novelsemperor.com/series/xuanhuan-please-dont-take-my-chance-again/ chapter 1
* https://novelsemperor.com/series/for-making-anime-all-stars-have-become-my-cos/ chapter 1

For my notes: 20 minutes work

**Comment by dteviot** [comment]
@Finks82 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
