### ISSUE TITLE
Develop Android and iOS apps using nativescript

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#81]
So for those that dont know what nativescript is then feast your eyes. https://www.nativescript.org

I'm hoping to target android of versions 4.4+.
As for iOS not my expertise so up to you guys.

Main reason is because currently Server mode is still in development and will require things which could become problematic in the future or may be depricated due to security reasons. 

Yes this is DEFINETLY an alternative to Server Mode.

@dteviot

**Comment by dteviot** [comment]
@belldandu
I've done native Android development.  It's not significantly worse than any other Java development on Windows.
My experience with iOS is... Well, let's just say my employer's official opinion on Apple is "They're the most amazing, brilliant, wonderful company in the world" and I'm required to have this opinion as well.

**Comment by belldandu** [comment]
Haha yeah but @dteviot id prefer it if we used nativescript, because java is no longer required for app devlopement and we would have to rewrite less stuff using native script then we would if we switched to straight up java or c++.
That and i have no idea what language is native for iOS.

**Comment by dteviot** [comment]
@belldandu
Sorry, I wasn't very clear.  I meant I expect the Android development to go OK.

**Comment by belldandu** [comment]
Ah ok xD

**Comment by AzSiAz** [comment]
There is also React Native as an alternative to NS

**Comment by Jaykoerner** [comment]
can't this just be a close to direct port in cordova? i'm pretty sure you can tell it to strait up ignore XSS protection and source origin rules, meaning you could just get away with javascript and iframes  and it should work, but idk havent tried anything like that myself in it.

**Comment by dteviot** [comment]
Acording to https://github.com/dteviot/WebToEpub/issues/151
Extension works on Firefox for Android version 57.0.1.
So, Android devices are now supported.  
And I don't want anything to do with Apple devices.
