### ISSUE TITLE
Please add site https://novelr18.com/

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#814]
Hello

Is it possible to add this website : https://novelr18.com/

Thanks you very much for all your work !

**Comment by dteviot** [comment]
@Flwk
It seems to work.  I tried: https://novelr18.com/manga/the-boy-raised-in-a-dark-elf-village/
Please describe problem in more detail.

**Comment by dteviot** [comment]
Closing, due to lack of response
