### ISSUE TITLE
Please add site https://novelhi.com

### ISSUE THREAD

**Issue by rvindo** [dteviot/WebToEpub#815]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novelhi.com/s/index/A-Record-of-a-Mortals-Journey-to-Immortality-%E2%80%93-Immortal-World-Arc

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
No, the default parser page didn't show up.

### What settings did you use?  What didn't work?
* URL of first chapter: https://novelhi.com/s/A-Record-of-a-Mortals-Journey-to-Immortality-%E2%80%93-Immortal-World-Arc/1
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
I'm sorry, I don't have any developer skills.

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I'm sorry, I don't have friends.

**Comment by dteviot** [comment]
@rvindo 
Already works, just need to go use the right URL https://novelhi.com/s/A-Record-of-a-Mortals-Journey-to-Immortality-%E2%80%93-Immortal-World-Arc (hint, NOT the index).

**Comment by budikesuma** [comment]
@dteviot 

Still not working with that link above...
Both desktop or mobile...

**Comment by dteviot** [comment]
@budikesuma 
Seems to be some sort of intermittent problem with chapters 3, 4, and 8 of that story.
Unfortunately, I've not been able to figure out what it is.  (I'm guessing some sort of captcha page, which it's now not showing to me.)
Anyway, under advanced options set "Skip chapters that return HTTP 404 error", and WebToEpub will continue on when it hits one of these chapters.  And should give you a list of the ones it had problems with.
So, you'll get an epub with nearly all the chapters.
