### ISSUE TITLE
Baka-Tsuki parsing

### ISSUE THREAD

**Issue by Tenome** [dteviot/WebToEpub#816]
I noticed that when loading a Baka-Tsuki page, it doesn't show the option to select which chapters to parse. Is this intentional? It still works as intended, just wondering. I only get the option to choose the cover image.

https://puu.sh/JlNdV/fdd0a2b315.png

Example URL:
https://www.baka-tsuki.org/project/index.php?title=Kami-sama_no_Inai_Nichiyoubi

**Comment by dteviot** [comment]
@Tenome 
> it doesn't show the option to select which chapters to parse. Is this intentional?
Yes.  I like getting complete volumes in an epub.  Why would I only want some chapters?

The Baka-Tsuki parsing is rather old.  And not helped by fact that the format isn't consistent between books.
Anyway, for Baka-Tsuki, you'll get better results by opening a volume in the browser, e.g. https://www.baka-tsuki.org/project/index.php?title=Kami-sama_no_Inai_Nichiyoubi:Volume1 and then opening WebToEpub.  (i.e. do it on a per volume basis.)
