### ISSUE TITLE
Please remove the hidden text 

### ISSUE THREAD

**Issue by seizue** [dteviot/WebToEpub#820]
There is a hidden text in **Noblemtl.com** epub. It kind of annoying to read 
specially I encourter it in a particular novel. 

It only visible when it was pack as an epub but in the website it's not visible. 
Here's the novel I'm talking about. It's in chapter 515  toward at the end of the chapter 
https://noblemtl.com/taming-the-villainesses-chapter-515/

While here is in the epub. 
It look like this. 

![IMG_20220921_074958](https://user-images.githubusercontent.com/25120376/191385228-77b78f79-af02-426f-ae8c-257fa94cef0f.jpg)

**Comment by seizue** [comment]
My bad, the hidden text only appear when I'm using moon+reader. In lithium it's not visible. 
Although it's moon reader fault hopefully you still find a way to be make them hidden or invisible. 🙏

**Comment by budikesuma** [comment]
> My bad, the hidden text only appear when I'm using moon+reader. In lithium it's not visible. Although it's moon reader fault hopefully you still find a way to be make them hidden or invisible. 🙏
.
.
@dteviot 

The issue of text being hidden with the `opacity:0` technique can be solved by removing this paragraph element: 
`<p style="position:fixed;opacity:0;">`
.
.
@seizue 

Lithium can't display elements that are not meant to be seen in epub, but it also can't handle the slightest html parsing error in epub.

Moon Reader, on the other hand, can easily handle all html parsing errors in the epub, and as a result it also displays all elements included in the epub package.

But I still recommend using Moon Reader instead of Lithium. Because Moon Reader's reliability has been proven to be robust, as well as more features than other ereaders.

**Comment by seizue** [comment]
Oh, I have no idea, I thought moon reader is the problem. 😅 Thank you for the explanation. Yes, moon reader have been my primary when using to read my files. I just use lithium for this particular novel

**Comment by dteviot** [comment]
@seizue 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://noblemtl.com/series/taming-the-villainessess/, chapters 1, 515, 514

For my notes: 29 minutes work

**Comment by seizue** [comment]
Thank you it works. I can finally read it peacefully ♥️🙏

**Comment by dteviot** [comment]
@seizue, @budikesuma 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
