### ISSUE TITLE
How to fix this issue please?

### ISSUE THREAD

**Issue by itsgraxiabibi** [dteviot/WebToEpub#821]
Hello, this is the error showing when I tried to use the webtoepub extension. I never had a problem with this site before (I was able to download them successfully) so this error is new.

Is there something i should do if it shows an error like this? Thank you!

Error: Fetch of URL 'https://api-pagestage.kakao.com/users/login' failed with network error 401. at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:32:25) at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:166:45) at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:160:31

**Comment by dteviot** [comment]
@itsgraxiabibi 
401 is an "access denied" from the site.
At a guess, you may need to log into the site before you can use WebToEpub.

**Comment by itsgraxiabibi** [comment]
Hi! Actually, I'm already signed in. My second thought was that I need to "open" or atleast "read" the chapters in order for it to work but it's still not downloading like before.



> @itsgraxiabibi
> 401 is an "access denied" from the site.
> At a guess, you may need to log into the site before you can use WebToEpub.

**Comment by dteviot** [comment]
@itsgraxiabibi 
What's the URL you're using?

**Comment by itsgraxiabibi** [comment]
> @itsgraxiabibi
> What's the URL you're using?

I tried both scenario where I logged in first from page.kakao.com and open the pagestage site

and where I logged out and logged in directly at the pagestage site but it's still the same error. This never happened before so Im at lost.

Here ya go: https://pagestage.kakao.com/rofan

**Comment by dteviot** [comment]
@itsgraxiabibi 
OK, I've had a look at this.
Looks like there's been a change to the site.
I didn't write the parser for this site,  So, it might be worth asking @Synteresis to have a look at this.
Unfortunately, it's not a simple site (it's using javascript to fetch content) and it's in Korean (I think) which I don't know.  Which makes it harder.

**Comment by dteviot** [comment]
@itsgraxiabibi 
Fix was provided by courli79, See: https://github.com/dteviot/WebToEpub/issues/827

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by itsgraxiabibi** [comment]
> @itsgraxiabibi Fix was provided by courli79, See: #827
> 
> Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Thank you so much! Much love to everyone who helped fix this issue. It's working now

![image](https://user-images.githubusercontent.com/86084990/195438369-19d843d4-0b46-47e0-8f15-f169a902f1b6.png)

**Comment by dteviot** [comment]
@itsgraxiabibi 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
