### ISSUE TITLE
add support for portuguese novels websites

### ISSUE THREAD

**Issue by kristianmsf** [dteviot/WebToEpub#824]
Hello, can you please add support to portuguese novels websites
https://saikaiscan.com.br/home

Thank You

**Comment by dteviot** [comment]
@kristianmsf 
To make progress tracking easier, please only have one web site per issue.

**Comment by kristianmsf** [comment]
Edited. Thank you

**Comment by dteviot** [comment]
@kristianmsf 
Sorry, that site requires disabling my add blocker, and I'm not prepared to do that.
Feel free to create issue for the other site you wanted.
