### ISSUE TITLE
Please add https://booktoki156.com/novel/1664649/%EC%A0%84%EC%A7%80%EC%A0%81-%EB%8F%85%EC%9E%90-%EC%8B%9C%EC%A0%90

### ISSUE THREAD

**Issue by eulaveen** [dteviot/WebToEpub#825]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

https://booktoki156.com/novel/1664649/%EC%A0%84%EC%A7%80%EC%A0%81-%EB%8F%85%EC%9E%90-%EC%8B%9C%EC%A0%90

### Did you try using the Default Parser for the site?  If not, why not?

Yes I tried 

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB. 
☝️ Couldn't get it right 
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you tried writing a parser, and it doesn't work.  Attach the parser here.

I don't have any knowledge but I did try 
* URL of first chapter
https://booktoki156.com/novel/1666110?sst=as_view&sod=desc&spage=1
* CSS selector for element holding content to put into EPUB 
#novel_content > div.l7b36f53a5a
#novel_content
#content_wrapper > div.content > div > div.view-wrap.view-mobile.font-14 > section > article

I tried with all the lines (??) Above each one individually but it doesn't seem to work 
here is a screenshot
![Screenshot_2022-09-30-18-35-26-231_com kiwibrowser browser](https://user-images.githubusercontent.com/114764978/193326406-f0d2ca20-a23e-4e0e-b0e6-582eff20e61e.jpg)

The site is in korean which can make it harder but do try to take a look if it too much work then it's fine but I hoped that maybe it because I don't know what I was doing and the fix is easy 
Than you anyway

**Comment by dteviot** [comment]
@eulaveen 

This one's easy.  Looks like site https://booktoki152.com/ changed its name to https://booktoki156.com/

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://booktoki156.com/novel/1664649/%EC%A0%84%EC%A7%80%EC%A0%81-%EB%8F%85%EC%9E%90-%EC%8B%9C%EC%A0%90

For my notes: 10 minutes work  (mostly paperwork)

**Comment by eulaveen** [comment]
@dteviot Thank you so much it works nicely 

Note 
it did stop after 57 chapter not because of the extension but the site itself I got 403 forbidden message when I rechecked it so I assume I should download in bulks of 50 chapter each so the site doesn't detect it or is there a better way around it ?

**Comment by dteviot** [comment]
@eulaveen 
It depends.  
You can use the advanced settings to reduce the collection rate.  Which might help.
If you try opening the 57th chapter normally in browser, what happens?  Do you get a useful error message?

**Comment by eulaveen** [comment]
@dteviot 
I changed the delay between each chapter to 5 seconds and it worked
Truly thank you for taking the time to help and for making such useful extension

**Comment by dteviot** [comment]
@eulaveen 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
