### ISSUE TITLE
Can u please add the website : https://lightnovelfr.com/

### ISSUE THREAD

**Issue by marodev1** [dteviot/WebToEpub#826]
Hello,

Can u please add this website : https://lightnovelfr.com/series/classroom-of-the-elite/ ?

Thanks a lot in advance :)

**Comment by dteviot** [comment]
@marodev1 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with: https://lightnovelfr.com/series/classroom-of-the-elite/ , prolog 0 + chapter 1

For my notes: 42 minutes work

**Comment by marodev1** [comment]
thanks a lot man

**Comment by dteviot** [comment]
@marodev1 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
