### ISSUE TITLE
Please add site https://reaperscans.com/novels (was previously supported/available before the sites re-design)

### ISSUE THREAD

**Issue by Leifman35** [dteviot/WebToEpub#829]
So i figured i'd post and ask... previously repaerscans had a design/UI that using web2epub worked fine and was quite easy and straightforward. now after the new website design of that site it no longer works. was wondering if now it falls under the category of 'problematic websites' (something like the new wuxiaworld design?) or if it's possible to fix.

I know absolutely nothing about that .CSS or w/e so figured i'd ask people that do know quite a lot about it :D

So yeah, ill appreciate some feedback, even if it's a 'yep it's not possible anymore' just to know where web2epub stands with the new re-design of reaperscans novel section

**Comment by dteviot** [comment]
@Leifman35
At first glance, it looks doable.
The only complication is how to get the URLs for all the Table of Content pages.
Specifically, what happens when there are a very large number of chapters?  (It puts a button for each ToC page at the bottom of the ToC.  What happens when they don't fit?)
I'll probably look at it this weekend, when I have a large enough block of spare time.

**Comment by Leifman35** [comment]
@dteviot Much appreciated! I know there are 'alternatives' like using one of the dozen of sites that scrap from reaperscans (and other websites out there) that are supported by web2epub, like for example my personal favorite 'readwn.com' that does reaperscans specifically, but i just absolutely love using web2epub so much so that i first had to ask :D as i mentioned, before the website updated it worked flawlessly with web2epub and i got used to it :)

So thanks again, and no rush obviously.. if and when you have the time i'll appreciate if you check it out if it is indeed doable!

**Comment by dteviot** [comment]
@Leifman35 
Unfortunately, it looks like they're doing something funny for some ToC pages.
Some of these pages don't have any chapters, instead, they make JSON calls to get the chapters.  And unfortunately, the calls are INSANELY complicated.  Seriously, they're far more complicated than they possibly need to be.  I suspect someone has copy/pasted code intended for a different purpose for the job. Anyway, trying to figure them out will take much longer than I'm willing to spend.

The best I'm willing to do is get the chapters that are on the currently shown page.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know what you think.

Tested with https://reaperscans.com/novels/5172-the-divine-hunter

For my notes: 82 minutes

**Comment by Leifman35** [comment]
@dteviot oh wow, sneaky reaperscans... I'm sorry it took longer that you thought it would and i appreciate the end-result regardless! Thank you. it's fine, there are alternatives as i mentioned but being that 'loyal' and used to using your wonderful addon, i simply had to ask/make sure about it first. I sorta had a feeling that it might be similar to 'wuxiaworld' 'eque with it's re-design, but lately i noticed that wuxiaworld works fine with 'lightnovel crawler' so i didn't know what to think about reaperscans really.

Anyways yet again, Thanks a lot! i appreciate being able to grab the 'currently shown page' chapters with web2epub, and appreciate your time and effort!

**Comment by dteviot** [comment]
@Leifman35 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
