### ISSUE TITLE
CSS update

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#83]
Some CSS update.
I was unsure which branch to make a pull request to.
https://github.com/dteviot/WebToEpub/compare/master...toshiya44:master

Here's the bit of CSS I wanted to suggest.
```
body {
  margin: 2%;
}

/*Breaks extremely long words, screams, wails etc to fit viewer window.*/
p {
  overflow-wrap: break-word;
}

/*Prevent texts inside mutliple definition list tags going outside viewer window.
Example https://www.baka-tsuki.org/project/index.php?title=The_Unexplored_Summon_Blood_Sign:Volume2_Opening2
It looks okay in a browser but in devices with small screen, it's almost unreadable.*/
dd, dt, dl {
  padding: 0;
  margin: 0;
}
```

I've been using them on my epubs for a while and so far they're working well.
PS: I'm not sure if the `body` margin is necessary.

**Comment by dteviot** [comment]
@toshiya44 
Thanks.  All going well I'll add this tonight.

>I was unsure which branch to make a pull request to.

Work is normally done on the Experimental branch. https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode
When stable, this is merged into the Sonako branch for a release.
Then Sonako is merged into Master once it's been around for a while.

i.e. I'm using this model.  http://nvie.com/posts/a-successful-git-branching-model/
Where ExperimentalTabMode corresponds to "develop" and Sonako is Release Branches (and Master is Master.)
Side note, I should probably rename the branches.
