### ISSUE TITLE
Please add site https://www.dreame.com/ 

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#833]
Please add dreame to convert to epub, thank you so much!

**Comment by dteviot** [comment]
@AngelBurn 
Not easy.  Site is blocking use of Chrome DevTools, so I can't see the network calls it's making.
I could probably try using Fiddler to figure it out, but that's too much like work.

**Comment by AngelBurn** [comment]
Oh i understand thank u so much

**Comment by dteviot** [comment]
@AngelBurn 
I should have been more clear.  The answer is "Won't do.  Too difficult."
