### ISSUE TITLE
Vivaldi Crash

### ISSUE THREAD

**Issue by Saladitas** [dteviot/WebToEpub#834]
**Describe the bug**
Brower crashes when I try to use the extension. 

**To Reproduce**
1. Click on extension
2. The extension opens a new tab
3. Immediately crashes browser 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi 
 - Version 5.5.2805.38

**Additional context**
I was trying this extension out on RoyalRoad, Don't know if this happens on other supported sites.
From other reviews I've seen It might be a problem for Vivildi users only.

**Comment by dteviot** [comment]
@Saladitas 

>From other reviews I've seen It might be a problem for Vivildi users only.

I just tried the Chrome version with Royal Road, and had no problems.
So, you could try contacting the Vivaldi team.  I have no time or interest in trying to get WebToEpub to work with Vivaldi.
