### ISSUE TITLE
Please add site https://m.goodnovel.com/

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#835]

**Comment by dteviot** [comment]
@AngelBurn 
Looks like it might be doable.  However, it's one of the time consuming ones, that requires making REST calls to get the chapter content, and then converting the JSON into HTML.
So, it's going to be a while before I get onto this.

For my notes:
Looks like the call to get a chapter is: POST https://www.goodnovel.com/hwyc/chapter/detail
with a payload of 
```json
{
    bookId: "31000242907", 
    chapterId: "2101091"
}
```
Looks like bookId can be obtained from div.bookinfo.  To get chapters, 
May be able to do post https://www.goodnovel.com/hwyc/chapter/list/preview
with a payload of 

```json
{
    bookId:  "31000242907"
    pageNo:  1
    pageSize:  10
    rid: ""
}
```

**Comment by dteviot** [comment]
@AngelBurn 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with:
https://www.goodnovel.com/book_info/31000309520/Werewolf/The-Pack-s-Secret-Keeper, chapters 1 to 3
https://www.goodnovel.com/book_info/31000357192/Romance/My-Bully-s-Love, chaptes 1 to 5

Notes, 
1. Chapters that are locked have no content.  e.g. My-Bully-s-Love, chapter 5.  (I don't know how you unlock chapters,  It may work for you if you're logged in and the chapter is unlocked for you, but I didn't try.)
2. This works for www.goodnovel.com, which is the desktop version of m.goodnovel.com.  (m.goodnovel.com is the mobile version of site.)  So, if you want to use WebToEpub with a mobile browser, make both the novel page and extension page desktop mode.

For my notes: 100 minutes

**Comment by dteviot** [comment]
@AngelBurn 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
