### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by shonetypto** [dteviot/WebToEpub#836]
I am reading on my phone a lot more lately and have been looking into code for iOS devices. Theres an app called scriptable that allows you to run java and other code on ios devices and other apps. 

I am playing around with it now since I know next to nothing about code, but I was wondering if you had a chance to look into supporting ios devices? If you're not able to do you mind if I continue to play around with your code to see if i can get it running on my phone?

**Comment by dteviot** [comment]
@shonetypto 
I have no intention of supporting iOS.  Just trying to support Chrome and Firefox takes too much of my spare time as it is.
Just in case you didn't realize it, WebToEpub is open source, so you are most welcome to take the code and try to do whatever you like with it.  Code base is: https://github.com/dteviot/WebToEpub

**Comment by shonetypto** [comment]
Thank you! I found a few work arounds but your packing and parsers are the best out of all the other web to epub extensions and sites. :)
