### ISSUE TITLE
Change "royalroadl.com" to "royalroad.com" in addon descriptions and readme.md

### ISSUE THREAD

**Issue by xypha** [dteviot/WebToEpub#838]
RoyalRoad has changed it's domain from "royalroadl.com" to "royalroad.com".
Addon descriptions require change to reflect this

**Comment by dteviot** [comment]
@xypha
>RoyalRoad has changed it's domain from "royalroadl.com" to "royalroad.com".
Addon descriptions and readme.md require change to reflect this

Which readme.md are you referring to?

**Comment by xypha** [comment]
i was talking about this one - [Link](https://github.com/dteviot/WebToEpub/blob/master/readme.md). I see that it's already fixed. 👍

**Comment by dteviot** [comment]
@xypha 
1. Description in Firefox store updated.
2. Request to update Chrome store submitted.  Now need to wait for approval.
