### ISSUE TITLE
royalroadl issue

### ISSUE THREAD

**Issue by Nsixtyfour** [dteviot/WebToEpub#84]
Chapters on royalroadl.com that start with a poll cause WebToEpub to not grab the chapter text. Opening the epub does show the html file for the chapter, but it only contains the chapter title and no body text. Examples are chapter 39 of Forgotten Conqueror https://royalroadl.com/fiction/chapter/16150 or many chapters of True World Online https://royalroadl.com/fiction/4989 ch 5, 7, 9...

**Comment by toshiya44** [comment]
> True World Online https://royalroadl.com/fiction/4989 ch 5, 7, 9...

Yup, I can reproduce this in version 0.0.0.23 on Firefox 52

**Comment by dteviot** [comment]
@Nsixtyfour 
My apologies.  Have added fix to experimental branch here: https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode  If you'd be kind enough to give it a test and confirm the fix works and doesn't break any other stories please,  Note, you'll need to install from source.  Instructions are given in the readme on above link.

**Comment by Nsixtyfour** [comment]
That worked, thank you for the quick fix. I tested it on 3 different stories that previously had that problem and they all worked with the new version. Also spot checked to make sure it looked right.

Side note, your instructions for installing from source for chrome didn't quite make sense to me at first. It says download the source to zip, extract it and put that folder into a plugin folder (so you end up with \plugin\WebToEpub-ExperimentalTabMode\...). The problem is when trying to install that extracted folder in chrome it complains about manifest not found. I noticed in the extracted WebToEpub-ExperimentalTabMode it had a plugin folder itself and saw it had the manifest in there. It also had a jszip folder within its plugin folder so I created the WebToEpub-ExperimentalTabMode\plugin\jszip\dist and put the jszip.min.js in there and told chrome to use the WebToEpub-ExperimentalTabMode\plugin as the extension folder and that worked.

**Comment by dteviot** [comment]
@Nsixtyfour 
Here's what I propose for updated instructions.  Any improvements you can suggest would be appreciated.

1. Download the extension. Go to https://github.com/dteviot/WebToEpub and click on the "Download Zip" button.
2. Unpack zip file and move the "plugin" directory to the location you want to keep it.
3. In the "plugin" directory from the previous step there is a "jszip" directory.  Create a "dist" directory inside this "jszip" directory.
4. Download jszip library v3.0.0 from https://github.com/Stuk/jszip
5. Extract jszip.min.js from the jszip library and copy to the "dist" directory you created in step 3.
6. Open Chrome and type "chrome://extensions" into the browser.
7. Make sure "Developer Mode" at the top of the page is checked.
8. Press the "Load unpacked extension.." button and browse to the "plugin" directory from step 2.

**Comment by Nsixtyfour** [comment]
That makes more sense I think.
