### ISSUE TITLE
Extention stopped working...

### ISSUE THREAD

**Issue by Keitagit-kun** [dteviot/WebToEpub#840]
not bug report but...

after loading new dev version of WebToEpub it stopped working - WebToEpub button is gray and extention display errors:

'action' requires canary channel or newer, but this is the stable channel.
'host_permissions' requires dev channel or newer, but this is the stable channel.
The maximum currently-supported manifest version is 2, but this is 3. Certain features may not work as expected.
Permission 'scripting' is unknown or URL pattern is malformed.

{"manifest_version":3,"name":"WebToEpub","version":"0.0.0.151","default_locale":"en","icons":{"128":"book128.png"},"permissions":["downloads","scripting"],"host_permissions":["<all_urls>"],"action":{"default_title":"","default_icon":"book128.png","default_popup":"popup.html"},"incognito":"split","minimum_chrome_version":"80"}

WebToEpub 0.0.0.151
hkimdjmogmdpjfekookfbgdiampfabae

My chrome_version is 86.0.4240.198, I cannot update it. What I can do to keep use new WebToEpub 0.0.0.151+ parsers? Will copying "js" folder to old (150) version work?

**Comment by gamebeaker** [comment]
Hi you can find the reason in this issue #819. Short version: manifest v2 is end of life on chrome in a few months so the version got updated to manifest v3 your old chrome version 86 doesn't support manifest v3. Why can't you update your Chrome? Possible solution: Use firefox :)
Or build WebToEpub yourself and check that the manifest version is 2 not 3 in the file manifest.json.

**Comment by gamebeaker** [comment]
@dteviot maybe change in manifest.json "minimum_chrome_version": "80" to "minimum_chrome_version": "88" because with version 88 chrome supported manifest version 3 (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version).

**Comment by dteviot** [comment]
@gamebeaker 
Thanks.  Updated.
