### ISSUE TITLE
Please help generate the Chapter Titles in the EPUB too for the site [https://travistranslations.com/]

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#844]
Hello, apologies for the inconvenience. This isn't a site request, but I wasn't sure which issue this fell under. WebToEpub firstly does generate epubs for this website **[https://travistranslations.com/]** very well. But for some reason, it does not generate the **Chapter Titles** under the horizontal line in the EPUB output itself. Would it be possible to somehow make WebToEpub also generate the **Chapter Titles** into its respective .xhtml file too, please? My explanation is rather poor, so hopefully the below images will serve as a useful reference. 

When viewing the chapter in Chrome, the chapter title is shown UNDER the horizontal line (<hr />). I've highlighted in red where it is visible.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/55352222/198032990-ec050f5b-4d2d-47d2-a77e-e4df9a36610e.png">

But in the EPUB output that WebToEpub has generated, everything does appear as it should, except only the chapter title underneath the horizontal line.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/55352222/198033322-f9f8d529-55ac-4147-ab83-7e5860d69c95.png">

Thank you very much for your help as always!

**Comment by dteviot** [comment]
@vanessabluellie 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note.  Due to way WebToEpub works, I've had to put both the "Chapter #" and the other text into single chapter line.

For my notes: 10 minutes work

**Comment by vanessabluellie** [comment]
I actually prefer the chapter title being on the same line much more!! Thank you so much!!! :D

**Comment by Tenome** [comment]
> @vanessabluellie
> 
> Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
> 
> Note. Due to way WebToEpub works, I've had to put both the "Chapter #" and the other text into single chapter line.
> 
> Tested with:
> 
>     * https://travistranslations.com/novel/60794/a-heroic-tale-about-starting-with-a-personal-relations-cheat-ability-and-letting-others-do-the-job
> 
> 
> For my notes: 10 minutes work

I tried that URL just now and it's not grabbing any of the images.

**Comment by dteviot** [comment]
@vanessabluellie, @Tenome 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
