### ISSUE TITLE
Please add site [https://www.wuxiaworld.eu/]

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#846]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://www.wuxiaworld.eu/novel/generals-gown**

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

**Yes, but WebToEpub didn't register any of the chapter links.**

Thank you very much!!! :D

**Comment by dteviot** [comment]
@vanessabluellie 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, you don't need to select the chapters before opening WebToEpub.  (If you do, most of the description will be missing.)

Tested with
* https://www.wuxiaworld.eu/novel/generals-gown, chapter 1, 10

For my notes: 67 minutes work

**Comment by vanessabluellie** [comment]
Thank you so much!!!! It works perfectly!!! :D

**Comment by dteviot** [comment]
@vanessabluellie 

Note, site changed name to Wuxia.click

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
