### ISSUE TITLE
Please update site https://www.69shu.com/

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#848]
![Screenshot_20221030-232440](https://user-images.githubusercontent.com/87926179/198886852-49a842a4-e228-4d6b-aba9-d02900134ce0.jpg)
also look like this if using default parser
![Screenshot_20221030-232010](https://user-images.githubusercontent.com/87926179/198886921-07b5f0d5-8620-43f3-afe4-22cd968992f6.jpg)

**Comment by dteviot** [comment]
@Dlordload 
It's working for me.  Tested with URL https://www.69shu.com/txt/41121.htm, chapters 1 to 4
It may be because site is returning mobile mode.

For my notes: 10 minutes work

**Comment by Dlordload** [comment]
chrome and kiwi returns this
and I only just now knew that firefox doesn't have this problem

**Comment by dteviot** [comment]
@Dlordload 
For my records, what URL was giving the problem?

**Comment by Dlordload** [comment]
@dteviot 
the catalog page full chapters page
https://www.69shu.com/43348/
