### ISSUE TITLE
Please add site www.inkitt.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#850]

**Comment by dteviot** [comment]
@AngelBurn 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with
* https://www.inkitt.com/stories/scifi/848813
* https://www.inkitt.com/stories/fantasy/433194

For my notes: 77 minutes work

**Comment by dteviot** [comment]
@AngelBurn 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by AngelBurn** [comment]
Hi i tried to convert but it suddenly stop only the summary has been download chapters not included

**Comment by dteviot** [comment]
@AngelBurn 
What URL were you using?

**Comment by AngelBurn** [comment]
The URL im using is the inkitt, 
![Uploading Screenshot_20230210_171039_com.kiwibrowser.browser.jpg…]()

**Comment by dteviot** [comment]
@AngelBurn 
I mean, what's the exact URL of the story that did not work.  So that I can try it and see what's going on.
e.g. I've tested with https://www.inkitt.com/stories/scifi/848813 and it worked.  Does this one work for you?
Note, if you're using the Kiwibrowser (a mobile browser) you may need to put it into desktop mode for WebToEpub to work for some sites.  This is because some sites use a different format when they're taking to a mobile browser, and WebToEpub only knows how to do desktop format (because I don't want to do twice the work for both desktop and mobile formats.)

**Comment by AngelBurn** [comment]
Hi, i just want to inform you it works really well on my PC but when in mobile it doesnt download even if i in desktop mode, but its okay im still happy that it works on PC. Thank you!

**Comment by gamebeaker** [comment]
@AngelBurn Hi does it work if you follow this wiki entry? https://github.com/dteviot/WebToEpub/wiki#how-to-use-with-kiwi-browser-not-supported

**Comment by AngelBurn** [comment]
Nope kiwi browser doesn't work on inkitt, when im converting inkitt im using my pc bcoz it works

**Comment by gamebeaker** [comment]
@AngelBurn I tried in on my Android device and it worked. Are you sure that you set the WebToEpub tab in Desktop mode?

**Comment by AngelBurn** [comment]
In my android it doesn't work i already put it in desktop mode same with others but only inkitt cant be downloaded
Phone: Huawei Nova5t android 10
Browser: Kiwi browser


But in PC it works really well, aside on Kiwi browser may u suggest other browser on android? Chrome android has no Extensions sad.

**Comment by AngelBurn** [comment]
Omg! It works thank u so much! I dont need my pc to convert inkitt thank u!
