### ISSUE TITLE
Advanced option: "Add Information page to Epub" Generates False Error messages when used on fictions from www.RoyalRoad.com

### ISSUE THREAD

**Issue by AJM10565** [dteviot/WebToEpub#856]
**Describe the bug**
When the Advanced option: "Add Information page to Epub" is toggled on, and a user attempts to use the tool in order to create an epub from any novel on the www.royalroad.com website, the tool erroneously created an error message in the browser and in the final novel creation. To my knowledge the software is functionally pulling all the information required, but its generating a false error, as well. 

**To Reproduce**
1. Use these options:
[Options.txt](https://github.com/dteviot/WebToEpub/files/9946680/Options.txt)

Note: this seems to be broken for any fiction on www.royalroad.com, but for the reproduction steps, I'll be referencing this story:
[https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy](https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy)
1. Go to https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy
2. Click on the 
![WebToEpub](https://user-images.githubusercontent.com/32456394/200191324-c8fcde3c-5710-4742-99a1-5294565d3bc2.jpeg)
 chrome extension
3. load the options file above by clicking advanced options, scrolling to the bottom of the list, and choosing the file to load options from.
4. click "Pack Epub"
5. Wait for extension to finish
6. Note extension will reach N-1 chapters and then hang, and then the following will appear:
<img width="809" alt="Screen Shot 2022-11-06 at 1 31 45 PM" src="https://user-images.githubusercontent.com/32456394/200191174-bb7c87cd-1f6a-4cd5-b3dc-cdebcfe941aa.png">

```
Error: Could not find content element for web page 'https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:500:23
    at async Promise.all (index 0)
    at async RoyalRoadParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:470:17)
```
7. See file is downloaded. When file is opened notice the following information:
Although the file does contain information about the story, the following additional content also appears:
“This is a placeholder.  Attempt to fetch chapter from 'https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy' failed with error:  Error: Could not find content element for web page 'https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy'.”
8. This issue is fixed if you disable the advanced option: "Add Information page to Epub"
However, then the information page is not included in the novel.
**Expected behavior**
When the advanced option:
"Add Information page to Epub" is selected
The user expects the novel to contain the information at the novel's start, but not an erroneous error message saying content couldn't be fetched.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]
 - Version [0.0.0.150]

**Comment by dteviot** [comment]
@AJM10565 
I believe your are mistaken.  Based on the error message, the advance option that is causing the problem is "Add Page with Chapters to Chapters List"

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with: https://www.royalroad.com/fiction/55601/the-exalt-western-cultivation-fantasy 

For my notes; 40 minutes work

**Comment by dteviot** [comment]
@AJM10565 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
