### ISSUE TITLE
Novels from shubaow only downloads upto 33 chapters and then it will stop

### ISSUE THREAD

**Issue by Hyacinth299** [dteviot/WebToEpub#857]
A week ago, I started noticing the fact that webtoepub freezes when downloading from shubaow. It always stop at 33. I tried MTLNovel and it works just fine, but novels from shubaow(using both my laptop and in yandex app in mobile) will stop downloading. 

I tried circumventing it, maybe it can only download 32 chapters at a time 1-32 chapters if you pick 32 as last chapter will download just fine but if I try it with 33-64, it will still freeze at 1(meaning 33). 

Please look up into this issue.

**Comment by dteviot** [comment]
@Hyacinth299 
I just tried it myself.
After 33 pages, site is giving a HTTP 429 message, https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 with a retry after of 1 hour.
Basically, site is saying, "go away, I'm not going to talk to you for an hour."
So, site has a rate limit, I'm guessing of around 2 minutes per page.  You can use the advanced options on WebToEpub to adjust the rate.

For my notes: 12 minutes work

**Comment by Hyacinth299** [comment]
Thank you! I tried the 5 sec per chapter and it went past 33 chapters, here's hoping I will be able to download now

**Comment by Hyacinth299** [comment]
Update: the novel was successfully downloaded. Thank you again
