### ISSUE TITLE
Add mediawiki base parser

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#86]
So currently we have a bakatsuki parser. BakaTsuki uses mediawiki for their site. So we should probably add a mediawiki base parser and have the bakatsuki parser extend off of that.

**Comment by toshiya44** [comment]
I haven't seen any other novel hosting sites use mediawiki though. Can you post some example sites?
Although it will be useful to get Wikipedia articles as epubs.

**Comment by belldandu** [comment]
List of sites using mediawiki https://m.mediawiki.org/wiki/Sites_using_MediaWiki/en
also i put it as low priority because i haven't seen novel sites use it either. But it would be nice to have a base parser for when we do find novel sites using it.

**Comment by dteviot** [comment]
Until such time as there is a second MediaWiki site, its difficult to know what is the "Base" functionality and what is the custom "Baka-Tsuki" functionality.

@toshiya44 
That said, if the request is to support converting Wikipedia to epub, the default parser can be made to do that.  Note, it will pack one article per "chapter" in the epub.

**Comment by toshiya44** [comment]
> it will pack one article per "chapter" in the epub

That's fine. Most wikipedia pages are reasonable sized so I don't think it will be a problem.

**Comment by typhoon71** [comment]
Wikipedia to epub parser +2 (me and myself)

**Comment by dteviot** [comment]
@toshiya44 @typhoon71 
Very basic parsing of Wikipedia pages added to Experimental Tab Mode branch.  Feedback would be appreciated.
Notes.
- Fetches largest image  (and some can be really big)
- By default, only selectes current page for converting to epub.  (Although you can add additional links using "Edit Chapter URLs".)
- Does not include thumbcaption text of images.

**Comment by dteviot** [comment]
@toshiya44 @typhoon71
Also, I've added a "Manually Select Parser" list to Advanced Options.
Which may make using the default parser easier.
Feedback appreciated.

**Comment by typhoon71** [comment]
I would've liked the have the "Manually Select Parser" list visible in the main window instead that in the Advanced Options, it would have been a couple of clicks faster.

About the wikipedia, well, it's very basic; I suppose the thumbcaption text of images would be the next thing to implement. Anyway it good to see it taking shape.

**Comment by dteviot** [comment]
@typhoon71
>I would've liked the have the "Manually Select Parser" list visible in the main window instead that in the Advanced Options, it would have been a couple of clicks faster.

I think it's a feature most users are not going to use.  So put it on the advanced tab to avoid confusion.

**Comment by typhoon71** [comment]
You have a point, most users won't need it there; even more since new parsers appears quickly! ;)
Maybe there could be an option to have the advanced option open by default?

**Comment by dteviot** [comment]
@typhoon71
>Maybe there could be an option to have the advanced option open by default?

Sounds reasonable.  Please create incident.

**Comment by typhoon71** [comment]
Maybe I'm too tired but what does " Please create incident" mean?

**Comment by dteviot** [comment]
@typhoon71
> Maybe I'm too tired but what does " Please create incident" mean?

Sorry, I should have said "Please create a new issue".  This is an issue.  i.e. https://github.com/dteviot/WebToEpub/issues

**Comment by typhoon71** [comment]
Oh, got it now. It was incident = issue. Makes sense.

**Comment by toshiya44** [comment]
I get an error.

URL: https://en.wikipedia.org/wiki/Accretion_disk
Browser: Firefox Dev Edition 54.0a2 (2017-04-14) (32-bit) - Fresh profile with only WebToEpub installed. 
```
currentStyle is undefined mergeStyles@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:372:17
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:388:30
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:393:17
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:393:17
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:393:17
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:393:17
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:393:17
walk@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:393:17
findPrimaryStyleSettings@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:400:9
setStyleToDefault@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Util.js:427:23
convertRawDomToContent@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Parser.js:33:9
chapterToEpubItems@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Parser.js:116:23
chaptersToEpubItems@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Parser.js:192:28
epubItemSupplier@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/Parser.js:182:25
packEpub@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:121:49
fetchContentAndPackEpub/<@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:112:13
promise callback*fetchContentAndPackEpub@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:111:9
EventHandlerNonNull*addOnClickEventHandlers@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:362:9
window.onload@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:379:13
EventHandlerNonNull*main<@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:374:5
@moz-extension://763fbafe-6c79-4a04-8405-24297b21e61a/js/main.js:5:13
```

**Comment by dteviot** [comment]
@toshiya44 
In case you didn't realise it, the commit I made to ExperimentalTab branch 4 days ago fixes the "currentStyle is undefined" error.

**Comment by toshiya44** [comment]
Oops. I missed the notification somehow. Thanks for the fix!

I no longer get the error. The epub is created and it's pretty readable.

I noticed a few issues in the epub:
1. Internal wiki links are broken. They show up as `<a href="/wiki/other-article" title="other-article_title">otherarticle</a>`.
 The href should be `https://wikipedia.org/wiki/other-article`
(Although it's not really necessary for the epub to have these links, since they're intended to be read offline anyway. So you can just remove them too.)

2. There's some weird `.svg+xml` documents in the epub. Can't they be named as just `svg`?
 They seem to be created because of the MathML stuff Wikipedia uses to render equations. But they're not rendered nicely in the epub. Looks huge. 
(This mostly effects scientific articles)
https://cloud.githubusercontent.com/assets/20046789/25412895/18b1bbc8-29f4-11e7-81d2-2037bedd5642.png


3. There's a section in the wikipedia articles called "External Links". They don't have any useful information (unless you're using a browser and online), and the table of links render badly. Please remove the tables.

![image](https://cloud.githubusercontent.com/assets/20046789/25412756/29ed272a-29f3-11e7-84ef-89bb100cd392.png)

4. Please remove the edit links too.

![image](https://cloud.githubusercontent.com/assets/20046789/25413231/c6ffbc50-29f6-11e7-9ef1-8bdda410f676.png)

**Comment by dteviot** [comment]
@toshiya44
I've checked into ExperimentalTab branch:
- Removal of table in External Links.  (Actually all navigation tables.)
- Removal of edit links.

**Comment by dteviot** [comment]
@toshiya44
Fix for SVG issue has been checked into ExperimentalTab branch.

**Comment by toshiya44** [comment]
Thanks for the fix o/

Can you please assign a class `svgimg` to files that end with `.svg` and add this to the stylesheet?
```
img.svgimg {
  display: inline;
  min-height: 2em;
  max-height: 100%;
  max-width: 100%;
  padding: auto;
  margin: auto;
}
```
It makes most of the small SVGs equations somewhat legible and lets the larger svg images maintain their shape. 
Here's a comparison.
![untitlessd](https://cloud.githubusercontent.com/assets/20046789/25831008/093afe4e-342f-11e7-8526-66ef1df2f700.png)

**Comment by dteviot** [comment]
@toshiya44 
It's a bit more complicated than that.  Small images (&lt; 200 pixels high) are saved as  &lt;img&gt; elements.  Bigger images are saved as  svg  &lt;image&gt; elements.
And there's already styling in the stylesheet for  &lt;img&gt;  elements.
```javascript
        img {
           display: block;
           max-height: 100%;
           max-width: 100%;
           padding-bottom: 0;
           padding-left: 0;
           padding-right: 0;
           padding-top: 0;
           margin-left: auto;
           margin-right: auto;
           margin-bottom: 2%;
           margin-top: 2%;
        }
```



So, I think you could just change the existing  &lt;img&gt;  style in the sheet.  
Is there any reason why the changed style should only be applied to SVG files, rather than all files?

i.e. I'm trying to understand how the changes you suggest solve the problem.

**Comment by dteviot** [comment]
@toshiya44 
I've now checked in code that removes most of the hyperlinks that reference web pages other than the current one.

**Comment by toshiya44** [comment]
Now that I think about it again, making 2em (2x the size of font-size) the minimum height for images might not be bad. I can't think of many cases where it might break stuff.
You can just add `min-height: 2em;` inside the `img` rule.

>I've now checked in code that removes most of the hyperlinks that reference web pages other than the current one.

Just tested. It works. Thanks!


My original thoughts when I proposed the new class:
Wikipedia uses svg images for showing equations and math symbols, these svg files are very small and Wikipedia automatically resizes them when you open the page in their site. The stylesheet lets all images retain their original size, these svgs look small. Specifying a minimum height for svg images allows making these svg images readable without messing with normal images.
It is possible to handle this situation by modifying the existing generic `img` rule, but doing so might break legitimate use of small images (such as logos, using a small image to show sections and other decoration).

**Comment by dteviot** [comment]
Additional problem to fix.  
Some of the images have additional text associated with them.  
e.g.  Note the thumbcaption &lt;div&gt;
```HTML
<div class="thumb tright">
  <div class="thumbinner" style="width:252px;">
    <a href="/wiki/File:Accretion_disk.jpg" class="image">
      <img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Accretion_disk.jpg/250px-Accretion_disk.jpg" width="250" height="200" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Accretion_disk.jpg/375px-Accretion_disk.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Accretion_disk.jpg/500px-Accretion_disk.jpg 2x" data-file-width="3000" data-file-height="2400">
    </a>
    <div class="thumbcaption">
      <div class="magnify">
        <a href="/wiki/File:Accretion_disk.jpg" class="internal" title="Enlarge"></a>
      </div>
      Artist's conception of a black hole drawing matter from a nearby star, forming an accretion disk.
    </div>
  </div>
</div>
```
This text needs to be retained in the epub.  (Sample URL is https://en.wikipedia.org/wiki/Accretion_disk

Note, similar problem may exist with the &lt;figure&gt; and &lt;figcaption&gt; tags.

**Comment by dteviot** [comment]
Additional problem.
Text may have "inline" images.  i.e. the &lt;img&gt; tags are inside &lt;span&gt; or &lt;p&gt; tags.
e.g. 
```HTML
<p>where <span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi mathvariant="normal">Ω<!-- Ω --></mi>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle \Omega }</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/24b0d5ca6f381068d756f6337c08e0af9d1eeb6f" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.338ex; width:1.689ex; height:2.176ex;" alt="\Omega "></span> represents the <a href="/wiki/Angular_velocity" title="Angular velocity">angular velocity</a> of a fluid element and <span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>R</mi>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle R}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/4b0bfb3769bf24d80e15374dc37b0441e2616e33" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.338ex; width:1.774ex; height:2.176ex;" alt="R"></span> its distance to the rotation center, an accretion disk is expected to be a <a href="/wiki/Laminar_flow" title="Laminar flow">laminar flow</a>. This prevents the existence of a <a href="/wiki/Fluid_dynamics" title="Fluid dynamics">hydrodynamic</a> mechanism for angular momentum transport.</p>
```

Currently, the epub converter moves the images to before (or after) the &lt;span&gt; or &lt;p&gt; tags.  (Because the svg image tag is wrapped in a &lt;div&gt;, which isn't allowed to be enclosed in them.
So, need to make converter smarter to recognise inline images and leave them inline.

**Comment by dteviot** [comment]
@toshiya44
New commit to ExperimentalTab branch
Now putting images that are in sentences inline with text.  (e.g. Maths symbols in https://en.wikipedia.org/wiki/Accretion_disk)
It's not perfect, but I think it's a significant improvement.
(note, this requires updated default stylesheet to be applied, by clicking "Reset stylesheet to default" in Advanced Options)
I'm also setting min-height for images to 1em.  (Looks bad at 2em.)

Note, this MIGHT case issues with other web sites that have inline images.

**Comment by toshiya44** [comment]
Yup, I think it looks good too. Does this effect only Mediawiki parser or others too?

**Comment by dteviot** [comment]
@toshiya44 
>Yup, I think it looks good too. Does this effect only Mediawiki parser or others too?

All the parsers.  That's why I said it might cause issues with other web sites.
That said, I've been wanting to improve support for inline images anyway.  See https://github.com/dteviot/WebToEpub/issues/74

**Comment by dteviot** [comment]
@toshiya44

I've now added code to Experimental Tab branch to copy image's thumbcaptions.
(Note, this isn't the image descriptions from https://github.com/dteviot/WebToEpub/issues/117)

I'm not totally happy with how this may work for Baka-Tsuki stories with thumbcaptions, as IIRC those usually just echo the story text.  But I was unable to find any when I did a quick search.
Suggestions/Feedback appreciated.

**Comment by toshiya44** [comment]
Example page: https://www.baka-tsuki.org/project/index.php?title=Mondaiji-tachi_ga_isekai_kara_kuru_soudesu_yo:Volume_10_Short_Story
Thumbcaptions are pretty rare indeed.

Although the caption was included, it seems that the citation link is broken. 


Can you please add this in the css too? It will help to differentiate caption text from body text. 

```
.thumbcaption {
  display: block;
  font-size: 0.9em;
  padding-right: 5%;
  padding-left: 5%;
}
```
![with css](https://user-images.githubusercontent.com/20046789/26865080-1a83a1c2-4b29-11e7-9a6c-25a0bc48c1c4.PNG)

**Comment by dteviot** [comment]
@toshiya44 
Thanks, 

> Can you please add this in the css too

Will do.
Will see what I can do about the citation link.

**Comment by dteviot** [comment]
@toshiya44
Was much easier than expected.
CSS and citation link fixes committed to Experimental Tab branch.
Note. you need to click the "Reset stylesheet to default" button on the Advanced Options for new stylesheet to take effect.

I'm going to call this issue fixed and close.
Please re-open if you have any problems.

**Comment by toshiya44** [comment]
Alright, the citation link works now. Thanks.
