### ISSUE TITLE
Show Message rate limited if HTTP 429

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#861]
**Is your feature request related to a problem? Please describe.**
No problem just to prevent new issues like #857 being generated.

**Describe the solution you'd like**
If WebToEpub receives HTTP 429 it shouldn't just stop.
Show an Error message:
"Server limits your request speed and blocked the request. More Information: #857 
Solution: 
Advanced Options -> lower Max web pages to fetch simultaneously
and/ or
Advanced Options -> increase Manulual Throttle|Delay per Chapter"

**Comment by dteviot** [comment]
@gamebeaker 
Actually, WebToEpub doesn't "just stop".
WebToEpub will recognize a 429 response, and will back off as requested.
The problem in this case was the server requested a back off of one hour.  So it looked like WebToEpub had stopped.

That said, maybe have a message/error text box show on the form for errors/warnings?

Something like
"HTTP 429 received for URL XXXX, Server has requested WebToEpub to reduce request rate. Retrying.  If fails, see:  YYYYY"
"HTTP 500 received for URL XXXX, Intermittent error at Server end. Retrying.  If fails, see:  YYYYY"

Or maybe a table?

**Comment by dteviot** [comment]
@gamebeaker 
Thanks. Updated pretty much as you suggested.  Everything else was too much work.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes:  39 minutes work

**Comment by dteviot** [comment]
@gamebeaker 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
