### ISSUE TITLE
Can't convert, getting the same error

### ISSUE THREAD

**Issue by FluffyPrincess** [dteviot/WebToEpub#863]
![image](https://user-images.githubusercontent.com/117925860/201127506-f40ee47f-dd72-4b63-920c-881d27610be9.png)

^ I am getting the above error from an independent light novel translator

**Comment by dteviot** [comment]
@FluffyPrincess 
That's not a valid URL.  
Looks like WebToEpub hasn't picked up the correct chapter link.
Send me the URL of the Table of Contents page and I'll see what I can do.

**Comment by FluffyPrincess** [comment]
yeah you are right, they did not make a proper link. I was able to edit the URL chapters myself and i was able to convert
