### ISSUE TITLE
Please add site [https://chaleuria.com/], thank you!

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#864]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site

**https://chaleuria.com/novels/records-of-the-dragon-follower/**

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

**Yes, but only random links (everything except the chapters itself) were generated into WebToEpub.**

**Again, thank you very much!!! :D**

**Comment by dteviot** [comment]
@vanessabluellie 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with a first chapters for
* https://chaleuria.com/novels/records-of-the-dragon-follower/
* https://chaleuria.com/novels/reborn-into-a-hamster-for-233-days/

For my records: 29 minutes work

**Comment by vanessabluellie** [comment]
Thank you, it works perfectly!!!! :D

**Comment by dteviot** [comment]
@vanessabluellie 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
