### ISSUE TITLE
Please add site https://www.webnovelpub.com/

### ISSUE THREAD

**Issue by Tiktac33** [dteviot/WebToEpub#869]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.webnovelpub.com/novel/martial-world-webnovel-09111244/chapters
### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html
Yes

### What settings did you use?  What didn't work?
* URL of first chapter --> worked
*https://www.webnovelpub.com/novel/martial-world-webnovel-09111244/220-chapter-0
* CSS selector for element holding content to put into EPUB --> worked
* div.chapter-content
* CSS selector for element holding Title of Chapter --> worked half
* span.chapter-title --> However in the chapter titles there is an error. The TOC has another part in the chapter name, chapter update, and I could not remove this automatically from chapter names
* CSS selector for element(s) to remove --> worked
* #chapter-container > div

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser
No
### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
No
### If you tried writing a parser, and it doesn't work.  Attach the parser here.

Also another problem was that not all chapters can be seen in the TOC, there are multiple pages of chapters. Don't know if this can be done automatically or do I need to do this manually?

Thank you very much!

**Comment by dteviot** [comment]
@Tiktac33 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes:
1. This was an easy one.  It's same layout as lightnovelworld.com
2. Time taken 21 minutes.

**Comment by Tiktac33** [comment]
Thank you for the quick update. The new parser worked pretty good for selecting the image and all the chapters, however there is still the "Visit web_novel_pub_com, for the best no_vel_read_ing experience" watermark in the text. 
I could remove it by adding "#chapter-container > div" to the  CSS selector for element(s) to remove. I don't know how to add it to the parser since I don't know JS, so maybe it could be added by you?

**Comment by dteviot** [comment]
@Tiktac33 
A minor complication, that parser code is shared for multiple sites.
So I need to be careful to make that change in a way that does not result in wanted text being stripped from the other sites.
Can you please provide link to chapter with a watermark, so I can check for myself.

**Comment by Tiktac33** [comment]
All chapters have multiple places where its in the text. For example: [Chapter 4](https://www.webnovelpub.com/novel/martial-world-webnovel-09111244/220-chapter-4). Halfway through the text are hidden elements which don't show up on the website but do show up when downloading the chapter. 
I'm hoping this clears it up a bit? Sorry I don't know a lot about JS, HTML or CSS.
![picture](https://user-images.githubusercontent.com/72865337/203723435-2f6fbdce-2b32-4a51-a3a1-b3f18ed2efad.png)

**Comment by dteviot** [comment]
@Tiktac33 
It's just what I needed, Thanks.

**Comment by dteviot** [comment]
@Tiktac33 
Done.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 15 minutes work.

**Comment by Tiktac33** [comment]
Nice It works perfectly! And also tested it with other books. Thanks a lot :)

**Comment by dteviot** [comment]
@Tiktac33 
Reopen, so I know to contact you when I update version in Chrome and Firefox stores.

**Comment by dteviot** [comment]
@Tiktac33 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
