### ISSUE TITLE
Ziru Musing parser issue

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#87]
Issue trying to grab "https://zirusmusings.com/fh-toc/": no content, probably something changed.
Only the first link ("full text") contains the content, all others link give back no content.

**Comment by dteviot** [comment]
Ah, "The Epic Tale of the Forsaken Hero".  Many of the chapters are GoogleDocs, which I still have not spent time to figure out how to handle.  (It's not a priority for me.)
Refer: https://github.com/dteviot/WebToEpub/issues/64#issuecomment-237109816

**Comment by typhoon71** [comment]
No, I wasn't talking about the google docs links, I'm not asking you to handle those.
If you check the whole TOC you'll see that it's organized like this:

1st "Chapter ": "full text" link (on ziru's), can grab; also individual  "Story"es (on google docs)
2nd "Chapter": individual "Story"es (on ziru's), cannot grab
3rd "Chapter": individual "Story"es (on ziru's), cannot grab
4th "Chapter": individual "Story"es (on ziru's), cannot grab

So my issue is with content on ziru's which doesn't get grabbed; I just see a page with one line of text at the top (ex: "Posted on November 30, 2014December 4, 2014 by Ziru"), one for each "Story".

**Comment by dteviot** [comment]
@typhoon71 
Ah, I see the problem.
The "stories" for "Chapter 1" were all Google docs, so I didn't bother looking at the stores for the other Chapters.  As you've pointed out, they're not Google Docs, but are  slightly different format to the other books on Ziru's site and are not correctly parsed.
Specifically the &lt;article&gt; element has two &lt;div&gt; children, and parser needs to grab the className.startsWith("entry-content") one.

**Comment by dteviot** [comment]
@typhoon71 
>Is that something fixable?

Yes.

**Comment by typhoon71** [comment]
Thanks a lot, works beautifully.
