### ISSUE TITLE
Ranobes error

### ISSUE THREAD

**Issue by bookimp** [dteviot/WebToEpub#871]
**Describe the bug**
Error downloading any ranobes.net ebook
Error: Fetch of URL 'https://ranobes.net/chapters/1205385/' failed with network error 403.
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:32:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:166:45)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:160:31
    at async RanobesParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/RanobesParser.js:20:23)

**To Reproduce**
1. Go to https://ranobes.net/novels/1205385-manuke-fps.html
2. Attempt to create epub

**Expected behavior**
Chapter URLs to load with no error so epub can be downloaded, this last worked for me 11/20 with no changes to system

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Opera GX 
 - Version LVL 4 (core: 92.0.4561.64

**Comment by dteviot** [comment]
@bookimp 

Looks like site has implemented checking for people accessing the site without a web browser.
You need to get a "Checking your browser" screen to appear before opening WebToEpub.
For me, I clicked on the "More Chapters" link.  Then back to https://ranobes.net/novels/1205385-manuke-fps.html and it worked.

For my notes: 15 minutes work.  (Included updating code to get story description for information page.)
