### ISSUE TITLE
Ranobes.Net unable to convert

### ISSUE THREAD

**Issue by Arsur3215Loki** [dteviot/WebToEpub#875]
**To Reproduce**
1. Go to '[Ranobes.net](https://ranobes.net/)'
2. Click on any story
3. Convert with WebToEpub

**Screenshots**
![image](https://user-images.githubusercontent.com/74763442/204926350-59c6c28b-1599-4f2c-83c4-376cd47c2091.png)

**Desktop (please complete the following information):**
 - OS: [Window 10 Pro]
 - Browser [Opera GX]
 - Version [LVL 4 (core: 92.0.4561.71)]

**Comment by dteviot** [comment]
@Arsur3215Loki 
See https://github.com/dteviot/WebToEpub/issues/871 for solution.

**Comment by Arsur3215Loki** [comment]
@dteviot 
I reproduced what was instructed as the alternative but it didn't recognize any chapter. I've also tried different pages and still got the same result. 

**Screenshot**
![image](https://user-images.githubusercontent.com/74763442/204977758-77ba1506-0bf2-41a6-b834-8b525143023d.png)

**Comment by dteviot** [comment]
@Arsur3215Loki 
I think you've opened WebToEpub while showing a "Table of Contents" page e.g. https://ranobes.net/chapters/1205660/
You need to open WebToEpub with a story page:  e.g. https://ranobes.net/novels/1205660-reincarnated-as-an-imperial-prince.html
I'm lazy, I could not be bothered getting WebToEpub to find chapters for both cases.  (Plus the ToC page lacks cover image and summary.)

**Comment by Arsur3215Loki** [comment]
@dteviot I did the normal way first before I made a report, but I think it's now fixed since I could now convert like normal. I don't know why it happened just that I know that I've tested multiple story pages thinking that I might have done something wrong or it might be because of the VPN from the Opera GX. 

Anyway, It is now working normally.
