### ISSUE TITLE
Please add site https://novelbin.net/

### ISSUE THREAD

**Issue by buthub** [dteviot/WebToEpub#877]
It's not the same as novelbin.com. Thanks.

Example Link of ToC:
https://novelbin.net/n/historys-strongest-senior-brother#tab-chapters-title

URL of first chapter,
https://novelbin.net/n/historys-strongest-senior-brother/chapter-1

I tried the default parser, but I couldn't fully get it to work.

The chapter title selector was,
a class="chr-title"
so I put in 
a.chr-title

The content was in,
div id="chr-content" class="chr-c"
I couldn't figure out how to do id (it would really help if you gave a few more examples in that default parser help page you set up, like how to do id or the others, for example), so I instead used
div.chr-c

The element to remove was,
div id="pf-6329760d3a4ce6002827284a"
Even after 20 minutes of searching, I couldn't figure out how to do id (it mentioned putting # in there; I tried it but the parser wouldn't proceed.
div#pf-6329760d3a4ce6002827284a [FAIL]
div.#pf-6329760d3a4ce6002827284a [FAIL]

Well, I've spent a bunch of time on this and I still can't figure it out (I know very little about programming). Please add the above site. Thanks.

**Comment by dteviot** [comment]
@buthub 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novelbin.net/n/historys-strongest-senior-brother

FYI.
for an element like 
> div id="chr-content" class="chr-c"

To get the "id" it's
> div#chr-content

To get a class, it's
> div.chr-c


For my notes: 5 minutes work

**Comment by buthub** [comment]
Thanks a lot, dteviot.

So why did my "div#pf-6329760d3a4ce6002827284a" fail then, when used with the default parser's remove element box?

**Comment by dteviot** [comment]
I don't know.   
Perhaps because there were several elements with similar, but not identical IDs, so one was removed, but the others not?

**Comment by buthub** [comment]
> 

I checked a couple of different chapters, even of a different title, and they all used the same div id. Guess it's one of those mysteries, lol. Thanks.

**Comment by dteviot** [comment]
@buthub 
Reopen, so I know to notify you when Chrome and Firefox stores updated

**Comment by dteviot** [comment]
@buthub 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
