### ISSUE TITLE
Novelhi is not working 

### ISSUE THREAD

**Issue by Okikaemmanuel1** [dteviot/WebToEpub#879]
Only 1 chapter can be gotten at a time

**Comment by dteviot** [comment]
@Okikaemmanuel1 

Seems site randomly gives pages with no content.  WebToEpub's default behavior when this happens is to stop.
You can get WebToEpub to continue when this happens by setting "Skip chapters that return HTTP 404 error" under "Advanced Options".

WebToEpub will then collect what it can, and tell you which chapters it failed.  You can then try to fetch the failed chapters again.
