### ISSUE TITLE
Parser issue: Skythewood

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#88]
I noticed that  the skythewood.blogspot.it parser doesn't always grab the higher resolution image.

For example: "Altina the Sword Princess" volume 10.
There is a b/w picture (0002_p017.jpg) which is 412kB if you click on the pic when reading (1st chapter); the addon grabs just the 81kB preview you see on the page.

It happens every now and the on all of the Altina; it does not happen every time, since the addon usually grabs the correct picture.

I don't know if it happens with other LN on the site.

Can you look into it? Thanks.

**Comment by dteviot** [comment]
@typhoon71
> For example: "Altina the Sword Princess" volume 10.
There is a b/w picture (0002_p017.jpg) which is 412kB if you click on the pic when reading (1st chapter); the addon grabs just the 81kB preview you see on the page.

I assume you’re referring to the 1st  Black and white image at URL http://skythewood.blogspot.it/2016/11/ASP101.html
The HTML of this element is:
```XML
<a href="https://1.bp.blogspot.com/-TCzC8NdrIjY/WDACtZDVBiI/AAAAAAAAHCI/4siljWx8PO4DV6pApUn7NFj-q9UCNM5jQCLcB/s1600/p017.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><span style="font-family: inherit;"><img border="0" height="640" src="https://1.bp.blogspot.com/-TCzC8NdrIjY/WDACtZDVBiI/AAAAAAAAHCI/4siljWx8PO4DV6pApUn7NFj-q9UCNM5jQCLcB/s640/p017.jpg" width="452"></span></a>
```
In general, if an &lt;img&gt; tag is contained in a &lt;a&gt; then the &lt;a&gt; points to the full size image (or a HTML page with a set of images.) So WebToEpub fetches the full size image.
However, in this case the &lt;img&gt; tag is enclosed in a &lt;span&gt; and then a &lt;a&gt;
So, the &lt;span&gt; tag makes WebToEpub thinks the &lt;img&gt; is not enclosed by a hyperlink.

Fix committed to Experimental Tab branch.

**Comment by typhoon71** [comment]
Good, I'll test it out later.
Thanks.

**Comment by typhoon71** [comment]
Tested, works perfectly on all of skythewood; fixes altina, gate, ... I rebuilt all my epubs and I noticed there were quite a bit of images in that situation.

I suppose I can close this myself.

**Comment by dteviot** [comment]
@typhoon71 
> I can close this myself?

You raised it, so you can close it. 

>I suppose the fix will be pushed in the release soon(tm) XD.

Yes, it will go into the next release.  However, I'm not planning on another official release for a while, there's a number of things I want to do.  I want to 
- fix https://github.com/dteviot/WebToEpub/issues/13, 
- speed up things by downloading chapters simultaneously
- Give better download progress update.

**Comment by typhoon71** [comment]
np, I'll just keep using the Experimental Tab branch + chromium.
Btw, I don't think I noticed similar behaviour on other sites: does this (ex) issue apply to other parser too? I mean, Is the image grabbing done on a separate routine?

**Comment by dteviot** [comment]
@typhoon71
The image grabbing logic (img tag inside hyperlink) is common to nearly all sites.
That said, SkyTheWood has really messed up formatting. See https://github.com/dteviot/WebToEpub/issues/75#issuecomment-254613676

**Comment by typhoon71** [comment]
OK, got it.
