### ISSUE TITLE
Chrome crashes when epub is downloaded and Save location dialog opens up.

### ISSUE THREAD

**Issue by joelsnl** [dteviot/WebToEpub#881]
**Describe the bug**
Chrome crashes when epub is downloaded and Save location dialog opens up.

**To Reproduce**
Just downloaded epub from readwn.com and after downloading when the save dialog opens up, it has already crashed, you cannot select the location or do anything on chrome.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 108.0.5359.96

**Comment by joelsnl** [comment]
This works when I unselect the "Pop up Save As Dialog"

**Comment by gamebeaker** [comment]
@joelsnl couldn't reproduce error
https://www.readwn.com/novel/childhood-friend-of-the-zenith.html
Windows10
chrome 108.0.5359.99

Do you have other addons?

**Comment by joelsnl** [comment]
Maxi refresher, Ad block plus and Last Pass. I have always had these plugins even before getting webtoepub, so that can't be the reason also this just randomly started happening. I restarted my laptop twice and its still happening. No pending windows updates or anything else like and no pending reboots for any updates etc either.

**Comment by gamebeaker** [comment]
@joelsnl i downloaded your extensions and couldn't reproduce the problem.
try to delete your browser chache cookies etc. [chrome://settings/clearBrowserData](chrome://settings/clearBrowserData) select the whole time.
if you still have the problem you can use firefox browser with WebToEpub.

**Comment by dteviot** [comment]
@joelsnl 
1. Please describe what you mean by "Crashes".  e.g. Does WebToEpub freeze? Do you get an error message?
2. URL of story you're trying to convert.
3. Does this happen with all stories, or just this one?

**Comment by gamebeaker** [comment]
abandoned from issue creater.
