### ISSUE TITLE
Please add site https://lightnovels.live/novel/mage-academy-i-have-infinite-skill-points.html

### ISSUE THREAD

**Issue by FrostDuchess** [dteviot/WebToEpub#882]
The old website lightnovels.me redirects to this new mirror website which webtoepub doesn't work on for some reason 

thank you for your continued hard work on this software

**Comment by dteviot** [comment]
@FrostDuchess 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with chapters 1 and 2 of 
* https://lightnovels.live/novel/mage-academy-i-have-infinite-skill-points.html

For my notes: 18 minutes work

**Comment by dteviot** [comment]
@FrostDuchess 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
