### ISSUE TITLE
when downloading stories from spacebattles.com, not all of the story is downloaded

### ISSUE THREAD

**Issue by mhussaincov93** [dteviot/WebToEpub#883]
**Describe the bug**
when downloading stories from spacebattles.com not all of the story is downloaded.

**To Reproduce**
1. Go to
https://forums.spacebattles.com/threads/the-paragamer-book-i-worm-the-gamer-w-ocs-complete.496126/reader

2.
launch web to epub.
3.
try to download this story.

**Expected behavior**
the story should have been downloaded in full.
currently, the story is not fully downloaded.

chromium
latest

**Additional context**
the url is in reader mode, which means only the story elements are viewed not the comments.
if using fanficfare, the story is downloaded in full, how ever I wish to navigate away from fanficfare.

**Comment by dteviot** [comment]
@mhussaincov93 
What do you mean by "not all of the story is downloaded"?  e.g.
1. Not all chapters are shown?  (If so, which ones are not shown)
2. Not all chapters requested are fetched?  (If so, which ones are fetched/not fetched)
3. Something else?

Note, if problem is not all chapters are available to select to download, did you open the threadmarks before opening WebToEpub?.  e.g.
![image](https://user-images.githubusercontent.com/5157081/206921468-52526625-57ad-4012-a98d-d7756aa94646.png)

**Comment by mhussaincov93** [comment]
hi,
in my defence, I thought that reader mode would work to get all chapters/urls.
I was not aware of the threadmarks feature.
thank you for telling me about this neet feature.
do all sb threads have these threadmarks?
sorry for wasteing your time.
Majid

**Comment by dteviot** [comment]
@mhussaincov93 
> do all sb threads have these threadmarks?

I think so.
