### ISSUE TITLE
https://pandamtl.com

### ISSUE THREAD

**Issue by levinuiiy** [dteviot/WebToEpub#887]
https://pandamtl.com/

No, since i have no idea how. 

Um, don't have anyone that can help, but reason why i requested this site, 
due to this site has ALOT of Korean Mtl, that are not found on others.

**Comment by dteviot** [comment]
@levinuiiy 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with chapters 0, 1, 2 & 25 of:
* https://pandamtl.com/series/the-protagonist-is-a-villain/

For my notes: 21 minutes work.  (Pretty easy as site was very similar to https://novelsknight.com/

**Comment by dteviot** [comment]
@levinuiiy 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
