### ISSUE TITLE
"Test" and CSS selector for supported sites.

### ISSUE THREAD

**Issue by MohamadTaher** [dteviot/WebToEpub#889]
Hello. 

I love the feature where you choose what content you want to be in the chapter and what content you don't want. Unfortunately, I can't preview ("test") the content for the supported sites such as boxnovel.com or lightnovelworld.com

Can you include this feature "test" beside the "Copy URLs to Clipboard" and put the feature "CSS selector for element(s) to remove:" under the "file name" or anywhere?

It just doesn't make sense to me how the unsupported sites have a higher level of customization than the supported sites.

Example of a supported site: [https://www.lightnovelworld.com/novel/reincarnated-as-an-energy-with-a-system-13122039](https://www.lightnovelworld.com/novel/reincarnated-as-an-energy-with-a-system-13122039)

Example of not a supported site: [https://novelbin.net/n/reincarnated-as-an-energy-with-a-system-novel](https://novelbin.net/n/reincarnated-as-an-energy-with-a-system-novel)

Thanks in advance.

**Comment by dteviot** [comment]
@MohamadTaher 
To make sure I understand, you're request is for
> "CSS selector for element(s) to remove:" to be available for sites that you don't need to tell WebToEpub how to process.

My question is why?  For the sites that WebToEpub knows how to process, it should not be necessary to tell WebToEpub what to remove.   Note, if there is rubbish that needs to be removed, then WebToEpub needs to be updated.
Can you provide links to chapters with problem (and ideally, describe what I should be seeing.)
