### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Blakemontefalco** [dteviot/WebToEpub#891]
For mobile phone

**Comment by dteviot** [comment]
@Blakemontefalco 

I'm not sure what you're asking.
If you want to run WebToEpub on a mobile phone, 
1. Install either the Kiwi or Yandex browser (note, I'm not endorsing either browser)
2. In the Browser, load the extension from the Chrome web store.

Note, https://novelebook.com is not supported by WebToEpub.  
Half the content on each chapter is encrypted.
See: https://github.com/dteviot/WebToEpub/issues/764

**Comment by dteviot** [comment]
@Blakemontefalco 
Sorry, not possible, at least some of the content on each page is encrypted.
