### ISSUE TITLE
https://ranobes.net/ Antibot detection stop WebtoEpub completely

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#894]
In the past few months, I have encountered a problem using WebtoEpub when compiling web content into an ePub file. The site I have been using, Ranobes, has implemented an antibot detection system disrupting the compilation process. I fear that more websites will go the same route, and I am asking if there are any solutions.

**Comment by dteviot** [comment]
@DicerX 
Sorry, it's not really possible to work around this.
If there was, WebToEpub would be in violation of Google's rules for extensions.

**Comment by dteviot** [comment]
@DicerX 
That said, this set of steps might help.
https://github.com/dteviot/WebToEpub/issues/871

**Comment by DicerX** [comment]
Let's hope this solution can stay around. That said, I'll not be rash and ask for a solution that allows me to load a modded version of the extension.
