### ISSUE TITLE
May I ask how to install and run web to epub in pc🥰

### ISSUE THREAD

**Issue by Blakemontefalco** [dteviot/WebToEpub#895]

**Comment by DicerX** [comment]
https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm?hl=en

**Comment by davethwave** [comment]
You follow the link above, download the addon from the store. Once installed there will be a blue book icon top right.
To use it, you want to be on a site like royal road and be on a page where you can see the novels chapter list. After that you just click on the book icon and it should scan the page for chapter links, then it opens a new tab where you can inspect what's being downloaded as well as change stuff like how many chapters are being downloaded at a time or novel name if the addon bungles it up somehow.

**Comment by dteviot** [comment]
@Blakemontefalco 
I'm going to assume this answers the problem.  If not, add a comment and I'll reopen.
