### ISSUE TITLE
https://csycrus.wordpress.com/

### ISSUE THREAD

**Issue by graciagraciagracia** [dteviot/WebToEpub#898]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not? No, don't know how to execute.
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter https://csycrus.wordpress.com/chapter-61/
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@graciagraciagracia
Configure default parser as shown in image below, then click "Apply" button.
![image](https://user-images.githubusercontent.com/5157081/216839763-4824473f-3fb2-4695-b9e1-25c97054c6d4.png)

**Comment by dteviot** [comment]
For my notes: 14 minutes work
