### ISSUE TITLE
Feature Request: Use URL to specify Cover image

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#9]
(Request by "Guest")

On the topic of cover issues with the extension, could I make a suggestion, to allow the setting of covers using an image from any URL instead of just those available on the page?

For example, take this page
> https://www.baka-tsuki.org/project/index.php?title=The_Zashiki_Warashi_of_Intellectual_Village:Volume9

As visible on that page itself (and therefore available for packing by the extension), the closest one can get to a cover would be 

> https://www.baka-tsuki.org/project/images/3/31/Zashiki_v09_000.jpg

However, this is too wide as it includes the front cover, the spine, and the back cover as well.
If on the other hand one were to check the main series page, 

> https://www.baka-tsuki.org/project/index.php?title=The_Zashiki_Warashi_of_Intellectual_Village

there is a much better option available to act as a cover, not present on the volume's full text page.

> https://www.baka-tsuki.org/project/images/3/30/Zashiki_Volume_9_Cover.jpg

As-is, the extension does not allow for setting this as the cover, and therefore the epub needs to be manually tweaked after the fact to replace the cover. 

Since I'm uncertain if there is any practical easy one-size-fits-all fix to somehow magically detect the presence of a cover image on a page other than the one being viewed, then a solution could be to allow entering an image URL to fetch a specific image to act as cover.

**Comment by belldandu** [comment]
I will look into this a bit later.

**Comment by belldandu** [comment]
At this point after extensively looking into this. The best option would be to provide an option for a custom cover url. This url should be passed into the images array like the rest of the images however so that all the check can go through.

I will be making a seperate pull request from #10 to do this.

**Comment by dteviot** [comment]
Initial version implemented in version 0.0.0.9.
Needs more work for extracting the file name from the supplied URL.  Some cases don't work.
There are three cases for Baka Tsuki images.
- https://www.baka-tsuki.org/project/index.php?title=File:HSDxD_v01_cover.jpg
- https://www.baka-tsuki.org/project/thumb.php?f=HSDxD_v01_cover.jpg&width=427
- https://www.baka-tsuki.org/project/images/7/76/HSDxD_v01_cover.jpg

Only the first one works correctly.

**Comment by belldandu** [comment]
@dteviot I recommend using this http://blog.teamtreehouse.com/reading-files-using-the-html5-filereader-api here https://github.com/dteviot/WebToEpub/blob/sonako/plugin/js/parsers/ImageCollector.js#L306 to get the image name and type from the file itself along with its width and height.

I've added myself to assignees for this as well.

**Comment by belldandu** [comment]
Using the filereader api will also get rid of the need for complex regex's that might fail under certain conditions.

**Comment by belldandu** [comment]
The above might be a bad idea though. I am still looking into other options.

**Comment by dteviot** [comment]
@belldandu 
This works for the failing cases, but it's kind of ugly. https://github.com/dteviot/WebToEpub/commit/fc13f84ede4944f5c0a4cf30efaf2bf4f3318ebe
I guess it will do for the moment.

**Comment by dteviot** [comment]
I'm going to call this done.

**Comment by belldandu** [comment]
Yeah seems to work for now.
