### ISSUE TITLE
[Add Support] Firefox Android

### ISSUE THREAD

**Issue by Snake87r** [dteviot/WebToEpub#90]
Like the title says add support for firefox on android device

**Comment by dteviot** [comment]
Firefox for Android doesn't implement everything that the desktop uses.
See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

However, when it catches up, it should "just work".
Also, this: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

**Comment by belldandu** [comment]
This is less bug and more enhancement.

**Comment by belldandu** [comment]
Labeling this as pending until firefox on android catches up.

**Comment by belldandu** [comment]
Actually i think blocked fits better here.

**Comment by dteviot** [comment]
Works on my Android tablet.
