### ISSUE TITLE
Yandex browser not compatible 

### ISSUE THREAD

**Issue by yohanskelp** [dteviot/WebToEpub#900]
I tried installing the extension to Yandex Browser in Chrome webstore but it says 'not compatible'. Please help.

**Comment by dteviot** [comment]
@yohanskelp 
Note, I don't test or maintain WebToEpub for anything other than Chrome or Firefox.  So, if it doesn't work on other browsers, you're out of luck.

The latest version of WebToEpub in the Chrome store (0.0.0.151) has been updated to use Manifest version 3 (which at the time I did the work, was required by Google.) 
I suspect that the Yandex browser does not support Manifest version 3.
You might try the Kiwi browser, although I don't know if it supports version 3.  (Developer says he's not dropping support for v2, but doesn't say if he's adding v3.)
Failing that, you should be able to load an older version of the extension.  0.0.0.150 or earlier.
The other option, try the version from the Mozilla store.  That's the Firefox build and is still version 2.  Although I'm not sure if it will work on Chrome/Yandex.

**Comment by yohanskelp** [comment]
I tried using Kiwi Browser and it worked. Thankyou!
