### ISSUE TITLE
Please add site https://www.pawread.com/

### ISSUE THREAD

**Issue by Moonstarx** [dteviot/WebToEpub#903]
Toc example: https://www.pawread.com/novel/the-return-of-the-crazy-demon/

**Comment by dteviot** [comment]
@Moonstarx 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.pawread.com/novel/the-return-of-the-crazy-demon/ chapter 1

For my notes:  39 minutes work

**Comment by Moonstarx** [comment]
Thank you very much! it worked perfectly.

**Comment by dteviot** [comment]
@Moonstarx 
Reopening, so I know to notify you when version in Chrome and Firefox stores updated.

**Comment by dteviot** [comment]
@Moonstarx 
Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
