### ISSUE TITLE
Please fix this source

### ISSUE THREAD

**Issue by JoshOm21** [dteviot/WebToEpub#906]
**Describe the bug**
There's something wrong with the source inkitt.com, it won't pack the whole chapters. Only the first chapter which is the information will generate.

**To Reproduce**
1. Go to 'inkitt.com'
2. Click on 'WebToEpub Extension'
3. Scroll down to 'pack EPUB'
4. See error 'open the epub'

**Expected behavior**
Will pack the whole chapters.

**Screenshots**
![IMG_20230121_100558](https://user-images.githubusercontent.com/93379319/213839495-9d843aff-0444-4868-9930-be1c2c0bd033.jpg)
![IMG_20230121_100544](https://user-images.githubusercontent.com/93379319/213839505-fa926b36-9959-4e88-b6c0-4ea90d938e82.jpg)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version 151

**Smartphone (please complete the following information):**
 - Device: [Android]
 - Browser [kiwi browser]
 - Version [151]

**Additional context**
Hope it'll be fix soon. Thank you.

**Comment by dteviot** [comment]
@JoshOm21 
I just tried https://www.inkitt.com/stories/romance/433453 (the one you used) with desktop chrome and it seems to work fine.
So, my steps were:
1. Open Chrome and go to https://www.inkitt.com/stories/romance/433453
2. Click on WebToEpub icon.
3. Get list of chapters.
4. Click "Pack Epub".  Chapters collected, epub generated.

Can you give me the exact set of steps you did?

**Comment by JoshOm21** [comment]
I tried it. Only the first chapter. I'm using the kiwi browser then webtoepub extension.

**Comment by dteviot** [comment]
@JoshOm21 
Some sites format the pages differently, depending on if they think the web browser is a mobile or a desktop.
Are you running kiwi in desktop mode?

**Comment by JoshOm21** [comment]
Yes. I'm using my mobile and kiwi browser is on desktop mode. It generates but only the first chapter. I don't know why.

**Comment by dteviot** [comment]
@JoshOm21 
When you open WebToEpub, how many chapters does it say it's going to fetch?

**Comment by JoshOm21** [comment]
No chapter. Only the information.
![IMG_20230124_224549](https://user-images.githubusercontent.com/93379319/214325823-5f95631b-a80b-4d86-babc-9329166325a8.jpg)

**Comment by JoshOm21** [comment]
Once I'll click the (PACK EPUB) only the information of the novel will generate.

![IMG_20230125_192218](https://user-images.githubusercontent.com/93379319/214551071-e175e42e-f09d-4d3b-b94b-1ff2768e4955.jpg)

**Comment by gamebeaker** [comment]
@JoshOm21 if you have WebToEpub open (same as your last screenshot) change the website (WebToEpub) to desktop mode. Then click Pack Epub. If i don't do this i get an error Message from WebToEpub.
![signal-2023-01-25-162727](https://user-images.githubusercontent.com/9269847/214604266-ea6a47cc-d8e4-467b-b9e5-069042b5a59d.png)
For the future if you encounter a problem please share the error message with us.

**Comment by JoshOm21** [comment]
Oh, it works! Thank you so much! 😁
