### ISSUE TITLE
Can't fetch this novel: https://www.mtlnovel.com/i-have-the-alchemy-emperor-in-my-head/

### ISSUE THREAD

**Issue by Pinewood21** [dteviot/WebToEpub#908]
Error: Fetch of URL 'https://www.mtlnovel.com/json/99030-c-16-16.json' failed with network error 500.
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:32:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:178:45)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:172:31
    at async MtlnovelParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MtlnovelParser.js:23:25)

Here's the error I'm facing. I checked a few previous issues here, which is why I tried the default parser. However, I ended up not getting the result I wanted. Like the chapter list don't show up at all, instead it just mainly focus on what's in chapter 1. The rest of the other chapters don't show up. A little help please!

**Comment by dteviot** [comment]
@Pinewood21 
A 500 error means the site had some sort of problem trying to serve the request.
I just tried https://www.mtlnovel.com/i-just-became-an-immortal-my-descendants-beg-me-to-come-out-of-the-mountain/, chapters 1 and 300, and it seems to work.
1. What is the URL of the story you had a problem with?
2. What happens if you try to get the list of chapters in your browser?

**Comment by Pinewood21** [comment]
1. The url: 'https://www.mtlnovel.com/i-have-the-alchemy-emperor-in-my-head/'
2. It says 'searching for urls. Please wait.' After a while, you see the errors stated above. I tried reinstalling the web to epub extension. Still nothing.

And yes, there is no problem with other url from MTLnovel, only this one.

**Comment by dteviot** [comment]
@Pinewood21 
There's a problem with that list of chapters.
If you try to open the set labelled "Chapters 3751-3822" in a browser, it won't work either.  
Also note, other chapters in list seem to be messed up.  e.g. open 3500-3750, numbers don't match.

**Comment by dteviot** [comment]
Closing, due to lack of response
