### ISSUE TITLE
lightnovelbastion parser

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#91]
I noticed the parser for "lightnovelbastion.com" doesn't save the chapter title.

Try to grab "https://lightnovelbastion.com/project.php?p=98": the title is on top of the page but the epub has no title in the text.

I think it gets removed because it's outside of the article.

Btw, I noticed the parser is improved compared my previous grab there, well done.

**Comment by dteviot** [comment]
@typhoon71 
> I noticed the parser for "lightnovelbastion.com" doesn't save the chapter **title.**

D'oh!  I'll get that fixed shortly.

> Btw, I noticed the parser is improved compared my previous grab there, well done.

I don't see how that's possible.  Revision history for LightNovelBastionParser.js shows it has not been changed since it was first written.  Can you be more specific about what's improved?

**Comment by typhoon71** [comment]
Ollala!  /me blushes. What a blunder...

Then it means the my (really) old grab of Kuro no Maou at LightNovelBastion was done before you made the parser, I'd say around ch316 release (18 Nov); it's the only possibility that I can think of.

Obviously compared to a grab from the "default" parser the actual parser is beautiful... I probably just grabbed the content to work on it later, and I postponed(tm)... which seems to have been better than start working on it! XD

So, thanks again.

**Comment by dteviot** [comment]
@typhoon71 
>I noticed the parser for "lightnovelbastion.com" doesn't save the chapter title.

Fix added to Experimental Tab Mode branch.  Note, the three stories I checked have a title, and a sub title in a different location.

**Comment by typhoon71** [comment]
It's fine, since the chapter number and the title are in the same xhtml it's easy enough for me to fix that manually. Thanks a lot.
