### ISSUE TITLE
Option to Not Fetch "Translation Notes" and the "<span class='tooltip-toggle'>" From [https://chrysanthemumgarden.com/]

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#911]
Hello!

I'm really sorry for the inconvenience and bother, but I was just wondering if it was possible to create a "checkbox" option where the user can choose to not fetch the "Translator's Notes" from the site "https://chrysanthemumgarden.com/" as well as also not retrieving these **<span class='tooltip-toggle' tooltip-target='tooltip-e8fe86'></span>** html tags that appear with each individual footnote in the text.

Like this image below (from another site which has this option enabled):

<img width="500" alt="image" src="https://user-images.githubusercontent.com/55352222/216821970-dc5f0f9d-93eb-4ea1-a3d0-865536b6d1dc.png">

There are many notes that are actually irrelevant to the text and are more so comments that sometimes total in the hundreds which are a bit inconvenient to delete one by one.

If this is too much trouble then that's completely okay too! Thank you very much again!

**Comment by dteviot** [comment]
@BonBon
Please provide URL of page with translator's notes.

**Comment by vanessabluellie** [comment]
@dteviot

Ah I'm really sorry! Almost all their novels have translator's notes, but here's a novel URL that has many:

https://chrysanthemumgarden.com/novel-tl/gcf/

**Comment by dteviot** [comment]
@vanessabluellie 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://chrysanthemumgarden.com/novel-tl/gcf/gcf-10/

For my notes: 19 minutes work

**Comment by vanessabluellie** [comment]
@dteviot 

Hello! Thank you very much for the fix! It works really well! But I was wondering, is it perhaps not possible to also somehow make it so that WebToEpub will also not fetch the **<span class='tooltip-toggle'></span>** tags that come with every individual Translator's Note as well (in the chapter text)? Ah, but if this is not possible and too time-consuming, then that's okay!  Just disabling the translator's notes is really good! Apologies again for the inconvenience and thank you very much!

**Comment by dteviot** [comment]
@vanessabluellie 
> make it so that WebToEpub will also not fetch the tags that come with every individual Translator's Note as well

Please provide an example of what you mean.

**Comment by vanessabluellie** [comment]
@dteviot 

Ah okay! So on the website itself, throughout a chapter, when a word or phrase has a Translator's Note, you'd need only to click on the word to make the Translator's Note appear overhead which is created by the <span class='tooltip-toggle'> tags. I would ordinarily be able to edit them out via Calibre, but the target number (e.g. <span class='tooltip-toggle' tooltip-target='tooltip-**8380a6**'>Translator's Note</span>) for each Translator's Note changes continuously (and totals in the hundreds). It's also not constant because it would become a different number each time the chapter is re-opened.

It looks like this on the source itself:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/55352222/217399924-0349176f-cfb5-486c-926d-a08f4bd3d865.png">

And this on the "page source":

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/55352222/217400146-8a64c48e-53d9-4cde-8320-0baef1b8ee80.png">

But if this is not possible, then forget it ahah, it's only a little cumbersome but not a major inconvenience. Thank you very much again!

**Comment by dteviot** [comment]
Those are &lt;span&gt; elements.
If I remove them, the text inside the elements will be removed.  
This will result in bad text.
So, you presumably don't want these elements removed, just replaced with the text that's inside them.
Which is reasonably easy for me to do.  (Testing that it works properly and doing the commit paperwork will be the time consuming bit.)

Note, I can probably give you a script that will let [EpubEditor](https://github.com/dteviot/EpubEditor) do this for any of your existing epubs, if you like.

That said, these are span elements,  unless there's something in the stylesheet (and there isn't in the default one used by WebToEpub) then they have no effect.  So why do you want them replaced?

Note, I'm not refusing to do this, I'm trying to understand why you want it done.  
My mental model says, doing this will have no observable effect.  
You're asking for this to be done, which says to me "there is an effect."

I'm trying to understand where the discrepancy is.

**Comment by vanessabluellie** [comment]
@dteviot 

AH, I'm really sorry! You're completely correct that there is no observable effect at all to doing this. But since I edit the text in all my epubs (with the formatting and chapter text itself sometimes), I'm very particular with unnecessary tags even when I can't see them. I've spent hundreds of hours combing through them and deleting, so I'm just a little too picky ahah.

A script in EpubEditor to get rid of these span tags would be absolutely amazing (if the text in those span tags really don't get deleted ahah), but if this is much too time-consuming, then that's completely okay! Apologies for taking up your time again! :D

**Comment by dteviot** [comment]
@vanessabluellie 
Script you want is
```javascript
let toChange = [...dom.querySelectorAll("span.tooltip-toggle")];
for(let s of toChange) {
    s.replaceWith(s.textContent);
}
return 0 < toChange.length;
```

*Instructions*
1. After you've opened EpubEditor in browser
2. Drag and drop Chrysanthemum Garden epub onto the drop zone.
3. Replace the text in the right window with the script above.
4. Click the button "Run script above to modify Epub"
5. Wait a little bit. Depending on your chrome settings you will either 
    5.1 Get a file dialog asking you for name to save the fixed epub, or
    5.2 Modified epub will be saved.
    
 For my notes: 25 minutes work.  (Mostly test and write-up.)

**Comment by dteviot** [comment]
@vanessabluellie 
This is what the EpubEditor was created for.  Doing bulk edits to epubs, where Calibre's regex or search isn't quite up to the job.

**Comment by vanessabluellie** [comment]
> @vanessabluellie This is what the EpubEditor was created for. Doing bulk edits to epubs, where Calibre's regex or search isn't quite up to the job.

AH, I see! Thank you so much!!! It worked perfectly!!!!! :D
