### ISSUE TITLE
Please Add Jonaxx App Stories https://jonaxxstories.com/ 

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#914]

**Comment by dteviot** [comment]
@AngelBurn 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with: 
* https://jonaxxstories.com/category/baka-sakali-1/

NOTE
Not the nicest site,  I can't find a Table of Contents page.
Best seems to be, for story https://jonaxxstories.com/alegria-boys-series/baka-sakali-1/
https://jonaxxstories.com/category/baka-sakali-1/ is sort of a ToC.  But there's no link from one to other.  So, you'll need to open WebToEpub from a page like https://jonaxxstories.com/category/baka-sakali-1/, I don't know if those exist for the other stories.

For my notes: 53 minutes work

**Comment by dteviot** [comment]
@AngelBurn 
Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
