### ISSUE TITLE
Broken site in WixParser

### ISSUE THREAD

**Issue by alethiophile** [dteviot/WebToEpub#915]
**Describe the bug**
For the page https://machinevshornydemons.wixsite.com/machine-vs-horny-dem/marquis-eldest-sons-lascivious-story, running web2epub I get:

```
json is undefined extractRestUrlsFromJson@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/parsers/WixParser.js:42:24
buildMapOfPageUrltoRestUrlWithContent@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/parsers/WixParser.js:28:21
getChapterUrls@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/parsers/WixParser.js:20:41
onLoadFirstPage@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/Parser.js:378:14
processInitialHtml@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/main.js:46:24
populateControlsWithDom@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/main.js:237:27
onMessageListener@moz-extension://56703a59-b023-4715-901a-6994eb4de9ee/js/main.js:16:36
```

Manually selecting the default parser works.

**To Reproduce**
1. Go to the URL https://machinevshornydemons.wixsite.com/machine-vs-horny-dem/marquis-eldest-sons-lascivious-story
2. Invoke web2epub

**Expected behavior**
the normal download page

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: Firefox
 - Version: 107.0.1

**Comment by dteviot** [comment]
@alethiophile 
Not fixing for site that has single story, and default parser can be used for.

Not willing to spend time on the HTML soup that is that page.
