### ISSUE TITLE
Broken site

### ISSUE THREAD

**Issue by alethiophile** [dteviot/WebToEpub#916]
**Describe the bug**
When trying to scrape the site https://genesistls.com/series/the-main-heroines-are-trying-to-kill-me/, web2epub does not detect the contents list, and produces an empty list. To make it work I have to manually extract the contents and give them to web2epub via the "edit chapter URLs" function.

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: Firefox
 - Version: 107.0.1

**Comment by dteviot** [comment]
@alethiophile 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://genesistls.com/series/the-academy-heroines-remember-my-death/, chapters 1 to 6

Note, does not work for chapters that require a password

For my notes: 13 minutes work

**Comment by dteviot** [comment]
@alethiophile 
Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
