### ISSUE TITLE
Please add site https://novel-bin.net/

### ISSUE THREAD

**Issue by buthub** [dteviot/WebToEpub#918]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://novel-bin.net/novel-bin/all-hail-cousin-brother-nov1874311724#tab-chapters-title
(the chapters wind up including a bunch of irrelevant links; chapter 1's title becomes READ NOW; last chapter also winds up right after chapter 1)

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
https://novelbin.net/n/all-hail-cousin-brother/chapter-1 
* CSS selector for element holding content to put into EPUB
div.chr-c
* CSS selector for element holding Title of Chapter
a.chr-title
* CSS selector for element(s) to remove
div#pf-*

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@buthub 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novel-bin.net/novel-bin/all-hail-cousin-brother-nov1874311724, chapter 1

*Note*
* To get all chapters in title, make sure you've opened the chapters tab and scrolled down, so all chapters are showing before opening WebToEpub

For my notes: 45 minutes work

**Comment by dteviot** [comment]
@buthub 
Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
