### ISSUE TITLE
Remove scripts from epub

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#92]
I noticed some epubs made contain <script> ... </script> or <js> ... </js> "content", basically a bunch of scripts for ads or fancy animations: I suppose we don't want them around.

Would it be possible to remove it from the generated epub?

**Comment by dteviot** [comment]
@typhoon71
Most parsers remove the &lt;script&gt; elements.  However, there are some sites (e.g. readlightnovel) where some content is inside the script element.  So, the default parser leaves &lt;script&gt; elements as it doesn't know if it's needed or not.   Did you use the default parser to create those epubs?

**Comment by typhoon71** [comment]
I don't think I was grabbing from readlightnovels. 
I'm having an hard time trying to remember what site it was, but I'm pretty sure I used the default parser for that.

What I was hoping for was to remove scripts by default, but if there's content inside the script tags then there's the risk of losing stuff you/we don't want to.

If I find what site it was I will ask for a dedicated parser then.

**Comment by dteviot** [comment]
@typhoon71
If you can find the epub with the &lt;script&gt; tags, the URL it was retrieved from will be in the metadata.

**Comment by dteviot** [comment]
Closing, due to lack of URL that reproduces problem.

**Comment by typhoon71** [comment]
Yeah, didn't find the "offendig" webpage, and I forgot to close this.
