### ISSUE TITLE
Library.js EPUB2 error

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#920]
It is a three line fix and i didn't want to create a pull request for it.
If the EPUB in the Library was EPUB2 it didn't have the file OEBPS/toc.xhtml and JSzip.file(...) is null. null.async(...) creates an error.
Library.js line 80
old:
let PreviousEpubTocEpub3Text =  await PreviousEpubzip.file("OEBPS/toc.xhtml").async("string");
new:
let PreviousEpubTocEpub3Text =  await PreviousEpubzip.file("OEBPS/toc.xhtml");
if (PreviousEpubTocEpub3Text != null) {
    PreviousEpubTocEpub3Text = PreviousEpubTocEpub3Text.async("string");
}

**Comment by dteviot** [comment]
actually, I think it's a three character fix.
``` javascript
let PreviousEpubTocEpub3Text = (await PreviousEpubzip.file("OEBPS/toc.xhtml"))?.async("string");
```

**Comment by gamebeaker** [comment]
@dteviot you are right.

**Comment by dteviot** [comment]
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.
