### ISSUE TITLE
Hello pawtead is not working anymore 

### ISSUE THREAD

**Issue by Okikaemmanuel1** [dteviot/WebToEpub#922]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Okikaemmanuel1** [comment]
Sorry I meant this site https://m.pawread.com/

**Comment by dteviot** [comment]
@Okikaemmanuel1 
https://m.pawread.com/ is the mobile version of https://pawread.com/.  It's got a different layout.
From WebToEpub's viewpoint, it's a completely different site, and would require a parser of its own.

I'm going to guess you're using a mobile browser.  So, set your browser to desktop mode (refer "How to use with Kiwi-Browser" at 
https://github.com/dteviot/WebToEpub/wiki) and go to the non-mobile version of site.  

If that doesn't work.  Let me know.

For my notes: 15 minutes work.

**Comment by dteviot** [comment]
@Okikaemmanuel1 
Actually, if it works, please let me know, so I can close this.

**Comment by Okikaemmanuel1** [comment]
It doesn't work, tried it

**Comment by gamebeaker** [comment]
@dteviot There is no parser for https://www.pawread.com/novel/douluo-dalu-2-the-unrivaled-tang-sect/ even on desktop.

**Comment by dteviot** [comment]
@gamebeaker 
> There is no parser for https://www.pawread.com/novel/douluo-dalu-2-the-unrivaled-tang-sect/ even on desktop.

There is, but you probably need to update your branch. https://github.com/dteviot/WebToEpub/commit/d37cb64c6803066039be66f81e022591c3f9ef9f

@Okikaemmanuel1 
You'll need to load the in-development version of WebToEpub.  The version in store hasn't been updated for pawread yet.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@Okikaemmanuel1 @gamebeaker 

I'm going to call this done.

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
