### ISSUE TITLE
Empty chapters for panda-novel.com

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#923]
@dteviot,
Hello dev.

   I use the method of opening any chapter, when the contents of the chapter open without going through cloudflare authentication then to get the token, I then tap the address bar, delete the letter `s` from `https` to `http`, then press go/enter, then certainly the page will be directly connected to cloudflare for site authentication. 
   Then click on the Panda-Novel icon to return to the main page, find your novel there, click on it. Then webToepub can already load the TOC of the novel.

   WebToepub can download the chapters of the novel, but the chapters are empty, there are only chapter titles.
Please fix it...

**Test novel link**:   https://www.panda-novel.com/details/shadow-slave(YN)-1413/chapters
.
.
![Screenshot_20230220-193057_Kiwi Browser](https://user-images.githubusercontent.com/50254552/220109495-edf52541-991a-4cd3-9d63-166678038626.jpg)

![Screenshot_20230220-193151_MiXplorer](https://user-images.githubusercontent.com/50254552/220109546-f5c28c18-372f-4740-862b-a382728f5c10.jpg)

**Comment by dteviot** [comment]
@budikesuma 

I'm not able to get a table of contents, so if you can provide me with a URL to a TOC, that would be appreciated.
That said, I had a look at the content for a chapter, and it doesn't seem to have changed significantly, so I'm not sure why the existing parser does not work.  That said, I've made a few tweaks that should make it a bit less selective and might make it work for you.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Note, I have not tested this.

For my notes: 20 minutes work

**Comment by SirRomey** [comment]
Is there any updates on this? @dteviot 

I notice that the books actually download but for some reason they do not work on certain apps like Apple Books (didn't work both on Mac and iOS) whereas other applications like Freda (for Windows) load the content perfectly fine.

I do hope you fix this as soon as possible. :)

**Comment by dteviot** [comment]
@SirRomey 
Send me an epub that works on Freda and doesn't on Apple books and I'll take a look at it.

**Comment by SirRomey** [comment]
Here you go: https://drive.google.com/file/d/1IKgD9E3iEkjDN3thmGSOGpf_VL882YmW/view?usp=drivesdk

This is what every page looks like on Books: ![image](https://user-images.githubusercontent.com/71877936/227753041-f2d704e5-2436-4ea4-beb1-7075b1f3b3d5.png)

I'll send a screenshot of how it looks on Freda once I'm home.

**Comment by dteviot** [comment]
@SirRomey 
>I'll send a screenshot of how it looks on Freda once I'm home.

Unnecessary.  Problem seems to be a malformed style attribute in the chapter title.
```html
<h2 :style="{'font-size': fontSize * 1.4+'px'}">﻿1 Not Too Bad of a Start </h2>
```

Apple is (technically, correctly) refusing to process it.
I suspect other epub readers simply ignore it.

Fix should not be difficult.

**Comment by dteviot** [comment]
Well, this is embarrassing, [budikesuma](https://github.com/budikesuma) had already pointed out the problem with the malformed style attribute.

Anyway, root problem is site parser had code to deal with lazy loaded content, which complicated everything.
I think the lazy loading isn't happening any more, so stripped out that code.
And adjusted the content grabbing to ignore the title,  Instead, chapter title is processed by addTitleToContent() which cleans up the invalid style element.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.panda-novel.com/content/immortal-in-the-magic-world(IN)-1809-1432392/chapter-1, chapters 1, 300
* https://www.panda-novel.com/details/shadow-slave(3)-1413, chapters 1, 810

For my notes: 44 minutes work

**Comment by SirRomey** [comment]
It works perfectly fine. Thanks for your help regarding this matter. 😃

**Comment by dteviot** [comment]
@budikesuma @SirRomey 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
