### ISSUE TITLE
Please add site https://lightnovelpub.fan/

### ISSUE THREAD

**Issue by chaitanya44444** [dteviot/WebToEpub#925]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

[### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site](https://lightnovelpub.fan/novel/the-beginning-after-the-end-web-novel-10021224/chapters/page-4)  there are 5 pages as many chjapters

### Did you try using the Default Parser for the site?  If not, why not?
I did 
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter- **https://lightnovelpub.fan/novel/the-beginning-after-the-end-548/chapter-301-61112**
* CSS selector for element holding content to put into EPUB -div.chapter-content font_default
* CSS selector for element holding Title of Chapter- a.booktitle
* CSS selector for element(s) to remove - n/a idgaf tbh i just wanna read ink indle even with stupid text

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

### If you don't have developer skills, can you ask a friend who does have them if they can do it for you?
I have finals in 6 days on 27th .if i ask they will think I'm crazy

**Comment by gamebeaker** [comment]
@dteviot Hint: I think it is the LightNovelWorldParser.js

**Comment by dteviot** [comment]
@chaitanya44444 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://lightnovelpub.fan/novel/the-beginning-after-the-end-web-novel-10021224, chapters 1 and 422

For my notes: 6 minutes work

@gamebeaker 
> I think it is the LightNovelWorldParser.js

You are correct.  Thank you for that, saved me 15 to 30 minutes to find the right parser.  Any tips on how you recognized it?

**Comment by chaitanya44444** [comment]
Thanks alot

**Comment by gamebeaker** [comment]
@dteviot i have no tips. I just recognized the name and layout of the page.

**Comment by dteviot** [comment]
@chaitanya44444 
Reopening, so I know to notify you when version in Chrome and Firefox store is updated

**Comment by dteviot** [comment]
@chaitanya44444 
Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
