### ISSUE TITLE
WebToEpub not working anymore on https://noblemtl.com/

### ISSUE THREAD

**Issue by aelementj** [dteviot/WebToEpub#927]
The extension was working fine on [https://noblemtl.com/](url) the past cause I've already created several epubs from the site but now all i get is an error

Using [https://noblemtl.com/series/damn-system/](url) as an example:
![IMG_20230222_084716](https://user-images.githubusercontent.com/91315507/220492006-9717a961-e532-4c16-88c1-e314d215144f.jpg)
![IMG_20230222_084741](https://user-images.githubusercontent.com/91315507/220492011-34762f2b-830e-4986-ad05-d20f00043416.jpg)
![IMG_20230222_084801](https://user-images.githubusercontent.com/91315507/220492015-d6106253-c728-4776-94ac-0b0cc5e23fe5.jpg)
This was performed on a mobile device on Kiwi Browser

The file that was downloaded was an empty epub

**Comment by dteviot** [comment]
@aelementj 
I think you're running into the Cloudflare anti-scrape system.
You need to use your browser (without opening WebToEpub), until you get the Cloudflare page "checking connection/security" page.  Then you may have to click the "I'm a person button".  After that WebToEpub should work.

**Comment by aelementj** [comment]
I tried your solution and it actually worked! Also, i think i had a fault in this because i wasn't on "desktop site" mode when on the novel list. Verification wasn't triggered so maybe that's the reason i wasn't able to make an epub in the first place. Thanks for solving my problem
