### ISSUE TITLE
Please add site libri7.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#929]

**Comment by dteviot** [comment]
@AngelBurn 

**Note, to get WebToEpub to find chapters, you will need to click on "Contents" to get page to load chapters before opening WebToEpub.**

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://libri7.com/book/13088/Mated-to-the-Golden-Dragon, chapter 1
* https://libri7.com/chapters/11016/Billionaire's-Reborn-Baby, chapter 1

For my notes: 
This was thoroughly unpleasant.
* HTML pages are lacking the contentType header.
* Content of the &lt;p&gt; element is malformed.

92 minutes work

**Comment by dteviot** [comment]
@AngelBurn 
Reopen, so I know to notify you when Chrome and Firefox stores updated.

**Comment by dteviot** [comment]
@AngelBurn 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
