### ISSUE TITLE
Royalroad.com stopped working for me

### ISSUE THREAD

**Issue by Zewalla** [dteviot/WebToEpub#930]
When using Webtoepub for royalroad.com it spits out error now instead of working properly as it did 4 days ago.

To reproduce simply try to use the plugin on a story on RR
Example:
1. Go to 'https://www.royalroad.com/fiction/39408/beware-of-chicken'
2. Click on the webtoepub plugin
3. In the new tab thats opened read the error:
"
TypeError: Cannot read properties of null (reading 'textContent')
    at RoyalRoadParser.extractDescription (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/RoyalRoadParser.js:98:65)
    at RoyalRoadParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:275:37)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:237:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)
"

![image](https://user-images.githubusercontent.com/126287152/221277428-0280e1c1-47b7-4a45-8534-540324977661.png)

 - OS: Windows10
 - Browser chrome
 - Ver. 110.0.5481.178

I am very new to Github and to your wonderful tool. But i know your parser is supposed to work for Royalroad? Right? I'm utterly confused and wanted to report this. Anyone else having similar issues?

**Comment by gamebeaker** [comment]
@dteviot Hint: RoyalRoadParser.js line 92-99

`

    extractSubject(dom) {
        let tags = ([...dom.querySelectorAll("span.tags .label")]);
        return tags.map(e => e.textContent.trim()).join(", ");
    }

    extractDescription(dom) {
        return dom.querySelector("div .description").textContent.trim();
    }
`

**Comment by gamebeaker** [comment]
@dteviot Hint: RoyalRoadParser.js line 71-99

`

    extractTitleImpl(dom) {
        return dom.querySelector("div.fic-header div.col h1").innerText.trim();
    }

    extractAuthor(dom) {
        let author = dom.querySelector("div.fic-header h4 span a");
        if (author === null) {
            return super.extractAuthor(dom);
        }
        author = author.innerText.trim();
        return author;
    }

    extractSubject(dom) {
        let tags = ([...dom.querySelectorAll("span.tags .label")]);
        return tags.map(e => e.textContent.trim()).join(", ");
    }

    extractDescription(dom) {
        return dom.querySelector("div .description").textContent.trim();
    }
`

**Comment by TheSystemChange** [comment]
I am also having this problem.
![firefox_8Qs1q51YQp](https://user-images.githubusercontent.com/126322328/221350269-eb03716a-fb63-4f13-ba64-eaa110da2b3c.png)


- OS: Windows10
- Browser Firefox
- 110.0 (64-bit)

**Comment by Cronan1897** [comment]
I am having the same issue too, so it's not just me

**Comment by Cronan1897** [comment]
Got it

That said, just want to show this, to maybe show the specific problem, admittedly I have pretty much no idea what this stuff means

TypeError: Cannot read properties of null (reading 'textContent')
at RoyalRoadParser.extractDescription (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/RoyalRoadParser.js:98:65)
at RoyalRoadParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:275:37)
at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:237:9)
at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Comment by gamebeaker** [comment]
royalroad.com updated their website and now WebToEpub is unable to get infos like Autor etc. .

**Comment by Cronan1897** [comment]
was that update on purpose to avoid letting webtoepub be usable? Or just a
side effect?

**Comment by gamebeaker** [comment]
@Cronan1897 i think side effect.

**Comment by Cronan1897** [comment]
Okay, hopefully this can be fixed soon

**Comment by Landrovan** [comment]
For info: I replace the extractDescription function to simply return "Description". Correct the error, and was able to use it without any other change. So there is no error after that one.

**Comment by Cronan1897** [comment]
You can do that?

**Comment by gamebeaker** [comment]
I uploaded a hot fix version here (is 2 commits behind ExperimentalTabMode): https://mega.nz/folder/tV4i2RRZ#S_CVSpZ-o5lQ9lAiFTmtZw . Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers .

**Comment by Cronan1897** [comment]
Thanks, I will try later, for now I put 1Focus on for a few hours, so can’t
try RoyalRoad so as to avoid distractions from my workout and artwork
attempts

Thank you for your help dude, with Amazon making it harder, I really think
we need a way to keep info, even fiction en masse from disappearing or
being locked forever

**Comment by Cronan1897** [comment]
Sorry, still doesn't seem to work[image: Screen Shot 2023-02-26 at
07.01.07.png]

**Comment by Cronan1897** [comment]
It seems to work just fine with scribblehub still, though

**Comment by lll000111** [comment]
@Cronan1897 

Well of course it does, why wouldn't it? The bug report is for RoyalRoad! What does some other website have to do with it? It has its own recipe for parsing.

This is a bug report and not a chat room guys. Bug report has been filed, you can submit a PR, or add substantial new information, but all this chatting is just making the life of the ACTUAL maintainer(s) harder.

**Comment by Cronan1897** [comment]
Forgot to mention, it’s not working on RoyalRoad still

**Comment by Cronan1897** [comment]
Also, can't unpack 0.0.0.152.chrome

**Comment by Cronan1897** [comment]
can't unzip extension for installation

**Comment by Cronan1897** [comment]
Works, managed to somehow get it right

@gamebreaker

Thanks dude, I'm sorry for the bother

**Comment by dteviot** [comment]
@zewalla @gamebeaker @TheSystemChange @Cronan1897 @Landrovan @lll000111

Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Copies of released versions for Firefox and Chrome are uploaded to https://github.com/dteviot/WebToEpub/releases. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 93 minutes work.  (Sigh, so much paperwork to do a submission.)

**Comment by Cronan1897** [comment]
Thanks again dude
