### ISSUE TITLE
Please add site https://kemono.party

### ISSUE THREAD

**Issue by ghost** [dteviot/WebToEpub#932]
Could you add kemono.party for cases like this link:
https://kemono.party/patreon/user/5149963?q=Breaking+providence
Where there are stories, but when I try to use with web to epub it takes the entire page with the links and all, 
And creates much space from the titles to the content and files,so I want to know if could make to web to epub just consider content and files area when making the epub and if you make so that the title of the chapter much away from the content

**Comment by dteviot** [comment]
@PHBN2021 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kemono.party/patreon/user/5149963?q=Breaking+providence

For my notes: 37 minutes work

**Comment by PHBN2021** [comment]
The extension works when there is more than one page to pull the links, but if there is only one page it crashes without taking a single link, like in cases like: https://kemono.party/fanbox/user/31988653?q=Fanfiction%3A+Teacher+and+student

**Comment by dteviot** [comment]
@PHBN2021 

Fixed.  I think.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kemono.party/fanbox/user/31988653?q=Fanfiction%3A+Teacher+and+student

For my notes: 10 minutes work

**Comment by Juts2** [comment]
That site is a compiler of stolen patreon content and probably should not be supported.

**Comment by dteviot** [comment]
@xypha 

Going to call this done

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
