### ISSUE TITLE
Fix warnings raised by Mozilla

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#933]
Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.

js/Library.js line 324 column 13
Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.

js/Library.js line 436 column 9
Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.

js/Library.js line 533 column 9
Unsafe assignment to innerHTML
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.

js/Library.js line 650 column 9

**Comment by dteviot** [comment]
@gamebeaker 
Can you look into these?  Mozilla hasn't rejected it outright yet, but it may not get approved with them.

**Comment by dteviot** [comment]
@gamebeaker 
Mozilla have approved, but I'd like it fixed for next commit.  Basically, need to build the XML using createElement() and similar calls.  See [o EpubPacker.js](https://github.com/dteviot/WebToEpub/blob/master/plugin/js/EpubPacker.js) for examples

**Comment by gamebeaker** [comment]
@dteviot i am going to look into it.

**Comment by gamebeaker** [comment]
@dteviot how were you able the get these warnings? If i load WebToEpub in firefox for debugging i don't see warnings. I just want to be able to check if my fix works.

**Comment by gamebeaker** [comment]
@dteviot i was able to get the warnings with the command "web-ext lint". How to install web-ext is described here https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/

**Comment by dteviot** [comment]
@gamebeaker 
Thank you for that
