### ISSUE TITLE
Is it possible to move the footnotes (in tooltip tags) to the very bottom of chapters for the site [https://peachblossomcodex.com/]?

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#934]
Hello!

This site is a bit like ChrysanthemumGarden with how they do footnotes since they use the "tooltip" function as well. But unlike ChrysanthemumGarden, when WebToEpub packs the EPUB file, the footnotes that are generated are actually written within the chapter text itself. The footnotes don't appear in the paragraphs per se, but they're hidden within <span> tags throughout the chapter. Sometimes there are also **images within these footnote tags** as well. I was wondering if it was possible to have WebToEpub generate these footnotes at the bottom of the chapter like ChrysanthemumGarden as well? Apologies for the poor explanation. I'll try to use an example to elaborate  a bit...

The reddish coloured text in the below image that is underlined red is the text that has a footnote (clicking on that text makes the black box appear overhead with the respective footnote's explanation):

<img width="619" alt="image" src="https://user-images.githubusercontent.com/55352222/221405063-b3b41862-20a4-4fc6-912f-89835bfd52ec.png">

Then when WebToEpub packs the EPUB, the "footnote's explanation" appears **within the chapter text** right next to the actual words that is being explained, like below:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/55352222/221405157-ea97befe-9b30-4fc2-99ff-b5bad1673c83.png">

The text underlined red in the second image would be the **pink text from the website itself that has a footnote**, and the pink underlined text is the footnote explanation in the tooltip black box that appears overhead the pink text on the website.

Ah and just for reference, this is the chapter used specifically for the above example:
**https://peachblossomcodex.com/novel/bsdtwtbav/bsdtwtbav-ch-7/**
TOC: https://peachblossomcodex.com/novel/bsdtwtbav/

Apologies again for the inconvenience. And thank you very much for all that you've done!

**Comment by dteviot** [comment]
@vanessabluellie 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://peachblossomcodex.com/novel/bsdtwtbav/bsdtwtbav-ch-7/

For my notes: 33 minutes work

**Comment by vanessabluellie** [comment]
Thank you very much!!! It worked perfectly as always! :)

**Comment by dteviot** [comment]
@vanessabluellie 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
