### ISSUE TITLE
Empty titles causing RSC-005 epub validation failures

### ISSUE THREAD

**Issue by b3nw** [dteviot/WebToEpub#935]
If unable to parse a title, add something to the <title></title> to prevent epub validation failure RSC-005

**Comment by dteviot** [comment]
@b3nw 
Which title are you referring to?  The book as a whole, or title of chapters?
Ideally, please provide URL to site with issue.

**Comment by dteviot** [comment]
@b3nw 
Copy of failing epub would also be helpful

**Comment by b3nw** [comment]
``` https://travistranslations.com/novel/67619/sex-dungeons%e3%80%80-a-dungeon-has-appeared-in-the-basement-of-our-house-where-h-times-level/#toc ```

epub generated: https://drive.google.com/file/d/1iJAWIcuIeTPyX8oiDTa1vVcOsiZCCyFU/view?usp=share_link

```
<html>
<body>


ERROR | RSC-005 | /OEBPS/Text/0005_Vol_1_Chapter_5.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
-- | -- | -- | --
ERROR | RSC-005 | /OEBPS/Text/0006_Vol_1_Chapter_6.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0007_Vol_1_Chapter_7.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0008_Vol_1_Chapter_8.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0009_Vol_1_Chapter_9.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0010_Vol_1_Chapter_10.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0011_Vol_1_Chapter_11.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0012_Vol_1_Chapter_12.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0013_Vol_1_Chapter_13.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0014_Vol_1_Chapter_141.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/Text/0015_Vol_1_Chapter_142.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/toc.ncx (line 1, col 123) | Error while parsing file: value of attribute "xml:lang" is invalid; must be an RFC 3066 language identifier
ERROR | RSC-005 | /OEBPS/Text/Cover.xhtml (line 1, col 110) | Error while parsing file: Element "title" must not be empty.
ERROR | RSC-005 | /OEBPS/toc.xhtml (line 1, col 154) | Error while parsing file: value of attribute "xml:lang" is invalid; must be an RFC 3066 language identifier or must be equal to ""
ERROR | RSC-005 | /OEBPS/toc.xhtml (line 1, col 154) | Error while parsing file: value of attribute "lang" is invalid; must be an RFC 3066 language identifier or must be equal to ""


</body>
</html>


```

**Comment by gamebeaker** [comment]
@b3nw which epub viewer do you use? With Calibre i don't have a problem to view it.

**Comment by dteviot** [comment]
@b3nw 
It looks like WebToEpub has never populated the &lt;title&gt; element.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://travistranslations.com/novel/67619/sex-dungeons%e3%80%80-a-dungeon-has-appeared-in-the-basement-of-our-house-where-h-times-level/

For my notes: 38 minutes work

**Comment by b3nw** [comment]
this resolved the errors, thanks!

**Comment by dteviot** [comment]
@b3nw
Reopen, so I know to notify you when version in Chrome and Firefox stores is updated.

**Comment by dteviot** [comment]
@b3nw 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
