### ISSUE TITLE
0.0.0.152 appears to be completely nonfunctional on Fennec 110.0.1

### ISSUE THREAD

**Issue by LongFluffDragon** [dteviot/WebToEpub#936]
**Describe the bug**
Opening the addon from any table of contents page fails to load. The addon is unresponsive, shows only placeholder labels, with __MSG_Searching_For_URLs_Please_Wait__ displayed. It never times out and all buttons are nonfunctional.

**To Reproduce**
Open https://www.royalroad.com/fiction/31429/cinnamon-bun or https://wanderinginn.com/table-of-contents/
Open Addons -> WebToEpub
Observe failure to load

**Expected behavior**
Less failure to load. Both sites worked fine with this addon in the same browser prior to the update

**Screenshots**
Resulting page: https://i.imgur.com/jiEGtXY.png

**Smartphone (please complete the following information):**
 - Device: Pixel 3A XL
 - OS: Android 11
 - Browser Fennec F-Droid
 - Version 110.0.1

**Additional context**
The latest version of the addon continues to work fine in the latest desktop firefox. Unable to test on tablet devices due to browser UI issues.

**Comment by bootless-corpse** [comment]
Same issue using Firefox nightly

**Comment by dteviot** [comment]
@bootless-corpse 
Is this desktop or mobile Firefox?

**Comment by bootless-corpse** [comment]
Android Firefox

**Comment by gamebeaker** [comment]
@bootless-corpse can you please share the "Custom Add-on collection" you use.

**Comment by bootless-corpse** [comment]
I'm not sure 100% how to do that. I made my own collection with just the web to epub add-on. I think it's might be this 17305934 but let me know if I'm wrong lol.

**Comment by gamebeaker** [comment]
@dteviot i was able to debug it on firefox android. If the commit fe8e8cc is reverted it works again. 
@bootless-corpse @LongFluffDragon if this doesn't get fixed i would recomend using kiwi browser or other chromium based mobile browser.

**Comment by dteviot** [comment]
@gamebeaker 
Thanks for the fixes.  

@bootless-corpse @LongFluffDragon 
Updated version (0.0.0.153) has been submitted to Firefox store and is available now.
