### ISSUE TITLE
hostednovel capped at 200 chapters

### ISSUE THREAD

**Issue by snappyjel** [dteviot/WebToEpub#938]
**Describe the bug**
So, I tried using this to scrape a webnovel in https://hostednovel.com/, it work great with only 1 problem. The novel I tried to make an epub has 397 chapters right now, but the extension only shows up to 200 chapters.

**To Reproduce**
1. Go to (https://hostednovel.com/novel/im-really-not-the-demon-gods-lackey)
2. Click on WebToEpub icon on toolbar
3. Saw chapter list from 1 to 200

**Expected behavior**
I checked the Advanced Version and the default setting is set to 10.000 max chapters per epub, so clearly 397 chapters should be fine.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Latest

**Comment by dteviot** [comment]
@snappyjel 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://hostednovel.com/novel/im-really-not-the-demon-gods-lackey

For my notes: 13 minutes work

**Comment by snappyjel** [comment]
Work flawlessly, thank you for the quick response and the amazing work.

**Comment by dteviot** [comment]
@snappyjel
Reopen so I know to tell you when version in Chrome and Firefox stores updated.

**Comment by snappyjel** [comment]
Sure, sorry for closing it too fast

**Comment by dteviot** [comment]
@snappyjel 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
