### ISSUE TITLE
Please add site https:bookalb.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#941]
https://bookalb.com/category/ouch-my-ceo-fiance-fell-for-his-maid-by-lisa-salman

Thank you!

**Comment by dteviot** [comment]
@AngelBurn 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://bookalb.com/category/divorce-anxiety/, chapters 1 and 503

For my notes: 51 minutes work

**Comment by dteviot** [comment]
@AngelBurn 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
