### ISSUE TITLE
Overlapping image on top of "Copy URL"

### ISSUE THREAD

**Issue by MohamadTaher** [dteviot/WebToEpub#943]
**Describe the bug**
I will just post the screenshot to show the problem. This only happens if I change the cover to something new.

**To Reproduce**
Steps to reproduce the behaviour:
1: just change the cover to a new image from the web. Try different images with different sizes.

**Screenshots**
![Screenshot 2023-03-17 054645](https://user-images.githubusercontent.com/67930481/225897129-272d42ff-39d4-4977-b36c-e2d46a2cf7c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version [e.g. 22]: latest version.

**Comment by dteviot** [comment]
Notes.

Can reproduce something like this by using https://www.royalroad.com/fiction/65458/legend-of-yuki-the-wrath-of-the-tailed-asura as title, and https://images.unsplash.com/photo-1533282960533-51328aa49826?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8d2lkZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60 as image.

After spending hour on it, have no idea how to fix, as max-width does not work.
Looks like the image is abusing the table layout, by being in 3rd column, which nothing else uses. (I think).

**Comment by gamebeaker** [comment]
@dteviot which max-width did you use?
If you change min-width (line 195) to max-width it works for me. Or did i miss something?
https://github.com/dteviot/WebToEpub/blob/ea41bfe8e927d84182930196d573858bc4f8aaca/plugin/css/default.css#L193-L199

**Comment by dteviot** [comment]
@gamebeaker 
> If you change min-width (line 195) to max-width it works for me

D'oh! I was using max-width: auto.
Which is not going to work.  That will teach me to try copy-paste from an internet tutorial.

**Comment by dteviot** [comment]
@MohamadTaher 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* See prior notes in issue

For my notes: 75 minutes work

**Comment by MohamadTaher** [comment]
@dteviot 
Not working at all now if you try to change the image:

![Screenshot 2023-03-21 001907](https://user-images.githubusercontent.com/67930481/226531940-7478418a-2b5e-487a-b3a9-0ef7cfe7a999.png)

**Comment by dteviot** [comment]
@MohamadTaher 
I just tried
* https://www.royalroadcdn.com/public/covers/AADAe2qgBBM.png?time=1678334712
* https://images.unsplash.com/photo-1533282960533-51328aa49826?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8d2lkZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60

They seem to work fine.
![image](https://user-images.githubusercontent.com/5157081/226534947-2622f4e2-bead-41fe-9b4f-68e409ae1fe9.png)
![image](https://user-images.githubusercontent.com/5157081/226535021-05cdfaf6-5cd9-4601-818a-bc944024a817.png)

1. What happens if you try them?
2. What's the full URL of the image in the screenshot you supplied?

**Comment by dteviot** [comment]
@MohamadTaher, @gamebeaker 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
