### ISSUE TITLE
Goodnovel.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#947]
Please check Goodnovel

I cant convert the stories bot in PC and android

**Comment by dteviot** [comment]
@AngelBurn 

Site has changed layout, requiring a new parser.
As site seems to offer download as PDF (see screenshot below) I'm not interested in providing a parser for WebToEpub.
Have removed Goodnovel parser from WebToEpub.

![image](https://user-images.githubusercontent.com/5157081/227753358-6f9995ce-9c08-40d3-929e-0ee1973bd205.png)

For my notes: 45 minutes work  (mostly trying to get new parser to work)

**Comment by mian196** [comment]
It does not support downloading pdf now please add support for this site
