### ISSUE TITLE
Chapters capped on lightnovelpub.com

### ISSUE THREAD

**Issue by etn3912** [dteviot/WebToEpub#949]
**Describe the bug**
The chapters on lightnovelpub are capped at 200 chapters for a novel with with less than 400 chapters, and for a novel more than 400 chapters, the first and last 100 chapters are selected.

**To Reproduce**
1. Go to 'lightnovelpub.com'
2. Click on 'Hero of Darkness' or 'Immortal In The Magic World'
3. Click on WebToEpub

**Expected behavior**
For Immortal In The Magic World WebToEpub grabs only chapters 1 to 200. For Hero of Darkness WebToEpub grabs only  160 chapters; the first 100 chapters (1 - 100 ) and the last 60 chapters (801 - 860).

**Screenshots**
![Issue 1](https://user-images.githubusercontent.com/78277606/228131107-b21eac47-6eca-4d06-9ff0-8a122f7437d5.jpg)
![Issue 2](https://user-images.githubusercontent.com/78277606/228131109-e9c42146-e95d-4017-b4ab-870e20b06792.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [111.0.5563.111]

**Additional context**

**Comment by dteviot** [comment]
@etn3912 @zeoint 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.lightnovelworld.com/novel/i-stayed-at-home-for-a-century-when-i-emerged-i-was-invincible-28032201  (694 chapters)
* https://www.lightnovelworld.com/novel/marvel-game-maker-system-28032205 (96 chapters)
* https://www.lightnovelpub.com/novel/immortal-in-the-magic-world-28032202 (310 chapters)
* https://www.lightnovelpub.com/novel/hero-of-darkness-24032048 (860 chapters)
* https://novelpub.com/novel/jackal-among-snakes-28032202 (306 chapters)

For my notes: 41 minutes work

**Comment by John17880** [comment]
Could you remove the watermarks again as you did previously in issue <a href="https://github.com/dteviot/WebToEpub/issues/869">#869</a>?

**Comment by FrostDuchess** [comment]
@dteviot Can you add the bug fixed version to the firefox addon too? 

thanks so much

**Comment by dteviot** [comment]
@John17880 
>Could you remove the watermarks again as you did previously in issue https://github.com/dteviot/WebToEpub/issues/869?

Please provide URL of chapter with watermark, plus description of watermark (e.g. the text I'm looking for)

**Comment by dteviot** [comment]
@FrostDuchess 
>Can you add the bug fixed version to the firefox addon too?

I'm not sure what you're asking.  The Firefox version at  https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing should have the fix.

**Comment by FrostDuchess** [comment]
> @FrostDuchess
> 
> > Can you add the bug fixed version to the firefox addon too?
> 
> I'm not sure what you're asking. The Firefox version at https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing should have the fix.

I'm sorry I didn't clarify, I'm using the one from google drive already but i have to reinstall the fixed version everyday for some reason but when the addon is updated in the addon store all changes always stick without me having to do daily a reinstall 

again thank you for replying and sorry for bugging you

**Comment by dteviot** [comment]
@FrostDuchess 
You need to reinstall because the version on Google Drive is not signed, So Firefox won't keep it loaded.
Currently I have RL issues, so no time.  Might be a few weeks before I can get around to this.

**Comment by dteviot** [comment]
@FrostDuchess @John17880 @etn3912 @zeoint 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
