### ISSUE TITLE
Not reading other chapters 

### ISSUE THREAD

**Issue by ManhwaSReader** [dteviot/WebToEpub#951]
**Describe the bug**

**To Reproduce**
1. Go to 'lightnovelpub.com'
2. Click on 'webtoepub'
3. Scroll down to 'half of the chapter'

**Expected behavior**
The extension is working but when i want to melt 300+ chapters (estimation) it will skip other chapters ex: i want to melt 1000 chapter but it'll only show 1-100 then skip to 900-100 there's no 101-800

**Screenshots**
![Screenshot_2023-04-02-12-32-07-74_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/113340200/229331470-452719ac-3fb2-444e-9cb0-fb922d4da475.jpg)

**Desktop (please complete the following information):**
 - android [e.g. iOS]
 - Kiwi browser [e.g. chrome, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dteviot** [comment]
@ManhwaSReader 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Currently I have RL issues, so no time. Might be a few weeks before I can get around to updating version in Goggle/Firefox stores

**Comment by dteviot** [comment]
@ManhwaSReader @John17880 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
