### ISSUE TITLE
Remove: Multiple Chapter Header Titles

### ISSUE THREAD

**Issue by ParsingNoob** [dteviot/WebToEpub#955]
I have no clue if this has been talked about, from searching the web, I haven't seen anything related to it, so I decided to put in a request to the guy that makes the app in the first place. If this is a redundant request, I apologize in advance.

As I'm sure some of you are aware, many websites like putting double titles per chapter and WebToEpub pulls it. As I'm not at all computer inclined when it comes to these kinds of things, I was hoping it would be possible for a simplified method to be included to exclude the multiple chapter header/titles that get pulled. As an example, I uploaded a ZIP of a web novel I made with the app and left it as is to illustrate what I mean. Again, if this was easily avoided with some tampering with the current app, or if it's redundant at all, I apologize. 

[Tales of Herding Gods  Final Volume.zip](https://github.com/dteviot/WebToEpub/files/11182206/Tales.of.Herding.Gods.Final.Volume.zip)

**Comment by dteviot** [comment]
@ParsingNoob 
Unfortunately, this is difficult to do in the general case.  
It's not helped that sites are not consistent.  Some sites are not consistent between chapters of the same story.

I *think* there's some code to catch duplicate titles in the simplest cases.
This request has come up in the past.  However, given a choice between having chapters with two copies of the title, and no title, the two copies is the preferable option.
