### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by JoshOm21** [dteviot/WebToEpub#956]
**Is your feature request related to a problem? Please describe.** nope

**Additional context**
I just want to ask if this works for manga websites too. Or this is just only for novels? Thank you.

**Comment by dteviot** [comment]
@JoshOm21 
It works for some.
You'll just have to try and see if it works for the ones you want.

**Comment by JoshOm21** [comment]
Ok. Thank you.

Do you also accept a request for a new source that is a manga website?

**Comment by dteviot** [comment]
@JoshOm21
Make a request and I'll take a look.
I can't promise anything, and currently I have RL issues, so no time.  Might be a few weeks before I can look into it.
