### ISSUE TITLE
Missing some Content in PandaNovel Chapter

### ISSUE THREAD

**Issue by SirRomey** [dteviot/WebToEpub#958]
**Describe the bug**
When downloading from panda-novel.com, some or two paragraphs in the center gets skipped for some reason.

**To Reproduce**
1. Download any novel from panda-novel. Tested with https://www.panda-novel.com/content/the-innkeeper(DN1)-1462-1072910/chapter-1 

Note: I noticed this in some of the other novels as well but I realized it only towards the later chapters and cannot confirm if it's a recurring issue.

**Expected behavior**
Should download chapters with all content intact in every chapter.

**Screenshots**
![image](https://user-images.githubusercontent.com/71877936/230970973-5ceceeb1-9d21-44d5-bb9c-71a7cf281a1c.jpeg)
![image](https://user-images.githubusercontent.com/71877936/230971415-a0ccd7ce-8fd6-492a-99ae-c02ba993233d.png)

**Desktop (please complete the following information):**
 - OS: Latest MacOS
 - Browser: Brave Browser 
 - Version: 0.154 (the one you provided in another issue)

**Additional context**
Not the first time I've noticed this issue. This time it was obvious because of the missing content being large.

**Comment by dteviot** [comment]
Notes:

Looks like the full text is NOT in the default #novelArticle2 element.  Instead it's buried in one of the &lt;script&gt; tags.
Also, the missing chapter's text is not wrapped in a &lt;p&gt; tag, so when converting to XHMTL, its stripped out.
I think I've got a fix, unfortunately, Panda-Novel has now locked me out.  So, will need to finish this later.

For my notes: Time spent so far 174 minutes.

**Comment by dteviot** [comment]
@SirRomey 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.panda-novel.com/content/the-innkeeper(3)-1462-1072910/chapter-1

Note, you didn't tell me of any other chapters with same problem.

For my notes: Total time 200 minutes work

**Comment by SirRomey** [comment]
Can confirm fixed, thanks.
