### ISSUE TITLE
Firefox Nightly issue 

### ISSUE THREAD

**Issue by Quaturn** [dteviot/WebToEpub#96]
Addon stopped working in Firefox Nightly 53.0a1 (2016-12-19) (64-bit) and I do not know why. It works normally on Firefox, Firefox beta and Firefox Developers edition it is just Nightly editions where it stopped working.

To be more precise it downloads pages but when it comes to final packing of the Epub it is stuck in loading mode and it does not pack and offer file for download.

**Comment by dteviot** [comment]
@Quaturn
>To be more precise it downloads pages but when it comes to final packing of the Epub it is stuck in loading mode and it does not pack and offer file for download.

I think you mean, the "Save As" dialog does not appear.

Please raise this as a bug on https://bugzilla.mozilla.org/ and add the issued bug number here.  You'll need to add to the report that the following is the code that tries to write a file to the local system, using "download", and it is invoked in the "then" part of a promise.  (i.e., it's not running in the main thread)
```javascript
    // write blob to "Downloads" directory
    static save(blob, fileName) {
        var clickEvent = new MouseEvent("click", {
            "view": window,
            "bubbles": true,
            "cancelable": false
        });
        var a = document.createElement("a");
        let dataUrl = URL.createObjectURL(blob);
        a.href = dataUrl;
        a.download = fileName;
        a.dispatchEvent(clickEvent);
    }
```

**Comment by toshiya44** [comment]
Have you tried turning off e10?

**Comment by Quaturn** [comment]
@toshiya44 you were right once I turned Multi-Process (e10) off it started working

**Comment by dteviot** [comment]
Interesting.
If problem is electrolysis (e10) then should be able to reproduce in the release build by turning it on.
I currently have release build 50.1.0 installed.
According to https://wiki.mozilla.org/Electrolysis, can check if e10 is active by 
> Check about:support and look for a number higher than 0 in the "Multiprocess Windows" entry.

I do this, and I see: "1/1 (enabled by default)"  So I think e10 is on.
I try running WebToEpub.  The "Save As" dialog appears, but the filename shown is completely wrong, and the file is saved to downloads with yet another name.  Examination of file shows it is a valid epub, so it seems just the filename is scrambled.
I'll see if I can't put together a minimal test case to reproduce and submit a bug report to Mozilla.

**Comment by dteviot** [comment]
Additional, firefox console log has following.
> 1482610120174	addons.webextension.WebToEpub@Baka-tsuki.org	WARN	Loading extension 'WebToEpub@Baka-tsuki.org': Reading manifest: Error processing minimum_chrome_version: An unexpected property was found in the WebExtension manifest.
1482610120174	addons.webextension.WebToEpub@Baka-tsuki.org	WARN	Loading extension 'WebToEpub@Baka-tsuki.org': Reading manifest: Error processing minimum_firefox_version: An unexpected property was found in the WebExtension manifest.
1482610120195	addons.webextension.WebToEpub@Baka-tsuki.org	WARN	Please specify whether you want browser_style or not in your browser_action options.
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIAnnotationService.setPageAnnotation]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://app/modules/DownloadsCommon.jsm :: onDownloadChanged :: line 781"  data: no]  (unknown)

**Comment by dteviot** [comment]
Good news and bad.
Good News: I can fix the problem by using the downloads.download() API.
Bad News: Chrome version https://developer.chrome.com/extensions/downloads#method-download isn't 100% compatible with Firefox https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download
Really Bad News: Firefox version doesn't implement saveAs until version 52.

On the other hand, 52 should be version where Electrolysis is on be default, so can add the code then.
Changes.
1. add "downloads" to permissions in manifest.
2. change save() in EpubPacker to
```javascript
    static save(blob, fileName) {
            let options = {
            url: URL.createObjectURL(blob),
            filename: fileName,
            saveAs: true
        };
        if (typeof(browser) === "undefined") {
            // chrome version
            chrome.downloads.download(options);             
        } else {
            // firefox version
            browser.downloads.download(options);
        }
        EpubPacker.scheduleDataUrlForDisposal(dataUrl);
    }
```

**Comment by dteviot** [comment]
@toshiya44, @Quaturn
Now that Firefox 53 has been released, I've updated the code on the Experimental Tab branch so 
SaveAs dialog now appears on Firefox without needing to disable Electrolysis.
