### ISSUE TITLE
Is it possible to empty the <title></title> tags for novels generated at this site?

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#961]
Hello!

I've noticed a recent minor inconvenience with novels that are generated from the site [https://chrysanthemumgarden.com/]. After the latest update with WebToEpub, all EPUBS packed from this site now also have the **chapter title encased in the <title></title> tags** as well. But all previous versions of WebToEpub had left the <title></title> tags completely empty, which was more cleaner and less cluttered. Is it at all possible to maybe revert this so that the chapter titles and/or novel name aren't saved into the <title> tags anymore please? For a little reference (due to my lacking explanation), here's an image of the before & after:

The text underlined with red is the text in the <title> tags that used to be left empty, and the text underlined in pink is the chapter title in the heading tags.

![image](https://user-images.githubusercontent.com/55352222/231423940-85194526-ad09-410b-a5c5-2601884d07e9.png)

This is what it previously was like:

![image](https://user-images.githubusercontent.com/55352222/231424986-6e838223-225b-4ed6-af2e-4b47f31b8503.png)

Ah and also, I've also noticed one more thing, but for some reason, when WebToEpub saves the Table of Contents at this site, the **First Chapter Link of the TOC is never saved** into the EPUB's Table of Contents xhtml file... I'm not sure if this is a bug and if it can perhaps be amended somehow? Apologies for the inconveniences my request may have caused.

Thank you very much for your time and effort, as always!! :)

**Comment by dteviot** [comment]
@vanessabluellie 
Strictly speaking, the &lt;title&gt; element should not be empty.
See: https://github.com/dteviot/WebToEpub/issues/935
If you want to strip the text out, you could use EpubEditor to do it.

As regards the missing first chapter link, I'll look into when I have time.  Unfortunately RL issues mean it may be some weeks before I'm free.

**Comment by vanessabluellie** [comment]
> @vanessabluellie Strictly speaking, the <title> element should not be empty. See: #935 If you want to strip the text out, you could use EpubEditor to do it.

This is perfectly fine~ :) But may I ask how to do this through EpubEditor. I tried to use the option labelled **"Delete elements matching CSS"** and inputed the **tag "title"** in it, hoping to get the desired outcome (of emptying but preserving the tags). But it didn't only delete the contents encased in the <title></title> tags as it also deleted the <title> tags entirely with it... Although I suppose I can use Calibre to re-insert the <title> tags, is there perhaps another way to use EpubEditor to maybe empty the tags without deleting the tags itself? But there's no rush at all on this! Anytime that is convenient for you to reply is good!

![image](https://user-images.githubusercontent.com/55352222/232202692-0849636e-f186-4bea-af38-59501ec06b88.png)

> As regards the missing first chapter link, I'll look into when I have time. Unfortunately RL issues mean it may be some weeks before I'm free.

That's completely okay!! Hope everything goes well, and though you're very busy, thank you so much for still taking the time to reply! :D

**Comment by dteviot** [comment]
@vanessabluellie 

>  If you want to strip the text out, you could use EpubEditor to do it.

Sorry, I should have been more clear.  I meant, use a script in EpubEditor to modify the Epub.  Like in https://github.com/dteviot/WebToEpub/issues/911
I think the following will do it

```javascript
            for(let p of [...dom.querySelectorAll("title")]) {
                p.textContent = "";
            }
            return true;
```

**Comment by dteviot** [comment]
@vanessabluellie 
Sorry, missed issue with 
> Table of Contents at this site, the First Chapter Link of the TOC is never saved into the EPUB's Table of Contents xhtml file

This is why it's very important to create a new issue for each problem.  Otherwise they tend to get lost.

**Comment by dteviot** [comment]
@vanessabluellie 
Note you're using "Add Page with Chapters to Chapters List".

I think I figured it out.  It's because it's a link to the next chapter in the epub.  So WebToEpub think's it's a "next page/previous page" link, and removing it.

Fixing it is going to get messy.
removeNextAndPreviousChapterHyperlinks() has no idea that it's working on a ToC page, so I'd have to pass that info all the way down the stack.

So, I'm going to decline fixing this.  Sorry.

**Comment by vanessabluellie** [comment]
That's completely okay! Thank you for still providing a script for EpubEditor regarding the first request~ :D
