### ISSUE TITLE
The Addon stops working on https://readhive.org/

### ISSUE THREAD

**Issue by sakuyakudou10** [dteviot/WebToEpub#962]
**Describe the bug**
The addon doesn't work on https://readhive.org/ anymore. It won't load the chapter list and it won't download the chapters even if I input the chapter urls manually.

**Screenshots**
![Screenshot 5](https://user-images.githubusercontent.com/70010148/231668007-25005261-8deb-4c74-b0a1-20ce2495891e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 111.0.5563.149

**Comment by dteviot** [comment]
@sakuyakudou10 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://readhive.org/series/175/#releases  chapter 1, 33
* https://readhive.org/series/25464/ chapter 14, 65

For my notes: 67 minutes work

**Comment by sakuyakudou10** [comment]
Hello, I've tried the test version of the addon and now it works perfectly. Thank you!

**Comment by dteviot** [comment]
@sakuyakudou10 
Reopen, so I know to notify you when Firefox and Chrome stores updated with new version.

**Comment by dteviot** [comment]
@sakuyakudou10 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
