### ISSUE TITLE
[wuxiaworld] Parser removing chapter numbers

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#97]
I noticed that when grabbing www.wuxiaworld.com/wmw-index/ the epub "content" doesn't have the chapter number at the start, just the chapter title. In the TOC it's complete.
I think the number gets removed when cleaning out stuff like previous/next links.

I know wuxiaworld has lots of different formats, but would it be possible to add it? 
Maybe taking it from the chapter name in the TOC, which is always complete (for WMW).

**Comment by dteviot** [comment]
@typhoon71 
Fix has been checked into Experimental Tab branch.
It's grabbing the Title element at the top of the page, which has the chapter number.  (at least for WMW).
This does result in multiple titles for some stories.

As usual, please give it a test and let me know if satisfactory.

**Comment by typhoon71** [comment]
Thanks a lot, this is what I needed, WMW is perfect now (at least for me).

I can't speak for other stories, but I guess it's better having multiple titles on some stories than having some stories with missing chapter numbers/names.

**Comment by dteviot** [comment]
@typhoon71
Can you help?  I got the following request on the Chrome support page.
> somehow I couldn't make epubs from wuxiaworld anymore. it says "Could not find content element for web page" 

I've not been able to reproduce this problem, and I've got no reply from the person who reported the problem.  (The support page for Chrome is crap.  It won't tell me who the person is, nor will it give me their e-mail, so I can't contact them directly.)
Are you having any issues?  
Can you find any chapters where this happens?  (If so, can you send me the chapter URLs?  or at least the Story title.

Thanks,

**Comment by typhoon71** [comment]
Well, as you know I get WMW from wuxiaworld, and it works flawlessy (2 days ago).
I tested it with some other titles and I didn't spot any issue (MGA, Absolute Choice, ... and WMW again)

I do know that WMW has empty link / placeholders in the TOC pages, and when the parser tries to get them it trows an error, but that's OK because everything BEFORE is fetched correctly and packed into the epub.
This can happen if you go to the TOC, hit webtoepub icon and hit the "Pack ebup" button.

Maybe the guy got this for the first time and didn't notice the epub is still properly generated?

Also, do "we" know which version of chrome/addon is he using?

**Comment by typhoon71** [comment]
Oh, it could be they changed the page while the addon was fetching stuff: it happened to me on another site, and on baka-tsuki (remember my "cache" issue?). So I would say it can happen.

**Comment by dteviot** [comment]
@typhoon71 
> Also, do "we" know which version of chrome/addon is he using?

Yes. Version 0.0.0.27

> I do know that WMW has empty link / placeholders in the TOC pages

Thanks, that's probably it.
