### ISSUE TITLE
Please update site https://69shu.com

### ISSUE THREAD

**Issue by Raymond5176** [dteviot/WebToEpub#971]
Hi the current 69shu parser is not working as intended.
The below is the current parser

```javascript
"use strict";

parserFactory.register("69shu.com", function() { return new ShuParser() });

class ShuParser extends Parser{
    constructor() {
        super();
    }

    async getChapterUrls(dom) {
        let tocUrl = dom.querySelector("a.more-btn").href;
        let toc = (await HttpClient.wrapFetch(tocUrl, this.makeOptions())).responseXML;
        let menu = toc.querySelector("#catalog");
        return util.hyperlinksToChapterList(menu);
    }

    findContent(dom) {
        return dom.querySelector("div.txtnav");
    };

    extractTitleImpl(dom) {
        return dom.querySelector("div.booknav2 h1").textContent;
    };

    findCoverImageUrl(dom) {
        return util.getFirstImgSrc(dom, "div.bookbox");
    }

    async fetchChapter(url) {
        // site does not tell us gb18030 is used to encode text
        return (await HttpClient.wrapFetch(url, this.makeOptions())).responseXML;
    }

    makeOptions() {
        return ({
            makeTextDecoder: () => new TextDecoder("gb18030")
        });
    }
}
/
``` 
Is it possible to change the encoder to "gbk" from "gb18030"
(required) CSS selector for element holding content to put into EPUB: ".txtnav"
CSS selector for element(s) to remove: ".txtinfo,#txtright,.bottom-ad"

appreciated as i cant seem to manually create a new template parser to work the job

**Comment by dteviot** [comment]
@Raymond5176 

I tested with https://www.69shu.com/txt/26688.htm, chapter 1. Seems to work fine.
Did you perhaps try opening WebToEpub from one of the other page types?  e.g. the chapter list.  https://www.69shu.com/26688/

> Is it possible to change the encoder to "gbk" from "gb18030"

Encoder is already gb18030, see line 36 in file.

> (required) CSS selector for element holding content to put into EPUB: ".txtnav"

Already there see line 18.

> CSS selector for element(s) to remove: ".txtinfo,#txtright,.bottom-ad"

This, I have done.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.69shu.com/txt/26688.htm, chapter 1.

For my notes: 34 minutes work

**Comment by dteviot** [comment]
@Raymond5176 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
