### ISSUE TITLE
Literotica broken with 0.154

### ISSUE THREAD

**Issue by dra6on1** [dteviot/WebToEpub#978]
Literotica.com broken with 0.154 but works woth 0.152

for example go to 
www.literotica.com/stories/memberpage.php?uid=6952730&page=submissions
try and you get no list of chapters while with 0.152 it works fine

tested on both Firefox and Chrome

**Comment by yoanhg421** [comment]
Let me take a look a it later today or tomorrow.   
The site has so many different lists that is hard to build something that covers everything. 
I didn’t test for that specific URL but it shouldn’t be too complicated.  
I’ll let you know my findings soon.

**Comment by dteviot** [comment]
@yoanhg421 

Thanks.  
Can you please provide URLs to the sorts of pages it does currently work on?

**Comment by yoanhg421** [comment]
@dteviot  

Sure. 
It works here:
https://www.literotica.com/c/non-human-stories
https://www.literotica.com/top/NonHuman-14
https://www.literotica.com/series/se/67670368
https://www.literotica.com/s/literotica-geek-pride-story-event-list

doesn't seem to work on single stories or member submissions :
https://www.literotica.com/s/home-for-horny-monsters-ch-96
https://www.literotica.com/stories/memberpage.php?uid=3816655&page=submissions

**Comment by yoanhg421** [comment]
@dteviot  I have the fix for 
member pages:
<https://www.literotica.com/stories/memberpage.php?uid=3816655&page=submissions>

looking into single pages
<https://www.literotica.com/s/home-for-horny-monsters-ch-96>

**Comment by dteviot** [comment]
@yoanhg421 

Thanks for the fix.

@dra6on1

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* [www.literotica.com/stories/memberpage.php?uid=6952730&page=submissions](http://www.literotica.com/stories/memberpage.php?uid=6952730&page=submissions)

For my notes: 10 minutes work to check and merge

**Comment by dra6on1** [comment]
tested on a couple of different submission pages and now works fine. Thanks.

**Comment by dteviot** [comment]
@yoanhg421 @dra6on1 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
