### ISSUE TITLE
Is it possible to also grab footnotes from this site too please? [https://travistranslations.com/]

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#986]
Hello!

Apologies for another request again so soon, but I was wondering if it was possible to also grab the footnotes from this site [https://travistranslations.com/] as well? This site is just like from issue #934 and #769 as it has hovering footnotes that appear once the cursor hovers over the linked word/s (any text connected to a footnote are underlined throughout the chapter). Would it be possible to also place these respective footnotes at the bottom of the chapter like ChrysanthemumGarden?

Please refer to the below image for reference:

![image](https://github.com/dteviot/WebToEpub/assets/55352222/c1054160-962f-4654-97a3-c4b166da9aad)

The above example was generated from this chapter (+ the TOC of this novel) - 

**Example Chapter (with footnotes):** https://travistranslations.com/novel/19303/a-white-lotus-host-who-does-not-want-to-be-a-white-moonlight-is-not-a-good-host/chapter-1/

**Table of Contents:** https://travistranslations.com/novel/19303/a-white-lotus-host-who-does-not-want-to-be-a-white-moonlight-is-not-a-good-host/

This is because since this specific parser wasn't quite made to grab any footnotes from this site, when the EPUB was generated, the footnote came out as a really long gibberish span tag instead.

![image](https://github.com/dteviot/WebToEpub/assets/55352222/9abf3198-fdb1-4f4e-9d08-f9a4fff8a342)

Ah, and also if it's not too much trouble, whenever an EPUB is generated from TravisTranslations, can there also appear the option to **NOT** grab footnotes as well like for CG and Exiled Rebel Scanlations when the option **"Remove Author Notes"** is checked? Just in case, for the really long novels which have too many footnotes?

Like this?

![image](https://github.com/dteviot/WebToEpub/assets/55352222/1198125c-0238-478d-b00b-c8024b9a8964)

Many apologies again for any inconveniences my requests may cause or disrupt your time. And thank you again for your much appreciated time and efforts thus far! :D

**Comment by dteviot** [comment]
@vanessabluellie 
I can't find the footnote text in the HTML.  I suspect it's encoded as that "string of gibberish" in the span element, and it's not obvious (at least to me) how to decode it.  My initial thought it might be a mixture of HTML and Base64 encoding did not seem to be correct.

**Comment by vanessabluellie** [comment]
Ah, I see! That does seem much too overly complicated. Thank you for looking into my request as always though! :D

**Comment by dteviot** [comment]
@vanessabluellie 
If you can figure out how to get the footnote text, I'll see what I can do.  Otherwise, I'm calling this closed.
