### ISSUE TITLE
Please add site: https://lnreader.org

### ISSUE THREAD

**Issue by elpsycongruent** [dteviot/WebToEpub#987]
What used to be lightnovelreader.org now redirects to lnreader.org, so the existing parser no longer works. The site layout is otherwise completely the same, so hopefully it should be an easy fix?

**Comment by dteviot** [comment]
@elpsycongruent 

Fix provided by @ImLJS 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment]
@elpsycongruent 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
