### ISSUE TITLE
more than 1 option removeCSS in custom Parser

### ISSUE THREAD

**Issue by k4noe** [dteviot/WebToEpub#988]
is it possible to add more than one option 'CSS selector for element(s) to remove: ' , maybe separated by comma or semi colon ?

![Clipboard Image](https://github.com/dteviot/WebToEpub/assets/16418804/808e330d-ca08-421d-bd94-ff87e255f57c)

Thanks

**Comment by dteviot** [comment]
@k4noe 

You can use a comma exactly as you describe.  https://www.thoughtco.com/comma-in-css-selectors-3467052

**Comment by dteviot** [comment]
The problem may be the spaces.  I suggest leaving them out.
