### ISSUE TITLE
A solution to network error 403, cloudflare

### ISSUE THREAD

**Issue by zeoint** [dteviot/WebToEpub#991]
**Is your feature request related to a problem? Please describe.**

- Everytime I try to pack an epub from [Lightnovelworld](https://www.lightnovelworld.com) that have 1000+ chapters, cloudflare of the site activates and webtoepub throws 'failed with network error 403' and saves the epub with the chapters that were downloaded before cloudflare is thrown.

**Describe the solution you'd like**

- When a cloudflare is thrown, pause the download, after solving the captcha by the user, resume the download.
- The problem will be solved.

**Describe alternatives you've considered**

- [Comment](https://github.com/dteviot/WebToEpub/issues/991#issuecomment-1595573447)

**Additional context**

**Comment by gamebeaker** [comment]
@zeoint You could try to fetch the Chapter slower. Link to wiki [Manual Throttle|Delay per chapter](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#manual-throttledelay-per-chapter).

**Comment by dteviot** [comment]
@zeoint 

I've made a quick hack to the code so it **should** now ask if you want to retry when a 403 error is returned by the server.
**Warning: This is completely untested.  I'm not set up to easily test 403 errors.**

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. 

**Note, the file(s) you want are the ones labelled "403.experimental".  NOT the WebToEpub ones.**

Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

For my notes: 67 minutes work

**Comment by dteviot** [comment]
@zeoint 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
