### ISSUE TITLE
Kakao

### ISSUE THREAD

**Issue by courli79** [dteviot/WebToEpub#992]
@Synteresis
@dteviot

403 error with WevToEpub while logged in.
Fetch of URL 'https://page.kakao.com/api/login' failed with network error 403. onResponseError@moz-extension://a4da0363-e35f-4bdd-8d9d-8ed79c139c94/js/HttpClient.js:32:25
checkResponseAndGetData@moz-extension://a4da0363-e35f-4bdd-8d9d-8ed79c139c94/js/HttpClient.js:166:45

403 error with WevToEpub while logged in.
It seems that they are still changing their site or maybe they have added protection?
 - request the cookie response to accept the request?
 - domain of origin?
 - age... ?
 
![001](https://github.com/dteviot/WebToEpub/assets/82915245/8727541a-2dec-4d90-b013-c75821866729)

![002](https://github.com/dteviot/WebToEpub/assets/82915245/98503a82-da04-43ee-9a3f-5bd2841a0e19)

![003](https://github.com/dteviot/WebToEpub/assets/82915245/a52166ca-d480-496e-9b85-aaee2b27fde1)

**Comment by dteviot** [comment]
@courli79

I'm not sure what they've done to their site.Trying to go to https://kakao.com/ takes me to https://www.kakaocorp.com/page/ and I don't know Korean.

**Comment by courli79** [comment]
> @courli79
> 
> I'm not sure what they've done to their site.Trying to go to https://kakao.com/ takes me to https://www.kakaocorp.com/page/

**Comment by courli79** [comment]
> and I don't know Korean.

I don't read Korean either. I read your other posts about Kakao.
I'm posting the problem in case someone else finds the solution.

**Comment by itsgraxiabibi** [comment]
Hi dteviot! Sorry for barging in in the conversation but I just want to check if there's been changes on the webtoepub as the https://pagestage.kakao.com/ site is no longer "rippable". It was definitely working before (last year I think) but now, we're getting errors like this:

Error: No chapters found.
    at KakaoParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:456:35)
    at KakaoParser.fetchContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:442:21)
    at HTMLButtonElement.fetchContentAndPackEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:153:16)
    
    Im not sure if this is just one of those instances where Kakao developers wisened up and tightened security or Im doing something wrong.

**Comment by dteviot** [comment]
@itsgraxiabibi @courli79 

This is a Korean site, so I don't know what is happening.  Looking at the HTTP, I **suspect** something has changed with the Logon/Authentication process.
Anyway, I disabled that part and it seems to have worked for a couple of novels I picked at random of the front page

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://pagestage.kakao.com/novels/13754472
* https://pagestage.kakao.com/novels/83262280

For my notes:  36 minutes work

**Comment by itsgraxiabibi** [comment]
Thank you! It works now! If you have any patreon or kofi, I'd love to chip in!  I know this was extra work and I appreciate you checking out my concern. I tried looking around if you have kofi or patreon on github or on the google extention page but I cant seem to find it.

**Comment by dteviot** [comment]
@itsgraxiabibi 
>  I tried looking around if you have kofi or patreon on github or on the google extention page but I cant seem to find it.

That's because I don't have one.  (Reasons are complicated, but due to New Zealand copywrite and Tax laws)
But it's nice to be thanked.  Gives me a warm feeling.
If you really want, I suggest donating to the sites you like, or their authors.  Failing that, Mozilla would be good.

**Comment by courli79** [comment]
Hello, I also tested it works for me too. THANK YOU !!!

**Comment by dteviot** [comment]
@itsgraxiabibi @courli79 

Going to call this done.

Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
