### ISSUE TITLE
Please add site https://ncode.syosetu.com 

### ISSUE THREAD

**Issue by sorata225** [dteviot/WebToEpub#993]
I tried parsing the web novel for kuma kuma in this link: https://ncode.syosetu.com/n4185ci
It did not work:( It should have; given that it is the content page and has the links to main story and preface. I also tried with links to the first page of main story. The parser was showing no. of chapters as 1 probably. 

I am also aware that there is a default parser. But my inadequate knowledge of CSS/ HTML probably could not keep up with that(actually no knowledge is a better phrasing).

Edit: I have attached the ss which shows the error I get when trying to parse the page. 
![IMG_20230618_160152](https://github.com/dteviot/WebToEpub/assets/136738526/e5823668-9c01-4043-9972-5174ce989842)
![IMG_20230618_160253](https://github.com/dteviot/WebToEpub/assets/136738526/e03b34e7-1490-44b3-a185-3f659b24da37)

**Comment by ImLJS** [comment]
You are opening webtoepub extension from chapter 1, so it will not work.

Open it from table of contents, [https://ncode.syosetu.com/n4185ci](https://ncode.syosetu.com/n4185ci) from here

**Comment by sorata225** [comment]
> You are opening webtoepub extension from chapter 1, so it will not work.
> 
> Open it from table of contents, https://ncode.syosetu.com/n4185ci from here

Thank you for your effort to help. Actually I tried with the link you mentioned. I believe there was some confusion and errors in my post. I've updated it now. The thing is I tried the default parser, but I could not find the relevant CSS markers. If you have the time could you look into that? Thanks again.

**Comment by ImLJS** [comment]
do you want to edit the css of the packed epub?

**Comment by sorata225** [comment]
> do you want to edit the css of the packed epub?
I do not want to edit the packed epub. 
The thing is "pack epub" does not workkin syosetsu. That is the problem. So I tried the default parser. But as I'm no dev; I don't know what to put in in these three:

<b>(required) CSS selector for element holding content to put into EPUB:</b>[This one had body in it by default but in this case the epub includes many irrelevant content]

<b>CSS selector for element holding Title of Chapter:</b>

<b>CSS selector for element(s) to remove:</b>

**Comment by ImLJS** [comment]
By using [https://ncode.syosetu.com/n4185ci](https://ncode.syosetu.com/n4185ci), the chapters are getting detected. See Below

<img width="652" alt="Screenshot 2023-06-18 182620" src="https://github.com/dteviot/WebToEpub/assets/109210868/58607f75-5fb0-4511-ae30-7a362d381034">

Are you using webtoepub extension in mobile or try to update the extension.

If that does not work, try following this steps https://github.com/dteviot/WebToEpub#how-to-install-from-source-for-people-who-are-not-developers

**Comment by sorata225** [comment]
I now tried everything you mentioned including the steps here:
https://github.com/dteviot/WebToEpub#how-to-install-from-source-for-people-who-are-not-developers

I also tried changing browsers(from kiwi to firefox). Sadly, nothing seems to work. Except the default parser which I tested with the field <b>"(required) CSS selector for element holding content to put into EPUB:"</b> set to body. In the meantime I tried parsing this page:
https://www.baka-tsuki.org/project/index.php?title=Nogizaka_Haruka_no_Himitsu:Volume1_Epilogue

And it worked this time. So I think this problem is specific to syosetsu as I tried parsing re:zero and others. But for some reason I cannot parse the syosetsu website.

>Are you using webtoepub extension in mobile 

Yes, on android. I do not own a PC. I'm only a teenager.

**Comment by ImLJS** [comment]
Since you are using it on mobile, webtoepub may not work for some sites.

One such workaround is to turn on desktop mode in mobile browser then use webtoepub extension on the site.

**Comment by dteviot** [comment]
@sorata225 @ImLJS 

I checked, the Mobile and Desktop versions of the site are different.  WebToEpub will work, if you open the site in Desktop mode.  Failing that, if you want to use the default parser, I **think** the following will work:

* ** CSS selector for element holding content to put into EPUB:** div#novel_honbun
* **CSS selector for element holding Title of Chapter:** div.novel_subtitle
* ** CSS selector for element(s) to remove:**  leave blank

**Comment by sorata225** [comment]
@ImLJS @dteviot  Thank you both of you for your immense help. Yes, it worked now with the desktop version of the site. It was stupid of me to not try with the desktop version to begin with. I think this information should have been in the github page. Particularly in the section with instructions for non devs. Thanks again.

**Comment by sorata225** [comment]
@gamebeaker Oh I have not read that. But it still should have been mentioned in the main <code>page. The section on "how to use on android" does not mention this. Given that this section exists on the readme.md, it is natural to assume this is all of the points to know for using on android.
