### ISSUE TITLE
Gibberish Content bypass

### ISSUE THREAD

**Issue by Seraphine-12** [dteviot/WebToEpub#996]
I LOVEEEEEEEE the new feature password to bypass passcoded chapters, especially chrysanthemumgarden. However, can I ask if you can do something about the text having gibberish content when turned into epub? 

in phyroid3  using lncrawl, it bypassed that gibberish content however, this extension did not bypass it. Maybe you can do anything about this? ToT

**Comment by Seraphine-12** [comment]
Thank u so much💕

**Comment by dteviot** [comment]
@Seraphine-12 
I'm going to assume this solved your problem and close the issue.  If I'm wrong, add a comment to this issue and I'll reopen.
