### ISSUE TITLE
Sites like freewebnovel.com is now asking to slow down webtoepub which greatly add parsing time.

### ISSUE THREAD

**Issue by zicodm** [dteviot/WebToEpub#997]
Can you please a fix to this? I've only used freewebnovel.com but I hope it doesn't spread to other sites as well.

**Comment by zicodm** [comment]
![Uploading Screenshot_2023-06-23-15-23-30-082_com.tokopedia.tkpd~2.jpg…]()

**Comment by dteviot** [comment]
@zicodm 
There's no screenshot, you just need to copy/paste it into GitHub.

**Comment by dteviot** [comment]
@zicodm 
I don't understand the problem.
If site is asking WebToEpub to slow down, then things will take longer.
Not slowing down WebToEpub can result in you IP Address being blocked.

**Comment by zicodm** [comment]
I understand your point, indeed. I also use it occasionally, perhaps once a month. However, I have a feeling that today the site's parsing time will slow down, and tomorrow it might even block the parsing support. I guess it's inevitable. Thanks for your replies; I sincerely appreciate it

**Comment by gamebeaker** [comment]
@zicodm you could try to limit your request per second. A lot of websites slow you down if you request too many pages per second. Example: You request 10 pages a second -> website says slow down and wait 5min before next request -> WebToEpub resumes after 5min. If you slow down you requests like 1 Page per 3 seconds -> 20 Pages per minute most websites don't complain and it is much faster (10 pages in 5min vs. 100 pages in 5min). You can read here how to do it: [https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#manual-throttledelay-per-chapter](https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#manual-throttledelay-per-chapter)

**Comment by Flwk** [comment]
There are more and more site that limite the parsing now.


Before,  freewebnovel wasn't like that.

**Comment by zicodm** [comment]
My biggest fear has already arrived. My go to site which is freewebnovel.com (innread.com now) and novelfull.net already block the support. It was fun while it lasted haha

**Comment by zicodm** [comment]
Does the regular manually adding parsing support works? They already block the automatic parsing, I don't want to kinda wasting time manually adding them
